-- Kentucky reentry resources for Reentry to Recovery
-- Generated from src/lib/kentucky/*.ts
-- Run after: supabase/migrations/001_initial_schema.sql
--            supabase/migrations/002_add_description_es.sql
-- Optional reset first: supabase/reset-data.sql
-- Regenerate: npx tsx scripts/generate-kentucky-seed.ts

INSERT INTO categories (id, name, slug, description, icon, sort_order, is_active) VALUES
  ('c1000001-0001-4000-8000-000000000001', 'State Agency', 'state-agency', 'Kentucky state government reentry programs and services', 'shield', 1, true),
  ('c1000001-0002-4000-8000-000000000001', 'Housing', 'housing', 'Transitional housing, recovery housing, and shelter for people leaving incarceration', 'home', 2, true),
  ('c1000001-0003-4000-8000-000000000001', 'Employment', 'employment', 'Job training, placement, and fair-chance employment for justice-involved Kentuckians', 'briefcase', 3, true),
  ('c1000001-0004-4000-8000-000000000001', 'Healthcare', 'healthcare', 'Medical care, mental health, and recovery navigation', 'heart-pulse', 4, true),
  ('c1000001-0005-4000-8000-000000000001', 'Substance Use Treatment', 'substance-use-treatment', 'Addiction treatment and recovery housing for justice-involved individuals', 'shield', 5, true),
  ('c1000001-0006-4000-8000-000000000001', 'Legal Aid', 'legal-aid', 'Expungement, civil legal help, and record relief', 'scale', 6, true),
  ('c1000001-0007-4000-8000-000000000001', 'Food & Nutrition', 'food-nutrition', 'Food assistance and nutrition programs', 'utensils', 7, true),
  ('c1000001-0008-4000-8000-000000000001', 'ID & Documentation', 'id-documentation', 'Birth certificates, IDs, and vital records assistance', 'id-card', 8, true),
  ('c1000001-0009-4000-8000-000000000001', 'Financial Assistance', 'financial-assistance', 'Benefits, emergency funds, and financial coaching', 'dollar-sign', 9, true),
  ('c1000001-0010-4000-8000-000000000001', 'Transportation', 'transportation', 'Transit passes and transportation to appointments and work', 'bus', 10, true),
  ('c1000001-0011-4000-8000-000000000001', 'Family & Children', 'family-children', 'Family reunification and support for loved ones of incarcerated people', 'users', 11, true),
  ('c1000001-0012-4000-8000-000000000001', 'Peer Support', 'peer-support', 'Peer mentors and recovery community support', 'handshake', 12, true),
  ('c1000001-0013-4000-8000-000000000001', 'Education', 'education', 'GED, job training, and credential programs during reentry', 'graduation-cap', 13, true),
  ('c1000001-0014-4000-8000-000000000001', 'Veterans', 'veterans', 'Reentry services for justice-involved veterans', 'medal', 14, true),
  ('c1000001-0015-4000-8000-000000000001', 'Basic Needs', 'basic-needs', 'Clothing, hygiene, and essential items at release', 'handshake', 15, true),
  ('c1000001-0016-4000-8000-000000000001', 'Probation & Parole', 'probation-parole', 'Community supervision and DOC contracted reentry centers', 'scale', 16, true),
  ('c1000001-0017-4000-8000-000000000001', 'Reentry Organizations', 'reentry-organizations', 'Nonprofit reentry coalitions and community-based reentry programs', 'handshake', 17, true)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order,
  is_active = EXCLUDED.is_active;

INSERT INTO resources (
  id, name, description, description_es, category_id,
  state, county, city, address, phone, website, email, hours, eligibility,
  services, tags, is_featured, status
) VALUES
  (
    'b1000001-0001-4000-8000-000000000001',
    'Kentucky DOC Division of Reentry Services',
    'The Kentucky Department of Corrections Division of Reentry Services helps people who are incarcerated or under supervision prepare for successful return to the community. Staff develop individualized reentry plans, connect individuals and families to community resources, and coordinate evidence-based programming focused on life skills, employment readiness, and prosocial behavior. The division partners with local agencies across all 120 counties to address common barriers such as housing, employment, treatment, and transportation. Reentry coordinators are assigned by region to assist with questions about programs, referrals, and community resources before and after release.',
    'La División de Servicios de Reintegración del Departamento de Correcciones de Kentucky ayuda a las personas encarceladas o bajo supervisión a prepararse para un regreso exitoso a la comunidad. El personal elabora planes de reintegración individualizados, conecta a las personas y familias con recursos comunitarios y coordina programas basados en evidencia enfocados en habilidades para la vida, preparación laboral y conducta prosocial. La división colabora con agencias locales en los 120 condados para abordar barreras comunes como vivienda, empleo, tratamiento y transporte. Los coordinadores de reintegración están asignados por región para ayudar con preguntas sobre programas, referidos y recursos comunitarios antes y después de la liberación.',
    'c1000001-0001-4000-8000-000000000001',
    'Kentucky',
    'Franklin',
    'Frankfort',
    NULL,
    '502-782-2347',
    'https://corrections.ky.gov/Reentry',
    NULL,
    'Monday–Friday, 8 a.m.–4:30 p.m.',
    'Justice-involved individuals in Kentucky DOC custody or under DOC community supervision, and their families seeking reentry planning support.',
    ARRAY['Individualized reentry planning', 'Regional reentry coordinator referrals', 'Community partnership navigation', 'Pre-release programming coordination', 'Family support and guidance'],
    ARRAY['statewide', 'reentry', 'DOC', 'probation', 'parole', 'frankfort'],
    true,
    'active'
  ),
  (
    'b1000001-0002-4000-8000-000000000001',
    'Kentucky DOC Reentry Service Centers Program',
    'The Kentucky Department of Corrections Reentry Service Center (RSC) program, overseen by the Division of Probation and Parole, provides contracted residential reentry for state inmates, parolees, and probationers who are transitioning back to the community. RSCs offer housing, structured programming, vocational training, educational opportunities, cognitive behavioral programming, and substance use treatment at select locations. Participants typically enter near parole eligibility after obtaining community custody status. The program helps individuals reconnect with family, seek employment, and build skills before completing incarceration or supervision.',
    'El programa de Centros de Servicios de Reintegración (RSC) del Departamento de Correcciones de Kentucky, supervisado por la División de Libertad Condicional y Libertad Vigilada, ofrece reintegración residencial contratada para reclusos estatales, personas en libertad condicional y libertad vigilada que regresan a la comunidad. Los RSC ofrecen vivienda, programación estructurada, capacitación vocacional, oportunidades educativas, programación cognitivo-conductual y tratamiento de uso de sustancias en ubicaciones selectas. Los participantes suelen ingresar cerca de la elegibilidad para libertad condicional después de obtener custodia comunitaria. El programa ayuda a reconectarse con la familia, buscar empleo y desarrollar habilidades antes de completar el encarcelamiento o la supervisión.',
    'c1000001-0016-4000-8000-000000000001',
    'Kentucky',
    NULL,
    NULL,
    NULL,
    '502-564-7023',
    'https://corrections.ky.gov/Facilities/halfway-houses/Pages/reentryservicecenters.aspx',
    NULL,
    'Monday–Friday, 8 a.m.–4:30 p.m.',
    'Kentucky DOC inmates with community custody status near parole eligibility, and eligible parolees and probationers referred through Probation and Parole.',
    ARRAY['Transitional residential placement', 'Vocational training', 'Educational programming', 'Cognitive behavioral programming', 'Substance use treatment (select sites)', 'Employment preparation'],
    ARRAY['statewide', 'RSC', 'probation', 'parole', 'halfway house', 'DOC'],
    false,
    'active'
  ),
  (
    'b1000001-0003-4000-8000-000000000001',
    'Louisville Urban League — Reily Reentry Project',
    'The Reily Reentry Project at the Louisville Urban League helps justice-involved individuals in Jefferson County remove barriers caused by criminal records. The program facilitates Kentucky expungement for eligible convictions, covers most court and filing fees when approved, and connects participants to holistic Urban League services such as job coaching, health navigation, and financial counseling. Participants complete a needs assessment with a Community Health Navigator and may enroll in additional League programs to support long-term stability. Expungement clinics and record review determine legal eligibility before appointments are scheduled.',
    'El Proyecto Reily de Reintegración de la Liga Urbana de Louisville ayuda a personas con antecedentes de justicia en el condado de Jefferson a eliminar barreras causadas por registros penales. El programa facilita la eliminación de antecedentes de Kentucky para condenas elegibles, cubre la mayoría de las tarifas judiciales y de presentación cuando se aprueba, y conecta a los participantes con servicios integrales de la Liga como orientación laboral, navegación de salud y asesoría financiera. Los participantes completan una evaluación de necesidades con un Navegador de Salud Comunitaria y pueden inscribirse en programas adicionales de la Liga para apoyar la estabilidad a largo plazo. Las clínicas de eliminación de antecedentes y la revisión de registros determinan la elegibilidad legal antes de programar citas.',
    'c1000001-0006-4000-8000-000000000001',
    'Kentucky',
    'Jefferson',
    'Louisville',
    '1535 West Broadway',
    '502-585-4622',
    'https://lul.org/justice/reily-reentry-project/',
    NULL,
    'Monday–Friday, 9:30 a.m.–4 p.m.',
    'Individuals with Jefferson County convictions who are legally eligible for expungement under Kentucky law and agree to participate in League support services.',
    ARRAY['Criminal record review', 'Expungement filing assistance', 'Court fee assistance', 'Community Health Navigator assessment', 'Job coaching referrals', 'Financial counseling referrals'],
    ARRAY['louisville', 'jefferson county', 'expungement', 'legal aid', 'reentry'],
    true,
    'active'
  ),
  (
    'b1000001-0004-4000-8000-000000000001',
    'Legal Aid Society — Louisville',
    'The Legal Aid Society provides free civil legal help to low-income residents of the Louisville region, including criminal record expungement for eligible Kentucky charges. Attorneys and staff assist with expungement petitions, housing issues, public benefits, family matters, and consumer problems that create barriers after release. Intake is required to determine eligibility based on income and legal issue type. Legal Aid does not represent clients in active criminal cases but helps remove civil legal barriers that block employment and housing for justice-involved individuals.',
    'La Sociedad de Asistencia Legal ofrece ayuda legal civil gratuita a residentes de bajos ingresos de la región de Louisville, incluida la eliminación de antecedentes penales para cargos elegibles de Kentucky. Abogados y personal ayudan con peticiones de eliminación de antecedentes, problemas de vivienda, beneficios públicos, asuntos familiares y problemas de consumo que crean barreras después de la liberación. Se requiere admisión para determinar la elegibilidad según ingresos y tipo de problema legal. La Asistencia Legal no representa clientes en casos penales activos, pero ayuda a eliminar barreras legales civiles que bloquean el empleo y la vivienda para personas con antecedentes de justicia.',
    'c1000001-0006-4000-8000-000000000001',
    'Kentucky',
    'Jefferson',
    'Louisville',
    '416 W. Muhammad Ali Blvd., Suite 300',
    '502-584-1254',
    'https://yourlegalaid.org',
    NULL,
    'Intake Monday–Thursday, 10 a.m.–4 p.m.; office Monday–Friday, 9 a.m.–5 p.m.',
    'Low-income individuals at or below 125% of the federal poverty guideline in Jefferson, Bullitt, Hardin, Oldham, Shelby, Spencer, and other served counties with civil legal needs including eligible expungements.',
    ARRAY['Criminal record expungement', 'Housing legal assistance', 'Public benefits advocacy', 'Family law assistance', 'Consumer legal help', 'Online and phone intake'],
    ARRAY['louisville', 'jefferson county', 'expungement', 'legal aid', 'civil legal'],
    false,
    'active'
  ),
  (
    'b1000001-0005-4000-8000-000000000001',
    'Legal Aid of the Bluegrass',
    'Legal Aid of the Bluegrass (LABG) provides free civil legal representation to low-income Kentuckians across Central, Northern, and Eastern Kentucky, including criminal record expungement to remove employment and housing barriers. Staff partner with Goodwill of Kentucky for expungement clinics and help eligible clients file petitions at no cost when they qualify. LABG also assists with housing, public benefits, family safety, and consumer issues. Multiple regional offices serve Fayette, Kenton, Boyd, and surrounding counties through phone intake and online applications.',
    'Legal Aid of the Bluegrass (LABG) brinda representación legal civil gratuita a habitantes de bajos ingresos de Kentucky en las regiones Central, del Norte y del Este, incluida la eliminación de antecedentes penales para quitar barreras de empleo y vivienda. El personal colabora con Goodwill of Kentucky en clínicas de eliminación de antecedentes y ayuda a clientes elegibles a presentar peticiones sin costo cuando califican. LABG también asiste con vivienda, beneficios públicos, seguridad familiar y problemas de consumo. Varias oficinas regionales atienden Fayette, Kenton, Boyd y condados circundantes mediante admisión telefónica y solicitudes en línea.',
    'c1000001-0006-4000-8000-000000000001',
    'Kentucky',
    'Fayette',
    'Lexington',
    '300 E. Main Street, Suite 210',
    '859-431-8200',
    'https://lablaw.org',
    'legalaid@lablaw.org',
    'Office Monday–Friday, 8:30 a.m.–4:30 p.m.; intake Monday–Thursday, 10 a.m.–3 p.m. and Friday, 10 a.m.–1 p.m.',
    'Low-income individuals in LABG''s 33-county service area with civil legal needs, including eligible Kentucky criminal record expungements.',
    ARRAY['Criminal record expungement', 'Housing legal help', 'Public benefits assistance', 'Family law services', 'Consumer advocacy', 'Online application intake'],
    ARRAY['lexington', 'fayette county', 'northern kentucky', 'eastern kentucky', 'expungement', 'statewide'],
    false,
    'active'
  ),
  (
    'b1000001-0006-4000-8000-000000000001',
    'Kentucky Career Center — Louisville (KentuckianaWorks)',
    'The Kentucky Career Center on Broadway, operated through KentuckianaWorks, offers free career services to job seekers in Louisville and Jefferson County, including people recently released from incarceration. Career specialists provide resume help, interview coaching, job search assistance, GED referrals, and connections to training scholarships when available. The center explicitly serves justice-involved job seekers and connects them to quality employers. Services are available at the Goodwill Opportunity Campus and include workshops on LinkedIn, interviewing, and career planning.',
    'El Kentucky Career Center en Broadway, operado a través de KentuckianaWorks, ofrece servicios profesionales gratuitos a quienes buscan empleo en Louisville y el condado de Jefferson, incluidas personas recién liberadas del encarcelamiento. Los especialistas en carreras brindan ayuda con currículums, coaching de entrevistas, asistencia en búsqueda de empleo, referidos de GED y conexiones a becas de capacitación cuando están disponibles. El centro atiende explícitamente a quienes buscan empleo con antecedentes de justicia y los conecta con empleadores de calidad. Los servicios están disponibles en el Goodwill Opportunity Campus e incluyen talleres sobre LinkedIn, entrevistas y planificación de carrera.',
    'c1000001-0003-4000-8000-000000000001',
    'Kentucky',
    'Jefferson',
    'Louisville',
    '2820 W Broadway, Suite 100',
    '502-388-3010',
    'https://www.kentuckianaworks.org/kcclou',
    NULL,
    'Monday–Friday, 8:30 a.m.–5 p.m.',
    'Open to all job seekers in the Louisville/Jefferson County area, including justice-involved individuals seeking employment and training support.',
    ARRAY['Resume and cover letter help', 'Interview coaching', 'Job search assistance', 'Career planning workshops', 'GED referrals', 'Training scholarship information', 'Employer connections'],
    ARRAY['louisville', 'jefferson county', 'employment', 'second chance', 'career center'],
    true,
    'active'
  ),
  (
    'b1000001-0007-4000-8000-000000000001',
    'Kentucky Career Center — Northern Kentucky',
    'The Kentucky Career Center in Covington connects Northern Kentucky job seekers—including individuals in recovery and those with criminal records—to career coaching, job training, paid internships, and placement assistance. The center hosts partner organizations onsite such as Brighton Center, Gateway Community and Technical College, and Northern Kentucky Community Action Commission. Specialists offer resume building, mock interviews, and referrals to wrap-around supports including transportation and childcare. Reentry-focused career services are highlighted in regional recovery and workforce materials.',
    'El Kentucky Career Center en Covington conecta a quienes buscan empleo en el Norte de Kentucky—incluidas personas en recuperación y con antecedentes penales—con orientación profesional, capacitación laboral, pasantías pagadas y asistencia de colocación. El centro alberga organizaciones asociadas como Brighton Center, Gateway Community and Technical College y Northern Kentucky Community Action Commission. Los especialistas ofrecen elaboración de currículums, entrevistas simuladas y referidos a apoyos integrales incluyendo transporte y cuidado infantil. Los servicios de carrera enfocados en reintegración se destacan en materiales regionales de recuperación y fuerza laboral.',
    'c1000001-0003-4000-8000-000000000001',
    'Kentucky',
    'Kenton',
    'Covington',
    '1324 Madison Avenue',
    '859-292-6666',
    'https://www.nkcareercenter.org',
    NULL,
    'Monday–Friday, 8 a.m.–4:30 p.m.',
    'Job seekers in Northern Kentucky, including individuals in reentry and recovery seeking employment and training services.',
    ARRAY['Career coaching', 'Job training referrals', 'Paid internships', 'Job placement assistance', 'Resume and interview support', 'Partner agency referrals', 'Hiring events and job fairs'],
    ARRAY['northern kentucky', 'covington', 'kenton county', 'employment', 'reentry', 'recovery'],
    false,
    'active'
  ),
  (
    'b1000001-0008-4000-8000-000000000001',
    'Center for Employment Opportunities — Louisville',
    'The Center for Employment Opportunities (CEO) Louisville provides immediate, comprehensive employment services exclusively for people who have recently been released from incarceration. CEO offers paid transitional work experience, job coaching, placement with fair-chance employers, and retention support to reduce recidivism. The Louisville office partners with Kentucky DOC and local employers to connect participants to stable jobs quickly after release. CEO is a national evidence-based reentry employment provider with a dedicated Louisville location serving the metro area.',
    'Center for Employment Opportunities (CEO) Louisville ofrece servicios de empleo inmediatos e integrales exclusivamente para personas recién liberadas del encarcelamiento. CEO ofrece experiencia laboral transicional remunerada, orientación laboral, colocación con empleadores de segunda oportunidad y apoyo de retención para reducir la reincidencia. La oficina de Louisville colabora con el DOC de Kentucky y empleadores locales para conectar a los participantes con empleos estables rápidamente después de la liberación. CEO es un proveedor nacional de empleo de reintegración basado en evidencia con una ubicación dedicada en Louisville que sirve al área metropolitana.',
    'c1000001-0003-4000-8000-000000000001',
    'Kentucky',
    'Jefferson',
    'Louisville',
    '321 Guthrie Street',
    '502-694-7878',
    'https://www.ceoworks.org/locations/louisville',
    NULL,
    'Monday–Friday, 8 a.m.–5 p.m.',
    'Adults who have been released from incarceration within the past year (or meet CEO enrollment criteria) and live in the Louisville service area.',
    ARRAY['Paid transitional work', 'Job placement', 'Career coaching', 'Retention support', 'Employer partnerships', 'Life skills support'],
    ARRAY['louisville', 'jefferson county', 'employment', 'reentry', 'CEO', 'second chance'],
    true,
    'active'
  ),
  (
    'b1000001-0009-4000-8000-000000000001',
    'Goodwill Kentucky — RISE Program (Lexington)',
    'Goodwill of Kentucky''s RISE (Reintegrating Individuals Successfully Every Day) program provides employment services tailored to justice-involved job seekers in Lexington and Fayette County. Career coaches help participants overcome barriers to work, connect to training and employer partners, and build stability after release. RISE expanded from Louisville to Lexington, Bowling Green, and Pikeville to serve more Kentuckians with criminal backgrounds. The Lexington RISE team can be reached directly for enrollment and referrals.',
    'El programa RISE (Reintegrating Individuals Successfully Every Day) de Goodwill of Kentucky ofrece servicios de empleo adaptados a quienes buscan trabajo con antecedentes de justicia en Lexington y el condado de Fayette. Los coaches de carrera ayudan a los participantes a superar barreras laborales, conectarse con capacitación y empleadores asociados, y construir estabilidad después de la liberación. RISE se expandió de Louisville a Lexington, Bowling Green y Pikeville para atender a más habitantes de Kentucky con antecedentes penales. El equipo RISE de Lexington puede contactarse directamente para inscripción y referidos.',
    'c1000001-0003-4000-8000-000000000001',
    'Kentucky',
    'Fayette',
    'Lexington',
    '130 West New Circle Rd., Suite 110',
    '859-806-7956',
    'https://goodwillky.org/rise-program-now-offering-services-in-lexington-bowling-green-pikeville/',
    NULL,
    'Monday–Friday, 8 a.m.–4:30 p.m.',
    'Justice-involved individuals in the Lexington/Fayette County area seeking employment support through Goodwill Kentucky.',
    ARRAY['Employment coaching', 'Job placement assistance', 'Barrier removal support', 'Training referrals', 'Employer partner connections'],
    ARRAY['lexington', 'fayette county', 'employment', 'RISE', 'goodwill', 'second chance'],
    false,
    'active'
  ),
  (
    'b1000001-0010-4000-8000-000000000001',
    'Goodwill Kentucky — LifeLaunch: Ignite 2.0 (Lexington)',
    'Goodwill LifeLaunch: Ignite 2.0 is a reentry program for young adults ages 18–24 in Fayette County with current or prior justice involvement. Participants work with career coaches on a personalized pathway that includes job readiness training, enrollment in career credentials through Bluegrass Community and Technical College, and paid work experience with employer partners. The program addresses barriers such as transportation, housing, food insecurity, substance use, and mental health while promoting education and employment to reduce recidivism.',
    'Goodwill LifeLaunch: Ignite 2.0 es un programa de reintegración para jóvenes de 18 a 24 años en el condado de Fayette con participación actual o previa en el sistema de justicia. Los participantes trabajan con coaches de carrera en una ruta personalizada que incluye capacitación de preparación laboral, inscripción en credenciales profesionales a través de Bluegrass Community and Technical College y experiencia laboral remunerada con empleadores asociados. El programa aborda barreras como transporte, vivienda, inseguridad alimentaria, uso de sustancias y salud mental mientras promueve la educación y el empleo para reducir la reincidencia.',
    'c1000001-0013-4000-8000-000000000001',
    'Kentucky',
    'Fayette',
    'Lexington',
    '130 West New Circle Rd., Suite 110',
    '859-277-3661',
    'https://goodwillky.org/ignitelex/',
    NULL,
    'Monday–Friday, 8 a.m.–4:30 p.m.',
    'Young adults ages 18–24 in Fayette County with prior or current justice involvement willing to enroll in training and work pathways.',
    ARRAY['Career coaching', 'Job readiness training', 'BCTC credential pathways', 'Work and learn placements', 'Barrier reduction support', 'Online referral intake'],
    ARRAY['lexington', 'fayette county', 'young adults', 'education', 'employment', 'reentry'],
    false,
    'active'
  ),
  (
    'b1000001-0011-4000-8000-000000000001',
    'Dismas Charities — Louisville Reentry Center',
    'Dismas Charities operates a residential reentry center in Louisville for men and women transitioning from incarceration back into the community. As a Kentucky DOC-contracted Reentry Service Center provider, Dismas offers structured housing, case management, education, employment support, and family reunification services. The organization has served justice-involved individuals since 1964 with a mission of healing and community reintegration. Programming prepares residents for employment and stable community living before and during community supervision.',
    'Dismas Charities opera un centro de reintegración residencial en Louisville para hombres y mujeres que hacen la transición del encarcelamiento de regreso a la comunidad. Como proveedor contratado del DOC de Kentucky de Centros de Servicios de Reintegración, Dismas ofrece vivienda estructurada, gestión de casos, educación, apoyo laboral y servicios de reunificación familiar. La organización ha servido a personas con antecedentes de justicia desde 1964 con la misión de sanación y reintegración comunitaria. La programación prepara a los residentes para el empleo y una vida comunitaria estable antes y durante la supervisión comunitaria.',
    'c1000001-0002-4000-8000-000000000001',
    'Kentucky',
    'Jefferson',
    'Louisville',
    '124 West Oak Street',
    '502-634-3608',
    'https://www.dismas.com',
    NULL,
    'Contact facility for visiting and admission hours',
    'Kentucky DOC inmates, parolees, and probationers referred to a Reentry Service Center through the Department of Corrections.',
    ARRAY['Transitional housing', 'Case management', 'Education programs', 'Employment support', 'Family reunification', 'Life skills programming'],
    ARRAY['louisville', 'jefferson county', 'RSC', 'housing', 'reentry', 'DOC'],
    false,
    'active'
  ),
  (
    'b1000001-0012-4000-8000-000000000001',
    'Life Learning Center',
    'Life Learning Center in Covington is a nonprofit reentry and workforce program serving Northern Kentucky, including Kenton County Detention Center partners and justice-involved adults. Their transformational change model provides life skills education, career preparation, recovery supports, and basic essentials for people released from jail with felony or misdemeanor histories. Approximately 93% of participants have criminal convictions. Graduates receive help securing employment, and the center hosts regional reentry resource events with dozens of community partners.',
    'Life Learning Center en Covington es un programa sin fines de lucro de reintegración y fuerza laboral que sirve al Norte de Kentucky, incluidos socios del Centro de Detención del condado de Kenton y adultos con antecedentes de justicia. Su modelo de cambio transformacional ofrece educación en habilidades para la vida, preparación profesional, apoyos de recuperación y artículos básicos para personas liberadas de la cárcel con antecedentes penales por delitos graves o menores. Aproximadamente el 93% de los participantes tienen condenas penales. Los graduados reciben ayuda para conseguir empleo, y el centro organiza eventos regionales de recursos de reintegración con docenas de socios comunitarios.',
    'c1000001-0017-4000-8000-000000000001',
    'Kentucky',
    'Kenton',
    'Covington',
    '20 West 18th Street',
    '859-431-0100',
    'https://www.lifelearningcenter.us',
    'info@lifelearningcenter.us',
    'Monday–Friday, 8 a.m.–5 p.m.',
    'At-risk and justice-involved adults in Northern Kentucky seeking life skills, career training, and reentry support; program application required.',
    ARRAY['Life skills curriculum', 'Career preparation', 'Recovery support coordination', 'Release essentials and clothing', 'Employment placement help', 'Reentry resource events'],
    ARRAY['northern kentucky', 'covington', 'kenton county', 'reentry', 'workforce', 'recovery'],
    true,
    'active'
  ),
  (
    'b1000001-0013-4000-8000-000000000001',
    'Lexington Second Chance Academy',
    'The Second Chance Academy is a workforce reentry program led by Lexington-Fayette Urban County Government Economic Development in partnership with the Fayette County Detention Center and Jubilee Jobs of Lexington. It serves individuals with six months or less remaining on their sentence through a structured seven-week course focused on life and job skills. After release, participants receive at least one year of individualized support to find and keep employment and successfully transition back into the community.',
    'La Second Chance Academy es un programa de reintegración laboral liderado por el Desarrollo Económico del Gobierno Urbano del Condado Lexington-Fayette en asociación con el Centro de Detención del condado de Fayette y Jubilee Jobs of Lexington. Atiende a personas con seis meses o menos restantes de condena mediante un curso estructurado de siete semanas enfocado en habilidades para la vida y el trabajo. Después de la liberación, los participantes reciben al menos un año de apoyo individualizado para encontrar y mantener empleo y hacer la transición exitosamente de regreso a la comunidad.',
    'c1000001-0013-4000-8000-000000000001',
    'Kentucky',
    'Fayette',
    'Lexington',
    '200 E. Main St.',
    '859-258-3100',
    'https://www.lexingtonky.gov/economic-development/second-chance-academy',
    'katkins@lexingtonky.gov',
    'Monday–Friday, 8 a.m.–5 p.m.',
    'Individuals incarcerated at Fayette County Detention Center with approximately six months or less remaining on their sentence, selected through program partnership.',
    ARRAY['Seven-week reentry course', 'Life skills training', 'Job readiness training', 'Post-release case support (1+ year)', 'Employment retention assistance'],
    ARRAY['lexington', 'fayette county', 'second chance', 'workforce', 'jail reentry'],
    false,
    'active'
  ),
  (
    'b1000001-0014-4000-8000-000000000001',
    'Lexington Rescue Mission — Ex-Offender Re-Entry',
    'Lexington Rescue Mission provides faith-based reentry support for incarcerated and recently released men and women in Central Kentucky. Inside local jails—including Fayette, Woodford, and Madison County detention centers—the Mission offers Genesis Process and Jobs for Life classes. After release, a reentry case manager helps develop transition plans and assists with IDs, transportation, clothing, housing, and employment. Volunteer mentors provide ongoing support, and family support is available through Bluegrass Families of the Incarcerated.',
    'Lexington Rescue Mission brinda apoyo de reintegración basado en la fe para hombres y mujeres encarcelados y recién liberados en el centro de Kentucky. Dentro de las cárceles locales—incluidos los centros de detención de los condados de Fayette, Woodford y Madison—la Misión ofrece clases Genesis Process y Jobs for Life. Después de la liberación, un gestor de casos de reintegración ayuda a desarrollar planes de transición y asiste con identificaciones, transporte, ropa, vivienda y empleo. Mentores voluntarios brindan apoyo continuo, y el apoyo familiar está disponible a través de Bluegrass Families of the Incarcerated.',
    'c1000001-0017-4000-8000-000000000001',
    'Kentucky',
    'Fayette',
    'Lexington',
    NULL,
    '859-785-0979',
    'https://lexingtonrescue.org/services/ex-offender-re-entry/',
    NULL,
    'Contact program staff for appointment times',
    'Incarcerated and recently released individuals participating in Mission jail classes or referred for reentry case management in the Lexington region.',
    ARRAY['In-jail reentry classes', 'Jobs for Life training', 'Genesis Process classes', 'Reentry case management', 'ID and document assistance', 'Housing and employment referrals', 'Family support groups'],
    ARRAY['lexington', 'fayette county', 'madison county', 'woodford county', 'reentry', 'faith-based'],
    false,
    'active'
  ),
  (
    'b1000001-0015-4000-8000-000000000001',
    'Hope Center — SHARE Reentry Program',
    'The Hope Center SHARE (Supportive Housing for Adaptive ReEntry) program in Lexington provides long-term residential recovery services for Kentucky DOC-referred individuals with substance use disorders and serious mental illness. SHARE operates separate tracks for co-occurring disorders and serious mental illness, with male services at Jacob''s House and female services at the Ball-Quantrell Jones Center for Women. Clinical programming combines housing, behavioral health treatment, and peer support to prepare participants for community reintegration.',
    'El programa SHARE (Supportive Housing for Adaptive ReEntry) del Hope Center en Lexington ofrece servicios residenciales de recuperación a largo plazo para personas referidas por el DOC de Kentucky con trastornos por uso de sustancias y enfermedades mentales graves. SHARE opera rutas separadas para trastornos coexistentes y enfermedad mental grave, con servicios para hombres en Jacob''s House y servicios para mujeres en el Ball-Quantrell Jones Center for Women. La programación clínica combina vivienda, tratamiento de salud conductual y apoyo entre pares para preparar a los participantes para la reintegración comunitaria.',
    'c1000001-0005-4000-8000-000000000001',
    'Kentucky',
    'Fayette',
    'Lexington',
    '289 West Loudon Avenue',
    '859-543-2222',
    'https://hopectr.org/what-we-do/mental-health/',
    'sluchetefeld@hopectr.org',
    'Contact program for admission hours',
    'Kentucky DOC-referred individuals with substance use disorder and/or serious mental illness who meet clinical screening for SHARE programming.',
    ARRAY['Long-term residential recovery', 'Co-occurring disorder treatment', 'Serious mental illness support', 'Peer mentorship', 'Clinical case management', 'DOC partnership programming'],
    ARRAY['lexington', 'fayette county', 'SUD', 'mental health', 'RSC', 'recovery housing'],
    false,
    'active'
  ),
  (
    'b1000001-0016-4000-8000-000000000001',
    'Men''s Addiction Recovery Center (Recovery Kentucky)',
    'The Men''s Addiction Recovery Center (M.A.R.C.) in Bowling Green is a Kentucky Recovery Kentucky Center contracted through the Department of Corrections to provide peer-driven substance use disorder treatment and housing for justice-involved men. The Recovery Kentucky model uses phased programming based on 12-step principles and recovery dynamics to address addiction and homelessness. The program serves DOC clients needing residential treatment and can connect graduates to longer-term recovery and housing supports in the Bowling Green region.',
    'El Men''s Addiction Recovery Center (M.A.R.C.) en Bowling Green es un Centro Recovery Kentucky contratado a través del Departamento de Correcciones para brindar tratamiento de trastornos por uso de sustancias impulsado por pares y vivienda para hombres con antecedentes de justicia. El modelo Recovery Kentucky utiliza programación por fases basada en principios de 12 pasos y dinámicas de recuperación para abordar la adicción y la falta de vivienda. El programa atiende a clientes del DOC que necesitan tratamiento residencial y puede conectar a graduados con apoyos de recuperación y vivienda a largo plazo en la región de Bowling Green.',
    'c1000001-0005-4000-8000-000000000001',
    'Kentucky',
    'Warren',
    'Bowling Green',
    '1791 River Street',
    '270-715-0810',
    'https://corrections.ky.gov/Facilities/halfway-houses/Pages/recoverykentucky.aspx',
    NULL,
    'Contact facility for program hours',
    'Kentucky DOC clients with substance use disorder requiring residential treatment who are approved through DOC Addiction Services clinical assessment.',
    ARRAY['Residential SUD treatment', 'Peer-driven recovery phases', '12-step based programming', 'Recovery housing', 'Life skills development', 'DOC program credit upon completion'],
    ARRAY['bowling green', 'warren county', 'recovery kentucky', 'SUD', 'DOC', 'western kentucky'],
    false,
    'active'
  ),
  (
    'b1000001-0017-4000-8000-000000000001',
    'Northern Kentucky Addiction Helpline',
    'The Northern Kentucky Addiction Helpline, operated through the Northern Kentucky Office of Drug Control Policy, connects individuals and families to substance use treatment, recovery supports, and reentry resources 24 hours a day. Trained care coordinators answer calls and help with assessment, treatment placement, Casey’s Law support, harm reduction, and linkage to recovery and reentry services across Boone, Kenton, Campbell, and surrounding counties. The helpline is a starting point for justice-involved individuals seeking SUD treatment after jail or prison.',
    'La Línea de Ayuda de Adicciones del Norte de Kentucky, operada a través de la Oficina de Control de Drogas del Norte de Kentucky, conecta a individuos y familias con tratamiento de uso de sustancias, apoyos de recuperación y recursos de reintegración las 24 horas del día. Coordinadores de atención capacitados responden llamadas y ayudan con evaluación, colocación en tratamiento, apoyo de la Ley Casey, reducción de daños y enlace a servicios de recuperación y reintegración en los condados de Boone, Kenton, Campbell y circundantes. La línea de ayuda es un punto de partida para personas con antecedentes de justicia que buscan tratamiento de TUS después de la cárcel o prisión.',
    'c1000001-0004-4000-8000-000000000001',
    'Kentucky',
    'Kenton',
    'Covington',
    NULL,
    '859-415-9280',
    'https://nkyodcp.org/nky-helpline/',
    NULL,
    '24 hours a day, 7 days a week',
    'Anyone in Northern Kentucky seeking substance use treatment, recovery support, or reentry linkage, including justice-involved individuals and families.',
    ARRAY['24/7 phone support', 'Treatment assessment and placement', 'Recovery service referrals', 'Reentry resource linkage', 'Casey''s Law support', 'Harm reduction information'],
    ARRAY['northern kentucky', 'covington', 'SUD', 'helpline', 'recovery', 'reentry'],
    false,
    'active'
  ),
  (
    'b1000001-0018-4000-8000-000000000001',
    'Southern Kentucky Reentry Council',
    'The Southern Kentucky Reentry Council is a nonprofit coalition serving justice-involved individuals in the Bowling Green region and surrounding counties through the Barren River Area Development District (BRADD). The council helps people leaving jail with transportation, identification, driver''s licenses, housing referrals, toiletries, Narcan, and scholarship opportunities. Partnering with local jails and community agencies, SKRC connects newly released individuals to services that reduce recidivism and support stable reintegration in Southern Kentucky.',
    'El Southern Kentucky Reentry Council es una coalición sin fines de lucro que sirve a personas con antecedentes de justicia en la región de Bowling Green y condados circundantes a través del Barren River Area Development District (BRADD). El consejo ayuda a las personas que salen de la cárcel con transporte, identificación, licencias de conducir, referidos de vivienda, artículos de aseo, Narcan y oportunidades de becas. En asociación con cárceles locales y agencias comunitarias, SKRC conecta a personas recién liberadas con servicios que reducen la reincidencia y apoyan una reintegración estable en el sur de Kentucky.',
    'c1000001-0017-4000-8000-000000000001',
    'Kentucky',
    'Warren',
    'Bowling Green',
    '1945 Scottsville Road, PMB 394',
    NULL,
    'https://southernkyreentry.org',
    'info@southernkyreentry.org',
    'Contact by email for assistance',
    'Justice-involved individuals in Southern Kentucky needing reentry navigation, basic needs, ID help, or referral to local services.',
    ARRAY['Reentry navigation', 'Transportation assistance', 'ID and driver''s license help', 'Housing referrals', 'Release care packages', 'Narcan distribution', 'Community scholarships'],
    ARRAY['bowling green', 'warren county', 'southern kentucky', 'reentry council', 'BRADD'],
    false,
    'active'
  ),
  (
    'b1000001-0019-4000-8000-000000000001',
    'CTS-Russell Reentry Service Center',
    'CTS-Russell is a Kentucky Department of Corrections-contracted Reentry Service Center in Louisville providing residential reentry programming for eligible state inmates, parolees, and probationers. The facility offers structured housing, cognitive behavioral programming, vocational and educational opportunities, and substance use treatment options to support transition back to the Jefferson County community. RSC participants work toward employment and family reconnection while completing DOC community custody requirements.',
    'CTS-Russell es un Centro de Servicios de Reintegración contratado por el Departamento de Correcciones de Kentucky en Louisville que ofrece programación residencial de reintegración para reclusos estatales elegibles, personas en libertad condicional y libertad vigilada. La instalación ofrece vivienda estructurada, programación cognitivo-conductual, oportunidades vocacionales y educativas, y opciones de tratamiento de uso de sustancias para apoyar la transición de regreso a la comunidad del condado de Jefferson. Los participantes del RSC trabajan hacia el empleo y la reconexión familiar mientras completan los requisitos de custodia comunitaria del DOC.',
    'c1000001-0002-4000-8000-000000000001',
    'Kentucky',
    'Jefferson',
    'Louisville',
    '1407 West Jefferson Street',
    '502-855-6500',
    'https://corrections.ky.gov/Facilities/halfway-houses/Pages/reentryservicecenters.aspx',
    NULL,
    'Contact facility for program hours',
    'Kentucky DOC inmates with community custody near parole eligibility and eligible parolees/probationers referred through Probation and Parole.',
    ARRAY['Transitional housing', 'Cognitive behavioral programming', 'Vocational training', 'Educational programs', 'Substance use treatment', 'Employment preparation'],
    ARRAY['louisville', 'jefferson county', 'RSC', 'housing', 'DOC', 'reentry'],
    false,
    'active'
  ),
  (
    'b1000001-0020-4000-8000-000000000001',
    'Louisville Metro Department of Corrections — F2ACT Discharge Planning',
    'Louisville Metro Department of Corrections (LMDC) provides discharge planning and post-release support through its Familiar Faces in Action and Community Treatment (F2ACT) program for vulnerable individuals leaving the Jefferson County jail. F2ACT coordinates clothing, transportation, referrals to shelter or treatment, warm handoffs to community providers, and up to six months of service coordination after release. The program targets people at high risk of cycling between jail and homelessness who need connection to community-based reentry supports.',
    'El Departamento de Correcciones Metro de Louisville (LMDC) proporciona planificación de egreso y apoyo posterior a la liberación a través de su programa Familiar Faces in Action and Community Treatment (F2ACT) para personas vulnerables que salen de la cárcel del condado de Jefferson. F2ACT coordina ropa, transporte, referidos a refugio o tratamiento, traspasos cálidos a proveedores comunitarios y hasta seis meses de coordinación de servicios después de la liberación. El programa se dirige a personas con alto riesgo de alternar entre la cárcel y la falta de vivienda que necesitan conexión con apoyos comunitarios de reintegración.',
    'c1000001-0015-4000-8000-000000000001',
    'Kentucky',
    'Jefferson',
    'Louisville',
    '400 S. Sixth Street',
    '502-574-8477',
    'https://louisvilleky.gov/government/corrections/correction-cares-programs-and-services',
    NULL,
    'Monday–Friday, 8 a.m.–5 p.m.',
    'Individuals incarcerated at Louisville Metro Department of Corrections identified as vulnerable and enrolled in F2ACT discharge planning prior to release.',
    ARRAY['Discharge planning', 'Post-release service coordination (up to 6 months)', 'Clothing and basic needs', 'Transportation to placements', 'Shelter and treatment referrals', 'Warm handoff to community providers'],
    ARRAY['louisville', 'jefferson county', 'jail reentry', 'F2ACT', 'discharge planning', 'basic needs'],
    false,
    'active'
  )
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  description_es = EXCLUDED.description_es,
  category_id = EXCLUDED.category_id,
  state = EXCLUDED.state,
  county = EXCLUDED.county,
  city = EXCLUDED.city,
  address = EXCLUDED.address,
  phone = EXCLUDED.phone,
  website = EXCLUDED.website,
  email = EXCLUDED.email,
  hours = EXCLUDED.hours,
  eligibility = EXCLUDED.eligibility,
  services = EXCLUDED.services,
  tags = EXCLUDED.tags,
  is_featured = EXCLUDED.is_featured,
  status = EXCLUDED.status,
  updated_at = NOW();
