/**
 * Canonical Virginia locality names (133: 95 counties + 38 independent cities)
 * for filters and validation. Virginia independent cities are not part of any
 * county; each is its own locality. Where a city shares a name with a county
 * (Fairfax, Franklin, Richmond, Roanoke), the city uses a " City" suffix.
 */
export const VIRGINIA_COUNTIES = [
  "Accomack",
  "Albemarle",
  "Alexandria",
  "Alleghany",
  "Amelia",
  "Amherst",
  "Appomattox",
  "Arlington",
  "Augusta",
  "Bath",
  "Bedford",
  "Bland",
  "Botetourt",
  "Bristol",
  "Brunswick",
  "Buchanan",
  "Buckingham",
  "Buena Vista",
  "Campbell",
  "Caroline",
  "Carroll",
  "Charles City",
  "Charlotte",
  "Charlottesville",
  "Chesapeake",
  "Chesterfield",
  "Clarke",
  "Colonial Heights",
  "Covington",
  "Craig",
  "Culpeper",
  "Cumberland",
  "Danville",
  "Dickenson",
  "Dinwiddie",
  "Emporia",
  "Essex",
  "Fairfax",
  "Fairfax City",
  "Falls Church",
  "Fauquier",
  "Floyd",
  "Fluvanna",
  "Franklin",
  "Franklin City",
  "Frederick",
  "Fredericksburg",
  "Galax",
  "Giles",
  "Gloucester",
  "Goochland",
  "Grayson",
  "Greene",
  "Greensville",
  "Halifax",
  "Hampton",
  "Hanover",
  "Harrisonburg",
  "Henrico",
  "Henry",
  "Highland",
  "Hopewell",
  "Isle of Wight",
  "James City",
  "King and Queen",
  "King George",
  "King William",
  "Lancaster",
  "Lee",
  "Lexington",
  "Loudoun",
  "Louisa",
  "Lunenburg",
  "Lynchburg",
  "Madison",
  "Manassas",
  "Manassas Park",
  "Martinsville",
  "Mathews",
  "Mecklenburg",
  "Middlesex",
  "Montgomery",
  "Nelson",
  "New Kent",
  "Newport News",
  "Norfolk",
  "Northampton",
  "Northumberland",
  "Norton",
  "Nottoway",
  "Orange",
  "Page",
  "Patrick",
  "Petersburg",
  "Pittsylvania",
  "Poquoson",
  "Portsmouth",
  "Powhatan",
  "Prince Edward",
  "Prince George",
  "Prince William",
  "Pulaski",
  "Radford",
  "Rappahannock",
  "Richmond",
  "Richmond City",
  "Roanoke",
  "Roanoke City",
  "Rockbridge",
  "Rockingham",
  "Russell",
  "Salem",
  "Scott",
  "Shenandoah",
  "Smyth",
  "Southampton",
  "Spotsylvania",
  "Stafford",
  "Staunton",
  "Suffolk",
  "Surry",
  "Sussex",
  "Tazewell",
  "Virginia Beach",
  "Warren",
  "Washington",
  "Waynesboro",
  "Westmoreland",
  "Williamsburg",
  "Winchester",
  "Wise",
  "Wythe",
  "York",
] as const;
