"""Exact and fallback service mappings for strings not covered by primary rules."""
from __future__ import annotations

import re

# Keyed by alias_key(raw) for strings that need explicit canonical assignment.
EXACT_OVERRIDES: dict[str, str] = {
    "employment help": "Employment assistance",
    "employment preparation": "Employment assistance",
    "employment readiness": "Employment assistance",
    "employment readiness support": "Employment assistance",
    "employment readiness training": "Employment assistance",
    "employment readiness workshops": "Employment assistance",
    "employment retention coaching": "Employment assistance",
    "employment support": "Employment assistance",
    "employment training": "Employment assistance",
    "employment transition support": "Employment assistance",
    "employment workshops": "Employment assistance",
    "energy assistance": "Rent and utility assistance",
    "english language classes": "Adult literacy and ESL",
    "english language instruction": "Adult literacy and ESL",
    "english language learning": "Adult literacy and ESL",
    "entrepreneurship support": "Workforce development",
    "eviction defense": "Housing legal aid",
    "eviction prevention": "Housing legal aid",
    "fair-chance education": "Employment assistance",
    "family assistance": "Family reunification support",
    "family law": "Civil legal representation",
    "family law assistance": "Civil legal representation",
    "family member support": "Family reunification support",
    "family planning": "Family reunification support",
    "family preservation": "Family reunification support",
    "family preservation services": "Family reunification support",
    "family programming": "Family reunification support",
    "family self-sufficiency programs": "Family reunification support",
    "family shelter": "Emergency shelter",
    "family stability programs": "Family reunification support",
    "family stabilization": "Family reunification support",
    "family strengthening": "Family reunification support",
    "family support": "Family reunification support",
    "family-centered care": "Family reunification support",
    "felon release letter processing": "Civil legal representation",
    "filing fee assistance": "Rent and utility assistance",
    "financial aid info": "Basic needs assistance",
    "financial assistance": "Rent and utility assistance",
    "financial education workshops": "Basic needs assistance",
    "financial resource": "Rent and utility assistance",
    "fingerprinting": "Civil legal representation",
    "focused earn-while-you-learn": "Employment assistance",
    "food and housing programs": "Basic needs assistance",
    "food and housing support": "Basic needs assistance",
    "food assistance": "Food pantry access",
    "food distribution": "Food pantry access",
    "food pantries": "Food pantry access",
    "food security programs": "Food pantry access",
    "foreclosure defense": "Housing legal aid",
    "forensic interviews": "Primary medical care",
    "free hiv screening": "Primary medical care",
    "free service": "Partner referrals",
    "funds recovery": "Rent and utility assistance",
    "genesis process": "Job readiness training",
    "green river region reporting": "Probation and parole supervision",
    "health education": "Primary medical care",
    "heating and cooling bill assistance": "Rent and utility assistance",
    "higher education navigation": "Workforce development",
    "hiset": "Adult literacy and ESL",
    "hiset classes": "Adult literacy and ESL",
    "hiset preparation": "Adult literacy and ESL",
    "hiv care": "Primary medical care",
    "hiv housing assistance": "Primary medical care",
    "hiv/aids housing stability support": "Primary medical care",
    "home detention": "Probation and parole supervision",
    "home incarceration program info": "Probation and parole supervision",
    "homeless prevention": "Emergency shelter",
    "household goods": "Basic needs assistance",
    "household item donations": "Basic needs assistance",
    "household items": "Basic needs assistance",
    "household support": "Basic needs assistance",
    "housing and eviction defense": "Housing legal aid",
    "housing and eviction help": "Housing legal aid",
    "housing finance education": "Budgeting and financial coaching",
    "housing first": "Supportive housing",
    "housing legal navigator chat": "Housing legal aid",
    "housing program info": "Supportive housing",
    "housing programs": "Supportive housing",
    "housing search": "Supportive housing",
    "housing search assistance": "Supportive housing",
    "housing stabilization": "Supportive housing",
    "housing support": "Supportive housing",
    "hse preparation": "Adult literacy and ESL",
    "id and housing assistance": "Document assistance",
    "id and mailing address assistance": "Document assistance",
    "id replacement": "Document assistance",
    "idd services": "Developmental disability services",
    "immigration and family services": "Family reunification support",
    "immunizations": "Primary medical care",
    "in-custody sap therapeutic community (state inmates)": "Reentry navigation",
    "intake": "Application assistance",
    "intake and triage": "Application assistance",
    "integrated care": "Primary medical care",
    "intensive programming": "Job readiness training",
    "intermediate sanctions": "Probation and parole supervision",
    "job coaching": "Employment assistance",
    "job coaching and placement": "Employment assistance",
    "job preparation": "Employment assistance",
    "job search and placement assistance": "Employment assistance",
    "job skills classes": "Employment assistance",
    "job-readiness orientation": "Employment assistance",
    "job-readiness training": "Employment assistance",
    "jobs for life": "Employment assistance",
    "jobs for life training": "Employment assistance",
    "jobs4tn registration": "Employment assistance",
    "jobs4tn.gov support": "Employment assistance",
    "kentucky hb 185 policy resources": "Workforce development",
    "legal provider matching": "Civil legal representation",
    "lextran wheels paratransit": "Partner referrals",
    "life insurance": "Benefits navigation",
    "life recovery": "Substance use counseling",
    "life skills": "Job readiness training",
    "life skills programming": "Job readiness training",
    "life skills resource library": "Job readiness training",
    "liheap energy assistance": "Rent and utility assistance",
    "links to regional kentucky food banks": "Food pantry access",
    "live chat support": "Partner referrals",
    "local child support enforcement": "Child support services",
    "local records": "Document assistance",
    "long-term residential care": "Residential treatment",
    "mail and online ordering": "Document assistance",
    "mail and phone payment options": "Document assistance",
    "mail service": "Document assistance",
    "meals": "Emergency food assistance",
    "medicare enrollment": "Health insurance enrollment",
    "medicare enrollment assistance": "Health insurance enrollment",
    "medicare info": "Health insurance enrollment",
    "medication management": "Primary medical care",
    "mental health": "Primary medical care",
    "mental health and sud treatment": "Primary medical care",
    "mentor support": "Peer support",
    "mentorship": "Peer support",
    "mobile food distribution": "Food pantry access",
    "mobile food distributions": "Food pantry access",
    "monthly passes": "Partner referrals",
    "mrt classes": "Job readiness training",
    "mst support": "Counseling",
    "multi-language interpreter support": "Partner referrals",
    "multi-location kentucky access": "Partner referrals",
    "mytarc fare card": "Partner referrals",
    "national food bank search by zip code": "Food pantry access",
    "no-cost participation": "Rent and utility assistance",
    "non-custodial parent location": "Civil legal representation",
    "north star nrrc oversight": "Probation and parole supervision",
    "nutrition support": "Food pantry access",
    "occupational license guidance": "Workforce development",
    "occupational licensing guidance": "Workforce development",
    "off the streets motivational program": "Employment assistance",
    "off the streets program": "Employment assistance",
    "office location search": "Partner referrals",
    "officer assignment": "Probation and parole supervision",
    "officer contact": "Probation and parole supervision",
    "on-site pharmacy": "Primary medical care",
    "online and in-person instruction": "Partner referrals",
    "online benefits management": "Partner referrals",
    "online case intake for economic liberty violations": "Housing legal aid",
    "online certification courses": "Workforce development",
    "online chat support": "Partner referrals",
    "online claims": "Partner referrals",
    "online meeting options": "Partner referrals",
    "online registration": "Partner referrals",
    "online resource directory": "Partner referrals",
    "online service directory": "Partner referrals",
    "open access intake": "Partner referrals",
    "opportunity port partner services": "Partner referrals",
    "osha and forklift certification": "Workforce development",
    "overnight shelter": "Emergency shelter",
    "paid transitional work": "Employment assistance",
    "paid transitional work crews": "Employment assistance",
    "paratransit service": "Transportation assistance",
    "parent education": "Family reunification support",
    "park-and-ride locations": "Partner referrals",
    "paternity and order establishment": "Civil legal representation",
    "paternity establishment": "Civil legal representation",
    "payment and insurance filtering": "Document assistance",
    "payment collection and monitoring": "Partner referrals",
    "payment processing and tracking": "Partner referrals",
    "pediatric care": "Primary medical care",
    "peer accountability": "Addiction recovery support",
    "peer accountability program": "Addiction recovery support",
    "peer-led sobriety support": "Addiction recovery support",
    "pennyrile region reporting": "Probation and parole supervision",
    "pension and benefits filing": "Benefits navigation",
    "pension and disability filing": "Benefits navigation",
    "pension and education benefits": "Benefits navigation",
    "personal development programming": "Job readiness training",
    "pharmacy": "Primary medical care",
    "pharmacy assistance": "Primary medical care",
    "pharmacy services": "Primary medical care",
    "policy litigation": "Housing legal aid",
    "potential charge reduction upon completion": "Probation and parole supervision",
    "pre-release assessments": "Application assistance",
    "prenatal and postpartum care": "Primary medical care",
    "prescription assistance": "Primary medical care",
    "preventive care": "Primary medical care",
    "preventive services": "Primary medical care",
    "primary care": "Primary medical care",
    "primary care access": "Primary medical care",
    "primary care integration": "Primary medical care",
    "problem gambling resources": "Primary medical care",
    "professional attire": "Basic needs assistance",
    "professional interview attire": "Basic needs assistance",
    "professional women's group": "Workforce development",
    "provider directory": "Partner referrals",
    "provider matching": "Partner referrals",
    "ptsd and mst treatment": "Counseling",
    "ptsd treatment": "Counseling",
    "public assistance": "Benefits navigation",
    "public benefits": "Benefits navigation",
    "public housing": "Supportive housing",
    "ramp paratransit": "Transportation assistance",
    "rapid re-housing": "Supportive housing",
    "rapid start treatment": "Residential treatment",
    "record amendments": "Civil legal representation",
    "record review": "Civil legal representation",
    "record-related civil relief": "Housing legal aid",
    "recovery dynamics": "Job readiness training",
    "recovery dynamics curriculum": "Job readiness training",
    "recovery housing": "Supportive housing",
    "recovery housing search": "Supportive housing",
    "recovery housing vouchers": "Supportive housing",
    "recovery kentucky housing": "Supportive housing",
    "recovery programming": "Substance use counseling",
    "recovery programs": "Substance use counseling",
    "recovery-informed employment support": "Employment assistance",
    "recovery-oriented sentencing": "Employment assistance",
    "recycling and manufacturing training": "Workforce development",
    "rovr eligibility guidance": "Document assistance",
}

_FALLBACK_SPECS: tuple[tuple[str, str], ...] = (
    ("Employment assistance", r"employment help|employment preparation|employment readiness|employment retention|employment support|employment training|employment transition|employment workshop|jobs4tn|jobs for life|recovery-informed employment|paid transitional work|job coaching|job preparation|job-readiness|job skills|job search and placement|focused earn-while-you-learn|fair-chance education|recovery-oriented sentencing|off the streets|work crews"),
    ("Job readiness training", r"employment readiness|job-readiness|job skills|jobs for life|focused earn|life skills|personal development|genesis process|mrt classes|recovery dynamics|intensive programming|off the streets motivational"),
    ("Rent and utility assistance", r"energy assist|liheap|heating and cooling|financial assist|financial resource|filing fee|funds recovery|no-cost participation"),
    ("Adult literacy and ESL", r"english language|esl\b|hse preparation|hiset"),
    ("Workforce development", r"entrepreneurship|recycling and manufacturing|osha and forklift|occupational license|occupational licensing|higher education navigation|online certification|professional women's group|kentucky hb 185"),
    ("Housing legal aid", r"eviction|foreclosure|housing and eviction|housing legal navigator|record-related civil relief|policy litigation|online case intake for economic liberty"),
    ("Civil legal representation", r"family law|legal provider matching|record amendments|record review|felon release letter|fingerprinting|paternity|non-custodial parent"),
    ("Family reunification support", r"family preservation|family stability|family strengthening|family self-sufficiency|family programming|family-centered|family member support|family assistance|family support|family planning|parent education|immigration and family"),
    ("Emergency shelter", r"family shelter|overnight shelter|homeless prevention"),
    ("Basic needs assistance", r"household goods|household item|household support|professional attire|professional interview attire|food and housing|financial aid info|financial education"),
    ("Document assistance", r"felon release letter|fingerprinting|id and housing|id and mailing|id replacement|mail service|mail and|local records|rovr eligibility|payment and insurance filtering"),
    ("Food pantry access", r"food assistance|food distribution|food pantries|food security|mobile food|links to regional|national food bank|nutrition support"),
    ("Emergency food assistance", r"meals\b"),
    ("Partner referrals", r"free service|live chat|online chat|online meeting|online registration|online resource|online service|office location|provider directory|provider matching|multi-location|opportunity port|park-and-ride|mail and phone|mail and online|online and in-person|online benefits management|online claims|open access intake|payment processing|payment collection|mytarc fare|lextran|monthly passes|multi-language interpreter|chat support"),
    ("Primary medical care", r"primary care|pediatric|prenatal|postpartum|immunization|preventive|pharmacy|prescription|medication management|hiv care|free hiv|integrated care|health education|on-site pharmacy|mental health and sud|mental health\b|problem gambling|forensic interview|family-centered care"),
    ("Supportive housing", r"hiv housing|hiv/aids housing|recovery housing|recovery kentucky|rapid re-housing|housing first|public housing|recovery housing search|recovery housing vouchers|housing stabilization|housing support|housing search|housing programs|housing program info"),
    ("Health insurance enrollment", r"medicare"),
    ("Benefits navigation", r"public assistance|public benefits|pension and benefits|pension and disability|pension and education|life insurance|online benefits management|medicare info|medicare enrollment"),
    ("Application assistance", r"intake\b|intake and triage|pre-release assessment|open access intake|no-cost participation|filing fee|eligibility guidance|rovr eligibility"),
    ("Probation and parole supervision", r"green river region reporting|pennyrile region reporting|home detention|home incarceration|intermediate sanctions|officer assignment|officer contact|north star nrrc|potential charge reduction"),
    ("Residential treatment", r"in-custody sap|long-term residential|rapid start treatment"),
    ("Substance use counseling", r"mrt classes|recovery dynamics|genesis process|life recovery|recovery programming|recovery programs|off the streets"),
    ("Addiction recovery support", r"peer accountability|peer-led sobriety"),
    ("Peer support", r"mentor support|mentorship\b"),
    ("Developmental disability services", r"idd services"),
    ("Child support services", r"local child support|paternity|non-custodial parent|payment collection|payment monitoring|payment processing"),
    ("Transportation assistance", r"paratransit|ramp paratransit|lextran"),
    ("Budgeting and financial coaching", r"financial education|financial aid info|housing finance education"),
    ("Counseling", r"ptsd|mst support|ptsd treatment"),
)

FALLBACK_RULES: tuple[tuple[str, re.Pattern[str]], ...] = tuple(
    (canonical, re.compile(pattern, re.IGNORECASE))
    for canonical, pattern in _FALLBACK_SPECS
)
