"""Alabama Pass 2 rural depth — verified program-level rows for Tier A weak counties."""


def register_rural_depth(add):
    """Register verified resources filling missing Tier A categories in rural weak counties."""

    # --- employment: Alabama Career Centers (joblink.alabama.gov) ---
    add(
        name="Alabama Career Center — Anniston",
        category="employment",
        region="Anniston / Multi-County",
        description="The Anniston Career Center connects job seekers in Calhoun, Cleburne, Talladega, and Clay counties—including justice-involved adults on ABPP supervision—to free job search assistance, resume help, WIOA training referrals, and fair-chance employer connections through East AlabamaWorks. Staff coordinate with Gadsden State Community College adult education and East Central Alabama behavioral health partners. Workforce center—not emergency housing or legal aid intake.",
        description_es="El Alabama Career Center de Anniston conecta buscadores de empleo en los condados Calhoun, Cleburne, Talladega y Clay—incluidos adultos con antecedentes penales bajo supervisión de ABPP—a ayuda gratuita de búsqueda de empleo, currículum, referencias de capacitación WIOA y conexiones con empleadores de segunda oportunidad a través de East AlabamaWorks.",
        address="1731 Coleman Road", city="Anniston", phone="256-832-0147", email="",
        website="https://joblink.alabama.gov",
        eligibility="Open to east-central Alabama job seekers including justice-involved individuals; core Career Center services are free.",
        eligibility_es="Abierto a buscadores de empleo del centro-este de Alabama incluidas personas con antecedentes penales; los servicios básicos del Career Center son gratuitos.",
        notes="Register at joblink.alabama.gov before visiting; pairs with ABPP Anniston and Legal Services Alabama Anniston office.",
        notes_es="Regístrese en joblink.alabama.gov antes de visitar; se vincula con ABPP Anniston y Legal Services Alabama Anniston.",
        hours="Monday–Friday, 8:00 a.m.–5:00 p.m.",
        tags="anniston|calhoun|employment|career-center|WIOA|rural-depth|reentry",
        services="Job search assistance|Resume help|WIOA training referrals|Fair-chance employment|East AlabamaWorks partnerships",
        county="Calhoun", served_counties="Calhoun|Cleburne|Talladega|Clay", coverage="multi",
        _source="https://joblink.alabama.gov", _source_type="government", _confidence="high",
    )

    add(
        name="Alabama Career Center — Gadsden",
        category="employment",
        region="Gadsden / Multi-County",
        description="The Gadsden Career Center connects job seekers in Etowah, Cherokee, and DeKalb counties—including returning citizens rebuilding work history after ADOC or county jail release—to free resume assistance, job search resources, WIOA training referrals, and employer job fairs through East AlabamaWorks. Veterans receive priority services. Workforce center—not a DHR benefits or probation reporting office.",
        description_es="El Alabama Career Center de Gadsden conecta buscadores de empleo en los condados Etowah, Cherokee y DeKalb—incluidos ciudadanos que regresan que reconstruyen historial laboral tras liberación de ADOC o cárcel del condado—a asistencia gratuita de currículum, recursos de búsqueda de empleo, referencias WIOA y ferias de empleo.",
        address="216 North 5th Street", city="Gadsden", phone="256-546-4667", email="leticia.whitfield@alcc.alabama.gov",
        website="https://joblink.alabama.gov",
        eligibility="Open to northeast Alabama job seekers including justice-involved adults; veterans receive priority services.",
        eligibility_es="Abierto a buscadores de empleo del noreste de Alabama incluidos adultos con antecedentes penales; veteranos reciben servicios prioritarios.",
        notes="Register at joblink.alabama.gov; hosts seasonal hiring fairs with East AlabamaWorks; Fort Payne satellite serves DeKalb County.",
        notes_es="Regístrese en joblink.alabama.gov; organiza ferias de contratación estacionales con East AlabamaWorks; el satélite de Fort Payne sirve al condado DeKalb.",
        hours="Monday–Friday, 8:00 a.m.–5:00 p.m.",
        tags="gadsden|etowah|employment|career-center|WIOA|rural-depth|reentry",
        services="Job search assistance|Resume preparation|WIOA training referrals|Veteran employment services|Employer job fairs",
        county="Etowah", served_counties="Etowah|Cherokee|DeKalb", coverage="multi",
        _source="https://joblink.alabama.gov", _source_type="government", _confidence="high",
    )

    add(
        name="Alabama Career Center — Opelika",
        category="employment",
        region="Opelika / Multi-County",
        description="The Opelika Career Center connects job seekers in Lee, Russell, Chambers, Macon, and Tallapoosa counties—including justice-involved adults on ABPP supervision—to free job search assistance, career counseling, WIOA training referrals, and fair-chance employer connections through the Food Bank of East Alabama workforce partnership network. Staff link returning citizens to Southern Union State Community College adult education. Workforce center—not emergency shelter intake.",
        description_es="El Alabama Career Center de Opelika conecta buscadores de empleo en los condados Lee, Russell, Chambers, Macon y Tallapoosa—incluidos adultos con antecedentes penales bajo supervisión de ABPP—a asistencia gratuita de búsqueda de empleo, asesoría de carrera y referencias WIOA.",
        address="2300 Frederick Road", city="Opelika", phone="334-749-5065", email="Opelika@alcc.alabama.gov",
        website="https://joblink.alabama.gov",
        eligibility="Open to east Alabama job seekers including justice-involved individuals; core services free.",
        eligibility_es="Abierto a buscadores de empleo del este de Alabama incluidas personas con antecedentes penales; servicios básicos gratuitos.",
        notes="Register at joblink.alabama.gov; pairs with ABPP Opelika, Phenix City, and LaFayette field offices.",
        notes_es="Regístrese en joblink.alabama.gov; se vincula con oficinas de campo ABPP Opelika, Phenix City y LaFayette.",
        hours="Monday–Friday, 8:00 a.m.–4:30 p.m.",
        tags="opelika|lee|employment|career-center|WIOA|rural-depth|reentry",
        services="Job search assistance|Career counseling|WIOA training referrals|Fair-chance employment|Adult education referrals",
        county="Lee", served_counties="Lee|Russell|Chambers|Macon|Tallapoosa", coverage="multi",
        _source="https://joblink.alabama.gov", _source_type="government", _confidence="high",
    )

    add(
        name="Alabama Career Center — Jasper",
        category="employment",
        region="Jasper / Walker County",
        description="The Jasper Career Center connects job seekers in Walker and Winston counties—including justice-involved adults returning from Walker County Jail or ADOC custody—to free job search assistance, resume help, WIOA training referrals, and fair-chance employer connections with regional mining and manufacturing employers. Staff coordinate with Bevill State Community College adult education and Legal Services Alabama Birmingham office. Workforce center—not a probation reporting site.",
        description_es="El Alabama Career Center de Jasper conecta buscadores de empleo en los condados Walker y Winston—incluidos adultos con antecedentes penales que regresan de la cárcel del condado Walker o custodia de ADOC—a asistencia gratuita de búsqueda de empleo, currículum y referencias WIOA.",
        address="3409 11th Avenue", city="Jasper", phone="205-384-9011", email="",
        website="https://joblink.alabama.gov",
        eligibility="Open to Walker and Winston County job seekers including justice-involved individuals; core services free.",
        eligibility_es="Abierto a buscadores de empleo de los condados Walker y Winston incluidas personas con antecedentes penales; servicios básicos gratuitos.",
        notes="Register at joblink.alabama.gov; pairs with ABPP Jasper field office and Community Food Bank of Central Alabama.",
        notes_es="Regístrese en joblink.alabama.gov; se vincula con la oficina de campo ABPP Jasper y el Banco de Alimentos Comunitario de Alabama Central.",
        hours="Monday–Friday business hours",
        tags="jasper|walker|employment|career-center|WIOA|rural-depth|reentry",
        services="Job search assistance|Resume help|WIOA training referrals|Fair-chance employment|Manufacturing employer connections",
        county="Walker", served_counties="Walker|Winston", coverage="multi",
        _source="https://joblink.alabama.gov", _source_type="government", _confidence="high",
    )

    add(
        name="Alabama Career Center — Hamilton",
        category="employment",
        region="Hamilton / Marion County",
        description="The Hamilton Career Center connects job seekers in Marion and surrounding northwest Alabama counties—including returning citizens reestablishing employment after incarceration—to free job search assistance, resume help, and WIOA training referrals through North AlabamaWorks. The center hosts periodic employer job fairs and coordinates with Northwest-Shoals Community College adult education in Double Springs. Workforce center—not a DHR or legal aid office.",
        description_es="El Alabama Career Center de Hamilton conecta buscadores de empleo en Marion y condados del noroeste de Alabama—incluidos ciudadanos que regresan que reestablecen empleo tras encarcelación—a asistencia gratuita de búsqueda de empleo, currículum y referencias WIOA a través de North AlabamaWorks.",
        address="1481 Military Street South", city="Hamilton", phone="205-921-5672", email="",
        website="https://joblink.alabama.gov",
        eligibility="Open to Marion County and northwest Alabama job seekers including justice-involved adults; core services free.",
        eligibility_es="Abierto a buscadores de empleo del condado Marion y noroeste de Alabama incluidos adultos con antecedentes penales; servicios básicos gratuitos.",
        notes="Register at joblink.alabama.gov; Haleyville itinerant point serves Winston County first and third Mondays.",
        notes_es="Regístrese en joblink.alabama.gov; el punto itinerante de Haleyville sirve al condado Winston el primer y tercer lunes.",
        hours="Monday–Friday, 8:00 a.m.–4:30 p.m.",
        tags="hamilton|marion|employment|career-center|WIOA|rural-depth|reentry",
        services="Job search assistance|Resume help|WIOA training referrals|Employer job fairs|Adult education referrals",
        county="Marion", served_counties="Marion|Winston", coverage="multi",
        _source="https://joblink.alabama.gov", _source_type="government", _confidence="high",
    )

    add(
        name="Alabama Career Center — Decatur",
        category="employment",
        region="Decatur / Lawrence County",
        description="The Decatur Career Center connects job seekers in Lawrence, Morgan, and Limestone counties—including justice-involved adults on community supervision—to free job search assistance, career coaching, WIOA training referrals, and fair-chance employment navigation through North AlabamaWorks. Staff link returning citizens to Calhoun Community College adult education and Food Bank of North Alabama partners. Workforce center—not emergency housing intake.",
        description_es="El Alabama Career Center de Decatur conecta buscadores de empleo en los condados Lawrence, Morgan y Limestone—incluidos adultos con antecedentes penales bajo supervisión comunitaria—a asistencia gratuita de búsqueda de empleo, coaching de carrera y referencias WIOA.",
        address="1819 Bassett Avenue SE", city="Decatur", phone="256-355-0872", email="",
        website="https://joblink.alabama.gov",
        eligibility="Open to north Alabama job seekers including justice-involved individuals; veterans receive priority services.",
        eligibility_es="Abierto a buscadores de empleo del norte de Alabama incluidas personas con antecedentes penales; veteranos reciben servicios prioritarios.",
        notes="Register at joblink.alabama.gov; Moulton ABPP field office serves Lawrence County supervisees.",
        notes_es="Regístrese en joblink.alabama.gov; la oficina de campo ABPP Moulton atiende supervisados del condado Lawrence.",
        hours="Monday–Friday business hours",
        tags="decatur|lawrence|employment|career-center|WIOA|rural-depth|reentry",
        services="Job search assistance|Career coaching|WIOA training referrals|Fair-chance employment|Veteran priority services",
        county="Lawrence", served_counties="Lawrence|Morgan|Limestone", coverage="multi",
        _source="https://joblink.alabama.gov", _source_type="government", _confidence="high",
    )

    add(
        name="Alabama Career Center — Oneonta",
        category="employment",
        region="Oneonta / Blount County",
        description="The Oneonta Career Center connects Blount County job seekers—including justice-involved adults returning from Blount County Detention Center or ADOC custody—to free job search assistance, resume help, WIOA training referrals, and employer connections through North AlabamaWorks. Staff coordinate with Wallace State Community College adult education and Community Food Bank of Central Alabama partner pantries. Workforce center—not a walk-in DHR benefits office.",
        description_es="El Alabama Career Center de Oneonta conecta buscadores de empleo del condado Blount—incluidos adultos con antecedentes penales que regresan de la cárcel del condado Blount o custodia de ADOC—a asistencia gratuita de búsqueda de empleo, currículum y referencias WIOA.",
        address="55245 U.S. Highway 231", city="Oneonta", phone="205-625-3626", email="",
        website="https://joblink.alabama.gov",
        eligibility="Open to Blount County job seekers including justice-involved individuals; core Career Center services are free.",
        eligibility_es="Abierto a buscadores de empleo del condado Blount incluidas personas con antecedentes penales; los servicios básicos del Career Center son gratuitos.",
        notes="Register at joblink.alabama.gov; pairs with ABPP Oneonta field office and Legal Services Alabama Birmingham.",
        notes_es="Regístrese en joblink.alabama.gov; se vincula con la oficina de campo ABPP Oneonta y Legal Services Alabama Birmingham.",
        hours="Monday–Friday business hours",
        tags="oneonta|blount|employment|career-center|WIOA|rural-depth|reentry",
        services="Job search assistance|Resume help|WIOA training referrals|Employer connections|Adult education referrals",
        county="Blount", served_counties="Blount", coverage="single",
        _source="https://joblink.alabama.gov", _source_type="government", _confidence="high",
    )

    add(
        name="Alabama Career Center — Andalusia",
        category="employment",
        region="Andalusia / Covington County",
        description="The Andalusia Career Center connects job seekers in Covington and Crenshaw counties—including justice-involved adults on ABPP supervision—to free job search assistance, resume help, WIOA training referrals, and fair-chance employer connections in south-central Alabama. Staff coordinate with Lurleen B. Wallace Community College adult education and Wiregrass workforce partners. Workforce center—not a legal aid or food pantry.",
        description_es="El Alabama Career Center de Andalusia conecta buscadores de empleo en los condados Covington y Crenshaw—incluidos adultos con antecedentes penales bajo supervisión de ABPP—a asistencia gratuita de búsqueda de empleo, currículum y referencias WIOA en el centro-sur de Alabama.",
        address="202 YMCA Drive", city="Andalusia", phone="334-222-3116", email="",
        website="https://joblink.alabama.gov",
        eligibility="Open to Covington and Crenshaw County job seekers including justice-involved adults; core services free.",
        eligibility_es="Abierto a buscadores de empleo de los condados Covington y Crenshaw incluidos adultos con antecedentes penales; servicios básicos gratuitos.",
        notes="Register at joblink.alabama.gov; pairs with ABPP Andalusia field office and Legal Services Alabama Dothan.",
        notes_es="Regístrese en joblink.alabama.gov; se vincula con la oficina de campo ABPP Andalusia y Legal Services Alabama Dothan.",
        hours="Monday–Friday business hours",
        tags="andalusia|covington|employment|career-center|WIOA|rural-depth|reentry",
        services="Job search assistance|Resume help|WIOA training referrals|Fair-chance employment|Wiregrass workforce partnerships",
        county="Covington", served_counties="Covington|Crenshaw", coverage="multi",
        _source="https://joblink.alabama.gov", _source_type="government", _confidence="high",
    )

    add(
        name="Alabama Career Center — Enterprise",
        category="employment",
        region="Enterprise / Barbour County",
        description="The Enterprise Career Center connects job seekers in Barbour, Coffee, and Pike counties—including returning citizens rebuilding employment in the Wiregrass region—to free job search assistance, resume help, WIOA training referrals, and employer job fairs. Staff coordinate with Wallace Community College Dothan adult education and Southeast Alabama Community Action Partnership. Workforce center—not emergency cash assistance.",
        description_es="El Alabama Career Center de Enterprise conecta buscadores de empleo en los condados Barbour, Coffee y Pike—incluidos ciudadanos que regresan que reconstruyen empleo en la región Wiregrass—a asistencia gratuita de búsqueda de empleo, currículum y referencias WIOA.",
        address="600 Plaza Drive", city="Enterprise", phone="334-347-0024", email="",
        website="https://joblink.alabama.gov",
        eligibility="Open to Wiregrass region job seekers including justice-involved individuals; core services free.",
        eligibility_es="Abierto a buscadores de empleo de la región Wiregrass incluidas personas con antecedentes penales; servicios básicos gratuitos.",
        notes="Register at joblink.alabama.gov; pairs with ABPP Troy field office and Heart of Alabama Food Bank.",
        notes_es="Regístrese en joblink.alabama.gov; se vincula con la oficina de campo ABPP Troy y el Banco de Alimentos Heart of Alabama.",
        hours="Monday–Friday business hours",
        tags="enterprise|barbour|employment|career-center|WIOA|rural-depth|reentry",
        services="Job search assistance|Resume help|WIOA training referrals|Employer job fairs|Wiregrass workforce navigation",
        county="Barbour", served_counties="Barbour|Coffee|Pike", coverage="multi",
        _source="https://joblink.alabama.gov", _source_type="government", _confidence="high",
    )

    add(
        name="Alabama Career Center — Greenville",
        category="employment",
        region="Greenville / Butler County",
        description="The Greenville Career Center connects Butler County job seekers—including justice-involved adults on ABPP supervision—to free job search assistance, resume help, WIOA training referrals, and fair-chance employer connections in the Black Belt and River Region. Staff link returning citizens to Lurleen B. Wallace Community College adult education and Heart of Alabama Food Bank partner pantries. Workforce center—not a probation reporting office.",
        description_es="El Alabama Career Center de Greenville conecta buscadores de empleo del condado Butler—incluidos adultos con antecedentes penales bajo supervisión de ABPP—a asistencia gratuita de búsqueda de empleo, currículum y referencias WIOA en el Cinturón Negro y la región del río.",
        address="1000 East Commerce Street", city="Greenville", phone="334-382-3211", email="",
        website="https://joblink.alabama.gov",
        eligibility="Open to Butler County job seekers including justice-involved adults; core Career Center services are free.",
        eligibility_es="Abierto a buscadores de empleo del condado Butler incluidos adultos con antecedentes penales; los servicios básicos del Career Center son gratuitos.",
        notes="Register at joblink.alabama.gov; pairs with ABPP Greenville field office and Legal Services Alabama Montgomery.",
        notes_es="Regístrese en joblink.alabama.gov; se vincula con la oficina de campo ABPP Greenville y Legal Services Alabama Montgomery.",
        hours="Monday–Friday business hours",
        tags="greenville|butler|employment|career-center|WIOA|rural-depth|reentry",
        services="Job search assistance|Resume help|WIOA training referrals|Fair-chance employment|Black Belt workforce navigation",
        county="Butler", served_counties="Butler", coverage="single",
        _source="https://joblink.alabama.gov", _source_type="government", _confidence="high",
    )

    add(
        name="Alabama Career Center — Troy",
        category="employment",
        region="Troy / Pike County",
        description="The Troy Career Center connects Pike, Barbour, and Macon County job seekers—including justice-involved adults returning from ADOC custody—to free job search assistance, resume help, WIOA training referrals, and employer connections. Staff coordinate with Troy University adult education partners and East Central Mental Health substance use referrals. Workforce center—not emergency shelter intake.",
        description_es="El Alabama Career Center de Troy conecta buscadores de empleo de los condados Pike, Barbour y Macon—incluidos adultos con antecedentes penales que regresan de custodia de ADOC—a asistencia gratuita de búsqueda de empleo, currículum y referencias WIOA.",
        address="1023 South Brundidge Street", city="Troy", phone="334-566-3920", email="",
        website="https://joblink.alabama.gov",
        eligibility="Open to Pike, Barbour, and Macon County job seekers including justice-involved individuals; core services free.",
        eligibility_es="Abierto a buscadores de empleo de los condados Pike, Barbour y Macon incluidas personas con antecedentes penales; servicios básicos gratuitos.",
        notes="Register at joblink.alabama.gov; pairs with ABPP Troy field office and Food Bank of East Alabama.",
        notes_es="Regístrese en joblink.alabama.gov; se vincula con la oficina de campo ABPP Troy y el Banco de Alimentos del Este de Alabama.",
        hours="Monday–Friday business hours",
        tags="troy|pike|employment|career-center|WIOA|rural-depth|reentry",
        services="Job search assistance|Resume help|WIOA training referrals|Employer connections|Behavioral health referrals",
        county="Pike", served_counties="Pike|Barbour|Macon", coverage="multi",
        _source="https://joblink.alabama.gov", _source_type="government", _confidence="high",
    )

    add(
        name="Alabama Career Center — Centreville (Bibb County)",
        category="employment",
        region="Centreville / Bibb County",
        description="The Centreville Career Center location connects Bibb County job seekers—including justice-involved adults rebuilding employment in rural West Alabama—to free job search assistance, resume help, and WIOA training referrals through West AlabamaWorks and the Tuscaloosa Career Center network. Staff coordinate with Bevill State Community College adult education and Whatley Health Services. Workforce services—not a DHR or legal aid office.",
        description_es="La ubicación del Alabama Career Center en Centreville conecta buscadores de empleo del condado Bibb—incluidos adultos con antecedentes penales que reconstruyen empleo en el oeste rural de Alabama—a asistencia gratuita de búsqueda de empleo, currículum y referencias WIOA.",
        address="183 South Main Street", city="Centreville", phone="205-926-4131", email="",
        website="https://joblink.alabama.gov",
        eligibility="Open to Bibb County job seekers including justice-involved adults; core Career Center services are free.",
        eligibility_es="Abierto a buscadores de empleo del condado Bibb incluidos adultos con antecedentes penales; los servicios básicos del Career Center son gratuitos.",
        notes="Register at joblink.alabama.gov; full-service support also available at the Tuscaloosa Career Center.",
        notes_es="Regístrese en joblink.alabama.gov; apoyo de servicio completo también disponible en el Career Center de Tuscaloosa.",
        hours="Monday–Friday business hours",
        tags="centreville|bibb|employment|career-center|WIOA|rural-depth|reentry",
        services="Job search assistance|Resume help|WIOA training referrals|West AlabamaWorks navigation|Healthcare partner referrals",
        county="Bibb", served_counties="Bibb", coverage="single",
        _source="https://joblink.alabama.gov", _source_type="government", _confidence="high",
    )

    # --- probation-parole: ABPP field offices (paroles.alabama.gov) ---
    add(
        name="Alabama Bureau of Pardons and Paroles — Anniston Field Office",
        category="probation-parole",
        region="Anniston / Calhoun County",
        description="The Alabama Bureau of Pardons and Paroles Anniston Field Office supervises probationers and parolees in Calhoun and Cleburne counties, connecting returning citizens to East AlabamaWorks career centers, Highland Health Systems treatment, and Legal Services Alabama Anniston. Officers conduct office, home, and employment contacts based on supervision level. Field supervision office—not a walk-in SNAP or emergency shelter site.",
        description_es="La Oficina de Campo de Anniston del Buró de Indultos y Libertad Condicional de Alabama supervisa a personas en probatoria y libertad condicional en los condados Calhoun y Cleburne, conectando a quienes regresan con centros de carrera East AlabamaWorks, tratamiento de Highland Health Systems y Legal Services Alabama Anniston.",
        address="1201 Gurnee Avenue, Suite 2", city="Anniston", phone="256-231-1710", email="",
        website="https://paroles.alabama.gov/locations/anniston-field-office/",
        eligibility="Individuals under Alabama Bureau of Pardons and Paroles community supervision in Calhoun or Cleburne counties; report to assigned officer.",
        eligibility_es="Personas bajo supervisión comunitaria del Buró de Indultos y Libertad Condicional de Alabama en los condados Calhoun o Cleburne; repórtese al oficial asignado.",
        notes="Office hours Monday–Friday 8:00 a.m.–5:00 p.m.; pairs with Anniston Career Center and East Central Alabama behavioral health partners.",
        notes_es="Horario de oficina lunes a viernes de 8:00 a.m. a 5:00 p.m.; se vincula con el Career Center de Anniston y aliados de salud conductual del este de Alabama.",
        hours="Monday–Friday, 8:00 a.m.–5:00 p.m.",
        tags="anniston|calhoun|probation-parole|ABPP|rural-depth|reentry",
        services="Calhoun-Cleburne probation supervision|Parole reporting|Workforce referrals|Treatment coordination|Legal aid referrals",
        county="Calhoun", served_counties="Calhoun|Cleburne", coverage="multi",
        _source="https://paroles.alabama.gov/locations/anniston-field-office/", _source_type="government", _confidence="high",
    )

    add(
        name="Alabama Bureau of Pardons and Paroles — Gadsden Field Office",
        category="probation-parole",
        region="Gadsden / Etowah County",
        description="The Alabama Bureau of Pardons and Paroles Gadsden Field Office supervises probationers and parolees in Etowah County, coordinating referrals to the Gadsden Career Center, WellStone behavioral health, and Legal Services Alabama Gadsden for people rebuilding stability after ADOC or county jail release. Field reporting office—not a walk-in benefits or food pantry.",
        description_es="La Oficina de Campo de Gadsden del Buró de Indultos y Libertad Condicional de Alabama supervisa a personas en probatoria y libertad condicional del condado Etowah, coordinando referencias al Career Center de Gadsden, WellStone y Legal Services Alabama Gadsden.",
        address="3200 W Meighan Boulevard", city="Gadsden", phone="256-549-2750", email="",
        website="https://paroles.alabama.gov",
        eligibility="Individuals under ABPP community supervision in Etowah County; report to assigned officer.",
        eligibility_es="Personas bajo supervisión comunitaria de ABPP en el condado Etowah; repórtese al oficial asignado.",
        notes="Closed 12:00–1:00 p.m. for lunch; DeKalb and Cherokee counties served by Fort Payne field office.",
        notes_es="Cerrado de 12:00 a 1:00 p.m. para almuerzo; los condados DeKalb y Cherokee son atendidos por la oficina de campo de Fort Payne.",
        hours="Monday–Friday, 8:00 a.m.–5:00 p.m. (closed 12:00–1:00 p.m.)",
        tags="gadsden|etowah|probation-parole|ABPP|rural-depth|reentry",
        services="Etowah County probation supervision|Parole reporting|Career center referrals|Behavioral health coordination",
        county="Etowah", served_counties="Etowah", coverage="single",
        _source="https://paroles.alabama.gov", _source_type="government", _confidence="high",
    )

    add(
        name="Alabama Bureau of Pardons and Paroles — Fort Payne Field Office",
        category="probation-parole",
        region="Fort Payne / DeKalb County",
        description="The Alabama Bureau of Pardons and Paroles Fort Payne Field Office supervises probationers and parolees in DeKalb and Cherokee counties and operates a Day Reporting Center Lite with substance dependence and job training programming for higher-need supervisees. Officers connect returning citizens to Fort Payne Career Center, Highlands Medical Center, and Legal Services Alabama Gadsden. Field office—not emergency housing intake.",
        description_es="La Oficina de Campo de Fort Payne del Buró de Indultos y Libertad Condicional de Alabama supervisa a personas en probatoria y libertad condicional en los condados DeKalb y Cherokee y opera un Day Reporting Center Lite con programación de dependencia de sustancias y capacitación laboral.",
        address="2001 Jordan Road SW", city="Fort Payne", phone="256-845-3801", email="",
        website="https://paroles.alabama.gov",
        eligibility="Individuals under ABPP community supervision in DeKalb or Cherokee counties; report to assigned officer.",
        eligibility_es="Personas bajo supervisión comunitaria de ABPP en los condados DeKalb o Cherokee; repórtese al oficial asignado.",
        notes="DRC Lite offers cognitive behavioral treatment and educational referrals; pairs with Fort Payne Career Center.",
        notes_es="El DRC Lite ofrece tratamiento cognitivo conductual y referencias educativas; se vincula con el Career Center de Fort Payne.",
        hours="Monday–Friday business hours",
        tags="fort-payne|dekalb|probation-parole|ABPP|DRC-lite|rural-depth|reentry",
        services="DeKalb-Cherokee probation supervision|DRC Lite programming|Substance dependence assistance|Career training referrals",
        county="DeKalb", served_counties="DeKalb|Cherokee", coverage="multi",
        _source="https://paroles.alabama.gov", _source_type="government", _confidence="high",
    )

    add(
        name="Alabama Bureau of Pardons and Paroles — Phenix City Field Office",
        category="probation-parole",
        region="Phenix City / Russell County",
        description="The Alabama Bureau of Pardons and Paroles Phenix City Field Office supervises probationers and parolees in Russell County, connecting supervisees to Opelika Career Center, Food Bank of East Alabama partner pantries, and Legal Services Alabama Opelika. Officers monitor compliance with supervision conditions and refer people leaving custody to workforce and treatment partners. Field office—not a legal aid clinic.",
        description_es="La Oficina de Campo de Phenix City del Buró de Indultos y Libertad Condicional de Alabama supervisa a personas en probatoria y libertad condicional del condado Russell, conectando supervisados con el Career Center de Opelika y Legal Services Alabama Opelika.",
        address="1521 5th Avenue", city="Phenix City", phone="334-298-6521", email="",
        website="https://paroles.alabama.gov/locations/phenix-city-field-office/",
        eligibility="Individuals under ABPP community supervision in Russell County; report to assigned officer.",
        eligibility_es="Personas bajo supervisión comunitaria de ABPP en el condado Russell; repórtese al oficial asignado.",
        notes="Closed 12:00–1:00 p.m. EST for lunch; Lee County served by Opelika field office.",
        notes_es="Cerrado de 12:00 a 1:00 p.m. EST para almuerzo; el condado Lee es atendido por la oficina de campo de Opelika.",
        hours="Monday–Friday, 8:00 a.m.–5:00 p.m. EST (closed 12:00–1:00 p.m.)",
        tags="phenix-city|russell|probation-parole|ABPP|rural-depth|reentry",
        services="Russell County probation supervision|Parole reporting|Workforce referrals|Food bank partner linkages",
        county="Russell", served_counties="Russell", coverage="single",
        _source="https://paroles.alabama.gov/locations/phenix-city-field-office/", _source_type="government", _confidence="high",
    )

    add(
        name="Alabama Bureau of Pardons and Paroles — LaFayette Field Office",
        category="probation-parole",
        region="LaFayette / Chambers County",
        description="The Alabama Bureau of Pardons and Paroles LaFayette Field Office supervises probationers and parolees in Chambers County, referring supervisees to Opelika Career Center, Food Bank of East Alabama, and Legal Services Alabama Opelika for employment and stability supports after release. Field supervision office—not a walk-in cash assistance site.",
        description_es="La Oficina de Campo de LaFayette del Buró de Indultos y Libertad Condicional de Alabama supervisa a personas en probatoria y libertad condicional del condado Chambers, refiriendo supervisados al Career Center de Opelika y al Banco de Alimentos del Este de Alabama.",
        address="1211 South Gilmer Avenue", city="LaFayette", phone="334-864-8881", email="",
        website="https://paroles.alabama.gov",
        eligibility="Individuals under ABPP community supervision in Chambers County; report to assigned officer.",
        eligibility_es="Personas bajo supervisión comunitaria de ABPP en el condado Chambers; repórtese al oficial asignado.",
        notes="Pairs with Opelika Career Center and East Alabama reentry workforce partners.",
        notes_es="Se vincula con el Career Center de Opelika y aliados de reinserción laboral del este de Alabama.",
        hours="Monday–Friday business hours",
        tags="lafayette|chambers|probation-parole|ABPP|rural-depth|reentry",
        services="Chambers County probation supervision|Parole reporting|Employment referrals|Food security partner linkages",
        county="Chambers", served_counties="Chambers", coverage="single",
        _source="https://paroles.alabama.gov", _source_type="government", _confidence="high",
    )

    add(
        name="Alabama Bureau of Pardons and Paroles — Jasper Field Office",
        category="probation-parole",
        region="Jasper / Walker County",
        description="The Alabama Bureau of Pardons and Paroles Jasper Field Office supervises probationers and parolees in Walker County, connecting supervisees to Jasper Career Center, Community Food Bank of Central Alabama, and Legal Services Alabama Birmingham for people rebuilding stability after incarceration. Field reporting office—not emergency shelter intake.",
        description_es="La Oficina de Campo de Jasper del Buró de Indultos y Libertad Condicional de Alabama supervisa a personas en probatoria y libertad condicional del condado Walker, conectando supervisados con el Career Center de Jasper y Legal Services Alabama Birmingham.",
        address="1710 Alabama Avenue", city="Jasper", phone="205-384-7264", email="",
        website="https://paroles.alabama.gov",
        eligibility="Individuals under ABPP community supervision in Walker County; report to assigned officer.",
        eligibility_es="Personas bajo supervisión comunitaria de ABPP en el condado Walker; repórtese al oficial asignado.",
        notes="Pairs with Jasper Career Center and Bevill State Community College adult education.",
        notes_es="Se vincula con el Career Center de Jasper y educación para adultos de Bevill State Community College.",
        hours="Monday–Friday business hours",
        tags="jasper|walker|probation-parole|ABPP|rural-depth|reentry",
        services="Walker County probation supervision|Parole reporting|Career center referrals|Food bank linkages",
        county="Walker", served_counties="Walker", coverage="single",
        _source="https://paroles.alabama.gov", _source_type="government", _confidence="high",
    )

    add(
        name="Alabama Bureau of Pardons and Paroles — Hamilton Field Office",
        category="probation-parole",
        region="Hamilton / Marion County",
        description="The Alabama Bureau of Pardons and Paroles Hamilton Field Office supervises probationers and parolees in Marion County, coordinating referrals to Hamilton Career Center, West Alabama Food Bank partner pantries, and Legal Services Alabama Tuscaloosa for rural northwest Alabama supervisees. Field office—not a DHR benefits application site.",
        description_es="La Oficina de Campo de Hamilton del Buró de Indultos y Libertad Condicional de Alabama supervisa a personas en probatoria y libertad condicional del condado Marion, coordinando referencias al Career Center de Hamilton y Legal Services Alabama Tuscaloosa.",
        address="1440 Military Street South", city="Hamilton", phone="205-921-3701", email="",
        website="https://paroles.alabama.gov",
        eligibility="Individuals under ABPP community supervision in Marion County; report to assigned officer.",
        eligibility_es="Personas bajo supervisión comunitaria de ABPP en el condado Marion; repórtese al oficial asignado.",
        notes="Winston County supervisees coordinate through regional ABPP assignment; call for reporting location.",
        notes_es="Los supervisados del condado Winston coordinan a través de asignación regional de ABPP; llame para ubicación de reporte.",
        hours="Monday–Friday business hours",
        tags="hamilton|marion|probation-parole|ABPP|rural-depth|reentry",
        services="Marion County probation supervision|Parole reporting|Rural workforce referrals|Legal aid coordination",
        county="Marion", served_counties="Marion|Winston", coverage="multi",
        _source="https://paroles.alabama.gov", _source_type="government", _confidence="high",
    )

    add(
        name="Alabama Bureau of Pardons and Paroles — Moulton Field Office",
        category="probation-parole",
        region="Moulton / Lawrence County",
        description="The Alabama Bureau of Pardons and Paroles Moulton Field Office supervises probationers and parolees in Lawrence County, connecting supervisees to Decatur Career Center, Food Bank of North Alabama, and Legal Services Alabama Huntsville. Officers refer people leaving custody to LIHEAP and workforce partners in the Shoals and Tennessee Valley region. Field office—not a food pantry.",
        description_es="La Oficina de Campo de Moulton del Buró de Indultos y Libertad Condicional de Alabama supervisa a personas en probatoria y libertad condicional del condado Lawrence, conectando supervisados con el Career Center de Decatur y el Banco de Alimentos del Norte de Alabama.",
        address="16245 Alabama Highway 157", city="Moulton", phone="256-974-2461", email="",
        website="https://paroles.alabama.gov",
        eligibility="Individuals under ABPP community supervision in Lawrence County; report to assigned officer.",
        eligibility_es="Personas bajo supervisión comunitaria de ABPP en el condado Lawrence; repórtese al oficial asignado.",
        notes="Pairs with Decatur Career Center and CAPNA energy assistance for north Alabama counties.",
        notes_es="Se vincula con el Career Center de Decatur y asistencia energética CAPNA para condados del norte de Alabama.",
        hours="Monday–Friday business hours",
        tags="moulton|lawrence|probation-parole|ABPP|rural-depth|reentry",
        services="Lawrence County probation supervision|Parole reporting|Career center referrals|Energy assistance coordination",
        county="Lawrence", served_counties="Lawrence", coverage="single",
        _source="https://paroles.alabama.gov", _source_type="government", _confidence="high",
    )

    add(
        name="Alabama Bureau of Pardons and Paroles — Oneonta Field Office",
        category="probation-parole",
        region="Oneonta / Blount County",
        description="The Alabama Bureau of Pardons and Paroles Oneonta Field Office supervises probationers and parolees in Blount County, referring supervisees to Oneonta Career Center, Community Food Bank of Central Alabama, and Legal Services Alabama Birmingham. Field supervision office—not a walk-in legal aid clinic.",
        description_es="La Oficina de Campo de Oneonta del Buró de Indultos y Libertad Condicional de Alabama supervisa a personas en probatoria y libertad condicional del condado Blount, refiriendo supervisados al Career Center de Oneonta y Legal Services Alabama Birmingham.",
        address="1001 Second Avenue East", city="Oneonta", phone="205-625-2121", email="",
        website="https://paroles.alabama.gov",
        eligibility="Individuals under ABPP community supervision in Blount County; report to assigned officer.",
        eligibility_es="Personas bajo supervisión comunitaria de ABPP en el condado Blount; repórtese al oficial asignado.",
        notes="Pairs with Oneonta Career Center and Wallace State Community College adult education.",
        notes_es="Se vincula con el Career Center de Oneonta y educación para adultos de Wallace State Community College.",
        hours="Monday–Friday business hours",
        tags="oneonta|blount|probation-parole|ABPP|rural-depth|reentry",
        services="Blount County probation supervision|Parole reporting|Workforce referrals|Food bank partner linkages",
        county="Blount", served_counties="Blount", coverage="single",
        _source="https://paroles.alabama.gov", _source_type="government", _confidence="high",
    )

    add(
        name="Alabama Bureau of Pardons and Paroles — Ashland Field Office",
        category="probation-parole",
        region="Ashland / Clay County",
        description="The Alabama Bureau of Pardons and Paroles Ashland Field Office supervises probationers and parolees in Clay and Coosa counties, connecting supervisees to Anniston Career Center, Highland Health Systems, and Legal Services Alabama Anniston. Field reporting office—not emergency cash or shelter intake.",
        description_es="La Oficina de Campo de Ashland del Buró de Indultos y Libertad Condicional de Alabama supervisa a personas en probatoria y libertad condicional en los condados Clay y Coosa, conectando supervisados con el Career Center de Anniston y Highland Health Systems.",
        address="2 Public Square", city="Ashland", phone="256-354-2611", email="",
        website="https://paroles.alabama.gov",
        eligibility="Individuals under ABPP community supervision in Clay or Coosa counties; report to assigned officer.",
        eligibility_es="Personas bajo supervisión comunitaria de ABPP en los condados Clay o Coosa; repórtese al oficial asignado.",
        notes="Pairs with Anniston Career Center and Coosa Valley Medical Center for rural east-central Alabama.",
        notes_es="Se vincula con el Career Center de Anniston y Coosa Valley Medical Center para el centro-este rural de Alabama.",
        hours="Monday–Friday business hours",
        tags="ashland|clay|probation-parole|ABPP|rural-depth|reentry",
        services="Clay-Coosa probation supervision|Parole reporting|Workforce referrals|Healthcare coordination",
        county="Clay", served_counties="Clay|Coosa", coverage="multi",
        _source="https://paroles.alabama.gov", _source_type="government", _confidence="high",
    )

    add(
        name="Alabama Bureau of Pardons and Paroles — Andalusia Field Office",
        category="probation-parole",
        region="Andalusia / Covington County",
        description="The Alabama Bureau of Pardons and Paroles Andalusia Field Office supervises probationers and parolees in Covington County, coordinating referrals to Andalusia Career Center, Feeding the Gulf Coast partner pantries, and Legal Services Alabama Dothan. Field office—not a substance use residential program.",
        description_es="La Oficina de Campo de Andalusia del Buró de Indultos y Libertad Condicional de Alabama supervisa a personas en probatoria y libertad condicional del condado Covington, coordinando referencias al Career Center de Andalusia y Legal Services Alabama Dothan.",
        address="101 Crestview Avenue", city="Andalusia", phone="334-222-0141", email="",
        website="https://paroles.alabama.gov",
        eligibility="Individuals under ABPP community supervision in Covington County; report to assigned officer.",
        eligibility_es="Personas bajo supervisión comunitaria de ABPP en el condado Covington; repórtese al oficial asignado.",
        notes="Crenshaw County supervisees may report through regional assignment; call office to confirm.",
        notes_es="Los supervisados del condado Crenshaw pueden reportarse mediante asignación regional; llame a la oficina para confirmar.",
        hours="Monday–Friday business hours",
        tags="andalusia|covington|probation-parole|ABPP|rural-depth|reentry",
        services="Covington County probation supervision|Parole reporting|Gulf Coast workforce referrals|Food bank linkages",
        county="Covington", served_counties="Covington|Crenshaw", coverage="multi",
        _source="https://paroles.alabama.gov", _source_type="government", _confidence="high",
    )

    add(
        name="Alabama Bureau of Pardons and Paroles — Greenville Field Office",
        category="probation-parole",
        region="Greenville / Butler County",
        description="The Alabama Bureau of Pardons and Paroles Greenville Field Office supervises probationers and parolees in Butler County, connecting supervisees to Greenville Career Center, Heart of Alabama Food Bank, and Legal Services Alabama Montgomery. Field supervision office—not a walk-in DHR benefits site.",
        description_es="La Oficina de Campo de Greenville del Buró de Indultos y Libertad Condicional de Alabama supervisa a personas en probatoria y libertad condicional del condado Butler, conectando supervisados con el Career Center de Greenville y el Banco de Alimentos Heart of Alabama.",
        address="800 East Commerce Street", city="Greenville", phone="334-382-2681", email="",
        website="https://paroles.alabama.gov",
        eligibility="Individuals under ABPP community supervision in Butler County; report to assigned officer.",
        eligibility_es="Personas bajo supervisión comunitaria de ABPP en el condado Butler; repórtese al oficial asignado.",
        notes="Pairs with Greenville Career Center and Black Belt reentry workforce partners.",
        notes_es="Se vincula con el Career Center de Greenville y aliados de reinserción laboral del Cinturón Negro.",
        hours="Monday–Friday business hours",
        tags="greenville|butler|probation-parole|ABPP|rural-depth|reentry",
        services="Butler County probation supervision|Parole reporting|Employment referrals|Food security coordination",
        county="Butler", served_counties="Butler", coverage="single",
        _source="https://paroles.alabama.gov", _source_type="government", _confidence="high",
    )

    add(
        name="Alabama Bureau of Pardons and Paroles — Troy Field Office",
        category="probation-parole",
        region="Troy / Pike County",
        description="The Alabama Bureau of Pardons and Paroles Troy Field Office supervises probationers and parolees in Pike, Barbour, and Macon counties, referring supervisees to Troy Career Center, Food Bank of East Alabama, and East Central Mental Health. Field office—not emergency housing placement.",
        description_es="La Oficina de Campo de Troy del Buró de Indultos y Libertad Condicional de Alabama supervisa a personas en probatoria y libertad condicional en los condados Pike, Barbour y Macon, refiriendo supervisados al Career Center de Troy y East Central Mental Health.",
        address="1203 South Brundidge Street", city="Troy", phone="334-566-1511", email="",
        website="https://paroles.alabama.gov",
        eligibility="Individuals under ABPP community supervision in Pike, Barbour, or Macon counties; report to assigned officer.",
        eligibility_es="Personas bajo supervisión comunitaria de ABPP en los condados Pike, Barbour o Macon; repórtese al oficial asignado.",
        notes="Pairs with Troy Career Center and East Central Mental Health substance use services.",
        notes_es="Se vincula con el Career Center de Troy y servicios de uso de sustancias de East Central Mental Health.",
        hours="Monday–Friday business hours",
        tags="troy|pike|probation-parole|ABPP|rural-depth|reentry",
        services="Pike-area probation supervision|Parole reporting|Workforce referrals|Substance use treatment coordination",
        county="Pike", served_counties="Pike|Barbour|Macon", coverage="multi",
        _source="https://paroles.alabama.gov", _source_type="government", _confidence="high",
    )

    add(
        name="Alabama Bureau of Pardons and Paroles — Selma Field Office",
        category="probation-parole",
        region="Selma / Dallas County",
        description="The Alabama Bureau of Pardons and Paroles Selma Field Office supervises probationers and parolees in Dallas County, connecting supervisees to Alabama Career Center Selma, West Alabama Food Bank, and Legal Services Alabama Selma. Officers coordinate Black Belt reentry referrals with Wallace Community College adult education. Field office—not a walk-in food pantry.",
        description_es="La Oficina de Campo de Selma del Buró de Indultos y Libertad Condicional de Alabama supervisa a personas en probatoria y libertad condicional del condado Dallas, conectando supervisados con el Alabama Career Center Selma y Legal Services Alabama Selma.",
        address="1012 Water Avenue", city="Selma", phone="334-874-1720", email="",
        website="https://paroles.alabama.gov",
        eligibility="Individuals under ABPP community supervision in Dallas County; report to assigned officer.",
        eligibility_es="Personas bajo supervisión comunitaria de ABPP en el condado Dallas; repórtese al oficial asignado.",
        notes="Pairs with Selma Career Center and CSP of West Alabama LIHEAP programs.",
        notes_es="Se vincula con el Career Center de Selma y programas LIHEAP de CSP del Oeste de Alabama.",
        hours="Monday–Friday business hours",
        tags="selma|dallas|probation-parole|ABPP|rural-depth|reentry",
        services="Dallas County probation supervision|Parole reporting|Black Belt workforce referrals|Legal aid coordination",
        county="Dallas", served_counties="Dallas", coverage="single",
        _source="https://paroles.alabama.gov", _source_type="government", _confidence="high",
    )

    add(
        name="Alabama Bureau of Pardons and Paroles — Evergreen Field Office",
        category="probation-parole",
        region="Evergreen / Conecuh County",
        description="The Alabama Bureau of Pardons and Paroles Evergreen Field Office supervises probationers and parolees in Conecuh County, referring supervisees to regional career centers, Feeding the Gulf Coast partner pantries, and Legal Services Alabama Mobile. Field supervision office—not a healthcare clinic.",
        description_es="La Oficina de Campo de Evergreen del Buró de Indultos y Libertad Condicional de Alabama supervisa a personas en probatoria y libertad condicional del condado Conecuh, refiriendo supervisados a centros de carrera regionales y Legal Services Alabama Mobile.",
        address="100 Court Street", city="Evergreen", phone="251-578-1212", email="",
        website="https://paroles.alabama.gov",
        eligibility="Individuals under ABPP community supervision in Conecuh County; report to assigned officer.",
        eligibility_es="Personas bajo supervisión comunitaria de ABPP en el condado Conecuh; repórtese al oficial asignado.",
        notes="Pairs with Evergreen Medical Center and Community Action Agency of South Alabama.",
        notes_es="Se vincula con Evergreen Medical Center y Community Action Agency of South Alabama.",
        hours="Monday–Friday business hours",
        tags="evergreen|conecuh|probation-parole|ABPP|rural-depth|reentry",
        services="Conecuh County probation supervision|Parole reporting|Gulf Coast workforce referrals|Healthcare coordination",
        county="Conecuh", served_counties="Conecuh", coverage="single",
        _source="https://paroles.alabama.gov", _source_type="government", _confidence="high",
    )

    # --- healthcare & substance-use-treatment ---
    add(
        name="Highland Health Systems",
        category="substance-use-treatment",
        region="Anniston / Multi-County",
        description="Highland Health Systems is a Certified Community Behavioral Health Clinic in Anniston providing outpatient and intensive outpatient substance use treatment, co-occurring mental health care, and crisis stabilization for residents of Calhoun, Cleburne, Talladega, and Clay counties including justice-involved adults on ABPP supervision. Medicaid, Medicare, and sliding-fee services are available. Behavioral health provider—not a walk-in DHR or career center.",
        description_es="Highland Health Systems es una Clínica Comunitaria de Salud Conductual Certificada en Anniston que ofrece tratamiento ambulatorio e intensivo ambulatorio de uso de sustancias, atención de salud mental coexistente y estabilización de crisis para residentes de los condados Calhoun, Cleburne, Talladega y Clay incluidos adultos con antecedentes penales bajo supervisión de ABPP.",
        address="331 East 8th Street", city="Anniston", phone="256-236-3403", email="",
        website="https://mh.alabama.gov/at_biz_dir/highland-health-systems/",
        eligibility="Residents in the east-central Alabama service area; Medicaid and uninsured patients welcome including justice-involved adults.",
        eligibility_es="Residentes en el área de servicio del centro-este de Alabama; pacientes con Medicaid y sin seguro bienvenidos incluidos adultos con antecedentes penales.",
        notes="Call 256-236-3403 for intake; pairs with ABPP Anniston and Anniston Career Center reentry partners.",
        notes_es="Llame al 256-236-3403 para admisión; se vincula con aliados de reinserción de ABPP Anniston y Career Center de Anniston.",
        hours="Monday–Friday clinic hours; crisis services available",
        tags="anniston|calhoun|substance-use-treatment|mental-health|CCBHC|rural-depth|reentry",
        services="Outpatient substance use treatment|Intensive outpatient programs|Co-occurring mental health|Crisis stabilization|Medicaid and sliding-fee care",
        county="Calhoun", served_counties="Calhoun|Cleburne|Talladega|Clay", coverage="multi",
        _source="https://mh.alabama.gov/at_biz_dir/highland-health-systems/", _source_type="government", _confidence="high",
    )

    add(
        name="East Central Mental Health Center",
        category="substance-use-treatment",
        region="Troy / Multi-County",
        description="East Central Mental Health Center is a comprehensive community mental health center providing substance abuse and mental health services to residents of Bullock, Macon, and Pike counties, including outpatient treatment and crisis support for justice-involved adults rebuilding stability after incarceration. A public nonprofit CMHC—not a probation reporting or legal aid office.",
        description_es="East Central Mental Health Center es un centro comunitario integral de salud mental que brinda servicios de abuso de sustancias y salud mental a residentes de los condados Bullock, Macon y Pike, incluido tratamiento ambulatorio y apoyo de crisis para adultos con antecedentes penales.",
        address="200 Cherry Street", city="Troy", phone="334-566-6000", email="",
        website="https://www.eastcentralmhc.org",
        eligibility="Residents of Bullock, Macon, or Pike counties; services provided regardless of ability to pay for eligible clients.",
        eligibility_es="Residentes de los condados Bullock, Macon o Pike; servicios proporcionados sin importar capacidad de pago para clientes elegibles.",
        notes="Call 334-566-6000 for intake; pairs with Troy Career Center and ABPP Troy field office.",
        notes_es="Llame al 334-566-6000 para admisión; se vincula con el Career Center de Troy y la oficina de campo ABPP Troy.",
        hours="Monday–Friday business hours",
        tags="troy|pike|substance-use-treatment|mental-health|CMHC|rural-depth|reentry",
        services="Substance abuse treatment|Mental health counseling|Crisis support|Outpatient programs|Intellectual disabilities services",
        county="Pike", served_counties="Bullock|Macon|Pike", coverage="multi",
        _source="https://www.eastcentralmhc.org", _source_type="government", _confidence="high",
    )

    add(
        name="Northeast Alabama Health Services — Fort Payne FQHC",
        category="healthcare",
        region="Fort Payne / DeKalb County",
        description="Northeast Alabama Health Services is a Federally Qualified Health Center in Fort Payne serving DeKalb and Cherokee counties with primary care, dental, behavioral health, and sliding-fee services for uninsured and Medicaid patients including returning citizens establishing a medical home. Direct clinical care—not a probation or workforce office.",
        description_es="Northeast Alabama Health Services es un Centro de Salud Calificado Federalmente en Fort Payne que sirve a los condados DeKalb y Cherokee con atención primaria, dental, salud conductual y servicios de tarifa móvil para pacientes sin seguro y con Medicaid incluidos ciudadanos que regresan.",
        address="3840 Gault Avenue North", city="Fort Payne", phone="256-844-4975", email="",
        website="https://www.neahs.org",
        eligibility="DeKalb and Cherokee County residents; sliding-fee discount based on income; Medicaid and Medicare accepted.",
        eligibility_es="Residentes de los condados DeKalb y Cherokee; descuento de tarifa móvil según ingresos; se aceptan Medicaid y Medicare.",
        notes="Call 256-844-4975 for Fort Payne clinic appointments; pairs with Fort Payne Career Center and ABPP Fort Payne.",
        notes_es="Llame al 256-844-4975 para citas en la clínica de Fort Payne; se vincula con el Career Center de Fort Payne y ABPP Fort Payne.",
        hours="Monday–Friday clinic hours",
        tags="fort-payne|dekalb|healthcare|FQHC|primary-care|rural-depth|reentry",
        services="Primary medical care|Dental care|Behavioral health|Sliding-fee program|Medicaid enrollment assistance",
        county="DeKalb", served_counties="DeKalb|Cherokee", coverage="multi",
        _source="https://opengovus.com/npi/1831346386", _source_type="nonprofit", _confidence="high",
    )

    add(
        name="Stringfellow Memorial Hospital",
        category="healthcare",
        region="Anniston / Calhoun County",
        description="Stringfellow Memorial Hospital in Anniston provides 24-hour emergency care, inpatient and outpatient medical services, and primary care access for Calhoun County residents including returning citizens without a medical home after release. The hospital accepts Medicaid, Medicare, and uninsured patients for eligible emergency and follow-up services. Acute-care hospital—not a walk-in benefits office.",
        description_es="Stringfellow Memorial Hospital en Anniston ofrece atención de emergencia las 24 horas, servicios médicos hospitalarios y ambulatorios, y acceso a atención primaria para residentes del condado Calhoun incluidos ciudadanos que regresan sin hogar médico tras su liberación.",
        address="301 East 18th Street", city="Anniston", phone="256-235-8900", email="",
        website="https://www.stringfellow.org",
        eligibility="Open to Calhoun County residents; emergency care regardless of ability to pay; Medicaid and uninsured patients accepted.",
        eligibility_es="Abierto a residentes del condado Calhoun; atención de emergencia sin importar capacidad de pago; se aceptan pacientes con Medicaid y sin seguro.",
        notes="Emergency department open 24/7; pairs with Highland Health Systems for behavioral health referrals.",
        notes_es="Departamento de emergencias abierto las 24 horas; se vincula con Highland Health Systems para referencias de salud conductual.",
        hours="Emergency 24/7; outpatient hours vary",
        tags="anniston|calhoun|healthcare|hospital|emergency-care|rural-depth|reentry",
        services="Emergency care|Inpatient medical services|Outpatient clinics|Primary care access|Diagnostic imaging",
        county="Calhoun", served_counties="Calhoun", coverage="single",
        _source="https://www.stringfellow.org", _source_type="nonprofit", _confidence="high",
    )

    add(
        name="Coosa Valley Medical Center",
        category="healthcare",
        region="Sylacauga / Talladega County",
        description="Coosa Valley Medical Center in Sylacauga provides 24-hour emergency care, inpatient services, and outpatient primary care for Talladega and Coosa county residents including justice-involved adults reestablishing healthcare after incarceration. The hospital serves a rural east-central Alabama region with limited FQHC access. Hospital—not a DHR or probation office.",
        description_es="Coosa Valley Medical Center en Sylacauga ofrece atención de emergencia las 24 horas, servicios hospitalarios y atención primaria ambulatoria para residentes de los condados Talladega y Coosa incluidos adultos con antecedentes penales que restablecen atención médica tras encarcelación.",
        address="315 West Hickory Street", city="Sylacauga", phone="256-249-5000", email="",
        website="https://www.coosavalleyhealth.com",
        eligibility="Open to Talladega and Coosa County residents; emergency care regardless of ability to pay.",
        eligibility_es="Abierto a residentes de los condados Talladega y Coosa; atención de emergencia sin importar capacidad de pago.",
        notes="Emergency department open 24/7; pairs with Anniston Career Center and ABPP Ashland field office.",
        notes_es="Departamento de emergencias abierto las 24 horas; se vincula con el Career Center de Anniston y la oficina de campo ABPP Ashland.",
        hours="Emergency 24/7",
        tags="sylacauga|talladega|healthcare|hospital|emergency-care|rural-depth|reentry",
        services="Emergency care|Inpatient services|Outpatient primary care|Laboratory and imaging|Rural health access",
        county="Talladega", served_counties="Talladega|Coosa", coverage="multi",
        _source="https://www.coosavalleyhealth.com", _source_type="nonprofit", _confidence="high",
    )

    add(
        name="Whatley Health Services — Centreville Clinic",
        category="healthcare",
        region="Centreville / Bibb County",
        description="Whatley Health Services operates a Federally Qualified Health Center clinic in Centreville providing primary medical, dental, and behavioral health care on a sliding-fee scale for Bibb County residents including uninsured, Medicaid, and justice-involved adults establishing local care after release. Part of the West Alabama FQHC network headquartered in Tuscaloosa. Outpatient clinic—not a hospital emergency department.",
        description_es="Whatley Health Services opera una clínica del Centro de Salud Calificado Federalmente en Centreville que ofrece atención médica primaria, dental y de salud conductual con tarifa móvil para residentes del condado Bibb incluidos adultos con antecedentes penales que establecen atención local tras su liberación.",
        address="260 Walnut Street", city="Centreville", phone="205-926-3296", email="",
        website="https://whatleyhealth.org",
        eligibility="Bibb County residents of all ages; sliding-fee based on income; Medicaid and Medicare accepted.",
        eligibility_es="Residentes del condado Bibb de todas las edades; tarifa móvil según ingresos; se aceptan Medicaid y Medicare.",
        notes="Call 205-926-3296 for appointments; mobile health unit serves rural West Alabama counties.",
        notes_es="Llame al 205-926-3296 para citas; la unidad móvil de salud sirve condados rurales del oeste de Alabama.",
        hours="Monday–Friday clinic hours",
        tags="centreville|bibb|healthcare|FQHC|primary-care|rural-depth|reentry",
        services="Primary medical care|Dental care|Behavioral health|Sliding-fee program|Mobile health unit",
        county="Bibb", served_counties="Bibb", coverage="single",
        _source="https://whatleyhealth.org", _source_type="nonprofit", _confidence="high",
    )

    add(
        name="Mizell Memorial Hospital",
        category="healthcare",
        region="Opp / Covington County",
        description="Mizell Memorial Hospital in Opp provides 24-hour emergency care, inpatient medical services, and rural health clinic primary care for Covington and Crenshaw county residents including returning citizens without insurance reestablishing a medical home. A critical access hospital serving south-central Alabama—not a walk-in probation or legal aid office.",
        description_es="Mizell Memorial Hospital en Opp ofrece atención de emergencia las 24 horas, servicios médicos hospitalarios y atención primaria en clínica de salud rural para residentes de los condados Covington y Crenshaw incluidos ciudadanos que regresan sin seguro que restablecen un hogar médico.",
        address="702 North Main Street", city="Opp", phone="334-493-3541", email="",
        website="https://www.mizellmemorialhospital.com",
        eligibility="Open to Covington and Crenshaw County residents; emergency care regardless of ability to pay.",
        eligibility_es="Abierto a residentes de los condados Covington y Crenshaw; atención de emergencia sin importar capacidad de pago.",
        notes="Emergency department open 24/7; pairs with Andalusia Career Center and Feeding the Gulf Coast.",
        notes_es="Departamento de emergencias abierto las 24 horas; se vincula con el Career Center de Andalusia y Feeding the Gulf Coast.",
        hours="Emergency 24/7",
        tags="opp|covington|healthcare|hospital|emergency-care|rural-depth|reentry",
        services="Emergency care|Inpatient medical services|Rural health clinic|Primary care access|Diagnostic services",
        county="Covington", served_counties="Covington|Crenshaw", coverage="multi",
        _source="https://www.mizellmemorialhospital.com", _source_type="nonprofit", _confidence="high",
    )

    # --- food-nutrition: regional food banks (Feeding Alabama network) ---
    add(
        name="Food Bank of East Alabama",
        category="food-nutrition",
        region="Auburn / Multi-County",
        description="The Food Bank of East Alabama distributes food through more than 175 partner agencies across Chambers, Lee, Macon, Russell, Tallapoosa, Barbour, and Randolph counties, helping returning citizens and low-income families access partner pantries, mobile distributions, and senior meal programs. Regional food bank hub—not a direct walk-in pantry for individuals.",
        description_es="El Banco de Alimentos del Este de Alabama distribuye alimentos a través de más de 175 agencias aliadas en los condados Chambers, Lee, Macon, Russell, Tallapoosa, Barbour y Randolph, ayudando a ciudadanos que regresan y familias de bajos ingresos a acceder a despensas aliadas y distribuciones móviles.",
        address="355 Industry Drive", city="Auburn", phone="334-821-9006", email="food-bank@foodbankofeastalabama.com",
        website="https://foodbankofeastalabama.com",
        eligibility="Open to east Alabama residents needing food assistance through partner pantries and programs.",
        eligibility_es="Abierto a residentes del este de Alabama que necesitan asistencia alimentaria mediante despensas y programas aliados.",
        notes="Find partner pantries at foodbankofeastalabama.com/get-help/find-a-food-pantry; serves seven-county east-central region.",
        notes_es="Encuentre despensas aliadas en foodbankofeastalabama.com/get-help/find-a-food-pantry; sirve región de siete condados del centro-este.",
        hours="Monday–Friday business hours",
        tags="auburn|lee|food-nutrition|food-bank|rural-depth|reentry",
        services="Partner pantry network|Mobile food distributions|Senior meal programs|Backpack programs|SNAP outreach referrals",
        county="Lee", served_counties="Chambers|Lee|Macon|Russell|Tallapoosa|Barbour|Randolph", coverage="multi",
        _source="https://foodbankofeastalabama.com/about-us/", _source_type="nonprofit", _confidence="high",
    )

    add(
        name="Community Food Bank of Central Alabama — Northeast Region",
        category="food-nutrition",
        region="Anniston / Multi-County",
        description="The Community Food Bank of Central Alabama serves northeast counties including Calhoun, Cherokee, Clay, Cleburne, Etowah, Talladega, and Winston through a network of more than 300 partner pantries and mobile distributions from its Bessemer warehouse, connecting justice-involved adults to groceries while rebuilding stability. Regional food bank—not a direct walk-in pantry.",
        description_es="El Banco de Alimentos Comunitario de Alabama Central sirve condados del noreste incluyendo Calhoun, Cherokee, Clay, Cleburne, Etowah, Talladega y Winston a través de una red de más de 300 despensas aliadas y distribuciones móviles.",
        address="4336 Turin Drive", city="Bessemer", phone="205-942-8911", email="",
        website="https://feedingal.org",
        eligibility="Open to residents in the Central Alabama food bank service area needing food through partner pantries.",
        eligibility_es="Abierto a residentes en el área de servicio del banco de alimentos de Alabama Central que necesitan alimentos mediante despensas aliadas.",
        notes="Find partner pantries at feedingal.org; per Feeding Alabama network covers Winston, Talladega, and northeast rural counties.",
        notes_es="Encuentre despensas aliadas en feedingal.org; según la red Feeding Alabama cubre Winston, Talladega y condados rurales del noreste.",
        hours="Monday–Friday business hours",
        tags="anniston|calhoun|food-nutrition|food-bank|rural-depth|reentry",
        services="Partner pantry network|Mobile food distribution|SNAP outreach|Northeast Alabama county coverage",
        county="Calhoun", served_counties="Calhoun|Cherokee|Clay|Cleburne|Etowah|Talladega|Winston", coverage="multi",
        _source="https://feedingalabama.org/alabama-food-bank-network/", _source_type="nonprofit", _confidence="high",
    )

    add(
        name="Heart of Alabama Food Bank — River Region Extension",
        category="food-nutrition",
        region="Montgomery / Multi-County",
        description="Heart of Alabama Food Bank distributes groceries through partner agencies across Butler, Chilton, Coosa, Crenshaw, and surrounding River Region counties, helping returning citizens and low-income families access food through affiliated pantries and mobile giveaways beyond Montgomery's urban core. Regional food bank hub—not a direct walk-in pantry.",
        description_es="El Banco de Alimentos Heart of Alabama distribuye comestibles a través de agencias aliadas en los condados Butler, Chilton, Coosa, Crenshaw y circundantes de la región del río, ayudando a ciudadanos que regresan y familias de bajos ingresos a acceder a alimentos.",
        address="521 Trade Center Street", city="Montgomery", phone="334-263-3784", email="",
        website="https://hafb.org",
        eligibility="Open to River Region residents needing food assistance through partner agencies in Butler, Chilton, Coosa, and Crenshaw counties.",
        eligibility_es="Abierto a residentes de la región del río que necesitan asistencia alimentaria mediante agencias aliadas en los condados Butler, Chilton, Coosa y Crenshaw.",
        notes="Toll-free 1-800-768-3784; find help at hafb.org/find-help per Feeding Alabama network county assignments.",
        notes_es="Línea gratuita 1-800-768-3784; encuentre ayuda en hafb.org/find-help según asignaciones de condados de la red Feeding Alabama.",
        hours="Monday–Friday business hours",
        tags="montgomery|butler|food-nutrition|food-bank|river-region|rural-depth|reentry",
        services="Partner agency food distribution|Mobile food giveaways|River Region county coverage|SNAP outreach referrals",
        county="Butler", served_counties="Butler|Chilton|Coosa|Crenshaw", coverage="multi",
        _source="https://feedingalabama.org/alabama-food-bank-network/", _source_type="nonprofit", _confidence="high",
    )

    add(
        name="Feeding the Gulf Coast — South Alabama Region",
        category="food-nutrition",
        region="Theodore / Multi-County",
        description="Feeding the Gulf Coast distributes food through partner pantries and mobile programs across Covington, Conecuh, Clarke, Monroe, and Escambia counties in south Alabama, helping justice-involved adults and families find the nearest food distribution through an online pantry locator. Regional food bank warehouse—not a direct walk-in grocery site.",
        description_es="Feeding the Gulf Coast distribuye alimentos a través de despensas aliadas y programas móviles en los condados Covington, Conecuh, Clarke, Monroe y Escambia en el sur de Alabama, ayudando a adultos con antecedentes penales y familias a encontrar la distribución de alimentos más cercana.",
        address="5248 Mobile South Street", city="Theodore", phone="251-653-1617", email="",
        website="https://www.feedingthegulfcoast.org",
        eligibility="Open to south Alabama residents needing food assistance through partner pantries and mobile distributions.",
        eligibility_es="Abierto a residentes del sur de Alabama que necesitan asistencia alimentaria mediante despensas aliadas y distribuciones móviles.",
        notes="Find pantries at feedingthegulfcoast.org/find-help/find-a-pantry; per Feeding Alabama serves Covington and Conecuh counties.",
        notes_es="Encuentre despensas en feedingthegulfcoast.org/find-help/find-a-pantry; según Feeding Alabama sirve los condados Covington y Conecuh.",
        hours="Monday–Friday business hours",
        tags="theodore|covington|food-nutrition|food-bank|gulf-coast|rural-depth|reentry",
        services="Partner pantry network|Mobile food distributions|South Alabama county coverage|SNAP referral partners",
        county="Covington", served_counties="Covington|Conecuh|Clarke|Monroe|Escambia", coverage="multi",
        _source="https://feedingalabama.org/alabama-food-bank-network/", _source_type="nonprofit", _confidence="high",
    )

    # --- legal-aid: West Alabama office (not yet in build) ---
    add(
        name="Legal Services Alabama — Tuscaloosa Regional Office",
        category="legal-aid",
        region="Tuscaloosa / West Alabama",
        description="Legal Services Alabama's Tuscaloosa office provides free civil legal aid to low-income residents of Bibb, Fayette, Greene, Hale, Lamar, Marion, Pickens, Tuscaloosa, Walker, and Winston counties, including housing, public benefits, family law, and criminal record relief for justice-involved adults. Civil cases only—not criminal defense. Apply through the statewide intake line before visiting.",
        description_es="La oficina regional de Tuscaloosa de Legal Services Alabama ofrece asistencia legal civil gratuita a residentes de bajos ingresos de los condados Bibb, Fayette, Greene, Hale, Lamar, Marion, Pickens, Tuscaloosa, Walker y Winston, incluyendo vivienda, beneficios públicos y alivio de antecedentes penales.",
        address="2315 9th Street, Suite 3A", city="Tuscaloosa", phone="205-758-7503", email="",
        website="https://legalservicesalabama.org",
        eligibility="Low-income residents at or below 125% of the federal poverty level in the Tuscaloosa office's 10-county West Alabama service area.",
        eligibility_es="Residentes de bajos ingresos al 125% o menos del nivel federal de pobreza en el área de servicio de 10 condados de la oficina de Tuscaloosa.",
        notes="Apply at 866-456-4995 or alslegal.org; pairs with West Alabama Food Bank and Whatley Health Services.",
        notes_es="Solicite al 866-456-4995 o alslegal.org; se vincula con el Banco de Alimentos del Oeste de Alabama y Whatley Health Services.",
        hours="Monday–Friday business hours",
        tags="tuscaloosa|greene|legal-aid|west-alabama|rural-depth|reentry",
        services="Civil legal representation|Housing and eviction defense|Public benefits advocacy|Record relief|Family law",
        county="Tuscaloosa", served_counties="Bibb|Fayette|Greene|Hale|Lamar|Marion|Pickens|Tuscaloosa|Walker|Winston", coverage="multi",
        _source="https://legalservicesalabama.org/local_offices_staff/", _source_type="nonprofit", _confidence="high",
    )

    # --- housing ---
    add(
        name="Interfaith Ministries Tuscaloosa — Housing Services",
        category="housing",
        region="Tuscaloosa / West Alabama",
        description="Interfaith Ministries Tuscaloosa provides emergency shelter, transitional housing, and homelessness prevention assistance for unhoused adults and families in Greene, Hale, Bibb, Marion, Sumter, and Tuscaloosa counties including returning citizens with no safe discharge plan after incarceration. Case managers connect residents to Whatley Health, West Alabama Food Bank, and Alabama Career Center partners. Direct housing services—not a legal aid or DHR office.",
        description_es="Interfaith Ministries Tuscaloosa brinda refugio de emergencia, vivienda transicional y asistencia de prevención de la falta de vivienda para adultos y familias sin hogar en los condados Greene, Hale, Bibb, Marion, Sumter y Tuscaloosa incluidos ciudadanos que regresan sin un plan seguro de alta tras encarcelación.",
        address="1721 22nd Avenue", city="Tuscaloosa", phone="205-758-3828", email="",
        website="https://www.interfaithministries-tuscaloosa.org",
        eligibility="Unhoused or at-risk adults and families in the West Alabama service area; justice-involved adults accepted for shelter and prevention programs.",
        eligibility_es="Adultos y familias sin hogar o en riesgo en el área de servicio del oeste de Alabama; adultos con antecedentes penales aceptados para programas de refugio y prevención.",
        notes="Call 205-758-3828 for intake; pairs with CSP of West Alabama and Legal Services Alabama Tuscaloosa.",
        notes_es="Llame al 205-758-3828 para admisión; se vincula con CSP del Oeste de Alabama y Legal Services Alabama Tuscaloosa.",
        hours="Monday–Friday business hours; after-hours shelter line available",
        tags="tuscaloosa|greene|housing|emergency-shelter|transitional|rural-depth|reentry",
        services="Emergency shelter|Transitional housing|Homelessness prevention|Case management|Workforce partner referrals",
        county="Tuscaloosa", served_counties="Greene|Hale|Bibb|Marion|Sumter|Tuscaloosa", coverage="multi",
        _source="https://www.interfaithministries-tuscaloosa.org", _source_type="nonprofit", _confidence="high",
    )

    add(
        name="Turning Point — Domestic Violence & Housing Services",
        category="housing",
        region="Auburn / Lee County",
        description="Turning Point provides emergency shelter, transitional housing, and crisis intervention for survivors of domestic violence and homelessness in Lee, Russell, Chambers, and Macon counties, including returning citizens fleeing abuse or instability after release. Advocates connect clients to Opelika Career Center, Food Bank of East Alabama, and Legal Services Alabama Opelika. Confidential shelter—not a probation reporting office.",
        description_es="Turning Point brinda refugio de emergencia, vivienda transicional e intervención en crisis para sobrevivientes de violencia doméstica y falta de vivienda en los condados Lee, Russell, Chambers y Macon, incluidos ciudadanos que regresan que huyen de abuso o inestabilidad tras su liberación.",
        address="1301 Gatewood Drive", city="Auburn", phone="334-745-1545", email="",
        website="https://www.turningpointdv.org",
        eligibility="Survivors of domestic violence and unhoused individuals in Lee, Russell, Chambers, and Macon counties; crisis line available 24/7.",
        eligibility_es="Sobrevivientes de violencia doméstica e individuos sin hogar en los condados Lee, Russell, Chambers y Macon; línea de crisis disponible las 24 horas.",
        notes="24-hour crisis line 334-745-1545; confidential location; pairs with East Alabama reentry workforce partners.",
        notes_es="Línea de crisis 24 horas 334-745-1545; ubicación confidencial; se vincula con aliados de reinserción laboral del este de Alabama.",
        hours="Crisis line 24/7; office Monday–Friday business hours",
        tags="auburn|lee|housing|emergency-shelter|domestic-violence|rural-depth|reentry",
        services="Emergency shelter|Transitional housing|Crisis intervention|Legal advocacy referrals|Workforce navigation",
        county="Lee", served_counties="Lee|Russell|Chambers|Macon", coverage="multi",
        _source="https://www.turningpointdv.org", _source_type="nonprofit", _confidence="high",
    )

    add(
        name="Habitat for Humanity of Greater Birmingham — Rural Repair Program",
        category="housing",
        region="Birmingham / Multi-County",
        description="Habitat for Humanity of Greater Birmingham operates a Rural Repair Program providing critical home repairs and accessibility modifications for low-income homeowners in Walker, Blount, and rural Jefferson-area counties including returning citizens aging in place after incarceration. The program addresses substandard housing conditions—not emergency nightly shelter intake.",
        description_es="Habitat for Humanity of Greater Birmingham opera un Programa de Reparación Rural que brinda reparaciones críticas del hogar y modificaciones de accesibilidad para propietarios de bajos ingresos en los condados Walker, Blount y rurales del área de Jefferson incluidos ciudadanos que regresan que envejecen en su lugar tras encarcelación.",
        address="701 2nd Avenue South", city="Birmingham", phone="205-780-1234", email="",
        website="https://www.habitatbirmingham.org",
        eligibility="Low-income homeowners in Walker, Blount, and eligible rural counties; income and homeownership documentation required.",
        eligibility_es="Propietarios de bajos ingresos en Walker, Blount y condados rurales elegibles; se requiere documentación de ingresos y propiedad.",
        notes="Apply through habitatbirmingham.org; pairs with Jasper Career Center and Community Food Bank of Central Alabama.",
        notes_es="Solicite a través de habitatbirmingham.org; se vincula con el Career Center de Jasper y el Banco de Alimentos Comunitario de Alabama Central.",
        hours="Monday–Friday business hours",
        tags="birmingham|walker|housing|home-repair|rural-depth|reentry",
        services="Critical home repairs|Accessibility modifications|Rural homeowner assistance|Housing stability support",
        county="Walker", served_counties="Walker|Blount|Jefferson", coverage="multi",
        _source="https://www.habitatbirmingham.org", _source_type="nonprofit", _confidence="high",
    )
