"""Direct-service pins for rural Alabama counties that would otherwise only have a DHR benefits row."""


def register_thin_counties(add):
    """Program-level rows for thin Black Belt and rural counties — health, food, employment, education."""

    add(
        name="Cahaba Medical Care — Camden Clinic",
        category="healthcare",
        region="Camden / Wilcox County",
        description="Cahaba Medical Care operates a Federally Qualified Health Center clinic in Camden providing primary medical care, women's health and prenatal services, chronic disease management, and behavioral health screening for Wilcox County residents, including uninsured and Medicaid patients such as returning citizens reestablishing a local medical home after release. The nonprofit FQHC network also serves neighboring Perry, Bibb, Chilton, Shelby, and Jefferson counties with a discounted sliding-fee schedule based on income and family size. A primary care clinic — not a hospital emergency department.",
        description_es="Cahaba Medical Care opera una clínica FQHC en Camden que ofrece atención médica primaria, salud de la mujer y atención prenatal, manejo de enfermedades crónicas y evaluación de salud conductual para residentes del condado Wilcox, incluidos pacientes sin seguro y con Medicaid como ciudadanos que regresan y reestablecen un hogar médico local tras su liberación. La red FQHC también atiende a los condados vecinos de Perry, Bibb, Chilton, Shelby y Jefferson con una escala de tarifas móvil según ingresos. Es una clínica de atención primaria, no una sala de emergencias hospitalaria.",
        address="321 Whiskey Run Road",
        city="Camden",
        phone="334-682-4128",
        email="contact@cahabamedicalcare.com",
        website="https://cahabamedicalcare.com/who-we-are",
        eligibility="Wilcox County residents of all ages; sliding-fee discount based on income and family size; Medicaid, Medicare, and most insurance accepted; criminal record is not a stated barrier to care.",
        eligibility_es="Residentes del condado Wilcox de todas las edades; descuento de tarifa móvil según ingresos y tamaño familiar; se aceptan Medicaid, Medicare y la mayoría de seguros; los antecedentes penales no son una barrera indicada para recibir atención.",
        notes="Call 334-682-4128 for an appointment; walk-ins accepted as capacity allows; closed daily for lunch.",
        notes_es="Llame al 334-682-4128 para una cita; se aceptan pacientes sin cita según disponibilidad; cerrado diariamente para el almuerzo.",
        hours="Monday–Friday, 8:00 a.m.–5:00 p.m.",
        tags="camden|wilcox|healthcare|FQHC|primary-care|sliding-fee|reentry",
        services="Primary medical care|Prenatal and women's health|Chronic disease management|Behavioral health screening|Sliding-fee program",
        county="Wilcox",
        served_counties="Wilcox",
        coverage="single",
        _source="https://cahabamedicalcare.com/who-we-are",
        _source_type="nonprofit",
        _confidence="high",
    )

    add(
        name="Christian Way — Food Pantry & Clothing Ministry",
        category="food-nutrition",
        region="Camden / Wilcox County",
        description="Christian Way, operated by Christian Way Baptist Church on Depot Street in Camden, runs a food pantry and clothing/donation center that helps more than 300 Wilcox County families each year with canned goods, frozen meals, clothing, and household items. Returning citizens and families facing food insecurity can visit the donation center for groceries and basic supplies at no cost. Direct food and clothing assistance — not an emergency shelter or cash-assistance office.",
        description_es="Christian Way, operado por Christian Way Baptist Church en Depot Street en Camden, administra un banco de alimentos y un centro de ropa y donaciones que ayuda a más de 300 familias del condado Wilcox cada año con alimentos enlatados, comidas congeladas, ropa y artículos del hogar. Ciudadanos que regresan y familias con inseguridad alimentaria pueden visitar el centro de donaciones para obtener alimentos y suministros básicos sin costo. Asistencia directa de alimentos y ropa, no un refugio de emergencia ni una oficina de asistencia en efectivo.",
        address="948 Depot Street",
        city="Camden",
        phone="334-682-4908",
        email="christianway@frontiernet.net",
        website="http://www.bethlehempinebarren.com/churches/christian-way",
        eligibility="Open to Wilcox and Monroe County residents in need of food or clothing; visitors are asked to sign in at the donation center; no income documentation barrier reported.",
        eligibility_es="Abierto a residentes de los condados Wilcox y Monroe que necesiten alimentos o ropa; se pide a los visitantes registrarse en el centro de donaciones; no se reporta barrera de documentación de ingresos.",
        notes="Call 334-682-4908 to confirm current pantry hours before visiting; clothing and household goods available in addition to food.",
        notes_es="Llame al 334-682-4908 para confirmar el horario actual de la despensa antes de visitar; también hay ropa y artículos del hogar disponibles además de alimentos.",
        hours="Contact for current pantry hours",
        tags="camden|wilcox|food-nutrition|food-pantry|clothing|reentry",
        services="Emergency food pantry|Clothing and household donations|Furniture and equipment donations|Community outreach",
        county="Wilcox",
        served_counties="Wilcox|Monroe",
        coverage="multi",
        _source="https://cla.auburn.edu/cah/programs/living-democracy/stories-archive/christian-way-lends-a-helping-hand-in-camden/",
        _source_type="nonprofit",
        _confidence="high",
    )

    add(
        name="Greene County Health System",
        category="healthcare",
        region="Eutaw / Greene County",
        description="Greene County Health System operates the county's only hospital in Eutaw, providing 24-hour emergency care, inpatient medical and surgical services, laboratory and imaging, physical and occupational therapy, and skilled nursing care for Greene, Sumter, Hale, Marengo, and Tuscaloosa county residents. Returning citizens without a medical home can access emergency and follow-up care through the hospital's outpatient and swing-bed programs. A rural acute-care hospital — not a walk-in benefits office.",
        description_es="Greene County Health System opera el único hospital del condado en Eutaw, ofreciendo atención de emergencia las 24 horas, servicios médicos y quirúrgicos hospitalarios, laboratorio e imágenes, terapia física y ocupacional, y cuidado de enfermería especializada para residentes de los condados Greene, Sumter, Hale, Marengo y Tuscaloosa. Ciudadanos que regresan sin un hogar médico pueden acceder a atención de emergencia y de seguimiento. Es un hospital rural de cuidados agudos, no una oficina de beneficios sin cita.",
        address="509 Wilson Avenue",
        city="Eutaw",
        phone="205-372-3388",
        email="",
        website="https://gcheutaw.com/",
        eligibility="Open to residents of Greene County and surrounding West Alabama counties; emergency care provided regardless of ability to pay; Medicaid and uninsured patients accepted for eligible services.",
        eligibility_es="Abierto a residentes del condado Greene y condados vecinos del oeste de Alabama; atención de emergencia sin importar la capacidad de pago; se aceptan pacientes con Medicaid y sin seguro para servicios elegibles.",
        notes="Emergency department open 24/7; call 205-372-3388 for outpatient scheduling and swing-bed/nursing home admissions.",
        notes_es="Departamento de emergencias abierto las 24 horas; llame al 205-372-3388 para programar citas ambulatorias y admisiones de cuidado de enfermería.",
        hours="Emergency 24/7; outpatient clinic hours vary",
        tags="eutaw|greene|healthcare|hospital|emergency-care|reentry",
        services="Emergency care|Inpatient medical and surgical care|Laboratory and imaging|Physical and occupational therapy|Skilled nursing and swing-bed care",
        county="Greene",
        served_counties="Greene",
        coverage="single",
        _source="https://gcheutaw.com/",
        _source_type="nonprofit",
        _confidence="high",
    )

    add(
        name="Greene County Community Service — Food Pantry",
        category="food-nutrition",
        region="Eutaw / Greene County",
        description="Greene County Community Service operates a food pantry in Eutaw distributing groceries to low-income Greene County households, including returning citizens reestablishing food security after incarceration. The pantry is open several days a week with a midday closure and is one of the only standalone food distribution points serving the county alongside partner church pantries. Direct food assistance — not a statewide hotline or SNAP application office.",
        description_es="Greene County Community Service opera un banco de alimentos en Eutaw que distribuye comestibles a hogares de bajos ingresos del condado Greene, incluidos ciudadanos que regresan que reestablecen la seguridad alimentaria tras su encarcelamiento. La despensa está abierta varios días a la semana con un cierre al mediodía y es uno de los pocos puntos de distribución de alimentos independientes del condado junto con despensas de iglesias aliadas. Asistencia directa de alimentos, no una línea directa estatal ni una oficina de solicitud de SNAP.",
        address="116 Prairie Avenue",
        city="Eutaw",
        phone="205-372-4562",
        email="",
        website="https://www.foodpantries.org/li/greene_county_community_service_35462",
        eligibility="Greene County residents in need of food assistance; no referral required; call ahead to confirm current requirements.",
        eligibility_es="Residentes del condado Greene que necesiten asistencia alimentaria; no se requiere referencia; llame con anticipación para confirmar los requisitos actuales.",
        notes="Pantry hours Monday–Thursday 8:00 a.m.–5:00 p.m., closed for lunch 12:00–1:00 p.m.; call 205-372-4562 to confirm before visiting.",
        notes_es="Horario de la despensa lunes a jueves de 8:00 a.m. a 5:00 p.m., cerrado para almuerzo de 12:00 a 1:00 p.m.; llame al 205-372-4562 para confirmar antes de visitar.",
        hours="Monday–Thursday, 8:00 a.m.–5:00 p.m. (closed 12:00–1:00 p.m.)",
        tags="eutaw|greene|food-nutrition|food-pantry|reentry",
        services="Emergency food pantry|Grocery distribution|Referrals to West Alabama Food Bank",
        county="Greene",
        served_counties="Greene",
        coverage="single",
        _source="https://www.foodpantries.org/li/greene_county_community_service_35462",
        _source_type="nonprofit",
        _confidence="high",
    )

    add(
        name="Cahaba Medical Care — Marion Clinic",
        category="healthcare",
        region="Marion / Perry County",
        description="Cahaba Medical Care's Marion clinic is a Federally Qualified Health Center serving Perry County, a county with no hospital of its own, offering primary care, prenatal and obstetric services, dental referrals, and behavioral health support for uninsured, Medicaid, and low-income patients including justice-involved adults establishing local care after release. The clinic opened a dedicated prenatal program in 2023 to address gaps in maternal healthcare access. An outpatient FQHC — not an emergency room.",
        description_es="La clínica de Cahaba Medical Care en Marion es un Centro de Salud Calificado Federalmente que atiende al condado Perry, que no cuenta con hospital propio, ofreciendo atención primaria, servicios prenatales y obstétricos, referencias dentales y apoyo de salud conductual para pacientes sin seguro, con Medicaid y de bajos ingresos, incluidos adultos con antecedentes penales que establecen atención local tras su liberación. La clínica abrió un programa prenatal dedicado en 2023. Es una clínica FQHC ambulatoria, no una sala de emergencias.",
        address="1303 Washington Street",
        city="Marion",
        phone="334-247-1006",
        email="contact@cahabamedicalcare.com",
        website="https://cahabamedicalcare.com/who-we-are",
        eligibility="Perry County residents of all ages; sliding-fee discount based on income; Medicaid and Medicare accepted; criminal record is not a stated barrier to care.",
        eligibility_es="Residentes del condado Perry de todas las edades; descuento de tarifa móvil según ingresos; se aceptan Medicaid y Medicare; los antecedentes penales no son una barrera indicada para recibir atención.",
        notes="Call 334-247-1006 for an appointment; closed daily 12:30–1:30 p.m. for lunch; prenatal and ultrasound services available on-site.",
        notes_es="Llame al 334-247-1006 para una cita; cerrado diariamente de 12:30 a 1:30 p.m. para almuerzo; servicios prenatales y de ultrasonido disponibles en el sitio.",
        hours="Monday–Thursday, 8:00 a.m.–7:00 p.m.; Friday, 8:00 a.m.–5:00 p.m.",
        tags="marion|perry|healthcare|FQHC|prenatal-care|sliding-fee|reentry",
        services="Primary medical care|Prenatal and obstetric care|Behavioral health support|Sliding-fee program|Dental referrals",
        county="Perry",
        served_counties="Perry",
        coverage="single",
        _source="https://www.wsfa.com/2023/08/31/cahaba-medical-care-opens-prenatal-clinic-perry-county/",
        _source_type="nonprofit",
        _confidence="high",
    )

    add(
        name="Sowing Seeds of Hope — Community & Direct Services",
        category="basic-needs",
        region="Marion / Perry County",
        description="Sowing Seeds of Hope is a faith-based community development nonprofit in Marion serving Perry County residents with a job training and work-readiness program, free computer classes, hypertension and diabetes support, self-help housing construction, and assistance with clothing, school supplies, and home repairs. Returning citizens can access job-search help and concrete family support through direct, walk-in services. A hands-on community organization — not a crisis hotline or legal aid office.",
        description_es="Sowing Seeds of Hope es una organización comunitaria de fe en Marion que sirve a los residentes del condado Perry con un programa de capacitación laboral y preparación para el trabajo, clases gratuitas de computación, apoyo para hipertensión y diabetes, construcción de vivienda de autoayuda, y asistencia con ropa, útiles escolares y reparaciones del hogar. Los ciudadanos que regresan pueden acceder a ayuda de búsqueda de empleo y apoyo familiar concreto mediante servicios directos sin cita previa. Es una organización comunitaria práctica, no una línea de crisis ni una oficina de asistencia legal.",
        address="1728 South Washington Street",
        city="Marion",
        phone="334-683-4666",
        email="susan@ssohope.org",
        website="https://ssohope.org/",
        eligibility="Perry County residents; specific program requirements vary; job training and work-readiness program open to adults seeking employment including justice-involved residents.",
        eligibility_es="Residentes del condado Perry; los requisitos específicos del programa varían; el programa de capacitación laboral y preparación para el trabajo está abierto a adultos que buscan empleo, incluidos residentes con antecedentes penales.",
        notes="Call 334-683-4666 to ask about current program schedules; home repair assistance has a waitlist subject to volunteer group availability.",
        notes_es="Llame al 334-683-4666 para preguntar sobre los horarios actuales de los programas; la asistencia de reparación del hogar tiene lista de espera sujeta a disponibilidad de grupos de voluntarios.",
        hours="Monday–Friday, 9:00 a.m.–5:00 p.m.",
        tags="marion|perry|basic-needs|job-training|community-development|reentry",
        services="Job training and work-readiness program|Free computer classes|Self-help housing program|Clothing and school supply assistance|Health screenings and support groups",
        county="Perry",
        served_counties="Perry",
        coverage="single",
        _source="https://ssohope.org/",
        _source_type="nonprofit",
        _confidence="high",
    )

    add(
        name="Ochsner Choctaw General",
        category="healthcare",
        region="Butler / Choctaw County",
        description="Ochsner Choctaw General is a 25-bed critical access hospital in Butler providing 24/7 emergency care, inpatient and outpatient services, diagnostic imaging, laboratory testing, and rehabilitation therapy for Choctaw County residents, plus two affiliated clinics — Choctaw Urgent Care Center and Gilbertown Family Medical Clinic. Returning citizens without a medical home can access emergency care and outpatient follow-up regardless of insurance status. A community hospital — not a walk-in DHR or probation office.",
        description_es="Ochsner Choctaw General es un hospital de acceso crítico de 25 camas en Butler que ofrece atención de emergencia las 24 horas, servicios hospitalarios y ambulatorios, imágenes diagnósticas, pruebas de laboratorio y terapia de rehabilitación para residentes del condado Choctaw, además de dos clínicas afiliadas: Choctaw Urgent Care Center y Gilbertown Family Medical Clinic. Ciudadanos que regresan sin un hogar médico pueden acceder a atención de emergencia y seguimiento ambulatorio sin importar su estado de seguro. Es un hospital comunitario, no una oficina de DHR ni de libertad condicional.",
        address="401 Vanity Fair Avenue",
        city="Butler",
        phone="205-459-9100",
        email="",
        website="https://www.ochsner.org/locations/ochsner-choctaw-general/",
        eligibility="Open to Choctaw County residents; emergency care provided regardless of ability to pay; Medicaid, Medicare, and uninsured patients accepted for eligible services.",
        eligibility_es="Abierto a residentes del condado Choctaw; atención de emergencia sin importar la capacidad de pago; se aceptan pacientes con Medicaid, Medicare y sin seguro para servicios elegibles.",
        notes="Emergency department open 24/7; call 205-459-9100 for outpatient scheduling; affiliated clinics in Gilbertown provide additional primary care access.",
        notes_es="Departamento de emergencias abierto las 24 horas; llame al 205-459-9100 para programar citas ambulatorias; las clínicas afiliadas en Gilbertown ofrecen acceso adicional a atención primaria.",
        hours="Emergency 24/7; outpatient clinic hours vary",
        tags="butler|choctaw|healthcare|hospital|emergency-care|reentry",
        services="Emergency care|Inpatient and outpatient services|Diagnostic imaging|Physical and occupational therapy|Wound care",
        county="Choctaw",
        served_counties="Choctaw",
        coverage="single",
        _source="https://www.ochsner.org/locations/ochsner-choctaw-general/",
        _source_type="nonprofit",
        _confidence="high",
    )

    add(
        name="Evergreen Medical Center",
        category="healthcare",
        region="Evergreen / Conecuh County",
        description="Evergreen Medical Center is a 44-bed acute care hospital serving Conecuh County with 24-hour emergency care, inpatient medical and surgical services, diagnostic imaging, rural health clinic primary care, and home health and hospice programs. Returning citizens without a medical home can access emergency treatment and establish ongoing primary care through Evergreen Primary Care regardless of insurance status. A hospital and rural health clinic — not a benefits or probation office.",
        description_es="Evergreen Medical Center es un hospital de cuidados agudos de 44 camas que atiende al condado Conecuh con atención de emergencia las 24 horas, servicios médicos y quirúrgicos hospitalarios, imágenes diagnósticas, atención primaria en clínica de salud rural, y programas de cuidado en el hogar y cuidados paliativos. Ciudadanos que regresan sin un hogar médico pueden recibir tratamiento de emergencia y establecer atención primaria continua a través de Evergreen Primary Care sin importar su estado de seguro. Es un hospital y clínica de salud rural, no una oficina de beneficios ni de libertad condicional.",
        address="101 Crestview Street",
        city="Evergreen",
        phone="251-578-2480",
        email="",
        website="https://www.evergreenmedical.org/",
        eligibility="Open to Conecuh County residents; emergency care provided regardless of ability to pay; Medicaid, Medicare, and uninsured patients accepted through the rural health clinic.",
        eligibility_es="Abierto a residentes del condado Conecuh; atención de emergencia sin importar la capacidad de pago; se aceptan pacientes con Medicaid, Medicare y sin seguro a través de la clínica de salud rural.",
        notes="Emergency department open 24/7; call 251-578-2480 for Evergreen Primary Care appointments and home health referrals.",
        notes_es="Departamento de emergencias abierto las 24 horas; llame al 251-578-2480 para citas de Evergreen Primary Care y referencias de cuidado en el hogar.",
        hours="Emergency 24/7; clinic hours vary",
        tags="evergreen|conecuh|healthcare|hospital|rural-health-clinic|reentry",
        services="Emergency care|Inpatient medical and surgical care|Rural health clinic primary care|Diagnostic imaging|Home health and hospice",
        county="Conecuh",
        served_counties="Conecuh",
        coverage="single",
        _source="https://www.evergreenmedical.org/",
        _source_type="nonprofit",
        _confidence="high",
    )

    add(
        name="Community Action Agency of South Alabama — Conecuh County Office",
        category="basic-needs",
        region="Evergreen / Conecuh County",
        description="The Community Action Agency of South Alabama operates a Conecuh County office in Evergreen providing emergency financial assistance for housing, utilities, and medical bills, a food program, LIHEAP energy assistance, and children's services for low-income households. Returning citizens reestablishing a household after release can apply for utility and rent assistance and connect to weatherization and self-sufficiency programs. Direct financial and food assistance — not a legal aid or probation office.",
        description_es="La Community Action Agency of South Alabama opera una oficina del condado Conecuh en Evergreen que brinda asistencia financiera de emergencia para vivienda, servicios públicos y facturas médicas, un programa de alimentos, asistencia energética LIHEAP y servicios para niños de hogares de bajos ingresos. Ciudadanos que regresan y reestablecen un hogar tras su liberación pueden solicitar asistencia de servicios públicos y renta y conectarse con programas de climatización y autosuficiencia. Asistencia financiera y alimentaria directa, no una oficina de asistencia legal ni de libertad condicional.",
        address="714 West Front Street",
        city="Evergreen",
        phone="251-578-2331",
        email="",
        website="https://www.caaofsa.org/",
        eligibility="Low-income Conecuh County households meeting income guidelines; income documentation required; call the 24/7 appointment line to check eligibility and schedule intake.",
        eligibility_es="Hogares de bajos ingresos del condado Conecuh que cumplan con las pautas de ingresos; se requiere documentación de ingresos; llame a la línea de citas 24/7 para verificar elegibilidad y programar la admisión.",
        notes="Call the 24/7 appointment line at 1-877-246-7836 or schedule online at caaofsa.org; local Evergreen office direct line 251-578-2331; funds are limited and dependent on availability.",
        notes_es="Llame a la línea de citas 24/7 al 1-877-246-7836 o programe en línea en caaofsa.org; línea directa de la oficina local de Evergreen 251-578-2331; los fondos son limitados y dependen de la disponibilidad.",
        hours="Monday–Friday, 8:00 a.m.–5:00 p.m.",
        tags="evergreen|conecuh|basic-needs|utility-assistance|LIHEAP|food-program|reentry",
        services="Emergency rent and utility assistance|Food program|LIHEAP energy assistance|Weatherization referrals|Children's services",
        county="Conecuh",
        served_counties="Conecuh",
        coverage="single",
        _source="https://adeca.alabama.gov/liheap/",
        _source_type="government",
        _confidence="high",
    )

    add(
        name="Bullock County Food Pantry",
        category="food-nutrition",
        region="Union Springs / Bullock County",
        description="The Bullock County Food Pantry in Union Springs distributes groceries to residents of Bullock County and special-needs populations facing food insecurity, including returning citizens rebuilding household stability after release. Monthly distribution serves families who call ahead to confirm eligibility and current hours. Direct food assistance — not an emergency shelter or a SNAP application office.",
        description_es="El Bullock County Food Pantry en Union Springs distribuye alimentos a residentes del condado Bullock y a poblaciones con necesidades especiales que enfrentan inseguridad alimentaria, incluidos ciudadanos que regresan y reconstruyen la estabilidad de su hogar tras su liberación. La distribución mensual atiende a familias que llaman con anticipación para confirmar elegibilidad y horario actual. Asistencia directa de alimentos, no un refugio de emergencia ni una oficina de solicitud de SNAP.",
        address="101 Powell Street",
        city="Union Springs",
        phone="334-738-2720",
        email="",
        website="https://www.foodpantries.org/li/bullock_county_food_pantry_36089",
        eligibility="Bullock County residents and special-needs populations; call ahead to confirm eligibility and distribution schedule.",
        eligibility_es="Residentes del condado Bullock y poblaciones con necesidades especiales; llame con anticipación para confirmar elegibilidad y horario de distribución.",
        notes="Distribution typically held the third Thursday of the month 2:00–4:00 p.m.; call 334-738-2720 to confirm before visiting, as hours can change.",
        notes_es="La distribución generalmente se realiza el tercer jueves del mes de 2:00 a 4:00 p.m.; llame al 334-738-2720 para confirmar antes de visitar, ya que el horario puede cambiar.",
        hours="3rd Thursday of the month, 2:00 p.m.–4:00 p.m. (call to confirm)",
        tags="union-springs|bullock|food-nutrition|food-pantry|reentry",
        services="Emergency food distribution|Grocery boxes|Special-needs population outreach",
        county="Bullock",
        served_counties="Bullock",
        coverage="single",
        _source="https://www.foodpantries.org/li/bullock_county_food_pantry_36089",
        _source_type="nonprofit",
        _confidence="high",
    )

    add(
        name="Alabama Career Center — Union Springs (Bullock County)",
        category="employment",
        region="Union Springs / Bullock County",
        description="The Alabama Career Center Union Springs location, housed at the Bullock County Career Technical Center, connects Bullock County job seekers including justice-involved adults to job search assistance, resume help, interview preparation, and training and education program referrals through the Alabama Department of Labor's career center network. The itinerant point operates on a limited schedule and coordinates with the Montgomery-area career center for full-service needs. Free workforce services — not emergency cash assistance.",
        description_es="La ubicación del Alabama Career Center en Union Springs, ubicada en el Bullock County Career Technical Center, conecta a los buscadores de empleo del condado Bullock, incluidos adultos con antecedentes penales, con asistencia de búsqueda de empleo, ayuda con currículum, preparación para entrevistas y referencias a programas de capacitación a través de la red de centros de carrera del Departamento de Trabajo de Alabama. Este punto itinerante opera en un horario limitado y coordina con el centro de carrera del área de Montgomery para necesidades de servicio completo. Servicios de fuerza laboral gratuitos, no asistencia de efectivo de emergencia.",
        address="304 East Blackmon Avenue",
        city="Union Springs",
        phone="334-821-2532",
        email="unionsprings@alcc.alabama.gov",
        website="https://adol.alabama.gov/career-centers/",
        eligibility="Open to Bullock County job seekers including justice-involved individuals; core Career Center services are free; call ahead as the itinerant schedule is limited.",
        eligibility_es="Abierto a buscadores de empleo del condado Bullock incluidas personas con antecedentes penales; los servicios básicos del Career Center son gratuitos; llame con anticipación ya que el horario itinerante es limitado.",
        notes="Call 334-821-2532 or email unionsprings@alcc.alabama.gov to confirm current open days; full-service support available at the Montgomery Career Center.",
        notes_es="Llame al 334-821-2532 o envíe un correo a unionsprings@alcc.alabama.gov para confirmar los días de atención actuales; el Career Center de Montgomery ofrece apoyo de servicio completo.",
        hours="Limited itinerant schedule; call to confirm current days and hours",
        tags="union-springs|bullock|employment|career-center|fair-chance|reentry",
        services="Job search assistance|Resume and cover letter help|Interview preparation|Training program referrals|Unemployment insurance information",
        county="Bullock",
        served_counties="Bullock",
        coverage="single",
        _source="https://adol.alabama.gov/career-centers/", _source_type="government", _confidence="high",
    )

    add(
        name="Alabama Career Center — Fayette (Serving Fayette & Lamar Counties)",
        category="employment",
        region="Fayette / Fayette & Lamar Counties",
        description="The Alabama Career Center in Fayette, located on the Bevill State Community College campus, connects job seekers in Fayette and Lamar counties — including justice-involved adults — to resume assistance, job search resources, employer referrals, and unemployment compensation filing help. The center regularly hosts job fairs with employers such as Bevill State Community College, the Alabama Department of Corrections, and area manufacturers, including events held at the Vernon City Complex for Lamar County residents. Free workforce services — not a DHR or probation office.",
        description_es="El Alabama Career Center en Fayette, ubicado en el campus de Bevill State Community College, conecta a buscadores de empleo de los condados Fayette y Lamar, incluidos adultos con antecedentes penales, con asistencia de currículum, recursos de búsqueda de empleo, referencias a empleadores y ayuda para solicitar compensación por desempleo. El centro organiza regularmente ferias de empleo con empleadores como Bevill State Community College y el Departamento de Correcciones de Alabama, incluyendo eventos realizados en Vernon City Complex para residentes del condado Lamar. Servicios de fuerza laboral gratuitos, no una oficina de DHR ni de libertad condicional.",
        address="2631 Temple Avenue North",
        city="Fayette",
        phone="205-303-6030",
        email="Fayette@alcc.alabama.gov",
        website="https://fayetteal.org/economic-development/careercenter/",
        eligibility="Open to Fayette and Lamar County job seekers including justice-involved individuals; core services are free; Alabama Department of Corrections has participated as an employer at center job fairs.",
        eligibility_es="Abierto a buscadores de empleo de los condados Fayette y Lamar incluidas personas con antecedentes penales; los servicios básicos son gratuitos; el Departamento de Correcciones de Alabama ha participado como empleador en las ferias de empleo del centro.",
        notes="Located in Tom Bevill Building Room B-37 on the Bevill State campus; call 205-303-6030 or email Fayette@alcc.alabama.gov; watch for periodic job fairs held in Vernon for Lamar County residents.",
        notes_es="Ubicado en el edificio Tom Bevill, sala B-37, en el campus de Bevill State; llame al 205-303-6030 o envíe un correo a Fayette@alcc.alabama.gov; esté atento a las ferias de empleo periódicas realizadas en Vernon para residentes del condado Lamar.",
        hours="Monday–Friday, 8:00 a.m.–5:00 p.m.",
        tags="fayette|lamar|vernon|employment|career-center|fair-chance|reentry",
        services="Job search assistance|Resume preparation|Employer job fairs|Unemployment insurance filing|Training and retraining referrals",
        county="Fayette",
        served_counties="Fayette|Lamar",
        coverage="multi",
        _source="https://fayetteal.org/economic-development/careercenter/",
        _source_type="government",
        _confidence="high",
    )

    add(
        name="Lamar County Health Department",
        category="healthcare",
        region="Vernon / Lamar County",
        description="The Lamar County Health Department in Vernon provides public health, clinical, WIC, environmental, and home care services for Lamar County residents, including STD testing and treatment, family planning, childhood and adult vaccines, and breast and cervical cancer screening. Returning citizens can obtain certified vital records and establish basic clinical care through the health department when no other local provider is accessible. A public health clinic — not a hospital emergency department.",
        description_es="El Departamento de Salud del Condado Lamar en Vernon ofrece servicios de salud pública, clínicos, WIC, ambientales y de cuidado en el hogar para residentes del condado Lamar, incluyendo pruebas y tratamiento de ETS, planificación familiar, vacunas infantiles y de adultos, y detección de cáncer de mama y cervical. Ciudadanos que regresan pueden obtener copias certificadas de registros vitales y establecer atención clínica básica a través del departamento de salud cuando no hay otro proveedor local accesible. Es una clínica de salud pública, no una sala de emergencias hospitalaria.",
        address="300 Springfield Road",
        city="Vernon",
        phone="205-695-9195",
        email="",
        website="https://www.alabamapublichealth.gov/lamar/",
        eligibility="Open to Lamar County residents; clinical services available on a fee or sliding-scale basis; certified vital records available with valid ID.",
        eligibility_es="Abierto a residentes del condado Lamar; servicios clínicos disponibles con tarifa o escala móvil; registros vitales certificados disponibles con identificación válida.",
        notes="Call 205-695-9195 for clinic appointments; home health services for Lamar County are coordinated through the Randolph County Health Department.",
        notes_es="Llame al 205-695-9195 para citas clínicas; los servicios de cuidado en el hogar para el condado Lamar se coordinan a través del Departamento de Salud del Condado Randolph.",
        hours="Monday–Friday, 7:30 a.m.–5:00 p.m.",
        tags="vernon|lamar|healthcare|public-health|WIC|vital-records|reentry",
        services="Clinical and STD services|Family planning|Immunizations|WIC|Certified vital records",
        county="Lamar",
        served_counties="Lamar",
        coverage="single",
        _source="https://www.alabamapublichealth.gov/lamar/",
        _source_type="government",
        _confidence="high",
    )

    add(
        name="Fayette Medical Center",
        category="healthcare",
        region="Fayette / Fayette County",
        description="Fayette Medical Center, part of the DCH Health System, is a 61-bed acute care hospital in Fayette offering 24-hour emergency care, surgical and specialty clinics, an on-site medical clinic, and a 122-bed nursing home for long-term and skilled care. Returning citizens without insurance or a local medical home can access emergency treatment and follow-up primary care through the FMC Medical Clinic. A hospital and outpatient clinic — not a walk-in benefits or probation office.",
        description_es="Fayette Medical Center, parte de DCH Health System, es un hospital de cuidados agudos de 61 camas en Fayette que ofrece atención de emergencia las 24 horas, clínicas quirúrgicas y de especialidad, una clínica médica en el sitio y un hogar de ancianos de 122 camas para cuidado a largo plazo y especializado. Ciudadanos que regresan sin seguro o sin un hogar médico local pueden acceder a tratamiento de emergencia y atención primaria de seguimiento a través de la FMC Medical Clinic. Es un hospital y clínica ambulatoria, no una oficina de beneficios ni de libertad condicional.",
        address="1653 Temple Avenue North",
        city="Fayette",
        phone="205-932-5966",
        email="",
        website="https://www.dchsystem.com/locations/fayette-medical-center/",
        eligibility="Open to Fayette County residents; emergency care provided regardless of ability to pay; Medicaid, Medicare, and uninsured patients accepted for eligible outpatient services.",
        eligibility_es="Abierto a residentes del condado Fayette; atención de emergencia sin importar la capacidad de pago; se aceptan pacientes con Medicaid, Medicare y sin seguro para servicios ambulatorios elegibles.",
        notes="Emergency department open 24/7; call 205-932-5966 for the hospital operator; FMC Medical Clinic at 1653 Temple Avenue, Suite 1, handles primary care scheduling.",
        notes_es="Departamento de emergencias abierto las 24 horas; llame al 205-932-5966 para el conmutador del hospital; la clínica FMC Medical Clinic en 1653 Temple Avenue, Suite 1, maneja las citas de atención primaria.",
        hours="Emergency 24/7; clinic hours vary",
        tags="fayette|healthcare|hospital|emergency-care|primary-care|reentry",
        services="Emergency care|Surgical and specialty clinics|Primary care clinic|Skilled nursing home care|Diagnostic imaging",
        county="Fayette",
        served_counties="Fayette",
        coverage="single",
        _source="https://fayetteal.org/health-care/",
        _source_type="nonprofit",
        _confidence="high",
    )

    add(
        name="HEARTS of Cleburne — Food Pantry",
        category="food-nutrition",
        region="Heflin / Cleburne County",
        description="HEARTS (Helping Every Area Resident To Succeed) of Cleburne operates a food pantry and family resource center in Heflin serving Cleburne County residents facing food insecurity, including returning citizens rebuilding stability after release. The center also hosts a 24-hour crisis hotline and partners with Gadsden State Community College to host adult education classes on-site. Direct food assistance — not a legal aid office or emergency shelter.",
        description_es="HEARTS (Helping Every Area Resident To Succeed) of Cleburne opera un banco de alimentos y centro de recursos familiares en Heflin que atiende a residentes del condado Cleburne con inseguridad alimentaria, incluidos ciudadanos que regresan y reconstruyen su estabilidad tras la liberación. El centro también mantiene una línea de crisis de 24 horas y colabora con Gadsden State Community College para ofrecer clases de educación para adultos en el sitio. Asistencia directa de alimentos, no una oficina de asistencia legal ni un refugio de emergencia.",
        address="915 Ross Street",
        city="Heflin",
        phone="256-926-5544",
        email="",
        website="https://heartsofcleburne.com/",
        eligibility="Cleburne County residents facing food insecurity; no referral required; call the 24-hour hotline for urgent needs outside office hours.",
        eligibility_es="Residentes del condado Cleburne con inseguridad alimentaria; no se requiere referencia; llame a la línea de 24 horas para necesidades urgentes fuera del horario de oficina.",
        notes="Office hours Monday–Friday 8:00 a.m.–4:00 p.m.; 24-hour crisis hotline 256-463-9535; call ahead to confirm current pantry distribution schedule.",
        notes_es="Horario de oficina lunes a viernes de 8:00 a.m. a 4:00 p.m.; línea de crisis de 24 horas 256-463-9535; llame con anticipación para confirmar el horario actual de distribución de la despensa.",
        hours="Monday–Friday, 8:00 a.m.–4:00 p.m.; 24-hour hotline available",
        tags="heflin|cleburne|food-nutrition|food-pantry|crisis-hotline|reentry",
        services="Emergency food pantry|24-hour crisis hotline|Family resource referrals|On-site adult education partnership",
        county="Cleburne",
        served_counties="Cleburne",
        coverage="single",
        _source="https://heartsofcleburne.com/",
        _source_type="nonprofit",
        _confidence="high",
    )

    add(
        name="Gadsden State Community College — Adult Education (Cleburne County)",
        category="education",
        region="Heflin / Cleburne County",
        description="Gadsden State Community College Adult Education provides free GED preparation, high school equivalency testing support, and the Mobilizing Alabama Pathways program at the HEARTS Family Resource Center in Heflin, serving Cleburne County adults including returning citizens rebuilding credentials for employment. Orientation is held twice monthly before enrollment, and instruction is self-paced based on an individualized plan. Free instruction — official GED test fees are covered through the program.",
        description_es="Gadsden State Community College Adult Education ofrece preparación GED gratuita, apoyo para el examen de equivalencia de escuela secundaria y el programa Mobilizing Alabama Pathways en el HEARTS Family Resource Center en Heflin, sirviendo a adultos del condado Cleburne incluidos ciudadanos que regresan que reconstruyen credenciales para el empleo. La orientación se realiza dos veces al mes antes de la inscripción, y la instrucción es a su propio ritmo según un plan individualizado. La instrucción es gratuita; las tarifas del examen GED oficial están cubiertas por el programa.",
        address="915 Ross Street",
        city="Heflin",
        phone="256-832-1206",
        email="adulted@gadsdenstate.edu",
        website="https://www.gadsdenstate.edu/programs-of-study/adult-education.cms",
        eligibility="Adults age 17+ not enrolled in K-12 in Cleburne County; must complete TABE placement testing; justice-involved adults welcome.",
        eligibility_es="Adultos de 17 años o más que no estén inscritos en K-12 en el condado Cleburne; deben completar la prueba de ubicación TABE; adultos con antecedentes penales bienvenidos.",
        notes="Orientations held the first Monday and fourth Thursday of each month at 8:30 a.m. at HEARTS in Heflin; call 256-832-1206 or email adulted@gadsdenstate.edu to register.",
        notes_es="Las orientaciones se realizan el primer lunes y el cuarto jueves de cada mes a las 8:30 a.m. en HEARTS en Heflin; llame al 256-832-1206 o envíe un correo a adulted@gadsdenstate.edu para registrarse.",
        hours="Orientation 1st Monday and 4th Thursday, 8:30 a.m.; class schedule set after enrollment",
        tags="heflin|cleburne|education|GED|adult-education|MAP|reentry",
        services="GED preparation|High school equivalency testing support|Mobilizing Alabama Pathways|Individualized instruction plans",
        county="Cleburne",
        served_counties="Cleburne",
        coverage="single",
        _source="https://heartsofcleburne.com/ged/",
        _source_type="government",
        _confidence="high",
    )

    add(
        name="Alabama Career Center — Roanoke (Randolph County)",
        category="employment",
        region="Roanoke / Randolph County",
        description="The Alabama Career Center satellite in Roanoke connects Randolph County job seekers, including justice-involved adults, to job search assistance, resume and cover letter help, interview preparation, career counseling, and unemployment insurance services. Randolph County Commission and other local employers direct applicants to this office to submit employment applications. Free workforce services — not a walk-in DHR benefits office.",
        description_es="La sucursal del Alabama Career Center en Roanoke conecta a los buscadores de empleo del condado Randolph, incluidos adultos con antecedentes penales, con asistencia de búsqueda de empleo, ayuda con currículum y carta de presentación, preparación para entrevistas, orientación profesional y servicios de seguro de desempleo. La Comisión del Condado Randolph y otros empleadores locales dirigen a los solicitantes a esta oficina para presentar solicitudes de empleo. Servicios de fuerza laboral gratuitos, no una oficina de beneficios de DHR sin cita.",
        address="3928 Highway 431",
        city="Roanoke",
        phone="256-692-5838",
        email="Roanoke@alcc.alabama.gov",
        website="https://adol.alabama.gov/career-centers/",
        eligibility="Open to Randolph County job seekers including justice-involved individuals; core services are free; county government job applications accepted at this location.",
        eligibility_es="Abierto a buscadores de empleo del condado Randolph incluidas personas con antecedentes penales; los servicios básicos son gratuitos; se aceptan solicitudes de empleo del gobierno del condado en esta ubicación.",
        notes="Call 256-692-5838 or email Roanoke@alcc.alabama.gov before visiting; hours posted as 9:00 a.m.–4:00 p.m.",
        notes_es="Llame al 256-692-5838 o envíe un correo a Roanoke@alcc.alabama.gov antes de visitar; el horario publicado es de 9:00 a.m. a 4:00 p.m.",
        hours="Monday–Friday, 9:00 a.m.–4:00 p.m.",
        tags="roanoke|randolph|employment|career-center|fair-chance|reentry",
        services="Job search assistance|Resume and cover letter help|Interview preparation|Career counseling|Unemployment insurance services",
        county="Randolph",
        served_counties="Randolph",
        coverage="single",
        _source="https://unemploymentoffice.us/alabama-unemployment-offices/roanoke-al-career-center-and-unemployment-office/",
        _source_type="government",
        _confidence="high",
    )

    add(
        name="Tanner Medical Center/East Alabama",
        category="healthcare",
        region="Wedowee / Randolph County",
        description="Tanner Medical Center/East Alabama is a 50,000-square-foot critical access hospital in Wedowee providing 24-hour emergency care with eight exam rooms, inpatient beds, on-site laboratory and imaging, and surgical services for Randolph County residents. The adjacent medical office building houses Tanner Primary Care of Wedowee and specialty services including gastroenterology, gynecology, and oncology. County residents approved a sales tax to fund the hospital after the county's previous hospital closed in 2011. A hospital — not a benefits or probation office.",
        description_es="Tanner Medical Center/East Alabama es un hospital de acceso crítico de 50,000 pies cuadrados en Wedowee que ofrece atención de emergencia las 24 horas con ocho salas de examen, camas de hospitalización, laboratorio e imágenes en el sitio, y servicios quirúrgicos para residentes del condado Randolph. El edificio de oficinas médicas adyacente alberga Tanner Primary Care of Wedowee y servicios de especialidad incluyendo gastroenterología, ginecología y oncología. Los residentes del condado aprobaron un impuesto sobre las ventas para financiar el hospital después de que el hospital anterior del condado cerrara en 2011. Es un hospital, no una oficina de beneficios ni de libertad condicional.",
        address="1032 South Main Street",
        city="Wedowee",
        phone="256-357-2111",
        email="",
        website="https://www.tanner.org/tanner-medical-center-east-alabama",
        eligibility="Open to Randolph County residents; emergency care provided regardless of ability to pay; Medicaid, Medicare, and uninsured patients accepted for eligible services.",
        eligibility_es="Abierto a residentes del condado Randolph; atención de emergencia sin importar la capacidad de pago; se aceptan pacientes con Medicaid, Medicare y sin seguro para servicios elegibles.",
        notes="Emergency department open 24/7; call 256-357-2111 for the hospital operator; Tanner Primary Care of Wedowee appointments at 256-357-2188.",
        notes_es="Departamento de emergencias abierto las 24 horas; llame al 256-357-2111 para el conmutador del hospital; citas de Tanner Primary Care of Wedowee al 256-357-2188.",
        hours="Emergency 24/7; clinic hours 7:00 a.m.–5:00 p.m. Monday–Friday",
        tags="wedowee|randolph|healthcare|hospital|emergency-care|reentry",
        services="Emergency care|Inpatient services|Surgical services|Diagnostic imaging|Primary and specialty care referrals",
        county="Randolph",
        served_counties="Randolph",
        coverage="single",
        _source="https://www.tanner.org/tanner-medical-center-east-alabama",
        _source_type="nonprofit",
        _confidence="high",
    )

    add(
        name="Clay County Hospital",
        category="healthcare",
        region="Ashland / Clay County",
        description="Clay County Hospital is a 53-bed acute care hospital in Ashland offering emergency care, radiology, physical and occupational therapy, cardiology, and a sleep lab, alongside an 83-bed nursing home and hospice program. Returning citizens without a medical home can access emergency treatment and outpatient follow-up regardless of insurance status. A hospital — not a walk-in benefits office; the county health department in Lineville handles WIC and clinical screenings.",
        description_es="Clay County Hospital es un hospital de cuidados agudos de 53 camas en Ashland que ofrece atención de emergencia, radiología, terapia física y ocupacional, cardiología y un laboratorio del sueño, además de un hogar de ancianos de 83 camas y un programa de cuidados paliativos. Ciudadanos que regresan sin un hogar médico pueden recibir tratamiento de emergencia y seguimiento ambulatorio sin importar su estado de seguro. Es un hospital, no una oficina de beneficios sin cita; el departamento de salud del condado en Lineville maneja WIC y evaluaciones clínicas.",
        address="83825 Highway 9",
        city="Ashland",
        phone="256-354-2131",
        email="",
        website="https://www.claycountyhospital.com/",
        eligibility="Open to Clay County residents; emergency care provided regardless of ability to pay; Medicaid, Medicare, and uninsured patients accepted for eligible services.",
        eligibility_es="Abierto a residentes del condado Clay; atención de emergencia sin importar la capacidad de pago; se aceptan pacientes con Medicaid, Medicare y sin seguro para servicios elegibles.",
        notes="Emergency and main hospital line 256-354-2131; Clay County Health & Wellness Center 256-354-1260; Clay County Health Department in Lineville 256-396-6421 for WIC and clinical services.",
        notes_es="Línea principal del hospital y emergencias 256-354-2131; Clay County Health & Wellness Center 256-354-1260; Departamento de Salud del Condado Clay en Lineville 256-396-6421 para WIC y servicios clínicos.",
        hours="Emergency 24/7; hospital and clinic hours vary",
        tags="ashland|clay|healthcare|hospital|emergency-care|reentry",
        services="Emergency care|Radiology|Physical and occupational therapy|Cardiology clinic|Skilled nursing and hospice",
        county="Clay",
        served_counties="Clay",
        coverage="single",
        _source="https://www.claycountyhospital.com/getpage.php?name=contact",
        _source_type="nonprofit",
        _confidence="high",
    )

    add(
        name="Southern Union State Community College — Adult Education (Clay County)",
        category="education",
        region="Lineville / Clay County",
        description="Southern Union State Community College Adult Education offers free GED preparation classes at Central High School of Clay County in Lineville, serving Clay County adults including returning citizens rebuilding credentials for employment through NCWorks-style referrals and career pathway programs. Instructors provide an individualized plan of instruction based on TABE placement testing, and students work at their own pace rather than a fixed term. Free instruction — official GED test fees are covered for enrolled students.",
        description_es="Southern Union State Community College Adult Education ofrece clases gratuitas de preparación GED en Central High School of Clay County en Lineville, sirviendo a adultos del condado Clay incluidos ciudadanos que regresan que reconstruyen credenciales para el empleo a través de programas de vías de carrera. Los instructores proporcionan un plan de instrucción individualizado basado en la prueba de ubicación TABE, y los estudiantes trabajan a su propio ritmo en lugar de un plazo fijo. La instrucción es gratuita; las tarifas del examen GED oficial están cubiertas para los estudiantes inscritos.",
        address="1 Bob Riley Drive",
        city="Lineville",
        phone="334-749-8480",
        email="rfields@suscc.edu",
        website="https://www.suscc.edu/programs/class-locations",
        eligibility="Adults age 18+ in Clay County; ages 16–17 with documentation of withdrawal from school; justice-involved adults welcome.",
        eligibility_es="Adultos de 18 años o más en el condado Clay; 16–17 años con documentación de retiro escolar; adultos con antecedentes penales bienvenidos.",
        notes="Classes meet Monday and Wednesday 3:00–7:00 p.m. at Central High School of Clay County; call 334-749-8480 or email rfields@suscc.edu to enroll; TABE placement testing required before starting.",
        notes_es="Las clases se reúnen los lunes y miércoles de 3:00 a 7:00 p.m. en Central High School of Clay County; llame al 334-749-8480 o envíe un correo a rfields@suscc.edu para inscribirse; se requiere la prueba de ubicación TABE antes de comenzar.",
        hours="Monday and Wednesday, 3:00 p.m.–7:00 p.m.",
        tags="lineville|clay|education|GED|adult-education|reentry",
        services="GED preparation|TABE placement testing|Individualized instruction plans|Career pathway referrals",
        county="Clay",
        served_counties="Clay",
        coverage="single",
        _source="https://www.suscc.edu/programs/class-locations",
        _source_type="government",
        _confidence="high",
    )

    add(
        name="Whatley Health Services — Marion Clinic",
        category="healthcare",
        region="Marion / Perry County",
        description="Whatley Health Services operates a Federally Qualified Health Center clinic in Marion serving Perry, Marengo, and surrounding Black Belt counties with primary medical, dental, behavioral health, and sliding-fee care for uninsured and Medicaid patients. Justice-involved adults reestablishing healthcare after release from Perry County Jail or ADOC custody can access same-week appointments and medication assistance. Direct clinical care—not a probation reporting office.",
        description_es="Whatley Health Services opera una clínica del Centro de Salud Calificado Federalmente en Marion que sirve a Perry, Marengo y condados circundantes del Cinturón Negro con atención médica primaria, dental, de salud conductual y tarifas móviles para pacientes sin seguro y Medicaid. Los adultos con antecedentes penales que restablecen atención médica pueden acceder a citas y asistencia con medicamentos.",
        address="1000 Washington Street",
        city="Marion",
        phone="334-683-6693",
        email="",
        website="https://www.whatleyhealth.org",
        eligibility="Residents of Perry, Marengo, and surrounding counties; sliding-fee scale based on income; Medicaid and Medicare accepted.",
        eligibility_es="Residentes de Perry, Marengo y condados circundantes; escala de tarifas según ingresos; se aceptan Medicaid y Medicare.",
        notes="Call 334-683-6693 for appointments; behavioral health and dental at select sites; pharmacy assistance available.",
        notes_es="Llame al 334-683-6693 para citas; salud conductual y dental en sitios selectos; asistencia de farmacia disponible.",
        hours="Monday–Friday business hours",
        tags="marion|perry|marengo|healthcare|FQHC|primary-care|black-belt|reentry",
        services="Primary medical care|Dental services|Behavioral health counseling|Sliding-fee program|Pharmacy assistance",
        county="Perry",
        served_counties="Perry|Marengo",
        coverage="multi",
        _source="https://www.whatleyhealth.org",
        _source_type="nonprofit",
        _confidence="high",
    )

    add(
        name="Northwest-Shoals Community College — Adult Education (Winston County)",
        category="education",
        region="Double Springs / Winston County",
        description="Northwest-Shoals Community College Adult Education offers free GED preparation at the Winston County satellite site in Double Springs for adults including returning citizens in rural northwest Alabama rebuilding credentials for North Alabama Career Center referrals. Instructors provide TABE-based individualized instruction and connections to Alabama Career Center Hamilton. Free GED classes—not a substance use residential program.",
        description_es="Northwest-Shoals Community College Adult Education ofrece preparación gratuita para el GED en el sitio satélite del condado Winston en Double Springs para adultos incluidos ciudadanos que regresan en el noroeste rural de Alabama que reconstruyen credenciales para referencias del North Alabama Career Center.",
        address="1481 Highway 33",
        city="Double Springs",
        phone="256-331-5200",
        email="",
        website="https://www.nwscc.edu/adult-education/",
        eligibility="Adults age 18+ in Winston and surrounding counties; ages 16–17 with school withdrawal documentation; justice-involved adults welcome.",
        eligibility_es="Adultos de 18 años o más en Winston y condados circundantes; 16–17 años con documentación de retiro escolar; adultos con antecedentes penales bienvenidos.",
        notes="Call 256-331-5200 for enrollment; classes at Double Springs and Phil Campbell campuses; TABE placement required.",
        notes_es="Llame al 256-331-5200 para inscripción; clases en campus Double Springs y Phil Campbell; se requiere ubicación TABE.",
        hours="Class schedules vary; contact adult education office",
        tags="double-springs|winston|education|GED|adult-education|reentry",
        services="GED preparation|TABE placement testing|Individualized instruction|Career center referrals",
        county="Winston",
        served_counties="Winston",
        coverage="single",
        _source="https://www.nwscc.edu/adult-education/",
        _source_type="government",
        _confidence="high",
    )
