"""Final category-minimum gap fill for Arizona reentry resources."""


def register_gap_fill(add):
  # --- housing (+12 to reach 20) ---
  add(
    name="House of Refuge — Transitional Housing",
    category="housing", region="Mesa / Maricopa County",
    description="House of Refuge provides structured transitional housing, life skills training, and employment support for single mothers and families experiencing homelessness in Maricopa County including justice-involved women reunifying with children after release from Perryville or county jail. Case managers connect residents to ARIZONA@WORK, DES benefits, and Valleywise primary care. Family-focused transitional housing—not emergency walk-in shelter.",
    description_es="House of Refuge ofrece vivienda transicional estructurada, capacitación en habilidades para la vida y apoyo laboral para madres solteras y familias sin hogar en el condado Maricopa incluidas mujeres con antecedentes penales que se reunifican con sus hijos después de la liberación.",
    address="7550 East Main Street", city="Mesa", phone="480-833-7872", email="",
    website="https://houseofrefuge.org",
    eligibility="Homeless single mothers and families in Maricopa County; justice-involved women per program policy; referral or application required.",
    eligibility_es="Madres solteras y familias sin hogar en el condado Maricopa; mujeres con antecedentes penales según política del programa; se requiere referencia o solicitud.",
    notes="Call 480-833-7872 for intake; pairs with A New Leaf and UMOM.",
    notes_es="Llame al 480-833-7872 para admisión; se vincula con A New Leaf y UMOM.",
    hours="Contact for intake hours",
    tags="mesa|maricopa|housing|transitional|families|reentry",
    services="Transitional housing|Life skills training|Employment support|Case management|Benefits navigation",
    county="Maricopa", served_counties="Maricopa", coverage="single",
    _source="https://houseofrefuge.org", _source_type="nonprofit", _confidence="high",
  )
  add(
    name="Rehoboth — Transitional & Affordable Housing",
    category="housing", region="Phoenix / Maricopa County",
    description="Rehoboth Community Development Corporation operates transitional and affordable rental housing programs for low-income Maricopa County households including returning citizens rebuilding stable tenancy after incarceration. Property management and supportive services connect residents to St. Joseph the Worker and Community Legal Services for employment and tenant-rights support.",
    description_es="Rehoboth Community Development Corporation opera programas de vivienda de alquiler transicional y asequible para hogares de bajos ingresos del condado Maricopa incluidos ciudadanos que regresan que reconstruyen arrendamiento estable después de la encarcelación.",
    address="3102 North 35th Avenue", city="Phoenix", phone="602-258-7366", email="",
    website="https://www.rehobothcdc.org",
    eligibility="Low-income Maricopa County households; justice-involved applicants may qualify for transitional units per screening.",
    eligibility_es="Hogares de bajos ingresos del condado Maricopa; solicitantes con antecedentes penales pueden calificar para unidades transicionales según evaluación.",
    notes="Call 602-258-7366 for availability; not an emergency shelter.",
    notes_es="Llame al 602-258-7366 para disponibilidad; no es refugio de emergencia.",
    hours="Monday–Friday business hours",
    tags="phoenix|maricopa|housing|affordable|transitional|reentry",
    services="Affordable rental housing|Transitional housing|Tenant support|Employment referrals|Housing stabilization",
    county="Maricopa", served_counties="Maricopa", coverage="single",
    _source="https://www.rehobothcdc.org", _source_type="nonprofit", _confidence="high",
  )
  add(
    name="Family Promise of Greater Phoenix",
    category="housing", region="Phoenix / Maricopa County",
    description="Family Promise of Greater Phoenix provides emergency shelter, case management, and rehousing for homeless families in Maricopa County including parents returning from incarceration seeking reunification with children. Congregation-based shelter network connects families to DES benefits, ARIZONA@WORK, and permanent housing partners.",
    description_es="Family Promise of Greater Phoenix ofrece refugio de emergencia, manejo de casos y realojamiento para familias sin hogar en el condado Maricopa incluidos padres que regresan de la encarcelación que buscan reunificación con sus hijos.",
    address="7227 North 16th Street", city="Phoenix", phone="602-263-8856", email="",
    website="https://familypromisegp.org",
    eligibility="Homeless families with children in Maricopa County; justice-involved parents welcome per intake.",
    eligibility_es="Familias sin hogar con niños en el condado Maricopa; padres con antecedentes penales bienvenidos según admisión.",
    notes="Call 602-263-8856 for intake; host congregation network across metro Phoenix.",
    notes_es="Llame al 602-263-8856 para admisión; red de congregaciones anfitrionas en el área metropolitana de Phoenix.",
    hours="Contact for intake hours",
    tags="phoenix|maricopa|housing|families|shelter|reentry",
    services="Emergency family shelter|Case management|Rehousing assistance|Benefits navigation|Employment referrals",
    county="Maricopa", served_counties="Maricopa", coverage="single",
    _source="https://familypromisegp.org", _source_type="nonprofit", _confidence="high",
  )
  add(
    name="Sojourner Center — Emergency Family Shelter",
    category="housing", region="Phoenix / Maricopa County",
    description="Sojourner Center operates one of Arizona's largest domestic violence emergency shelters and transitional housing programs for women and children fleeing abuse in Maricopa County, including justice-involved survivors returning from custody. Advocates connect residents to legal aid, DES benefits, and behavioral health treatment. DV-focused shelter—not a general men's homeless program.",
    description_es="Sojourner Center opera uno de los mayores refugios de emergencia por violencia doméstica y programas de vivienda transicional para mujeres y niños que huyen del abuso en el condado Maricopa, incluidas sobrevivientes con antecedentes penales que regresan de la custodia.",
    address="4101 East Cotton Lane", city="Phoenix", phone="602-244-0089", email="",
    website="https://sojournercenter.org",
    eligibility="Women and children fleeing domestic violence in Maricopa County; justice-involved survivors eligible per safety assessment.",
    eligibility_es="Mujeres y niños que huyen de violencia doméstica en el condado Maricopa; sobrevivientes con antecedentes penales elegibles según evaluación de seguridad.",
    notes="24/7 crisis line 602-244-0089; confidential intake; pairs with Community Legal Services.",
    notes_es="Línea de crisis 24/7 602-244-0089; admisión confidencial; se vincula con Community Legal Services.",
    hours="Crisis line 24/7; shelter intake around the clock",
    tags="phoenix|maricopa|housing|domestic-violence|shelter|reentry",
    services="Emergency DV shelter|Transitional housing|Safety planning|Legal advocacy referrals|Benefits navigation",
    county="Maricopa", served_counties="Maricopa", coverage="single",
    _source="https://sojournercenter.org", _source_type="nonprofit", _confidence="high",
  )
  add(
    name="Halle Women's Center — Transitional Housing",
    category="housing", region="Tucson / Pima County",
    description="Halle Women's Center provides transitional housing and supportive services for homeless women in Pima County including justice-involved women released from Arizona State Prison Complex Tucson or Pima County Jail. Case managers coordinate CODAC treatment, Primavera employment programs, and DES benefits enrollment.",
    description_es="Halle Women's Center ofrece vivienda transicional y servicios de apoyo para mujeres sin hogar en el condado Pima incluidas mujeres con antecedentes penales liberadas de la prisión estatal de Tucson o la cárcel del condado Pima.",
    address="2800 East 18th Street", city="Tucson", phone="520-622-6696", email="",
    website="https://www.hallewomen.org",
    eligibility="Homeless women in Pima County; justice-involved women welcome per program screening.",
    eligibility_es="Mujeres sin hogar en el condado Pima; mujeres con antecedentes penales bienvenidas según evaluación del programa.",
    notes="Call 520-622-6696 for intake; pairs with Primavera and Our Family Services.",
    notes_es="Llame al 520-622-6696 para admisión; se vincula con Primavera y Our Family Services.",
    hours="Contact for intake hours",
    tags="tucson|pima|housing|women|transitional|reentry",
    services="Transitional housing|Case management|Employment support|Treatment referrals|Benefits navigation",
    county="Pima", served_counties="Pima", coverage="single",
    _source="https://www.hallewomen.org", _source_type="nonprofit", _confidence="high",
  )
  add(
    name="Yavapai Casa for Kids — Housing & Family Support",
    category="housing", region="Prescott / Yavapai County",
    description="Yavapai Casa for Kids provides housing navigation, kinship caregiver support, and family stabilization services for vulnerable households in Yavapai County including justice-involved parents working toward reunification after CPS or criminal justice involvement. Advocates connect families to West Yavapai Guidance Clinic and ARIZONA@WORK Prescott.",
    description_es="Yavapai Casa for Kids ofrece navegación de vivienda, apoyo a cuidadores de parentesco y servicios de estabilización familiar para hogares vulnerables en el condado Yavapai incluidos padres con antecedentes penales que trabajan hacia la reunificación.",
    address="851 South McCormick Street", city="Prescott", phone="928-445-0800", email="",
    website="https://www.yavapaicasaforkids.org",
    eligibility="Yavapai County families with child-welfare or housing instability; justice-involved parents may qualify for kinship and stabilization support.",
    eligibility_es="Familias del condado Yavapai con inestabilidad de bienestar infantil o vivienda; padres con antecedentes penales pueden calificar para apoyo de parentesco y estabilización.",
    notes="Call 928-445-0800; not an emergency men's shelter.",
    notes_es="Llame al 928-445-0800; no es refugio de emergencia para hombres.",
    hours="Monday–Friday business hours",
    tags="prescott|yavapai|housing|families|kinship|reentry",
    services="Housing navigation|Kinship caregiver support|Family stabilization|Benefits referrals|Employment connections",
    county="Yavapai", served_counties="Yavapai", coverage="single",
    _source="https://www.yavapaicasaforkids.org", _source_type="nonprofit", _confidence="high",
  )
  add(
    name="Catholic Community Services — Southern Arizona Housing",
    category="housing", region="Tucson / Pima County",
    description="Catholic Community Services of Southern Arizona operates scattered-site housing, rapid rehousing, and homeless prevention for low-income households in Pima, Santa Cruz, and Cochise counties including returning citizens establishing tenancy after incarceration. Housing specialists coordinate with El Rio Health and Southern Arizona Legal Aid.",
    description_es="Catholic Community Services del Sur de Arizona opera vivienda dispersa, realojamiento rápido y prevención de falta de vivienda para hogares de bajos ingresos en los condados Pima, Santa Cruz y Cochise incluidos ciudadanos que regresan que establecen arrendamiento después de la encarcelación.",
    address="140 West Speedway Boulevard", city="Tucson", phone="520-623-0344", email="",
    website="https://www.ccs-soaz.org",
    eligibility="Low-income households in southern Arizona service area facing homelessness; justice-involved adults may qualify for rapid rehousing.",
    eligibility_es="Hogares de bajos ingresos en el área de servicio del sur de Arizona que enfrentan falta de vivienda; adultos con antecedentes penales pueden calificar para realojamiento rápido.",
    notes="Call 520-623-0344 for housing intake; multiple southern Arizona counties served.",
    notes_es="Llame al 520-623-0344 para admisión de vivienda; sirve múltiples condados del sur de Arizona.",
    hours="Monday–Friday business hours",
    tags="tucson|pima|housing|rapid-rehousing|southern-arizona|reentry",
    services="Rapid rehousing|Homeless prevention|Scattered-site housing|Case management|Benefits navigation",
    county="Pima", served_counties="Pima|Santa Cruz|Cochise", coverage="multi",
    _source="https://www.ccs-soaz.org", _source_type="nonprofit", _confidence="high",
  )
  add(
    name="Northland Pioneer College — Housing & Basic Needs Support",
    category="housing", region="Show Low / Navajo County",
    description="Northland Pioneer College student services connect justice-involved adults in Navajo and Apache counties to emergency housing referrals, basic needs assistance, and GED pathways through White Mountain and Show Low campuses. Staff coordinate with DES Lakeside office and North Country HealthCare for rural reentry stabilization—not a standalone shelter operator.",
    description_es="Los servicios estudiantiles de Northland Pioneer College conectan a adultos con antecedentes penales en los condados Navajo y Apache con referencias de vivienda de emergencia, asistencia de necesidades básicas y vías GED a través de campus rurales.",
    address="1001 West Deuce of Clubs", city="Show Low", phone="928-532-6111", email="",
    website="https://www.npc.edu",
    eligibility="NPC students and community referrals in Navajo and Apache counties; justice-involved adults eligible for adult education and basic needs navigation.",
    eligibility_es="Estudiantes de NPC y referencias comunitarias en los condados Navajo y Apache; adultos con antecedentes penales elegibles para educación de adultos y navegación de necesidades básicas.",
    notes="Call 928-532-6111; pairs with DES Lakeside and ARIZONA@WORK rural offices.",
    notes_es="Llame al 928-532-6111; se vincula con DES Lakeside y oficinas rurales de ARIZONA@WORK.",
    hours="Campus hours vary by location",
    tags="show-low|navajo|apache|housing|referrals|reentry",
    services="Housing referrals|Basic needs navigation|GED pathways|Student support|Rural reentry coordination",
    county="Navajo", served_counties="Navajo|Apache", coverage="multi",
    _source="https://www.npc.edu", _source_type="government", _confidence="high",
  )
  add(
    name="Greenlee County Housing Department",
    category="housing", region="Clifton / Greenlee County",
    description="Greenlee County Community Development coordinates affordable housing lists, emergency rental assistance referrals, and homeless prevention navigation for low-income residents in Greenlee and eastern Graham counties including returning citizens from Safford area correctional releases. County housing navigation—not a 24-hour walk-in shelter.",
    description_es="El Desarrollo Comunitario del condado Greenlee coordina listas de vivienda asequible, referencias de asistencia de alquiler de emergencia y navegación de prevención de falta de vivienda para residentes de bajos ingresos en Greenlee y el este del condado Graham.",
    address="2535 South Coronado Boulevard", city="Morenci", phone="928-865-2072", email="",
    website="https://www.greenlee.az.gov",
    eligibility="Low-income Greenlee County residents facing housing instability; justice-involved adults may qualify for emergency rental referrals.",
    eligibility_es="Residentes de bajos ingresos del condado Greenlee que enfrentan inestabilidad de vivienda; adultos con antecedentes penales pueden calificar para referencias de alquiler de emergencia.",
    notes="Call 928-865-2072; coordinate with Graham County DES Safford office.",
    notes_es="Llame al 928-865-2072; coordine con la oficina DES de Safford en el condado Graham.",
    hours="Monday–Friday business hours",
    tags="greenlee|graham|housing|rental-assistance|rural|reentry",
    services="Affordable housing lists|Emergency rental referrals|Homeless prevention navigation|County housing counseling",
    county="Greenlee", served_counties="Greenlee|Graham", coverage="multi",
    _source="https://www.greenlee.az.gov", _source_type="government", _confidence="high",
  )
  add(
    name="La Paz County — Housing & Community Development",
    category="housing", region="Parker / La Paz County",
    description="La Paz County Community Development connects low-income residents in Parker and the Colorado River communities to emergency rental assistance, weatherization referrals, and homeless prevention resources for justice-involved adults returning to rural western Arizona. County office—not an emergency shelter.",
    description_es="El Desarrollo Comunitario del condado La Paz conecta a residentes de bajos ingresos en Parker y las comunidades del río Colorado con asistencia de alquiler de emergencia, referencias de climatización y recursos de prevención de falta de vivienda.",
    address="1108 Joshua Avenue", city="Parker", phone="928-669-6131", email="",
    website="https://www.co.la-paz.az.us",
    eligibility="La Paz County residents meeting income guidelines for housing assistance programs; justice-involved adults may apply for rental assistance.",
    eligibility_es="Residentes del condado La Paz que cumplan las pautas de ingresos para programas de asistencia de vivienda; adultos con antecedentes penales pueden solicitar asistencia de alquiler.",
    notes="Call 928-669-6131; pairs with DES Parker office and Crossroads Mission Yuma for overflow referrals.",
    notes_es="Llame al 928-669-6131; se vincula con la oficina DES de Parker y Crossroads Mission en Yuma.",
    hours="Monday–Friday business hours",
    tags="parker|la-paz|housing|rental-assistance|rural|reentry",
    services="Emergency rental assistance|Homeless prevention|Weatherization referrals|Housing counseling|County resource navigation",
    county="La Paz", served_counties="La Paz", coverage="single",
    _source="https://www.co.la-paz.az.us", _source_type="government", _confidence="high",
  )
  add(
    name="Mohave County Community Housing",
    category="housing", region="Kingman / Mohave County",
    description="Mohave County Community Development Block Grant housing programs connect low-income residents in Kingman, Lake Havasu City, and Bullhead City to emergency shelter referrals, rental assistance, and homeless prevention for justice-involved adults returning from Mohave County Detention Center. County navigation office—not a direct shelter operator.",
    description_es="Los programas de vivienda CDBG del condado Mohave conectan a residentes de bajos ingresos en Kingman, Lake Havasu City y Bullhead City con referencias de refugio de emergencia, asistencia de alquiler y prevención de falta de vivienda.",
    address="700 West Beale Street", city="Kingman", phone="928-753-0723", email="",
    website="https://www.mohave.gov",
    eligibility="Low-income Mohave County residents; justice-involved adults may qualify for rental and shelter referrals.",
    eligibility_es="Residentes de bajos ingresos del condado Mohave; adultos con antecedentes penales pueden calificar para referencias de alquiler y refugio.",
    notes="Call 928-753-0723; pairs with Kingman ARIZONA@WORK and DES Kingman office.",
    notes_es="Llame al 928-753-0723; se vincula con ARIZONA@WORK Kingman y oficina DES.",
    hours="Monday–Friday business hours",
    tags="kingman|mohave|housing|rental-assistance|reentry",
    services="Emergency shelter referrals|Rental assistance|Homeless prevention|CDBG housing navigation",
    county="Mohave", served_counties="Mohave", coverage="single",
    _source="https://www.mohave.gov", _source_type="government", _confidence="high",
  )
  add(
    name="Gila County Housing & Community Action",
    category="housing", region="Globe / Gila County",
    description="Gila County Community Action Program coordinates emergency rental assistance, utility help, and homeless prevention for low-income households in Gila and eastern Maricopa foothill communities including returning citizens released to Globe and Payson. Community action navigation—not a walk-in emergency shelter.",
    description_es="El Programa de Acción Comunitaria del condado Gila coordina asistencia de alquiler de emergencia, ayuda con servicios públicos y prevención de falta de vivienda para hogares de bajos ingresos en Gila y comunidades del este de Maricopa.",
    address="5515 South Apache Avenue", city="Globe", phone="928-425-7631", email="",
    website="https://www.gilacountyaz.gov",
    eligibility="Low-income Gila County residents; justice-involved adults may qualify for emergency rental and utility assistance.",
    eligibility_es="Residentes de bajos ingresos del condado Gila; adultos con antecedentes penales pueden calificar para asistencia de alquiler y servicios públicos de emergencia.",
    notes="Call 928-425-7631; pairs with DES Globe office and Cobre Valley Regional Medical Center.",
    notes_es="Llame al 928-425-7631; se vincula con oficina DES Globe.",
    hours="Monday–Friday business hours",
    tags="globe|gila|housing|rental-assistance|community-action|reentry",
    services="Emergency rental assistance|Utility assistance|Homeless prevention|Housing counseling",
    county="Gila", served_counties="Gila", coverage="single",
    _source="https://www.gilacountyaz.gov", _source_type="government", _confidence="high",
  )

  # --- education (+7 to reach 12) ---
  add(
    name="Rio Salado College — Adult Basic Education",
    category="education", region="Phoenix / Maricopa County",
    description="Rio Salado College Adult Basic Education offers free GED preparation, English language learning, and college bridge courses at locations across Maricopa County for justice-involved adults including students referred from Maricopa County jails and ADCRR reentry programs.",
    description_es="Rio Salado College Educación Básica para Adultos ofrece preparación GED gratuita, aprendizaje del idioma inglés y cursos puente universitarios en ubicaciones del condado Maricopa para adultos con antecedentes penales.",
    address="2323 West 14th Street", city="Tempe", phone="480-517-8110", email="",
    website="https://www.riosalado.edu",
    eligibility="Maricopa County adults age 16+; free ABE and GED classes for eligible students.",
    eligibility_es="Adultos del condado Maricopa de 16+ años; clases ABE y GED gratuitas para estudiantes elegibles.",
    notes="Call 480-517-8110; multiple valley locations; pairs with ARIZONA@WORK Phoenix.",
    notes_es="Llame al 480-517-8110; múltiples ubicaciones en el valle.",
    hours="Class schedules vary by site",
    tags="tempe|maricopa|education|GED|ABE|reentry",
    services="GED preparation|Adult Basic Education|English language learning|College bridge courses|Workforce referrals",
    county="Maricopa", served_counties="Maricopa", coverage="single",
    _source="https://www.riosalado.edu", _source_type="government", _confidence="high",
  )
  add(
    name="Maricopa County Adult Education",
    category="education", region="Phoenix / Maricopa County",
    description="Maricopa County School Superintendent Adult Education programs provide free High School Equivalency and English language instruction at community sites across Maricopa County for justice-involved adults rebuilding education credentials after release from county jail or state prison.",
    description_es="Los programas de Educación para Adultos del Superintendente Escolar del condado Maricopa ofrecen equivalencia de secundaria e instrucción de inglés gratuitas en sitios comunitarios para adultos con antecedentes penales.",
    address="4041 North 21st Avenue", city="Phoenix", phone="602-506-3884", email="",
    website="https://www.maricopa.gov/560/Adult-Education",
    eligibility="Maricopa County residents age 16+ without high school diploma; free HSE classes.",
    eligibility_es="Residentes del condado Maricopa de 16+ años sin diploma de secundaria; clases HSE gratuitas.",
    notes="Call 602-506-3884 for nearest class site; pairs with Rio Salado and ARIZONA@WORK.",
    notes_es="Llame al 602-506-3884 para el sitio de clases más cercano.",
    hours="Class schedules vary",
    tags="phoenix|maricopa|education|HSE|GED|reentry",
    services="High School Equivalency|English language instruction|Adult education|Workforce pathway referrals",
    county="Maricopa", served_counties="Maricopa", coverage="single",
    _source="https://www.maricopa.gov/560/Adult-Education", _source_type="government", _confidence="high",
  )
  add(
    name="Pima Community College — Adult Basic Education",
    category="education", region="Tucson / Pima County",
    description="Pima Community College Adult Basic Education offers free GED preparation and English language classes for Pima County adults including justice-involved students at Desert Vista and other Tucson campuses, with referrals from Pima County Jail education programs.",
    description_es="Pima Community College Educación Básica para Adultos ofrece preparación GED gratuita y clases de inglés para adultos del condado Pima incluidos estudiantes con antecedentes penales en campus de Tucson.",
    address="4905 East Broadway Boulevard", city="Tucson", phone="520-206-7330", email="",
    website="https://www.pima.edu",
    eligibility="Pima County adults age 16+; free ABE and GED for qualifying students.",
    eligibility_es="Adultos del condado Pima de 16+ años; ABE y GED gratuitos para estudiantes que califiquen.",
    notes="Call 520-206-7330; Desert Vista campus main ABE site; pairs with Pima County One-Stop.",
    notes_es="Llame al 520-206-7330; campus Desert Vista sitio principal de ABE.",
    hours="Class schedules vary",
    tags="tucson|pima|education|GED|ABE|reentry",
    services="GED preparation|Adult Basic Education|English language learning|College transition|Workforce referrals",
    county="Pima", served_counties="Pima", coverage="single",
    _source="https://www.pima.edu", _source_type="government", _confidence="high",
  )
  add(
    name="Yavapai College — Adult Basic Education",
    category="education", region="Prescott / Yavapai County",
    description="Yavapai College Adult Basic Education provides free GED and High School Equivalency preparation for adults in Yavapai County including justice-involved residents at Prescott and Verde Valley campuses, with connections to ARIZONA@WORK and West Yavapai Guidance Clinic.",
    description_es="Yavapai College Educación Básica para Adultos ofrece preparación GED y equivalencia de secundaria gratuita para adultos en el condado Yavapai incluidos residentes con antecedentes penales.",
    address="1100 East Sheldon Street", city="Prescott", phone="928-717-7747", email="",
    website="https://www.yc.edu",
    eligibility="Yavapai County adults age 16+; free HSE preparation.",
    eligibility_es="Adultos del condado Yavapai de 16+ años; preparación HSE gratuita.",
    notes="Call 928-717-7747; Prescott and Clarkdale campuses; pairs with ARIZONA@WORK Prescott.",
    notes_es="Llame al 928-717-7747; campus Prescott y Clarkdale.",
    hours="Class schedules vary",
    tags="prescott|yavapai|education|GED|reentry",
    services="GED preparation|High School Equivalency|Adult education|Workforce referrals",
    county="Yavapai", served_counties="Yavapai", coverage="single",
    _source="https://www.yc.edu", _source_type="government", _confidence="high",
  )
  add(
    name="Arizona Western College — Adult Education",
    category="education", region="Yuma / Yuma County",
    description="Arizona Western College Adult Education offers free GED preparation and English language classes for Yuma and La Paz county adults including justice-involved students returning from Arizona State Prison Complex Yuma and county jail releases.",
    description_es="Arizona Western College Educación para Adultos ofrece preparación GED gratuita y clases de inglés para adultos de los condados Yuma y La Paz incluidos estudiantes con antecedentes penales.",
    address="2020 South Avenue 8 East", city="Yuma", phone="928-344-7567", email="",
    website="https://www.azwestern.edu",
    eligibility="Yuma and La Paz County adults age 16+; free HSE classes.",
    eligibility_es="Adultos de los condados Yuma y La Paz de 16+ años; clases HSE gratuitas.",
    notes="Call 928-344-7567; main Yuma campus; pairs with ARIZONA@WORK Yuma.",
    notes_es="Llame al 928-344-7567; campus principal Yuma.",
    hours="Class schedules vary",
    tags="yuma|la-paz|education|GED|reentry",
    services="GED preparation|English language learning|Adult education|Workforce referrals",
    county="Yuma", served_counties="Yuma|La Paz", coverage="multi",
    _source="https://www.azwestern.edu", _source_type="government", _confidence="high",
  )
  add(
    name="Cochise College — Adult Education",
    category="education", region="Sierra Vista / Cochise County",
    description="Cochise College Adult Education provides free GED and High School Equivalency classes for Cochise County adults including justice-involved residents at Sierra Vista and Douglas campuses, coordinating with Fort Huachuca-area workforce partners.",
    description_es="Cochise College Educación para Adultos ofrece clases GED y equivalencia de secundaria gratuitas para adultos del condado Cochise incluidos residentes con antecedentes penales.",
    address="901 North Colombo Avenue", city="Sierra Vista", phone="520-515-5456", email="",
    website="https://www.cochise.edu",
    eligibility="Cochise County adults age 16+; free HSE preparation.",
    eligibility_es="Adultos del condado Cochise de 16+ años; preparación HSE gratuita.",
    notes="Call 520-515-5456; Sierra Vista and Douglas sites; pairs with DES Sierra Vista.",
    notes_es="Llame al 520-515-5456; sitios Sierra Vista y Douglas.",
    hours="Class schedules vary",
    tags="sierra-vista|cochise|education|GED|reentry",
    services="GED preparation|High School Equivalency|Adult education|Workforce referrals",
    county="Cochise", served_counties="Cochise", coverage="single",
    _source="https://www.cochise.edu", _source_type="government", _confidence="high",
  )
  add(
    name="Coconino Community College — Adult Education",
    category="education", region="Flagstaff / Coconino County",
    description="Coconino Community College Adult Education offers free GED preparation and English language instruction for northern Arizona adults including justice-involved Flagstaff residents, with referrals from Coconino County Jail programs and North Country HealthCare.",
    description_es="Coconino Community College Educación para Adultos ofrece preparación GED gratuita e instrucción de inglés para adultos del norte de Arizona incluidos residentes de Flagstaff con antecedentes penales.",
    address="2800 South Lone Tree Road", city="Flagstaff", phone="928-527-1222", email="",
    website="https://www.coconino.edu",
    eligibility="Coconino County adults age 16+; free HSE and ESL classes.",
    eligibility_es="Adultos del condado Coconino de 16+ años; clases HSE y ESL gratuitas.",
    notes="Call 928-527-1222; Lone Tree campus; pairs with ARIZONA@WORK Flagstaff.",
    notes_es="Llame al 928-527-1222; campus Lone Tree.",
    hours="Class schedules vary",
    tags="flagstaff|coconino|education|GED|reentry",
    services="GED preparation|English language instruction|Adult education|Workforce referrals",
    county="Coconino", served_counties="Coconino", coverage="single",
    _source="https://www.coconino.edu", _source_type="government", _confidence="high",
  )

  # --- basic-needs (+4) ---
  add(
    name="Society of St. Vincent de Paul — Phoenix",
    category="basic-needs", region="Phoenix / Maricopa County",
    description="Society of St. Vincent de Paul Phoenix provides emergency food boxes, clothing, utility assistance, and furniture for low-income Maricopa County households including returning citizens reestablishing basic needs after incarceration. Vincentian volunteers operate neighborhood conferences and a central dining room—not a benefits application office.",
    description_es="La Sociedad de San Vicente de Paul Phoenix ofrece cajas de alimentos de emergencia, ropa, asistencia con servicios públicos y muebles para hogares de bajos ingresos del condado Maricopa incluidos ciudadanos que regresan.",
    address="420 West Watkins Street", city="Phoenix", phone="602-261-6888", email="",
    website="https://www.stvincentdepaul.net",
    eligibility="Low-income Maricopa County residents in need; justice-involved households welcome for food and clothing assistance.",
    eligibility_es="Residentes de bajos ingresos del condado Maricopa en necesidad; hogares con antecedentes penales bienvenidos para asistencia de alimentos y ropa.",
    notes="Call 602-261-6888; dining room meals available; pairs with St. Mary's Food Bank.",
    notes_es="Llame al 602-261-6888; comidas en comedor disponibles.",
    hours="Dining room and assistance hours vary; call ahead",
    tags="phoenix|maricopa|basic-needs|food|clothing|reentry",
    services="Emergency food boxes|Clothing|Utility assistance|Furniture|Dining room meals",
    county="Maricopa", served_counties="Maricopa", coverage="single",
    _source="https://www.stvincentdepaul.net", _source_type="nonprofit", _confidence="high",
  )
  add(
    name="Salvation Army — Phoenix Family Services",
    category="basic-needs", region="Phoenix / Maricopa County",
    description="The Salvation Army Phoenix Family Services campus provides emergency food, clothing, utility assistance, and seasonal shelter beds for low-income Maricopa County families including justice-involved households seeking stabilization after release.",
    description_es="El campus Salvation Army Phoenix Family Services ofrece alimentos de emergencia, ropa, asistencia con servicios públicos y camas de refugio estacionales para familias de bajos ingresos del condado Maricopa.",
    address="2707 East Van Buren Street", city="Phoenix", phone="602-267-4122", email="",
    website="https://phoenix.salvationarmy.org",
    eligibility="Low-income Maricopa County families and individuals; justice-involved clients eligible for emergency assistance per program.",
    eligibility_es="Familias e individuos de bajos ingresos del condado Maricopa; clientes con antecedentes penales elegibles para asistencia de emergencia.",
    notes="Call 602-267-4122; not a DES benefits office.",
    notes_es="Llame al 602-267-4122; no es oficina de beneficios DES.",
    hours="Monday–Friday business hours; seasonal shelter hours vary",
    tags="phoenix|maricopa|basic-needs|food|utility|reentry",
    services="Emergency food|Clothing|Utility assistance|Seasonal shelter|Case management referrals",
    county="Maricopa", served_counties="Maricopa", coverage="single",
    _source="https://phoenix.salvationarmy.org", _source_type="nonprofit", _confidence="high",
  )
  add(
    name="Interfaith Community Services — Tucson",
    category="basic-needs", region="Tucson / Pima County",
    description="Interfaith Community Services provides emergency food, financial assistance, and basic needs navigation for low-income Pima County households including returning citizens, operating a food bank and utility assistance program in northwest Tucson.",
    description_es="Interfaith Community Services ofrece alimentos de emergencia, asistencia financiera y navegación de necesidades básicas para hogares de bajos ingresos del condado Pima incluidos ciudadanos que regresan.",
    address="2820 West Ina Road", city="Tucson", phone="520-297-6049", email="",
    website="https://www.icstucson.org",
    eligibility="Low-income Pima County residents; justice-involved households may qualify for emergency assistance.",
    eligibility_es="Residentes de bajos ingresos del condado Pima; hogares con antecedentes penales pueden calificar para asistencia de emergencia.",
    notes="Call 520-297-6049; food bank and financial assistance by appointment.",
    notes_es="Llame al 520-297-6049; banco de alimentos y asistencia financiera con cita.",
    hours="Monday–Friday business hours",
    tags="tucson|pima|basic-needs|food|utility|reentry",
    services="Emergency food bank|Financial assistance|Utility help|Basic needs navigation|Referrals",
    county="Pima", served_counties="Pima", coverage="single",
    _source="https://www.icstucson.org", _source_type="nonprofit", _confidence="high",
  )
  add(
    name="Yuma Community Food Bank",
    category="basic-needs", region="Yuma / Yuma County",
    description="Yuma Community Food Bank distributes emergency groceries and partners with Crossroads Mission and DES Yuma to support low-income households in Yuma and La Paz counties including returning citizens rebuilding food security after incarceration.",
    description_es="Yuma Community Food Bank distribuye comestibles de emergencia y se asocia con Crossroads Mission y DES Yuma para apoyar hogares de bajos ingresos en los condados Yuma y La Paz.",
    address="2404 East 24th Street", city="Yuma", phone="928-343-1243", email="",
    website="https://www.yumafoodbank.org",
    eligibility="Low-income Yuma and La Paz County residents; no criminal-record barrier stated.",
    eligibility_es="Residentes de bajos ingresos de los condados Yuma y La Paz; sin barrera de antecedentes indicada.",
    notes="Call 928-343-1243 for distribution schedule; pairs with Community Food Bank of Southern Arizona network.",
    notes_es="Llame al 928-343-1243 para horario de distribución.",
    hours="Distribution hours vary; call ahead",
    tags="yuma|la-paz|basic-needs|food-bank|reentry",
    services="Emergency food distribution|Grocery boxes|Partner agency referrals|Nutrition support",
    county="Yuma", served_counties="Yuma|La Paz", coverage="multi",
    _source="https://www.yumafoodbank.org", _source_type="nonprofit", _confidence="high",
  )

  # --- family-children (+1), food-nutrition (+1), id-documentation (+1) ---
  add(
    name="Arizona's Children Association — Family Support",
    category="family-children", region="Phoenix / Maricopa County",
    description="Arizona's Children Association provides foster care, kinship support, and family preservation services for vulnerable Maricopa County families including justice-involved parents working toward reunification after CPS or criminal justice involvement. Case managers coordinate DES child care subsidies and housing partners.",
    description_es="Arizona's Children Association ofrece cuidado de crianza, apoyo de parentesco y servicios de preservación familiar para familias vulnerables del condado Maricopa incluidos padres con antecedentes penales que trabajan hacia la reunificación.",
    address="3716 East Columbia Street", city="Phoenix", phone="602-234-1935", email="",
    website="https://www.arizonaschildren.org",
    eligibility="Maricopa County families involved with child welfare or needing kinship support; justice-involved parents may qualify for reunification services.",
    eligibility_es="Familias del condado Maricopa involucradas con bienestar infantil o que necesitan apoyo de parentesco; padres con antecedentes penales pueden calificar.",
    notes="Call 602-234-1935; not an emergency CPS hotline.",
    notes_es="Llame al 602-234-1935; no es línea directa de emergencia de CPS.",
    hours="Monday–Friday business hours",
    tags="phoenix|maricopa|family-children|kinship|reunification|reentry",
    services="Kinship caregiver support|Family preservation|Foster care navigation|Parent education|Benefits referrals",
    county="Maricopa", served_counties="Maricopa", coverage="single",
    _source="https://www.arizonaschildren.org", _source_type="nonprofit", _confidence="high",
  )
  add(
    name="Community Food Bank of Southern Arizona",
    category="food-nutrition", region="Tucson / Pima County",
    description="Community Food Bank of Southern Arizona distributes groceries through partner agencies and direct programs across Pima, Santa Cruz, Cochise, and Graham counties for low-income households including returning citizens reestablishing food security after incarceration.",
    description_es="Community Food Bank del Sur de Arizona distribuye comestibles a través de agencias aliadas y programas directos en los condados Pima, Santa Cruz, Cochise y Graham para hogares de bajos ingresos.",
    address="3003 South Country Club Road", city="Tucson", phone="520-622-0525", email="",
    website="https://www.communityfoodbank.org",
    eligibility="Low-income residents in southern Arizona service area; partner agency referral or direct distribution sites.",
    eligibility_es="Residentes de bajos ingresos en el área de servicio del sur de Arizona; referencia de agencia aliada o sitios de distribución directa.",
    notes="Call 520-622-0525 or use food bank locator online; not a SNAP application office.",
    notes_es="Llame al 520-622-0525 o use el localizador en línea; no es oficina de solicitud SNAP.",
    hours="Distribution hours vary by site",
    tags="tucson|pima|food-nutrition|food-bank|southern-arizona|reentry",
    services="Emergency food distribution|Partner agency network|Nutrition programs|Mobile food pantry",
    county="Pima", served_counties="Pima|Santa Cruz|Cochise|Graham", coverage="multi",
    _source="https://www.communityfoodbank.org", _source_type="nonprofit", _confidence="high",
  )
  add(
    name="Maricopa County Recorder — Voter Registration & ID",
    category="id-documentation", region="Phoenix / Maricopa County",
    description="The Maricopa County Recorder's Office assists residents with voter registration, replacement voter ID cards, and guidance on restoring voting rights after felony convictions under Arizona law. Staff provide forms and referrals to Arizona MVD and Community Legal Services—not DMV licensing services.",
    description_es="La Oficina del Registrador del condado Maricopa ayuda a residentes con registro de votantes, tarjetas de identificación de votante de reemplazo y orientación sobre restauración de derechos de voto después de condenas por delitos graves según la ley de Arizona.",
    address="111 South 3rd Avenue", city="Phoenix", phone="602-506-1511", email="",
    website="https://recorder.maricopa.gov",
    eligibility="Maricopa County residents; individuals with felony convictions should verify rights restoration requirements.",
    eligibility_es="Residentes del condado Maricopa; personas con condenas por delitos graves deben verificar requisitos de restauración de derechos.",
    notes="Call 602-506-1511; online voter registration at ServiceArizona.com; pairs with Arizona MVD.",
    notes_es="Llame al 602-506-1511; registro de votantes en ServiceArizona.com; se vincula con MVD de Arizona.",
    hours="Monday–Friday business hours",
    tags="phoenix|maricopa|id-documentation|voting-rights|reentry",
    services="Voter registration|Voter ID guidance|Rights restoration information|Document counseling",
    county="Maricopa", served_counties="Maricopa", coverage="single",
    _source="https://recorder.maricopa.gov", _source_type="government", _confidence="high",
  )

  # --- legal-aid (+2), probation-parole (+2), state-agency (+2), transportation (+1), veterans (+3) ---
  add(
    name="Community Legal Services — Mesa Office",
    category="legal-aid", region="Mesa / Maricopa County",
    description="Community Legal Services Mesa office provides free civil legal aid to low-income east valley residents including housing, public benefits, and record relief matters for justice-involved clients in Maricopa County—not criminal defense.",
    description_es="La oficina Mesa de Community Legal Services brinda asistencia legal civil gratuita a residentes de bajos ingresos del valle este incluyendo vivienda, beneficios públicos y alivio de antecedentes.",
    address="714 West Southern Avenue", city="Mesa", phone="1-800-852-9075", email="",
    website="https://www.clsaz.org",
    eligibility="Low-income Maricopa County residents; LSC income limits; civil matters only.",
    eligibility_es="Residentes de bajos ingresos del condado Maricopa; límites de ingresos LSC; solo asuntos civiles.",
    notes="Apply at clsaz.org or call 1-800-852-9075; east valley satellite office.",
    notes_es="Solicite en clsaz.org o llame al 1-800-852-9075.",
    hours="Monday–Friday business hours",
    tags="mesa|maricopa|legal-aid|low-income|reentry",
    services="Housing legal aid|Benefits advocacy|Record relief guidance|Eviction defense|Regional intake",
    county="Maricopa", served_counties="Maricopa", coverage="single",
    _source="https://www.clsaz.org", _source_type="nonprofit", _confidence="high",
  )
  add(
    name="DNA People's Legal Services — Flagstaff Office",
    category="legal-aid", region="Flagstaff / Coconino County",
    description="DNA People's Legal Services Flagstaff office provides free civil legal assistance to low-income residents of Coconino, Navajo, and Apache counties including public benefits, housing, and family law for justice-involved clients on tribal and non-tribal lands—not criminal defense.",
    description_es="La oficina Flagstaff de DNA People's Legal Services brinda asistencia legal civil gratuita a residentes de bajos ingresos de los condados Coconino, Navajo y Apache incluyendo beneficios públicos y vivienda.",
    address="2225 North Steves Boulevard", city="Flagstaff", phone="928-774-9000", email="",
    website="https://www.dnaazlaw.org",
    eligibility="Low-income residents of northern Arizona service area; tribal and non-tribal clients.",
    eligibility_es="Residentes de bajos ingresos del área de servicio del norte de Arizona; clientes tribales y no tribales.",
    notes="Call 928-774-9000; serves Coconino, Navajo, Apache, and portions of Mohave.",
    notes_es="Llame al 928-774-9000; sirve Coconino, Navajo, Apache y partes de Mohave.",
    hours="Monday–Friday business hours",
    tags="flagstaff|coconino|legal-aid|northern-arizona|reentry",
    services="Civil legal representation|Benefits advocacy|Housing legal aid|Family law assistance|Tribal coordination",
    county="Coconino", served_counties="Coconino|Navajo|Apache", coverage="multi",
    _source="https://www.dnaazlaw.org", _source_type="nonprofit", _confidence="high",
  )
  add(
    name="ADCRR — Kingman Community Corrections",
    category="probation-parole", region="Kingman / Mohave County",
    description="The ADCRR Kingman Community Corrections office supervises parolees and probationers in Mohave County, coordinating referrals to Mohave County ARIZONA@WORK, Kingman DES office, and regional behavioral health providers for justice-involved adults under state supervision.",
    description_es="La oficina de Correcciones Comunitarias ADCRR en Kingman supervisa personas en libertad condicional y probatoria en el condado Mohave, coordinando referencias con ARIZONA@WORK y proveedores de salud conductual.",
    address="303 West Beale Street", city="Kingman", phone="928-718-3956", email="",
    website="https://corrections.az.gov/adcr/community-corrections",
    eligibility="Adults under ADCRR supervision in Mohave County; report to assigned officer.",
    eligibility_es="Adultos bajo supervisión de ADCRR en el condado Mohave; reporte al oficial asignado.",
    notes="Call 928-718-3956; not a walk-in benefits office.",
    notes_es="Llame al 928-718-3956; no es oficina de beneficios.",
    hours="Monday–Friday business hours",
    tags="kingman|mohave|probation-parole|ADCRR|reentry",
    services="Parole supervision|Community corrections reporting|Treatment referrals|Employment coordination",
    county="Mohave", served_counties="Mohave", coverage="single",
    _source="https://corrections.az.gov/adcr/community-corrections", _source_type="government", _confidence="high",
  )
  add(
    name="ADCRR — Florence Complex Reentry Coordination",
    category="probation-parole", region="Florence / Pinal County",
    description="ADCRR staff at Arizona State Prison Complex Florence coordinate pre-release reentry planning and community corrections handoffs for individuals returning to Pinal, Maricopa, and Pima counties, connecting supervisees to ARIZONA@WORK, DES benefits, and local housing partners.",
    description_es="El personal de ADCRR en el Complejo Penitenciario Estatal de Florence coordina la planificación de reinserción previa a la liberación y traspasos de correcciones comunitarias para personas que regresan a los condados Pinal, Maricopa y Pima.",
    address="1305 East Butte Avenue", city="Florence", phone="520-868-4011", email="",
    website="https://corrections.az.gov/adcr/reentry",
    eligibility="Individuals in ADCRR custody at Florence complex preparing for release; community partners use published reentry resources.",
    eligibility_es="Personas en custodia de ADCRR en el complejo Florence que se preparan para la liberación; aliados comunitarios usan recursos publicados.",
    notes="Coordinate through facility reentry staff; not a public walk-in office for emergency needs.",
    notes_es="Coordine con el personal de reinserción de la instalación; no es oficina pública sin cita para necesidades de emergencia.",
    hours="Facility business hours",
    tags="florence|pinal|probation-parole|ADCRR|reentry|pre-release",
    services="Pre-release planning|Community corrections handoff|Reentry referrals|Supervision coordination",
    county="Pinal", served_counties="Pinal|Maricopa|Pima", coverage="multi",
    _source="https://corrections.az.gov/adcr/reentry", _source_type="government", _confidence="high",
  )
  add(
    name="Arizona Department of Housing — Homelessness & Rental Assistance",
    category="state-agency", region="Statewide",
    description="The Arizona Department of Housing administers statewide homelessness prevention, emergency rental assistance, and affordable housing programs that justice-involved Arizonans may access through regional housing navigators and coordinated entry systems in Maricopa, Pima, and rural counties.",
    description_es="El Departamento de Vivienda de Arizona administra programas estatales de prevención de falta de vivienda, asistencia de alquiler de emergencia y vivienda asequible que los arizonenses en reinserción pueden acceder a través de navegadores regionales.",
    address="1110 West Washington Street", city="Phoenix", phone="602-771-1000", email="",
    website="https://housing.az.gov",
    eligibility="Arizona residents meeting program income requirements for rental assistance and homelessness prevention; eligibility varies by program.",
    eligibility_es="Residentes de Arizona que cumplan requisitos de ingresos del programa para asistencia de alquiler y prevención de falta de vivienda; la elegibilidad varía.",
    notes="Browse programs at housing.az.gov; apply through local coordinated entry in your county.",
    notes_es="Explore programas en housing.az.gov; solicite a través de entrada coordinada local en su condado.",
    hours="State office Monday–Friday business hours",
    tags="statewide|housing|rental-assistance|ADOH|reentry",
    services="Emergency rental assistance|Homelessness prevention|Affordable housing programs|Housing navigator referrals",
    county="Maricopa", served_counties="", coverage="statewide",
    _source="https://housing.az.gov", _source_type="government", _confidence="high",
  )
  add(
    name="Arizona Attorney General — Victim Services",
    category="state-agency", region="Statewide",
    description="The Arizona Attorney General Victim Services Division provides crime victim compensation, restitution assistance, and referral navigation for eligible Arizonans including justice-involved crime victims and witnesses—not criminal defense representation.",
    description_es="La División de Servicios a Víctimas del Fiscal General de Arizona ofrece compensación a víctimas de delitos, asistencia de restitución y navegación de referencias para arizonenses elegibles incluidas víctimas con antecedentes penales.",
    address="2005 North Central Avenue", city="Phoenix", phone="602-542-5025", email="",
    website="https://www.azag.gov/criminal/victim-services",
    eligibility="Crime victims meeting Arizona victim compensation eligibility; application required.",
    eligibility_es="Víctimas de delitos que cumplan elegibilidad de compensación de Arizona; se requiere solicitud.",
    notes="Call 602-542-5025 or visit azag.gov victim services; not a general reentry cash program.",
    notes_es="Llame al 602-542-5025 o visite servicios a víctimas en azag.gov.",
    hours="Monday–Friday business hours",
    tags="statewide|victim-services|compensation|reentry",
    services="Crime victim compensation|Restitution assistance|Victim advocacy referrals|Application support",
    county="Maricopa", served_counties="", coverage="statewide",
    _source="https://www.azag.gov/criminal/victim-services", _source_type="government", _confidence="high",
  )
  add(
    name="Valley Metro — Reduced Fare & Reentry Transit",
    category="transportation", region="Phoenix / Maricopa County",
    description="Valley Metro provides public bus and light rail service across Maricopa County with reduced-fare passes for low-income riders including justice-involved adults returning from incarceration who need affordable transportation to ARIZONA@WORK, DES offices, and treatment appointments.",
    description_es="Valley Metro ofrece servicio de autobús y tren ligero en el condado Maricopa con pases de tarifa reducida para pasajeros de bajos ingresos incluidos adultos con antecedentes penales que necesitan transporte asequible.",
    address="4600 East Washington Street", city="Phoenix", phone="602-253-5000", email="",
    website="https://www.valleymetro.org",
    eligibility="Maricopa County riders; reduced-fare programs for seniors, disabled, and low-income riders per Valley Metro policy.",
    eligibility_es="Pasajeros del condado Maricopa; programas de tarifa reducida para mayores, discapacitados y de bajos ingresos según política de Valley Metro.",
    notes="Call 602-253-5000; buy passes online or at light rail stations; not a paratransit medical broker.",
    notes_es="Llame al 602-253-5000; compre pases en línea o en estaciones de tren ligero.",
    hours="Service hours vary by route",
    tags="phoenix|maricopa|transportation|transit|reduced-fare|reentry",
    services="Bus and light rail service|Reduced-fare passes|Route planning|ADA paratransit referrals",
    county="Maricopa", served_counties="Maricopa", coverage="single",
    _source="https://www.valleymetro.org", _source_type="government", _confidence="high",
  )
  add(
    name="Arizona Department of Veterans Services — Yuma County Office",
    category="veterans", region="Yuma / Yuma County",
    description="The Arizona Department of Veterans Services Yuma County office provides free VA benefits claims assistance, discharge upgrade guidance, and referral navigation for justice-involved veterans in Yuma and La Paz counties through the state county veterans service officer network.",
    description_es="La oficina del condado Yuma del Departamento de Servicios para Veteranos de Arizona ofrece asistencia gratuita con reclamaciones de beneficios VA y navegación de referencias para veteranos con antecedentes penales en los condados Yuma y La Paz.",
    address="1800 East Palo Verde Street", city="Yuma", phone="928-783-0132", email="",
    website="https://dvs.az.gov",
    eligibility="Veterans and eligible dependents in Yuma and La Paz counties; service documentation required for VA claims.",
    eligibility_es="Veteranos y dependientes elegibles en los condados Yuma y La Paz; se requiere documentación de servicio.",
    notes="Call 928-783-0132 for appointment; free claims help; pairs with Crossroads Mission and AWC adult ed.",
    notes_es="Llame al 928-783-0132 para cita; ayuda gratuita con reclamaciones.",
    hours="Monday–Friday business hours",
    tags="yuma|la-paz|veterans|VA-benefits|reentry",
    services="VA benefits claims assistance|Discharge upgrade guidance|Healthcare enrollment help|Veteran employment referrals",
    county="Yuma", served_counties="Yuma|La Paz", coverage="multi",
    _source="https://dvs.az.gov", _source_type="government", _confidence="high",
  )
  add(
    name="Arizona Department of Veterans Services — Coconino County Office",
    category="veterans", region="Flagstaff / Coconino County",
    description="The Arizona Department of Veterans Services Coconino County office assists northern Arizona veterans including justice-involved veterans in Flagstaff, Navajo, and Apache counties with VA disability claims, healthcare enrollment, and referrals to North Country HealthCare and ARIZONA@WORK Flagstaff.",
    description_es="La oficina del condado Coconino del Departamento de Servicios para Veteranos de Arizona ayuda a veteranos del norte de Arizona incluidos veteranos con antecedentes penales con reclamaciones de discapacidad VA e inscripción en atención médica.",
    address="1515 East Cedar Avenue", city="Flagstaff", phone="928-226-0488", email="",
    website="https://dvs.az.gov",
    eligibility="Veterans and eligible dependents in Coconino County and northern Arizona; service documentation required.",
    eligibility_es="Veteranos y dependientes elegibles en el condado Coconino y el norte de Arizona; se requiere documentación de servicio.",
    notes="Call 928-226-0488; free county veterans service officer assistance.",
    notes_es="Llame al 928-226-0488; asistencia gratuita del oficial de servicios para veteranos del condado.",
    hours="Monday–Friday business hours",
    tags="flagstaff|coconino|veterans|VA-benefits|northern-arizona|reentry",
    services="VA benefits claims assistance|Healthcare enrollment|Disability compensation navigation|Employment referrals",
    county="Coconino", served_counties="Coconino|Navajo|Apache", coverage="multi",
    _source="https://dvs.az.gov", _source_type="government", _confidence="high",
  )
  add(
    name="Arizona Department of Veterans Services — Mohave County Office",
    category="veterans", region="Kingman / Mohave County",
    description="The Arizona Department of Veterans Services Mohave County office provides free VA claims assistance and benefits navigation for veterans in Kingman, Lake Havasu City, and Bullhead City including justice-involved veterans coordinating with Mohave County ARIZONA@WORK and regional behavioral health providers.",
    description_es="La oficina del condado Mohave del Departamento de Servicios para Veteranos de Arizona ofrece asistencia gratuita con reclamaciones VA y navegación de beneficios para veteranos en Kingman, Lake Havasu City y Bullhead City.",
    address="700 West Beale Street", city="Kingman", phone="928-753-0713", email="",
    website="https://dvs.az.gov",
    eligibility="Veterans and eligible dependents in Mohave County; service documentation required for VA claims.",
    eligibility_es="Veteranos y dependientes elegibles en el condado Mohave; se requiere documentación de servicio.",
    notes="Call 928-753-0713 for appointment; pairs with Kingman ADCRR community corrections.",
    notes_es="Llame al 928-753-0713 para cita; se vincula con correcciones comunitarias ADCRR Kingman.",
    hours="Monday–Friday business hours",
    tags="kingman|mohave|veterans|VA-benefits|reentry",
    services="VA benefits claims assistance|Healthcare enrollment help|Disability navigation|Employment referrals",
    county="Mohave", served_counties="Mohave", coverage="single",
    _source="https://dvs.az.gov", _source_type="government", _confidence="high",
  )
  add(
    name="United Food Bank — Emergency Food Distribution",
    category="basic-needs", region="Mesa / Maricopa County",
    description="United Food Bank distributes emergency groceries through partner pantries and direct programs across eastern Maricopa, Pinal, and Gila counties for low-income households including returning citizens reestablishing food security after incarceration.",
    description_es="United Food Bank distribuye comestibles de emergencia a través de despensas aliadas y programas directos en el este del condado Maricopa, Pinal y Gila para hogares de bajos ingresos.",
    address="245 South Nina Drive", city="Mesa", phone="480-926-4897", email="",
    website="https://www.unitedfoodbank.org",
    eligibility="Low-income residents in United Food Bank service area; partner pantry locator online.",
    eligibility_es="Residentes de bajos ingresos en el área de servicio de United Food Bank; localizador de despensas aliadas en línea.",
    notes="Call 480-926-4897 or use pantry locator; not a SNAP application office.",
    notes_es="Llame al 480-926-4897 o use el localizador de despensas.",
    hours="Warehouse hours vary; call partner pantries",
    tags="mesa|maricopa|basic-needs|food-bank|reentry",
    services="Emergency food distribution|Partner pantry network|Mobile pantry|Nutrition programs",
    county="Maricopa", served_counties="Maricopa|Pinal|Gila", coverage="multi",
    _source="https://www.unitedfoodbank.org", _source_type="nonprofit", _confidence="high",
  )
  add(
    name="Chicanos Por La Causa — Workforce & Education",
    category="education", region="Phoenix / Maricopa County",
    description="Chicanos Por La Causa workforce and education programs offer GED preparation, digital literacy, and job training for Maricopa County adults including justice-involved participants referred from ARIZONA@WORK and community corrections partners.",
    description_es="Los programas de fuerza laboral y educación de Chicanos Por La Causa ofrecen preparación GED, alfabetización digital y capacitación laboral para adultos del condado Maricopa incluidos participantes con antecedentes penales.",
    address="1112 East Buckeye Road", city="Phoenix", phone="602-257-0700", email="",
    website="https://www.cplc.org",
    eligibility="Maricopa County adults in CPLC service programs; justice-involved participants welcome per program.",
    eligibility_es="Adultos del condado Maricopa en programas de servicio CPLC; participantes con antecedentes penales bienvenidos según programa.",
    notes="Call 602-257-0700; multiple Phoenix sites; pairs with ARIZONA@WORK.",
    notes_es="Llame al 602-257-0700; múltiples sitios en Phoenix.",
    hours="Program hours vary by site",
    tags="phoenix|maricopa|education|GED|workforce|reentry",
    services="GED preparation|Digital literacy|Job training|Workforce navigation|Referrals",
    county="Maricopa", served_counties="Maricopa", coverage="single",
    _source="https://www.cplc.org", _source_type="nonprofit", _confidence="high",
  )
  add(
    name="Literacy Volunteers of Maricopa County",
    category="education", region="Phoenix / Maricopa County",
    description="Literacy Volunteers of Maricopa County provides free adult literacy, ESL, and GED tutoring for low-literacy adults in Maricopa County including justice-involved learners rebuilding education skills after release from county jail or state prison.",
    description_es="Literacy Volunteers of Maricopa County ofrece alfabetización para adultos, ESL y tutoría GED gratuitas para adultos con baja alfabetización en el condado Maricopa incluidos aprendices con antecedentes penales.",
    address="1500 East Thomas Road", city="Phoenix", phone="602-274-3430", email="",
    website="https://www.lvmaricopa.org",
    eligibility="Maricopa County adults needing literacy or ESL support; free volunteer tutoring.",
    eligibility_es="Adultos del condado Maricopa que necesiten apoyo de alfabetización o ESL; tutoría voluntaria gratuita.",
    notes="Call 602-274-3430 to enroll; pairs with Rio Salado Adult Ed.",
    notes_es="Llame al 602-274-3430 para inscribirse.",
    hours="Tutoring schedules arranged with volunteers",
    tags="phoenix|maricopa|education|literacy|ESL|reentry",
    services="Adult literacy tutoring|ESL instruction|GED support|One-on-one tutoring",
    county="Maricopa", served_counties="Maricopa", coverage="single",
    _source="https://www.lvmaricopa.org", _source_type="nonprofit", _confidence="high",
  )
  add(
    name="Literacy Connects — Tucson Adult Education",
    category="education", region="Tucson / Pima County",
    description="Literacy Connects offers free adult literacy, GED support, and English language instruction for Pima County adults including justice-involved learners at Tucson community learning sites.",
    description_es="Literacy Connects ofrece alfabetización para adultos, apoyo GED e instrucción de inglés gratuitas para adultos del condado Pima incluidos aprendices con antecedentes penales.",
    address="200 East Yavapai Road", city="Tucson", phone="520-882-8006", email="",
    website="https://literacyconnects.org",
    eligibility="Pima County adults needing literacy or GED support; free programs.",
    eligibility_es="Adultos del condado Pima que necesiten apoyo de alfabetización o GED; programas gratuitos.",
    notes="Call 520-882-8006; pairs with Pima Community College ABE.",
    notes_es="Llame al 520-882-8006; se vincula con ABE de Pima Community College.",
    hours="Class and tutoring schedules vary",
    tags="tucson|pima|education|literacy|GED|reentry",
    services="Adult literacy|GED support|English language instruction|Workforce referrals",
    county="Pima", served_counties="Pima", coverage="single",
    _source="https://literacyconnects.org", _source_type="nonprofit", _confidence="high",
  )
  add(
    name="Homeward Bound — Transitional Housing",
    category="housing", region="Phoenix / Maricopa County",
    description="Homeward Bound provides transitional housing and supportive services for homeless families and single adults in Maricopa County including justice-involved parents reunifying with children, with case management connecting residents to ARIZONA@WORK and DES benefits.",
    description_es="Homeward Bound ofrece vivienda transicional y servicios de apoyo para familias sin hogar y adultos solteros en el condado Maricopa incluidos padres con antecedentes penales que se reunifican con sus hijos.",
    address="2302 West Colter Street", city="Phoenix", phone="602-263-5531", email="",
    website="https://www.homewardboundaz.org",
    eligibility="Homeless families and adults in Maricopa County; justice-involved applicants per intake screening.",
    eligibility_es="Familias y adultos sin hogar en el condado Maricopa; solicitantes con antecedentes penales según evaluación de admisión.",
    notes="Call 602-263-5531 for intake; not an emergency walk-in shelter for single men only.",
    notes_es="Llame al 602-263-5531 para admisión.",
    hours="Contact for intake hours",
    tags="phoenix|maricopa|housing|transitional|families|reentry",
    services="Transitional housing|Case management|Parent education|Employment referrals|Benefits navigation",
    county="Maricopa", served_counties="Maricopa", coverage="single",
    _source="https://www.homewardboundaz.org", _source_type="nonprofit", _confidence="high",
  )
  add(
    name="Volunteer Lawyers Program — State Bar of Arizona",
    category="legal-aid", region="Phoenix / Maricopa County",
    description="The State Bar of Arizona Volunteer Lawyers Program connects low-income Maricopa County residents including justice-involved clients to pro bono civil attorneys for housing, benefits, family law, and limited record relief matters—not criminal defense.",
    description_es="El Programa de Abogados Voluntarios del Colegio de Abogados de Arizona conecta a residentes de bajos ingresos del condado Maricopa incluidos clientes con antecedentes penales con abogados civiles pro bono.",
    address="4201 North 24th Street", city="Phoenix", phone="602-340-7323", email="",
    website="https://www.azvolunteerlawyers.org",
    eligibility="Low-income Maricopa County residents with civil legal needs; income screening required.",
    eligibility_es="Residentes de bajos ingresos del condado Maricopa con necesidades legales civiles; se requiere evaluación de ingresos.",
    notes="Apply at azvolunteerlawyers.org or call 602-340-7323; complements Community Legal Services.",
    notes_es="Solicite en azvolunteerlawyers.org o llame al 602-340-7323.",
    hours="Monday–Friday business hours",
    tags="phoenix|maricopa|legal-aid|pro-bono|reentry",
    services="Pro bono civil referrals|Housing legal help|Benefits advocacy|Family law referrals|Clinics",
    county="Maricopa", served_counties="Maricopa", coverage="single",
    _source="https://www.azvolunteerlawyers.org", _source_type="nonprofit", _confidence="high",
  )
