"""Phase 4 program-level expansion entries for Arizona reentry resources."""


def register_phase4(add):
    add(
            name="A New Leaf — Rapid Rehousing",
            category="housing",
            region="Mesa / Maricopa County",
            description="A New Leaf Rapid Rehousing helps families and individuals experiencing homelessness in Maricopa County—including parents returning from incarceration—move quickly into permanent housing with short-term rental assistance and case management. Housing specialists connect participants to DES benefits, ARIZONA@WORK, and Valleywise Health while stabilizing leases across the East Valley.",
            description_es="A New Leaf Rapid Rehousing ayuda a familias y personas sin hogar en el condado Maricopa—incluidos padres que regresan de la encarcelación—a trasladarse rápidamente a vivienda permanente con asistencia de alquiler a corto plazo y manejo de casos.",
            address="4340 E Cotton Lane",
            city="Mesa",
            phone="480-833-9200",
            email="",
            website="https://turnanewleaf.org",
            eligibility="Homeless Maricopa County households meeting HUD rapid rehousing criteria; justice-involved families welcome per program policy.",
            eligibility_es="Hogares sin hogar del condado Maricopa que cumplan criterios HUD de realojamiento rápido; familias con antecedentes penales bienvenidas según política.",
            notes="Call 480-833-9200 for housing intake; pairs with UMOM and St. Mary's Food Bank.",
            notes_es="Llame al 480-833-9200 para admisión de vivienda.",
            hours="Monday–Friday business hours",
            tags="mesa|maricopa|housing|rapid-rehousing|reentry|families",
            services="Rapid rehousing|Rental assistance|Case management|Benefits navigation|Employment referrals",
            county="Maricopa",
            served_counties="Maricopa",
            coverage="single",
            _source="https://turnanewleaf.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="House of Refuge — Transitional Housing",
            category="housing",
            region="Mesa / Maricopa County",
            description="House of Refuge provides transitional housing and supportive services for women and children experiencing homelessness in Maricopa County including justice-involved mothers reunifying with children after release. Case managers connect families to DES, ARIZONA@WORK, and Mesa public schools while stabilizing two-year transitional leases.",
            description_es="House of Refuge ofrece vivienda transicional y servicios de apoyo para mujeres y niños sin hogar en el condado Maricopa incluidas madres con antecedentes penales que se reunifican con sus hijos después de la liberación.",
            address="7225 E Baseline Road",
            city="Mesa",
            phone="480-892-8555",
            email="",
            website="https://www.houseofrefuge.org",
            eligibility="Homeless women with children in Maricopa County; justice-involved mothers per program policy.",
            eligibility_es="Mujeres sin hogar con niños en el condado Maricopa; madres con antecedentes penales según política.",
            notes="Call 480-892-8555 for intake; two-year transitional program; pairs with A New Leaf and UMOM.",
            notes_es="Llame al 480-892-8555 para admisión.",
            hours="Office Monday–Friday",
            tags="mesa|maricopa|housing|transitional|women|reentry",
            services="Transitional housing|Case management|Family reunification support|Benefits navigation|School enrollment help",
            county="Maricopa",
            served_counties="Maricopa",
            coverage="single",
            _source="https://www.houseofrefuge.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="CASS — Central Arizona Shelter Services",
            category="housing",
            region="Phoenix / Maricopa County",
            description="Central Arizona Shelter Services operates the largest emergency shelter and rehousing system in Maricopa County, providing single-adult shelter, coordinated entry, and rapid rehousing for justice-involved adults experiencing homelessness in Phoenix. CASS navigators connect clients to ARIZONA@WORK, Community Bridges, and DES benefits through the Maricopa regional continuum of care.",
            description_es="Central Arizona Shelter Services opera el mayor sistema de refugio de emergencia y realojamiento en el condado Maricopa, proporcionando refugio para adultos solteros y realojamiento rápido para adultos con antecedentes penales sin hogar en Phoenix.",
            address="230 S 12th Avenue",
            city="Phoenix",
            phone="602-256-6945",
            email="",
            website="https://www.cassaz.org",
            eligibility="Homeless single adults in Maricopa County; coordinated entry required for most placements; justice-involved adults welcome.",
            eligibility_es="Adultos solteros sin hogar en el condado Maricopa; entrada coordinada requerida; adultos con antecedentes penales bienvenidos.",
            notes="Call 602-256-6945; coordinated entry through Maricopa regional system; not walk-in housing assignment.",
            notes_es="Llame al 602-256-6945; entrada coordinada a través del sistema regional de Maricopa.",
            hours="Shelter 24/7; offices Monday–Friday",
            tags="phoenix|maricopa|housing|shelter|coordinated-entry|reentry",
            services="Emergency shelter|Coordinated entry|Rapid rehousing|Case management|Benefits navigation",
            county="Maricopa",
            served_counties="Maricopa",
            coverage="single",
            _source="https://www.cassaz.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Gospel Rescue Mission — Tucson",
            category="housing",
            region="Tucson / Pima County",
            description="Gospel Rescue Mission Tucson provides emergency shelter, addiction recovery, and workforce programs for homeless men and women in Pima County including justice-involved adults through faith-based life transformation programming. Graduates connect to Pima County One-Stop, CODAC, and Primavera housing partners. Faith-based shelter—not county probation.",
            description_es="Gospel Rescue Mission Tucson ofrece refugio de emergencia, recuperación de adicciones y programas laborales para hombres y mujeres sin hogar en el condado Pima incluidos adultos con antecedentes penales.",
            address="4550 S Palo Verde Road",
            city="Tucson",
            phone="520-740-1501",
            email="",
            website="https://grmtucson.com",
            eligibility="Homeless adults in Pima County; justice-involved participants in recovery and shelter programs.",
            eligibility_es="Adultos sin hogar en el condado Pima; participantes con antecedentes penales en programas de refugio.",
            notes="Call 520-740-1501 for intake; recovery and shelter campus on Palo Verde Road.",
            notes_es="Llame al 520-740-1501 para admisión.",
            hours="Shelter 24/7",
            tags="tucson|pima|housing|shelter|recovery|reentry",
            services="Emergency shelter|Addiction recovery|Workforce programs|Life skills|Faith-based support",
            county="Pima",
            served_counties="Pima",
            coverage="single",
            _source="https://grmtucson.com",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="MANA House — Veterans Transitional Housing",
            category="veterans",
            region="Phoenix / Maricopa County",
            description="MANA House provides transitional housing and peer support for homeless and justice-involved veterans in Maricopa County through U.S. VETS and community partners, connecting residents to VA benefits, ARIZONA@WORK veteran staff, and permanent housing. Veteran-focused housing—not a general population emergency shelter.",
            description_es="MANA House ofrece vivienda transicional y apoyo entre pares para veteranos sin hogar y con antecedentes penales en el condado Maricopa, conectando residentes con beneficios VA y vivienda permanente.",
            address="755 E Willetta Street",
            city="Phoenix",
            phone="602-263-5531",
            email="",
            website="https://www.usvetsinc.org",
            eligibility="Homeless veterans in Maricopa County; justice-involved veterans per program policy; DD-214 or veteran status required.",
            eligibility_es="Veteranos sin hogar en el condado Maricopa; veteranos con antecedentes penales según política; se requiere DD-214 o estatus de veterano.",
            notes="Call 602-263-5531; coordinated with Arizona DVS county veterans service officers.",
            notes_es="Llame al 602-263-5531; coordinado con oficiales de servicios para veteranos del condado DVS.",
            hours="Residential 24/7; office Monday–Friday",
            tags="phoenix|maricopa|veterans|housing|transitional|reentry",
            services="Veteran transitional housing|Peer support|VA benefits navigation|Employment referrals|Permanent housing planning",
            county="Maricopa",
            served_counties="Maricopa",
            coverage="single",
            _source="https://www.usvetsinc.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Adelante Healthcare — Mesa",
            category="healthcare",
            region="Mesa / Maricopa County",
            description="Adelante Healthcare operates community health centers in Maricopa and Pinal counties with primary care, behavioral health, and dental services including sliding-fee care for uninsured justice-involved patients. The Mesa clinic coordinates AHCCCS enrollment with DES and referrals from Community Bridges and ADCRR reentry staff.",
            description_es="Adelante Healthcare opera centros de salud comunitarios en los condados Maricopa y Pinal con atención primaria, salud conductual y dental incluyendo atención con tarifa móvil para pacientes con antecedentes penales sin seguro.",
            address="1661 E Camelback Road",
            city="Mesa",
            phone="480-964-3922",
            email="",
            website="https://www.adelantehealthcare.com",
            eligibility="Uninsured and Medicaid patients in Maricopa County; sliding fee scale available.",
            eligibility_es="Pacientes sin seguro y Medicaid en el condado Maricopa; escala de tarifa móvil disponible.",
            notes="Call 480-964-3922; multiple east valley locations; enroll at healthearizonaplus.gov.",
            notes_es="Llame al 480-964-3922; múltiples ubicaciones del este del valle.",
            hours="Clinic Monday–Friday",
            tags="mesa|maricopa|healthcare|FQHC|dental|reentry",
            services="Primary care|Behavioral health|Dental services|Sliding-fee care|AHCCCS enrollment support",
            county="Maricopa",
            served_counties="Maricopa|Pinal",
            coverage="multi",
            _source="https://www.adelantehealthcare.com",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Chiricahua Community Health Centers — Sierra Vista",
            category="healthcare",
            region="Sierra Vista / Cochise County",
            description="Chiricahua Community Health Centers provide Federally Qualified Health Center primary care, behavioral health, and pharmacy services for Cochise County residents including justice-involved adults returning from ADCRR and county jail with sliding-fee and AHCCCS acceptance.",
            description_es="Chiricahua Community Health Centers ofrecen atención primaria FQHC, salud conductual y farmacia para residentes del condado Cochise incluidos adultos con antecedentes penales con tarifa móvil y aceptación AHCCCS.",
            address="10566 N Highway 90",
            city="Sierra Vista",
            phone="520-459-7790",
            email="",
            website="https://www.cchci.org",
            eligibility="Cochise County patients; AHCCCS and sliding fee; justice-involved patients welcome.",
            eligibility_es="Pacientes del condado Cochise; AHCCCS y tarifa móvil; pacientes con antecedentes penales bienvenidos.",
            notes="Call 520-459-7790; multiple Cochise County clinics; pairs with ARIZONA@WORK Cochise.",
            notes_es="Llame al 520-459-7790; múltiples clínicas del condado Cochise.",
            hours="Clinic Monday–Friday",
            tags="sierra-vista|cochise|healthcare|FQHC|rural|reentry",
            services="Primary care|Behavioral health|Pharmacy|Sliding-fee care|Rural health services",
            county="Cochise",
            served_counties="Cochise",
            coverage="single",
            _source="https://www.cchci.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Community Medical Services — Phoenix MAT",
            category="substance-use-treatment",
            region="Phoenix / Maricopa County",
            description="Community Medical Services operates opioid treatment programs with medication-assisted treatment at multiple Maricopa County clinics for justice-involved adults referred from drug courts, ADCRR, and Community Bridges. AHCCCS and cash-pay options support daily dosing and counseling.",
            description_es="Community Medical Services opera programas de tratamiento de opioides con tratamiento asistido con medicamentos en múltiples clínicas del condado Maricopa para adultos con antecedentes penales referidos por tribunales de drogas y ADCRR.",
            address="2301 W Northern Avenue",
            city="Phoenix",
            phone="602-866-1475",
            email="",
            website="https://communitymedicalservices.org",
            eligibility="Adults with opioid use disorder in Maricopa County; AHCCCS accepted; justice-involved referrals welcome.",
            eligibility_es="Adultos con trastorno por uso de opioides en el condado Maricopa; AHCCCS aceptado; referencias con antecedentes penales bienvenidas.",
            notes="Call 602-866-1475 for intake; daily dosing hours early morning; pairs with Maricopa drug courts.",
            notes_es="Llame al 602-866-1475 para admisión; horas de dosificación diaria temprano en la mañana.",
            hours="Dosing early morning daily; counseling by appointment",
            tags="phoenix|maricopa|substance-use-treatment|MAT|OTP|reentry",
            services="Medication-assisted treatment|Opioid treatment program|Counseling|Drug court referrals|AHCCCS billing",
            county="Maricopa",
            served_counties="Maricopa",
            coverage="single",
            _source="https://communitymedicalservices.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Banner Behavioral Health — Phoenix",
            category="substance-use-treatment",
            region="Phoenix / Maricopa County",
            description="Banner Behavioral Health provides inpatient and outpatient psychiatric and substance use treatment for Maricopa County adults including justice-involved patients through AHCCCS and commercial insurance at the Banner University Medical Center behavioral health campus.",
            description_es="Banner Behavioral Health ofrece tratamiento psiquiátrico y de uso de sustancias hospitalario y ambulatorio para adultos del condado Maricopa incluidos pacientes con antecedentes penales a través de AHCCCS.",
            address="925 E McDowell Road",
            city="Phoenix",
            phone="602-839-2000",
            email="",
            website="https://www.bannerhealth.com",
            eligibility="Adults with behavioral health or SUD needs; AHCCCS and insurance; crisis and scheduled admissions.",
            eligibility_es="Adultos con necesidades de salud conductual o TUS; AHCCCS y seguro; admisiones de crisis y programadas.",
            notes="Call 602-839-2000; crisis assessment available; coordinate with Mercy Care RBHA.",
            notes_es="Llame al 602-839-2000; evaluación de crisis disponible.",
            hours="Crisis 24/7; outpatient Monday–Friday",
            tags="phoenix|maricopa|substance-use-treatment|mental-health|inpatient|reentry",
            services="Inpatient psychiatric care|Outpatient SUD treatment|Crisis assessment|Dual diagnosis treatment|Discharge planning",
            county="Maricopa",
            served_counties="Maricopa",
            coverage="single",
            _source="https://www.bannerhealth.com",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Spectrum Healthcare — Prescott",
            category="substance-use-treatment",
            region="Prescott / Yavapai County",
            description="Spectrum Healthcare provides integrated mental health and substance use disorder treatment for Yavapai County residents including justice-involved adults through outpatient, crisis, and peer support programs contracted with AHCCCS RBHA.",
            description_es="Spectrum Healthcare ofrece tratamiento integrado de salud mental y trastornos por uso de sustancias para residentes del condado Yavapai incluidos adultos con antecedentes penales.",
            address="8 E Cottonwood Street",
            city="Prescott",
            phone="928-445-5211",
            email="",
            website="https://www.spectrumhealthcare-group.com",
            eligibility="Yavapai County adults with mental health or SUD needs; AHCCCS accepted.",
            eligibility_es="Adultos del condado Yavapai con necesidades de salud mental o TUS; AHCCCS aceptado.",
            notes="Call 928-445-5211; crisis line available; pairs with West Yavapai Guidance Clinic referrals.",
            notes_es="Llame al 928-445-5211; línea de crisis disponible.",
            hours="Crisis 24/7; clinics Monday–Friday",
            tags="prescott|yavapai|substance-use-treatment|mental-health|reentry",
            services="Outpatient treatment|Crisis services|Peer support|Integrated care|Court referrals",
            county="Yavapai",
            served_counties="Yavapai",
            coverage="single",
            _source="https://www.spectrumhealthcare-group.com",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Southern Arizona Legal Aid — Tucson",
            category="legal-aid",
            region="Tucson / Pima County",
            description="Southern Arizona Legal Aid provides free civil legal assistance to low-income residents of Pima, Santa Cruz, Cochise, and surrounding counties including housing, benefits, and limited record relief for justice-involved clients—not criminal defense.",
            description_es="Southern Arizona Legal Aid brinda asistencia legal civil gratuita a residentes de bajos ingresos de Pima, Santa Cruz, Cochise y condados circundantes incluyendo vivienda, beneficios y alivio limitado de antecedentes.",
            address="64 E Broadway Boulevard",
            city="Tucson",
            phone="520-623-9465",
            email="",
            website="https://www.sazlegalaid.org",
            eligibility="Low-income residents of SALA service counties with civil legal problems; LSC income limits apply.",
            eligibility_es="Residentes de bajos ingresos de condados de servicio SALA con problemas legales civiles; aplican límites LSC.",
            notes="Apply at sazlegalaid.org or call 520-623-9465; intake Monday–Friday.",
            notes_es="Solicite en sazlegalaid.org o llame al 520-623-9465.",
            hours="Intake Monday–Friday",
            tags="tucson|pima|legal-aid|low-income|reentry",
            services="Civil legal representation|Housing legal aid|Benefits advocacy|Limited record relief|Eviction defense",
            county="Pima",
            served_counties="Pima|Santa Cruz|Cochise|Greenlee|Graham",
            coverage="multi",
            _source="https://www.sazlegalaid.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Volunteer Lawyers Program — Maricopa County",
            category="legal-aid",
            region="Phoenix / Maricopa County",
            description="The Maricopa County Volunteer Lawyers Program connects low-income residents to pro bono attorneys for civil matters including family law, housing, and consumer issues through the Maricopa County Bar Foundation—not criminal defense or full-scope CLS replacement.",
            description_es="El Programa de Abogados Voluntarios del condado Maricopa conecta a residentes de bajos ingresos con abogados pro bono para asuntos civiles incluyendo derecho familiar, vivienda y asuntos de consumo.",
            address="303 E Palm Lane",
            city="Phoenix",
            phone="602-506-4444",
            email="",
            website="https://www.maricopavlp.org",
            eligibility="Low-income Maricopa County residents with civil legal needs meeting VLP criteria.",
            eligibility_es="Residentes de bajos ingresos del condado Maricopa con necesidades legales civiles que cumplan criterios VLP.",
            notes="Apply at maricopavlp.org or call 602-506-4444; pairs with CLS for overlapping services.",
            notes_es="Solicite en maricopavlp.org o llame al 602-506-4444.",
            hours="Intake Monday–Friday",
            tags="phoenix|maricopa|legal-aid|pro-bono|reentry",
            services="Pro bono civil referrals|Family law assistance|Housing legal help|Consumer law|Clinic events",
            county="Maricopa",
            served_counties="Maricopa",
            coverage="single",
            _source="https://www.maricopavlp.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Arizona Recovery Coalition",
            category="peer-support",
            region="Phoenix / Maricopa County",
            description="The Arizona Recovery Coalition advocates for recovery-oriented systems and provides peer support training and warm-line connections for justice-involved individuals in recovery across Maricopa County and statewide behavioral health networks.",
            description_es="La Coalición de Recuperación de Arizona aboga por sistemas orientados a la recuperación y ofrece capacitación de apoyo entre pares y conexiones de línea de apoyo para personas con antecedentes penales en recuperación.",
            address="5025 N Central Avenue",
            city="Phoenix",
            phone="602-279-0404",
            email="",
            website="https://www.arizonarecoverycoalition.org",
            eligibility="Individuals in recovery and peer support professionals; justice-involved peers welcome.",
            eligibility_es="Individuos en recuperación y profesionales de apoyo entre pares; pares con antecedentes penales bienvenidos.",
            notes="Call 602-279-0404; peer training schedules on website; pairs with Community Bridges.",
            notes_es="Llame al 602-279-0404; calendarios de capacitación en el sitio web.",
            hours="Monday–Friday business hours",
            tags="phoenix|maricopa|peer-support|recovery|advocacy|reentry",
            services="Peer support training|Recovery advocacy|Warm-line connections|Systems navigation|Justice-involved peer networks",
            county="Maricopa",
            served_counties="",
            coverage="statewide",
            _source="https://www.arizonarecoverycoalition.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Recovery Empowerment Network — Phoenix",
            category="peer-support",
            region="Phoenix / Maricopa County",
            description="Recovery Empowerment Network provides peer-operated wellness centers, recovery coaching, and drop-in support for adults with mental health and substance use challenges in Maricopa County including justice-involved members building community after release.",
            description_es="Recovery Empowerment Network ofrece centros de bienestar operados por pares, coaching de recuperación y apoyo sin cita para adultos con desafíos de salud mental y uso de sustancias en el condado Maricopa incluidos miembros con antecedentes penales.",
            address="5025 N Central Avenue",
            city="Phoenix",
            phone="602-650-1212",
            email="",
            website="https://www.recoveryempowerment.org",
            eligibility="Adults with mental health or SUD recovery goals in Maricopa County; justice-involved peers welcome.",
            eligibility_es="Adultos con metas de recuperación de salud mental o TUS en el condado Maricopa; pares con antecedentes penales bienvenidos.",
            notes="Call 602-650-1212; drop-in wellness center hours on website.",
            notes_es="Llame al 602-650-1212; horas del centro de bienestar en el sitio web.",
            hours="Drop-in center Monday–Saturday",
            tags="phoenix|maricopa|peer-support|recovery|wellness|reentry",
            services="Peer-operated wellness center|Recovery coaching|Drop-in support|Community building|RBHA coordination",
            county="Maricopa",
            served_counties="Maricopa",
            coverage="single",
            _source="https://www.recoveryempowerment.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="ARIZONA@WORK — Phoenix Metro",
            category="employment",
            region="Phoenix / Maricopa County",
            description="The ARIZONA@WORK Phoenix Metro center on Van Buren Street connects central Phoenix job seekers including justice-involved adults to WIOA training, career fairs, and fair-chance employer partnerships through the Maricopa County workforce board.",
            description_es="El centro ARIZONA@WORK Phoenix Metro en Van Buren Street conecta buscadores de empleo del centro de Phoenix incluidos adultos con antecedentes penales con capacitación WIOA y alianzas de empleo de segunda oportunidad.",
            address="3406 N 51st Avenue",
            city="Phoenix",
            phone="602-372-4200",
            email="",
            website="https://arizonaatwork.com",
            eligibility="Maricopa County job seekers; justice-involved individuals; core services free.",
            eligibility_es="Buscadores de empleo del condado Maricopa; personas con antecedentes penales; servicios básicos gratuitos.",
            notes="Register at arizonaatwork.com; call 602-372-4200.",
            notes_es="Regístrese en arizonaatwork.com; llame al 602-372-4200.",
            hours="Monday–Friday business hours",
            tags="phoenix|maricopa|employment|arizona-at-work|WIOA|reentry",
            services="Career coaching|WIOA referrals|Job fairs|Fair-chance employers|Resume workshops",
            county="Maricopa",
            served_counties="Maricopa",
            coverage="single",
            _source="https://arizonaatwork.com",
            _source_type="government",
            _confidence="high",
        )

    add(
            name="ARIZONA@WORK — Flagstaff",
            category="employment",
            region="Flagstaff / Coconino County",
            description="ARIZONA@WORK Flagstaff connects Coconino County job seekers including justice-involved adults from northern Arizona correctional releases to career coaching, WIOA referrals, and rural fair-chance employment navigation.",
            description_es="ARIZONA@WORK Flagstaff conecta buscadores de empleo del condado Coconino incluidos adultos con antecedentes penales con coaching de carrera y referencias WIOA.",
            address="201 E Birch Avenue",
            city="Flagstaff",
            phone="928-213-4750",
            email="",
            website="https://arizonaatwork.com",
            eligibility="Coconino County job seekers including justice-involved individuals; core services free.",
            eligibility_es="Buscadores de empleo del condado Coconino incluidas personas con antecedentes penales.",
            notes="Register at arizonaatwork.com; call 928-213-4750; pairs with North Country HealthCare.",
            notes_es="Regístrese en arizonaatwork.com; llame al 928-213-4750.",
            hours="Monday–Friday business hours",
            tags="flagstaff|coconino|employment|arizona-at-work|WIOA|reentry",
            services="Career coaching|WIOA referrals|Rural job search|Fair-chance employment|Resume assistance",
            county="Coconino",
            served_counties="Coconino",
            coverage="single",
            _source="https://arizonaatwork.com",
            _source_type="government",
            _confidence="high",
        )

    add(
            name="ARIZONA@WORK — Yuma",
            category="employment",
            region="Yuma / Yuma County",
            description="ARIZONA@WORK Yuma connects Yuma County job seekers including justice-involved adults to career coaching, agricultural and logistics employer networks, and WIOA training through the regional workforce board.",
            description_es="ARIZONA@WORK Yuma conecta buscadores de empleo del condado Yuma incluidos adultos con antecedentes penales con coaching de carrera y capacitación WIOA.",
            address="1350 W 8th Street",
            city="Yuma",
            phone="928-783-2222",
            email="",
            website="https://arizonaatwork.com",
            eligibility="Yuma County job seekers; justice-involved individuals welcome; core services free.",
            eligibility_es="Buscadores de empleo del condado Yuma; personas con antecedentes penales bienvenidas.",
            notes="Register at arizonaatwork.com; call 928-783-2222; pairs with Crossroads Mission.",
            notes_es="Regístrese en arizonaatwork.com; llame al 928-783-2222.",
            hours="Monday–Friday business hours",
            tags="yuma|employment|arizona-at-work|WIOA|reentry",
            services="Career coaching|WIOA referrals|Employer networking|Fair-chance employment|Bilingual services",
            county="Yuma",
            served_counties="Yuma",
            coverage="single",
            _source="https://arizonaatwork.com",
            _source_type="government",
            _confidence="high",
        )

    add(
            name="ID Theft Resource — Arizona Attorney General",
            category="id-documentation",
            region="Phoenix / Maricopa County",
            description="The Arizona Attorney General Identity Theft Resource Unit helps victims—including justice-involved individuals whose identity was compromised—restore credit, dispute fraudulent records, and obtain guidance on replacing identification documents needed for MVD and DES applications.",
            description_es="La Unidad de Recursos contra Robo de Identidad del Fiscal General de Arizona ayuda a víctimas—incluidas personas con antecedentes penales cuya identidad fue comprometida—a restaurar crédito y obtener orientación para reemplazar documentos de identificación.",
            address="2005 N Central Avenue",
            city="Phoenix",
            phone="602-542-5763",
            email="",
            website="https://www.azag.gov/identity-theft",
            eligibility="Arizona identity theft victims; free consumer assistance regardless of criminal record.",
            eligibility_es="Víctimas de robo de identidad en Arizona; asistencia gratuita al consumidor sin importar antecedentes penales.",
            notes="File complaint at azag.gov; call 602-542-5763; pairs with MVD and ADHS vital records.",
            notes_es="Presente queja en azag.gov; llame al 602-542-5763.",
            hours="Monday–Friday business hours",
            tags="phoenix|maricopa|id-documentation|identity-theft|consumer|reentry",
            services="Identity theft recovery|Credit dispute guidance|Document replacement navigation|Fraud reporting|Consumer protection",
            county="Maricopa",
            served_counties="",
            coverage="statewide",
            _source="https://www.azag.gov/identity-theft",
            _source_type="government",
            _confidence="high",
        )

    add(
            name="Arizona Transformation Project",
            category="reentry-organizations",
            region="Phoenix / Maricopa County",
            description="The Arizona Transformation Project provides reentry mentoring, family reunification support, and community navigation for justice-involved men and women returning to Maricopa County through volunteer mentors and partnerships with St. Joseph the Worker and Community Bridges.",
            description_es="El Arizona Transformation Project ofrece mentoría de reinserción, apoyo de reunificación familiar y navegación comunitaria para hombres y mujeres con antecedentes penales que regresan al condado Maricopa.",
            address="424 S 2nd Avenue",
            city="Phoenix",
            phone="602-254-2220",
            email="",
            website="https://www.aztransformationproject.org",
            eligibility="Justice-involved adults returning to Maricopa County; mentor matching by application.",
            eligibility_es="Adultos con antecedentes penales que regresan al condado Maricopa; emparejamiento de mentores por solicitud.",
            notes="Apply at aztransformationproject.org; call 602-254-2220; volunteer mentor program.",
            notes_es="Solicite en aztransformationproject.org; llame al 602-254-2220.",
            hours="Monday–Friday business hours",
            tags="phoenix|maricopa|reentry|mentoring|family|reentry-organizations",
            services="Reentry mentoring|Family reunification|Community navigation|Volunteer support|Partner referrals",
            county="Maricopa",
            served_counties="Maricopa",
            coverage="single",
            _source="https://www.aztransformationproject.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Middle Ground Prison Reform",
            category="reentry-organizations",
            region="Phoenix / Maricopa County",
            description="Middle Ground Prison Reform advocates for fair correctional policies and connects Arizona families and returning citizens to reentry resources, visitation support, and policy education across Maricopa County and statewide—not direct cash or housing placement.",
            description_es="Middle Ground Prison Reform aboga por políticas correccionales justas y conecta a familias de Arizona y ciudadanos que regresan con recursos de reinserción y educación de políticas en todo el estado.",
            address="P.O. Box 12086",
            city="Phoenix",
            phone="602-258-0080",
            email="",
            website="https://www.middlegroundprisonreform.org",
            eligibility="Arizona families and returning citizens seeking policy information and reentry resource navigation.",
            eligibility_es="Familias de Arizona y ciudadanos que regresan que buscan información de políticas y navegación de recursos de reinserción.",
            notes="Call 602-258-0080; resource referrals by phone; advocacy organization not direct service provider.",
            notes_es="Llame al 602-258-0080; referencias de recursos por teléfono.",
            hours="Monday–Friday business hours",
            tags="phoenix|maricopa|reentry|advocacy|policy|statewide",
            services="Policy advocacy|Family support information|Reentry resource referrals|Visitation guidance|Correctional policy education",
            county="Maricopa",
            served_counties="",
            coverage="statewide",
            _source="https://www.middlegroundprisonreform.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Salvation Army — Phoenix Family Services",
            category="basic-needs",
            region="Phoenix / Maricopa County",
            description="The Salvation Army Phoenix Family Services provides emergency rent and utility assistance, food boxes, and case management for low-income Maricopa County families including returning citizens stabilizing after release.",
            description_es="Salvation Army Phoenix Family Services ofrece asistencia de emergencia de renta y servicios públicos, cajas de alimentos y manejo de casos para familias de bajos ingresos del condado Maricopa incluidos ciudadanos que regresan.",
            address="2707 E Van Buren Street",
            city="Phoenix",
            phone="602-267-4122",
            email="",
            website="https://www.salvationarmyphoenix.org",
            eligibility="Low-income Maricopa County families meeting emergency assistance criteria; justice-involved households per program policy.",
            eligibility_es="Familias de bajos ingresos del condado Maricopa que cumplan criterios; hogares con antecedentes penales según política.",
            notes="Call 602-267-4122; appointment required for financial assistance.",
            notes_es="Llame al 602-267-4122; cita requerida para asistencia financiera.",
            hours="Monday–Friday business hours",
            tags="phoenix|maricopa|basic-needs|emergency-assistance|reentry",
            services="Rent assistance|Utility assistance|Food boxes|Case management|Benefits referrals",
            county="Maricopa",
            served_counties="Maricopa",
            coverage="single",
            _source="https://www.salvationarmyphoenix.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Nogales Community Development — Food Bank",
            category="food-nutrition",
            region="Nogales / Santa Cruz County",
            description="Nogales Community Development food bank and emergency services support low-income Santa Cruz County families including justice-involved households on the Arizona-Mexico border with food distribution and DES benefits referrals.",
            description_es="El banco de alimentos de Nogales Community Development apoya a familias de bajos ingresos del condado Santa Cruz incluidos hogares con antecedentes penales con distribución de alimentos y referencias de beneficios DES.",
            address="190 N Apache Boulevard",
            city="Nogales",
            phone="520-287-2046",
            email="",
            website="https://www.ncdaz.org",
            eligibility="Low-income Santa Cruz County residents; bilingual services; justice-involved families welcome.",
            eligibility_es="Residentes de bajos ingresos del condado Santa Cruz; servicios bilingües; familias con antecedentes penales bienvenidas.",
            notes="Call 520-287-2046; food distribution schedules on website; pairs with ARIZONA@WORK Nogales.",
            notes_es="Llame al 520-287-2046; horarios de distribución en el sitio web.",
            hours="Food distribution hours vary",
            tags="nogales|santa-cruz|food-nutrition|bilingual|border|reentry",
            services="Emergency food|Basic needs assistance|Benefits referrals|Bilingual services|Border community support",
            county="Santa Cruz",
            served_counties="Santa Cruz",
            coverage="single",
            _source="https://www.ncdaz.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Gila County Health & Emergency Management — Public Health",
            category="healthcare",
            region="Globe / Gila County",
            description="Gila County Health Department connects rural Gila County residents including justice-involved adults to public health services, immunizations, and referrals to Copper Basin Medical Center and ARIZONA@WORK Globe for care and employment after release.",
            description_es="El Departamento de Salud del condado Gila conecta a residentes rurales incluidos adultos con antecedentes penales con servicios de salud pública, inmunizaciones y referencias a Copper Basin Medical Center y ARIZONA@WORK Globe.",
            address="5515 S Apache Avenue",
            city="Globe",
            phone="928-402-8811",
            email="",
            website="https://www.gilacountyaz.gov",
            eligibility="Gila County residents; public health services; referrals to regional providers.",
            eligibility_es="Residentes del condado Gila; servicios de salud pública; referencias a proveedores regionales.",
            notes="Call 928-402-8811; rural health navigation; pairs with Gila County DES.",
            notes_es="Llame al 928-402-8811; navegación de salud rural.",
            hours="Monday–Friday business hours",
            tags="globe|gila|healthcare|rural|public-health|reentry",
            services="Public health services|Immunizations|Health referrals|Rural navigation|Emergency preparedness info",
            county="Gila",
            served_counties="Gila",
            coverage="single",
            _source="https://www.gilacountyaz.gov",
            _source_type="government",
            _confidence="high",
        )

    add(
            name="SEABHS — Safford Behavioral Health",
            category="substance-use-treatment",
            region="Safford / Graham County",
            description="Southeastern Arizona Behavioral Health Services provides outpatient mental health and substance use treatment for Graham and Greenlee county residents including justice-involved adults through AHCCCS and sliding-fee programs.",
            description_es="Southeastern Arizona Behavioral Health Services ofrece tratamiento ambulatorio de salud mental y uso de sustancias para residentes de los condados Graham y Greenlee incluidos adultos con antecedentes penales.",
            address="1615 S 1st Avenue",
            city="Safford",
            phone="928-428-0560",
            email="",
            website="https://www.seabhs.org",
            eligibility="Graham and Greenlee County adults with behavioral health needs; AHCCCS accepted.",
            eligibility_es="Adultos de los condados Graham y Greenlee con necesidades de salud conductual; AHCCCS aceptado.",
            notes="Call 928-428-0560 for intake; rural eastern Arizona coverage.",
            notes_es="Llame al 928-428-0560 para admisión.",
            hours="Clinic Monday–Friday",
            tags="safford|graham|substance-use-treatment|mental-health|rural|reentry",
            services="Outpatient SUD treatment|Mental health services|Sliding-fee care|Rural behavioral health|Court referrals",
            county="Graham",
            served_counties="Graham|Greenlee",
            coverage="multi",
            _source="https://www.seabhs.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Native Health — Phoenix",
            category="healthcare",
            region="Phoenix / Maricopa County",
            description="Native Health provides culturally competent primary care, behavioral health, and wellness programs for Native and non-Native families in Maricopa County including justice-involved adults through sliding-fee and AHCCCS services at the Phoenix clinic.",
            description_es="Native Health ofrece atención primaria culturalmente competente, salud conductual y programas de bienestar para familias nativas y no nativas en el condado Maricopa incluidos adultos con antecedentes penales.",
            address="4041 N Central Avenue",
            city="Phoenix",
            phone="602-279-5262",
            email="",
            website="https://www.nativehealth.org",
            eligibility="Maricopa County patients; AHCCCS and sliding fee; open to all community members.",
            eligibility_es="Pacientes del condado Maricopa; AHCCCS y tarifa móvil; abierto a todos los miembros de la comunidad.",
            notes="Call 602-279-5262; multiple Phoenix locations.",
            notes_es="Llame al 602-279-5262; múltiples ubicaciones en Phoenix.",
            hours="Clinic Monday–Friday",
            tags="phoenix|maricopa|healthcare|native|behavioral-health|reentry",
            services="Primary care|Behavioral health|Wellness programs|Sliding-fee care|Culturally competent care",
            county="Maricopa",
            served_counties="Maricopa",
            coverage="single",
            _source="https://www.nativehealth.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="La Paz Regional Hospital — Parker",
            category="healthcare",
            region="Parker / La Paz County",
            description="La Paz Regional Hospital serves La Paz County with emergency, inpatient, and outpatient care and financial assistance for uninsured patients including justice-involved adults returning to the Colorado River communities.",
            description_es="La Paz Regional Hospital sirve al condado La Paz con atención de emergencia, hospitalaria y ambulatoria y asistencia financiera para pacientes sin seguro incluidos adultos con antecedentes penales.",
            address="1200 W Mohave Road",
            city="Parker",
            phone="928-669-2211",
            email="",
            website="https://www.lapazhospital.org",
            eligibility="La Paz County patients; financial assistance available; AHCCCS accepted.",
            eligibility_es="Pacientes del condado La Paz; asistencia financiera disponible; AHCCCS aceptado.",
            notes="Call 928-669-2211; emergency 24/7.",
            notes_es="Llame al 928-669-2211; emergencias 24/7.",
            hours="Emergency 24/7",
            tags="parker|la-paz|healthcare|hospital|rural|reentry",
            services="Emergency care|Inpatient services|Outpatient clinics|Financial assistance|Discharge planning",
            county="La Paz",
            served_counties="La Paz",
            coverage="single",
            _source="https://www.lapazhospital.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Hope Lives — Peer Recovery Center",
            category="peer-support",
            region="Prescott / Yavapai County",
            description="Hope Lives operates a peer recovery community center in Prescott offering drop-in support, recovery meetings, and navigation to Spectrum Healthcare and West Yavapai Guidance Clinic for justice-involved members in Yavapai County.",
            description_es="Hope Lives opera un centro comunitario de recuperación entre pares en Prescott ofreciendo apoyo sin cita y navegación a Spectrum Healthcare para miembros con antecedentes penales en el condado Yavapai.",
            address="800 W Gurley Street",
            city="Prescott",
            phone="928-515-1038",
            email="",
            website="https://www.hopelivesaz.org",
            eligibility="Adults in recovery in Yavapai County; justice-involved peers welcome.",
            eligibility_es="Adultos en recuperación en el condado Yavapai; pares con antecedentes penales bienvenidos.",
            notes="Call 928-515-1038; drop-in hours on website.",
            notes_es="Llame al 928-515-1038; horas sin cita en el sitio web.",
            hours="Drop-in center hours vary",
            tags="prescott|yavapai|peer-support|recovery|reentry",
            services="Peer recovery center|Drop-in support|Recovery meetings|Treatment navigation|Community building",
            county="Yavapai",
            served_counties="Yavapai",
            coverage="single",
            _source="https://www.hopelivesaz.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Navajo County Public Health Services District",
            category="healthcare",
            region="Holbrook / Navajo County",
            description="Navajo County Public Health Services District connects rural Navajo, Apache, and northern Gila county residents including justice-involved adults to public health programs, immunizations, and referrals to North Country HealthCare and regional providers.",
            description_es="El Distrito de Servicios de Salud Pública del condado Navajo conecta a residentes rurales incluidos adultos con antecedentes penales con programas de salud pública e inmunizaciones y referencias a North Country HealthCare.",
            address="117 E Buffalo Street",
            city="Holbrook",
            phone="928-524-4750",
            email="",
            website="https://www.navajocountyaz.gov",
            eligibility="Navajo County residents; public health programs; rural health navigation.",
            eligibility_es="Residentes del condado Navajo; programas de salud pública; navegación de salud rural.",
            notes="Call 928-524-4750; pairs with ARIZONA@WORK Holbrook and Navajo County DES.",
            notes_es="Llame al 928-524-4750; se vincula con ARIZONA@WORK Holbrook.",
            hours="Monday–Friday business hours",
            tags="holbrook|navajo|healthcare|public-health|rural|reentry",
            services="Public health programs|Immunizations|Health education|Rural referrals|Emergency preparedness",
            county="Navajo",
            served_counties="Navajo",
            coverage="single",
            _source="https://www.navajocountyaz.gov",
            _source_type="government",
            _confidence="high",
        )

    add(
            name="Pinal County Public Health — Casa Grande",
            category="healthcare",
            region="Casa Grande / Pinal County",
            description="Pinal County Public Health connects residents including justice-involved adults to immunizations, WIC, and referrals to regional FQHC clinics and ARIZONA@WORK Pinal for health and employment services in central Arizona.",
            description_es="Salud Pública del condado Pinal conecta a residentes incluidos adultos con antecedentes penales con inmunizaciones, WIC y referencias a clínicas FQHC regionales y ARIZONA@WORK Pinal.",
            address="1000 N Arizola Road",
            city="Casa Grande",
            phone="520-836-3566",
            email="",
            website="https://www.pinalcountyaz.gov",
            eligibility="Pinal County residents; public health and WIC services.",
            eligibility_es="Residentes del condado Pinal; servicios de salud pública y WIC.",
            notes="Call 520-836-3566; pairs with Adelante Healthcare Pinal and DES Casa Grande.",
            notes_es="Llame al 520-836-3566.",
            hours="Monday–Friday business hours",
            tags="casa-grande|pinal|healthcare|public-health|WIC|reentry",
            services="Immunizations|WIC|Public health referrals|Health education|Regional provider navigation",
            county="Pinal",
            served_counties="Pinal",
            coverage="single",
            _source="https://www.pinalcountyaz.gov",
            _source_type="government",
            _confidence="high",
        )

    add(
            name="U.S. VETS — Prescott",
            category="veterans",
            region="Prescott / Yavapai County",
            description="U.S. VETS Prescott provides transitional housing, case management, and employment support for homeless veterans in Yavapai County including justice-involved veterans through VA benefits coordination and ARIZONA@WORK referrals.",
            description_es="U.S. VETS Prescott ofrece vivienda transicional, manejo de casos y apoyo de empleo para veteranos sin hogar en el condado Yavapai incluidos veteranos con antecedentes penales.",
            address="1040 Whipple Street",
            city="Prescott",
            phone="928-583-1304",
            email="",
            website="https://www.usvetsinc.org",
            eligibility="Homeless veterans in Yavapai County; DD-214 or veteran status required.",
            eligibility_es="Veteranos sin hogar en el condado Yavapai; se requiere DD-214 o estatus de veterano.",
            notes="Call 928-583-1304; coordinate with Yavapai County CVSO.",
            notes_es="Llame al 928-583-1304; coordine con CVSO del condado Yavapai.",
            hours="Residential 24/7; office Monday–Friday",
            tags="prescott|yavapai|veterans|housing|transitional|reentry",
            services="Veteran transitional housing|Case management|VA benefits navigation|Employment support|Permanent housing planning",
            county="Yavapai",
            served_counties="Yavapai",
            coverage="single",
            _source="https://www.usvetsinc.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Goodwill of Southern Arizona — Tucson",
            category="employment",
            region="Tucson / Pima County",
            description="Goodwill of Southern Arizona connects Pima County job seekers including fair-chance hires to career centers, thrift social enterprise jobs, and digital skills training through the Tucson career hub.",
            description_es="Goodwill del Sur de Arizona conecta buscadores de empleo del condado Pima incluidas contrataciones de segunda oportunidad con centros de carrera y capacitación en habilidades digitales.",
            address="1940 E Broadway Boulevard",
            city="Tucson",
            phone="520-623-5174",
            email="",
            website="https://www.goodwillsouthernaz.org",
            eligibility="Pima County job seekers including justice-involved individuals.",
            eligibility_es="Buscadores de empleo del condado Pima incluidas personas con antecedentes penales.",
            notes="Call 520-623-5174; career center on Broadway; register at arizonaatwork.com.",
            notes_es="Llame al 520-623-5174; centro de carrera en Broadway.",
            hours="Career center Monday–Friday",
            tags="tucson|pima|employment|goodwill|fair-chance|reentry",
            services="Career coaching|Social enterprise jobs|Digital skills|Employer connections|WIOA referrals",
            county="Pima",
            served_counties="Pima",
            coverage="single",
            _source="https://www.goodwillsouthernaz.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="AWEE — Tucson Career Center",
            category="employment",
            region="Tucson / Pima County",
            description="AWEE's Tucson career center provides employment training and job placement for Pima County adults including justice-involved participants through specialized reentry employment tracks and DES referrals.",
            description_es="El centro de carrera AWEE de Tucson ofrece capacitación laboral y colocación de empleo para adultos del condado Pima incluidos participantes con antecedentes penales a través de rutas especializadas de empleo de reinserción.",
            address="320 N Commerce Park Loop",
            city="Tucson",
            phone="520-622-4900",
            email="",
            website="https://www.awee.org",
            eligibility="Pima County adults seeking employment; justice-involved tracks available.",
            eligibility_es="Adultos del condado Pima que buscan empleo; rutas para personas con antecedentes penales disponibles.",
            notes="Call 520-622-4900; near Pima County One-Stop.",
            notes_es="Llame al 520-622-4900; cerca del One-Stop del condado Pima.",
            hours="Monday–Friday business hours",
            tags="tucson|pima|employment|women|fair-chance|reentry",
            services="Career training|Job placement|Justice-involved employment track|Interview preparation|DES coordination",
            county="Pima",
            served_counties="Pima",
            coverage="single",
            _source="https://www.awee.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="St. Vincent de Paul — Phoenix",
            category="basic-needs",
            region="Phoenix / Maricopa County",
            description="Society of St. Vincent de Paul Phoenix provides food boxes, rent and utility assistance, and furniture for low-income Maricopa County families including returning citizens through parish-based caseworker visits and the main dining room.",
            description_es="La Sociedad de San Vicente de Paul Phoenix ofrece cajas de alimentos, asistencia de renta y servicios públicos y muebles para familias de bajos ingresos del condado Maricopa incluidos ciudadanos que regresan.",
            address="420 W Watkins Road",
            city="Phoenix",
            phone="602-261-6886",
            email="",
            website="https://www.stvincentdepaul.net",
            eligibility="Low-income Maricopa County households; home visits by caseworkers; justice-involved families per policy.",
            eligibility_es="Hogares de bajos ingresos del condado Maricopa; visitas domiciliarias; familias con antecedentes penales según política.",
            notes="Call 602-261-6886; dining room meals daily; financial assistance by caseworker referral.",
            notes_es="Llame al 602-261-6886; comidas diarias en comedor.",
            hours="Dining room daily; office Monday–Friday",
            tags="phoenix|maricopa|basic-needs|food|rent-assistance|reentry",
            services="Food boxes|Rent assistance|Utility assistance|Furniture|Dining room meals",
            county="Maricopa",
            served_counties="Maricopa",
            coverage="single",
            _source="https://www.stvincentdepaul.net",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Copper Basin Medical Center — Globe",
            category="healthcare",
            region="Globe / Gila County",
            description="Copper Basin Medical Center is Gila County's community hospital providing emergency, inpatient, and outpatient care with financial assistance for uninsured patients including justice-involved adults returning to rural central Arizona.",
            description_es="Copper Basin Medical Center es el hospital comunitario del condado Gila que ofrece atención de emergencia, hospitalaria y ambulatoria con asistencia financiera para pacientes sin seguro incluidos adultos con antecedentes penales.",
            address="5880 S Hospital Drive",
            city="Globe",
            phone="928-425-3261",
            email="",
            website="https://www.copperbasinmedical.com",
            eligibility="Gila County patients; financial assistance available; AHCCCS accepted.",
            eligibility_es="Pacientes del condado Gila; asistencia financiera disponible; AHCCCS aceptado.",
            notes="Call 928-425-3261; emergency 24/7; pairs with Gila County DES and ARIZONA@WORK Globe.",
            notes_es="Llame al 928-425-3261; emergencias 24/7.",
            hours="Emergency 24/7",
            tags="globe|gila|healthcare|hospital|rural|reentry",
            services="Emergency care|Inpatient services|Outpatient clinics|Financial assistance|Discharge planning",
            county="Gila",
            served_counties="Gila",
            coverage="single",
            _source="https://www.copperbasinmedical.com",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Little Colorado Medical Center — Winslow",
            category="healthcare",
            region="Winslow / Navajo County",
            description="Little Colorado Medical Center serves Navajo County with emergency and outpatient care and financial counseling for uninsured and justice-involved patients in the Winslow and Holbrook region of northeastern Arizona.",
            description_es="Little Colorado Medical Center sirve al condado Navajo con atención de emergencia y ambulatoria y consejería financiera para pacientes sin seguro y con antecedentes penales en la región de Winslow y Holbrook.",
            address="1501 N Williamson Avenue",
            city="Winslow",
            phone="928-289-4691",
            email="",
            website="https://www.lcmcaz.org",
            eligibility="Navajo County patients; financial assistance available.",
            eligibility_es="Pacientes del condado Navajo; asistencia financiera disponible.",
            notes="Call 928-289-4691; emergency 24/7; pairs with North Country HealthCare and ARIZONA@WORK Holbrook.",
            notes_es="Llame al 928-289-4691; emergencias 24/7.",
            hours="Emergency 24/7",
            tags="winslow|navajo|healthcare|hospital|rural|reentry",
            services="Emergency care|Outpatient services|Financial counseling|Rural health services|Discharge planning",
            county="Navajo",
            served_counties="Navajo",
            coverage="single",
            _source="https://www.lcmcaz.org",
            _source_type="nonprofit",
            _confidence="high",
        )
