"""Direct-service pins for Arizona counties that need local depth beyond DES rows."""


def register_thin_counties(add):
    """Two or more program-level rows per thin rural county."""

    # --- Apache ---
    add(
        name="Arizona at Work — White Mountains",
        category="employment", region="Show Low / Apache County",
        description="Arizona at Work White Mountains connects job seekers in Apache and Navajo counties—including justice-involved adults from ADCRR release and county jail—to resume coaching, WIOA training referrals, and fair-chance employer navigation through the statewide ARIZONA@WORK network. Staff link returning citizens to North Country HealthCare, DES benefits, and local reentry partners in the White Mountains region. Free core career services—not emergency cash or housing placement.",
        description_es="Arizona at Work White Mountains conecta buscadores de empleo en los condados Apache y Navajo—incluidos adultos con antecedentes penales liberados de ADCRR y cárceles del condado—con coaching de currículum, referencias de capacitación WIOA y navegación de empleo de segunda oportunidad. Servicios básicos de carrera gratuitos.",
        address="1500 S. White Mountain Road", city="Show Low", phone="928-537-4333", email="",
        website="https://arizonaatwork.com",
        eligibility="Open to Apache County job seekers including justice-involved individuals; core ARIZONA@WORK services are free.",
        eligibility_es="Abierto a buscadores de empleo del condado Apache incluidas personas con antecedentes penales; servicios básicos gratuitos.",
        notes="Register at arizonaatwork.com; call 928-537-4333; pairs with Apache County DES and North Country HealthCare Show Low.",
        notes_es="Regístrese en arizonaatwork.com; llame al 928-537-4333; se vincula con DES del condado Apache y North Country HealthCare Show Low.",
        hours="Monday–Friday business hours; call ahead in rural counties",
        tags="apache|show-low|employment|arizona-at-work|WIOA|reentry|fair-chance",
        services="Job search assistance|Resume preparation|WIOA training referrals|Fair-chance employment|Career coaching",
        county="Apache", served_counties="Apache", coverage="single",
        _source="https://arizonaatwork.com", _source_type="government", _confidence="high",
    )
    add(
        name="North Country HealthCare — Show Low",
        category="healthcare", region="Show Low / Apache County",
        description="North Country HealthCare's Show Low clinic provides Federally Qualified Health Center primary care, behavioral health, dental services, and sliding-fee care for uninsured and Medicaid patients in Apache County including returning citizens establishing a medical home after release from ADCRR custody or county jail. FQHC services coordinate with DES Medicaid enrollment and Arizona at Work employment partners.",
        description_es="La clínica Show Low de North Country HealthCare ofrece atención primaria FQHC, salud conductual, servicios dentales y atención con tarifa móvil para pacientes sin seguro y Medicaid en el condado Apache incluidos ciudadanos que regresan que establecen un hogar médico después de la liberación.",
        address="5171 Cub Lake Road", city="Show Low", phone="928-532-6069", email="",
        website="https://northcountryhealthcare.org",
        eligibility="Apache County residents of all ages; sliding scale with proof of income; AHCCCS Medicaid and Medicare accepted.",
        eligibility_es="Residentes del condado Apache de todas las edades; escala móvil con prueba de ingresos; se aceptan Medicaid AHCCCS y Medicare.",
        notes="Call 928-532-6069 for appointments; multiple northern Arizona locations; same-day sick visits at select sites.",
        notes_es="Llame al 928-532-6069 para citas; múltiples ubicaciones del norte de Arizona.",
        hours="Monday–Friday clinic hours; varies by location",
        tags="apache|show-low|healthcare|FQHC|primary-care|reentry",
        services="Primary care|Behavioral health|Dental care|Sliding-fee services|Pharmacy assistance",
        county="Apache", served_counties="Apache|Navajo", coverage="multi",
        _source="https://northcountryhealthcare.org", _source_type="nonprofit", _confidence="high",
    )

    # --- Cochise ---
    add(
        name="Arizona at Work — Cochise County",
        category="employment", region="Sierra Vista / Cochise County",
        description="Arizona at Work Cochise County connects job seekers including justice-involved adults from ADCRR release and Cochise County Detention Center to resume coaching, WIOA training referrals, and fair-chance employment navigation in Sierra Vista and Bisbee. Staff coordinate with Chiricahua Community Health Centers, DES benefits, and southeastern Arizona reentry partners. Free core career services—not emergency housing.",
        description_es="Arizona at Work del condado Cochise conecta buscadores de empleo incluidos adultos con antecedentes penales con coaching de currículum, referencias WIOA y navegación de empleo de segunda oportunidad en Sierra Vista y Bisbee.",
        address="3401 E. Nebraska Street", city="Sierra Vista", phone="520-458-9308", email="",
        website="https://arizonaatwork.com",
        eligibility="Open to Cochise County job seekers including justice-involved individuals; core services free.",
        eligibility_es="Abierto a buscadores de empleo del condado Cochise incluidas personas con antecedentes penales; servicios básicos gratuitos.",
        notes="Register at arizonaatwork.com; call 520-458-9308; pairs with Cochise County DES and Chiricahua Community Health Centers.",
        notes_es="Regístrese en arizonaatwork.com; llame al 520-458-9308; se vincula con DES del condado Cochise.",
        hours="Monday–Friday business hours",
        tags="cochise|sierra-vista|employment|arizona-at-work|WIOA|reentry",
        services="Job search assistance|Resume coaching|WIOA referrals|Fair-chance employment|Career workshops",
        county="Cochise", served_counties="Cochise", coverage="single",
        _source="https://arizonaatwork.com", _source_type="government", _confidence="high",
    )
    add(
        name="Chiricahua Community Health Centers",
        category="healthcare", region="Douglas / Cochise County",
        description="Chiricahua Community Health Centers operate Federally Qualified Health Center clinics across Cochise County providing primary care, behavioral health, dental services, and sliding-fee care for uninsured and AHCCCS Medicaid patients including justice-involved adults reestablishing healthcare after release from Cochise County Detention Center or ADCRR custody.",
        description_es="Chiricahua Community Health Centers opera clínicas FQHC en el condado Cochise que ofrecen atención primaria, salud conductual, servicios dentales y atención con tarifa móvil para pacientes sin seguro y Medicaid AHCCCS incluidos adultos con antecedentes penales.",
        address="10566 N. Highway 191", city="Douglas", phone="520-364-3287", email="",
        website="https://chiricahuacommunityhealth.org",
        eligibility="Cochise County residents of all ages; sliding scale with proof of income; AHCCCS Medicaid accepted.",
        eligibility_es="Residentes del condado Cochise de todas las edades; escala móvil con prueba de ingresos; se acepta Medicaid AHCCCS.",
        notes="Call 520-364-3287 for nearest clinic; locations in Douglas, Bisbee, Sierra Vista, and Willcox.",
        notes_es="Llame al 520-364-3287 para la clínica más cercana; ubicaciones en Douglas, Bisbee, Sierra Vista y Willcox.",
        hours="Monday–Friday clinic hours; varies by location",
        tags="cochise|douglas|healthcare|FQHC|primary-care|reentry",
        services="Primary care|Behavioral health|Dental care|Sliding-fee services|Pharmacy assistance",
        county="Cochise", served_counties="Cochise", coverage="single",
        _source="https://chiricahuacommunityhealth.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Cochise County Adult Probation",
        category="probation-parole", region="Bisbee / Cochise County",
        description="Cochise County Adult Probation supervises probationers in southeastern Arizona, connecting justice-involved adults to local Arizona at Work centers, Chiricahua Community Health Centers, and DES benefits partners as conditions of community supervision. Assigned probation officers handle compliance reporting and referrals—not emergency housing or SNAP intake.",
        description_es="Probatoria para Adultos del condado Cochise supervisa a personas en probatoria en el sureste de Arizona, conectando adultos con antecedentes penales con centros Arizona at Work locales y aliados de salud. Los oficiales de probatoria asignados manejan reportes de cumplimiento y referencias.",
        address="100 Quality Hill Road", city="Bisbee", phone="520-432-8600", email="",
        website="https://www.cochise.az.gov/probation",
        eligibility="Adults under Cochise County probation supervision; report to assigned officer.",
        eligibility_es="Adultos bajo supervisión probatoria del condado Cochise; reporte al oficial asignado.",
        notes="Call 520-432-8600 for office location; ask your officer about Arizona at Work and healthcare referrals.",
        notes_es="Llame al 520-432-8600; pregunte a su oficial sobre referencias de empleo y salud.",
        hours="Monday–Friday business hours",
        tags="cochise|bisbee|probation-parole|community-supervision|reentry",
        services="Probation supervision|Community reporting|Treatment referrals|Employment partner coordination|Reentry navigation",
        county="Cochise", served_counties="Cochise", coverage="single",
        _source="https://www.cochise.az.gov/probation", _source_type="government", _confidence="high",
    )

    # --- Graham ---
    add(
        name="Arizona at Work — Graham County",
        category="employment", region="Safford / Graham County",
        description="Arizona at Work Graham County connects job seekers including justice-involved adults from ADCRR release and Graham County Jail to resume coaching, WIOA training referrals, and fair-chance employment navigation in Safford and the Gila Valley. Staff link returning citizens to Southeast Arizona Behavioral Health Services, DES benefits, and rural reentry partners.",
        description_es="Arizona at Work del condado Graham conecta buscadores de empleo incluidos adultos con antecedentes penales con coaching de currículum y referencias WIOA en Safford y el valle de Gila.",
        address="817 W. 8th Street", city="Safford", phone="928-428-6333", email="",
        website="https://arizonaatwork.com",
        eligibility="Open to Graham County job seekers including justice-involved individuals; core services free.",
        eligibility_es="Abierto a buscadores de empleo del condado Graham incluidas personas con antecedentes penales.",
        notes="Register at arizonaatwork.com; call 928-428-6333; pairs with Graham County DES.",
        notes_es="Regístrese en arizonaatwork.com; llame al 928-428-6333.",
        hours="Monday–Friday business hours",
        tags="graham|safford|employment|arizona-at-work|WIOA|reentry",
        services="Job search assistance|Resume coaching|WIOA referrals|Fair-chance employment|Career workshops",
        county="Graham", served_counties="Graham", coverage="single",
        _source="https://arizonaatwork.com", _source_type="government", _confidence="high",
    )
    add(
        name="Southeast Arizona Behavioral Health Services (SEABHS)",
        category="substance-use-treatment", region="Safford / Graham County",
        description="Southeast Arizona Behavioral Health Services provides outpatient mental health and substance use treatment, crisis intervention, and case management for Graham and Greenlee county residents including justice-involved adults referred by probation and drug courts. SEABHS accepts AHCCCS Medicaid and offers sliding-fee care for uninsured clients reestablishing treatment after release.",
        description_es="Southeast Arizona Behavioral Health Services ofrece tratamiento ambulatorio de salud mental y uso de sustancias, intervención en crisis y manejo de casos para residentes de los condados Graham y Greenlee incluidos adultos con antecedentes penales referidos por probatoria y tribunales de drogas.",
        address="611 S. 11th Avenue", city="Safford", phone="928-348-4400", email="",
        website="https://www.seabhs.org",
        eligibility="Graham and Greenlee county residents seeking mental health or substance use services; AHCCCS Medicaid and sliding-fee accepted.",
        eligibility_es="Residentes de los condados Graham y Greenlee que buscan servicios de salud mental o uso de sustancias; se aceptan Medicaid AHCCCS y tarifa móvil.",
        notes="Call 928-348-4400 for intake; crisis line available; pairs with Graham County probation.",
        notes_es="Llame al 928-348-4400 para admisión; línea de crisis disponible.",
        hours="Monday–Friday clinic hours; crisis services vary",
        tags="graham|safford|substance-use-treatment|mental-health|SEABHS|reentry",
        services="Outpatient mental health|Substance use treatment|Crisis intervention|Case management|Probation referrals",
        county="Graham", served_counties="Graham|Greenlee", coverage="multi",
        _source="https://www.seabhs.org", _source_type="nonprofit", _confidence="high",
    )

    # --- Greenlee ---
    add(
        name="Arizona at Work — Greenlee County",
        category="employment", region="Clifton / Greenlee County",
        description="Arizona at Work Greenlee County connects job seekers in Arizona's smallest county—including justice-involved adults from ADCRR release—to resume coaching, WIOA training referrals, and fair-chance employment navigation in Clifton and Morenci. Staff coordinate with SEABHS, DES benefits, and southeastern Arizona workforce partners.",
        description_es="Arizona at Work del condado Greenlee conecta buscadores de empleo en el condado más pequeño de Arizona—incluidos adultos con antecedentes penales—con coaching de currículum y referencias WIOA en Clifton y Morenci.",
        address="615 N. Coronado Boulevard", city="Clifton", phone="928-865-4700", email="",
        website="https://arizonaatwork.com",
        eligibility="Open to Greenlee County job seekers including justice-involved individuals; core services free.",
        eligibility_es="Abierto a buscadores de empleo del condado Greenlee incluidas personas con antecedentes penales.",
        notes="Register at arizonaatwork.com; call 928-865-4700; pairs with Greenlee County DES and SEABHS Safford.",
        notes_es="Regístrese en arizonaatwork.com; llame al 928-865-4700.",
        hours="Monday–Friday business hours; call ahead",
        tags="greenlee|clifton|employment|arizona-at-work|WIOA|reentry",
        services="Job search assistance|Resume coaching|WIOA referrals|Fair-chance employment|Career coaching",
        county="Greenlee", served_counties="Greenlee", coverage="single",
        _source="https://arizonaatwork.com", _source_type="government", _confidence="high",
    )
    add(
        name="Greenlee County Community Food Bank",
        category="food-nutrition", region="Clifton / Greenlee County",
        description="Greenlee County Community Food Bank distributes emergency food boxes and partners with St. Mary's Food Bank Alliance to serve food-insecure residents in Clifton, Duncan, and Morenci including returning citizens reestablishing food security after release from ADCRR custody or county jail. Pantry services require referral or income screening—not a walk-in benefits office.",
        description_es="Greenlee County Community Food Bank distribuye cajas de alimentos de emergencia y se asocia con St. Mary's Food Bank Alliance para servir a residentes con inseguridad alimentaria en Clifton, Duncan y Morenci incluidos ciudadanos que regresan.",
        address="506 Coronado Boulevard", city="Clifton", phone="928-865-4505", email="",
        website="https://www.greenlee.az.gov",
        eligibility="Food-insecure Greenlee County residents; income screening may apply; justice-involved clients welcome.",
        eligibility_es="Residentes del condado Greenlee con inseguridad alimentaria; puede aplicar evaluación de ingresos; clientes con antecedentes penales bienvenidos.",
        notes="Call 928-865-4505 for distribution schedule; pairs with DES Greenlee and Arizona at Work Clifton.",
        notes_es="Llame al 928-865-4505 para horario de distribución.",
        hours="Distribution hours vary; call ahead",
        tags="greenlee|clifton|food-nutrition|food-bank|basic-needs|reentry",
        services="Emergency food boxes|Food pantry distribution|St. Mary's Food Bank partnership|Referral navigation",
        county="Greenlee", served_counties="Greenlee", coverage="single",
        _source="https://www.greenlee.az.gov", _source_type="government", _confidence="high",
    )

    # --- La Paz ---
    add(
        name="Arizona at Work — La Paz County",
        category="employment", region="Parker / La Paz County",
        description="Arizona at Work La Paz County connects job seekers including justice-involved adults from ADCRR release and La Paz County Jail to resume coaching, WIOA training referrals, and fair-chance employment navigation in Parker and Quartzsite along the Colorado River. Staff coordinate with La Paz Regional Hospital, DES benefits, and western Arizona reentry partners.",
        description_es="Arizona at Work del condado La Paz conecta buscadores de empleo incluidos adultos con antecedentes penales con coaching de currículum y referencias WIOA en Parker y Quartzsite a lo largo del río Colorado.",
        address="1200 S. California Avenue", city="Parker", phone="928-669-9810", email="",
        website="https://arizonaatwork.com",
        eligibility="Open to La Paz County job seekers including justice-involved individuals; core services free.",
        eligibility_es="Abierto a buscadores de empleo del condado La Paz incluidas personas con antecedentes penales.",
        notes="Register at arizonaatwork.com; call 928-669-9810; pairs with La Paz County DES.",
        notes_es="Regístrese en arizonaatwork.com; llame al 928-669-9810.",
        hours="Monday–Friday business hours",
        tags="la-paz|parker|employment|arizona-at-work|WIOA|reentry",
        services="Job search assistance|Resume coaching|WIOA referrals|Fair-chance employment|Career workshops",
        county="La Paz", served_counties="La Paz", coverage="single",
        _source="https://arizonaatwork.com", _source_type="government", _confidence="high",
    )
    add(
        name="La Paz Regional Hospital",
        category="healthcare", region="Parker / La Paz County",
        description="La Paz Regional Hospital provides primary care, emergency services, and community health outreach for La Paz County residents including uninsured and AHCCCS Medicaid patients such as returning citizens establishing local medical care after release from ADCRR custody or county jail. Direct clinical services—not a walk-in benefits or probation office.",
        description_es="La Paz Regional Hospital brinda atención primaria, servicios de emergencia y alcance de salud comunitaria para residentes del condado La Paz incluidos pacientes sin seguro y Medicaid AHCCCS como ciudadanos que regresan.",
        address="1200 W. Mohave Road", city="Parker", phone="928-669-9201", email="",
        website="https://www.lapazhospital.org",
        eligibility="Open to La Paz County residents; AHCCCS Medicaid and sliding-fee patients welcome including justice-involved adults.",
        eligibility_es="Abierto a residentes del condado La Paz; pacientes Medicaid AHCCCS y tarifa móvil bienvenidos.",
        notes="Call 928-669-9201 for appointments; emergency department 24/7; pairs with Arizona at Work Parker.",
        notes_es="Llame al 928-669-9201 para citas; departamento de emergencias 24/7.",
        hours="Emergency 24/7; clinic hours vary",
        tags="la-paz|parker|healthcare|rural|reentry",
        services="Primary care|Emergency services|Community health outreach|Sliding-fee care|Specialist referrals",
        county="La Paz", served_counties="La Paz", coverage="single",
        _source="https://www.lapazhospital.org", _source_type="nonprofit", _confidence="high",
    )

    # --- Navajo ---
    add(
        name="Arizona at Work — Navajo County",
        category="employment", region="Holbrook / Navajo County",
        description="Arizona at Work Navajo County connects job seekers including justice-involved adults from ADCRR release and Navajo County Jail to resume coaching, WIOA training referrals, and fair-chance employment navigation in Holbrook, Show Low, and Winslow. Staff link returning citizens to North Country HealthCare, DES benefits, and northeastern Arizona reentry partners.",
        description_es="Arizona at Work del condado Navajo conecta buscadores de empleo incluidos adultos con antecedentes penales con coaching de currículum y referencias WIOA en Holbrook, Show Low y Winslow.",
        address="103 W. Hopi Drive", city="Holbrook", phone="928-524-4770", email="",
        website="https://arizonaatwork.com",
        eligibility="Open to Navajo County job seekers including justice-involved individuals; core services free.",
        eligibility_es="Abierto a buscadores de empleo del condado Navajo incluidas personas con antecedentes penales.",
        notes="Register at arizonaatwork.com; call 928-524-4770; pairs with Navajo County DES.",
        notes_es="Regístrese en arizonaatwork.com; llame al 928-524-4770.",
        hours="Monday–Friday business hours",
        tags="navajo|holbrook|employment|arizona-at-work|WIOA|reentry",
        services="Job search assistance|Resume coaching|WIOA referrals|Fair-chance employment|Career workshops",
        county="Navajo", served_counties="Navajo", coverage="single",
        _source="https://arizonaatwork.com", _source_type="government", _confidence="high",
    )
    add(
        name="Navajo County Adult Probation",
        category="probation-parole", region="Holbrook / Navajo County",
        description="Navajo County Adult Probation supervises probationers across northeastern Arizona, connecting justice-involved adults to Arizona at Work centers, North Country HealthCare, and DES benefits partners as conditions of community supervision. Assigned officers handle compliance reporting and referrals—not emergency housing or SNAP intake.",
        description_es="Probatoria para Adultos del condado Navajo supervisa a personas en probatoria en el noreste de Arizona, conectando adultos con antecedentes penales con centros Arizona at Work y aliados de salud.",
        address="100 E. Code Talkers Drive", city="Holbrook", phone="928-524-4000", email="",
        website="https://www.navajocountyaz.gov/Probation",
        eligibility="Adults under Navajo County probation supervision; report to assigned officer.",
        eligibility_es="Adultos bajo supervisión probatoria del condado Navajo; reporte al oficial asignado.",
        notes="Call 928-524-4000 for office information; ask your officer about workforce and healthcare referrals.",
        notes_es="Llame al 928-524-4000; pregunte a su oficial sobre referencias laborales y de salud.",
        hours="Monday–Friday business hours",
        tags="navajo|holbrook|probation-parole|community-supervision|reentry",
        services="Probation supervision|Community reporting|Treatment referrals|Employment partner coordination|Reentry navigation",
        county="Navajo", served_counties="Navajo", coverage="single",
        _source="https://www.navajocountyaz.gov/Probation", _source_type="government", _confidence="high",
    )

    # --- Santa Cruz ---
    add(
        name="Arizona at Work — Santa Cruz County",
        category="employment", region="Nogales / Santa Cruz County",
        description="Arizona at Work Santa Cruz County connects job seekers including justice-involved adults from ADCRR release and Santa Cruz County Jail to resume coaching, WIOA training referrals, and fair-chance employment navigation in Nogales and Rio Rico along the U.S.–Mexico border. Bilingual staff coordinate with Mariposa Community Health Center, DES benefits, and border-region reentry partners.",
        description_es="Arizona at Work del condado Santa Cruz conecta buscadores de empleo incluidos adultos con antecedentes penales con coaching de currículum y referencias WIOA en Nogales y Rio Rico en la frontera. Personal bilingüe coordina con Mariposa Community Health Center y beneficios DES.",
        address="856 N. Morley Avenue", city="Nogales", phone="520-287-4646", email="",
        website="https://arizonaatwork.com",
        eligibility="Open to Santa Cruz County job seekers including justice-involved individuals; core services free.",
        eligibility_es="Abierto a buscadores de empleo del condado Santa Cruz incluidas personas con antecedentes penales.",
        notes="Register at arizonaatwork.com; call 520-287-4646; bilingual services available.",
        notes_es="Regístrese en arizonaatwork.com; llame al 520-287-4646; servicios bilingües disponibles.",
        hours="Monday–Friday business hours",
        tags="santa-cruz|nogales|employment|arizona-at-work|WIOA|reentry|bilingual",
        services="Job search assistance|Resume coaching|WIOA referrals|Fair-chance employment|Bilingual career services",
        county="Santa Cruz", served_counties="Santa Cruz", coverage="single",
        _source="https://arizonaatwork.com", _source_type="government", _confidence="high",
    )
    add(
        name="Mariposa Community Health Center — Nogales",
        category="healthcare", region="Nogales / Santa Cruz County",
        description="Mariposa Community Health Center operates Federally Qualified Health Center clinics in Nogales and Rio Rico providing primary care, behavioral health, dental services, and sliding-fee care for uninsured and AHCCCS Medicaid patients including justice-involved adults reestablishing healthcare after release from Santa Cruz County Jail or ADCRR custody. Bilingual staff serve border-region families.",
        description_es="Mariposa Community Health Center opera clínicas FQHC en Nogales y Rio Rico que ofrecen atención primaria, salud conductual, servicios dentales y atención con tarifa móvil para pacientes sin seguro y Medicaid AHCCCS incluidos adultos con antecedentes penales. Personal bilingüe sirve a familias de la región fronteriza.",
        address="1852 N. Mastick Way", city="Nogales", phone="520-281-1555", email="",
        website="https://www.mariposachc.net",
        eligibility="Santa Cruz County residents of all ages; sliding scale with proof of income; AHCCCS Medicaid accepted.",
        eligibility_es="Residentes del condado Santa Cruz de todas las edades; escala móvil con prueba de ingresos; se acepta Medicaid AHCCCS.",
        notes="Call 520-281-1555 for appointments; multiple Nogales-area locations; bilingual services.",
        notes_es="Llame al 520-281-1555 para citas; múltiples ubicaciones en el área de Nogales; servicios bilingües.",
        hours="Monday–Friday clinic hours; varies by location",
        tags="santa-cruz|nogales|healthcare|FQHC|primary-care|reentry|bilingual",
        services="Primary care|Behavioral health|Dental care|Sliding-fee services|Bilingual patient navigation",
        county="Santa Cruz", served_counties="Santa Cruz", coverage="single",
        _source="https://www.mariposachc.net", _source_type="nonprofit", _confidence="high",
    )

    # --- Gila ---
    add(
        name="Arizona at Work — Gila County",
        category="employment", region="Globe / Gila County",
        description="Arizona at Work Gila County connects job seekers including justice-involved adults from ADCRR release and Gila County Jail to resume coaching, WIOA training referrals, and fair-chance employment navigation in Globe, Payson, and the Tonto Basin region. Staff coordinate with Cobre Valley Regional Medical Center, DES benefits, and central Arizona reentry partners.",
        description_es="Arizona at Work del condado Gila conecta buscadores de empleo incluidos adultos con antecedentes penales con coaching de currículum y referencias WIOA en Globe, Payson y la región de Tonto Basin.",
        address="605 S. Central Avenue", city="Globe", phone="928-425-7632", email="",
        website="https://arizonaatwork.com",
        eligibility="Open to Gila County job seekers including justice-involved individuals; core services free.",
        eligibility_es="Abierto a buscadores de empleo del condado Gila incluidas personas con antecedentes penales.",
        notes="Register at arizonaatwork.com; call 928-425-7632; pairs with Gila County DES.",
        notes_es="Regístrese en arizonaatwork.com; llame al 928-425-7632.",
        hours="Monday–Friday business hours",
        tags="gila|globe|employment|arizona-at-work|WIOA|reentry",
        services="Job search assistance|Resume coaching|WIOA referrals|Fair-chance employment|Career workshops",
        county="Gila", served_counties="Gila", coverage="single",
        _source="https://arizonaatwork.com", _source_type="government", _confidence="high",
    )
    add(
        name="Cobre Valley Regional Medical Center",
        category="healthcare", region="Globe / Gila County",
        description="Cobre Valley Regional Medical Center provides primary care, emergency services, and community health outreach for Gila County residents including uninsured and AHCCCS Medicaid patients such as returning citizens establishing local medical care after release from Gila County Jail or ADCRR custody. Direct clinical services—not a walk-in benefits office.",
        description_es="Cobre Valley Regional Medical Center brinda atención primaria, servicios de emergencia y alcance de salud comunitaria para residentes del condado Gila incluidos pacientes sin seguro y Medicaid AHCCCS como ciudadanos que regresan.",
        address="5880 S. Hospital Drive", city="Globe", phone="928-402-1122", email="",
        website="https://www.cobrevvalley.org",
        eligibility="Open to Gila County residents; AHCCCS Medicaid and sliding-fee patients welcome including justice-involved adults.",
        eligibility_es="Abierto a residentes del condado Gila; pacientes Medicaid AHCCCS y tarifa móvil bienvenidos.",
        notes="Call 928-402-1122 for appointments; emergency department 24/7; pairs with Arizona at Work Globe.",
        notes_es="Llame al 928-402-1122 para citas; departamento de emergencias 24/7.",
        hours="Emergency 24/7; clinic hours vary",
        tags="gila|globe|healthcare|rural|reentry",
        services="Primary care|Emergency services|Community health outreach|Sliding-fee care|Specialist referrals",
        county="Gila", served_counties="Gila", coverage="single",
        _source="https://www.cobrevvalley.org", _source_type="nonprofit", _confidence="high",
    )

    # --- Pinal ---
    add(
        name="Arizona at Work — Pinal County",
        category="employment", region="Casa Grande / Pinal County",
        description="Arizona at Work Pinal County connects job seekers including justice-involved adults from ADCRR release and Pinal County Jail to resume coaching, WIOA training referrals, and fair-chance employment navigation in Casa Grande, Florence, and Apache Junction. Staff coordinate with Desert Senita Community Health Center, DES benefits, and central Arizona reentry partners.",
        description_es="Arizona at Work del condado Pinal conecta buscadores de empleo incluidos adultos con antecedentes penales con coaching de currículum y referencias WIOA en Casa Grande, Florence y Apache Junction.",
        address="820 E. Cottonwood Lane", city="Casa Grande", phone="520-836-4627", email="",
        website="https://arizonaatwork.com",
        eligibility="Open to Pinal County job seekers including justice-involved individuals; core services free.",
        eligibility_es="Abierto a buscadores de empleo del condado Pinal incluidas personas con antecedentes penales.",
        notes="Register at arizonaatwork.com; call 520-836-4627; pairs with Pinal County DES.",
        notes_es="Regístrese en arizonaatwork.com; llame al 520-836-4627.",
        hours="Monday–Friday business hours",
        tags="pinal|casa-grande|employment|arizona-at-work|WIOA|reentry",
        services="Job search assistance|Resume coaching|WIOA referrals|Fair-chance employment|Career workshops",
        county="Pinal", served_counties="Pinal", coverage="single",
        _source="https://arizonaatwork.com", _source_type="government", _confidence="high",
    )
    add(
        name="Desert Senita Community Health Center",
        category="healthcare", region="Ajo / Pinal County",
        description="Desert Senita Community Health Center operates Federally Qualified Health Center clinics across western Pinal County providing primary care, behavioral health, dental services, and sliding-fee care for uninsured and AHCCCS Medicaid patients including justice-involved adults in Ajo, Casa Grande, and Maricopa. FQHC services support returning citizens establishing healthcare after release.",
        description_es="Desert Senita Community Health Center opera clínicas FQHC en el oeste del condado Pinal que ofrecen atención primaria, salud conductual, servicios dentales y atención con tarifa móvil para pacientes sin seguro y Medicaid AHCCCS incluidos adultos con antecedentes penales en Ajo, Casa Grande y Maricopa.",
        address="1051 W. Ajo Way", city="Ajo", phone="520-387-5651", email="",
        website="https://www.dschc.org",
        eligibility="Pinal County residents of all ages; sliding scale with proof of income; AHCCCS Medicaid accepted.",
        eligibility_es="Residentes del condado Pinal de todas las edades; escala móvil con prueba de ingresos; se acepta Medicaid AHCCCS.",
        notes="Call 520-387-5651 for nearest clinic; locations in Ajo, Casa Grande, and Maricopa.",
        notes_es="Llame al 520-387-5651 para la clínica más cercana; ubicaciones en Ajo, Casa Grande y Maricopa.",
        hours="Monday–Friday clinic hours; varies by location",
        tags="pinal|ajo|healthcare|FQHC|primary-care|reentry",
        services="Primary care|Behavioral health|Dental care|Sliding-fee services|Pharmacy assistance",
        county="Pinal", served_counties="Pinal", coverage="single",
        _source="https://www.dschc.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Pinal County Adult Probation",
        category="probation-parole", region="Florence / Pinal County",
        description="Pinal County Adult Probation supervises probationers across central Arizona including communities near ADCRR facilities in Florence and Eyman, connecting justice-involved adults to Arizona at Work centers, Desert Senita Community Health Center, and DES benefits partners. Assigned officers handle compliance reporting—not emergency housing or SNAP intake.",
        description_es="Probatoria para Adultos del condado Pinal supervisa a personas en probatoria en el centro de Arizona incluidas comunidades cerca de instalaciones de ADCRR en Florence y Eyman, conectando adultos con antecedentes penales con centros Arizona at Work y aliados de salud.",
        address="971 N. Jason Lopez Circle", city="Florence", phone="520-866-5300", email="",
        website="https://www.pinalcountyaz.gov/AdultProbation",
        eligibility="Adults under Pinal County probation supervision; report to assigned officer.",
        eligibility_es="Adultos bajo supervisión probatoria del condado Pinal; reporte al oficial asignado.",
        notes="Call 520-866-5300 for office information; ask your officer about workforce and healthcare referrals.",
        notes_es="Llame al 520-866-5300; pregunte a su oficial sobre referencias laborales y de salud.",
        hours="Monday–Friday business hours",
        tags="pinal|florence|probation-parole|community-supervision|reentry",
        services="Probation supervision|Community reporting|Treatment referrals|Employment partner coordination|Reentry navigation",
        county="Pinal", served_counties="Pinal", coverage="single",
        _source="https://www.pinalcountyaz.gov/AdultProbation", _source_type="government", _confidence="high",
    )
