"""Category minimum fill for Arizona reentry resources."""


def register_category_fill(add):
    add(
            name="ADCRR — Phoenix Community Corrections Field Office",
            category="probation-parole",
            region="Phoenix / Maricopa County",
            description="The ADCRR Phoenix Community Corrections field office supervises parolees and probationers in central Maricopa County, coordinating compliance reporting and referrals to St. Joseph the Worker, Community Bridges, and ARIZONA@WORK for justice-involved adults under state supervision.",
            description_es="La oficina de campo de Correcciones Comunitarias de ADCRR en Phoenix supervisa personas en libertad condicional y probatoria en el centro del condado Maricopa, coordinando informes de cumplimiento y referencias a aliados de reinserción.",
            address="1601 W Jefferson Street",
            city="Phoenix",
            phone="602-542-5535",
            email="",
            website="https://corrections.az.gov/adcr/community-corrections",
            eligibility="Adults under ADCRR parole or community supervision in Maricopa County; report to assigned officer.",
            eligibility_es="Adultos bajo libertad condicional o supervisión comunitaria de ADCRR en el condado Maricopa; reporte al oficial asignado.",
            notes="Call 602-542-5535; not a walk-in benefits or housing office; ask officer about local reentry referrals.",
            notes_es="Llame al 602-542-5535; no es oficina de beneficios o vivienda; pregunte al oficial sobre referencias locales.",
            hours="Monday–Friday business hours",
            tags="phoenix|maricopa|probation-parole|ADCRR|reentry",
            services="Parole supervision|Community corrections reporting|Treatment referrals|Employment coordination|Reentry partner linkage",
            county="Maricopa",
            served_counties="Maricopa",
            coverage="single",
            _source="https://corrections.az.gov/adcr/community-corrections",
            _source_type="government",
            _confidence="high",
        )

    add(
            name="ADCRR — Tucson Community Corrections Field Office",
            category="probation-parole",
            region="Tucson / Pima County",
            description="The ADCRR Tucson Community Corrections field office supervises parolees and probationers in Pima County, connecting supervisees to CODAC, Primavera, Pima County One-Stop, and El Rio Health as conditions of release.",
            description_es="La oficina de campo de Correcciones Comunitarias de ADCRR en Tucson supervisa personas en libertad condicional y probatoria en el condado Pima, conectando supervisados con CODAC, Primavera y Pima County One-Stop.",
            address="3434 E 22nd Street",
            city="Tucson",
            phone="520-514-3400",
            email="",
            website="https://corrections.az.gov/adcr/community-corrections",
            eligibility="Adults under ADCRR parole or community supervision in Pima County; report to assigned officer.",
            eligibility_es="Adultos bajo libertad condicional o supervisión comunitaria de ADCRR en el condado Pima; reporte al oficial asignado.",
            notes="Call 520-514-3400; coordinate through assigned officer for reentry referrals.",
            notes_es="Llame al 520-514-3400; coordine a través del oficial asignado.",
            hours="Monday–Friday business hours",
            tags="tucson|pima|probation-parole|ADCRR|reentry",
            services="Parole supervision|Community corrections reporting|Treatment referrals|Employment coordination|Reentry partner linkage",
            county="Pima",
            served_counties="Pima",
            coverage="single",
            _source="https://corrections.az.gov/adcr/community-corrections",
            _source_type="government",
            _confidence="high",
        )

    add(
            name="Maricopa County Adult Probation",
            category="probation-parole",
            region="Phoenix / Maricopa County",
            description="Maricopa County Adult Probation supervises county probationers through field offices across the Phoenix metro, connecting clients to local treatment, employment, and housing partners as court-ordered conditions—not a benefits or emergency shelter intake center.",
            description_es="La Probatoria de Adultos del condado Maricopa supervisa a personas en probatoria del condado a través de oficinas de campo en el metro Phoenix, conectando clientes con tratamiento, empleo y vivienda según órdenes judiciales.",
            address="702 W Madison Street",
            city="Phoenix",
            phone="602-372-0300",
            email="",
            website="https://www.maricopa.gov/Adult-Probation",
            eligibility="Adults under Maricopa County adult probation; report to assigned probation officer.",
            eligibility_es="Adultos bajo probatoria de adultos del condado Maricopa; reporte al oficial de probatoria asignado.",
            notes="Call 602-372-0300; find field office at maricopa.gov; distinct from ADCRR state parole.",
            notes_es="Llame al 602-372-0300; encuentre oficina de campo en maricopa.gov; distinto de libertad condicional estatal ADCRR.",
            hours="Field offices Monday–Friday",
            tags="phoenix|maricopa|probation-parole|county|reentry",
            services="County probation supervision|Court-ordered treatment referrals|Employment compliance|Community reporting|Local reentry coordination",
            county="Maricopa",
            served_counties="Maricopa",
            coverage="single",
            _source="https://www.maricopa.gov/Adult-Probation",
            _source_type="government",
            _confidence="high",
        )

    add(
            name="Pima County Adult Probation",
            category="probation-parole",
            region="Tucson / Pima County",
            description="Pima County Adult Probation supervises county probationers from the Tucson headquarters and regional field offices, coordinating referrals to CODAC, Primavera, and Southern Arizona Legal Aid for justice-involved adults under county court supervision.",
            description_es="La Probatoria de Adultos del condado Pima supervisa a personas en probatoria del condado desde la sede de Tucson, coordinando referencias a CODAC, Primavera y Southern Arizona Legal Aid.",
            address="240 N Stone Avenue",
            city="Tucson",
            phone="520-724-5500",
            email="",
            website="https://www.pima.gov/Adult-Probation",
            eligibility="Adults under Pima County adult probation; report to assigned probation officer.",
            eligibility_es="Adultos bajo probatoria de adultos del condado Pima; reporte al oficial de probatoria asignado.",
            notes="Call 520-724-5500; main office on Stone Avenue; distinct from ADCRR state parole.",
            notes_es="Llame al 520-724-5500; oficina principal en Stone Avenue.",
            hours="Monday–Friday business hours",
            tags="tucson|pima|probation-parole|county|reentry",
            services="County probation supervision|Court-ordered referrals|Treatment compliance|Employment reporting|Reentry partner coordination",
            county="Pima",
            served_counties="Pima",
            coverage="single",
            _source="https://www.pima.gov/Adult-Probation",
            _source_type="government",
            _confidence="high",
        )

    add(
            name="Maricopa Community Colleges — Adult Education",
            category="education",
            region="Phoenix / Maricopa County",
            description="Maricopa Community Colleges Adult Education provides free GED and High School Equivalency preparation, English language classes, and citizenship instruction at campuses across Maricopa County for returning citizens rebuilding credentials for ARIZONA@WORK and employer requirements.",
            description_es="Maricopa Community Colleges Educación para Adultos ofrece preparación GED y equivalencia de secundaria gratuita, clases de inglés e instrucción de ciudadanía en campus del condado Maricopa para ciudadanos que regresan que reconstruyen credenciales.",
            address="2411 W 14th Street",
            city="Tempe",
            phone="480-517-8540",
            email="",
            website="https://www.maricopa.edu/adult-education",
            eligibility="Maricopa County adults age 16+; free HSE classes; orientation required.",
            eligibility_es="Adultos del condado Maricopa de 16+ años; clases HSE gratuitas; se requiere orientación.",
            notes="Call 480-517-8540; classes at multiple MCCCD campuses; HSE test fees separate.",
            notes_es="Llame al 480-517-8540; clases en múltiples campus MCCCD.",
            hours="Class schedules vary by campus",
            tags="tempe|maricopa|education|GED|ESL|reentry",
            services="GED preparation|High School Equivalency|English language classes|Citizenship instruction|Career pathway referrals",
            county="Maricopa",
            served_counties="Maricopa",
            coverage="single",
            _source="https://www.maricopa.edu/adult-education",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Rio Salado College — Adult Basic Education",
            category="education",
            region="Phoenix / Maricopa County",
            description="Rio Salado College Adult Basic Education offers online and in-person GED preparation, adult high school diploma, and English language programs for Maricopa County adults including justice-involved learners through MCCCD with flexible scheduling.",
            description_es="Rio Salado College Educación Básica para Adultos ofrece preparación GED en línea y presencial, diploma de secundaria para adultos e inglés para adultos del condado Maricopa incluidos estudiantes con antecedentes penales.",
            address="2323 W 14th Street",
            city="Tempe",
            phone="480-517-8080",
            email="",
            website="https://www.riosalado.edu",
            eligibility="Maricopa County adults; free ABE classes; online and in-person options.",
            eligibility_es="Adultos del condado Maricopa; clases ABE gratuitas; opciones en línea y presenciales.",
            notes="Call 480-517-8080; online GED prep popular for working adults.",
            notes_es="Llame al 480-517-8080; preparación GED en línea popular para adultos trabajadores.",
            hours="Online 24/7; in-person by schedule",
            tags="tempe|maricopa|education|GED|online|reentry",
            services="GED preparation|Adult high school diploma|English language|Online learning|College transition",
            county="Maricopa",
            served_counties="Maricopa",
            coverage="single",
            _source="https://www.riosalado.edu",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Pima Community College — Adult Basic Education",
            category="education",
            region="Tucson / Pima County",
            description="Pima Community College Adult Basic Education provides free GED and High School Equivalency classes, English language instruction, and citizenship preparation for Pima County adults including returning citizens at the Desert Vista and downtown campuses.",
            description_es="Pima Community College Educación Básica para Adultos ofrece clases GED y equivalencia de secundaria gratuitas, instrucción de inglés y preparación de ciudadanía para adultos del condado Pima incluidos ciudadanos que regresan.",
            address="5901 S Calle Santa Cruz",
            city="Tucson",
            phone="520-206-7330",
            email="",
            website="https://www.pima.edu",
            eligibility="Pima County adults age 16+; free ABE and HSE classes; orientation required.",
            eligibility_es="Adultos del condado Pima de 16+ años; clases ABE y HSE gratuitas; se requiere orientación.",
            notes="Call 520-206-7330; Desert Vista campus main ABE site; HSE testing on campus.",
            notes_es="Llame al 520-206-7330; campus Desert Vista sitio principal ABE.",
            hours="Class schedules vary",
            tags="tucson|pima|education|GED|ESL|reentry",
            services="GED preparation|High School Equivalency|English language classes|Citizenship preparation|College transition",
            county="Pima",
            served_counties="Pima",
            coverage="single",
            _source="https://www.pima.edu",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Yavapai College — Adult Basic Education",
            category="education",
            region="Prescott / Yavapai County",
            description="Yavapai College Adult Basic Education offers free GED preparation and English language classes for Yavapai County adults including justice-involved residents at Prescott and Verde Valley campuses.",
            description_es="Yavapai College Educación Básica para Adultos ofrece preparación GED gratuita y clases de inglés para adultos del condado Yavapai incluidos residentes con antecedentes penales.",
            address="1100 E Sheldon Street",
            city="Prescott",
            phone="928-717-7756",
            email="",
            website="https://www.yc.edu",
            eligibility="Yavapai County adults; free HSE classes; orientation required.",
            eligibility_es="Adultos del condado Yavapai; clases HSE gratuitas; se requiere orientación.",
            notes="Call 928-717-7756; Prescott and Clarkdale campuses.",
            notes_es="Llame al 928-717-7756; campus Prescott y Clarkdale.",
            hours="Class schedules vary",
            tags="prescott|yavapai|education|GED|ESL|reentry",
            services="GED preparation|English language classes|Adult education|College transition|Workforce pathway referrals",
            county="Yavapai",
            served_counties="Yavapai",
            coverage="single",
            _source="https://www.yc.edu",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Maricopa County Veterans Service Office",
            category="veterans",
            region="Phoenix / Maricopa County",
            description="The Maricopa County Veterans Service Office helps veterans and families file VA disability claims, education benefits, and emergency assistance referrals through accredited benefits counselors at the downtown Phoenix office.",
            description_es="La Oficina de Servicios para Veteranos del condado Maricopa ayuda a veteranos y familias a presentar reclamos de discapacidad VA, beneficios educativos y referencias de asistencia de emergencia.",
            address="222 N Central Avenue",
            city="Phoenix",
            phone="602-506-7373",
            email="",
            website="https://www.maricopa.gov/veterans",
            eligibility="Maricopa County veterans and eligible family members; DD-214 or service records helpful.",
            eligibility_es="Veteranos del condado Maricopa y familiares elegibles; DD-214 o registros de servicio útiles.",
            notes="Call 602-506-7373; appointment recommended; pairs with MANA House and Arizona DVS.",
            notes_es="Llame al 602-506-7373; cita recomendada.",
            hours="Monday–Friday business hours",
            tags="phoenix|maricopa|veterans|CVSO|VA-benefits|reentry",
            services="VA disability claims|Education benefits counseling|Emergency assistance referrals|Benefits appeals help|DD-214 guidance",
            county="Maricopa",
            served_counties="Maricopa",
            coverage="single",
            _source="https://www.maricopa.gov/veterans",
            _source_type="government",
            _confidence="high",
        )

    add(
            name="Pima County Veterans Service Office",
            category="veterans",
            region="Tucson / Pima County",
            description="The Pima County Veterans Service Office provides accredited VA benefits counseling, disability claims assistance, and referrals to veteran housing and employment partners for justice-involved veterans in Tucson.",
            description_es="La Oficina de Servicios para Veteranos del condado Pima ofrece consejería acreditada de beneficios VA, asistencia con reclamos de discapacidad y referencias a aliados de vivienda y empleo para veteranos.",
            address="3550 N Oracle Road",
            city="Tucson",
            phone="520-724-8226",
            email="",
            website="https://www.pima.gov/veterans",
            eligibility="Pima County veterans and eligible family members.",
            eligibility_es="Veteranos del condado Pima y familiares elegibles.",
            notes="Call 520-724-8226; Oracle Road office; pairs with Pima County One-Stop veteran staff.",
            notes_es="Llame al 520-724-8226; oficina Oracle Road.",
            hours="Monday–Friday business hours",
            tags="tucson|pima|veterans|CVSO|VA-benefits|reentry",
            services="VA benefits counseling|Disability claims|Education benefits|Housing referrals|Employment referrals",
            county="Pima",
            served_counties="Pima",
            coverage="single",
            _source="https://www.pima.gov/veterans",
            _source_type="government",
            _confidence="high",
        )

    add(
            name="Valley Metro — Reduced Fare & ADA Paratransit",
            category="transportation",
            region="Phoenix / Maricopa County",
            description="Valley Metro provides public transit, reduced fares for seniors and people with disabilities, and ADA paratransit (Dial-a-Ride) across Maricopa County helping justice-involved adults reach probation appointments, ARIZONA@WORK, and medical visits.",
            description_es="Valley Metro ofrece transporte público, tarifas reducidas para adultos mayores y personas con discapacidades y paratransporte ADA en el condado Maricopa ayudando a adultos con antecedentes penales a llegar a citas de probatoria y ARIZONA@WORK.",
            address="302 N 1st Avenue",
            city="Phoenix",
            phone="602-253-5000",
            email="",
            website="https://www.valleymetro.org",
            eligibility="Maricopa County transit riders; reduced fare and ADA paratransit require eligibility application.",
            eligibility_es="Pasajeros de tránsito del condado Maricopa; tarifa reducida y paratransporte ADA requieren solicitud de elegibilidad.",
            notes="Call 602-253-5000; apply for ADA paratransit at valleymetro.org; reduced fare ID at office.",
            notes_es="Llame al 602-253-5000; solicite paratransporte ADA en valleymetro.org.",
            hours="Customer service Monday–Friday",
            tags="phoenix|maricopa|transportation|transit|ADA|reentry",
            services="Public bus and light rail|Reduced fare programs|ADA paratransit|Trip planning|Regional transit passes",
            county="Maricopa",
            served_counties="Maricopa",
            coverage="single",
            _source="https://www.valleymetro.org",
            _source_type="government",
            _confidence="high",
        )

    add(
            name="Community Legal Services — Mesa Office",
            category="legal-aid",
            region="Mesa / Maricopa County",
            description="The Community Legal Services Mesa office provides free civil legal aid to low-income residents of east Maricopa County including housing, benefits, family law, and set-aside assistance for justice-involved clients.",
            description_es="La oficina CLS de Mesa brinda asistencia legal civil gratuita a residentes de bajos ingresos del este del condado Maricopa incluyendo vivienda, beneficios y asistencia de anulación.",
            address="215 W Southern Avenue",
            city="Mesa",
            phone="480-833-9333",
            email="",
            website="https://www.clsaz.org",
            eligibility="Low-income residents of CLS Mesa service area with civil legal problems; LSC income limits apply.",
            eligibility_es="Residentes de bajos ingresos del área de servicio CLS Mesa con problemas legales civiles.",
            notes="Call 480-833-9333 or statewide 1-800-852-9075; apply at clsaz.org.",
            notes_es="Llame al 480-833-9333 o estatal 1-800-852-9075.",
            hours="Intake Monday–Friday",
            tags="mesa|maricopa|legal-aid|low-income|set-aside|reentry",
            services="Civil legal representation|Set-aside assistance|Housing legal aid|Benefits appeals|Family law assistance",
            county="Maricopa",
            served_counties="Maricopa",
            coverage="single",
            _source="https://www.clsaz.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Community Legal Services — West Valley Office",
            category="legal-aid",
            region="Glendale / Maricopa County",
            description="The Community Legal Services West Valley office serves low-income residents of west Maricopa County with civil legal aid including eviction defense, public benefits appeals, and record relief guidance for returning citizens.",
            description_es="La oficina CLS del Valle del Oeste sirve a residentes de bajos ingresos del oeste del condado Maricopa con asistencia legal civil incluyendo defensa contra desalojo y apelaciones de beneficios públicos.",
            address="9201 W Thomas Road",
            city="Glendale",
            phone="623-516-0213",
            email="",
            website="https://www.clsaz.org",
            eligibility="Low-income west Maricopa County residents with civil legal problems; LSC income limits apply.",
            eligibility_es="Residentes de bajos ingresos del oeste del condado Maricopa con problemas legales civiles.",
            notes="Call 623-516-0213 or statewide 1-800-852-9075; apply at clsaz.org.",
            notes_es="Llame al 623-516-0213 o estatal 1-800-852-9075.",
            hours="Intake Monday–Friday",
            tags="glendale|maricopa|legal-aid|low-income|reentry",
            services="Civil legal representation|Eviction defense|Benefits appeals|Set-aside guidance|Family law assistance",
            county="Maricopa",
            served_counties="Maricopa",
            coverage="single",
            _source="https://www.clsaz.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Community Legal Services — Yuma Office",
            category="legal-aid",
            region="Yuma / Yuma County",
            description="The Community Legal Services Yuma office provides free civil legal aid to low-income Yuma County residents including agricultural workers and justice-involved clients with housing, benefits, and family law needs.",
            description_es="La oficina CLS de Yuma brinda asistencia legal civil gratuita a residentes de bajos ingresos del condado Yuma incluidos trabajadores agrícolas y clientes con antecedentes penales.",
            address="2650 W 8th Street",
            city="Yuma",
            phone="928-782-0676",
            email="",
            website="https://www.clsaz.org",
            eligibility="Low-income Yuma County residents with civil legal problems; LSC income limits apply.",
            eligibility_es="Residentes de bajos ingresos del condado Yuma con problemas legales civiles.",
            notes="Call 928-782-0676 or statewide 1-800-852-9075; bilingual intake available.",
            notes_es="Llame al 928-782-0676 o estatal 1-800-852-9075; admisión bilingüe disponible.",
            hours="Intake Monday–Friday",
            tags="yuma|legal-aid|low-income|bilingual|reentry",
            services="Civil legal representation|Housing legal aid|Benefits advocacy|Family law|Bilingual services",
            county="Yuma",
            served_counties="Yuma",
            coverage="single",
            _source="https://www.clsaz.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Arizona Recovered Citizens United",
            category="peer-support",
            region="Phoenix / Maricopa County",
            description="Arizona Recovered Citizens United organizes peer support, civic engagement, and reentry navigation for formerly incarcerated Arizonans in Maricopa County through mutual aid networks and partnerships with Arizona Transformation Project.",
            description_es="Arizona Recovered Citizens United organiza apoyo entre pares, participación cívica y navegación de reinserción para arizonenses anteriormente encarcelados en el condado Maricopa.",
            address="424 S 2nd Avenue",
            city="Phoenix",
            phone="602-254-2220",
            email="",
            website="https://www.arizonarecoveredcitizens.org",
            eligibility="Formerly incarcerated Arizonans and allies; peer-led organization.",
            eligibility_es="Arizonenses anteriormente encarcelados y aliados; organización dirigida por pares.",
            notes="Contact through arizonarecoveredcitizens.org; pairs with peer recovery centers.",
            notes_es="Contacte a través de arizonarecoveredcitizens.org.",
            hours="Meeting schedules vary",
            tags="phoenix|maricopa|peer-support|advocacy|reentry|reentry-organizations",
            services="Peer support networks|Civic engagement|Reentry navigation|Mutual aid|Policy advocacy",
            county="Maricopa",
            served_counties="Maricopa",
            coverage="single",
            _source="https://www.arizonarecoveredcitizens.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Mohave County Peer Support Center",
            category="peer-support",
            region="Kingman / Mohave County",
            description="Mohave County behavioral health peer support services connect justice-involved adults in rural Mohave County to certified peer specialists, recovery groups, and referrals to West Yavapai Guidance Clinic satellite and Kingman Regional Medical Center.",
            description_es="Los servicios de apoyo entre pares de salud conductual del condado Mohave conectan a adultos con antecedentes penales en el condado rural Mohave con especialistas certificados entre pares y grupos de recuperación.",
            address="1040 Kino Avenue",
            city="Kingman",
            phone="928-753-0714",
            email="",
            website="https://www.mohavecounty.us",
            eligibility="Mohave County adults in behavioral health recovery; AHCCCS peer services through RBHA.",
            eligibility_es="Adultos del condado Mohave en recuperación de salud conductual; servicios entre pares AHCCCS a través de RBHA.",
            notes="Coordinate through Mohave County DES behavioral health referral; call 928-753-0714.",
            notes_es="Coordine a través de referencia de salud conductual DES del condado Mohave.",
            hours="Monday–Friday business hours",
            tags="kingman|mohave|peer-support|rural|recovery|reentry",
            services="Certified peer specialists|Recovery groups|Behavioral health navigation|Rural peer support|Treatment referrals",
            county="Mohave",
            served_counties="Mohave",
            coverage="single",
            _source="https://www.mohavecounty.us",
            _source_type="government",
            _confidence="high",
        )

    add(
            name="Coconino County Peer Support Services",
            category="peer-support",
            region="Flagstaff / Coconino County",
            description="Coconino County Health and Human Services peer support programs connect justice-involved adults in Flagstaff and rural northern Arizona to recovery coaching and North Country HealthCare behavioral health follow-up.",
            description_es="Los programas de apoyo entre pares de Salud y Servicios Humanos del condado Coconino conectan a adultos con antecedentes penales en Flagstaff y el norte rural de Arizona con coaching de recuperación.",
            address="2625 N King Street",
            city="Flagstaff",
            phone="928-679-7272",
            email="",
            website="https://www.coconino.az.gov",
            eligibility="Coconino County adults in behavioral health recovery; peer services through AHCCCS RBHA.",
            eligibility_es="Adultos del condado Coconino en recuperación de salud conductual; servicios entre pares a través de RBHA AHCCCS.",
            notes="Call 928-679-7272; pairs with North Country HealthCare and ARIZONA@WORK Flagstaff.",
            notes_es="Llame al 928-679-7272; se vincula con North Country HealthCare.",
            hours="Monday–Friday business hours",
            tags="flagstaff|coconino|peer-support|rural|recovery|reentry",
            services="Peer recovery coaching|Behavioral health navigation|Rural support groups|Treatment referrals|Community wellness",
            county="Coconino",
            served_counties="Coconino",
            coverage="single",
            _source="https://www.coconino.az.gov",
            _source_type="government",
            _confidence="high",
        )

    add(
            name="Reentry Coalition of Pima County",
            category="reentry-organizations",
            region="Tucson / Pima County",
            description="The Reentry Coalition of Pima County coordinates cross-agency reentry planning among corrections, behavioral health, workforce, and legal partners serving justice-involved adults returning to Tucson and eastern Pima County.",
            description_es="La Coalición de Reinserción del condado Pima coordina la planificación de reinserción entre agencias de correcciones, salud conductual, fuerza laboral y aliados legales que sirven a adultos con antecedentes penales que regresan a Tucson.",
            address="3830 E Bellevue Street",
            city="Tucson",
            phone="520-323-1708",
            email="",
            website="https://www.ourfamilyservices.org",
            eligibility="Justice-involved adults and reentry service providers in Pima County; coalition referrals through partner agencies.",
            eligibility_es="Adultos con antecedentes penales y proveedores de servicios de reinserción en el condado Pima; referencias a través de agencias aliadas.",
            notes="Contact through Our Family Services reentry navigation; coalition partner network.",
            notes_es="Contacte a través de navegación de reinserción de Our Family Services.",
            hours="Coalition meetings monthly",
            tags="tucson|pima|reentry|coalition|coordination|reentry-organizations",
            services="Cross-agency coordination|Reentry navigation|Partner referrals|Systems planning|Community reentry network",
            county="Pima",
            served_counties="Pima",
            coverage="single",
            _source="https://www.ourfamilyservices.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Sunrise Community — Reentry Employment",
            category="employment",
            region="Tucson / Pima County",
            description="Sunrise Community provides employment services and day programs for adults with disabilities in Pima County including justice-involved individuals who qualify for vocational supports through DES and RSA referrals.",
            description_es="Sunrise Community ofrece servicios de empleo y programas diurnos para adultos con discapacidades en el condado Pima incluidas personas con antecedentes penales que califican para apoyos vocacionales.",
            address="300 N Commerce Park Loop",
            city="Tucson",
            phone="520-795-0727",
            email="",
            website="https://www.sunrisecommunity.org",
            eligibility="Adults with developmental or intellectual disabilities in Pima County; VR and DES referrals.",
            eligibility_es="Adultos con discapacidades del desarrollo o intelectuales en el condado Pima; referencias VR y DES.",
            notes="Call 520-795-0727; near Pima County One-Stop; coordinate with RSA counselor.",
            notes_es="Llame al 520-795-0727; cerca del One-Stop del condado Pima.",
            hours="Monday–Friday business hours",
            tags="tucson|pima|employment|disability|vocational|reentry",
            services="Vocational day programs|Supported employment|Job coaching|DES coordination|RSA referrals",
            county="Pima",
            served_counties="Pima",
            coverage="single",
            _source="https://www.sunrisecommunity.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Yavapai County Veterans Service Office",
            category="veterans",
            region="Prescott / Yavapai County",
            description="The Yavapai County Veterans Service Office provides VA benefits counseling and emergency assistance referrals for veterans in Prescott, Prescott Valley, and Verde Valley including justice-involved veterans.",
            description_es="La Oficina de Servicios para Veteranos del condado Yavapai ofrece consejería de beneficios VA y referencias de asistencia de emergencia para veteranos en Prescott y el Valle de Verde.",
            address="1015 Fair Street",
            city="Prescott",
            phone="928-771-3280",
            email="",
            website="https://www.yavapaiaz.gov",
            eligibility="Yavapai County veterans and eligible family members.",
            eligibility_es="Veteranos del condado Yavapai y familiares elegibles.",
            notes="Call 928-771-3280; Fair Street office; pairs with U.S. VETS Prescott.",
            notes_es="Llame al 928-771-3280; oficina Fair Street.",
            hours="Monday–Friday business hours",
            tags="prescott|yavapai|veterans|CVSO|VA-benefits|reentry",
            services="VA benefits counseling|Disability claims|Emergency assistance referrals|Education benefits|Employment preference guidance",
            county="Yavapai",
            served_counties="Yavapai",
            coverage="single",
            _source="https://www.yavapaiaz.gov",
            _source_type="government",
            _confidence="high",
        )

    add(
            name="Mohave County Veterans Service Office",
            category="veterans",
            region="Kingman / Mohave County",
            description="The Mohave County Veterans Service Office helps veterans in Kingman, Lake Havasu City, and Colorado City access VA disability claims, pension assistance, and referrals to rural veteran housing partners.",
            description_es="La Oficina de Servicios para Veteranos del condado Mohave ayuda a veteranos en Kingman, Lake Havasu City y Colorado City a acceder a reclamos de discapacidad VA y asistencia de pensión.",
            address="1040 Kino Avenue",
            city="Kingman",
            phone="928-753-0723",
            email="",
            website="https://www.mohavecounty.us",
            eligibility="Mohave County veterans and eligible family members.",
            eligibility_es="Veteranos del condado Mohave y familiares elegibles.",
            notes="Call 928-753-0723; co-located with DES; rural veteran outreach available.",
            notes_es="Llame al 928-753-0723; ubicado junto a DES.",
            hours="Monday–Friday business hours",
            tags="kingman|mohave|veterans|CVSO|VA-benefits|rural|reentry",
            services="VA disability claims|Pension assistance|Rural veteran outreach|Benefits appeals|Housing referrals",
            county="Mohave",
            served_counties="Mohave",
            coverage="single",
            _source="https://www.mohavecounty.us",
            _source_type="government",
            _confidence="high",
        )

    add(
            name="Sun Tran — Tucson Paratransit",
            category="transportation",
            region="Tucson / Pima County",
            description="Sun Tran and Sun Van paratransit provide public bus service and ADA complementary paratransit for eligible Pima County riders including justice-involved adults traveling to probation, CODAC, and Pima County One-Stop appointments.",
            description_es="Sun Tran y paratransporte Sun Van ofrecen servicio de autobús público y paratransporte ADA complementario para pasajeros elegibles del condado Pima incluidos adultos con antecedentes penales que viajan a citas de probatoria y CODAC.",
            address="3920 N Sun Tran Boulevard",
            city="Tucson",
            phone="520-792-9222",
            email="",
            website="https://www.suntran.com",
            eligibility="Pima County transit riders; Sun Van requires ADA eligibility certification.",
            eligibility_es="Pasajeros de tránsito del condado Pima; Sun Van requiere certificación de elegibilidad ADA.",
            notes="Call 520-792-9222; apply for Sun Van at suntran.com; reduced fares available.",
            notes_es="Llame al 520-792-9222; solicite Sun Van en suntran.com.",
            hours="Customer service Monday–Friday",
            tags="tucson|pima|transportation|transit|ADA|reentry",
            services="Public bus service|ADA paratransit|Reduced fares|Trip planning|Regional transit",
            county="Pima",
            served_counties="Pima",
            coverage="single",
            _source="https://www.suntran.com",
            _source_type="government",
            _confidence="high",
        )

    add(
            name="Arizona Center for Disability Law",
            category="legal-aid",
            region="Phoenix / Maricopa County",
            description="The Arizona Center for Disability Law provides free advocacy for Arizonans with disabilities including justice-involved individuals facing discrimination in employment, housing, and benefits access under the ADA and Arizona law.",
            description_es="El Centro de Ley de Discapacidad de Arizona ofrece defensa gratuita para arizonenses con discapacidades incluidas personas con antecedentes penales que enfrentan discriminación en empleo, vivienda y acceso a beneficios.",
            address="5025 E Washington Street",
            city="Phoenix",
            phone="602-274-6287",
            email="",
            website="https://www.acdl.com",
            eligibility="Arizonans with disabilities facing civil rights or benefits access issues; includes reentry-related ADA claims.",
            eligibility_es="Arizonenses con discapacidades que enfrentan problemas de derechos civiles o acceso a beneficios.",
            notes="Call 602-274-6287; intake for disability rights issues; not general criminal defense.",
            notes_es="Llame al 602-274-6287; admisión para asuntos de derechos de discapacidad.",
            hours="Intake Monday–Friday",
            tags="phoenix|maricopa|legal-aid|disability|ADA|reentry",
            services="Disability rights advocacy|ADA employment claims|Housing discrimination|Benefits access appeals|Systems advocacy",
            county="Maricopa",
            served_counties="",
            coverage="statewide",
            _source="https://www.acdl.com",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Florence Project — Immigrant Legal Services",
            category="legal-aid",
            region="Florence / Pinal County",
            description="The Florence Project provides free legal services to detained and formerly detained immigrants in Arizona including justice-involved non-citizens facing deportation proceedings, with offices in Florence and Phoenix.",
            description_es="El Florence Project brinda servicios legales gratuitos a inmigrantes detenidos y anteriormente detenidos en Arizona incluidos no ciudadanos con antecedentes penales que enfrentan procedimientos de deportación.",
            address="325 W 2nd Street",
            city="Florence",
            phone="520-868-0191",
            email="",
            website="https://www.florenceproject.org",
            eligibility="Detained and formerly detained immigrants in Arizona; immigration legal services only.",
            eligibility_es="Inmigrantes detenidos y anteriormente detenidos en Arizona; solo servicios legales de inmigración.",
            notes="Call 520-868-0191; detention visitation and legal orientation; Phoenix office for released clients.",
            notes_es="Llame al 520-868-0191; orientación legal y visitas a detención.",
            hours="Office Monday–Friday",
            tags="florence|pinal|legal-aid|immigration|detention|reentry",
            services="Immigration legal representation|Detention visitation|Know Your Rights orientation|Bond hearings|Post-release immigration support",
            county="Pinal",
            served_counties="Pinal|Maricopa|Pima|Cochise|Santa Cruz",
            coverage="multi",
            _source="https://www.florenceproject.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Central Arizona College — Adult Education",
            category="education",
            region="Coolidge / Pinal County",
            description="Central Arizona College Adult Education offers free GED and High School Equivalency preparation for Pinal County adults including justice-involved residents at Coolidge and Aravaipa campuses.",
            description_es="Central Arizona College Educación para Adultos ofrece preparación GED y equivalencia de secundaria gratuita para adultos del condado Pinal incluidos residentes con antecedentes penales.",
            address="8470 N Overfield Road",
            city="Coolidge",
            phone="520-494-5444",
            email="",
            website="https://www.centralaz.edu",
            eligibility="Pinal County adults age 16+; free HSE classes.",
            eligibility_es="Adultos del condado Pinal de 16+ años; clases HSE gratuitas.",
            notes="Call 520-494-5444; Coolidge main campus; pairs with ARIZONA@WORK Pinal.",
            notes_es="Llame al 520-494-5444; campus principal Coolidge.",
            hours="Class schedules vary",
            tags="coolidge|pinal|education|GED|reentry",
            services="GED preparation|High School Equivalency|Adult education|College transition|Workforce referrals",
            county="Pinal",
            served_counties="Pinal",
            coverage="single",
            _source="https://www.centralaz.edu",
            _source_type="nonprofit",
            _confidence="high",
        )
