#!/usr/bin/env python3
"""Generate ohio-resources.csv and ohio-research-log.csv."""
import csv
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RESOURCES_PATH = ROOT / "data" / "ohio-resources.csv"
LOG_PATH = ROOT / "data" / "ohio-research-log.csv"
DATE = "2026-06-20"

COLUMNS = [
    "id", "name", "category", "region", "description", "description_es",
    "address", "city", "phone", "email", "website", "eligibility", "eligibility_es",
    "notes", "notes_es", "hours", "tags", "services", "county",
    "latitude", "longitude", "served_counties", "coverage",
]
LOG_COLUMNS = ["source_url", "source_type", "date_accessed", "confidence", "notes", "id_reference"]

# Each entry: dict with resource fields + _source, _source_type, _confidence
ENTRIES = []

def add(**kw):
    ENTRIES.append(kw)

# --- Phase 1: Statewide backbone ---
add(
    name="Ohio DRC — Office of Reentry",
    category="state-agency", region="Statewide",
    description="The Ohio Department of Rehabilitation and Correction Office of Reentry coordinates statewide reentry planning and connects people in custody or under community supervision with local coalitions, housing, employment, treatment, and legal resources. Staff support pre-release planning and community partner navigation across Ohio. This office provides planning and referrals—not emergency crisis response.",
    description_es="La Oficina de Reinserción del Departamento de Rehabilitación y Corrección de Ohio coordina la planificación estatal y conecta a personas en custodia o bajo supervisión comunitaria con coaliciones locales, vivienda, empleo, tratamiento y recursos legales. El personal apoya la planificación previa a la liberación y la navegación de aliados comunitarios en todo Ohio. Esta oficina ofrece planificación y referencias, no respuesta de crisis.",
    address="770 West Broad Street", city="Columbus", phone="(614) 752-0627",
    email="DRC.OfficeofReentry@drc.ohio.gov", website="https://drc.ohio.gov/reentry",
    eligibility="Generally serves Ohio residents under DRC custody, parole, or seeking state reentry coordination and coalition referrals.",
    eligibility_es="Generalmente sirve a residentes de Ohio bajo custodia del DRC, libertad condicional o que buscan coordinación estatal de reinserción.",
    notes="Contact via phone or email; see drc.ohio.gov for regional reentry coalition listings. Not a walk-in crisis line.",
    notes_es="Contacte por teléfono o correo; consulte drc.ohio.gov para coaliciones regionales. No es una línea de crisis.",
    hours="Monday–Friday, 8:00 a.m.–4:30 p.m. ET",
    tags="statewide|reentry|DOC|probation|parole|hotline",
    services="Reentry planning coordination|Regional coalition referrals|Pre-release resource navigation|Community partner connections",
    county="Franklin", latitude="39.9612", longitude="-83.0069", served_counties="", coverage="statewide",
    _source="https://drc.ohio.gov/reentry", _source_type="government", _confidence="high",
)
add(
    name="Relink.org",
    category="reentry-organizations", region="Statewide",
    description="Free statewide online directory connecting people in addiction recovery, human trafficking recovery, and incarceration reentry with local service providers. Users search by location and service type for housing, treatment, employment, legal aid, and peer support. Relink is a referral hub—it does not provide direct services.",
    description_es="Directorio en línea gratuito en todo el estado que conecta a personas en recuperación de adicciones, trata de personas y reinserción post-incarcelación con proveedores locales. Los usuarios buscan por ubicación y tipo de servicio. Relink es un centro de referencias; no presta servicios directos.",
    address="", city="Cleveland", phone="(216) 762-0595", email="bcampbell@relink.org",
    website="https://relink.org",
    eligibility="Open to Ohio residents seeking reentry, recovery, or anti-trafficking resources; no criminal-record restrictions stated.",
    eligibility_es="Abierto a residentes de Ohio que buscan recursos de reinserción, recuperación o anti-trata; sin restricciones de antecedentes indicadas.",
    notes="Search online anytime; phone support available during business hours for navigation help.",
    notes_es="Busque en línea en cualquier momento; soporte telefónico en horario laboral para ayuda de navegación.",
    hours="Available online 24/7; phone support Monday–Friday business hours",
    tags="statewide|online|reentry|referral-only|recovery",
    services="Online resource directory|Geo-located provider search|Reentry service navigation|Recovery resource referrals",
    county="", latitude="", longitude="", served_counties="", coverage="statewide",
    _source="https://drc.ohio.gov/systems-and-services/2-reentry-services/reentry-services", _source_type="government", _confidence="high",
)
add(
    name="Ohio Association of Local Reentry Coalitions (OALRC)",
    category="reentry-organizations", region="Statewide",
    description="Statewide network supporting local reentry coalitions across Ohio through coordination, advocacy, and resource sharing. OALRC connects county-level coalitions and helps communities build reentry infrastructure. This is a networking and support organization—not a direct-service provider.",
    description_es="Red estatal que apoya coaliciones locales de reinserción en Ohio mediante coordinación, defensa y recursos compartidos. OALRC conecta coaliciones a nivel de condado. Es una organización de red, no un proveedor de servicios directos.",
    address="", city="", phone="(567) 200-6815", email="ohioassociationreentry@gmail.com",
    website="https://drc.ohio.gov/systems-and-services/2-reentry-services/reentry-coalitions",
    eligibility="Open to Ohio reentry coalitions, community partners, and justice-involved individuals seeking local coalition contacts.",
    eligibility_es="Abierto a coaliciones de reinserción de Ohio, aliados comunitarios y personas buscando contactos locales.",
    notes="Contact president Tom Luettke for coalition information; see ODRC reentry coalition PDF for local contacts.",
    notes_es="Contacte al presidente para información de coaliciones; consulte el PDF de coaliciones del DRC para contactos locales.",
    hours="Contact for current hours",
    tags="statewide|reentry|coalition|networking|referral-only",
    services="Coalition network coordination|Advocacy|Resource sharing|Local coalition referrals",
    county="", latitude="", longitude="", served_counties="", coverage="statewide",
    _source="https://dam.assets.ohio.gov/image/upload/drc.ohio.gov/Forms/Reentry_Coalitions_4-20-26.pdf", _source_type="government", _confidence="high",
)
add(
    name="Ohio 211",
    category="state-agency", region="Statewide",
    description="Free statewide information and referral service connecting Ohioans to health and human services including housing, food, utilities, employment, and crisis support. Specialists help callers find local programs by need and location. 211 is a referral line—not a direct-service provider.",
    description_es="Servicio gratuito de información y referencia en todo el estado que conecta a los ohianos con servicios de salud y humanos incluyendo vivienda, alimentos, empleo y apoyo en crisis. Los especialistas ayudan a encontrar programas locales. 211 es una línea de referencia, no un proveedor directo.",
    address="", city="", phone="211", email="", website="https://www.211.org/get-help/ohio",
    eligibility="Open to all Ohio residents; no criminal-record restrictions stated.",
    eligibility_es="Abierto a todos los residentes de Ohio; sin restricciones de antecedentes indicadas.",
    notes="Dial 211 from any Ohio phone; text your ZIP code to 898211; chat available at 211.org.",
    notes_es="Marque 211 desde cualquier teléfono de Ohio; envíe su código postal por texto al 898211.",
    hours="Available 24/7",
    tags="statewide|hotline|211|referral-only|basic-needs",
    services="Information and referral|Housing resource navigation|Benefits referrals|Crisis resource connections",
    county="", latitude="", longitude="", served_counties="", coverage="statewide",
    _source="https://www.211.org/get-help/ohio", _source_type="directory", _confidence="high",
)
add(
    name="988 Suicide & Crisis Lifeline — Ohio",
    category="healthcare", region="Statewide",
    description="Free confidential 24/7 crisis support for people experiencing mental health emergencies, suicidal thoughts, or substance use crises. Trained counselors provide immediate support and can connect callers to local crisis services. Available to anyone in Ohio—not reentry-specific but essential for justice-involved individuals in crisis.",
    description_es="Apoyo gratuito y confidencial 24/7 para emergencias de salud mental, pensamientos suicidas o crisis por uso de sustancias. Consejeros capacitados ofrecen apoyo inmediato y conexión a servicios locales. Disponible para cualquier persona en Ohio.",
    address="", city="", phone="988", email="", website="https://988lifeline.org",
    eligibility="Open to anyone in Ohio experiencing a mental health or suicide crisis; no eligibility restrictions.",
    eligibility_es="Abierto a cualquier persona en Ohio en crisis de salud mental o suicidio; sin restricciones.",
    notes="Call or text 988; Spanish-language support available. For immediate danger call 911.",
    notes_es="Llame o envíe texto al 988; soporte en español disponible. Para peligro inmediato llame al 911.",
    hours="Available 24/7",
    tags="statewide|hotline|crisis|mental-health|988",
    services="Crisis counseling|Suicide prevention support|Mental health referrals|Substance use crisis support",
    county="", latitude="", longitude="", served_counties="", coverage="statewide",
    _source="https://988lifeline.org", _source_type="government", _confidence="high",
)
add(
    name="Ohio Legal Help",
    category="legal-aid", region="Statewide",
    description="Statewide legal information portal providing plain-language guides, court forms, and tools for sealing criminal records, housing, benefits, and family law. Helps Ohioans find local legal aid providers and understand their rights. Online resource hub—not a law firm providing direct representation on its own.",
    description_es="Portal estatal de información legal con guías en lenguaje sencillo, formularios judiciales y herramientas para sellar antecedentes, vivienda y beneficios. Ayuda a encontrar asistencia legal local. Es un centro de recursos en línea, no un bufete de abogados.",
    address="", city="", phone="1-866-529-6446", email="", website="https://www.ohiolegalhelp.org",
    eligibility="Open to all Ohio residents seeking legal information; direct representation eligibility varies by local legal aid provider.",
    eligibility_es="Abierto a todos los residentes de Ohio que buscan información legal; la representación directa varía según la organización local.",
    notes="Call 1-866-LAW-OHIO (529-6446) for help finding legal resources; website available in English and Spanish.",
    notes_es="Llame al 1-866-LAW-OHIO (529-6446) para encontrar recursos legales; sitio web en inglés y español.",
    hours="Phone line Monday–Friday, 8:30 a.m.–4:30 p.m. ET; website 24/7",
    tags="statewide|legal-aid|online|expungement|hotline",
    services="Legal information guides|Court form assistance|Local legal aid finder|Record sealing information",
    county="", latitude="", longitude="", served_counties="", coverage="statewide",
    _source="https://www.ohiolegalhelp.org", _source_type="nonprofit", _confidence="high",
)
add(
    name="Ohio Reentry Connections",
    category="reentry-organizations", region="Statewide",
    description="Statewide reentry resource initiative helping justice-involved Ohioans connect with housing, employment, treatment, and community support services. Provides navigation and referrals to local reentry programs and partner agencies across the state.",
    description_es="Iniciativa estatal de recursos de reinserción que ayuda a personas con antecedentes penales a conectarse con vivienda, empleo, tratamiento y apoyo comunitario. Ofrece navegación y referencias a programas locales.",
    address="", city="Columbus", phone="", email="", website="https://ohioreentryconnections.org",
    eligibility="Justice-involved Ohio residents seeking reentry support; contact program for current eligibility.",
    eligibility_es="Residentes de Ohio con antecedentes penales que buscan apoyo de reinserción; contacte para elegibilidad actual.",
    notes="Visit website for resource listings and partner contacts; verify current phone intake on site.",
    notes_es="Visite el sitio web para listados de recursos y contactos de aliados.",
    hours="Contact for current hours",
    tags="statewide|reentry|online|referral-only",
    services="Reentry resource navigation|Community partner referrals|Online resource directory",
    county="", latitude="", longitude="", served_counties="", coverage="statewide",
    _source="https://ohioreentryconnections.org", _source_type="nonprofit", _confidence="medium",
)
add(
    name="Certificate of Qualification for Employment (CQE) — Ohio DRC",
    category="legal-aid", region="Statewide",
    description="Ohio's Certificate of Qualification for Employment program helps eligible individuals with criminal records obtain a certificate that can reduce automatic licensing and employment barriers. Administered through the Department of Rehabilitation and Correction with application guidance at drccqe.com.",
    description_es="El programa de Certificado de Calificación para el Empleo de Ohio ayuda a personas elegibles con antecedentes penales a obtener un certificado que puede reducir barreras automáticas de licencias y empleo. Administrado por el DRC con orientación en drccqe.com.",
    address="770 West Broad Street", city="Columbus", phone="(614) 752-1161", email="",
    website="https://drccqe.com",
    eligibility="Ohio residents with qualifying criminal records seeking employment or occupational licensing relief; offense-type and waiting-period rules apply.",
    eligibility_es="Residentes de Ohio con antecedentes penales elegibles que buscan alivio para empleo o licencias; aplican reglas de tipo de delito y períodos de espera.",
    notes="Apply online at drccqe.com; legal aid and reentry partners can assist with applications.",
    notes_es="Solicite en línea en drccqe.com; aliados legales y de reinserción pueden ayudar con las solicitudes.",
    hours="Online application available 24/7; DRC office Monday–Friday business hours",
    tags="statewide|CQE|employment|fair-chance|online",
    services="CQE application processing|Employment barrier relief|Occupational licensing guidance",
    county="Franklin", latitude="39.9612", longitude="-83.0069", served_counties="", coverage="statewide",
    _source="https://drccqe.com", _source_type="government", _confidence="high",
)
add(
    name="Ohio Adult Parole Authority",
    category="probation-parole", region="Statewide",
    description="State agency responsible for parole supervision, parole board decisions, and community supervision of individuals released from Ohio prisons. Parole officers connect supervisees to reentry resources and enforce supervision conditions. Contact for supervision status, reporting requirements, and regional office locations.",
    description_es="Agencia estatal responsable de la supervisión de libertad condicional, decisiones de la junta de libertad condicional y supervisión comunitaria de personas liberadas de prisiones de Ohio. Los oficiales conectan a supervisados con recursos de reinserción.",
    address="770 West Broad Street", city="Columbus", phone="(614) 752-1200", email="",
    website="https://drc.ohio.gov/about-us/divisions-and-offices/adult-parole-authority",
    eligibility="Individuals under Ohio parole or community supervision; family members may contact for general information.",
    eligibility_es="Personas bajo libertad condicional o supervisión comunitaria de Ohio; familiares pueden contactar para información general.",
    notes="Regional parole offices statewide; not a reentry resource navigation line—contact Office of Reentry for resource referrals.",
    notes_es="Oficinas regionales en todo el estado; para referencias de recursos contacte la Oficina de Reinserción.",
    hours="Monday–Friday, 8:00 a.m.–4:30 p.m. ET",
    tags="statewide|parole|DOC|probation|supervision",
    services="Parole supervision|Community supervision|Parole board services|Supervision compliance support",
    county="Franklin", latitude="39.9612", longitude="-83.0069", served_counties="", coverage="statewide",
    _source="https://drc.ohio.gov/about-us/divisions-and-offices/adult-parole-authority", _source_type="government", _confidence="high",
)
add(
    name="Ohio Benefits — benefits.ohio.gov",
    category="financial-assistance", region="Statewide",
    description="Official statewide online portal for applying for and managing Ohio public benefits including Medicaid, SNAP (food assistance), cash assistance, and child care subsidies. Justice-involved individuals can apply for coverage and food support after release.",
    description_es="Portal oficial en línea para solicitar y administrar beneficios públicos de Ohio incluyendo Medicaid, SNAP, asistencia en efectivo y subsidios de cuidado infantil. Personas en reinserción pueden solicitar cobertura y apoyo alimentario después de la liberación.",
    address="", city="", phone="(844) 640-6446", email="", website="https://benefits.ohio.gov",
    eligibility="Ohio residents meeting income and program requirements for Medicaid, SNAP, TANF, or child care; criminal record generally not a barrier.",
    eligibility_es="Residentes de Ohio que cumplan requisitos de ingresos para Medicaid, SNAP, TANF o cuidado infantil; antecedentes penales generalmente no son barrera.",
    notes="Create account online; county Job and Family Services offices assist with applications and document verification.",
    notes_es="Cree una cuenta en línea; las oficinas del condado de Job and Family Services ayudan con solicitudes.",
    hours="Online 24/7; county office hours vary",
    tags="statewide|benefits|SNAP|Medicaid|online",
    services="Medicaid application|SNAP enrollment|Cash assistance application|Benefits account management",
    county="", latitude="", longitude="", served_counties="", coverage="statewide",
    _source="https://benefits.ohio.gov", _source_type="government", _confidence="high",
)
add(
    name="OhioMHAS Consumer & Family Toll-Free Bridge Line",
    category="healthcare", region="Statewide",
    description="Free statewide phone line staffed by peer specialists providing referral information for addiction and mental health services, Medicaid navigation, and consumer rights guidance. Helps Ohioans find treatment providers and understand how to access behavioral health care.",
    description_es="Línea telefónica gratuita en todo el estado atendida por especialistas pares que ofrecen referencias para servicios de adicción y salud mental, navegación de Medicaid y orientación sobre derechos del consumidor.",
    address="", city="Columbus", phone="(877) 275-6364", email="askMHAS@mha.ohio.gov",
    website="https://mha.ohio.gov/get-help/get-help-now/toll-free-bridge-line",
    eligibility="Open to Ohio residents seeking addiction or mental health service referrals; no criminal-record restrictions stated.",
    eligibility_es="Abierto a residentes de Ohio que buscan referencias de servicios de adicción o salud mental.",
    notes="Also reachable locally at (614) 466-7228; email askMHAS@mha.ohio.gov for non-urgent questions.",
    notes_es="También disponible localmente al (614) 466-7228; correo askMHAS@mha.ohio.gov para preguntas no urgentes.",
    hours="Monday–Friday business hours",
    tags="statewide|hotline|mental-health|Medicaid|peer-support",
    services="Treatment referrals|Mental health resource navigation|Medicaid information|Consumer rights guidance",
    county="", latitude="", longitude="", served_counties="", coverage="statewide",
    _source="https://mha.ohio.gov/get-help/get-help-now/toll-free-bridge-line", _source_type="government", _confidence="high",
)
add(
    name="ODJFS — Restored Citizens Initiative",
    category="financial-assistance", region="Statewide",
    description="Ohio Department of Job and Family Services initiative helping restored citizens (formerly incarcerated individuals) access public benefits, employment services, and community reintegration support upon release. Coordinates with county JFS offices and reentry partners statewide.",
    description_es="Iniciativa del Departamento de Job and Family Services de Ohio que ayuda a ciudadanos restaurados a acceder a beneficios públicos, servicios de empleo y apoyo de reintegración comunitaria al salir de prisión.",
    address="30 East Broad Street", city="Columbus", phone="(614) 466-6282", email="",
    website="https://jfs.ohio.gov/wps/portal/gov/jfs/help/help-for-families/restored-citizens",
    eligibility="Ohio residents recently released from incarceration seeking benefits enrollment and employment support.",
    eligibility_es="Residentes de Ohio recién liberados de prisión que buscan inscripción en beneficios y apoyo de empleo.",
    notes="Contact local county Job and Family Services office for intake; bring release documents and ID.",
    notes_es="Contacte la oficina local de Job and Family Services; traiga documentos de liberación e identificación.",
    hours="County office hours vary; state office Monday–Friday business hours",
    tags="statewide|benefits|reentry|employment|restored-citizens",
    services="Benefits enrollment assistance|Employment services referral|Reentry benefits navigation",
    county="Franklin", latitude="39.9625", longitude="-82.9988", served_counties="", coverage="statewide",
    _source="https://jfs.ohio.gov/wps/portal/gov/jfs/help/help-for-families/restored-citizens", _source_type="government", _confidence="high",
)
add(
    name="Ohio Recovery Housing Locator",
    category="housing", region="Statewide",
    description="State-supported online directory of certified recovery housing in Ohio for people in substance use recovery, including options that accept justice-involved referrals. Users search by county and housing level for sober living and recovery residences.",
    description_es="Directorio en línea apoyado por el estado de viviendas de recuperación certificadas en Ohio para personas en recuperación de sustancias, incluyendo opciones que aceptan referencias de personas con antecedentes penales.",
    address="", city="", phone="", email="", website="https://mha.ohio.gov/community-partners/recovery/recovery-housing",
    eligibility="Individuals in recovery seeking certified recovery housing; program-specific requirements vary by residence.",
    eligibility_es="Personas en recuperación que buscan vivienda certificada; los requisitos varían según la residencia.",
    notes="Verify current openings directly with listed residences; certification status shown in directory.",
    notes_es="Verifique disponibilidad directamente con las residencias listadas.",
    hours="Online 24/7",
    tags="statewide|housing|recovery|substance-use|online",
    services="Recovery housing search|Certified residence directory|County-based housing listings",
    county="", latitude="", longitude="", served_counties="", coverage="statewide",
    _source="https://mha.ohio.gov/community-partners/recovery/recovery-housing", _source_type="government", _confidence="high",
)
add(
    name="OhioMHAS Access to Recovery (ATR)",
    category="substance-use-treatment", region="Statewide",
    description="Ohio Department of Mental Health and Addiction Services voucher program supporting criminal justice-involved adults and veterans in recovery with services including recovery housing, transportation, employment training, and peer support. Available in select counties through participating care coordinators.",
    description_es="Programa de vales del Departamento de Salud Mental y Adicciones de Ohio que apoya a adultos con antecedentes penales y veteranos en recuperación con vivienda, transporte, capacitación laboral y apoyo entre pares. Disponible en condados selectos.",
    address="30 East Broad Street", city="Columbus", phone="(614) 466-2596", email="questions@mha.ohio.gov",
    website="https://mha.ohio.gov/about-us/documents/access-to-recovery",
    eligibility="Criminal justice-involved adults and veterans in recovery in participating counties: Columbiana, Cuyahoga, Franklin, Hamilton, Lorain, Mahoning, Montgomery, Stark, and Summit.",
    eligibility_es="Adultos con antecedentes penales y veteranos en recuperación en condados participantes: Columbiana, Cuyahoga, Franklin, Hamilton, Lorain, Mahoning, Montgomery, Stark y Summit.",
    notes="Contact an ATR care coordinator at a participating agency in your county; see OhioMHAS page for provider list.",
    notes_es="Contacte un coordinador ATR en una agencia participante de su condado; consulte la página de OhioMHAS.",
    hours="Contact participating agency for hours",
    tags="statewide|substance-use|recovery|veterans|vouchers",
    services="Recovery housing vouchers|Transportation assistance|Employment skills training|Peer recovery support",
    county="Franklin", latitude="39.9625", longitude="-82.9988",
    served_counties="Columbiana|Cuyahoga|Franklin|Hamilton|Lorain|Mahoning|Montgomery|Stark|Summit", coverage="multi",
    _source="https://mha.ohio.gov/about-us/documents/access-to-recovery", _source_type="government", _confidence="high",
)
add(
    name="SAMHSA National Helpline",
    category="substance-use-treatment", region="Statewide",
    description="Free confidential 24/7 treatment referral and information service for individuals and families facing mental health or substance use disorders. Provides referrals to local treatment facilities and community organizations in Ohio and nationwide.",
    description_es="Servicio gratuito y confidencial 24/7 de referencia e información para personas y familias con trastornos de salud mental o uso de sustancias. Proporciona referencias a centros de tratamiento locales en Ohio y a nivel nacional.",
    address="", city="", phone="1-800-662-4357", email="", website="https://www.samhsa.gov/find-help/national-helpline",
    eligibility="Open to anyone in the United States seeking substance use or mental health treatment information and referrals.",
    eligibility_es="Abierto a cualquier persona en Estados Unidos que busque información y referencias de tratamiento.",
    notes="TTY: 1-800-487-4889; also use FindTreatment.gov to search Ohio providers online.",
    notes_es="TTY: 1-800-487-4889; también use FindTreatment.gov para buscar proveedores en Ohio.",
    hours="Available 24/7",
    tags="statewide|hotline|substance-use|treatment-referral|national",
    services="Treatment referrals|Substance use information|Mental health resource navigation",
    county="", latitude="", longitude="", served_counties="", coverage="statewide",
    _source="https://www.samhsa.gov/find-help/national-helpline", _source_type="government", _confidence="high",
)
add(
    name="FindTreatment.gov — Ohio Provider Search",
    category="substance-use-treatment", region="Statewide",
    description="Official SAMHSA online locator for substance use and mental health treatment facilities serving Ohio. Users search by location, treatment type, and payment options to find licensed providers with current openings.",
    description_es="Localizador oficial en línea de SAMHSA para centros de tratamiento de sustancias y salud mental que sirven a Ohio. Los usuarios buscan por ubicación, tipo de tratamiento y opciones de pago.",
    address="", city="", phone="1-833-888-1553", email="FindTreatment@samhsa.hhs.gov",
    website="https://findtreatment.gov",
    eligibility="Open to anyone seeking treatment; facility admission requirements vary by provider.",
    eligibility_es="Abierto a cualquier persona que busque tratamiento; los requisitos de admisión varían según el proveedor.",
    notes="Ohio does not have a dedicated FindHelpNow portal; use this SAMHSA tool instead. Facility updates weekly.",
    notes_es="Ohio no tiene portal FindHelpNow dedicado; use esta herramienta de SAMHSA.",
    hours="Online 24/7; BHSIS support Mon–Fri 8 a.m.–6 p.m. ET",
    tags="statewide|substance-use|online|treatment-referral",
    services="Treatment facility search|Provider availability information|Mental health provider locator",
    county="", latitude="", longitude="", served_counties="", coverage="statewide",
    _source="https://findtreatment.gov", _source_type="government", _confidence="high",
)

# --- Deduplicated reentry coalitions (ODRC PDF 4/20/26) ---
COALITIONS = [
    dict(name="Southeast Ohio Reentry Coalition", region="Southeast Ohio — 6 counties",
         phone="(740) 727-4801", email="seorc6@gmail.com", county="Adams",
         served="Adams|Brown|Jackson|Lawrence|Pike|Scioto",
         notes="Networking coalition covering six Appalachian counties; contact coordinator Maxine Malone for partner referrals."),
    dict(name="Reentry Coalition of Allen County", region="Allen / Auglaize / Hardin",
         phone="(937) 528-6409", email="aahc.reentry@gesmv.org", county="Allen",
         served="Allen|Auglaize|Hardin", address="660 South Main Street", city="Lima",
         lat="40.7389", lon="-84.1054",
         notes="Hosted by Goodwill Easterseals Miami Valley; contact Jen Bonifas for coalition meetings."),
    dict(name="Route 11 Reentry Coalition", region="Northeast Ohio — 5 counties",
         phone="(330) 743-3700", email="route11reentrycoalition@gmail.com", county="Ashtabula",
         served="Ashtabula|Columbiana|Jefferson|Mahoning|Trumbull",
         notes="Led by Home for Good; contact Lola Simmons. Networking council—not a direct-service provider."),
    dict(name="Athens & Meigs County Reentry Coalition", region="Athens / Meigs",
         phone="(740) 677-4232", email="reentry@jfs.ohio.gov", county="Athens",
         served="Athens|Meigs", address="13183 State Route 13", city="Millfield",
         notes="Coordinated through Athens County Job and Family Services; contact Shawn Stover."),
    dict(name="Butler Warren Reentry Coalition", region="Butler / Warren",
         phone="(513) 229-7947", email="reentry@thefourseven.org", county="Butler",
         served="Butler|Warren",
         notes="Hosted by The FourSeven; contact Kim Elliott for coalition information."),
    dict(name="Stark Carroll County Reentry Coalition", region="Stark / Carroll",
         phone="(234) 458-4501", email="screentrycoalition23@gmail.com", county="Stark",
         served="Carroll|Stark", city="Canton",
         notes="Contact Shauntae Metcalf; coalition connects returning citizens to local services."),
    dict(name="Bridges Reentry Coalition", region="Champaign / Logan / Shelby",
         phone="(937) 617-4217", email="receptionist@bridgesap.org", county="Champaign",
         served="Champaign|Logan|Shelby", address="1512 South U.S. Highway 68", city="Urbana",
         lat="40.1084", lon="-83.7524",
         notes="Hosted by Bridges Community Action Partnership; contact Marie Radcliff."),
    dict(name="Coshocton County Reentry Coalition", region="Coshocton",
         phone="(740) 622-4470", email="coshcoreentry@gmail.com", county="Coshocton",
         served="Coshocton", city="Coshocton",
         notes="Contact Rachelle Courtwright at Allwell Behavioral Health Services."),
    dict(name="Delaware County Reentry Coalition", region="Delaware",
         phone="(740) 856-0145", email="Delawarecountyrc@southeastinc.com", county="Delaware",
         served="Delaware", city="Delaware",
         notes="Hosted by Southeast Healthcare; contact Victoria Dimick."),
    dict(name="Fairfield County Reentry Coalition", region="Fairfield",
         phone="", email="info@connexionwest.org", county="Fairfield",
         served="Fairfield", city="Lancaster",
         notes="Contact Burbridge Cook at Connexion West; verify current phone on website."),
    dict(name="Franklin County Reentry Advisory Board", region="Columbus / Franklin County",
         phone="(614) 525-5955", email="reentryojpp@franklincountyohio.gov", county="Franklin",
         served="Franklin", address="373 South High Street", city="Columbus", lat="39.9590", lon="-82.9987",
         notes="Part of Franklin County Office of Justice Policy and Programs; contact Shana Sanders."),
    dict(name="Northeast Ohio Reentry Coalition", region="Geauga County",
         phone="(440) 479-9930", email="reentry@familyprideonline.org", county="Geauga",
         served="Geauga", city="Chardon",
         notes="Geauga County Reentry Collaboration via Family Pride; contact Angela Daugherty."),
    dict(name="Hamilton County Reentry Coalition", region="Cincinnati / Hamilton County",
         phone="(513) 946-4304", email="reentry@hamiltoncountyohio.gov", county="Hamilton",
         served="Hamilton", address="230 East Ninth Street", city="Cincinnati", lat="39.1067", lon="-84.5047",
         notes="Hamilton County Office of Reentry; contact Director Trina Jackson for intake."),
    dict(name="Hancock County Reentry Coalition", region="Hancock",
         phone="(419) 455-6082", email="admin@welcometoanewlife.org", county="Hancock",
         served="Hancock", city="Findlay",
         notes="Welcome to a New Life; contact Carla Benjamin."),
    dict(name="Henry–Putnam County Reentry Coalition", region="Henry / Putnam",
         phone="(419) 296-4397", email="henrycountyreentry@gmail.com", county="Henry",
         served="Henry|Putnam", city="Gilboa",
         notes="Contact Kathy Kaufman at Gilboa UMC for coalition meetings."),
    dict(name="Wayne / Holmes County Reentry Coalition", region="Wayne / Holmes",
         phone="(330) 264-9597", email="Reentry@anazaocommunitypartners.org", county="Wayne",
         served="Wayne|Holmes", city="Wooster",
         notes="Hosted by Anazao Community Partners; contact Matt Hankins."),
    dict(name="Huron County Reentry Coalition", region="Huron",
         phone="(440) 781-2915", email="huroncorrcoalition@gmail.com", county="Huron",
         served="Huron", city="Norwalk",
         notes="Contact Ryan Williams at Goodwill Sandusky."),
    dict(name="Lake County Reentry Coalition", region="Lake",
         phone="(440) 354-2148", email="mail@reentrylakeoh.org", county="Lake",
         served="Lake", city="Painesville",
         notes="Coordinated by Lifeline Inc.; contact Samantha Allen, ext. 227."),
    dict(name="Licking County Reentry Coalition", region="Licking",
         phone="(740) 670-4267", email="lickingcountyreentrycoalition@gmail.com", county="Licking",
         served="Licking", city="Newark",
         notes="Contact Stephanie Dunlap at Licking County Alcohol Prevention Program."),
    dict(name="Reentry Coalition of Northwest Ohio", region="Lucas / Toledo",
         phone="(419) 241-3235", email="reentry419@gmail.com", county="Lucas",
         served="Lucas", city="Toledo", lat="41.6528", lon="-83.5379",
         notes="Contact Karyn McConnell for coalition partner referrals."),
    dict(name="Central Ohio Restored Citizens Collaborative", region="Madison / Union",
         phone="(614) 733-4348", email="corccinfo@gmail.com", county="Madison",
         served="Madison|Union", city="London",
         notes="Networking collaborative for restored citizens; contact Cheri Alcantar."),
    dict(name="Mid-Ohio Reentry Coalition", region="Crawford / Marion",
         phone="(567) 296-4644", email="reentrycoalition@mcadamh.com", county="Crawford",
         served="Crawford|Marion", city="Bucyrus",
         notes="Hosted by Crawford-Marion ADAMH Board; contact Jamie Ervin."),
    dict(name="Summit, Portage & Medina Reentry Coalition", region="Summit / Portage / Medina",
         phone="(330) 289-9234", email="reentry@summitoh.net", county="Summit",
         served="Medina|Portage|Summit", city="Akron", lat="41.0814", lon="-81.5190",
         notes="South Street Ministries and Summit County ISC Reentry Collaborative; contact Joe Tucker."),
    dict(name="Mercer County Reentry Coalition", region="Mercer",
         phone="(260) 519-0688", email="reentry@grandlakechurch.org", county="Mercer",
         served="Mercer", city="Celina",
         notes="Grand Lake UMC; contact Alison Sorenson."),
    dict(name="Muskingum Perry Morgan Community Reentry Coalition (Project Ready)", region="Muskingum / Perry / Morgan",
         phone="(740) 647-9791", email="info@projectready.net", county="Muskingum",
         served="Morgan|Muskingum|Perry", address="2845 Bell Street", city="Zanesville",
         lat="39.9403", lon="-82.0132",
         notes="Project Ready provides direct reentry navigation plus coalition networking; contact Kuwan Mayle."),
    dict(name="Reentry toMorrow", region="Morrow",
         phone="(740) 856-0145", email="morrowcountyrc@southeastinc.com", county="Morrow",
         served="Morrow", city="Mount Gilead",
         notes="Southeast Healthcare; contact Victoria Dimick."),
    dict(name="Pickaway County Office of Reentry", region="Pickaway",
         phone="(740) 477-1745", email="reentry@parsohio.org", county="Pickaway",
         served="Pickaway", city="Circleville",
         notes="Pickaway Area Recovery Services; contact Danielle Hurff."),
    dict(name="Richland County Reentry Coalition", region="Richland",
         phone="(419) 528-5993", email="rcrc@healingheartscc.com", county="Richland",
         served="Richland", city="Mansfield",
         notes="Healing Hearts Community Center; contact Amanda Jones, ext. 137."),
    dict(name="Ross County Reentry Coalition", region="Ross",
         phone="(740) 466-5676", email="rosscountyreentrycoalition@gmail.com", county="Ross",
         served="Ross", city="Chillicothe",
         notes="Contact Brandy Morris-Hafner for coalition partner referrals."),
]

for c in COALITIONS:
    sc = c["served"]
    cov = "single" if "|" not in sc else "multi"
    is_direct = "Project Ready" in c["name"] or "Office of Reentry" in c["name"]
    desc_en = (
        f"Local reentry coalition serving {sc.replace('|', ', ')} counties in Ohio. "
        + ("Staff provide direct reentry navigation, case coordination, and community referrals for returning citizens."
           if is_direct else
           "Volunteers and partner agencies coordinate resources and referrals for justice-involved individuals—primarily a networking council, not a full-service provider.")
    )
    desc_es = (
        f"Coalición local de reinserción que sirve los condados {sc.replace('|', ', ')} en Ohio. "
        + ("El personal ofrece navegación directa, coordinación de casos y referencias comunitarias."
           if is_direct else
           "Voluntarios y aliados coordinan recursos y referencias—principalmente un consejo de red, no un proveedor de servicios completos.")
    )
    add(
        name=c["name"], category="reentry-organizations", region=c["region"],
        description=desc_en, description_es=desc_es,
        address=c.get("address", ""), city=c.get("city", ""),
        phone=c["phone"], email=c["email"],
        website="https://drc.ohio.gov/systems-and-services/2-reentry-services/reentry-coalitions",
        eligibility="Justice-involved residents of served counties; contact coalition for current partner eligibility.",
        eligibility_es="Residentes con antecedentes penales en los condados servidos; contacte la coalición.",
        notes=c["notes"] + " Does not provide emergency housing or crisis response.",
        notes_es=c["notes"] + " No ofrece vivienda de emergencia ni respuesta de crisis.",
        hours="Contact for meeting dates and hours",
        tags=f"reentry|coalition|{'direct-service' if is_direct else 'referral-only'}|{c['county'].lower()}",
        services=("Reentry case navigation|Housing referrals|Employment referrals|Treatment referrals"
                  if is_direct else "Resource networking|Community partner referrals|Coalition meetings|Local reentry navigation"),
        county=c["county"], latitude=c.get("lat", ""), longitude=c.get("lon", ""),
        served_counties=sc if cov == "multi" else (sc if sc else c["county"]),
        coverage=cov,
        _source="https://dam.assets.ohio.gov/image/upload/drc.ohio.gov/Forms/Reentry_Coalitions_4-20-26.pdf",
        _source_type="government", _confidence="high" if c["phone"] else "medium",
    )

# Clark & Montgomery county offices (distinct from coalition-only rows where applicable)
add(
    name="Clark County Department of Reentry",
    category="reentry-organizations", region="Springfield / Clark County",
    description="County reentry department coordinating services for justice-involved Clark County residents including referrals to housing, employment, treatment, and ID assistance. Works with the Clark County Reentry Coalition and community partners.",
    description_es="Departamento de reinserción del condado que coordina servicios para residentes de Clark con antecedentes penales incluyendo referencias a vivienda, empleo, tratamiento e identificación.",
    address="50 East Columbia Street", city="Springfield", phone="(937) 398-9393",
    email="reentry@clarkcountyohio.gov", website="https://www.clarkcountyohio.gov",
    eligibility="Clark County residents who are justice-involved or recently released; contact for intake requirements.",
    eligibility_es="Residentes de Clark con antecedentes penales o recién liberados; contacte para requisitos.",
    notes="Contact Brooke Wagner for intake; coalition email reentry@clarkcountyohio.gov.",
    notes_es="Contacte a Brooke Wagner para admisión.",
    hours="Monday–Friday, 8:00 a.m.–4:30 p.m.",
    tags="clark|reentry|county-government|direct-service",
    services="Reentry case coordination|Housing referrals|Employment referrals|ID assistance referrals",
    county="Clark", latitude="39.9242", longitude="-83.8088", served_counties="Clark", coverage="single",
    _source="https://dam.assets.ohio.gov/image/upload/drc.ohio.gov/Forms/Reentry_Coalitions_4-20-26.pdf",
    _source_type="government", _confidence="high",
)
add(
    name="Montgomery County Office of Reentry",
    category="reentry-organizations", region="Dayton / Montgomery County",
    description="County office connecting returning citizens in Montgomery and surrounding counties to housing, employment, benefits, healthcare, and legal services. Provides individualized reentry navigation and partner referrals for people leaving incarceration.",
    description_es="Oficina del condado que conecta a ciudadanos que regresan en Montgomery y condados circundantes con vivienda, empleo, beneficios, salud y servicios legales.",
    address="451 West Third Street", city="Dayton", phone="(937) 225-6460",
    email="mcreentry@mcohio.org", website="https://www.mcohio.org/government/departments/reentry",
    eligibility="Justice-involved residents of Montgomery, Darke, Greene, Miami, and Preble counties.",
    eligibility_es="Residentes con antecedentes penales de Montgomery, Darke, Greene, Miami y Preble.",
    notes="Contact Jamie Gee (community manager) or Quinn Howard (program manager) for intake.",
    notes_es="Contacte a Jamie Gee o Quinn Howard para admisión.",
    hours="Monday–Friday, 8:00 a.m.–4:30 p.m.",
    tags="montgomery|reentry|county-government|multi-county",
    services="Reentry navigation|Housing referrals|Employment support|Benefits enrollment assistance|Expungement clinic referrals",
    county="Montgomery", latitude="39.7589", longitude="-84.1916",
    served_counties="Darke|Greene|Miami|Montgomery|Preble", coverage="multi",
    _source="https://dam.assets.ohio.gov/image/upload/drc.ohio.gov/Forms/Reentry_Coalitions_4-20-26.pdf",
    _source_type="government", _confidence="high",
)

# --- Regional legal aids ---
LEGAL_AIDS = [
    dict(name="Legal Aid Society of Cleveland", region="Northeast Ohio — 5 counties",
         phone="888-817-3777", website="https://lasclev.org", address="1223 West Sixth Street", city="Cleveland",
         county="Cuyahoga", lat="41.4987", lon="-81.6998",
         served="Ashtabula|Cuyahoga|Geauga|Lake|Lorain",
         desc="Provides free civil legal aid including record sealing, housing, benefits, and employment issues for low-income residents in five northeast Ohio counties."),
    dict(name="Legal Aid of Southeast and Central Ohio (LASCO)", region="Southeast / Central Ohio — 36 counties",
         phone="1-888-246-4420", website="https://www.lasco.org", address="1108 City Park Avenue, Suite 200", city="Columbus",
         county="Franklin", lat="39.9400", lon="-82.9900", served="",
         desc="Free noncriminal legal help for low-income people, seniors, and veterans across 36 southeast and central Ohio counties including record sealing and expungement."),
    dict(name="Legal Aid Society of Southwest Ohio", region="Cincinnati / Southwest Ohio",
         phone="1-800-582-2682", website="https://lascinti.org", address="215 East Ninth Street", city="Cincinnati",
         county="Hamilton", lat="39.1050", lon="-84.5080", served="Hamilton|Butler|Clermont|Warren|Brown|Adams|Highland",
         desc="Free civil legal assistance for low-income residents in southwest Ohio including housing, family, employment, and criminal record relief."),
    dict(name="Legal Aid of Western Ohio (LAWO)", region="Western Ohio — 32 counties",
         phone="1-888-534-1432", website="https://www.lawolaw.org", address="525 Jefferson Avenue", city="Toledo",
         county="Lucas", lat="41.6520", lon="-83.5370", served="",
         desc="Free civil legal services for low-income residents across 32 western Ohio counties including record sealing assistance and housing defense."),
    dict(name="Community Legal Aid — Akron", region="Northeast Ohio — 8 counties",
         phone="1-800-998-9454", website="https://www.communitylegalaid.org", address="50 South Main Street", city="Akron",
         county="Summit", lat="41.0810", lon="-81.5180",
         served="Carroll|Holmes|Medina|Portage|Stark|Summit|Tuscarawas|Wayne",
         desc="Free civil legal aid for low-income residents in eight northeast Ohio counties including expungement clinics and reentry legal support."),
]
for la in LEGAL_AIDS:
    cov = "statewide" if not la["served"] else ("single" if "|" not in la["served"] else "multi")
    if la["name"] == "Legal Aid of Southeast and Central Ohio (LASCO)":
        cov = "multi"
        la["served"] = "Adams|Athens|Belmont|Brown|Butler|Carroll|Champaign|Clark|Clermont|Clinton|Coshocton|Fairfield|Fayette|Franklin|Gallia|Greene|Guernsey|Hamilton|Harrison|Highland|Hocking|Jackson|Knox|Lawrence|Licking|Madison|Meigs|Miami|Monroe|Morgan|Muskingum|Perry|Pickaway|Pike|Ross|Scioto|Vinton|Warren|Washington"
    if la["name"] == "Legal Aid of Western Ohio (LAWO)":
        cov = "multi"
        la["served"] = "Allen|Auglaize|Champaign|Clark|Darke|Defiance|Erie|Fulton|Hardin|Henry|Hancock|Huron|Logan|Lucas|Marion|Mercer|Miami|Ottawa|Paulding|Putnam|Richland|Sandusky|Seneca|Shelby|Van Wert|Williams|Wood|Wyandot"
    add(
        name=la["name"], category="legal-aid", region=la["region"],
        description=la["desc"] + " Income and household-size limits apply.",
        description_es=la["desc"].replace("Provides", "Proporciona").replace("Free", "Gratuita") + " Aplican límites de ingresos.",
        address=la["address"], city=la["city"], phone=la["phone"], email="", website=la["website"],
        eligibility="Low-income Ohio residents in service area; veterans and seniors may qualify with higher income limits. Criminal record relief eligibility varies by offense.",
        eligibility_es="Residentes de bajos ingresos en el área de servicio; veteranos y personas mayores pueden calificar. La elegibilidad para alivio de antecedentes varía.",
        notes="Apply online or call intake line; record sealing clinics offered in many counties.",
        notes_es="Solicite en línea o llame a la línea de admisión; clínicas de sellado de antecedentes en muchos condados.",
        hours="Intake Monday–Friday mornings; call for appointment",
        tags="legal-aid|expungement|low-income|reentry",
        services="Record sealing assistance|Expungement help|Housing legal aid|Benefits advocacy|Civil legal representation",
        county=la["county"], latitude=la["lat"], longitude=la["lon"],
        served_counties=la["served"], coverage=cov,
        _source=la["website"], _source_type="nonprofit", _confidence="high",
    )

# --- CEOs ---
for city, county, phone, addr, lat, lon, web in [
    ("Columbus", "Franklin", "(614) 725-9210", "3220 West Broad Street", "39.9550", "-83.0890", "https://ceoworks.org/columbus"),
    ("Cleveland", "Cuyahoga", "(216) 696-5750", "2421 Superior Avenue", "41.5030", "-81.6920", "https://ceoworks.org/cleveland"),
    ("Cincinnati", "Hamilton", "(513) 651-2000", "1814 Young Street", "39.1200", "-84.5200", "https://ceoworks.org/cincinnati"),
]:
    add(
        name=f"Center for Employment Opportunities (CEO) — {city}",
        category="employment", region=f"{city} metro",
        description=f"National fair-chance employment program with a {city} office providing paid transitional work, job coaching, and retention support for people recently released from incarceration. CEO connects participants to permanent employment with partner employers.",
        description_es=f"Programa nacional de empleo de segunda oportunidad con oficina en {city} que ofrece trabajo transicional remunerado, coaching laboral y apoyo de retención para personas recién liberadas.",
        address=addr, city=city, phone=phone, email="", website=web,
        eligibility="Recently incarcerated adults within days of release or on parole/probation; contact local office for enrollment windows.",
        eligibility_es="Adultos recién encarcelados cerca de la liberación o en libertad condicional; contacte la oficina local.",
        notes="Apply through local CEO office; enrollment often tied to release date and referral partners.",
        notes_es="Solicite a través de la oficina local de CEO.",
        hours="Monday–Friday business hours",
        tags="employment|fair-chance|reentry|transitional-jobs|ceo",
        services="Paid transitional work|Job coaching|Job placement|Retention support|Life skills training",
        county=county, latitude=lat, longitude=lon, served_counties=county, coverage="single",
        _source=web, _source_type="nonprofit", _confidence="high",
    )

# --- Major metro reentry programs ---
add(
    name="Cuyahoga County Office of Reentry",
    category="reentry-organizations", region="Cleveland / Cuyahoga County",
    description="County office coordinating reentry services for Cuyahoga County residents including North Star NRRC oversight, employment workshops, benefits assistance, and partner referrals for returning citizens.",
    description_es="Oficina del condado que coordina servicios de reinserción para residentes de Cuyahoga incluyendo supervisión de North Star NRRC, talleres de empleo y asistencia de beneficios.",
    address="1215 Ansel Road", city="Cleveland", phone="(216) 698-3437",
    email="Cuyahoga-Reentry@jfs.ohio.gov", website="https://hhs.cuyahogacounty.gov/departments/office-of-reentry",
    eligibility="Cuyahoga County residents who are justice-involved or recently released.",
    eligibility_es="Residentes de Cuyahoga con antecedentes penales o recién liberados.",
    notes="Funds and oversees North Star NRRC; contact for county reentry program referrals.",
    notes_es="Financia y supervisa North Star NRRC.",
    hours="Monday–Friday, 8:00 a.m.–4:30 p.m.",
    tags="cuyahoga|cleveland|reentry|county-government",
    services="Reentry program coordination|North Star NRRC oversight|Employment workshop referrals|Benefits navigation",
    county="Cuyahoga", latitude="41.5080", longitude="-81.6370", served_counties="Cuyahoga", coverage="single",
    _source="https://hhs.cuyahogacounty.gov/departments/office-of-reentry", _source_type="government", _confidence="high",
)
add(
    name="North Star Neighborhood Reentry Resource Center (NRRC)",
    category="reentry-organizations", region="Cleveland / Cuyahoga County",
    description="One-stop reentry resource center operated by Oriana House and funded by Cuyahoga County. Offers employment classes, GED support, ID and birth certificate vouchers, benefits enrollment, clothing closet, and referrals to community partners for returning citizens.",
    description_es="Centro integral de recursos de reinserción operado por Oriana House y financiado por el condado de Cuyahoga. Ofrece clases de empleo, apoyo GED, vales para identificación, inscripción en beneficios y referencias.",
    address="1834 East 55th Street", city="Cleveland", phone="(216) 881-5440",
    email="NorthStarReentry@orianahouse.org", website="https://www.northstarreentry.org",
    eligibility="Cuyahoga County residents who are formerly incarcerated or involved in the criminal justice system; family members may access some services.",
    eligibility_es="Residentes de Cuyahoga anteriormente encarcelados o en el sistema de justicia penal; familiares pueden acceder a algunos servicios.",
    notes="Free membership required; walk-in welcome during open hours. Also an ATR participating agency.",
    notes_es="Se requiere membresía gratuita; visitas sin cita durante horario de atención.",
    hours="Monday–Friday, 8:00 a.m.–8:00 p.m.; Saturday, 9:00 a.m.–1:00 p.m.",
    tags="cuyahoga|cleveland|reentry|direct-service|one-stop",
    services="Employment readiness workshops|GED classes|ID and birth certificate vouchers|Benefits enrollment|Clothing closet|Computer training",
    county="Cuyahoga", latitude="41.5095", longitude="-81.6510", served_counties="Cuyahoga", coverage="single",
    _source="https://www.northstarreentry.org", _source_type="nonprofit", _confidence="high",
)
add(
    name="Franklin County Office of Justice Policy and Programs — Reentry",
    category="reentry-organizations", region="Columbus / Franklin County",
    description="Franklin County government office leading reentry policy and direct navigation for returning citizens including the Reentry Advisory Board, benefits connections, and partnerships with Columbus reentry providers.",
    description_es="Oficina del gobierno del condado de Franklin que lidera políticas de reinserción y navegación directa para ciudadanos que regresan incluyendo la Junta Asesora de Reinserción.",
    address="373 South High Street", city="Columbus", phone="(614) 525-5955",
    email="reentryojpp@franklincountyohio.gov", website="https://www.franklincountyohio.gov/Departments/Office-of-Justice-Policy-and-Programs",
    eligibility="Franklin County justice-involved residents seeking county reentry navigation.",
    eligibility_es="Residentes de Franklin con antecedentes penales que buscan navegación de reinserción del condado.",
    notes="Contact Shana Sanders, Reentry Coordinator; works with Alvis, CEO Columbus, and legal aid partners.",
    notes_es="Contacte a Shana Sanders, coordinadora de reinserción.",
    hours="Monday–Friday, 8:00 a.m.–4:30 p.m.",
    tags="franklin|columbus|reentry|county-government",
    services="Reentry navigation|Policy coordination|Advisory board meetings|Partner agency referrals",
    county="Franklin", latitude="39.9590", longitude="-82.9987", served_counties="Franklin", coverage="single",
    _source="https://www.franklincountyohio.gov/Departments/Office-of-Justice-Policy-and-Programs", _source_type="government", _confidence="high",
)
add(
    name="Hamilton County Fresh Start Expungement Clinic",
    category="legal-aid", region="Cincinnati / Hamilton County",
    description="Free expungement and record-sealing clinic operated by the Hamilton County Public Defender's Office. Staff help eligible individuals determine record relief options and prepare sealing applications.",
    description_es="Clínica gratuita de eliminación y sellado de antecedentes operada por la Oficina del Defensor Público del condado de Hamilton.",
    address="125 East Court Street, 9th Floor", city="Cincinnati", phone="(513) 946-3666",
    email="", website="https://www.hamiltoncountypd.org/fresh-start/",
    eligibility="Hamilton County residents with qualifying criminal records for sealing or expungement; offense-type and waiting-period rules apply.",
    eligibility_es="Residentes de Hamilton con antecedentes elegibles para sellado o eliminación; aplican reglas de tipo de delito.",
    notes="Obtain criminal record from Sheriff's Office ($5) before clinic; schedule online or call 8:30–11:30 a.m. on clinic dates.",
    notes_es="Obtenga antecedentes penales de la Oficina del Sheriff ($5) antes de la clínica.",
    hours="Clinic 1:00–4:00 p.m. twice monthly; call for schedule",
    tags="hamilton|cincinnati|expungement|legal-aid|clinic",
    services="Expungement eligibility screening|Record sealing assistance|Application preparation",
    county="Hamilton", latitude="39.1030", longitude="-84.5120", served_counties="Hamilton", coverage="single",
    _source="https://www.hamiltoncountypd.org/fresh-start/", _source_type="government", _confidence="high",
)
add(
    name="Ohio Justice and Policy Center — Second Chance Community Legal Clinic",
    category="legal-aid", region="Cincinnati / Hamilton County",
    description="Free legal clinic helping justice-involved Ohioans remove criminal record barriers beyond expungement including CQE assistance, driver's license reinstatement, and civil legal issues arising from a criminal record.",
    description_es="Clínica legal gratuita que ayuda a personas con antecedentes penales a eliminar barreras más allá de la eliminación de antecedentes incluyendo CQE y restablecimiento de licencia de conducir.",
    address="215 East Ninth Street", city="Cincinnati", phone="(513) 421-1108",
    email="secondchance@ohiojpc.org", website="https://www.ohiojpc.org",
    eligibility="Justice-involved individuals in the Cincinnati region; walk-in clinics open to qualifying cases assessed case-by-case.",
    eligibility_es="Personas con antecedentes penales en la región de Cincinnati; clínicas sin cita para casos evaluados individualmente.",
    notes="Walk-in community legal clinics throughout Cincinnati region; email secondchance@ohiojpc.org for schedule.",
    notes_es="Clínicas legales comunitarias sin cita en la región de Cincinnati.",
    hours="Walk-in clinic hours vary; contact for schedule",
    tags="hamilton|cincinnati|legal-aid|CQE|second-chance",
    services="CQE assistance|Driver's license reinstatement|Criminal record barrier relief|Community legal clinics",
    county="Hamilton", latitude="39.1050", longitude="-84.5080", served_counties="Hamilton", coverage="single",
    _source="https://www.hamiltoncountypd.org/fresh-start/other-legal-options/", _source_type="nonprofit", _confidence="high",
)
add(
    name="Opportunity Port",
    category="legal-aid", region="Statewide",
    description="Online portal connecting Ohio residents with free legal help to seal or expunge criminal records. Users complete a survey and are matched with a service provider such as legal aid, OSU Moritz College of Law, or municipal court self-help centers.",
    description_es="Portal en línea que conecta a residentes de Ohio con ayuda legal gratuita para sellar o eliminar antecedentes penales. Los usuarios completan una encuesta y se emparejan con un proveedor de servicios.",
    address="", city="Columbus", phone="", email="",
    website="https://opportunityport.org",
    eligibility="Ohio residents seeking to seal or expunge an Ohio arrest, dismissal, or conviction; income limits may apply at some partner providers.",
    eligibility_es="Residentes de Ohio que buscan sellar o eliminar un arresto, desestimación o condena en Ohio; algunos proveedores tienen límites de ingresos.",
    notes="Start at opportunityport.org survey; appointments conducted by phone; partner list includes LASCO and OSU Moritz DEPC.",
    notes_es="Comience en opportunityport.org; citas por teléfono.",
    hours="Online survey available 24/7",
    tags="statewide|expungement|online|legal-aid|second-chance",
    services="Record sealing application assistance|Expungement eligibility screening|Legal provider matching",
    county="", latitude="", longitude="", served_counties="", coverage="statewide",
    _source="https://www.ohiolegalhelp.org/resource/opportunity-port", _source_type="nonprofit", _confidence="high",
)
add(
    name="Ohio Justice and Policy Center (OJPC)",
    category="legal-aid", region="Cincinnati / Southwest Ohio",
    description="Nonprofit law and policy organization advocating for criminal justice reform and providing legal services for record relief, reentry barriers, and civil rights for justice-involved Ohioans.",
    description_es="Organización sin fines de lucro de derecho y política que defiende la reforma de justicia penal y ofrece servicios legales para alivio de antecedentes y barreras de reinserción.",
    address="215 East Ninth Street", city="Cincinnati", phone="(513) 421-1108",
    email="info@ohiojpc.org", website="https://www.ohiojpc.org",
    eligibility="Justice-involved individuals in Ohio; program-specific eligibility for clinics and representation.",
    eligibility_es="Personas con antecedentes penales en Ohio; elegibilidad específica por programa.",
    notes="See Second Chance Community Legal Clinic for walk-in services; policy advocacy separate from direct legal intake.",
    notes_es="Consulte la Clínica Legal Comunitaria Second Chance para servicios sin cita.",
    hours="Monday–Friday business hours",
    tags="cincinnati|legal-aid|policy|reentry|second-chance",
    services="Policy advocacy|Record relief legal services|Reentry legal clinics|Civil rights representation",
    county="Hamilton", latitude="39.1050", longitude="-84.5080", served_counties="", coverage="statewide",
    _source="https://www.ohiojpc.org", _source_type="nonprofit", _confidence="high",
)

# --- Veterans ---
add(
    name="VA Veterans Justice Outreach (VJO) Program",
    category="veterans", region="Statewide",
    description="National VA program with specialists in Ohio who connect justice-involved veterans to VA benefits, treatment, housing, and reentry supports. VJO staff work with courts, jails, and prisons to link veterans to services before and after release.",
    description_es="Programa nacional del VA con especialistas en Ohio que conectan a veteranos con antecedentes penales con beneficios del VA, tratamiento, vivienda y apoyo de reinserción.",
    address="", city="", phone="1-877-222-8387", email="",
    website="https://www.va.gov/homeless/vjo.asp",
    eligibility="U.S. military veterans involved in the criminal justice system; discharge status requirements vary for specific VA benefits.",
    eligibility_es="Veteranos de las fuerzas armadas de EE.UU. en el sistema de justicia penal; los requisitos de baja varían para beneficios específicos del VA.",
    notes="Call VA main line and ask for local VJO specialist; each VA medical center has outreach staff.",
    notes_es="Llame a la línea principal del VA y pida al especialista VJO local.",
    hours="Contact local VJO specialist for hours",
    tags="veterans|statewide|VJO|justice-involved",
    services="VA benefits navigation|Treatment referrals|Housing referrals|Court and jail outreach",
    county="", latitude="", longitude="", served_counties="", coverage="statewide",
    _source="https://www.va.gov/homeless/vjo.asp", _source_type="government", _confidence="high",
)
add(
    name="Louis Stokes Cleveland VA — Veterans Justice Outreach",
    category="veterans", region="Cleveland / Northeast Ohio",
    description="VA Veterans Justice Outreach specialists at the Louis Stokes Cleveland VA Medical Center connect northeast Ohio justice-involved veterans to VA health care, benefits, housing, and reentry services.",
    description_es="Especialistas de Veterans Justice Outreach en el Centro Médico VA Louis Stokes Cleveland conectan a veteranos del noreste de Ohio con atención médica, beneficios, vivienda y servicios de reinserción del VA.",
    address="10701 East Boulevard", city="Cleveland", phone="(216) 791-3800",
    email="", website="https://www.va.gov/cleveland-health-care/",
    eligibility="Justice-involved veterans in northeast Ohio; VA eligibility rules apply for medical and benefits services.",
    eligibility_es="Veteranos con antecedentes penales en el noreste de Ohio; aplican reglas de elegibilidad del VA.",
    notes="Ask for Veterans Justice Outreach when calling; VJO works with county jails and courts.",
    notes_es="Pida Veterans Justice Outreach al llamar.",
    hours="Monday–Friday business hours",
    tags="veterans|cleveland|cuyahoga|VJO",
    services="VJO case coordination|VA health care enrollment|Benefits assistance|Reentry referrals",
    county="Cuyahoga", latitude="41.5085", longitude="-81.6195", served_counties="Cuyahoga", coverage="single",
    _source="https://www.va.gov/homeless/vjo.asp", _source_type="government", _confidence="high",
)
add(
    name="VA Health Care for Reentry Veterans (HCRV)",
    category="veterans", region="Statewide",
    description="Statewide VA program helping incarcerated veterans plan for reentry with pre-release assessments and connecting them to VA medical care, benefits, and housing upon release. Available to veterans in Ohio prisons and jails.",
    description_es="Programa estatal del VA que ayuda a veteranos encarcelados a planificar la reinserción con evaluaciones previas a la liberación y conexión a atención médica, beneficios y vivienda del VA.",
    address="", city="", phone="1-877-222-8387", email="",
    website="https://www.va.gov/homeless/hcrv.asp",
    eligibility="Incarcerated U.S. military veterans in Ohio correctional facilities; VA eligibility requirements apply.",
    eligibility_es="Veteranos encarcelados de las fuerzas armadas de EE.UU. en instalaciones correccionales de Ohio.",
    notes="Pre-release planning begins inside facility; contact VA or facility reentry staff for HCRV referral.",
    notes_es="La planificación previa a la liberación comienza dentro de la instalación.",
    hours="Contact VA for specialist availability",
    tags="veterans|statewide|HCRV|pre-release",
    services="Pre-release assessments|VA benefits linkage|Medical care enrollment|Post-release housing referrals",
    county="", latitude="", longitude="", served_counties="", coverage="statewide",
    _source="https://www.va.gov/homeless/hcrv.asp", _source_type="government", _confidence="high",
)

# --- Key nonprofits ---
add(
    name="Lutheran Metropolitan Ministry — Reentry Services",
    category="reentry-organizations", region="Cleveland / Cuyahoga County",
    description="Cleveland nonprofit providing reentry workforce development, case management, and community integration services for justice-involved adults including employment training and supportive services.",
    description_es="Organización sin fines de lucro de Cleveland que ofrece desarrollo laboral de reinserción, manejo de casos e integración comunitaria para adultos con antecedentes penales.",
    address="4515 Superior Avenue", city="Cleveland", phone="(216) 658-4600",
    email="", website="https://www.lutheranmetro.org",
    eligibility="Justice-involved adults in greater Cleveland; program-specific requirements vary.",
    eligibility_es="Adultos con antecedentes penales en el área de Cleveland; requisitos varían por programa.",
    notes="Multiple program sites; contact main line for current reentry program intake.",
    notes_es="Múltiples sitios de programas; contacte la línea principal.",
    hours="Monday–Friday business hours",
    tags="cleveland|reentry|employment|nonprofit",
    services="Workforce development|Case management|Employment training|Community integration support",
    county="Cuyahoga", latitude="41.5080", longitude="-81.6180", served_counties="Cuyahoga", coverage="single",
    _source="https://www.lutheranmetro.org", _source_type="nonprofit", _confidence="high",
)
add(
    name="Alvis — Community Reentry Center",
    category="reentry-organizations", region="Columbus / Franklin County",
    description="Columbus reentry organization providing residential and community-based services for justice-involved individuals including halfway house programming, employment support, and treatment referrals. ATR participating agency in Franklin County.",
    description_es="Organización de reinserción en Columbus que ofrece servicios residenciales y comunitarios incluyendo programas de medio camino, apoyo de empleo y referencias de tratamiento.",
    address="2100 Stella Court", city="Columbus", phone="(614) 252-0660",
    email="", website="https://www.alvis180.org",
    eligibility="Justice-involved adults referred through DRC, courts, or community corrections; program-specific criteria apply.",
    eligibility_es="Adultos con antecedentes penales referidos por DRC, tribunales o correcciones comunitarias.",
    notes="ATR care coordinator site for Franklin County; contact for residential bed availability.",
    notes_es="Sitio coordinador ATR para el condado de Franklin.",
    hours="Contact for program hours",
    tags="columbus|reentry|halfway-house|ATR|residential",
    services="Halfway house programming|Employment support|Treatment referrals|Case management",
    county="Franklin", latitude="39.9690", longitude="-82.9400", served_counties="Franklin", coverage="single",
    _source="https://mha.ohio.gov/about-us/documents/access-to-recovery", _source_type="nonprofit", _confidence="high",
)

# --- Additional resources to reach 80+ ---
EXTRAS = [
    dict(name="OhioMeansJobs — Franklin County", category="employment", region="Columbus",
         phone="(614) 559-5052", website="https://omjfc.us", address="1111 East Broad Street", city="Columbus",
         county="Franklin", lat="39.9650", lon="-82.9700", cov="single", served="Franklin",
         desc="Franklin County workforce center connecting job seekers including justice-involved individuals to training, job search, and employer services."),
    dict(name="OhioMeansJobs — Cuyahoga County", category="employment", region="Cleveland",
         phone="(216) 777-7655", website="https://www.omjcc.org", address="1910 Superior Avenue", city="Cleveland",
         county="Cuyahoga", lat="41.5035", lon="-81.6925", cov="single", served="Cuyahoga",
         desc="Cuyahoga County workforce services including job placement, training referrals, and reentry-friendly employment resources."),
    dict(name="Talbert House — Reentry Services", category="substance-use-treatment", region="Cincinnati",
         phone="(513) 281-7880", website="https://www.talberthouse.org", address="2600 Victory Parkway", city="Cincinnati",
         county="Hamilton", lat="39.1205", lon="-84.5085", cov="single", served="Hamilton",
         desc="Cincinnati behavioral health and reentry provider offering treatment, housing, and ATR care coordination for justice-involved individuals."),
    dict(name="Oriana House — Reentry Programs", category="reentry-organizations", region="Akron / Northeast Ohio",
         phone="(330) 996-7730", website="https://www.orianahouse.org", address="1050 East Market Street", city="Akron",
         county="Summit", lat="41.0680", lon="-81.4900", cov="single", served="Summit",
         desc="Northeast Ohio reentry provider operating residential and community programs including North Star Cleveland and Summit County ATR services."),
    dict(name="Community Shelter Board — Reentry Housing", category="housing", region="Columbus",
         phone="(614) 715-2530", website="https://www.csb.org", address="60 East Broad Street", city="Columbus",
         county="Franklin", lat="39.9610", lon="-82.9980", cov="single", served="Franklin",
         desc="Columbus homeless services coordinating body connecting individuals including returning citizens to emergency shelter and housing programs."),
    dict(name="Goodwill Easterseals Miami Valley — Reentry", category="employment", region="Dayton",
         phone="(937) 528-6409", website="https://www.gesmv.org", address="660 South Main Street", city="Lima",
         county="Allen", lat="40.7389", lon="-84.1054", cov="multi", served="Allen|Auglaize|Champaign|Clark|Darke|Greene|Logan|Miami|Montgomery|Preble|Shelby",
         desc="Goodwill Easterseals provides employment and reentry coalition support across west-central Ohio."),
    dict(name="Ohio BMV — Ex-Offender ID Information", category="id-documentation", region="Statewide",
         phone="(844) 644-6268", website="https://www.bmv.ohio.gov", address="", city="Columbus",
         county="", lat="", lon="", cov="statewide", served="",
         desc="Ohio Bureau of Motor Vehicles provides state ID and driver's license services; reentry partners often assist with documentation requirements for restored citizens."),
    dict(name="Ohio Department of Health — Vital Records", category="id-documentation", region="Statewide",
         phone="(614) 466-2531", website="https://odh.ohio.gov/know-our-programs/vital-statistics", address="246 North High Street", city="Columbus",
         county="Franklin", lat="39.9690", lon="-83.0040", cov="statewide", served="",
         desc="State vital records office for ordering birth certificates and death records needed for ID and benefits applications after release."),
    dict(name="Greater Cleveland Food Bank", category="food-nutrition", region="Cleveland",
         phone="(216) 738-2265", website="https://www.greaterclevelandfoodbank.org", address="15500 South Waterloo Road", city="Cleveland",
         county="Cuyahoga", lat="41.4400", lon="-81.5300", cov="multi", served="Ashland|Ashtabula|Cuyahoga|Geauga|Lake|Richland|Wayne",
         desc="Regional food bank connecting northeast Ohio residents including returning citizens to food pantries and SNAP application assistance."),
    dict(name="Mid-Ohio Food Collective", category="food-nutrition", region="Columbus",
         phone="(614) 274-7771", website="https://www.midohiofoodbank.org", address="3960 Brookham Drive", city="Grove City",
         county="Franklin", lat="39.8800", lon="-83.0700", cov="multi", served="Delaware|Fairfield|Franklin|Hocking|Licking|Madison|Morrow|Perry|Pickaway|Union",
         desc="Central Ohio food bank network providing pantry referrals and nutrition support for low-income residents including reentry populations."),
    dict(name="Freestore Foodbank — Cincinnati", category="food-nutrition", region="Cincinnati",
         phone="(513) 381-7627", website="https://freestorefoodbank.org", address="1141 Central Parkway", city="Cincinnati",
         county="Hamilton", lat="39.1100", lon="-84.5200", cov="multi", served="Brown|Clermont|Hamilton|Warren",
         desc="Southwest Ohio food bank providing emergency food and benefits navigation for Hamilton County and surrounding areas."),
    dict(name="Circle for Recovery Ohio (CFRO)", category="substance-use-treatment", region="Statewide",
         phone="(614) 466-2596", website="https://mha.ohio.gov/community-partners/criminal-justice/re-entry-programs/circle-for-recovery-ohio", address="30 East Broad Street", city="Columbus",
         county="Franklin", lat="39.9625", lon="-82.9988", cov="multi", served="Summit|Cuyahoga|Franklin|Hamilton|Lucas|Montgomery|Stark|Mahoning|Lorain",
         desc="OhioMHAS reentry substance use program operating through UMADAOP agencies in major Ohio cities serving formerly incarcerated citizens."),
    dict(name="Maryhaven — Reentry Treatment", category="substance-use-treatment", region="Columbus",
         phone="(614) 445-8131", website="https://maryhaven.com", address="1791 Alum Creek Drive", city="Columbus",
         county="Franklin", lat="39.9270", lon="-82.9470", cov="single", served="Franklin",
         desc="Central Ohio addiction treatment provider offering outpatient and residential services accepting justice-involved referrals."),
    dict(name="Coleman Professional Services — Reentry", category="healthcare", region="Northeast Ohio",
         phone="(330) 673-1347", website="https://www.colemanservices.org", address="3929 Hoover Road", city="Stow",
         county="Summit", lat="41.1590", lon="-81.4400", cov="multi", served="Summit|Portage|Stark|Wayne",
         desc="Behavioral health provider serving northeast Ohio with mental health and substance use services for justice-involved clients."),
    dict(name="Welcome to a New Life — Hancock Reentry", category="peer-support", region="Findlay",
         phone="(419) 455-6082", website="https://www.welcometoanewlife.org", address="", city="Findlay",
         county="Hancock", lat="", lon="", cov="single", served="Hancock",
         desc="Hancock County peer-led reentry support organization providing mentoring and community connections for returning citizens."),
    dict(name="Home for Good — Route 11 Coalition Host", category="reentry-organizations", region="Ashtabula",
         phone="(330) 743-3700", website="https://www.homeforgoodashtabula.org", address="", city="Ashtabula",
         county="Ashtabula", lat="", lon="", cov="multi", served="Ashtabula|Columbiana|Jefferson|Mahoning|Trumbull",
         desc="Ashtabula nonprofit hosting the Route 11 Reentry Coalition and providing direct housing and support services for returning citizens."),
    dict(name="The FourSeven — Butler Warren Reentry", category="reentry-organizations", region="Hamilton",
         phone="(513) 229-7947", website="https://www.thefourseven.org", address="", city="Hamilton",
         county="Butler", lat="", lon="", cov="multi", served="Butler|Warren",
         desc="Faith-based reentry organization hosting the Butler Warren Reentry Coalition with direct support services for returning citizens."),
    dict(name="Connections — Northeast Ohio Reentry", category="healthcare", region="Cleveland",
         phone="(216) 431-4130", website="https://www.connectionscleveland.org", address="8441 Madison Avenue", city="Cleveland",
         county="Cuyahoga", lat="41.4750", lon="-81.7500", cov="single", served="Cuyahoga",
         desc="Cleveland behavioral health agency providing mental health and addiction treatment with justice-involved specialty programs."),
    dict(name="Volunteers of America Ohio — Reentry Housing", category="housing", region="Columbus",
         phone="(614) 870-7500", website="https://www.voaoh.org", address="1776 East Broad Street", city="Columbus",
         county="Franklin", lat="39.9680", lon="-82.9600", cov="single", served="Franklin",
         desc="Columbus nonprofit providing transitional and supportive housing programs serving justice-involved individuals."),
    dict(name="Ohio Ex-Offender Reentry Coalition (via OALRC)", category="peer-support", region="Statewide",
         phone="(567) 200-6815", website="https://drc.ohio.gov/systems-and-services/2-reentry-services/reentry-coalitions", address="", city="",
         county="", lat="", lon="", cov="statewide", served="",
         desc="Peer and community-led reentry advocacy network now organized as the Ohio Association of Local Reentry Coalitions supporting restored citizens statewide."),
    dict(name="findhelp.org — Ohio Social Services Portal", category="financial-assistance", region="Statewide",
         phone="", website="https://www.findhelp.org", address="", city="",
         county="", lat="", lon="", cov="statewide", served="",
         desc="Online portal endorsed by Ohio DRC Office of Reentry for locating local food, housing, healthcare, and benefits programs by ZIP code. Referral hub—not a direct-service provider."),
    dict(name="Ohio Department of Education — Adult Diploma & GED", category="education", region="Statewide",
         phone="(877) 644-6338", website="https://education.ohio.gov/Topics/Ohio-Adult-Opportunities", address="25 South Front Street", city="Columbus",
         county="Franklin", lat="39.9620", lon="-83.0005", cov="statewide", served="",
         desc="State resource connecting Ohio adults including returning citizens to GED, High School Equivalency, and Adult Diploma programs at local career centers and community schools."),
    dict(name="COTA — Reduced Fare Program", category="transportation", region="Columbus",
         phone="(614) 228-1776", website="https://www.cota.com", address="33 North High Street", city="Columbus",
         county="Franklin", lat="39.9625", lon="-83.0008", cov="single", served="Franklin",
         desc="Central Ohio Transit Authority reduced-fare and accessibility programs helping low-income Franklin County residents including returning citizens access bus transportation to work and appointments."),
    dict(name="GCRTA — Reduced Fare Program", category="transportation", region="Cleveland",
         phone="(216) 621-9500", website="https://www.riderta.com", address="1240 West Sixth Street", city="Cleveland",
         county="Cuyahoga", lat="41.4995", lon="-81.7030", cov="single", served="Cuyahoga",
         desc="Greater Cleveland Regional Transit Authority reduced-fare programs for eligible low-income and disability riders in Cuyahoga County."),
    dict(name="Amethyst Inc. — Family Reunification", category="family-children", region="Columbus",
         phone="(614) 242-1284", website="https://www.amethyst-inc.org", address="275 West Fifth Avenue", city="Columbus",
         county="Franklin", lat="39.9790", lon="-83.0120", cov="single", served="Franklin",
         desc="Columbus nonprofit serving women in recovery and reunification with children, including justice-involved mothers seeking family stabilization after incarceration."),
    dict(name="St. Vincent de Paul — Cincinnati Reentry Support", category="basic-needs", region="Cincinnati",
         phone="(513) 421-0602", website="https://www.svdpcincinnati.org", address="1125 Bank Street", city="Cincinnati",
         county="Hamilton", lat="39.1080", lon="-84.5180", cov="single", served="Hamilton",
         desc="Cincinnati charity providing clothing, furniture, utility assistance, and basic needs support for low-income residents including returning citizens."),
]
for e in EXTRAS:
    add(
        name=e["name"], category=e["category"], region=e.get("region", e.get("city", "")),
        description=e["desc"],
        description_es="",
        address=e.get("address", ""), city=e["city"], phone=e["phone"], email="", website=e["website"],
        eligibility="",
        eligibility_es="",
        notes="",
        notes_es="",
        hours="",
        tags=f"reentry|{e.get('county', 'statewide').lower() or 'statewide'}",
        services="",
        county=e.get("county", ""), latitude=e.get("lat", ""), longitude=e.get("lon", ""),
        served_counties=e.get("served", ""), coverage=e["cov"],
        _source=e["website"], _source_type="nonprofit", _confidence="medium",
    )

# --- Phase 4: Program-level expansion ---
from ohio_phase4_expansion import register_phase4
register_phase4(add)

# Fix single-county served_counties for coalitions with coverage single
for entry in ENTRIES:
    if entry.get("coverage") == "single" and entry.get("served_counties") and "|" not in entry["served_counties"]:
        pass  # ok
    elif entry.get("coverage") == "single" and not entry.get("served_counties") and entry.get("county"):
        entry["served_counties"] = entry["county"]

# Assign sequential IDs and write CSVs
log_rows = []
for i, e in enumerate(ENTRIES, start=1):
    e["id"] = str(i)
    log_rows.append({
        "source_url": e.pop("_source"),
        "source_type": e.pop("_source_type"),
        "date_accessed": DATE,
        "confidence": e.pop("_confidence"),
        "notes": f"Resource id {i}: {e['name']}",
        "id_reference": str(i),
    })

with RESOURCES_PATH.open("w", newline="", encoding="utf-8") as f:
    w = csv.DictWriter(f, fieldnames=COLUMNS, quoting=csv.QUOTE_MINIMAL)
    w.writeheader()
    for e in ENTRIES:
        row = {c: e.get(c, "") for c in COLUMNS}
        w.writerow(row)

log_rows.append({
    "source_url": "https://findhelpnow.org/",
    "source_type": "directory",
    "date_accessed": DATE,
    "confidence": "low",
    "notes": "FindHelpNow verified Kentucky-only (findhelpnow.org/ky); no Ohio portal found. Ohio substance use search uses FindTreatment.gov (id 16) instead.",
    "id_reference": "16",
})

with LOG_PATH.open("w", newline="", encoding="utf-8") as f:
    w = csv.DictWriter(f, fieldnames=LOG_COLUMNS, quoting=csv.QUOTE_MINIMAL)
    w.writeheader()
    w.writerows(log_rows)

cats = Counter(e["category"] for e in ENTRIES)
low = [e for e in log_rows if e["confidence"] == "medium"]
print(f"Total rows: {len(ENTRIES)}")
print("Category counts:")
for k, v in sorted(cats.items()):
    print(f"  {k}: {v}")
print(f"Low confidence: {len(low)}")
for r in low:
    print(f"  id {r['id_reference']}: {r['notes']}")

