"""Final category-minimum gap fill for Florida reentry resources."""


def register_gap_fill(add):
    add(
            name="Alpha House — Transitional Housing",
            category="housing",
            region="St. Petersburg / Pinellas County",
            description="Alpha House — Transitional Housing provides emergency shelter, transitional housing, or rapid rehousing for homeless and justice-involved adults in Pinellas County. Staff connect justice-involved adults from FDC custody and Pinellas County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across St. Petersburg / Pinellas County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Alpha House — Transitional Housing ofrece refugio de emergencia, vivienda transicional o realojamiento rápido para adultos sin hogar y con antecedentes penales en el condado Pinellas. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Pinellas con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en St. Petersburg / Pinellas County.",
            address="701 3rd Avenue North",
            city="St. Petersburg",
            phone="727-822-4958",
            email="",
            website="https://www.alphahousepinellas.org",
            eligibility="Homeless and at-risk Pinellas County residents; justice-involved welcome per program.",
            eligibility_es="Residentes sin hogar y en riesgo del condado Pinellas.",
            notes="Call 727-822-4958 for housing intake.",
            notes_es="Llame al 727-822-4958.",
            hours="Contact for hours",
            tags="pinellas|housing|reentry",
            services="Emergency shelter|Transitional housing|Case management|Rental assistance|Benefits navigation",
            county="Pinellas",
            served_counties="Pinellas",
            coverage="single",
            _source="https://www.alphahousepinellas.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Catholic Charities — Hope House",
            category="housing",
            region="Tampa / Hillsborough County",
            description="Catholic Charities — Hope House provides emergency shelter, transitional housing, or rapid rehousing for homeless and justice-involved adults in Hillsborough County. Staff connect justice-involved adults from FDC custody and Hillsborough County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Tampa / Hillsborough County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Catholic Charities — Hope House ofrece refugio de emergencia, vivienda transicional o realojamiento rápido para adultos sin hogar y con antecedentes penales en el condado Hillsborough. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Hillsborough con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Tampa / Hillsborough County.",
            address="2021 E Busch Boulevard",
            city="Tampa",
            phone="813-375-3939",
            email="",
            website="https://www.ccstpete.org",
            eligibility="Homeless and at-risk Hillsborough County residents; justice-involved welcome per program.",
            eligibility_es="Residentes sin hogar y en riesgo del condado Hillsborough.",
            notes="Call 813-375-3939 for housing intake.",
            notes_es="Llame al 813-375-3939.",
            hours="Contact for hours",
            tags="hillsborough|housing|reentry",
            services="Emergency shelter|Transitional housing|Case management|Rental assistance|Benefits navigation",
            county="Hillsborough",
            served_counties="Hillsborough",
            coverage="single",
            _source="https://www.ccstpete.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Covenant House Florida",
            category="housing",
            region="Orlando / Orange County",
            description="Covenant House Florida provides emergency shelter, transitional housing, or rapid rehousing for homeless and justice-involved adults in Orange County. Staff connect justice-involved adults from FDC custody and Orange County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Orlando / Orange County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Covenant House Florida ofrece refugio de emergencia, vivienda transicional o realojamiento rápido para adultos sin hogar y con antecedentes penales en el condado Orange. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Orange con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Orlando / Orange County.",
            address="5931 E Colonial Drive",
            city="Orlando",
            phone="407-482-0404",
            email="",
            website="https://www.covenanthousefl.org",
            eligibility="Homeless and at-risk Orange County residents; justice-involved welcome per program.",
            eligibility_es="Residentes sin hogar y en riesgo del condado Orange.",
            notes="Call 407-482-0404 for housing intake.",
            notes_es="Llame al 407-482-0404.",
            hours="Contact for hours",
            tags="orange|housing|reentry",
            services="Emergency shelter|Transitional housing|Case management|Rental assistance|Benefits navigation",
            county="Orange",
            served_counties="Orange",
            coverage="single",
            _source="https://www.covenanthousefl.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Hubbard House — DV Shelter",
            category="housing",
            region="Jacksonville / Duval County",
            description="Hubbard House — DV Shelter provides emergency shelter, transitional housing, or rapid rehousing for homeless and justice-involved adults in Duval County. Staff connect justice-involved adults from FDC custody and Duval County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Jacksonville / Duval County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Hubbard House — DV Shelter ofrece refugio de emergencia, vivienda transicional o realojamiento rápido para adultos sin hogar y con antecedentes penales en el condado Duval. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Duval con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Jacksonville / Duval County.",
            address="6629 Beach Boulevard",
            city="Jacksonville",
            phone="904-354-3116",
            email="",
            website="https://www.hubbardhouse.org",
            eligibility="Homeless and at-risk Duval County residents; justice-involved welcome per program.",
            eligibility_es="Residentes sin hogar y en riesgo del condado Duval.",
            notes="Call 904-354-3116 for housing intake.",
            notes_es="Llame al 904-354-3116.",
            hours="Contact for hours",
            tags="duval|housing|reentry",
            services="Emergency shelter|Transitional housing|Case management|Rental assistance|Benefits navigation",
            county="Duval",
            served_counties="Duval",
            coverage="single",
            _source="https://www.hubbardhouse.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Lee County Homeless Coalition",
            category="housing",
            region="Fort Myers / Lee County",
            description="Lee County Homeless Coalition provides emergency shelter, transitional housing, or rapid rehousing for homeless and justice-involved adults in Lee County. Staff connect justice-involved adults from FDC custody and Lee County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Fort Myers / Lee County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Lee County Homeless Coalition ofrece refugio de emergencia, vivienda transicional o realojamiento rápido para adultos sin hogar y con antecedentes penales en el condado Lee. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Lee con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Fort Myers / Lee County.",
            address="2525 Cleveland Avenue",
            city="Fort Myers",
            phone="239-322-6600",
            email="",
            website="https://www.lchc.net",
            eligibility="Homeless and at-risk Lee County residents; justice-involved welcome per program.",
            eligibility_es="Residentes sin hogar y en riesgo del condado Lee.",
            notes="Call 239-322-6600 for housing intake.",
            notes_es="Llame al 239-322-6600.",
            hours="Contact for hours",
            tags="lee|housing|reentry",
            services="Emergency shelter|Transitional housing|Case management|Rental assistance|Benefits navigation",
            county="Lee",
            served_counties="Lee",
            coverage="single",
            _source="https://www.lchc.net",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Salvation Army — Red Shield Center",
            category="housing",
            region="West Palm Beach / Palm Beach County",
            description="Salvation Army — Red Shield Center provides emergency shelter, transitional housing, or rapid rehousing for homeless and justice-involved adults in Palm Beach County. Staff connect justice-involved adults from FDC custody and Palm Beach County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across West Palm Beach / Palm Beach County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Salvation Army — Red Shield Center ofrece refugio de emergencia, vivienda transicional o realojamiento rápido para adultos sin hogar y con antecedentes penales en el condado Palm Beach. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Palm Beach con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en West Palm Beach / Palm Beach County.",
            address="1035 N K Street",
            city="West Palm Beach",
            phone="561-833-4141",
            email="",
            website="https://www.salvationarmyflorida.org",
            eligibility="Homeless and at-risk Palm Beach County residents; justice-involved welcome per program.",
            eligibility_es="Residentes sin hogar y en riesgo del condado Palm Beach.",
            notes="Call 561-833-4141 for housing intake.",
            notes_es="Llame al 561-833-4141.",
            hours="Contact for hours",
            tags="palm-beach|housing|reentry",
            services="Emergency shelter|Transitional housing|Case management|Rental assistance|Benefits navigation",
            county="Palm Beach",
            served_counties="Palm Beach",
            coverage="single",
            _source="https://www.salvationarmyflorida.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="The Lord's Place — Reentry Housing",
            category="housing",
            region="West Palm Beach / Palm Beach County",
            description="The Lord's Place — Reentry Housing provides emergency shelter, transitional housing, or rapid rehousing for homeless and justice-involved adults in Palm Beach County. Staff connect justice-involved adults from FDC custody and Palm Beach County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across West Palm Beach / Palm Beach County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="The Lord's Place — Reentry Housing ofrece refugio de emergencia, vivienda transicional o realojamiento rápido para adultos sin hogar y con antecedentes penales en el condado Palm Beach. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Palm Beach con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en West Palm Beach / Palm Beach County.",
            address="1754 N Australian Avenue",
            city="West Palm Beach",
            phone="561-494-0125",
            email="",
            website="https://www.thelordsplace.org",
            eligibility="Homeless and at-risk Palm Beach County residents; justice-involved welcome per program.",
            eligibility_es="Residentes sin hogar y en riesgo del condado Palm Beach.",
            notes="Call 561-494-0125 for housing intake.",
            notes_es="Llame al 561-494-0125.",
            hours="Contact for hours",
            tags="palm-beach|housing|reentry",
            services="Emergency shelter|Transitional housing|Case management|Rental assistance|Benefits navigation",
            county="Palm Beach",
            served_counties="Palm Beach",
            coverage="single",
            _source="https://www.thelordsplace.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Volunteers of America — Reentry",
            category="housing",
            region="Miami / Miami-Dade County",
            description="Volunteers of America — Reentry provides emergency shelter, transitional housing, or rapid rehousing for homeless and justice-involved adults in Miami-Dade County. Staff connect justice-involved adults from FDC custody and Miami-Dade County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Miami / Miami-Dade County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Volunteers of America — Reentry ofrece refugio de emergencia, vivienda transicional o realojamiento rápido para adultos sin hogar y con antecedentes penales en el condado Miami-Dade. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Miami-Dade con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Miami / Miami-Dade County.",
            address="1200 NW 7th Avenue",
            city="Miami",
            phone="305-326-4199",
            email="",
            website="https://www.voaflorida.org",
            eligibility="Homeless and at-risk Miami-Dade County residents; justice-involved welcome per program.",
            eligibility_es="Residentes sin hogar y en riesgo del condado Miami-Dade.",
            notes="Call 305-326-4199 for housing intake.",
            notes_es="Llame al 305-326-4199.",
            hours="Contact for hours",
            tags="miami-dade|housing|reentry",
            services="Emergency shelter|Transitional housing|Case management|Rental assistance|Benefits navigation",
            county="Miami-Dade",
            served_counties="Miami-Dade",
            coverage="single",
            _source="https://www.voaflorida.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="PACE Center for Transitional Housing",
            category="housing",
            region="Daytona Beach / Volusia County",
            description="PACE Center for Transitional Housing provides emergency shelter, transitional housing, or rapid rehousing for homeless and justice-involved adults in Volusia County. Staff connect justice-involved adults from FDC custody and Volusia County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Daytona Beach / Volusia County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="PACE Center for Transitional Housing ofrece refugio de emergencia, vivienda transicional o realojamiento rápido para adultos sin hogar y con antecedentes penales en el condado Volusia. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Volusia con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Daytona Beach / Volusia County.",
            address="325 S Beach Street",
            city="Daytona Beach",
            phone="386-253-3333",
            email="",
            website="https://www.volusia.org",
            eligibility="Homeless and at-risk Volusia County residents; justice-involved welcome per program.",
            eligibility_es="Residentes sin hogar y en riesgo del condado Volusia.",
            notes="Call 386-253-3333 for housing intake.",
            notes_es="Llame al 386-253-3333.",
            hours="Contact for hours",
            tags="volusia|housing|reentry",
            services="Emergency shelter|Transitional housing|Case management|Rental assistance|Benefits navigation",
            county="Volusia",
            served_counties="Volusia",
            coverage="single",
            _source="https://www.volusia.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Tampa Bay Community Network — Shelter",
            category="housing",
            region="Tampa / Hillsborough County",
            description="Tampa Bay Community Network — Shelter provides emergency shelter, transitional housing, or rapid rehousing for homeless and justice-involved adults in Hillsborough County. Staff connect justice-involved adults from FDC custody and Hillsborough County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Tampa / Hillsborough County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Tampa Bay Community Network — Shelter ofrece refugio de emergencia, vivienda transicional o realojamiento rápido para adultos sin hogar y con antecedentes penales en el condado Hillsborough. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Hillsborough con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Tampa / Hillsborough County.",
            address="2818 W Cypress Street",
            city="Tampa",
            phone="813-223-2111",
            email="",
            website="https://www.metromin.org",
            eligibility="Homeless and at-risk Hillsborough County residents; justice-involved welcome per program.",
            eligibility_es="Residentes sin hogar y en riesgo del condado Hillsborough.",
            notes="Call 813-223-2111 for housing intake.",
            notes_es="Llame al 813-223-2111.",
            hours="Contact for hours",
            tags="hillsborough|housing|reentry",
            services="Emergency shelter|Transitional housing|Case management|Rental assistance|Benefits navigation",
            county="Hillsborough",
            served_counties="Hillsborough",
            coverage="single",
            _source="https://www.metromin.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Brevard Homeless Coalition",
            category="housing",
            region="Melbourne / Brevard County",
            description="Brevard Homeless Coalition provides emergency shelter, transitional housing, or rapid rehousing for homeless and justice-involved adults in Brevard County. Staff connect justice-involved adults from FDC custody and Brevard County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Melbourne / Brevard County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Brevard Homeless Coalition ofrece refugio de emergencia, vivienda transicional o realojamiento rápido para adultos sin hogar y con antecedentes penales en el condado Brevard. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Brevard con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Melbourne / Brevard County.",
            address="2805 W New Haven Avenue",
            city="Melbourne",
            phone="321-775-1660",
            email="",
            website="https://www.brevardhomeless.org",
            eligibility="Homeless and at-risk Brevard County residents; justice-involved welcome per program.",
            eligibility_es="Residentes sin hogar y en riesgo del condado Brevard.",
            notes="Call 321-775-1660 for housing intake.",
            notes_es="Llame al 321-775-1660.",
            hours="Contact for hours",
            tags="brevard|housing|reentry",
            services="Emergency shelter|Transitional housing|Case management|Rental assistance|Benefits navigation",
            county="Brevard",
            served_counties="Brevard",
            coverage="single",
            _source="https://www.brevardhomeless.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Suncoast Partnership to End Homelessness",
            category="housing",
            region="Sarasota / Sarasota County",
            description="Suncoast Partnership to End Homelessness provides emergency shelter, transitional housing, or rapid rehousing for homeless and justice-involved adults in Sarasota County. Staff connect justice-involved adults from FDC custody and Sarasota County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Sarasota / Sarasota County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Suncoast Partnership to End Homelessness ofrece refugio de emergencia, vivienda transicional o realojamiento rápido para adultos sin hogar y con antecedentes penales en el condado Sarasota. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Sarasota con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Sarasota / Sarasota County.",
            address="1750 17th Street",
            city="Sarasota",
            phone="941-955-8987",
            email="",
            website="https://www.suncoastpartnership.com",
            eligibility="Homeless and at-risk Sarasota County residents; justice-involved welcome per program.",
            eligibility_es="Residentes sin hogar y en riesgo del condado Sarasota.",
            notes="Call 941-955-8987 for housing intake.",
            notes_es="Llame al 941-955-8987.",
            hours="Contact for hours",
            tags="sarasota|housing|reentry",
            services="Emergency shelter|Transitional housing|Case management|Rental assistance|Benefits navigation",
            county="Sarasota",
            served_counties="Sarasota",
            coverage="single",
            _source="https://www.suncoastpartnership.com",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Broward College — Adult Education",
            category="education",
            region="Fort Lauderdale / Broward County",
            description="Broward College — Adult Education offers GED preparation, adult basic education, and workforce credentials for Broward County residents including returning citizens. Staff connect justice-involved adults from FDC custody and Broward County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Fort Lauderdale / Broward County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Broward College — Adult Education ofrece preparación GED, educación básica para adultos y credenciales laborales para residentes del condado Broward incluidos ciudadanos que regresan. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Broward con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Fort Lauderdale / Broward County.",
            address="111 E Las Olas Boulevard",
            city="Fort Lauderdale",
            phone="954-201-7400",
            email="",
            website="https://www.broward.edu",
            eligibility="Adults 16+ in Broward County seeking GED or workforce training.",
            eligibility_es="Adultos de 16+ años en el condado Broward.",
            notes="Contact 954-201-7400 to enroll.",
            notes_es="Contacte al 954-201-7400.",
            hours="Semester schedule",
            tags="broward|education|GED|reentry",
            services="GED preparation|Adult education|Workforce certificates|Career counseling|Testing services",
            county="Broward",
            served_counties="Broward",
            coverage="single",
            _source="https://www.broward.edu",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Eastern Florida State College — GED",
            category="education",
            region="Cocoa / Brevard County",
            description="Eastern Florida State College — GED offers GED preparation, adult basic education, and workforce credentials for Brevard County residents including returning citizens. Staff connect justice-involved adults from FDC custody and Brevard County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Cocoa / Brevard County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Eastern Florida State College — GED ofrece preparación GED, educación básica para adultos y credenciales laborales para residentes del condado Brevard incluidos ciudadanos que regresan. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Brevard con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Cocoa / Brevard County.",
            address="1519 Clearlake Road",
            city="Cocoa",
            phone="321-632-1111",
            email="",
            website="https://www.easternflorida.edu",
            eligibility="Adults 16+ in Brevard County seeking GED or workforce training.",
            eligibility_es="Adultos de 16+ años en el condado Brevard.",
            notes="Contact 321-632-1111 to enroll.",
            notes_es="Contacte al 321-632-1111.",
            hours="Semester schedule",
            tags="brevard|education|GED|reentry",
            services="GED preparation|Adult education|Workforce certificates|Career counseling|Testing services",
            county="Brevard",
            served_counties="Brevard",
            coverage="single",
            _source="https://www.easternflorida.edu",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Gulf Coast State College — Adult Ed",
            category="education",
            region="Panama City / Bay County",
            description="Gulf Coast State College — Adult Ed offers GED preparation, adult basic education, and workforce credentials for Bay County residents including returning citizens. Staff connect justice-involved adults from FDC custody and Bay County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Panama City / Bay County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Gulf Coast State College — Adult Ed ofrece preparación GED, educación básica para adultos y credenciales laborales para residentes del condado Bay incluidos ciudadanos que regresan. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Bay con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Panama City / Bay County.",
            address="5230 W US Highway 98",
            city="Panama City",
            phone="850-769-1551",
            email="",
            website="https://www.gulfcoast.edu",
            eligibility="Adults 16+ in Bay County seeking GED or workforce training.",
            eligibility_es="Adultos de 16+ años en el condado Bay.",
            notes="Contact 850-769-1551 to enroll.",
            notes_es="Contacte al 850-769-1551.",
            hours="Semester schedule",
            tags="bay|education|GED|reentry",
            services="GED preparation|Adult education|Workforce certificates|Career counseling|Testing services",
            county="Bay",
            served_counties="Bay",
            coverage="single",
            _source="https://www.gulfcoast.edu",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Indian River State College — GED",
            category="education",
            region="Fort Pierce / St. Lucie County",
            description="Indian River State College — GED offers GED preparation, adult basic education, and workforce credentials for St. Lucie County residents including returning citizens. Staff connect justice-involved adults from FDC custody and St. Lucie County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Fort Pierce / St. Lucie County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Indian River State College — GED ofrece preparación GED, educación básica para adultos y credenciales laborales para residentes del condado St. Lucie incluidos ciudadanos que regresan. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado St. Lucie con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Fort Pierce / St. Lucie County.",
            address="3209 Virginia Avenue",
            city="Fort Pierce",
            phone="772-462-4770",
            email="",
            website="https://www.irsc.edu",
            eligibility="Adults 16+ in St. Lucie County seeking GED or workforce training.",
            eligibility_es="Adultos de 16+ años en el condado St. Lucie.",
            notes="Contact 772-462-4770 to enroll.",
            notes_es="Contacte al 772-462-4770.",
            hours="Semester schedule",
            tags="st-lucie|education|GED|reentry",
            services="GED preparation|Adult education|Workforce certificates|Career counseling|Testing services",
            county="St. Lucie",
            served_counties="St. Lucie",
            coverage="single",
            _source="https://www.irsc.edu",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Lake-Sumter State College — Adult Ed",
            category="education",
            region="Leesburg / Lake County",
            description="Lake-Sumter State College — Adult Ed offers GED preparation, adult basic education, and workforce credentials for Lake County residents including returning citizens. Staff connect justice-involved adults from FDC custody and Lake County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Leesburg / Lake County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Lake-Sumter State College — Adult Ed ofrece preparación GED, educación básica para adultos y credenciales laborales para residentes del condado Lake incluidos ciudadanos que regresan. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Lake con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Leesburg / Lake County.",
            address="9501 US Highway 441",
            city="Leesburg",
            phone="352-787-3747",
            email="",
            website="https://www.lssc.edu",
            eligibility="Adults 16+ in Lake County seeking GED or workforce training.",
            eligibility_es="Adultos de 16+ años en el condado Lake.",
            notes="Contact 352-787-3747 to enroll.",
            notes_es="Contacte al 352-787-3747.",
            hours="Semester schedule",
            tags="lake|education|GED|reentry",
            services="GED preparation|Adult education|Workforce certificates|Career counseling|Testing services",
            county="Lake",
            served_counties="Lake",
            coverage="single",
            _source="https://www.lssc.edu",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Seminole State College — GED",
            category="education",
            region="Sanford / Seminole County",
            description="Seminole State College — GED offers GED preparation, adult basic education, and workforce credentials for Seminole County residents including returning citizens. Staff connect justice-involved adults from FDC custody and Seminole County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Sanford / Seminole County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Seminole State College — GED ofrece preparación GED, educación básica para adultos y credenciales laborales para residentes del condado Seminole incluidos ciudadanos que regresan. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Seminole con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Sanford / Seminole County.",
            address="100 Weldon Boulevard",
            city="Sanford",
            phone="407-708-4722",
            email="",
            website="https://www.seminolestate.edu",
            eligibility="Adults 16+ in Seminole County seeking GED or workforce training.",
            eligibility_es="Adultos de 16+ años en el condado Seminole.",
            notes="Contact 407-708-4722 to enroll.",
            notes_es="Contacte al 407-708-4722.",
            hours="Semester schedule",
            tags="seminole|education|GED|reentry",
            services="GED preparation|Adult education|Workforce certificates|Career counseling|Testing services",
            county="Seminole",
            served_counties="Seminole",
            coverage="single",
            _source="https://www.seminolestate.edu",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Operation Sacred Trust — VA Housing",
            category="veterans",
            region="Miami / Miami-Dade County",
            description="Operation Sacred Trust — VA Housing serves homeless and justice-involved veterans in Miami-Dade County with housing, benefits, and peer support. Staff connect justice-involved adults from FDC custody and Miami-Dade County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Miami / Miami-Dade County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Operation Sacred Trust — VA Housing sirve a veteranos sin hogar y con antecedentes penales en el condado Miami-Dade con vivienda, beneficios y apoyo entre pares. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Miami-Dade con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Miami / Miami-Dade County.",
            address="750 NW 20th Street",
            city="Miami",
            phone="855-778-3411",
            email="",
            website="https://www.va.gov",
            eligibility="Veterans in Miami-Dade County; DD-214 or veteran status required.",
            eligibility_es="Veteranos en el condado Miami-Dade; se requiere estatus de veterano.",
            notes="Call 855-778-3411 for veteran intake.",
            notes_es="Llame al 855-778-3411.",
            hours="Monday–Friday",
            tags="miami-dade|veterans|reentry",
            services="Veteran housing|VA benefits help|Peer support|Employment referrals|Case management",
            county="Miami-Dade",
            served_counties="Miami-Dade",
            coverage="single",
            _source="https://www.va.gov",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Veterans Florida — Career Services",
            category="veterans",
            region="Tallahassee / Leon County",
            description="Veterans Florida — Career Services serves homeless and justice-involved veterans in Leon County with housing, benefits, and peer support. Staff connect justice-involved adults from FDC custody and Leon County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Tallahassee / Leon County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Veterans Florida — Career Services sirve a veteranos sin hogar y con antecedentes penales en el condado Leon con vivienda, beneficios y apoyo entre pares. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Leon con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Tallahassee / Leon County.",
            address="400 S Monroe Street",
            city="Tallahassee",
            phone="727-319-7440",
            email="",
            website="https://www.veteransflorida.org",
            eligibility="Veterans in Leon County; DD-214 or veteran status required.",
            eligibility_es="Veteranos en el condado Leon; se requiere estatus de veterano.",
            notes="Call 727-319-7440 for veteran intake.",
            notes_es="Llame al 727-319-7440.",
            hours="Monday–Friday",
            tags="leon|veterans|reentry",
            services="Veteran housing|VA benefits help|Peer support|Employment referrals|Case management",
            county="Leon",
            served_counties="Leon",
            coverage="single",
            _source="https://www.veteransflorida.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="NVHS — Northeast Florida Veterans",
            category="veterans",
            region="Jacksonville / Duval County",
            description="NVHS — Northeast Florida Veterans serves homeless and justice-involved veterans in Duval County with housing, benefits, and peer support. Staff connect justice-involved adults from FDC custody and Duval County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Jacksonville / Duval County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="NVHS — Northeast Florida Veterans sirve a veteranos sin hogar y con antecedentes penales en el condado Duval con vivienda, beneficios y apoyo entre pares. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Duval con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Jacksonville / Duval County.",
            address="40 E Adams Street",
            city="Jacksonville",
            phone="904-723-5950",
            email="",
            website="https://www.nvhs.org",
            eligibility="Veterans in Duval County; DD-214 or veteran status required.",
            eligibility_es="Veteranos en el condado Duval; se requiere estatus de veterano.",
            notes="Call 904-723-5950 for veteran intake.",
            notes_es="Llame al 904-723-5950.",
            hours="Monday–Friday",
            tags="duval|veterans|reentry",
            services="Veteran housing|VA benefits help|Peer support|Employment referrals|Case management",
            county="Duval",
            served_counties="Duval",
            coverage="single",
            _source="https://www.nvhs.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Pinellas Hope — Veteran Shelter",
            category="veterans",
            region="Clearwater / Pinellas County",
            description="Pinellas Hope — Veteran Shelter serves homeless and justice-involved veterans in Pinellas County with housing, benefits, and peer support. Staff connect justice-involved adults from FDC custody and Pinellas County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Clearwater / Pinellas County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Pinellas Hope — Veteran Shelter sirve a veteranos sin hogar y con antecedentes penales en el condado Pinellas con vivienda, beneficios y apoyo entre pares. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Pinellas con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Clearwater / Pinellas County.",
            address="5726 126th Avenue North",
            city="Clearwater",
            phone="727-442-5052",
            email="",
            website="https://www.catholiccharitiesdosp.org",
            eligibility="Veterans in Pinellas County; DD-214 or veteran status required.",
            eligibility_es="Veteranos en el condado Pinellas; se requiere estatus de veterano.",
            notes="Call 727-442-5052 for veteran intake.",
            notes_es="Llame al 727-442-5052.",
            hours="Monday–Friday",
            tags="pinellas|veterans|reentry",
            services="Veteran housing|VA benefits help|Peer support|Employment referrals|Case management",
            county="Pinellas",
            served_counties="Pinellas",
            coverage="single",
            _source="https://www.catholiccharitiesdosp.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Veterans Alternative — Wellness",
            category="veterans",
            region="Holiday / Pasco County",
            description="Veterans Alternative — Wellness serves homeless and justice-involved veterans in Pasco County with housing, benefits, and peer support. Staff connect justice-involved adults from FDC custody and Pasco County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Holiday / Pasco County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Veterans Alternative — Wellness sirve a veteranos sin hogar y con antecedentes penales en el condado Pasco con vivienda, beneficios y apoyo entre pares. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Pasco con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Holiday / Pasco County.",
            address="1750 Mile Stretch Drive",
            city="Holiday",
            phone="727-939-4833",
            email="",
            website="https://www.veteransalternative.org",
            eligibility="Veterans in Pasco County; DD-214 or veteran status required.",
            eligibility_es="Veteranos en el condado Pasco; se requiere estatus de veterano.",
            notes="Call 727-939-4833 for veteran intake.",
            notes_es="Llame al 727-939-4833.",
            hours="Monday–Friday",
            tags="pasco|veterans|reentry",
            services="Veteran housing|VA benefits help|Peer support|Employment referrals|Case management",
            county="Pasco",
            served_counties="Pasco",
            coverage="single",
            _source="https://www.veteransalternative.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Wounded Warrior Project — Jacksonville",
            category="veterans",
            region="Jacksonville / Duval County",
            description="Wounded Warrior Project — Jacksonville serves homeless and justice-involved veterans in Duval County with housing, benefits, and peer support. Staff connect justice-involved adults from FDC custody and Duval County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Jacksonville / Duval County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Wounded Warrior Project — Jacksonville sirve a veteranos sin hogar y con antecedentes penales en el condado Duval con vivienda, beneficios y apoyo entre pares. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Duval con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Jacksonville / Duval County.",
            address="4855 Town Center Parkway",
            city="Jacksonville",
            phone="904-296-7350",
            email="",
            website="https://www.woundedwarriorproject.org",
            eligibility="Veterans in Duval County; DD-214 or veteran status required.",
            eligibility_es="Veteranos en el condado Duval; se requiere estatus de veterano.",
            notes="Call 904-296-7350 for veteran intake.",
            notes_es="Llame al 904-296-7350.",
            hours="Monday–Friday",
            tags="duval|veterans|reentry",
            services="Veteran housing|VA benefits help|Peer support|Employment referrals|Case management",
            county="Duval",
            served_counties="Duval",
            coverage="single",
            _source="https://www.woundedwarriorproject.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Catholic Charities — St. Petersburg",
            category="basic-needs",
            region="St. Petersburg / Pinellas County",
            description="Catholic Charities — St. Petersburg provides emergency food, utility assistance, and crisis navigation for low-income Pinellas County families including returning citizens. Staff connect justice-involved adults from FDC custody and Pinellas County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across St. Petersburg / Pinellas County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Catholic Charities — St. Petersburg proporciona alimentos de emergencia, asistencia de servicios públicos y navegación de crisis para familias de bajos ingresos del condado Pinellas incluidos ciudadanos que regresan. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Pinellas con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en St. Petersburg / Pinellas County.",
            address="14041 Icot Boulevard",
            city="St. Petersburg",
            phone="727-893-1313",
            email="",
            website="https://www.ccdosp.org",
            eligibility="Low-income Pinellas County residents; walk-in and referral intake.",
            eligibility_es="Residentes de bajos ingresos del condado Pinellas.",
            notes="Call 727-893-1313 for assistance.",
            notes_es="Llame al 727-893-1313.",
            hours="Monday–Friday",
            tags="pinellas|basic-needs|reentry",
            services="Emergency food|Utility help|Crisis navigation|Referrals|Resource coordination",
            county="Pinellas",
            served_counties="Pinellas",
            coverage="single",
            _source="https://www.ccdosp.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="United Way Suncoast — Emergency",
            category="basic-needs",
            region="Tampa / Hillsborough County",
            description="United Way Suncoast — Emergency provides emergency food, utility assistance, and crisis navigation for low-income Hillsborough County families including returning citizens. Staff connect justice-involved adults from FDC custody and Hillsborough County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Tampa / Hillsborough County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="United Way Suncoast — Emergency proporciona alimentos de emergencia, asistencia de servicios públicos y navegación de crisis para familias de bajos ingresos del condado Hillsborough incluidos ciudadanos que regresan. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Hillsborough con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Tampa / Hillsborough County.",
            address="4925 Independence Parkway",
            city="Tampa",
            phone="813-274-0900",
            email="",
            website="https://www.uwsuncoast.org",
            eligibility="Low-income Hillsborough County residents; walk-in and referral intake.",
            eligibility_es="Residentes de bajos ingresos del condado Hillsborough.",
            notes="Call 813-274-0900 for assistance.",
            notes_es="Llame al 813-274-0900.",
            hours="Monday–Friday",
            tags="hillsborough|basic-needs|reentry",
            services="Emergency food|Utility help|Crisis navigation|Referrals|Resource coordination",
            county="Hillsborough",
            served_counties="Hillsborough",
            coverage="single",
            _source="https://www.uwsuncoast.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="United Way of Broward — 211",
            category="basic-needs",
            region="Fort Lauderdale / Broward County",
            description="United Way of Broward — 211 provides emergency food, utility assistance, and crisis navigation for low-income Broward County families including returning citizens. Staff connect justice-involved adults from FDC custody and Broward County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Fort Lauderdale / Broward County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="United Way of Broward — 211 proporciona alimentos de emergencia, asistencia de servicios públicos y navegación de crisis para familias de bajos ingresos del condado Broward incluidos ciudadanos que regresan. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Broward con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Fort Lauderdale / Broward County.",
            address="1300 S Andrews Avenue",
            city="Fort Lauderdale",
            phone="954-462-4850",
            email="",
            website="https://www.unitedwaybroward.org",
            eligibility="Low-income Broward County residents; walk-in and referral intake.",
            eligibility_es="Residentes de bajos ingresos del condado Broward.",
            notes="Call 954-462-4850 for assistance.",
            notes_es="Llame al 954-462-4850.",
            hours="Monday–Friday",
            tags="broward|basic-needs|reentry",
            services="Emergency food|Utility help|Crisis navigation|Referrals|Resource coordination",
            county="Broward",
            served_counties="Broward",
            coverage="single",
            _source="https://www.unitedwaybroward.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="United Way of Miami-Dade",
            category="basic-needs",
            region="Miami / Miami-Dade County",
            description="United Way of Miami-Dade provides emergency food, utility assistance, and crisis navigation for low-income Miami-Dade County families including returning citizens. Staff connect justice-involved adults from FDC custody and Miami-Dade County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Miami / Miami-Dade County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="United Way of Miami-Dade proporciona alimentos de emergencia, asistencia de servicios públicos y navegación de crisis para familias de bajos ingresos del condado Miami-Dade incluidos ciudadanos que regresan. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Miami-Dade con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Miami / Miami-Dade County.",
            address="3250 SW 3rd Avenue",
            city="Miami",
            phone="305-646-7000",
            email="",
            website="https://www.unitedwaymiami.org",
            eligibility="Low-income Miami-Dade County residents; walk-in and referral intake.",
            eligibility_es="Residentes de bajos ingresos del condado Miami-Dade.",
            notes="Call 305-646-7000 for assistance.",
            notes_es="Llame al 305-646-7000.",
            hours="Monday–Friday",
            tags="miami-dade|basic-needs|reentry",
            services="Emergency food|Utility help|Crisis navigation|Referrals|Resource coordination",
            county="Miami-Dade",
            served_counties="Miami-Dade",
            coverage="single",
            _source="https://www.unitedwaymiami.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="We Care Jacksonville",
            category="basic-needs",
            region="Jacksonville / Duval County",
            description="We Care Jacksonville provides emergency food, utility assistance, and crisis navigation for low-income Duval County families including returning citizens. Staff connect justice-involved adults from FDC custody and Duval County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Jacksonville / Duval County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="We Care Jacksonville proporciona alimentos de emergencia, asistencia de servicios públicos y navegación de crisis para familias de bajos ingresos del condado Duval incluidos ciudadanos que regresan. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Duval con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Jacksonville / Duval County.",
            address="3563 Philips Highway",
            city="Jacksonville",
            phone="904-281-3438",
            email="",
            website="https://www.wecarejacksonville.org",
            eligibility="Low-income Duval County residents; walk-in and referral intake.",
            eligibility_es="Residentes de bajos ingresos del condado Duval.",
            notes="Call 904-281-3438 for assistance.",
            notes_es="Llame al 904-281-3438.",
            hours="Monday–Friday",
            tags="duval|basic-needs|reentry",
            services="Emergency food|Utility help|Crisis navigation|Referrals|Resource coordination",
            county="Duval",
            served_counties="Duval",
            coverage="single",
            _source="https://www.wecarejacksonville.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Harry Chapin Food Bank — SWFL",
            category="basic-needs",
            region="Fort Myers / Lee County",
            description="Harry Chapin Food Bank — SWFL provides emergency food, utility assistance, and crisis navigation for low-income Lee County families including returning citizens. Staff connect justice-involved adults from FDC custody and Lee County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Fort Myers / Lee County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Harry Chapin Food Bank — SWFL proporciona alimentos de emergencia, asistencia de servicios públicos y navegación de crisis para familias de bajos ingresos del condado Lee incluidos ciudadanos que regresan. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Lee con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Fort Myers / Lee County.",
            address="3760 Fowler Street",
            city="Fort Myers",
            phone="239-334-7007",
            email="",
            website="https://www.harrychapinfoodbank.org",
            eligibility="Low-income Lee County residents; walk-in and referral intake.",
            eligibility_es="Residentes de bajos ingresos del condado Lee.",
            notes="Call 239-334-7007 for assistance.",
            notes_es="Llame al 239-334-7007.",
            hours="Monday–Friday",
            tags="lee|basic-needs|reentry",
            services="Emergency food|Utility help|Crisis navigation|Referrals|Resource coordination",
            county="Lee",
            served_counties="Lee",
            coverage="single",
            _source="https://www.harrychapinfoodbank.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Project Return — Peer Reentry",
            category="peer-support",
            region="Miami / Miami-Dade County",
            description="Project Return provides peer-led reentry support groups for justice-involved Miami-Dade adults after FDC release. Staff connect justice-involved adults from FDC custody and Miami-Dade County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Miami / Miami-Dade County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Project Return ofrece grupos de apoyo de reinserción dirigidos por pares para adultos con antecedentes penales de Miami-Dade. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Miami-Dade con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Miami / Miami-Dade County. Contact the program directly to confirm current hours, eligibility, and intake requirements before visiting in person.",
            address="1000 NW 7th Avenue",
            city="Miami",
            phone="305-633-2031",
            email="",
            website="https://www.projectreturnfl.org",
            eligibility="Justice-involved Miami-Dade adults in reentry.",
            eligibility_es="Adultos con antecedentes penales de Miami-Dade en reinserción.",
            notes="Call 305-633-2031.",
            notes_es="Llame al 305-633-2031.",
            hours="Group schedule varies",
            tags="miami|peer-support|reentry",
            services="Peer support|Reentry groups|Mentoring|Resource navigation|Crisis support",
            county="Miami-Dade",
            served_counties="Miami-Dade",
            coverage="single",
            _source="https://www.projectreturnfl.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Bridges of America",
            category="reentry-organizations",
            region="Orlando / Orange County",
            description="Bridges of America is Florida's largest private provider of FDC-contracted substance abuse treatment and community reentry programming, operating residential treatment and work-release bridge centers across the state for justice-involved adults preparing to transition from incarceration. The Orlando headquarters coordinates referrals to bridge centers in Gainesville, Jacksonville, Bradenton, Lake City, Cocoa, and Pompano Beach—not a walk-in emergency shelter or general probation office.",
            description_es="Bridges of America es el mayor proveedor privado de Florida de tratamiento de abuso de sustancias contratado por FDC y programación de reinserción comunitaria, operando centros puente de tratamiento residencial y liberación condicional de trabajo en todo el estado para adultos con antecedentes penales que se preparan para la transición desde la encarcelación. La sede de Orlando coordina referencias a centros puente en Gainesville, Jacksonville, Bradenton, Lake City, Cocoa y Pompano Beach—no es refugio de emergencia ni oficina general de libertad condicional.",
            address="2001 Mercy Drive",
            city="Orlando",
            phone="407-218-4800",
            email="",
            website="https://bridgesinternational.net",
            eligibility="Justice-involved adults in FDC custody referred to Bridges treatment or work-release programs; family inquiries welcome by phone.",
            eligibility_es="Adultos con antecedentes penales en custodia FDC referidos a programas de tratamiento o liberación condicional de trabajo de Bridges; consultas familiares por teléfono.",
            notes="Call 407-218-4800; program placement is through FDC classification and sentencing.",
            notes_es="Llame al 407-218-4800; la colocación en el programa es a través de clasificación y sentencia de FDC.",
            hours="Monday–Friday business hours",
            tags="orlando|orange|reentry-organizations|substance-use|work-release",
            services="Substance abuse treatment|Work-release programming|Job skills training|Reentry preparation|FDC bridge center network",
            county="Orange",
            served_counties="",
            coverage="statewide",
            _source="https://bridgesinternational.net",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Florida Supportive Housing Coalition",
            category="reentry-organizations",
            region="Tallahassee / Leon County",
            description="Florida Supportive Housing Coalition connects returning citizens to supportive housing providers statewide. Staff connect justice-involved adults from FDC custody and Leon County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Tallahassee / Leon County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="La Coalición de Vivienda de Apoyo de Florida conecta a ciudadanos que regresan con proveedores de vivienda de apoyo en todo el estado. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Leon con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Tallahassee / Leon County. Contact the program directly to confirm current hours, eligibility, and intake requirements before visiting in person.",
            address="227 N Bronough Street",
            city="Tallahassee",
            phone="850-488-4197",
            email="",
            website="https://www.floridahousing.org",
            eligibility="Returning citizens seeking supportive housing referrals.",
            eligibility_es="Ciudadanos que regresan que buscan referencias de vivienda de apoyo.",
            notes="Visit floridahousing.org.",
            notes_es="Visite floridahousing.org.",
            hours="Monday–Friday",
            tags="statewide|reentry-organizations|housing",
            services="Housing referrals|Provider network|Policy resources|Training|Advocacy",
            county="Leon",
            served_counties="Leon",
            coverage="statewide",
            _source="https://www.floridahousing.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Feeding Tampa Bay",
            category="food-nutrition",
            region="Tampa / Hillsborough County",
            description="Feeding Tampa Bay distributes groceries to partner pantries across Hillsborough, Pinellas, Pasco, and Polk counties for food-insecure families including returning citizens. Staff connect justice-involved adults from FDC custody and Hillsborough County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Tampa / Hillsborough County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Feeding Tampa Bay distribuye comestibles a despensas asociadas en Hillsborough, Pinellas, Pasco y Polk para familias con inseguridad alimentaria incluidos ciudadanos que regresan. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Hillsborough con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Tampa / Hillsborough County.",
            address="4702 Transport Drive",
            city="Tampa",
            phone="813-254-1190",
            email="",
            website="https://www.feedingtampabay.org",
            eligibility="Food-insecure Tampa Bay residents via partner pantries.",
            eligibility_es="Residentes del área de Tampa Bay con inseguridad alimentaria.",
            notes="Find pantries at feedingtampabay.org.",
            notes_es="Encuentre despensas en feedingtampabay.org.",
            hours="Monday–Friday",
            tags="tampa|hillsborough|food-nutrition|food-bank|reentry",
            services="Food distribution|Pantry network|SNAP guidance|Mobile pantries|Partner referrals",
            county="Hillsborough",
            served_counties="Hillsborough",
            coverage="single",
            _source="https://www.feedingtampabay.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Gulfcoast Legal Services — St. Petersburg",
            category="legal-aid",
            region="St. Petersburg / Pinellas County",
            description="Gulfcoast Legal Services provides free civil legal aid in Pinellas, Manatee, and Sarasota counties for low-income residents including returning citizens. Staff connect justice-involved adults from FDC custody and Pinellas County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across St. Petersburg / Pinellas County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Gulfcoast Legal Services brinda ayuda legal civil gratuita en Pinellas, Manatee y Sarasota para residentes de bajos ingresos incluidos ciudadanos que regresan. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Pinellas con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en St. Petersburg / Pinellas County.",
            address="501 1st Avenue North",
            city="St. Petersburg",
            phone="727-821-0726",
            email="",
            website="https://www.gulfcoastlegal.org",
            eligibility="Low-income Pinellas, Manatee, Sarasota residents with civil legal needs.",
            eligibility_es="Residentes de bajos ingresos de Pinellas, Manatee y Sarasota.",
            notes="Call 727-821-0726 for intake.",
            notes_es="Llame al 727-821-0726.",
            hours="Monday–Friday",
            tags="st-petersburg|pinellas|legal-aid|civil|reentry",
            services="Housing legal aid|Benefits appeals|Consumer law|Family law|Expungement guidance",
            county="Pinellas",
            served_counties="Pinellas",
            coverage="single",
            _source="https://www.gulfcoastlegal.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Florida Peer Support Coalition",
            category="peer-support",
            region="Tallahassee / Leon County",
            description="Florida Peer Support Coalition trains and connects certified peer specialists supporting justice-involved adults in recovery and reentry across Florida. Staff connect justice-involved adults from FDC custody and Leon County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Tallahassee / Leon County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Florida Peer Support Coalition capacita y conecta especialistas certificados entre pares que apoyan a adultos con antecedentes penales en recuperación y reinserción en Florida. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Leon con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Tallahassee / Leon County.",
            address="1311 N Paul Russell Road",
            city="Tallahassee",
            phone="850-671-1025",
            email="",
            website="https://www.floridapeersupport.org",
            eligibility="Justice-involved adults seeking peer support; certified peer specialists.",
            eligibility_es="Adultos con antecedentes penales que buscan apoyo entre pares.",
            notes="Visit floridapeersupport.org for local peers.",
            notes_es="Visite floridapeersupport.org.",
            hours="Monday–Friday",
            tags="tallahassee|leon|peer-support|recovery|reentry",
            services="Certified peer support|Recovery coaching|Mentoring|Warm handoffs|Training",
            county="Leon",
            served_counties="Leon",
            coverage="single",
            _source="https://www.floridapeersupport.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Florida Rights Restoration Coalition",
            category="reentry-organizations",
            region="Orlando / Orange County",
            description="Florida Rights Restoration Coalition advocates for returning citizens and helps eligible Floridians restore voting rights and navigate civic reintegration after felony convictions. Staff connect justice-involved adults from FDC custody and Orange County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Orlando / Orange County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Florida Rights Restoration Coalition aboga por ciudadanos que regresan y ayuda a floridanos elegibles a restaurar derechos de voto y navegar la reintegración cívica después de condenas por delito grave. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Orange con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Orlando / Orange County.",
            address="1800 Mercy Drive",
            city="Orlando",
            phone="407-960-1849",
            email="",
            website="https://www.floridarrc.com",
            eligibility="Returning citizens seeking rights restoration and civic reintegration support.",
            eligibility_es="Ciudadanos que regresan que buscan restauración de derechos y apoyo de reintegración cívica.",
            notes="Visit floridarrc.com for workshops and clinics.",
            notes_es="Visite floridarrc.com.",
            hours="Monday–Friday",
            tags="orlando|orange|reentry-organizations|advocacy|rights-restoration",
            services="Rights restoration help|Voting rights|Advocacy|Community workshops|Legal clinic referrals",
            county="Orange",
            served_counties="Orange",
            coverage="single",
            _source="https://www.floridarrc.com",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Florida Department of Law Enforcement — Criminal History",
            category="state-agency",
            region="Tallahassee / Leon County",
            description="FDLE provides criminal history record checks and seal/expunge eligibility information needed by returning citizens seeking employment, housing, and occupational licensing across Florida. Staff connect justice-involved adults from FDC custody and Leon County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Tallahassee / Leon County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="FDLE proporciona verificaciones de historial criminal e información de elegibilidad para sellar o eliminar antecedentes necesaria para ciudadanos que regresan que buscan empleo, vivienda y licencias ocupacionales en Florida. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Leon con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Tallahassee / Leon County.",
            address="2331 Phillips Road",
            city="Tallahassee",
            phone="850-410-7000",
            email="",
            website="https://www.fdle.state.fl.us",
            eligibility="Florida residents requesting criminal history records or seal/expunge information.",
            eligibility_es="Residentes de Florida que solicitan registros de historial criminal o información de sellado.",
            notes="Visit fdle.state.fl.us for record requests and seal/expunge guides.",
            notes_es="Visite fdle.state.fl.us.",
            hours="Monday–Friday",
            tags="tallahassee|leon|state-agency|records|reentry",
            services="Criminal history checks|Seal and expunge info|Background check guidance|Record review|Licensing resources",
            county="Leon",
            served_counties="Leon",
            coverage="single",
            _source="https://www.fdle.state.fl.us",
            _source_type="government",
            _confidence="high",
        )

    add(
            name="Florida Department of Commerce — Reentry Employment",
            category="state-agency",
            region="Tallahassee / Leon County",
            description="The Florida Department of Commerce coordinates statewide workforce and reentry employment initiatives linking returning citizens to CareerSource boards, apprenticeships, and fair-chance hiring programs. Staff connect justice-involved adults from FDC custody and Leon County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Tallahassee / Leon County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="El Departamento de Comercio de Florida coordina iniciativas estatales de fuerza laboral y empleo de reinserción vinculando a ciudadanos que regresan con juntas CareerSource, aprendizajes y programas de contratación de segunda oportunidad. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Leon con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Tallahassee / Leon County.",
            address="2601 Blair Stone Road",
            city="Tallahassee",
            phone="850-717-0442",
            email="",
            website="https://www.floridajobs.org",
            eligibility="Returning citizens and employers seeking state reentry workforce programs.",
            eligibility_es="Ciudadanos que regresan y empleadores que buscan programas estatales de reinserción laboral.",
            notes="Visit floridajobs.org/reentry resources.",
            notes_es="Visite floridajobs.org.",
            hours="Monday–Friday",
            tags="statewide|state-agency|employment|reentry|careersource",
            services="Workforce policy|Reentry employment programs|Apprenticeship referrals|Employer incentives|CareerSource linkage",
            county="Leon",
            served_counties="Leon",
            coverage="statewide",
            _source="https://www.floridajobs.org",
            _source_type="government",
            _confidence="high",
        )
