"""Tier A closure for Florida counties below 3 core categories."""

def register_tier_a_closure(add):
    add(
        name="CareerSource Suncoast — Manatee County",
        category="employment", region="Bradenton / Manatee County",
        description="CareerSource Suncoast connects Manatee County job seekers—including justice-involved adults after FDC release or Manatee County Jail—to WIOA-funded career coaching, training referrals, and fair-chance employment navigation. Staff connect participants to MyACCESS benefits, local healthcare, and reentry partners—not emergency cash or probation reporting unless noted.",
        description_es="Servicios para residentes del condado Manatee incluidos adultos con antecedentes penales; el personal conecta con beneficios MyACCESS, salud local y aliados de reinserción.",
        address="3660 63rd Avenue East", city="Bradenton", phone="941-358-4200", email="",
        website="https://careersourcesuncoast.com",
        eligibility="Manatee County residents including justice-involved adults; core services free where noted.",
        eligibility_es="Residentes del condado Manatee incluidos adultos con antecedentes penales.",
        notes="Call 941-358-4200 for intake and hours.",
        notes_es="Llame al 941-358-4200 para admisión y horario.",
        hours="Monday–Friday business hours; call for current schedule",
        tags="manatee|employment|reentry|fair-chance",
        services="Career coaching|Training referrals|Job placement|Benefits navigation",
        county="Manatee", served_counties="Manatee", coverage="single",
        _source="https://careersourcesuncoast.com", _source_type="government", _confidence="high",
    )
    add(
        name="CareerSource Central Florida — Osceola County",
        category="employment", region="Kissimmee / Osceola County",
        description="CareerSource Central Florida serves Osceola County with free career services linking returning citizens to training, job placement, and MyACCESS benefits navigation partners. Staff connect participants to MyACCESS benefits, local healthcare, and reentry partners—not emergency cash or probation reporting unless noted.",
        description_es="Servicios para residentes del condado Osceola incluidos adultos con antecedentes penales; el personal conecta con beneficios MyACCESS, salud local y aliados de reinserción.",
        address="3501 W Vine Street", city="Kissimmee", phone="407-531-1222", email="",
        website="https://careersourcecf.com",
        eligibility="Osceola County residents including justice-involved adults; core services free where noted.",
        eligibility_es="Residentes del condado Osceola incluidos adultos con antecedentes penales.",
        notes="Call 407-531-1222 for intake and hours.",
        notes_es="Llame al 407-531-1222 para admisión y horario.",
        hours="Monday–Friday business hours; call for current schedule",
        tags="osceola|employment|reentry|fair-chance",
        services="Career coaching|Training referrals|Job placement|Benefits navigation",
        county="Osceola", served_counties="Osceola", coverage="single",
        _source="https://careersourcecf.com", _source_type="government", _confidence="high",
    )
    add(
        name="AdventHealth Kissimmee (serves Osceola County)",
        category="healthcare", region="Kissimmee / Osceola County",
        description="AdventHealth Kissimmee provides emergency and primary care for Osceola County residents including uninsured and Medicaid patients such as returning citizens establishing medical care. Staff connect participants to MyACCESS benefits, local healthcare, and reentry partners—not emergency cash or probation reporting unless noted.",
        description_es="Servicios para residentes del condado Osceola incluidos adultos con antecedentes penales; el personal conecta con beneficios MyACCESS, salud local y aliados de reinserción.",
        address="2450 N Orange Blossom Trail", city="Kissimmee", phone="407-847-9355", email="",
        website="https://www.adventhealth.com",
        eligibility="Osceola County residents including justice-involved adults; core services free where noted.",
        eligibility_es="Residentes del condado Osceola incluidos adultos con antecedentes penales.",
        notes="Call 407-847-9355 for intake and hours.",
        notes_es="Llame al 407-847-9355 para admisión y horario.",
        hours="Monday–Friday business hours; call for current schedule",
        tags="osceola|healthcare|reentry|fair-chance",
        services="Career coaching|Training referrals|Job placement|Benefits navigation",
        county="Osceola", served_counties="Osceola", coverage="single",
        _source="https://www.adventhealth.com", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="CareerSource Central Florida — Seminole County",
        category="employment", region="Sanford / Seminole County",
        description="CareerSource Central Florida Seminole location connects justice-involved job seekers to WIOA career coaching, training, and fair-chance employer referrals across Sanford and Seminole County. Staff connect participants to MyACCESS benefits, local healthcare, and reentry partners—not emergency cash or probation reporting unless noted.",
        description_es="Servicios para residentes del condado Seminole incluidos adultos con antecedentes penales; el personal conecta con beneficios MyACCESS, salud local y aliados de reinserción.",
        address="7450 Futures Drive", city="Sanford", phone="407-531-1222", email="",
        website="https://careersourcecf.com",
        eligibility="Seminole County residents including justice-involved adults; core services free where noted.",
        eligibility_es="Residentes del condado Seminole incluidos adultos con antecedentes penales.",
        notes="Call 407-531-1222 for intake and hours.",
        notes_es="Llame al 407-531-1222 para admisión y horario.",
        hours="Monday–Friday business hours; call for current schedule",
        tags="seminole|employment|reentry|fair-chance",
        services="Career coaching|Training referrals|Job placement|Benefits navigation",
        county="Seminole", served_counties="Seminole", coverage="single",
        _source="https://careersourcecf.com", _source_type="government", _confidence="high",
    )
    add(
        name="CareerSource Flagler Volusia — Volusia County",
        category="employment", region="Daytona Beach / Volusia County",
        description="CareerSource Flagler Volusia provides free employment services for Volusia County residents including returning citizens from FDC custody and Volusia County corrections seeking job placement and training. Staff connect participants to MyACCESS benefits, local healthcare, and reentry partners—not emergency cash or probation reporting unless noted.",
        description_es="Servicios para residentes del condado Volusia incluidos adultos con antecedentes penales; el personal conecta con beneficios MyACCESS, salud local y aliados de reinserción.",
        address="3598 Forest Hill Boulevard", city="Daytona Beach", phone="386-323-7071", email="",
        website="https://www.careersourcefv.com",
        eligibility="Volusia County residents including justice-involved adults; core services free where noted.",
        eligibility_es="Residentes del condado Volusia incluidos adultos con antecedentes penales.",
        notes="Call 386-323-7071 for intake and hours.",
        notes_es="Llame al 386-323-7071 para admisión y horario.",
        hours="Monday–Friday business hours; call for current schedule",
        tags="volusia|employment|reentry|fair-chance",
        services="Career coaching|Training referrals|Job placement|Benefits navigation",
        county="Volusia", served_counties="Volusia", coverage="single",
        _source="https://www.careersourcefv.com", _source_type="government", _confidence="high",
    )
