"""Phase 4 program-level expansion entries for Florida reentry resources."""


def register_phase4(add):
    add(
            name="South Florida Behavioral Health Network",
            category="healthcare",
            region="Miami / Miami-Dade County",
            description="South Florida Behavioral Health Network coordinates Medicaid behavioral health services for Miami-Dade and Monroe county residents including returning citizens with mental health and substance use needs. Staff connect justice-involved adults from FDC custody and Miami-Dade County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Miami / Miami-Dade County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="South Florida Behavioral Health Network coordina servicios de salud conductual Medicaid para residentes de Miami-Dade y Monroe. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Miami-Dade con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Miami / Miami-Dade County. Contact the program directly to confirm current hours, eligibility, and intake requirements before visiting in person.",
            address="2950 NW 75th Street",
            city="Miami",
            phone="305-623-3500",
            email="",
            website="https://www.sfbhn.org",
            eligibility="Miami-Dade and Monroe residents with Medicaid behavioral health needs.",
            eligibility_es="Residentes de Miami-Dade y Monroe con necesidades de salud conductual Medicaid.",
            notes="Call 305-623-3500 for provider network.",
            notes_es="Llame al 305-623-3500.",
            hours="Monday–Friday",
            tags="miami|miami-dade|healthcare|behavioral-health|reentry",
            services="Behavioral health network|Provider referrals|Medicaid navigation|Crisis linkage|Treatment coordination",
            county="Miami-Dade",
            served_counties="Miami-Dade",
            coverage="single",
            _source="https://www.sfbhn.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Spectrum Programs — Substance Use Treatment",
            category="substance-use-treatment",
            region="Miami / Miami-Dade County",
            description="Spectrum Programs provides outpatient substance use treatment and DUI services for Miami-Dade residents including FDC probation referrals, accepting Medicaid and sliding-fee payment. Staff connect justice-involved adults from FDC custody and Miami-Dade County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Miami / Miami-Dade County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Spectrum Programs ofrece tratamiento ambulatorio de uso de sustancias y servicios DUI para residentes de Miami-Dade incluidas referencias de probatoria FDC. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Miami-Dade con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Miami / Miami-Dade County.",
            address="6100 Blue Lagoon Drive",
            city="Miami",
            phone="305-634-7734",
            email="",
            website="https://www.spectrumprograms.com",
            eligibility="Miami-Dade residents with substance use disorders; justice-involved referrals accepted.",
            eligibility_es="Residentes de Miami-Dade con trastornos por uso de sustancias.",
            notes="Call 305-634-7734 for assessment.",
            notes_es="Llame al 305-634-7734.",
            hours="Monday–Friday",
            tags="miami|miami-dade|substance-use|treatment|reentry",
            services="Outpatient treatment|DUI programs|Medicaid billing|Probation referrals|Recovery support",
            county="Miami-Dade",
            served_counties="Miami-Dade",
            coverage="single",
            _source="https://www.spectrumprograms.com",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Broward Addiction Recovery Center",
            category="substance-use-treatment",
            region="Fort Lauderdale / Broward County",
            description="Broward Addiction Recovery Center provides county-funded detox, residential, and outpatient substance use treatment for Broward residents including court and FDC referrals. Staff connect justice-involved adults from FDC custody and Broward County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Fort Lauderdale / Broward County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Broward Addiction Recovery Center ofrece desintoxicación, tratamiento residencial y ambulatorio financiado por el condado para residentes de Broward. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Broward con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Fort Lauderdale / Broward County.",
            address="3270 NW 29th Court",
            city="Fort Lauderdale",
            phone="954-357-4900",
            email="",
            website="https://www.broward.org/addictionrecovery",
            eligibility="Broward County residents; court and FDC referrals accepted.",
            eligibility_es="Residentes del condado Broward; referencias judiciales y FDC aceptadas.",
            notes="Call 954-357-4900 for intake.",
            notes_es="Llame al 954-357-4900.",
            hours="24/7 detox access",
            tags="fort-lauderdale|broward|substance-use|detox|reentry",
            services="Detox|Residential treatment|Outpatient services|Court referrals|Medicaid services",
            county="Broward",
            served_counties="Broward",
            coverage="single",
            _source="https://www.broward.org/addictionrecovery",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Salvation Army — Red Shield Lodge",
            category="housing",
            region="St. Petersburg / Pinellas County",
            description="Salvation Army Red Shield Lodge provides emergency shelter and transitional housing for homeless adults in Pinellas County including justice-involved men and women after FDC release. Staff connect justice-involved adults from FDC custody and Pinellas County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across St. Petersburg / Pinellas County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Salvation Army Red Shield Lodge ofrece refugio de emergencia y vivienda transicional para adultos sin hogar en el condado Pinellas incluidas personas con antecedentes penales. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Pinellas con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en St. Petersburg / Pinellas County.",
            address="1404 4th Street South",
            city="St. Petersburg",
            phone="727-822-4958",
            email="",
            website="https://www.salvationarmyflorida.org",
            eligibility="Homeless Pinellas County adults; justice-involved welcome.",
            eligibility_es="Adultos sin hogar del condado Pinellas; personas con antecedentes penales bienvenidas.",
            notes="Call 727-822-4958 for bed availability.",
            notes_es="Llame al 727-822-4958.",
            hours="Shelter 24/7",
            tags="st-petersburg|pinellas|housing|shelter|reentry",
            services="Emergency shelter|Transitional housing|Meals|Case management|Employment referrals",
            county="Pinellas",
            served_counties="Pinellas",
            coverage="single",
            _source="https://www.salvationarmyflorida.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Tampa Crossroads — Veterans Housing",
            category="veterans",
            region="Tampa / Hillsborough County",
            description="Tampa Crossroads operates supportive housing and case management for homeless veterans in Hillsborough County including justice-involved veterans connecting to VA benefits and CareerSource Tampa Bay. Staff connect justice-involved adults from FDC custody and Hillsborough County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Tampa / Hillsborough County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Tampa Crossroads opera vivienda de apoyo y manejo de casos para veteranos sin hogar en el condado Hillsborough incluidos veteranos con antecedentes penales. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Hillsborough con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Tampa / Hillsborough County.",
            address="1301 East Columbus Drive",
            city="Tampa",
            phone="813-247-7111",
            email="",
            website="https://www.tampacrossroads.com",
            eligibility="Homeless veterans in Hillsborough County; DD-214 required.",
            eligibility_es="Veteranos sin hogar en el condado Hillsborough; se requiere DD-214.",
            notes="Call 813-247-7111 for veteran intake.",
            notes_es="Llame al 813-247-7111.",
            hours="Monday–Friday",
            tags="tampa|hillsborough|veterans|housing|reentry",
            services="Veteran supportive housing|VA benefits help|Case management|Employment referrals|Peer support",
            county="Hillsborough",
            served_counties="Hillsborough",
            coverage="single",
            _source="https://www.tampacrossroads.com",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Goodwill Suncoast — Reentry Employment",
            category="employment",
            region="St. Petersburg / Pinellas County",
            description="Goodwill Suncoast provides job training, thrift-store employment, and reentry career services for Pinellas, Manatee, and Sarasota county residents including justice-involved adults. Staff connect justice-involved adults from FDC custody and Pinellas County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across St. Petersburg / Pinellas County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Goodwill Suncoast ofrece capacitación laboral, empleo en tiendas de segunda mano y servicios de carrera de reinserción para residentes de Pinellas, Manatee y Sarasota. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Pinellas con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en St. Petersburg / Pinellas County.",
            address="10596 Gandy Boulevard",
            city="St. Petersburg",
            phone="727-523-1512",
            email="",
            website="https://www.goodwill-suncoast.org",
            eligibility="Open to Pinellas, Manatee, Sarasota job seekers including justice-involved individuals.",
            eligibility_es="Abierto a buscadores de empleo de Pinellas, Manatee y Sarasota.",
            notes="Visit goodwill-suncoast.org for career center hours.",
            notes_es="Visite goodwill-suncoast.org.",
            hours="Monday–Saturday",
            tags="st-petersburg|pinellas|employment|goodwill|reentry",
            services="Job training|Thrift employment|Career services|Skills workshops|Fair-chance hiring",
            county="Pinellas",
            served_counties="Pinellas",
            coverage="single",
            _source="https://www.goodwill-suncoast.org",
            _source_type="government",
            _confidence="high",
        )

    add(
            name="Orlando Union Rescue Mission",
            category="housing",
            region="Orlando / Orange County",
            description="Orlando Union Rescue Mission provides emergency shelter, addiction recovery, and life transformation programs for homeless men and women in Orange County including justice-involved adults. Staff connect justice-involved adults from FDC custody and Orange County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Orlando / Orange County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Orlando Union Rescue Mission ofrece refugio de emergencia, recuperación de adicciones y programas de transformación de vida para hombres y mujeres sin hogar en el condado Orange. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Orange con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Orlando / Orange County.",
            address="1521 W Washington Street",
            city="Orlando",
            phone="407-422-4851",
            email="",
            website="https://www.orm.org",
            eligibility="Homeless Orange County adults; justice-involved participants in recovery programs.",
            eligibility_es="Adultos sin hogar del condado Orange; participantes con antecedentes penales en programas de recuperación.",
            notes="Call 407-422-4851 for intake.",
            notes_es="Llame al 407-422-4851.",
            hours="Shelter 24/7",
            tags="orlando|orange|housing|shelter|recovery|reentry",
            services="Emergency shelter|Addiction recovery|Life skills|Workforce programs|Faith-based support",
            county="Orange",
            served_counties="Orange",
            coverage="single",
            _source="https://www.orm.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Second Harvest Food Bank of Central Florida",
            category="food-nutrition",
            region="Orlando / Orange County",
            description="Second Harvest Food Bank of Central Florida distributes groceries to partner pantries across Orange, Osceola, Seminole, and Brevard counties for food-insecure families including returning citizens awaiting SNAP. Staff connect justice-involved adults from FDC custody and Orange County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Orlando / Orange County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Second Harvest Food Bank of Central Florida distribuye comestibles a despensas asociadas en Orange, Osceola, Seminole y Brevard para familias con inseguridad alimentaria incluidos ciudadanos que regresan. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Orange con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Orlando / Orange County.",
            address="411 Mercy Drive",
            city="Orlando",
            phone="407-295-1066",
            email="",
            website="https://www.feedhopenow.org",
            eligibility="Food-insecure Central Florida residents; pantry eligibility varies.",
            eligibility_es="Residentes del centro de Florida con inseguridad alimentaria.",
            notes="Find pantries at feedhopenow.org; call 407-295-1066.",
            notes_es="Encuentre despensas en feedhopenow.org.",
            hours="Monday–Friday",
            tags="orlando|orange|food-nutrition|food-bank|reentry",
            services="Food distribution|Pantry network|SNAP application guidance|Mobile pantries|Partner referrals",
            county="Orange",
            served_counties="Orange",
            coverage="single",
            _source="https://www.feedhopenow.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Brevard Neighborhood Development Coalition",
            category="housing",
            region="Melbourne / Brevard County",
            description="Brevard Neighborhood Development Coalition builds affordable housing and provides homebuyer education for low-income Brevard County families including returning citizens meeting income guidelines. Staff connect justice-involved adults from FDC custody and Brevard County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Melbourne / Brevard County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Brevard Neighborhood Development Coalition construye vivienda asequible y ofrece educación para compradores de vivienda para familias de bajos ingresos del condado Brevard incluidos ciudadanos que regresan. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Brevard con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Melbourne / Brevard County.",
            address="1619 Oak Street",
            city="Melbourne",
            phone="321-757-3222",
            email="",
            website="https://www.bndcoalition.org",
            eligibility="Low-income Brevard households meeting program income limits.",
            eligibility_es="Hogares de bajos ingresos de Brevard que cumplan límites de ingresos.",
            notes="Call 321-757-3222 for programs.",
            notes_es="Llame al 321-757-3222.",
            hours="Monday–Friday",
            tags="melbourne|brevard|housing|affordable|reentry",
            services="Affordable housing|Homebuyer education|Financial coaching|Rental counseling|Neighborhood development",
            county="Brevard",
            served_counties="Brevard",
            coverage="single",
            _source="https://www.bndcoalition.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="CareerSource Brevard",
            category="employment",
            region="Rockledge / Brevard County",
            description="CareerSource Brevard connects Brevard County job seekers including justice-involved adults to WIOA training, aerospace and healthcare career pathways, and fair-chance employers. Staff connect justice-involved adults from FDC custody and Brevard County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Rockledge / Brevard County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="CareerSource Brevard conecta buscadores de empleo del condado Brevard incluidos adultos con antecedentes penales a capacitación WIOA y empleadores de segunda oportunidad. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Brevard con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Rockledge / Brevard County.",
            address="2725 Judge Fran Jamieson Way",
            city="Rockledge",
            phone="321-504-7600",
            email="",
            website="https://www.careersourcebrevard.com",
            eligibility="Open to Brevard County job seekers including justice-involved individuals.",
            eligibility_es="Abierto a buscadores de empleo del condado Brevard.",
            notes="Register at careersourcebrevard.com.",
            notes_es="Regístrese en careersourcebrevard.com.",
            hours="Monday–Friday",
            tags="rockledge|brevard|employment|careersource|reentry",
            services="Job search|WIOA training|Career pathways|Fair-chance employers|Resume coaching",
            county="Brevard",
            served_counties="Brevard",
            coverage="single",
            _source="https://www.careersourcebrevard.com",
            _source_type="government",
            _confidence="high",
        )

    add(
            name="Seminole County Sheriff — Reentry Unit",
            category="probation-parole",
            region="Sanford / Seminole County",
            description="The Seminole County Sheriff Reentry Unit coordinates jail transition planning and community referrals for justice-involved adults releasing to Seminole, Orange, and Osceola counties. Staff connect justice-involved adults from FDC custody and Seminole County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Sanford / Seminole County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="La Unidad de Reinserción del Sheriff del condado Seminole coordina planificación de transición de la cárcel y referencias comunitarias para adultos con antecedentes penales. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Seminole con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Sanford / Seminole County.",
            address="100 Eslinger Way",
            city="Sanford",
            phone="407-665-6600",
            email="",
            website="https://www.seminolesheriff.org",
            eligibility="Individuals releasing from Seminole County jail; community reentry referrals.",
            eligibility_es="Personas que salen de la cárcel del condado Seminole; referencias de reinserción comunitaria.",
            notes="Coordinate through jail reentry staff before release.",
            notes_es="Coordine con el personal de reinserción de la cárcel antes de la liberación.",
            hours="Monday–Friday",
            tags="sanford|seminole|probation-parole|reentry|jail",
            services="Jail transition planning|Community referrals|Resource navigation|Employment linkage|Benefits help",
            county="Seminole",
            served_counties="Seminole",
            coverage="single",
            _source="https://www.seminolesheriff.org",
            _source_type="government",
            _confidence="high",
        )

    add(
            name="Osceola Council on Aging — Transportation",
            category="transportation",
            region="Kissimmee / Osceola County",
            description="Osceola Council on Aging provides paratransit and medical transportation for seniors and disabled Osceola County residents including returning citizens needing rides to probation, treatment, and CareerSource appointments. Staff connect justice-involved adults from FDC custody and Osceola County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Kissimmee / Osceola County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Osceola Council on Aging proporciona paratransporte y transporte médico para residentes mayores y con discapacidad del condado Osceola incluidos ciudadanos que regresan que necesitan transporte a citas de probatoria y tratamiento. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Osceola con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Kissimmee / Osceola County.",
            address="700 Generation Point",
            city="Kissimmee",
            phone="407-846-8532",
            email="",
            website="https://www.osceolagenerations.org",
            eligibility="Osceola County seniors and disabled residents; some programs serve broader low-income riders.",
            eligibility_es="Residentes mayores y con discapacidad del condado Osceola.",
            notes="Call 407-846-8532 to schedule rides.",
            notes_es="Llame al 407-846-8532.",
            hours="Monday–Friday",
            tags="kissimmee|osceola|transportation|paratransit|reentry",
            services="Paratransit|Medical transportation|Senior rides|Appointment transport|Medicaid transport referrals",
            county="Osceola",
            served_counties="Osceola",
            coverage="single",
            _source="https://www.osceolagenerations.org",
            _source_type="government",
            _confidence="high",
        )

    add(
            name="Manatee Glens — Behavioral Health",
            category="healthcare",
            region="Bradenton / Manatee County",
            description="Manatee Glens provides behavioral health, crisis, and substance use services for Manatee and DeSoto county residents including justice-involved adults referred by FDC and courts. Staff connect justice-involved adults from FDC custody and Manatee County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Bradenton / Manatee County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Manatee Glens brinda salud conductual, crisis y servicios de uso de sustancias para residentes de Manatee y DeSoto incluidos adultos con antecedentes penales. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Manatee con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Bradenton / Manatee County.",
            address="379 6th Avenue West",
            city="Bradenton",
            phone="941-782-4150",
            email="",
            website="https://www.manateeglens.org",
            eligibility="Manatee and DeSoto residents; Medicaid accepted; crisis line 24/7.",
            eligibility_es="Residentes de Manatee y DeSoto; línea de crisis 24/7.",
            notes="Crisis line 941-782-4150; walk-in crisis center available.",
            notes_es="Línea de crisis 941-782-4150.",
            hours="24/7 crisis",
            tags="bradenton|manatee|healthcare|behavioral-health|reentry",
            services="Behavioral health|Crisis services|Substance use treatment|Medicaid services|Court referrals",
            county="Manatee",
            served_counties="Manatee",
            coverage="single",
            _source="https://www.manateeglens.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Volusia/Flagler Family YMCA — Reentry Support",
            category="peer-support",
            region="Daytona Beach / Volusia County",
            description="Volusia/Flagler Family YMCA offers reentry peer support groups, wellness programming, and community connections for justice-involved adults in Volusia and Flagler counties. Staff connect justice-involved adults from FDC custody and Volusia County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Daytona Beach / Volusia County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Volusia/Flagler Family YMCA ofrece grupos de apoyo entre pares de reinserción, programación de bienestar y conexiones comunitarias para adultos con antecedentes penales en Volusia y Flagler. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Volusia con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Daytona Beach / Volusia County.",
            address="1100 Dunlawton Avenue",
            city="Daytona Beach",
            phone="386-253-9622",
            email="",
            website="https://www.vfymca.org",
            eligibility="Volusia and Flagler residents in reentry; open enrollment for peer groups.",
            eligibility_es="Residentes de Volusia y Flagler en reinserción.",
            notes="Contact local YMCA branch for schedule.",
            notes_es="Contacte la sucursal local YMCA.",
            hours="Varies by branch",
            tags="daytona-beach|volusia|peer-support|reentry|wellness",
            services="Peer support groups|Wellness programming|Community connections|Referrals|Life skills",
            county="Volusia",
            served_counties="Volusia",
            coverage="single",
            _source="https://www.vfymca.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Northeast Florida Community Action Agency",
            category="basic-needs",
            region="Jacksonville / Duval County",
            description="Northeast Florida Community Action Agency provides utility assistance, weatherization, and family support for low-income Duval, Clay, and Nassau county households including returning citizens. Staff connect justice-involved adults from FDC custody and Duval County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Jacksonville / Duval County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Northeast Florida Community Action Agency proporciona asistencia de servicios públicos, climatización y apoyo familiar para hogares de bajos ingresos de Duval, Clay y Nassau incluidos ciudadanos que regresan. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Duval con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Jacksonville / Duval County.",
            address="421 West Church Street",
            city="Jacksonville",
            phone="904-398-7472",
            email="",
            website="https://www.nfcaa.net",
            eligibility="Low-income Duval, Clay, Nassau households meeting LIHEAP and program guidelines.",
            eligibility_es="Hogares de bajos ingresos de Duval, Clay y Nassau.",
            notes="Call 904-398-7472 for intake.",
            notes_es="Llame al 904-398-7472.",
            hours="Monday–Friday",
            tags="jacksonville|duval|basic-needs|utility|reentry",
            services="Utility assistance|Weatherization|Family support|Energy relief|Resource navigation",
            county="Duval",
            served_counties="Duval",
            coverage="single",
            _source="https://www.nfcaa.net",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Gateway Community Services — Substance Use",
            category="substance-use-treatment",
            region="Jacksonville / Duval County",
            description="Gateway Community Services provides outpatient substance use treatment and recovery housing referrals for Duval County residents including FDC probation and drug court participants. Staff connect justice-involved adults from FDC custody and Duval County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Jacksonville / Duval County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Gateway Community Services ofrece tratamiento ambulatorio de uso de sustancias y referencias de vivienda de recuperación para residentes del condado Duval incluidos participantes de probatoria FDC. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Duval con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Jacksonville / Duval County.",
            address="555 Stockton Street",
            city="Jacksonville",
            phone="904-387-4661",
            email="",
            website="https://www.gatewaycommunity.com",
            eligibility="Duval County residents with substance use disorders; justice-involved referrals accepted.",
            eligibility_es="Residentes del condado Duval con trastornos por uso de sustancias.",
            notes="Call 904-387-4661 for assessment.",
            notes_es="Llame al 904-387-4661.",
            hours="Monday–Friday",
            tags="jacksonville|duval|substance-use|outpatient|reentry",
            services="Outpatient treatment|Recovery housing referrals|Drug court services|Medicaid billing|Peer support",
            county="Duval",
            served_counties="Duval",
            coverage="single",
            _source="https://www.gatewaycommunity.com",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Tallahassee Senior Center — Reentry Peer Navigators",
            category="peer-support",
            region="Tallahassee / Leon County",
            description="Tallahassee community peer navigators connect justice-involved Leon County adults to local housing, CareerSource Capital Region, and DCF benefits through neighborhood resource networks. Staff connect justice-involved adults from FDC custody and Leon County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Tallahassee / Leon County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Navegadores comunitarios entre pares de Tallahassee conectan a adultos con antecedentes penales del condado Leon con vivienda local, CareerSource Capital Region y beneficios DCF. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Leon con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Tallahassee / Leon County.",
            address="1400 N Monroe Street",
            city="Tallahassee",
            phone="850-891-4000",
            email="",
            website="https://www.talgov.com",
            eligibility="Justice-involved Leon County residents seeking community reentry support.",
            eligibility_es="Residentes del condado Leon con antecedentes penales que buscan apoyo de reinserción.",
            notes="Call 850-891-4000 for community resources.",
            notes_es="Llame al 850-891-4000.",
            hours="Monday–Friday",
            tags="tallahassee|leon|peer-support|reentry|navigation",
            services="Peer navigation|Community referrals|Benefits help|Housing linkage|Employment support",
            county="Leon",
            served_counties="Leon",
            coverage="single",
            _source="https://www.talgov.com",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Elder Care Services — Transportation",
            category="transportation",
            region="Tallahassee / Leon County",
            description="Elder Care Services provides transportation and caregiver support in the Big Bend including rides to medical, probation, and employment appointments for disabled and senior Leon County residents in reentry. Staff connect justice-involved adults from FDC custody and Leon County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Tallahassee / Leon County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Elder Care Services proporciona transporte y apoyo a cuidadores en el Big Bend incluidos viajes a citas médicas, de probatoria y empleo para residentes mayores y con discapacidad del condado Leon en reinserción. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Leon con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Tallahassee / Leon County.",
            address="2518 West Tennessee Street",
            city="Tallahassee",
            phone="850-921-5554",
            email="",
            website="https://www.eldercarebigbend.org",
            eligibility="Leon and surrounding Big Bend residents meeting program eligibility.",
            eligibility_es="Residentes de Leon y el Big Bend que cumplan elegibilidad.",
            notes="Call 850-921-5554 to schedule.",
            notes_es="Llame al 850-921-5554.",
            hours="Monday–Friday",
            tags="tallahassee|leon|transportation|medical-rides|reentry",
            services="Medical transportation|Caregiver support|Appointment rides|Resource navigation|Senior services",
            county="Leon",
            served_counties="Leon",
            coverage="single",
            _source="https://www.eldercarebigbend.org",
            _source_type="government",
            _confidence="high",
        )

    add(
            name="Capital Area Transportation System",
            category="transportation",
            region="Tallahassee / Leon County",
            description="StarMetro/Capital Area Transportation System provides fixed-route and paratransit bus service in Tallahassee and Leon County helping returning citizens reach probation, DCF, and CareerSource appointments. Staff connect justice-involved adults from FDC custody and Leon County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Tallahassee / Leon County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="StarMetro proporciona servicio de autobús de ruta fija y paratransporte en Tallahassee y el condado Leon ayudando a ciudadanos que regresan a llegar a citas de probatoria, DCF y CareerSource. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Leon con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Tallahassee / Leon County.",
            address="607 Appleyard Drive",
            city="Tallahassee",
            phone="850-606-0600",
            email="",
            website="https://www.talgov.com",
            eligibility="Leon County riders; reduced fares available for qualifying low-income residents.",
            eligibility_es="Pasajeros del condado Leon; tarifas reducidas disponibles.",
            notes="Visit talgov.com/starmetro for routes and fares.",
            notes_es="Visite talgov.com/starmetro.",
            hours="Varies by route",
            tags="tallahassee|leon|transportation|transit|reentry",
            services="Fixed-route bus|Paratransit|Reduced fares|Route planning|Accessibility services",
            county="Leon",
            served_counties="Leon",
            coverage="single",
            _source="https://www.talgov.com",
            _source_type="government",
            _confidence="high",
        )

    add(
            name="Pensacola Habitat for Humanity",
            category="housing",
            region="Pensacola / Escambia County",
            description="Pensacola Habitat for Humanity builds affordable homeownership for low-income Escambia and Santa Rosa families including returning citizens meeting sweat-equity requirements. Staff connect justice-involved adults from FDC custody and Escambia County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Pensacola / Escambia County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Pensacola Habitat for Humanity construye propiedad de vivienda asequible para familias de bajos ingresos de Escambia y Santa Rosa incluidos ciudadanos que regresan. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Escambia con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Pensacola / Escambia County.",
            address="300 W Leonard Street",
            city="Pensacola",
            phone="850-434-5456",
            email="",
            website="https://www.pensacolahabitat.org",
            eligibility="Low-income Escambia and Santa Rosa households meeting Habitat guidelines.",
            eligibility_es="Hogares de bajos ingresos de Escambia y Santa Rosa.",
            notes="Call 850-434-5456 for application.",
            notes_es="Llame al 850-434-5456.",
            hours="Monday–Friday",
            tags="pensacola|escambia|housing|habitat|reentry",
            services="Affordable homeownership|Sweat equity|Homebuyer education|Critical repair|Volunteer builds",
            county="Escambia",
            served_counties="Escambia",
            coverage="single",
            _source="https://www.pensacolahabitat.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Fort Myers Rescue Mission",
            category="housing",
            region="Fort Myers / Lee County",
            description="Fort Myers Rescue Mission provides emergency shelter, meals, and recovery programs for homeless adults in Lee County including justice-involved men and women after FDC release. Staff connect justice-involved adults from FDC custody and Lee County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Fort Myers / Lee County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Fort Myers Rescue Mission ofrece refugio de emergencia, comidas y programas de recuperación para adultos sin hogar en el condado Lee incluidas personas con antecedentes penales. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Lee con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Fort Myers / Lee County.",
            address="6900 Mission Lane",
            city="Fort Myers",
            phone="239-332-0300",
            email="",
            website="https://www.rescuemission.net",
            eligibility="Homeless Lee County adults; justice-involved welcome in recovery programs.",
            eligibility_es="Adultos sin hogar del condado Lee; personas con antecedentes penales bienvenidas.",
            notes="Call 239-332-0300 for intake.",
            notes_es="Llame al 239-332-0300.",
            hours="Shelter 24/7",
            tags="fort-myers|lee|housing|shelter|recovery|reentry",
            services="Emergency shelter|Meals|Recovery programs|Workforce training|Case management",
            county="Lee",
            served_counties="Lee",
            coverage="single",
            _source="https://www.rescuemission.net",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Sarasota County Veterans Services",
            category="veterans",
            region="Sarasota / Sarasota County",
            description="Sarasota County Veterans Services helps veterans and justice-involved veterans access VA benefits, discharge upgrades, and housing referrals through the county veterans service officer. Staff connect justice-involved adults from FDC custody and Sarasota County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Sarasota / Sarasota County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Sarasota County Veterans Services ayuda a veteranos y veteranos con antecedentes penales a acceder a beneficios VA, actualizaciones de baja y referencias de vivienda. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Sarasota con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Sarasota / Sarasota County.",
            address="1660 Ringling Boulevard",
            city="Sarasota",
            phone="941-861-5000",
            email="",
            website="https://www.scgov.net",
            eligibility="Sarasota County veterans; DD-214 or service documentation required.",
            eligibility_es="Veteranos del condado Sarasota; se requiere DD-214.",
            notes="Call 941-861-5000 for VSO appointment.",
            notes_es="Llame al 941-861-5000.",
            hours="Monday–Friday",
            tags="sarasota|sarasota|veterans|VA|reentry",
            services="VA benefits counseling|Discharge upgrade help|Housing referrals|Healthcare enrollment|State benefits",
            county="Sarasota",
            served_counties="Sarasota",
            coverage="single",
            _source="https://www.scgov.net",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Santa Fe College — Adult Education",
            category="education",
            region="Gainesville / Alachua County",
            description="Santa Fe College Adult Education offers GED preparation, ESL, and career pathway classes for Alachua and Bradford county residents including justice-involved adults rebuilding credentials for CareerSource employment. Staff connect justice-involved adults from FDC custody and Alachua County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Gainesville / Alachua County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Santa Fe College Adult Education ofrece preparación GED, ESL y clases de trayectoria profesional para residentes de Alachua y Bradford incluidos adultos con antecedentes penales. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Alachua con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Gainesville / Alachua County.",
            address="3000 NW 83rd Street",
            city="Gainesville",
            phone="352-395-5044",
            email="",
            website="https://www.sfcollege.edu",
            eligibility="Adults 16+ in Alachua and Bradford counties seeking GED or adult education.",
            eligibility_es="Adultos de 16+ años en Alachua y Bradford que buscan GED.",
            notes="Register at sfcollege.edu/adult-education.",
            notes_es="Regístrese en sfcollege.edu.",
            hours="Semester schedule",
            tags="gainesville|alachua|education|GED|reentry",
            services="GED preparation|ESL classes|Career pathways|Testing center|College transition",
            county="Alachua",
            served_counties="Alachua",
            coverage="single",
            _source="https://www.sfcollege.edu",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Polk State College — Reentry Education",
            category="education",
            region="Lakeland / Polk County",
            description="Polk State College provides GED, workforce certificates, and college transition for Polk County residents including returning citizens coordinating with CareerSource Polk and FDC probation. Staff connect justice-involved adults from FDC custody and Polk County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Lakeland / Polk County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Polk State College ofrece GED, certificados laborales y transición universitaria para residentes del condado Polk incluidos ciudadanos que regresan. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Polk con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Lakeland / Polk County.",
            address="999 Avenue H NE",
            city="Lakeland",
            phone="863-297-1000",
            email="",
            website="https://www.polk.edu",
            eligibility="Polk County adults seeking GED or workforce credentials.",
            eligibility_es="Adultos del condado Polk que buscan GED o credenciales laborales.",
            notes="Contact 863-297-1000 for adult education.",
            notes_es="Contacte al 863-297-1000.",
            hours="Semester schedule",
            tags="lakeland|polk|education|GED|workforce|reentry",
            services="GED classes|Workforce certificates|College transition|Career counseling|Financial aid help",
            county="Polk",
            served_counties="Polk",
            coverage="single",
            _source="https://www.polk.edu",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Gulf Coast Jewish Family & Community Services",
            category="family-children",
            region="Clearwater / Pinellas County",
            description="Gulf Coast JFCS provides counseling, adoption, and family stabilization for Pinellas and Pasco families including those affected by parental incarceration and reunification after FDC release. Staff connect justice-involved adults from FDC custody and Pinellas County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Clearwater / Pinellas County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Gulf Coast JFCS ofrece consejería, adopción y estabilización familiar para familias de Pinellas y Pasco incluidas las afectadas por encarcelación parental. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Pinellas con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Clearwater / Pinellas County.",
            address="14041 Icot Boulevard",
            city="Clearwater",
            phone="727-479-1800",
            email="",
            website="https://www.jfcs-pinellas.org",
            eligibility="Pinellas and Pasco families; sliding-fee counseling available.",
            eligibility_es="Familias de Pinellas y Pasco; consejería con tarifa móvil disponible.",
            notes="Call 727-479-1800 for intake.",
            notes_es="Llame al 727-479-1800.",
            hours="Monday–Friday",
            tags="clearwater|pinellas|family-children|counseling|reentry",
            services="Family counseling|Adoption services|Parenting support|Reunification help|Crisis counseling",
            county="Pinellas",
            served_counties="Pinellas",
            coverage="single",
            _source="https://www.jfcs-pinellas.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Palm Beach County Food Bank",
            category="food-nutrition",
            region="Lake Worth / Palm Beach County",
            description="Palm Beach County Food Bank distributes food to partner agencies across Palm Beach County for families including returning citizens awaiting MyACCESS SNAP benefits. Staff connect justice-involved adults from FDC custody and Palm Beach County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Lake Worth / Palm Beach County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Palm Beach County Food Bank distribuye alimentos a agencias asociadas en el condado Palm Beach para familias incluidos ciudadanos que regresan en espera de beneficios SNAP MyACCESS. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Palm Beach con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Lake Worth / Palm Beach County.",
            address="525 Gator Drive",
            city="Lake Worth Beach",
            phone="561-670-2518",
            email="",
            website="https://www.pbcfoodbank.org",
            eligibility="Food-insecure Palm Beach County residents via partner pantries.",
            eligibility_es="Residentes del condado Palm Beach con inseguridad alimentaria.",
            notes="Find agencies at pbcfoodbank.org.",
            notes_es="Encuentre agencias en pbcfoodbank.org.",
            hours="Monday–Friday",
            tags="lake-worth|palm-beach|food-nutrition|food-bank|reentry",
            services="Food distribution|Partner pantries|SNAP guidance|Mobile distributions|Agency network",
            county="Palm Beach",
            served_counties="Palm Beach",
            coverage="single",
            _source="https://www.pbcfoodbank.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Westcare Florida — Veterans Treatment",
            category="veterans",
            region="Pensacola / Escambia County",
            description="Westcare Florida provides veterans treatment court support, residential recovery, and behavioral health for justice-involved veterans in Escambia and Santa Rosa counties. Staff connect justice-involved adults from FDC custody and Escambia County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Pensacola / Escambia County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Westcare Florida ofrece apoyo de tribunal de tratamiento para veteranos, recuperación residencial y salud conductual para veteranos con antecedentes penales en Escambia y Santa Rosa. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Escambia con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Pensacola / Escambia County.",
            address="1000 W Moreno Street",
            city="Pensacola",
            phone="850-429-6900",
            email="",
            website="https://www.westcare.com",
            eligibility="Justice-involved veterans in Northwest Florida; veteran status required.",
            eligibility_es="Veteranos con antecedentes penales en el noroeste de Florida.",
            notes="Call 850-429-6900 for veteran programs.",
            notes_es="Llame al 850-429-6900.",
            hours="24/7 residential",
            tags="pensacola|escambia|veterans|treatment|reentry",
            services="Veterans treatment support|Residential recovery|Behavioral health|Court coordination|Peer support",
            county="Escambia",
            served_counties="Escambia",
            coverage="single",
            _source="https://www.westcare.com",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Boys Town Central Florida — Family Services",
            category="family-children",
            region="Orlando / Orange County",
            description="Boys Town Central Florida provides in-home family services, parenting support, and crisis intervention for Orange and Osceola families including reunification after parental incarceration. Staff connect justice-involved adults from FDC custody and Orange County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Orlando / Orange County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Boys Town Central Florida ofrece servicios familiares en el hogar, apoyo parental e intervención en crisis para familias de Orange y Osceola incluida reunificación después de encarcelación parental. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Orange con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Orlando / Orange County.",
            address="3901 E Colonial Drive",
            city="Orlando",
            phone="407-482-2400",
            email="",
            website="https://www.boystown.org",
            eligibility="Orange and Osceola families with children at risk; DCF and court referrals.",
            eligibility_es="Familias de Orange y Osceola con niños en riesgo.",
            notes="Call 407-482-2400 for family services.",
            notes_es="Llame al 407-482-2400.",
            hours="Monday–Friday",
            tags="orlando|orange|family-children|parenting|reentry",
            services="In-home family services|Parenting support|Crisis intervention|Reunification|Case management",
            county="Orange",
            served_counties="Orange",
            coverage="single",
            _source="https://www.boystown.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Miami-Dade Public Library — ID & Document Help",
            category="id-documentation",
            region="Miami / Miami-Dade County",
            description="Miami-Dade Public Library System offers free computer access, document printing, and notary services helping returning citizens gather materials for FLHSMV IDs and MyACCESS applications. Staff connect justice-involved adults from FDC custody and Miami-Dade County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Miami / Miami-Dade County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="El Sistema de Bibliotecas Públicas de Miami-Dade ofrece acceso gratuito a computadoras, impresión de documentos y servicios notariales ayudando a ciudadanos que regresan a reunir materiales para identificaciones FLHSMV y solicitudes MyACCESS. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Miami-Dade con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Miami / Miami-Dade County.",
            address="101 W Flagler Street",
            city="Miami",
            phone="305-375-2665",
            email="",
            website="https://www.mdpls.org",
            eligibility="Open to all Miami-Dade residents; free library card available.",
            eligibility_es="Abierto a todos los residentes de Miami-Dade.",
            notes="Visit mdpls.org for branch hours.",
            notes_es="Visite mdpls.org.",
            hours="Branch hours vary",
            tags="miami|miami-dade|id-documentation|library|reentry",
            services="Computer access|Document printing|Notary services|Online benefits applications|Research help",
            county="Miami-Dade",
            served_counties="Miami-Dade",
            coverage="single",
            _source="https://www.mdpls.org",
            _source_type="government",
            _confidence="high",
        )

    add(
            name="Tax Collector — Hillsborough Driver License",
            category="id-documentation",
            region="Tampa / Hillsborough County",
            description="The Hillsborough County Tax Collector issues FLHSMV driver licenses and state ID cards for Tampa residents including returning citizens with required identity documents for employment and MyACCESS enrollment. Staff connect justice-involved adults from FDC custody and Hillsborough County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Tampa / Hillsborough County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="El Recaudador de Impuestos del condado Hillsborough emite licencias de conducir FLHSMV y tarjetas de identificación estatal para residentes de Tampa incluidos ciudadanos que regresan. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Hillsborough con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Tampa / Hillsborough County.",
            address="601 E Kennedy Boulevard",
            city="Tampa",
            phone="813-635-5200",
            email="",
            website="https://www.hillstax.org",
            eligibility="Hillsborough County residents meeting FLHSMV documentation requirements.",
            eligibility_es="Residentes del condado Hillsborough que cumplan requisitos de documentación FLHSMV.",
            notes="Schedule at hillstax.org; bring required documents.",
            notes_es="Programe en hillstax.org.",
            hours="Monday–Friday",
            tags="tampa|hillsborough|id-documentation|driver-license|reentry",
            services="Driver license issuance|State ID cards|REAL ID|Appointment scheduling|Document checklist",
            county="Hillsborough",
            served_counties="Hillsborough",
            coverage="single",
            _source="https://www.hillstax.org",
            _source_type="government",
            _confidence="high",
        )

    add(
            name="St. Vincent de Paul — South Pinellas",
            category="basic-needs",
            region="St. Petersburg / Pinellas County",
            description="St. Vincent de Paul South Pinellas provides emergency food, utility help, and clothing for low-income Pinellas families including returning citizens rebuilding stability after FDC release. Staff connect justice-involved adults from FDC custody and Pinellas County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across St. Petersburg / Pinellas County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="St. Vincent de Paul South Pinellas proporciona alimentos de emergencia, ayuda con servicios públicos y ropa para familias de bajos ingresos de Pinellas incluidos ciudadanos que regresan. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Pinellas con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en St. Petersburg / Pinellas County.",
            address="384 15th Street North",
            city="St. Petersburg",
            phone="727-823-2516",
            email="",
            website="https://www.svdpstpete.org",
            eligibility="Low-income Pinellas County residents; walk-in and referral intake.",
            eligibility_es="Residentes de bajos ingresos del condado Pinellas.",
            notes="Call 727-823-2516 for assistance.",
            notes_es="Llame al 727-823-2516.",
            hours="Monday–Friday",
            tags="st-petersburg|pinellas|basic-needs|food|utility|reentry",
            services="Emergency food|Utility assistance|Clothing|Furniture|Resource navigation",
            county="Pinellas",
            served_counties="Pinellas",
            coverage="single",
            _source="https://www.svdpstpete.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Catholic Charities — Diocese of Orlando",
            category="basic-needs",
            region="Orlando / Orange County",
            description="Catholic Charities of Central Florida provides emergency assistance, immigration legal referrals, and family support for Orange, Osceola, and Seminole residents including returning citizens. Staff connect justice-involved adults from FDC custody and Orange County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Orlando / Orange County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Catholic Charities del Centro de Florida proporciona asistencia de emergencia, referencias legales de inmigración y apoyo familiar para residentes de Orange, Osceola y Seminole incluidos ciudadanos que regresan. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Orange con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Orlando / Orange County.",
            address="1819 N Semoran Boulevard",
            city="Orlando",
            phone="407-658-1818",
            email="",
            website="https://www.cflcc.org",
            eligibility="Low-income Central Florida residents; program eligibility varies.",
            eligibility_es="Residentes de bajos ingresos del centro de Florida.",
            notes="Call 407-658-1818 for services.",
            notes_es="Llame al 407-658-1818.",
            hours="Monday–Friday",
            tags="orlando|orange|basic-needs|emergency|reentry",
            services="Emergency assistance|Food help|Immigration referrals|Family support|Financial counseling",
            county="Orange",
            served_counties="Orange",
            coverage="single",
            _source="https://www.cflcc.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Jacksonville Transportation Authority",
            category="transportation",
            region="Jacksonville / Duval County",
            description="Jacksonville Transportation Authority provides fixed-route buses and paratransit Connexion service helping Duval County returning citizens reach probation, treatment, and employment appointments. Staff connect justice-involved adults from FDC custody and Duval County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Jacksonville / Duval County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Jacksonville Transportation Authority proporciona autobuses de ruta fija y servicio paratransporte Connexion ayudando a ciudadanos que regresan del condado Duval a llegar a citas de probatoria, tratamiento y empleo. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Duval con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Jacksonville / Duval County.",
            address="100 N Liberty Street",
            city="Jacksonville",
            phone="904-630-3100",
            email="",
            website="https://www.jtafla.com",
            eligibility="Duval County riders; reduced fares for qualifying residents.",
            eligibility_es="Pasajeros del condado Duval; tarifas reducidas para residentes elegibles.",
            notes="Visit jtafla.com for routes.",
            notes_es="Visite jtafla.com.",
            hours="Varies by route",
            tags="jacksonville|duval|transportation|transit|reentry",
            services="Fixed-route bus|Paratransit|Reduced fares|Route planning|Connexion service",
            county="Duval",
            served_counties="Duval",
            coverage="single",
            _source="https://www.jtafla.com",
            _source_type="government",
            _confidence="high",
        )

    add(
            name="Baker County FDC Probation",
            category="probation-parole",
            region="Macclenny / Baker County",
            description="FDC Baker County Probation supervises felony probationers in rural Baker County, coordinating referrals to CareerSource Northeast Florida and Macclenny health providers. Staff connect justice-involved adults from FDC custody and Baker County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Macclenny / Baker County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Probatoria FDC del condado Baker supervisa personas en probatoria por delito grave en el condado rural Baker, coordinando referencias a CareerSource Northeast Florida. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Baker con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Macclenny / Baker County.",
            address="32 N 5th Street",
            city="Macclenny",
            phone="904-259-4471",
            email="",
            website="https://www.fdc.myflorida.com/probation",
            eligibility="Adults under FDC supervision in Baker County.",
            eligibility_es="Adultos bajo supervisión FDC en el condado Baker.",
            notes="Report to assigned probation officer.",
            notes_es="Reporte al oficial de probatoria asignado.",
            hours="Monday–Friday",
            tags="macclenny|baker|probation-parole|FDC|rural|reentry",
            services="Probation supervision|Treatment referrals|Employment coordination|Compliance reporting|Rural reentry linkage",
            county="Baker",
            served_counties="Baker",
            coverage="single",
            _source="https://www.fdc.myflorida.com/probation",
            _source_type="government",
            _confidence="high",
        )

    add(
            name="Marion County Day Reporting Center",
            category="probation-parole",
            region="Ocala / Marion County",
            description="The Marion County Day Reporting Center provides structured supervision, treatment, and employment programming for justice-involved adults in Marion County as an alternative to incarceration. Staff connect justice-involved adults from FDC custody and Marion County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Ocala / Marion County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="El Centro de Reporte Diurno del condado Marion ofrece supervisión estructurada, tratamiento y programación laboral para adultos con antecedentes penales como alternativa a la encarcelación. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Marion con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Ocala / Marion County.",
            address="692 NW 30th Avenue",
            city="Ocala",
            phone="352-369-7500",
            email="",
            website="https://www.fdc.myflorida.com",
            eligibility="Marion County court and FDC referrals to day reporting.",
            eligibility_es="Referencias judiciales y FDC al reporte diurno del condado Marion.",
            notes="Call 352-369-7500 for program info.",
            notes_es="Llame al 352-369-7500.",
            hours="Monday–Friday",
            tags="ocala|marion|probation-parole|day-reporting|reentry",
            services="Day reporting|Structured supervision|Treatment programming|Employment services|Case management",
            county="Marion",
            served_counties="Marion",
            coverage="single",
            _source="https://www.fdc.myflorida.com",
            _source_type="government",
            _confidence="high",
        )

    add(
            name="Heart of Florida United Way — 211",
            category="basic-needs",
            region="Orlando / Orange County",
            description="Heart of Florida United Way operates 211 and emergency assistance navigation for Orange, Osceola, Seminole, Lake, and Volusia counties connecting returning citizens to housing, food, and utility programs. Staff connect justice-involved adults from FDC custody and Orange County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Orlando / Orange County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Heart of Florida United Way opera 211 y navegación de asistencia de emergencia para los condados Orange, Osceola, Seminole, Lake y Volusia conectando a ciudadanos que regresan con programas de vivienda, alimentos y servicios públicos. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Orange con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Orlando / Orange County.",
            address="1940 Traylor Boulevard",
            city="Orlando",
            phone="407-429-2121",
            email="",
            website="https://www.hfuw.org",
            eligibility="Central Florida residents seeking resource navigation; 211 open to all.",
            eligibility_es="Residentes del centro de Florida que buscan navegación de recursos.",
            notes="Dial 211 or call 407-429-2121.",
            notes_es="Marque 211 o llame al 407-429-2121.",
            hours="211 hours vary",
            tags="orlando|orange|basic-needs|211|reentry",
            services="211 navigation|Emergency assistance|Utility help|Housing referrals|Benefits guidance",
            county="Orange",
            served_counties="Orange",
            coverage="single",
            _source="https://www.hfuw.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Legal Aid Society of the Orange County Bar",
            category="legal-aid",
            region="Orlando / Orange County",
            description="Legal Aid Society of the Orange County Bar provides pro bono civil legal help for low-income Orange County residents including returning citizens with eviction and record-sealing cases. Staff connect justice-involved adults from FDC custody and Orange County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Orlando / Orange County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Legal Aid Society of the Orange County Bar brinda ayuda legal civil pro bono para residentes de bajos ingresos del condado Orange incluidos ciudadanos que regresan con casos de desalojo y sellado de antecedentes. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Orange con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Orlando / Orange County.",
            address="100 E Robinson Street",
            city="Orlando",
            phone="407-841-8310",
            email="",
            website="https://www.legalaidocba.org",
            eligibility="Low-income Orange County residents with civil legal needs.",
            eligibility_es="Residentes de bajos ingresos del condado Orange con necesidades legales civiles.",
            notes="Call 407-841-8310 for intake.",
            notes_es="Llame al 407-841-8310.",
            hours="Monday–Friday",
            tags="orlando|orange|legal-aid|civil|reentry",
            services="Pro bono legal help|Eviction defense|Record sealing|Family law referrals|Clinic services",
            county="Orange",
            served_counties="Orange",
            coverage="single",
            _source="https://www.legalaidocba.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Gulf Coast Legal Services — Sarasota",
            category="legal-aid",
            region="Sarasota / Sarasota County",
            description="Gulf Coast Legal Services provides free civil legal aid in Sarasota and Manatee counties for low-income residents including returning citizens with housing and benefits appeals. Staff connect justice-involved adults from FDC custody and Sarasota County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Sarasota / Sarasota County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Gulf Coast Legal Services brinda ayuda legal civil gratuita en los condados Sarasota y Manatee para residentes de bajos ingresos incluidos ciudadanos que regresan. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Sarasota con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Sarasota / Sarasota County.",
            address="501 S Washington Boulevard",
            city="Sarasota",
            phone="941-957-2677",
            email="",
            website="https://www.gulfcoastlegal.org",
            eligibility="Low-income Sarasota and Manatee residents with civil legal needs.",
            eligibility_es="Residentes de bajos ingresos de Sarasota y Manatee.",
            notes="Call 941-957-2677 for intake.",
            notes_es="Llame al 941-957-2677.",
            hours="Monday–Friday",
            tags="sarasota|sarasota|legal-aid|civil|reentry",
            services="Housing legal aid|Benefits appeals|Consumer law|Family law|Expungement guidance",
            county="Sarasota",
            served_counties="Sarasota",
            coverage="single",
            _source="https://www.gulfcoastlegal.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="CareerSource Northeast Florida",
            category="employment",
            region="Jacksonville / Duval County",
            description="CareerSource Northeast Florida serves Duval, Clay, Nassau, Putnam, and St. Johns job seekers including justice-involved adults with WIOA training and fair-chance employer partnerships. Staff connect justice-involved adults from FDC custody and Duval County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Jacksonville / Duval County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="CareerSource Northeast Florida sirve a buscadores de empleo de Duval, Clay, Nassau, Putnam y St. Johns incluidos adultos con antecedentes penales con capacitación WIOA. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Duval con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Jacksonville / Duval County.",
            address="7740 Normandy Boulevard",
            city="Jacksonville",
            phone="904-356-5627",
            email="",
            website="https://www.careersourcenefl.com",
            eligibility="Open to Northeast Florida job seekers including justice-involved individuals.",
            eligibility_es="Abierto a buscadores de empleo del noreste de Florida.",
            notes="Register at careersourcenefl.com.",
            notes_es="Regístrese en careersourcenefl.com.",
            hours="Monday–Friday",
            tags="jacksonville|duval|employment|careersource|reentry",
            services="Job search|WIOA training|Career coaching|Fair-chance employers|Resume help",
            county="Duval",
            served_counties="Duval",
            coverage="single",
            _source="https://www.careersourcenefl.com",
            _source_type="government",
            _confidence="high",
        )

    add(
            name="CareerSource Capital Region",
            category="employment",
            region="Tallahassee / Leon County",
            description="CareerSource Capital Region connects Leon, Gadsden, Wakulla, and Franklin job seekers including justice-involved adults to WIOA training and state government employment pathways. Staff connect justice-involved adults from FDC custody and Leon County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Tallahassee / Leon County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="CareerSource Capital Region conecta buscadores de empleo de Leon, Gadsden, Wakulla y Franklin incluidos adultos con antecedentes penales a capacitación WIOA. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Leon con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Tallahassee / Leon County.",
            address="2607 Blair Stone Road",
            city="Tallahassee",
            phone="850-617-4570",
            email="",
            website="https://www.careersourcecapitalregion.com",
            eligibility="Open to Capital Region job seekers including justice-involved individuals.",
            eligibility_es="Abierto a buscadores de empleo de la región capital.",
            notes="Register at careersourcecapitalregion.com.",
            notes_es="Regístrese en careersourcecapitalregion.com.",
            hours="Monday–Friday",
            tags="tallahassee|leon|employment|careersource|reentry",
            services="Job search|WIOA training|State employer connections|Resume coaching|Career counseling",
            county="Leon",
            served_counties="Leon",
            coverage="single",
            _source="https://www.careersourcecapitalregion.com",
            _source_type="government",
            _confidence="high",
        )

    add(
            name="CareerSource Polk",
            category="employment",
            region="Lakeland / Polk County",
            description="CareerSource Polk serves Polk, Hardee, and Highlands job seekers including justice-involved adults with WIOA training, logistics and healthcare career pathways. Staff connect justice-involved adults from FDC custody and Polk County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Lakeland / Polk County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="CareerSource Polk sirve a buscadores de empleo de Polk, Hardee y Highlands incluidos adultos con antecedentes penales con capacitación WIOA. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Polk con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Lakeland / Polk County. Contact the program directly to confirm current hours, eligibility, and intake requirements before visiting in person.",
            address="2000 E Edgewood Drive",
            city="Lakeland",
            phone="863-508-1100",
            email="",
            website="https://www.careersourcepolk.com",
            eligibility="Open to Polk area job seekers including justice-involved individuals.",
            eligibility_es="Abierto a buscadores de empleo del área Polk.",
            notes="Register at careersourcepolk.com.",
            notes_es="Regístrese en careersourcepolk.com.",
            hours="Monday–Friday",
            tags="lakeland|polk|employment|careersource|reentry",
            services="Job search|WIOA training|Career pathways|Fair-chance employers|Resume coaching",
            county="Polk",
            served_counties="Polk",
            coverage="single",
            _source="https://www.careersourcepolk.com",
            _source_type="government",
            _confidence="high",
        )
