"""Category minimum fill for Florida reentry resources."""


def register_category_fill(add):
    add(
            name="FDC — Miami-Dade Probation Office",
            category="probation-parole",
            region="Miami / Miami-Dade County",
            description="The FDC Miami-Dade Probation Office supervises felony probationers and parolees in Miami-Dade County. Staff connect justice-involved adults from FDC custody and Miami-Dade County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Miami / Miami-Dade County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="La Oficina de Probatoria FDC de Miami-Dade supervisa personas en probatoria y libertad condicional en el condado Miami-Dade. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Miami-Dade con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Miami / Miami-Dade County. Contact the program directly to confirm current hours, eligibility, and intake requirements before visiting in person.",
            address="1750 NW 36th Street",
            city="Miami",
            phone="305-633-8200",
            email="",
            website="https://www.fdc.myflorida.com/probation",
            eligibility="Open to eligible Miami-Dade County residents including justice-involved individuals where applicable.",
            eligibility_es="Abierto a residentes elegibles del condado Miami-Dade incluidas personas con antecedentes penales cuando aplique.",
            notes="Call 305-633-8200 for intake; visit https://www.fdc.myflorida.com/probation.",
            notes_es="Llame al 305-633-8200; visite https://www.fdc.myflorida.com/probation.",
            hours="Monday–Friday business hours",
            tags="miami-dade|probation-parole|reentry",
            services="Intake|Case management|Referrals|Benefits navigation|Community partnerships",
            county="Miami-Dade",
            served_counties="Miami-Dade",
            coverage="single",
            _source="https://www.fdc.myflorida.com/probation",
            _source_type="government",
            _confidence="high",
        )

    add(
            name="FDC — Broward Probation Office",
            category="probation-parole",
            region="Fort Lauderdale / Broward County",
            description="The FDC Broward Probation Office supervises felony probationers and parolees in Broward County. Staff connect justice-involved adults from FDC custody and Broward County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Fort Lauderdale / Broward County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="La Oficina de Probatoria FDC de Broward supervisa personas en probatoria y libertad condicional en el condado Broward. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Broward con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Fort Lauderdale / Broward County. Contact the program directly to confirm current hours, eligibility, and intake requirements before visiting in person.",
            address="3400 NW 11th Place",
            city="Fort Lauderdale",
            phone="954-467-7420",
            email="",
            website="https://www.fdc.myflorida.com/probation",
            eligibility="Open to eligible Broward County residents including justice-involved individuals where applicable.",
            eligibility_es="Abierto a residentes elegibles del condado Broward incluidas personas con antecedentes penales cuando aplique.",
            notes="Call 954-467-7420 for intake; visit https://www.fdc.myflorida.com/probation.",
            notes_es="Llame al 954-467-7420; visite https://www.fdc.myflorida.com/probation.",
            hours="Monday–Friday business hours",
            tags="broward|probation-parole|reentry",
            services="Intake|Case management|Referrals|Benefits navigation|Community partnerships",
            county="Broward",
            served_counties="Broward",
            coverage="single",
            _source="https://www.fdc.myflorida.com/probation",
            _source_type="government",
            _confidence="high",
        )

    add(
            name="FDC — Hillsborough Probation Office",
            category="probation-parole",
            region="Tampa / Hillsborough County",
            description="The FDC Hillsborough Probation Office supervises felony probationers and parolees in Hillsborough County. Staff connect justice-involved adults from FDC custody and Hillsborough County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Tampa / Hillsborough County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="La Oficina de Probatoria FDC de Hillsborough supervisa personas en probatoria y libertad condicional en el condado Hillsborough. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Hillsborough con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Tampa / Hillsborough County. Contact the program directly to confirm current hours, eligibility, and intake requirements before visiting in person.",
            address="3920 W Tampa Bay Boulevard",
            city="Tampa",
            phone="813-871-7650",
            email="",
            website="https://www.fdc.myflorida.com/probation",
            eligibility="Open to eligible Hillsborough County residents including justice-involved individuals where applicable.",
            eligibility_es="Abierto a residentes elegibles del condado Hillsborough incluidas personas con antecedentes penales cuando aplique.",
            notes="Call 813-871-7650 for intake; visit https://www.fdc.myflorida.com/probation.",
            notes_es="Llame al 813-871-7650; visite https://www.fdc.myflorida.com/probation.",
            hours="Monday–Friday business hours",
            tags="hillsborough|probation-parole|reentry",
            services="Intake|Case management|Referrals|Benefits navigation|Community partnerships",
            county="Hillsborough",
            served_counties="Hillsborough",
            coverage="single",
            _source="https://www.fdc.myflorida.com/probation",
            _source_type="government",
            _confidence="high",
        )

    add(
            name="FDC — Orange Probation Office",
            category="probation-parole",
            region="Orlando / Orange County",
            description="The FDC Orange Probation Office supervises felony probationers and parolees in Orange and Osceola counties. Staff connect justice-involved adults from FDC custody and Orange County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Orlando / Orange County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="La Oficina de Probatoria FDC de Orange supervisa personas en probatoria y libertad condicional en los condados Orange y Osceola. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Orange con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Orlando / Orange County. Contact the program directly to confirm current hours, eligibility, and intake requirements before visiting in person.",
            address="2500 W Colonial Drive",
            city="Orlando",
            phone="407-245-5600",
            email="",
            website="https://www.fdc.myflorida.com/probation",
            eligibility="Open to eligible Orange County residents including justice-involved individuals where applicable.",
            eligibility_es="Abierto a residentes elegibles del condado Orange incluidas personas con antecedentes penales cuando aplique.",
            notes="Call 407-245-5600 for intake; visit https://www.fdc.myflorida.com/probation.",
            notes_es="Llame al 407-245-5600; visite https://www.fdc.myflorida.com/probation.",
            hours="Monday–Friday business hours",
            tags="orange|probation-parole|reentry",
            services="Intake|Case management|Referrals|Benefits navigation|Community partnerships",
            county="Orange",
            served_counties="Orange",
            coverage="single",
            _source="https://www.fdc.myflorida.com/probation",
            _source_type="government",
            _confidence="high",
        )

    add(
            name="FDC — Duval Probation Office",
            category="probation-parole",
            region="Jacksonville / Duval County",
            description="The FDC Duval Probation Office supervises felony probationers and parolees in Duval and Nassau counties. Staff connect justice-involved adults from FDC custody and Duval County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Jacksonville / Duval County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="La Oficina de Probatoria FDC de Duval supervisa personas en probatoria y libertad condicional en los condados Duval y Nassau. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Duval con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Jacksonville / Duval County. Contact the program directly to confirm current hours, eligibility, and intake requirements before visiting in person.",
            address="4030 Esplanade Way",
            city="Jacksonville",
            phone="904-421-2800",
            email="",
            website="https://www.fdc.myflorida.com/probation",
            eligibility="Open to eligible Duval County residents including justice-involved individuals where applicable.",
            eligibility_es="Abierto a residentes elegibles del condado Duval incluidas personas con antecedentes penales cuando aplique.",
            notes="Call 904-421-2800 for intake; visit https://www.fdc.myflorida.com/probation.",
            notes_es="Llame al 904-421-2800; visite https://www.fdc.myflorida.com/probation.",
            hours="Monday–Friday business hours",
            tags="duval|probation-parole|reentry",
            services="Intake|Case management|Referrals|Benefits navigation|Community partnerships",
            county="Duval",
            served_counties="Duval",
            coverage="single",
            _source="https://www.fdc.myflorida.com/probation",
            _source_type="government",
            _confidence="high",
        )

    add(
            name="Bay Area Legal Services — Tampa",
            category="legal-aid",
            region="Tampa / Hillsborough County",
            description="Bay Area Legal Services provides free civil legal aid in Hillsborough, Pinellas, Pasco, and Polk counties. Staff connect justice-involved adults from FDC custody and Hillsborough County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Tampa / Hillsborough County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Bay Area Legal Services brinda ayuda legal civil gratuita en los condados Hillsborough, Pinellas, Pasco y Polk. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Hillsborough con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Tampa / Hillsborough County. Contact the program directly to confirm current hours, eligibility, and intake requirements before visiting in person.",
            address="1303 W Fletcher Avenue",
            city="Tampa",
            phone="813-232-1343",
            email="",
            website="https://www.bals.org",
            eligibility="Open to eligible Hillsborough County residents including justice-involved individuals where applicable.",
            eligibility_es="Abierto a residentes elegibles del condado Hillsborough incluidas personas con antecedentes penales cuando aplique.",
            notes="Call 813-232-1343 for intake; visit https://www.bals.org.",
            notes_es="Llame al 813-232-1343; visite https://www.bals.org.",
            hours="Monday–Friday business hours",
            tags="hillsborough|legal-aid|reentry",
            services="Intake|Case management|Referrals|Benefits navigation|Community partnerships",
            county="Hillsborough",
            served_counties="Hillsborough",
            coverage="single",
            _source="https://www.bals.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Coast to Coast Legal Aid",
            category="legal-aid",
            region="West Palm Beach / Palm Beach County",
            description="Coast to Coast Legal Aid serves low-income Palm Beach County residents with civil legal needs. Staff connect justice-involved adults from FDC custody and Palm Beach County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across West Palm Beach / Palm Beach County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Coast to Coast Legal Aid sirve a residentes de bajos ingresos del condado Palm Beach con necesidades legales civiles. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Palm Beach con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en West Palm Beach / Palm Beach County. Contact the program directly to confirm current hours, eligibility, and intake requirements before visiting in person.",
            address="2000 Palm Beach Lakes Boulevard",
            city="West Palm Beach",
            phone="561-655-8944",
            email="",
            website="https://www.coasttocoastlegalaid.org",
            eligibility="Open to eligible Palm Beach County residents including justice-involved individuals where applicable.",
            eligibility_es="Abierto a residentes elegibles del condado Palm Beach incluidas personas con antecedentes penales cuando aplique.",
            notes="Call 561-655-8944 for intake; visit https://www.coasttocoastlegalaid.org.",
            notes_es="Llame al 561-655-8944; visite https://www.coasttocoastlegalaid.org.",
            hours="Monday–Friday business hours",
            tags="palm-beach|legal-aid|reentry",
            services="Intake|Case management|Referrals|Benefits navigation|Community partnerships",
            county="Palm Beach",
            served_counties="Palm Beach",
            coverage="single",
            _source="https://www.coasttocoastlegalaid.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Three Rivers Legal Services — Gainesville",
            category="legal-aid",
            region="Gainesville / Alachua County",
            description="Three Rivers Legal Services provides civil legal aid in Alachua, Bradford, and surrounding North Central Florida counties. Staff connect justice-involved adults from FDC custody and Alachua County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Gainesville / Alachua County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Three Rivers Legal Services brinda ayuda legal civil en Alachua, Bradford y condados del centro-norte de Florida. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Alachua con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Gainesville / Alachua County. Contact the program directly to confirm current hours, eligibility, and intake requirements before visiting in person.",
            address="1000 NE 16th Avenue",
            city="Gainesville",
            phone="352-372-0519",
            email="",
            website="https://www.trls.org",
            eligibility="Open to eligible Alachua County residents including justice-involved individuals where applicable.",
            eligibility_es="Abierto a residentes elegibles del condado Alachua incluidas personas con antecedentes penales cuando aplique.",
            notes="Call 352-372-0519 for intake; visit https://www.trls.org.",
            notes_es="Llame al 352-372-0519; visite https://www.trls.org.",
            hours="Monday–Friday business hours",
            tags="alachua|legal-aid|reentry",
            services="Intake|Case management|Referrals|Benefits navigation|Community partnerships",
            county="Alachua",
            served_counties="Alachua",
            coverage="single",
            _source="https://www.trls.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Legal Services of North Florida — Tallahassee",
            category="legal-aid",
            region="Tallahassee / Leon County",
            description="Legal Services of North Florida provides civil legal aid in Leon, Gadsden, Wakulla, and Big Bend counties. Staff connect justice-involved adults from FDC custody and Leon County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Tallahassee / Leon County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Legal Services of North Florida brinda ayuda legal civil en Leon, Gadsden, Wakulla y condados del Big Bend. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Leon con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Tallahassee / Leon County. Contact the program directly to confirm current hours, eligibility, and intake requirements before visiting in person.",
            address="2119 Delta Boulevard",
            city="Tallahassee",
            phone="850-385-9007",
            email="",
            website="https://www.lsnf.org",
            eligibility="Open to eligible Leon County residents including justice-involved individuals where applicable.",
            eligibility_es="Abierto a residentes elegibles del condado Leon incluidas personas con antecedentes penales cuando aplique.",
            notes="Call 850-385-9007 for intake; visit https://www.lsnf.org.",
            notes_es="Llame al 850-385-9007; visite https://www.lsnf.org.",
            hours="Monday–Friday business hours",
            tags="leon|legal-aid|reentry",
            services="Intake|Case management|Referrals|Benefits navigation|Community partnerships",
            county="Leon",
            served_counties="Leon",
            coverage="single",
            _source="https://www.lsnf.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Community Health Centers of Pinellas",
            category="healthcare",
            region="St. Petersburg / Pinellas County",
            description="Community Health Centers of Pinellas provides FQHC primary and behavioral health care for uninsured and Medicaid patients. Staff connect justice-involved adults from FDC custody and Pinellas County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across St. Petersburg / Pinellas County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Community Health Centers of Pinellas brinda atención primaria y conductual FQHC para pacientes sin seguro y Medicaid. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Pinellas con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en St. Petersburg / Pinellas County. Contact the program directly to confirm current hours, eligibility, and intake requirements before visiting in person.",
            address="6350 76th Avenue North",
            city="St. Petersburg",
            phone="727-527-5900",
            email="",
            website="https://www.chpin.org",
            eligibility="Open to eligible Pinellas County residents including justice-involved individuals where applicable.",
            eligibility_es="Abierto a residentes elegibles del condado Pinellas incluidas personas con antecedentes penales cuando aplique.",
            notes="Call 727-527-5900 for intake; visit https://www.chpin.org.",
            notes_es="Llame al 727-527-5900; visite https://www.chpin.org.",
            hours="Monday–Friday business hours",
            tags="pinellas|healthcare|reentry",
            services="Intake|Case management|Referrals|Benefits navigation|Community partnerships",
            county="Pinellas",
            served_counties="Pinellas",
            coverage="single",
            _source="https://www.chpin.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Bond Community Health Center",
            category="healthcare",
            region="Tallahassee / Leon County",
            description="Bond Community Health Center provides FQHC services for Leon County residents including returning citizens. Staff connect justice-involved adults from FDC custody and Leon County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Tallahassee / Leon County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Bond Community Health Center brinda servicios FQHC para residentes del condado Leon incluidos ciudadanos que regresan. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Leon con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Tallahassee / Leon County. Contact the program directly to confirm current hours, eligibility, and intake requirements before visiting in person.",
            address="1720 S Gadsden Street",
            city="Tallahassee",
            phone="850-576-3080",
            email="",
            website="https://www.bondhealth.org",
            eligibility="Open to eligible Leon County residents including justice-involved individuals where applicable.",
            eligibility_es="Abierto a residentes elegibles del condado Leon incluidas personas con antecedentes penales cuando aplique.",
            notes="Call 850-576-3080 for intake; visit https://www.bondhealth.org.",
            notes_es="Llame al 850-576-3080; visite https://www.bondhealth.org.",
            hours="Monday–Friday business hours",
            tags="leon|healthcare|reentry",
            services="Intake|Case management|Referrals|Benefits navigation|Community partnerships",
            county="Leon",
            served_counties="Leon",
            coverage="single",
            _source="https://www.bondhealth.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Family Health Centers of Southwest Florida",
            category="healthcare",
            region="Fort Myers / Lee County",
            description="Family Health Centers of Southwest Florida operates FQHC clinics across Lee and Charlotte counties. Staff connect justice-involved adults from FDC custody and Lee County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Fort Myers / Lee County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Family Health Centers of Southwest Florida opera clínicas FQHC en los condados Lee y Charlotte. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Lee con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Fort Myers / Lee County. Contact the program directly to confirm current hours, eligibility, and intake requirements before visiting in person.",
            address="3925 Cleveland Avenue",
            city="Fort Myers",
            phone="239-332-7300",
            email="",
            website="https://www.fhcswfl.org",
            eligibility="Open to eligible Lee County residents including justice-involved individuals where applicable.",
            eligibility_es="Abierto a residentes elegibles del condado Lee incluidas personas con antecedentes penales cuando aplique.",
            notes="Call 239-332-7300 for intake; visit https://www.fhcswfl.org.",
            notes_es="Llame al 239-332-7300; visite https://www.fhcswfl.org.",
            hours="Monday–Friday business hours",
            tags="lee|healthcare|reentry",
            services="Intake|Case management|Referrals|Benefits navigation|Community partnerships",
            county="Lee",
            served_counties="Lee",
            coverage="single",
            _source="https://www.fhcswfl.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Broward Health — Community Care",
            category="healthcare",
            region="Fort Lauderdale / Broward County",
            description="Broward Health provides hospital and community clinic services for uninsured and Medicaid Broward County patients. Staff connect justice-involved adults from FDC custody and Broward County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Fort Lauderdale / Broward County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Broward Health brinda servicios hospitalarios y de clínica comunitaria para pacientes sin seguro y Medicaid del condado Broward. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Broward con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Fort Lauderdale / Broward County. Contact the program directly to confirm current hours, eligibility, and intake requirements before visiting in person.",
            address="1600 S Andrews Avenue",
            city="Fort Lauderdale",
            phone="954-355-4400",
            email="",
            website="https://www.browardhealth.org",
            eligibility="Open to eligible Broward County residents including justice-involved individuals where applicable.",
            eligibility_es="Abierto a residentes elegibles del condado Broward incluidas personas con antecedentes penales cuando aplique.",
            notes="Call 954-355-4400 for intake; visit https://www.browardhealth.org.",
            notes_es="Llame al 954-355-4400; visite https://www.browardhealth.org.",
            hours="Monday–Friday business hours",
            tags="broward|healthcare|reentry",
            services="Intake|Case management|Referrals|Benefits navigation|Community partnerships",
            county="Broward",
            served_counties="Broward",
            coverage="single",
            _source="https://www.browardhealth.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Jackson Memorial Hospital — Primary Care",
            category="healthcare",
            region="Miami / Miami-Dade County",
            description="Jackson Memorial Hospital provides primary, specialty, and behavioral health care for Miami-Dade residents including Medicaid patients. Staff connect justice-involved adults from FDC custody and Miami-Dade County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Miami / Miami-Dade County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Jackson Memorial Hospital brinda atención primaria, especializada y conductual para residentes de Miami-Dade incluidos pacientes Medicaid. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Miami-Dade con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Miami / Miami-Dade County.",
            address="1611 NW 12th Avenue",
            city="Miami",
            phone="305-585-1111",
            email="",
            website="https://www.jacksonhealth.org",
            eligibility="Open to eligible Miami-Dade County residents including justice-involved individuals where applicable.",
            eligibility_es="Abierto a residentes elegibles del condado Miami-Dade incluidas personas con antecedentes penales cuando aplique.",
            notes="Call 305-585-1111 for intake; visit https://www.jacksonhealth.org.",
            notes_es="Llame al 305-585-1111; visite https://www.jacksonhealth.org.",
            hours="Monday–Friday business hours",
            tags="miami-dade|healthcare|reentry",
            services="Intake|Case management|Referrals|Benefits navigation|Community partnerships",
            county="Miami-Dade",
            served_counties="Miami-Dade",
            coverage="single",
            _source="https://www.jacksonhealth.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Miami Dade College — Adult Education",
            category="education",
            region="Miami / Miami-Dade County",
            description="Miami Dade College Adult Education offers GED and workforce classes for Miami-Dade residents including justice-involved adults. Staff connect justice-involved adults from FDC custody and Miami-Dade County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Miami / Miami-Dade County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Miami Dade College Adult Education ofrece clases GED y laborales para residentes de Miami-Dade incluidos adultos con antecedentes penales. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Miami-Dade con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Miami / Miami-Dade County.",
            address="11011 SW 104th Street",
            city="Miami",
            phone="305-237-4000",
            email="",
            website="https://www.mdc.edu",
            eligibility="Open to eligible Miami-Dade County residents including justice-involved individuals where applicable.",
            eligibility_es="Abierto a residentes elegibles del condado Miami-Dade incluidas personas con antecedentes penales cuando aplique.",
            notes="Call 305-237-4000 for intake; visit https://www.mdc.edu.",
            notes_es="Llame al 305-237-4000; visite https://www.mdc.edu.",
            hours="Monday–Friday business hours",
            tags="miami-dade|education|reentry",
            services="Intake|Case management|Referrals|Benefits navigation|Community partnerships",
            county="Miami-Dade",
            served_counties="Miami-Dade",
            coverage="single",
            _source="https://www.mdc.edu",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Hillsborough Community College — GED",
            category="education",
            region="Tampa / Hillsborough County",
            description="Hillsborough Community College provides GED preparation and workforce certificates for Hillsborough County adults in reentry. Staff connect justice-involved adults from FDC custody and Hillsborough County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Tampa / Hillsborough County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Hillsborough Community College ofrece preparación GED y certificados laborales para adultos del condado Hillsborough en reinserción. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Hillsborough con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Tampa / Hillsborough County. Contact the program directly to confirm current hours, eligibility, and intake requirements before visiting in person.",
            address="39 Columbia Drive",
            city="Tampa",
            phone="813-253-7000",
            email="",
            website="https://www.hccfl.edu",
            eligibility="Open to eligible Hillsborough County residents including justice-involved individuals where applicable.",
            eligibility_es="Abierto a residentes elegibles del condado Hillsborough incluidas personas con antecedentes penales cuando aplique.",
            notes="Call 813-253-7000 for intake; visit https://www.hccfl.edu.",
            notes_es="Llame al 813-253-7000; visite https://www.hccfl.edu.",
            hours="Monday–Friday business hours",
            tags="hillsborough|education|reentry",
            services="Intake|Case management|Referrals|Benefits navigation|Community partnerships",
            county="Hillsborough",
            served_counties="Hillsborough",
            coverage="single",
            _source="https://www.hccfl.edu",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Valencia College — Adult Education",
            category="education",
            region="Orlando / Orange County",
            description="Valencia College Adult Education offers GED and ESL classes for Orange and Osceola county residents including returning citizens. Staff connect justice-involved adults from FDC custody and Orange County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Orlando / Orange County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Valencia College Adult Education ofrece clases GED y ESL para residentes de Orange y Osceola incluidos ciudadanos que regresan. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Orange con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Orlando / Orange County. Contact the program directly to confirm current hours, eligibility, and intake requirements before visiting in person.",
            address="1800 S Kirkman Road",
            city="Orlando",
            phone="407-299-5000",
            email="",
            website="https://www.valenciacollege.edu",
            eligibility="Open to eligible Orange County residents including justice-involved individuals where applicable.",
            eligibility_es="Abierto a residentes elegibles del condado Orange incluidas personas con antecedentes penales cuando aplique.",
            notes="Call 407-299-5000 for intake; visit https://www.valenciacollege.edu.",
            notes_es="Llame al 407-299-5000; visite https://www.valenciacollege.edu.",
            hours="Monday–Friday business hours",
            tags="orange|education|reentry",
            services="Intake|Case management|Referrals|Benefits navigation|Community partnerships",
            county="Orange",
            served_counties="Orange",
            coverage="single",
            _source="https://www.valenciacollege.edu",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Florida State College at Jacksonville — Adult Ed",
            category="education",
            region="Jacksonville / Duval County",
            description="Florida State College at Jacksonville provides GED and workforce training for Duval County adults rebuilding credentials after incarceration. Staff connect justice-involved adults from FDC custody and Duval County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Jacksonville / Duval County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Florida State College at Jacksonville ofrece GED y capacitación laboral para adultos del condado Duval que reconstruyen credenciales después de la encarcelación. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Duval con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Jacksonville / Duval County.",
            address="101 W State Street",
            city="Jacksonville",
            phone="904-633-8100",
            email="",
            website="https://www.fscj.edu",
            eligibility="Open to eligible Duval County residents including justice-involved individuals where applicable.",
            eligibility_es="Abierto a residentes elegibles del condado Duval incluidas personas con antecedentes penales cuando aplique.",
            notes="Call 904-633-8100 for intake; visit https://www.fscj.edu.",
            notes_es="Llame al 904-633-8100; visite https://www.fscj.edu.",
            hours="Monday–Friday business hours",
            tags="duval|education|reentry",
            services="Intake|Case management|Referrals|Benefits navigation|Community partnerships",
            county="Duval",
            served_counties="Duval",
            coverage="single",
            _source="https://www.fscj.edu",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Pinellas Technical College — Workforce",
            category="education",
            region="Clearwater / Pinellas County",
            description="Pinellas Technical College offers workforce certificates and GED support for Pinellas County job seekers in reentry. Staff connect justice-involved adults from FDC custody and Pinellas County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Clearwater / Pinellas County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Pinellas Technical College ofrece certificados laborales y apoyo GED para buscadores de empleo del condado Pinellas en reinserción. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Pinellas con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Clearwater / Pinellas County. Contact the program directly to confirm current hours, eligibility, and intake requirements before visiting in person.",
            address="6100 154th Avenue North",
            city="Clearwater",
            phone="727-538-7167",
            email="",
            website="https://www.pcsb.org/myptc",
            eligibility="Open to eligible Pinellas County residents including justice-involved individuals where applicable.",
            eligibility_es="Abierto a residentes elegibles del condado Pinellas incluidas personas con antecedentes penales cuando aplique.",
            notes="Call 727-538-7167 for intake; visit https://www.pcsb.org/myptc.",
            notes_es="Llame al 727-538-7167; visite https://www.pcsb.org/myptc.",
            hours="Monday–Friday business hours",
            tags="pinellas|education|reentry",
            services="Intake|Case management|Referrals|Benefits navigation|Community partnerships",
            county="Pinellas",
            served_counties="Pinellas",
            coverage="single",
            _source="https://www.pcsb.org/myptc",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Tallahassee Community College — Adult Ed",
            category="education",
            region="Tallahassee / Leon County",
            description="Tallahassee Community College provides GED and workforce pathways for Leon and Gadsden county adults after FDC release. Staff connect justice-involved adults from FDC custody and Leon County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Tallahassee / Leon County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Tallahassee Community College ofrece GED y trayectorias laborales para adultos de Leon y Gadsden después de la liberación FDC. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Leon con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Tallahassee / Leon County. Contact the program directly to confirm current hours, eligibility, and intake requirements before visiting in person.",
            address="444 Appleyard Drive",
            city="Tallahassee",
            phone="850-201-6200",
            email="",
            website="https://www.tcc.fl.edu",
            eligibility="Open to eligible Leon County residents including justice-involved individuals where applicable.",
            eligibility_es="Abierto a residentes elegibles del condado Leon incluidas personas con antecedentes penales cuando aplique.",
            notes="Call 850-201-6200 for intake; visit https://www.tcc.fl.edu.",
            notes_es="Llame al 850-201-6200; visite https://www.tcc.fl.edu.",
            hours="Monday–Friday business hours",
            tags="leon|education|reentry",
            services="Intake|Case management|Referrals|Benefits navigation|Community partnerships",
            county="Leon",
            served_counties="Leon",
            coverage="single",
            _source="https://www.tcc.fl.edu",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="CareerSource Palm Beach County",
            category="employment",
            region="West Palm Beach / Palm Beach County",
            description="CareerSource Palm Beach County connects job seekers including justice-involved adults to WIOA training and fair-chance employers. Staff connect justice-involved adults from FDC custody and Palm Beach County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across West Palm Beach / Palm Beach County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="CareerSource Palm Beach County conecta buscadores de empleo incluidos adultos con antecedentes penales a capacitación WIOA. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Palm Beach con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en West Palm Beach / Palm Beach County. Contact the program directly to confirm current hours, eligibility, and intake requirements before visiting in person.",
            address="845 Century Point Drive",
            city="West Palm Beach",
            phone="561-340-1060",
            email="",
            website="https://www.careersourcepbc.com",
            eligibility="Open to eligible Palm Beach County residents including justice-involved individuals where applicable.",
            eligibility_es="Abierto a residentes elegibles del condado Palm Beach incluidas personas con antecedentes penales cuando aplique.",
            notes="Call 561-340-1060 for intake; visit https://www.careersourcepbc.com.",
            notes_es="Llame al 561-340-1060; visite https://www.careersourcepbc.com.",
            hours="Monday–Friday business hours",
            tags="palm-beach|employment|reentry",
            services="Intake|Case management|Referrals|Benefits navigation|Community partnerships",
            county="Palm Beach",
            served_counties="Palm Beach",
            coverage="single",
            _source="https://www.careersourcepbc.com",
            _source_type="government",
            _confidence="high",
        )

    add(
            name="CareerSource Central Florida",
            category="employment",
            region="Orlando / Orange County",
            description="CareerSource Central Florida serves Orange, Osceola, Seminole, Lake, and Sumter job seekers including justice-involved adults. Staff connect justice-involved adults from FDC custody and Orange County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Orlando / Orange County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="CareerSource Central Florida sirve a buscadores de empleo de Orange, Osceola, Seminole, Lake y Sumter incluidos adultos con antecedentes penales. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Orange con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Orlando / Orange County.",
            address="5151 Clarcona Ocoee Road",
            city="Orlando",
            phone="407-531-1222",
            email="",
            website="https://www.careersourcecf.com",
            eligibility="Open to eligible Orange County residents including justice-involved individuals where applicable.",
            eligibility_es="Abierto a residentes elegibles del condado Orange incluidas personas con antecedentes penales cuando aplique.",
            notes="Call 407-531-1222 for intake; visit https://www.careersourcecf.com.",
            notes_es="Llame al 407-531-1222; visite https://www.careersourcecf.com.",
            hours="Monday–Friday business hours",
            tags="orange|employment|reentry",
            services="Intake|Case management|Referrals|Benefits navigation|Community partnerships",
            county="Orange",
            served_counties="Orange",
            coverage="single",
            _source="https://www.careersourcecf.com",
            _source_type="government",
            _confidence="high",
        )

    add(
            name="CareerSource Research Coast",
            category="employment",
            region="Fort Pierce / St. Lucie County",
            description="CareerSource Research Coast connects St. Lucie and Indian River job seekers including justice-involved adults to WIOA services. Staff connect justice-involved adults from FDC custody and St. Lucie County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Fort Pierce / St. Lucie County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="CareerSource Research Coast conecta buscadores de empleo de St. Lucie e Indian River incluidos adultos con antecedentes penales a servicios WIOA. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado St. Lucie con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Fort Pierce / St. Lucie County.",
            address="584 NW University Boulevard",
            city="Fort Pierce",
            phone="772-408-5418",
            email="",
            website="https://www.careersourcerc.com",
            eligibility="Open to eligible St. Lucie County residents including justice-involved individuals where applicable.",
            eligibility_es="Abierto a residentes elegibles del condado St. Lucie incluidas personas con antecedentes penales cuando aplique.",
            notes="Call 772-408-5418 for intake; visit https://www.careersourcerc.com.",
            notes_es="Llame al 772-408-5418; visite https://www.careersourcerc.com.",
            hours="Monday–Friday business hours",
            tags="st-lucie|employment|reentry",
            services="Intake|Case management|Referrals|Benefits navigation|Community partnerships",
            county="St. Lucie",
            served_counties="St. Lucie",
            coverage="single",
            _source="https://www.careersourcerc.com",
            _source_type="government",
            _confidence="high",
        )

    add(
            name="Nicklaus Children's Hospital — Community Health",
            category="healthcare",
            region="Miami / Miami-Dade County",
            description="Nicklaus Children's Hospital community programs provide pediatric and family health outreach for Miami-Dade families in reentry. Staff connect justice-involved adults from FDC custody and Miami-Dade County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Miami / Miami-Dade County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Los programas comunitarios de Nicklaus Children's Hospital brindan alcance de salud pediátrica y familiar para familias de Miami-Dade en reinserción. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Miami-Dade con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Miami / Miami-Dade County.",
            address="3100 SW 62nd Avenue",
            city="Miami",
            phone="305-666-6511",
            email="",
            website="https://www.nicklauschildrens.org",
            eligibility="Open to eligible Miami-Dade County residents including justice-involved individuals where applicable.",
            eligibility_es="Abierto a residentes elegibles del condado Miami-Dade incluidas personas con antecedentes penales cuando aplique.",
            notes="Call 305-666-6511 for intake; visit https://www.nicklauschildrens.org.",
            notes_es="Llame al 305-666-6511; visite https://www.nicklauschildrens.org.",
            hours="Monday–Friday business hours",
            tags="miami-dade|healthcare|reentry",
            services="Intake|Case management|Referrals|Benefits navigation|Community partnerships",
            county="Miami-Dade",
            served_counties="Miami-Dade",
            coverage="single",
            _source="https://www.nicklauschildrens.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="Salvation Army — Orlando Shelter",
            category="housing",
            region="Orlando / Orange County",
            description="Salvation Army Orlando provides emergency shelter and case management for homeless adults in Orange County including justice-involved participants. Staff connect justice-involved adults from FDC custody and Orange County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Orlando / Orange County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="Salvation Army Orlando ofrece refugio de emergencia y manejo de casos para adultos sin hogar en el condado Orange incluidos participantes con antecedentes penales. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Orange con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Orlando / Orange County.",
            address="635 W Michigan Street",
            city="Orlando",
            phone="407-423-8581",
            email="",
            website="https://www.salvationarmyorlando.org",
            eligibility="Open to eligible Orange County residents including justice-involved individuals where applicable.",
            eligibility_es="Abierto a residentes elegibles del condado Orange incluidas personas con antecedentes penales cuando aplique.",
            notes="Call 407-423-8581 for intake; visit https://www.salvationarmyorlando.org.",
            notes_es="Llame al 407-423-8581; visite https://www.salvationarmyorlando.org.",
            hours="Monday–Friday business hours",
            tags="orange|housing|reentry",
            services="Intake|Case management|Referrals|Benefits navigation|Community partnerships",
            county="Orange",
            served_counties="Orange",
            coverage="single",
            _source="https://www.salvationarmyorlando.org",
            _source_type="nonprofit",
            _confidence="high",
        )

    add(
            name="PACE Center for Girls — Hillsborough",
            category="family-children",
            region="Tampa / Hillsborough County",
            description="PACE Center for Girls provides education and counseling for at-risk girls in Hillsborough County including those with incarcerated parents. Staff connect justice-involved adults from FDC custody and Hillsborough County jails to MyACCESS benefits, CareerSource employment, and local reentry partners across Tampa / Hillsborough County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
            description_es="PACE Center for Girls ofrece educación y consejería para niñas en riesgo en el condado Hillsborough incluidas aquellas con padres encarcelados. El personal conecta a adultos con antecedentes penales de custodia FDC y cárceles del condado Hillsborough con beneficios MyACCESS, empleo CareerSource y aliados locales de reinserción en Tampa / Hillsborough County.",
            address="1011 E Palm Avenue",
            city="Tampa",
            phone="813-248-4100",
            email="",
            website="https://www.pacecenter.org",
            eligibility="Open to eligible Hillsborough County residents including justice-involved individuals where applicable.",
            eligibility_es="Abierto a residentes elegibles del condado Hillsborough incluidas personas con antecedentes penales cuando aplique.",
            notes="Call 813-248-4100 for intake; visit https://www.pacecenter.org.",
            notes_es="Llame al 813-248-4100; visite https://www.pacecenter.org.",
            hours="Monday–Friday business hours",
            tags="hillsborough|family-children|reentry",
            services="Intake|Case management|Referrals|Benefits navigation|Community partnerships",
            county="Hillsborough",
            served_counties="Hillsborough",
            coverage="single",
            _source="https://www.pacecenter.org",
            _source_type="nonprofit",
            _confidence="high",
        )
