#!/usr/bin/env python3
"""Generate US state SVG paths and county centroids for the coverage map."""

from __future__ import annotations

import json
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "src" / "lib" / "us-map"
COUNTY_CACHE = ROOT / "scripts" / "data" / "county-centroids.json"

import sys

sys.path.insert(0, str(ROOT / "scripts"))

from lib.us_state_fips import load_deployed_state_fips

W, H = 960, 600
LON_MIN, LON_MAX = -125.0, -66.5
LAT_MIN, LAT_MAX = 24.0, 49.5


def project(lon: float, lat: float) -> tuple[float, float]:
    x = (lon - LON_MIN) / (LON_MAX - LON_MIN) * W
    y = (LAT_MAX - lat) / (LAT_MAX - LAT_MIN) * H
    return round(x, 2), round(y, 2)


def ring_to_path(ring: list[list[float]]) -> str:
    parts: list[str] = []
    for index, (lon, lat) in enumerate(ring):
        x, y = project(lon, lat)
        parts.append(f"{'M' if index == 0 else 'L'}{x},{y}")
    parts.append("Z")
    return " ".join(parts)


def geom_to_path(geom: dict) -> str:
    if geom["type"] == "Polygon":
        return ring_to_path(geom["coordinates"][0])
    if geom["type"] == "MultiPolygon":
        return " ".join(ring_to_path(poly[0]) for poly in geom["coordinates"])
    return ""


def ring_centroid(ring: list[list[float]]) -> tuple[float, float]:
    xs = [point[0] for point in ring]
    ys = [point[1] for point in ring]
    return sum(xs) / len(xs), sum(ys) / len(ys)


def fetch_json(url: str) -> dict | list:
    with urllib.request.urlopen(url, timeout=30) as response:
        return json.load(response)


def generate_county_centroids(state_fips: dict[str, str]) -> list[dict]:
    geo = fetch_json(
        "https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json"
    )
    counties: list[dict] = []
    for feature in geo["features"]:
        fips = feature["id"]
        state_code = fips[:2]
        if state_code not in state_fips:
            continue
        name = feature["properties"]["NAME"]
        geometry = feature["geometry"]
        if geometry["type"] == "Polygon":
            ring = geometry["coordinates"][0]
        elif geometry["type"] == "MultiPolygon":
            ring = max(geometry["coordinates"], key=lambda polygon: len(polygon[0]))[0]
        else:
            continue
        lon, lat = ring_centroid(ring)
        counties.append(
            {
                "state": state_fips[state_code],
                "county": name,
                "lon": round(lon, 5),
                "lat": round(lat, 5),
            }
        )
    COUNTY_CACHE.parent.mkdir(parents=True, exist_ok=True)
    COUNTY_CACHE.write_text(json.dumps(counties, indent=2), encoding="utf-8")
    return counties


def generate_state_paths() -> list[dict]:
    geo = fetch_json(
        "https://raw.githubusercontent.com/PublicaMundi/MappingAPI/master/data/geojson/us-states.json"
    )
    states: list[dict] = []
    for feature in geo["features"]:
        name = feature["properties"]["name"]
        path = geom_to_path(feature["geometry"])
        if not path:
            continue
        geometry = feature["geometry"]
        coords: list[list[float]] = []
        if geometry["type"] == "Polygon":
            coords = geometry["coordinates"][0]
        else:
            for polygon in geometry["coordinates"]:
                coords.extend(polygon[0])
        lon = sum(point[0] for point in coords) / len(coords)
        lat = sum(point[1] for point in coords) / len(coords)
        x, y = project(lon, lat)
        states.append({"name": name, "path": path, "x": x, "y": y})
    return sorted(states, key=lambda item: item["name"])


def write_ts(path: Path, header: str, export_name: str, payload: list[dict], type_block: str) -> None:
    path.write_text(
        f"// Generated by scripts/generate-us-map-data.py — do not edit by hand.\n\n"
        f"{type_block}\n\n"
        f"export const {export_name} = {json.dumps(payload, indent=2)} as const;\n",
        encoding="utf-8",
    )


def main() -> None:
    state_fips = load_deployed_state_fips(ROOT)
    deployed = ", ".join(sorted(state_fips.values()))
    print(f"Generating map data for deployed states: {deployed}")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    counties = generate_county_centroids(state_fips)
    states = generate_state_paths()

    write_ts(
        OUT_DIR / "county-centroids.generated.ts",
        "",
        "COUNTY_CENTROIDS",
        counties,
        "export interface CountyCentroid {\n"
        "  state: string;\n"
        "  county: string;\n"
        "  lon: number;\n"
        "  lat: number;\n"
        "}",
    )

    state_file = OUT_DIR / "state-paths.generated.ts"
    state_file.write_text(
        "// Generated by scripts/generate-us-map-data.py — do not edit by hand.\n\n"
        "export interface UsStateMapPath {\n"
        "  name: string;\n"
        "  path: string;\n"
        "  x: number;\n"
        "  y: number;\n"
        "}\n\n"
        f"export const US_STATE_MAP_PATHS: UsStateMapPath[] = {json.dumps(states, indent=2)} as const;\n\n"
        f"export const US_MAP_VIEWBOX = {{ width: {W}, height: {H} }} as const;\n",
        encoding="utf-8",
    )

    print(f"Wrote {len(states)} states and {len(counties)} county centroids")


if __name__ == "__main__":
    main()
