#!/usr/bin/env python3
"""Generate service_aliases.json from classification rules + CSV strings."""
from __future__ import annotations

import csv
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from lib.service_types import (  # noqa: E402
    CANONICAL_SERVICES,
    EXACT_OVERRIDES,
    alias_key,
    classify_with_fallback,
    consolidate_canonical,
)

DATA_DIR = ROOT / "data"
RAW_STRINGS_PATH = DATA_DIR / "service-strings-raw.json"
CSV_PATHS = [
    DATA_DIR / "kentucky-resources.csv",
    DATA_DIR / "ohio-resources.csv",
    DATA_DIR / "indiana-resources.csv",
    DATA_DIR / "tennessee-resources.csv",
]
OUT_JSON = ROOT / "scripts" / "lib" / "service_aliases.json"
OUT_TS = ROOT / "src" / "lib" / "service-aliases.generated.ts"


def collect_services() -> set[str]:
    services: set[str] = set()
    if RAW_STRINGS_PATH.exists():
        raw_data = json.loads(RAW_STRINGS_PATH.read_text(encoding="utf-8"))
        if isinstance(raw_data, dict):
            services.update(raw_data.keys())
        elif isinstance(raw_data, list):
            services.update(str(item) for item in raw_data)
    for path in CSV_PATHS:
        if not path.exists():
            continue
        with path.open(newline="", encoding="utf-8") as handle:
            for row in csv.DictReader(handle):
                for part in (row.get("services") or "").split("|"):
                    value = part.strip()
                    if value:
                        services.add(value)
    return services


def build_aliases(services: set[str]) -> dict[str, str]:
    aliases: dict[str, str] = {}
    unmapped: list[str] = []

    for raw in sorted(services):
        key = alias_key(raw)
        if key in aliases:
            continue
        if key in EXACT_OVERRIDES:
            canonical = consolidate_canonical(EXACT_OVERRIDES[key])
        elif raw in CANONICAL_SERVICES:
            canonical = raw
        else:
            classified = classify_with_fallback(raw)
            if not classified:
                unmapped.append(raw)
                continue
            canonical = classified
        if not canonical:
            unmapped.append(raw)
            continue
        aliases[key] = canonical

    if unmapped:
        print(f"UNMAPPED ({len(unmapped)}):", file=sys.stderr)
        for item in unmapped:
            print(f"  {item}", file=sys.stderr)
        sys.exit(1)

    return aliases


def write_ts(aliases: dict[str, str]) -> None:
    lines = [
        "// Generated by scripts/generate-service-aliases.py — do not edit.",
        "export const SERVICE_ALIASES: Readonly<Record<string, string>> = {",
    ]
    for key, value in sorted(aliases.items()):
        esc_key = key.replace("\\", "\\\\").replace('"', '\\"')
        esc_val = value.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'  "{esc_key}": "{esc_val}",')
    lines.append("} as const;")
    lines.append("")
    OUT_TS.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    services = collect_services()
    aliases = build_aliases(services)
    OUT_JSON.write_text(json.dumps(aliases, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    write_ts(aliases)
    canonical_used = sorted(set(aliases.values()))
    print(f"Services in CSVs: {len(services)}")
    print(f"Alias entries: {len(aliases)}")
    print(f"Canonical types used: {len(canonical_used)}")
    print(f"Wrote {OUT_JSON}")
    print(f"Wrote {OUT_TS}")


if __name__ == "__main__":
    main()
