"""Category minimum fill for Georgia reentry resources."""


def register_category_fill(add):
    """Add verified rows to meet category minimums not met by phase4/rural depth."""

    add(
        name="Georgia Department of Education — Adult Education & GED",
        category="education", region="Statewide",
        description="The Georgia Department of Education Adult Education Program connects adults including returning citizens to GED and HiSET preparation, adult diploma programs, and English literacy classes at local adult education sites in every region of Georgia. Justice-involved Georgians can rebuild credentials for employment and training programs through free or low-cost instruction at technical colleges and community partners. A statewide navigation resource—not a walk-in classroom at the state office.",
        description_es="El Programa de Educación para Adultos del Departamento de Educación de Georgia conecta a adultos, incluidos ciudadanos que regresan, con preparación GED y HiSET, programas de diploma de adultos y clases de alfabetización en sitios locales en cada región. Los georgianos con antecedentes penales pueden reconstruir credenciales para empleo y capacitación mediante instrucción gratuita o de bajo costo en colegios técnicos y aliados comunitarios.",
        address="205 Jesse Hill Jr. Drive SE", city="Atlanta", phone="404-463-1155", email="",
        website="https://www.gadoe.org/Pages/Adult-Education.aspx",
        eligibility="Georgia adults age 16+ not enrolled in high school seeking GED, HiSET, or adult diploma; criminal record not a barrier.",
        eligibility_es="Adultos de Georgia de 16 años o más no inscritos en secundaria que buscan GED, HiSET o diploma de adultos; los antecedentes penales no son barrera.",
        notes="Find local adult education centers at gadoe.org; contact regional adult education director for nearest HiSET/GED site.",
        notes_es="Encuentre centros locales en gadoe.org; contacte al director regional de educación para adultos para el sitio HiSET/GED más cercano.",
        hours="Local sites vary; state office Monday–Friday business hours",
        tags="statewide|education|GED|HiSET|adult-education|reentry",
        services="GED preparation|HiSET testing referrals|Adult diploma programs|English literacy|Local site locator",
        county="Fulton", served_counties="", coverage="statewide",
        _source="https://www.gadoe.org/Pages/Adult-Education.aspx", _source_type="government", _confidence="high",
    )
    add(
        name="Technical College System of Georgia — Adult Education",
        category="education", region="Statewide",
        description="The Technical College System of Georgia operates adult education and GED programs at 22 technical colleges statewide helping justice-involved Georgians earn high school equivalency credentials and transition to workforce training. Instructors at campuses in every region provide free GED preparation and connect graduates to TCSG certificate and diploma programs. Contact your nearest technical college adult education office—not emergency services.",
        description_es="El Sistema de Colegios Técnicos de Georgia opera programas de educación para adultos y GED en 22 colegios técnicos en todo el estado ayudando a georgianos con antecedentes penales a obtener credenciales de equivalencia de secundaria y transición a capacitación laboral. Instructores en campus de cada región ofrecen preparación GED gratuita y conectan graduados a programas de certificado TCSG.",
        address="1800 Century Boulevard NE", city="Atlanta", phone="404-679-1600", email="",
        website="https://www.tcsg.edu/adult-education/",
        eligibility="Georgia residents age 16+ seeking GED or adult education; open to justice-involved adults at local technical college sites.",
        eligibility_es="Residentes de Georgia de 16 años o más que buscan GED o educación para adultos; abierto a adultos con antecedentes penales en sitios locales.",
        notes="Visit tcsg.edu/adult-education for campus locator; GED testing and preparation available at affiliated technical colleges.",
        notes_es="Visite tcsg.edu/adult-education para localizador de campus; pruebas y preparación GED disponibles en colegios técnicos afiliados.",
        hours="Campus hours vary",
        tags="statewide|education|GED|TCSG|technical-college|reentry",
        services="GED preparation|HiSET preparation|Workforce training pathways|Technical college referrals|Credential attainment",
        county="Fulton", served_counties="", coverage="statewide",
        _source="https://www.tcsg.edu/adult-education/", _source_type="government", _confidence="high",
    )
    add(
        name="Literacy Action — Atlanta Adult Education",
        category="education", region="Atlanta / Fulton County",
        description="Literacy Action is Georgia's oldest and largest adult literacy nonprofit providing GED preparation, digital literacy, and workforce readiness classes for low-income adults in metro Atlanta including returning citizens rebuilding education credentials after incarceration. Small-group instruction and tutoring at Atlanta campuses help participants pass GED exams and connect to employment programs. Direct classroom services—not a statewide hotline.",
        description_es="Literacy Action es la organización sin fines de lucro de alfabetización para adultos más antigua y grande de Georgia que ofrece preparación GED, alfabetización digital y clases de preparación laboral para adultos de bajos ingresos en el metro de Atlanta, incluidos ciudadanos que regresan que reconstruyen credenciales educativas. Instrucción en grupos pequeños en campus de Atlanta ayuda a aprobar exámenes GED.",
        address="100 Edgewood Avenue NE", city="Atlanta", phone="404-818-7323", email="",
        website="https://literacyaction.org",
        eligibility="Low-income metro Atlanta adults age 18+ seeking GED or literacy services; justice-involved adults welcome.",
        eligibility_es="Adultos de bajos ingresos del metro de Atlanta de 18 años o más que buscan GED o servicios de alfabetización; adultos con antecedentes penales bienvenidos.",
        notes="Call 404-818-7323 or visit literacyaction.org for enrollment; multiple Atlanta class locations.",
        notes_es="Llame al 404-818-7323 o visite literacyaction.org para inscripción; múltiples ubicaciones de clases en Atlanta.",
        hours="Class schedules vary; call for current sessions",
        tags="atlanta|fulton|education|GED|literacy|reentry",
        services="GED preparation|Digital literacy|Workforce readiness|One-on-one tutoring|Employment referrals",
        county="Fulton", served_counties="Fulton|DeKalb|Cobb", coverage="multi",
        _source="https://literacyaction.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Augusta Technical College — Adult Education",
        category="education", region="Augusta / Richmond County",
        description="Augusta Technical College Adult Education program provides GED and HiSET preparation, English literacy, and workforce readiness for justice-involved adults in Richmond, Columbia, Burke, and McDuffie counties. Free instruction helps returning citizens earn high school equivalency credentials required for WorkSource CSRA employment programs and technical college enrollment. Contact the adult education office for orientation—not walk-in GED testing without appointment.",
        description_es="El programa de Educación para Adultos de Augusta Technical College ofrece preparación GED y HiSET, alfabetización en inglés y preparación laboral para adultos con antecedentes penales en los condados Richmond, Columbia, Burke y McDuffie. Instrucción gratuita ayuda a ciudadanos que regresan a obtener credenciales de equivalencia de secundaria requeridas para programas de empleo WorkSource CSRA.",
        address="3200 Augusta Tech Drive", city="Augusta", phone="706-771-4131", email="",
        website="https://www.augustatech.edu/adult-education",
        eligibility="Adults age 16+ in CSRA counties seeking GED or HiSET; open to justice-involved participants.",
        eligibility_es="Adultos de 16 años o más en condados CSRA que buscan GED o HiSET; abierto a participantes con antecedentes penales.",
        notes="Call 706-771-4131 for enrollment; connects to WorkSource CSRA and Augusta reentry partners.",
        notes_es="Llame al 706-771-4131 para inscripción; conecta con WorkSource CSRA y aliados de reinserción de Augusta.",
        hours="Monday–Thursday class hours; call for schedule",
        tags="augusta|richmond|education|GED|HiSET|reentry",
        services="GED preparation|HiSET preparation|English literacy|Workforce readiness|Technical college pathways",
        county="Richmond", served_counties="Richmond|Columbia|Burke|McDuffie", coverage="multi",
        _source="https://www.augustatech.edu/adult-education", _source_type="government", _confidence="high",
    )
    add(
        name="Savannah Technical College — Adult Education",
        category="education", region="Savannah / Chatham County",
        description="Savannah Technical College Adult Education offers GED preparation, adult literacy, and workforce transition classes for low-income adults in Chatham, Effingham, and Bryan counties including returning citizens from Chatham County Jail seeking credentials for coastal Georgia jobs. Instructors connect graduates to Savannah Technical College certificate programs and WorkSource Coastal career centers. Enrollment required before classes begin.",
        description_es="Savannah Technical College Educación para Adultos ofrece preparación GED, alfabetización para adultos y clases de transición laboral para adultos de bajos ingresos en los condados Chatham, Effingham y Bryan, incluidos ciudadanos que regresan de la cárcel del condado Chatham. Instructores conectan graduados a programas de certificado y centros WorkSource Coastal.",
        address="5717 White Bluff Road", city="Savannah", phone="912-443-5497", email="",
        website="https://www.savannahtech.edu/adult-education/",
        eligibility="Adults age 16+ in coastal Georgia seeking GED; justice-involved adults accepted.",
        eligibility_es="Adultos de 16 años o más en la costa de Georgia que buscan GED; adultos con antecedentes penales aceptados.",
        notes="Call 912-443-5497 for enrollment at Savannah, Effingham, or Liberty county sites.",
        notes_es="Llame al 912-443-5497 para inscripción en sitios de Savannah, Effingham o Liberty.",
        hours="Contact for class schedule",
        tags="savannah|chatham|education|GED|reentry",
        services="GED preparation|Adult literacy|Workforce transition|Technical college pathways|Career center referrals",
        county="Chatham", served_counties="Chatham|Effingham|Bryan", coverage="multi",
        _source="https://www.savannahtech.edu/adult-education/", _source_type="government", _confidence="high",
    )
    add(
        name="Columbus Technical College — Adult Education",
        category="education", region="Columbus / Muscogee County",
        description="Columbus Technical College Adult Education provides GED and HiSET preparation for justice-involved adults in Muscogee, Harris, Chattahoochee, Marion, and Stewart counties rebuilding education credentials after release from Muscogee County Jail or nearby state prisons. Free classes prepare participants for high school equivalency exams and connect to Columbus Technical College workforce certificate programs and WorkSource Columbus career services.",
        description_es="Columbus Technical College Educación para Adultos ofrece preparación GED y HiSET para adultos con antecedentes penales en los condados Muscogee, Harris, Chattahoochee, Marion y Stewart que reconstruyen credenciales educativas después de la liberación. Clases gratuitas preparan para exámenes de equivalencia y conectan a programas de certificado laboral.",
        address="928 Manchester Expressway", city="Columbus", phone="706-641-5722", email="",
        website="https://www.columbustech.edu/adult-education",
        eligibility="Adults age 16+ in west Georgia service area; open to returning citizens.",
        eligibility_es="Adultos de 16 años o más en el área de servicio del oeste de Georgia; abierto a ciudadanos que regresan.",
        notes="Call 706-641-5722 for enrollment; partners with Valley Rescue Mission and WorkSource Columbus.",
        notes_es="Llame al 706-641-5722 para inscripción; aliados con Valley Rescue Mission y WorkSource Columbus.",
        hours="Contact for class schedule",
        tags="columbus|muscogee|education|GED|HiSET|reentry",
        services="GED preparation|HiSET preparation|Workforce certificates|Career center referrals|Adult literacy",
        county="Muscogee", served_counties="Muscogee|Harris|Chattahoochee|Marion|Stewart", coverage="multi",
        _source="https://www.columbustech.edu/adult-education", _source_type="government", _confidence="high",
    )

    add(
        name="Georgia Center for Child Advocacy — Family Reunification Supports",
        category="family-children", region="Statewide",
        description="The Georgia Center for Child Advocacy provides trauma-informed services for children and families affected by abuse and supports family stabilization for parents rebuilding relationships after incarceration through referrals and community partnerships. While not exclusively a reentry program, staff connect justice-involved parents to counseling, parenting resources, and community supports in metro Atlanta and through statewide training networks. Referral-based services—not emergency shelter.",
        description_es="El Centro de Defensa de la Infancia de Georgia ofrece servicios informados sobre trauma para niños y familias afectados por abuso y apoya la estabilización familiar para padres que reconstruyen relaciones después de la encarcelación mediante referencias y alianzas comunitarias. El personal conecta a padres con antecedentes penales a consejería y recursos de crianza en el metro de Atlanta.",
        address="673 Metro Place", city="Atlanta", phone="404-880-4929", email="",
        website="https://georgiacenterforchildadvocacy.org",
        eligibility="Children and families referred through DFCS, law enforcement, or community partners; justice-involved parents may access through partner referrals.",
        eligibility_es="Niños y familias referidos a través de DFCS, aplicación de la ley o aliados comunitarios; padres con antecedentes penales pueden acceder mediante referencias.",
        notes="Call 404-880-4929 for referral information; primarily serves metro Atlanta with statewide training programs.",
        notes_es="Llame al 404-880-4929 para información de referencias; sirve principalmente el metro de Atlanta con programas de capacitación estatales.",
        hours="Monday–Friday business hours",
        tags="statewide|family-children|trauma|parenting|reentry",
        services="Trauma-informed counseling referrals|Parenting resource navigation|Family stabilization supports|Community partner referrals",
        county="Fulton", served_counties="", coverage="statewide",
        _source="https://georgiacenterforchildadvocacy.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Aid to Children of Imprisoned Mothers (AIM) — Atlanta",
        category="family-children", region="Atlanta / Fulton County",
        description="Aid to Children of Imprisoned Mothers (AIM) supports children and caregivers while mothers are incarcerated and during family reunification after release in metro Atlanta. Programs include emergency assistance, mentoring, holiday support, and resource navigation helping justice-involved mothers reconnect with children and stabilize housing. Direct family support services—not a statewide hotline.",
        description_es="Aid to Children of Imprisoned Mothers (AIM) apoya a niños y cuidadores mientras las madres están encarceladas y durante la reunificación familiar después de la liberación en el metro de Atlanta. Los programas incluyen asistencia de emergencia, mentoría, apoyo en festividades y navegación de recursos ayudando a madres con antecedentes penales a reconectarse con sus hijos.",
        address="PO Box 191", city="Atlanta", phone="404-223-1227", email="",
        website="https://www.acim.org",
        eligibility="Children of incarcerated mothers and caregivers in metro Atlanta; mothers recently released seeking reunification support.",
        eligibility_es="Niños de madres encarceladas y cuidadores en el metro de Atlanta; madres recién liberadas que buscan apoyo de reunificación.",
        notes="Call 404-223-1227 or visit acim.org; primarily serves Fulton and surrounding metro counties.",
        notes_es="Llame al 404-223-1227 o visite acim.org; sirve principalmente Fulton y condados metropolitanos circundantes.",
        hours="Contact for program hours",
        tags="atlanta|fulton|family-children|reunification|women|reentry",
        services="Emergency family assistance|Mentoring for children|Reunification support|Resource navigation|Caregiver support",
        county="Fulton", served_counties="Fulton|DeKalb|Cobb|Clayton", coverage="multi",
        _source="https://www.acim.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Georgia DFCS — Reunification & Parenting Supports",
        category="family-children", region="Statewide",
        description="Georgia DFCS provides reunification services, parenting education, and family preservation supports for parents working to regain custody or stabilize family relationships after incarceration through county DFCS offices and contracted providers. Justice-involved parents with open DFCS cases can access case management, supervised visitation coordination, and referrals to community resources. Services require DFCS case involvement—not walk-in for unrelated families.",
        description_es="Georgia DFCS ofrece servicios de reunificación, educación para padres y apoyos de preservación familiar para padres que trabajan para recuperar la custodia o estabilizar relaciones familiares después de la encarcelación a través de oficinas DFCS del condado. Padres con antecedentes penales con casos abiertos de DFCS pueden acceder a manejo de casos y referencias comunitarias.",
        address="2 Peachtree Street NW", city="Atlanta", phone="1-877-423-4746", email="",
        website="https://dfcs.georgia.gov/services/adoption-and-foster-care/reunification",
        eligibility="Parents with active DFCS cases seeking reunification; justice-involved parents must work through assigned DFCS case manager.",
        eligibility_es="Padres con casos activos de DFCS que buscan reunificación; padres con antecedentes penales deben trabajar con su administrador de casos DFCS asignado.",
        notes="Contact your county DFCS office or assigned case manager; not for families without open DFCS cases.",
        notes_es="Contacte su oficina DFCS del condado o administrador de casos asignado; no para familias sin casos abiertos de DFCS.",
        hours="County office hours vary",
        tags="statewide|family-children|reunification|DFCS|parenting",
        services="Reunification case management|Parenting education|Supervised visitation coordination|Family preservation referrals",
        county="Fulton", served_counties="", coverage="statewide",
        _source="https://dfcs.georgia.gov/services/adoption-and-foster-care/reunification", _source_type="government", _confidence="high",
    )

    add(
        name="Georgia Secretary of State — Probate Court Vital Records Guide",
        category="id-documentation", region="Statewide",
        description="Georgia probate courts issue certified birth certificate copies needed for state ID, COMPASS benefits, and employment after release. The Secretary of State provides guidance on locating the correct county probate court for birth records based on county of birth. Returning citizens should contact the probate court in their birth county or use the online vital records portal for statewide orders.",
        description_es="Los tribunales de sucesiones de Georgia emiten copias certificadas de certificados de nacimiento necesarias para identificación estatal, beneficios COMPASS y empleo después de la liberación. La Secretaría de Estado ofrece orientación para localizar el tribunal de sucesiones correcto según el condado de nacimiento.",
        address="214 State Capitol", city="Atlanta", phone="404-656-2881", email="",
        website="https://sos.ga.gov/page/order-vital-records",
        eligibility="Individuals with legal right to request Georgia birth records; acceptable ID required; fees vary by county.",
        eligibility_es="Personas con derecho legal a solicitar registros de nacimiento de Georgia; se requiere identificación aceptable; tarifas varían por condado.",
        notes="Order through county probate court or dph.georgia.gov/vital-records; allow processing time before DDS ID appointment.",
        notes_es="Ordene a través del tribunal de sucesiones del condado o dph.georgia.gov/vital-records; permita tiempo de procesamiento antes de cita de identificación DDS.",
        hours="Probate court hours vary by county",
        tags="statewide|id-documentation|birth-certificate|vital-records",
        services="Birth certificate guidance|Probate court locator|Vital records process information",
        county="Fulton", served_counties="", coverage="statewide",
        _source="https://sos.ga.gov/page/order-vital-records", _source_type="government", _confidence="high",
    )
    add(
        name="Social Security Administration — Georgia Field Offices",
        category="id-documentation", region="Statewide",
        description="Social Security Administration field offices in Georgia help returning citizens apply for or replace Social Security cards required for employment, COMPASS benefits, and DDS state ID applications. SSA offices accept walk-in and appointment requests for card replacement with proof of identity. Not a reentry-specific program but essential for documentation after incarceration.",
        description_es="Las oficinas de campo de la Administración del Seguro Social en Georgia ayudan a ciudadanos que regresan a solicitar o reemplazar tarjetas de Seguro Social necesarias para empleo, beneficios COMPASS y solicitudes de identificación estatal DDS. Las oficinas SSA aceptan solicitudes con cita o sin cita para reemplazo de tarjetas.",
        address="", city="Atlanta", phone="800-772-1213", email="",
        website="https://www.ssa.gov/locator",
        eligibility="U.S. citizens and eligible non-citizens needing Social Security card; identity documentation required.",
        eligibility_es="Ciudadanos estadounidenses y no ciudadanos elegibles que necesitan tarjeta de Seguro Social; se requiere documentación de identidad.",
        notes="Use ssa.gov/locator to find nearest office; schedule appointment online; bring ID and release documents.",
        notes_es="Use ssa.gov/locator para encontrar la oficina más cercana; programe cita en línea; traiga identificación y documentos de liberación.",
        hours="Field office hours vary; call 800-772-1213",
        tags="statewide|id-documentation|social-security|reentry",
        services="Social Security card application|Card replacement|Office locator|Identity verification guidance",
        county="Fulton", served_counties="", coverage="statewide",
        _source="https://www.ssa.gov/locator", _source_type="government", _confidence="high",
    )

    add(
        name="Atlanta Volunteer Lawyers Foundation — Record Restriction Clinic",
        category="legal-aid", region="Atlanta / Fulton County",
        description="Atlanta Volunteer Lawyers Foundation provides pro bono civil legal assistance to low-income Fulton County residents including record restriction clinics helping returning citizens understand Georgia's Second Chance Law and navigate petition processes for eligible misdemeanor and felony records. Clinics and referrals connect participants to volunteer attorneys—not criminal defense representation.",
        description_es="Atlanta Volunteer Lawyers Foundation ofrece asistencia legal civil pro bono a residentes de bajos ingresos del condado Fulton incluyendo clínicas de restricción de registros que ayudan a ciudadanos que regresan a entender la Ley de Segunda Oportunidad de Georgia y procesos de petición para registros elegibles.",
        address="229 Peachtree Street NE", city="Atlanta", phone="404-521-0790", email="",
        website="https://www.avlf.org",
        eligibility="Low-income Fulton County residents; record restriction eligibility depends on offense type and waiting periods under Georgia law.",
        eligibility_es="Residentes de bajos ingresos del condado Fulton; la elegibilidad para restricción de registros depende del tipo de delito y períodos de espera.",
        notes="Call 404-521-0790 or visit avlf.org for clinic schedule; separate from Atlanta Legal Aid Society.",
        notes_es="Llame al 404-521-0790 o visite avlf.org para horario de clínicas; separado de Atlanta Legal Aid Society.",
        hours="Clinic hours vary; call for schedule",
        tags="atlanta|fulton|legal-aid|record-restriction|expungement|reentry",
        services="Record restriction clinics|Pro bono civil legal aid|Second Chance Law navigation|Volunteer attorney referrals",
        county="Fulton", served_counties="Fulton", coverage="single",
        _source="https://www.avlf.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Georgia Legal Services — Albany Office",
        category="legal-aid", region="Albany / Southwest Georgia",
        description="Georgia Legal Services Program Albany office provides free civil legal aid to low-income residents of Dougherty, Lee, Worth, Terrell, and surrounding southwest Georgia counties including record restriction assistance, eviction defense, and public benefits appeals for returning citizens. Attorneys handle reentry-related civil legal barriers—not criminal defense.",
        description_es="La oficina de Albany de Georgia Legal Services Program ofrece asistencia legal civil gratuita a residentes de bajos ingresos de Dougherty, Lee, Worth, Terrell y condados del suroeste de Georgia incluyendo restricción de registros y apelaciones de beneficios públicos para ciudadanos que regresan.",
        address="230 S. Jackson Street", city="Albany", phone="229-431-6000", email="",
        website="https://www.glsp.org/offices",
        eligibility="Low-income residents of southwest Georgia GLSP service area; LSC income limits apply.",
        eligibility_es="Residentes de bajos ingresos del área de servicio GLSP del suroeste de Georgia; aplican límites de ingresos LSC.",
        notes="Call 229-431-6000 or apply through glsp.org intake; serves 10+ southwest Georgia counties.",
        notes_es="Llame al 229-431-6000 o solicite a través de admisión glsp.org; sirve más de 10 condados del suroeste de Georgia.",
        hours="Monday–Friday business hours",
        tags="albany|dougherty|legal-aid|record-restriction|southwest-georgia|reentry",
        services="Record restriction assistance|Eviction defense|Benefits appeals|Civil legal representation|Housing legal aid",
        county="Dougherty", served_counties="Dougherty|Lee|Worth|Terrell|Mitchell|Colquitt|Tift|Turner|Crisp|Sumter", coverage="multi",
        _source="https://www.glsp.org/offices", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Georgia Legal Services — Gainesville Office",
        category="legal-aid", region="Gainesville / Northeast Georgia",
        description="Georgia Legal Services Program Gainesville office serves low-income residents of Hall, Banks, Dawson, Lumpkin, White, and northeast Georgia counties with civil legal aid including record restriction, housing disputes, and public benefits advocacy for justice-involved adults rebuilding stability after release from Hall County Jail or state custody.",
        description_es="La oficina de Gainesville de Georgia Legal Services Program sirve a residentes de bajos ingresos de Hall, Banks, Dawson, Lumpkin, White y condados del noreste de Georgia con asistencia legal civil incluyendo restricción de registros y defensa de vivienda para adultos con antecedentes penales.",
        address="430 Prior Street", city="Gainesville", phone="770-535-5727", email="",
        website="https://www.glsp.org/offices",
        eligibility="Low-income northeast Georgia residents in GLSP service area; record restriction eligibility varies by offense.",
        eligibility_es="Residentes de bajos ingresos del noreste de Georgia en el área de servicio GLSP; la elegibilidad para restricción de registros varía.",
        notes="Call 770-535-5727 for intake; serves 13 northeast Georgia counties from Gainesville office.",
        notes_es="Llame al 770-535-5727 para admisión; sirve 13 condados del noreste de Georgia desde la oficina de Gainesville.",
        hours="Monday–Friday business hours",
        tags="gainesville|hall|legal-aid|northeast-georgia|record-restriction|reentry",
        services="Civil legal representation|Record restriction|Housing legal aid|Benefits advocacy|Eviction defense",
        county="Hall", served_counties="Hall|Banks|Dawson|Lumpkin|White|Habersham|Rabun|Towns|Union|Stephens|Franklin|Hart", coverage="multi",
        _source="https://www.glsp.org/offices", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Georgia Legal Services — Valdosta Office",
        category="legal-aid", region="Valdosta / South Georgia",
        description="Georgia Legal Services Program Valdosta office provides free civil legal assistance to low-income residents of Lowndes, Brooks, Echols, Lanier, and south Georgia counties including record restriction petitions, public benefits appeals, and housing legal aid for returning citizens from Lowndes County Jail and nearby correctional facilities.",
        description_es="La oficina de Valdosta de Georgia Legal Services Program ofrece asistencia legal civil gratuita a residentes de bajos ingresos de Lowndes, Brooks, Echols, Lanier y condados del sur de Georgia incluyendo peticiones de restricción de registros y apelaciones de beneficios públicos.",
        address="1707 North Patterson Street", city="Valdosta", phone="229-245-9400", email="",
        website="https://www.glsp.org/offices",
        eligibility="Low-income south Georgia residents in GLSP Valdosta service area.",
        eligibility_es="Residentes de bajos ingresos del sur de Georgia en el área de servicio Valdosta de GLSP.",
        notes="Call 229-245-9400 for intake appointment; serves 10 south Georgia counties.",
        notes_es="Llame al 229-245-9400 para cita de admisión; sirve 10 condados del sur de Georgia.",
        hours="Monday–Friday business hours",
        tags="valdosta|lowndes|legal-aid|south-georgia|record-restriction|reentry",
        services="Record restriction petitions|Benefits appeals|Housing legal aid|Civil legal representation",
        county="Lowndes", served_counties="Lowndes|Brooks|Echols|Lanier|Berrien|Cook|Thomas|Grady|Decatur|Mitchell", coverage="multi",
        _source="https://www.glsp.org/offices", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Southern Center for Human Rights — Reentry Legal Advocacy",
        category="legal-aid", region="Atlanta / Statewide",
        description="Southern Center for Human Rights is a nonprofit law firm advocating for criminal justice reform and providing legal representation in select civil rights and conditions-of-confinement cases affecting incarcerated and formerly incarcerated Georgians. While not a general legal aid intake line, SCRH resources on parole, probation, and record restriction help returning citizens understand legal rights. Advocacy organization—not a walk-in clinic for all civil cases.",
        description_es="Southern Center for Human Rights es un bufete de abogados sin fines de lucro que aboga por la reforma de justicia penal y proporciona representación legal en casos selectos de derechos civiles que afectan a georgianos encarcelados y anteriormente encarcelados. Recursos sobre libertad condicional y restricción de registros ayudan a ciudadanos que regresan.",
        address="83 Poplar Street NW", city="Atlanta", phone="404-688-1202", email="",
        website="https://www.schr.org",
        eligibility="Select cases involving civil rights and criminal justice system conditions; not general legal aid intake.",
        eligibility_es="Casos selectos que involucran derechos civiles y condiciones del sistema de justicia penal; no admisión general de asistencia legal.",
        notes="Visit schr.org for resources; for civil legal aid call GLSP 1-800-498-9469 or Atlanta Legal Aid.",
        notes_es="Visite schr.org para recursos; para asistencia legal civil llame a GLSP 1-800-498-9469 o Atlanta Legal Aid.",
        hours="Office Monday–Friday business hours",
        tags="statewide|legal-aid|criminal-justice-reform|advocacy|reentry",
        services="Civil rights advocacy|Criminal justice reform resources|Legal rights education|Select case representation",
        county="Fulton", served_counties="", coverage="statewide",
        _source="https://www.schr.org", _source_type="nonprofit", _confidence="high",
    )

    add(
        name="Georgia Peer Recovery Support — CARES Warm Line",
        category="peer-support", region="Statewide",
        description="Georgia Council on Substance Abuse operates the CARES Warm Line providing peer support from certified peer specialists to Georgians in recovery including justice-involved individuals navigating substance use recovery after release. Trained peers offer non-crisis support, resource navigation, and connection to recovery meetings statewide. For crisis call GCAL 800-715-4225 or 988—not a substitute for emergency services.",
        description_es="Georgia Council on Substance Abuse opera la Línea de Apoyo CARES que proporciona apoyo entre pares de especialistas certificados a georgianos en recuperación incluidas personas con antecedentes penales que navegan recuperación de uso de sustancias después de la liberación. Para crisis llame a GCAL 800-715-4225 o 988.",
        address="", city="Atlanta", phone="844-326-5525", email="",
        website="https://gasupport.org",
        eligibility="Open to Georgians in recovery from substance use including justice-involved individuals; non-crisis warm line.",
        eligibility_es="Abierto a georgianos en recuperación de uso de sustancias incluidas personas con antecedentes penales; línea de apoyo no crisis.",
        notes="Call or text 844-326-5525; peer specialists available; also see gasupport.org for recovery community resources.",
        notes_es="Llame o envíe texto al 844-326-5525; especialistas entre pares disponibles; vea gasupport.org para recursos comunitarios de recuperación.",
        hours="Published warm line hours; check gasupport.org",
        tags="statewide|peer-support|recovery|warm-line|substance-use|reentry",
        services="Peer recovery support|Resource navigation|Recovery meeting connections|Non-crisis counseling",
        county="Fulton", served_counties="", coverage="statewide",
        _source="https://gasupport.org", _source_type="nonprofit", _confidence="high",
    )

    add(
        name="Georgia Department of Behavioral Health — Opioid Crisis Helpline",
        category="state-agency", region="Statewide",
        description="The Georgia Department of Behavioral Health and Developmental Disabilities supports statewide substance use disorder treatment access through the Opioid Crisis Helpline and provider network navigation for Georgians including justice-involved individuals seeking MAT and recovery services after release. DBHDD coordinates publicly funded behavioral health services through regional providers. For crisis call GCAL 800-715-4225.",
        description_es="El Departamento de Salud Conductual y Desarrollo de Georgia apoya el acceso estatal al tratamiento de trastornos por uso de sustancias a través de la Línea de Crisis de Opioides y navegación de red de proveedores para georgianos incluidas personas con antecedentes penales que buscan TMO después de la liberación. Para crisis llame a GCAL 800-715-4225.",
        address="2 Peachtree Street NW", city="Atlanta", phone="888-901-0029", email="",
        website="https://dbhdd.georgia.gov",
        eligibility="Georgia residents seeking substance use treatment information and referrals; provider admission rules vary.",
        eligibility_es="Residentes de Georgia que buscan información y referencias de tratamiento de uso de sustancias; las reglas de admisión varían.",
        notes="Opioid Crisis Helpline 888-901-0029; find providers at dbhdd.georgia.gov; GCAL for behavioral health crisis.",
        notes_es="Línea de Crisis de Opioides 888-901-0029; encuentre proveedores en dbhdd.georgia.gov; GCAL para crisis de salud conductual.",
        hours="Helpline hours vary; GCAL 24/7",
        tags="statewide|state-agency|substance-use|DBHDD|MAT|reentry",
        services="Treatment provider navigation|Opioid crisis helpline|Public behavioral health referrals|MAT program information",
        county="Fulton", served_counties="", coverage="statewide",
        _source="https://dbhdd.georgia.gov", _source_type="government", _confidence="high",
    )
    add(
        name="Georgia Department of Community Affairs — Housing Resources",
        category="state-agency", region="Statewide",
        description="The Georgia Department of Community Affairs administers affordable housing programs, homeless services grants, and the Reentry Partnership Housing (RPH) initiative connecting returning citizens to short-term stable housing through certified providers. DCA housing navigators help justice-involved Georgians locate rental assistance and transitional housing resources—not emergency shelter intake.",
        description_es="El Departamento de Asuntos Comunitarios de Georgia administra programas de vivienda asequible, subvenciones de servicios para personas sin hogar y la iniciativa de Vivienda de Asociación para la Reinserción (RPH) que conecta a ciudadanos que regresan con vivienda estable a corto plazo. Navegadores de vivienda DCA ayudan a georgianos con antecedentes penales a localizar asistencia de alquiler.",
        address="60 Executive Park South NE", city="Atlanta", phone="404-679-4840", email="",
        website="https://www.dca.ga.gov",
        eligibility="Georgia residents seeking affordable housing or RPH referral through DCS; program-specific requirements apply.",
        eligibility_es="Residentes de Georgia que buscan vivienda asequible o referencia RPH a través de DCS; aplican requisitos específicos del programa.",
        notes="Visit dca.ga.gov for housing search and RPH information; RPH requires DCS officer referral.",
        notes_es="Visite dca.ga.gov para búsqueda de vivienda e información RPH; RPH requiere referencia del oficial de DCS.",
        hours="State office Monday–Friday business hours",
        tags="statewide|state-agency|housing|RPH|affordable-housing|reentry",
        services="Affordable housing locator|RPH program information|Homeless services grants|Housing navigation",
        county="DeKalb", served_counties="", coverage="statewide",
        _source="https://www.dca.ga.gov", _source_type="government", _confidence="high",
    )

    add(
        name="Augusta VA Medical Center — Veterans Justice Outreach",
        category="veterans", region="Augusta / CSRA",
        description="Augusta VA Medical Center Veterans Justice Outreach specialist connects justice-involved veterans in the CSRA to VA health care, benefits, housing, and treatment court supports after release from Richmond County Jail or state custody. VJO staff coordinate with GA Department of Veterans Service and local courts on veteran reentry plans. VA enrollment required for medical services.",
        description_es="El especialista de Veterans Justice Outreach del Centro Médico VA de Augusta conecta a veteranos con antecedentes penales en el CSRA con atención médica del VA, beneficios, vivienda y apoyos de tribunales de tratamiento después de la liberación. El personal VJO coordina con el Departamento de Servicios para Veteranos de Georgia.",
        address="1 Freedom Way", city="Augusta", phone="706-733-0188", email="",
        website="https://www.va.gov/augusta-health-care/",
        eligibility="Justice-involved veterans with qualifying military service; VA eligibility determination required.",
        eligibility_es="Veteranos con antecedentes penales con servicio militar calificado; se requiere determinación de elegibilidad del VA.",
        notes="Contact VJO through Augusta VA; also call Georgia Department of Veterans Service county office for claims help.",
        notes_es="Contacte VJO a través del VA de Augusta; también llame a la oficina del condado del Departamento de Servicios para Veteranos de Georgia.",
        hours="VA business hours; call for VJO appointment",
        tags="augusta|richmond|veterans|VJO|reentry|justice-involved-veterans",
        services="Veterans Justice Outreach|VA health care enrollment|Benefits navigation|Treatment court coordination|Housing referrals",
        county="Richmond", served_counties="Richmond|Columbia|Burke|McDuffie|Jefferson|Lincoln|Warren|Wilkes", coverage="multi",
        _source="https://www.va.gov/augusta-health-care/", _source_type="government", _confidence="high",
    )
    add(
        name="Dublin VA Medical Center — Veterans Justice Outreach",
        category="veterans", region="Central Georgia",
        description="Dublin VA Medical Center Veterans Justice Outreach serves justice-involved veterans in central and south Georgia including those released from Macon-Bibb County facilities and state prisons in the region. VJO specialists link veterans to VA mental health, substance use treatment, and housing resources as part of veteran treatment court and reentry partnerships.",
        description_es="Veterans Justice Outreach del Centro Médico VA de Dublin sirve a veteranos con antecedentes penales en el centro y sur de Georgia incluidos los liberados de instalaciones del condado Macon-Bibb y prisiones estatales de la región. Especialistas VJO vinculan a veteranos con salud mental del VA, tratamiento de uso de sustancias y recursos de vivienda.",
        address="1826 Veterans Boulevard", city="Dublin", phone="478-274-5200", email="",
        website="https://www.va.gov/dublin-health-care/",
        eligibility="Justice-involved veterans in central/south Georgia with qualifying military service.",
        eligibility_es="Veteranos con antecedentes penales en el centro/sur de Georgia con servicio militar calificado.",
        notes="Call Dublin VA for VJO referral; coordinates with Georgia DVS county offices.",
        notes_es="Llame al VA de Dublin para referencia VJO; coordina con oficinas del condado DVS de Georgia.",
        hours="VA business hours",
        tags="dublin|laurens|veterans|VJO|central-georgia|reentry",
        services="Veterans Justice Outreach|VA mental health referrals|Substance use treatment|Housing navigation|Treatment court support",
        county="Laurens", served_counties="Laurens|Bibb|Houston|Peach|Twiggs|Wilkinson|Johnson|Washington|Jefferson", coverage="multi",
        _source="https://www.va.gov/dublin-health-care/", _source_type="government", _confidence="high",
    )
    add(
        name="Trinka Davis Veterans Village — Transitional Housing",
        category="veterans", region="Carrollton / West Georgia",
        description="Trinka Davis Veterans Village provides transitional housing and supportive services for homeless and at-risk veterans including justice-involved veterans rebuilding stability in west Georgia. On-site case management, benefits assistance, and employment supports help participants transition to permanent housing. VA and community partner referrals required for admission.",
        description_es="Trinka Davis Veterans Village ofrece vivienda transicional y servicios de apoyo para veteranos sin hogar y en riesgo incluidos veteranos con antecedentes penales que reconstruyen estabilidad en el oeste de Georgia. Manejo de casos en el sitio, asistencia de beneficios y apoyos de empleo ayudan a participantes a transicionar a vivienda permanente.",
        address="924 Maple Street", city="Carrollton", phone="770-832-7860", email="",
        website="https://www.trinkadavisfoundation.org",
        eligibility="Homeless or at-risk veterans including justice-involved veterans; referral through VA or community partners typically required.",
        eligibility_es="Veteranos sin hogar o en riesgo incluidos veteranos con antecedentes penales; referencia a través del VA o aliados comunitarios generalmente requerida.",
        notes="Call 770-832-7860 for intake information; partners with Atlanta VA and Georgia DVS.",
        notes_es="Llame al 770-832-7860 para información de admisión; aliados con VA de Atlanta y DVS de Georgia.",
        hours="Contact for program hours",
        tags="carrollton|carroll|veterans|transitional-housing|reentry|west-georgia",
        services="Transitional veteran housing|Case management|Benefits assistance|Employment supports|Permanent housing transition",
        county="Carroll", served_counties="Carroll|Douglas|Paulding|Haralson|Heard|Coweta", coverage="multi",
        _source="https://www.trinkadavisfoundation.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Georgia Veterans Education Career Transition Resource (VECTR)",
        category="veterans", region="Statewide",
        description="Georgia VECTR centers help veterans including justice-involved veterans translate military experience to civilian careers through skills assessment, training referrals, and employer connections at locations affiliated with technical colleges statewide. VECTR staff coordinate with GVRA and WorkSource Georgia on employment supports for veterans with barriers including criminal records.",
        description_es="Los centros VECTR de Georgia ayudan a veteranos incluidos veteranos con antecedentes penales a traducir experiencia militar a carreras civiles mediante evaluación de habilidades, referencias de capacitación y conexiones con empleadores en ubicaciones afiliadas a colegios técnicos en todo el estado.",
        address="1800 Century Boulevard NE", city="Atlanta", phone="404-679-1600", email="",
        website="https://www.tcsg.edu/vectr/",
        eligibility="Georgia veterans with honorable or qualifying discharge seeking civilian employment or training.",
        eligibility_es="Veteranos de Georgia con baja honorable o calificada que buscan empleo o capacitación civil.",
        notes="Find VECTR locations at tcsg.edu/vectr; coordinates with Georgia DVS and WorkSource career centers.",
        notes_es="Encuentre ubicaciones VECTR en tcsg.edu/vectr; coordina con DVS de Georgia y centros de carrera WorkSource.",
        hours="Center hours vary by location",
        tags="statewide|veterans|employment|VECTR|training|reentry",
        services="Military skills translation|Career assessment|Training referrals|Employer connections|WorkSource coordination",
        county="Fulton", served_counties="", coverage="statewide",
        _source="https://www.tcsg.edu/vectr/", _source_type="government", _confidence="high",
    )
    add(
        name="Veterans Court Program — Georgia Accountability Courts",
        category="veterans", region="Statewide",
        description="Georgia's Veterans Court Program through the Accountability Court system provides treatment-oriented supervision alternatives for justice-involved veterans with substance use or mental health needs, combining court oversight with VA services, peer support, and housing referrals. Eligible veterans in participating counties access structured reentry supports instead of traditional incarceration. Referral through court system—not walk-in enrollment.",
        description_es="El Programa de Tribunales para Veteranos de Georgia a través del sistema de Tribunales de Responsabilidad ofrece alternativas de supervisión orientadas al tratamiento para veteranos con antecedentes penales con necesidades de salud mental o uso de sustancias, combinando supervisión judicial con servicios del VA y apoyo entre pares.",
        address="244 Washington Street SW", city="Atlanta", phone="404-656-3470", email="",
        website="https://cjcc.georgia.gov/grants/veterans-court-program",
        eligibility="Justice-involved veterans in participating Georgia counties meeting veterans court eligibility criteria; court referral required.",
        eligibility_es="Veteranos con antecedentes penales en condados participantes de Georgia que cumplan criterios de elegibilidad; se requiere referencia judicial.",
        notes="Participation varies by county; contact local accountability court or Georgia CJCC for participating jurisdictions.",
        notes_es="La participación varía por condado; contacte el tribunal de responsabilidad local o Georgia CJCC para jurisdicciones participantes.",
        hours="Court schedules vary",
        tags="statewide|veterans|accountability-court|treatment-court|reentry",
        services="Veterans court supervision|VA treatment coordination|Peer support|Housing referrals|Structured reentry",
        county="Fulton", served_counties="", coverage="statewide",
        _source="https://cjcc.georgia.gov/grants/veterans-court-program", _source_type="government", _confidence="high",
    )
