"""Polish pass: program-level pins for infra-only counties + verified regional partners."""


def register_polish(add):
    add(
        name="GNTC — Catoosa County Adult Education",
        category="education",
        region="Ringgold / Catoosa County",
        description="Georgia Northwestern Technical College operates the Shirley Smith Learning Center in Ringgold providing free GED and HiSET preparation, adult literacy, and workforce transition classes for Catoosa County residents including returning citizens rebuilding education credentials after release. Instructors connect graduates to technical college certificate programs and WorkSource Dalton career services in northwest Georgia. Enrollment and orientation required before classes begin—not walk-in testing without appointment.",
        description_es="Georgia Northwestern Technical College opera el Shirley Smith Learning Center en Ringgold con preparación GED y HiSET gratuita, alfabetización para adultos y clases de transición laboral para residentes del condado Catoosa, incluidos ciudadanos que regresan que reconstruyen credenciales educativas. Los instructores conectan graduados a programas de certificado y servicios WorkSource Dalton.",
        address="36 Muscogee Trail, Benton Place",
        city="Ringgold",
        phone="706-965-6155",
        email="",
        website="https://www.gntc.edu/adult-education/",
        eligibility="Adults age 16+ in Catoosa County not enrolled in high school; justice-involved adults welcome.",
        eligibility_es="Adultos de 16 años o más en el condado Catoosa no inscritos en secundaria; adultos con antecedentes penales bienvenidos.",
        notes="Call 706-965-6155 ext. 7 for enrollment; free classes through TCSG adult education funding.",
        notes_es="Llame al 706-965-6155 ext. 7 para inscripción; clases gratuitas mediante financiamiento TCSG.",
        hours="Contact for class schedule",
        tags="catoosa|ringgold|education|GED|GNTC|reentry",
        services="GED preparation|HiSET preparation|Adult literacy|Workforce transition|Technical college referrals",
        county="Catoosa",
        served_counties="Catoosa",
        coverage="single",
        _source="https://www.gntc.edu/adult-education/class/",
        _source_type="government",
        _confidence="high",
    )
    add(
        name="The DEO Clinic — Free Healthcare",
        category="healthcare",
        region="Dalton / Northwest Georgia",
        description="The DEO Clinic provides free primary and chronic-disease care to low-income uninsured adults in Whitfield and Murray counties including justice-involved returning citizens establishing medical homes after release. Volunteers and staff treat hypertension, diabetes, COPD, and acute illnesses at the Mack Gaston Community Center clinic in Dalton with medication assistance and follow-up visits—not a hospital emergency department.",
        description_es="The DEO Clinic ofrece atención primaria gratuita y manejo de enfermedades crónicas para adultos sin seguro de bajos ingresos en los condados Whitfield y Murray, incluidos ciudadanos que regresan que establecen hogares médicos después de la liberación. Voluntarios y personal tratan hipertensión, diabetes y EPOC en la clínica del Mack Gaston Community Center en Dalton.",
        address="Mack Gaston Community Center",
        city="Dalton",
        phone="706-581-2009",
        email="officedeoclinic@gmail.com",
        website="https://www.deoclinic.org",
        eligibility="Low-income uninsured residents of Whitfield or Murray County; justice-involved adults accepted.",
        eligibility_es="Residentes sin seguro de bajos ingresos de Whitfield o Murray; adultos con antecedentes penales aceptados.",
        notes="Call 706-581-2009 for appointment; chronic disease management and prescription assistance available.",
        notes_es="Llame al 706-581-2009 para cita; manejo de enfermedades crónicas y asistencia con recetas disponibles.",
        hours="Clinic hours vary; call for schedule",
        tags="dalton|whitfield|murray|healthcare|uninsured|reentry",
        services="Primary care|Chronic disease management|Prescription assistance|Follow-up visits|Uninsured clinic services",
        county="Whitfield",
        served_counties="Whitfield|Murray",
        coverage="multi",
        _source="https://www.deoclinic.org/about-us",
        _source_type="nonprofit",
        _confidence="high",
    )
    add(
        name="United Way of Northwest Georgia",
        category="basic-needs",
        region="Dalton / Northwest Georgia",
        description="United Way of Northwest Georgia invests in education, basic needs, and health programs across Whitfield and Murray counties connecting low-income families—including returning citizens—to funded partners for food, housing stability, utility assistance, and financial counseling. The Dalton-based team coordinates 211 referrals, volunteer projects, and community action initiatives. A funding and navigation hub—not direct emergency shelter.",
        description_es="United Way of Northwest Georgia invierte en programas de educación, necesidades básicas y salud en los condados Whitfield y Murray conectando a familias de bajos ingresos—incluidos ciudadanos que regresan—a aliados financiados para alimentos, estabilidad de vivienda, servicios públicos y consejería financiera. Equipo con sede en Dalton coordina referencias 211 e iniciativas comunitarias.",
        address="PO Box 566",
        city="Dalton",
        phone="706-529-1591",
        email="",
        website="https://www.ourunitedway.org",
        eligibility="Residents of Whitfield and Murray counties seeking referrals to funded partner programs; open to justice-involved households.",
        eligibility_es="Residentes de Whitfield y Murray que buscan referencias a programas aliados financiados; abierto a hogares con antecedentes penales.",
        notes="Call 706-529-1591 or visit ourunitedway.org; partners include food, housing, and health agencies in Dalton area.",
        notes_es="Llame al 706-529-1591 o visite ourunitedway.org; aliados incluyen agencias de alimentos, vivienda y salud.",
        hours="Monday–Friday business hours",
        tags="dalton|whitfield|murray|basic-needs|united-way|reentry",
        services="Community funding|Partner referrals|Basic needs navigation|Housing stability programs|Financial counseling partners",
        county="Whitfield",
        served_counties="Whitfield|Murray",
        coverage="multi",
        _source="https://www.ourunitedway.org/our-impact",
        _source_type="nonprofit",
        _confidence="high",
    )
    add(
        name="Community Action for Improvement (CAFI)",
        category="reentry-organizations",
        region="LaGrange / West Georgia",
        description="Community Action for Improvement is the community action agency for Carroll, Coweta, Heard, Meriwether, and Troup counties providing LIHEAP utility assistance, homeless prevention, employment readiness, veterans services, and reentry supports for low-income residents including returning citizens rebuilding stability. Service connection centers in LaGrange and county sites help clients access SNAP verification partners, housing resources, and WorkSource LaGrange career services. Appointment required for most financial assistance—not emergency shelter.",
        description_es="Community Action for Improvement es la agencia de acción comunitaria para los condados Carroll, Coweta, Heard, Meriwether y Troup que ofrece asistencia LIHEAP, prevención de personas sin hogar, preparación laboral, servicios para veteranos y apoyos de reinserción para residentes de bajos ingresos, incluidos ciudadanos que regresan. Centros de conexión de servicios en LaGrange ayudan a acceder a recursos de vivienda y WorkSource LaGrange.",
        address="1380 Lafayette Parkway",
        city="LaGrange",
        phone="706-884-2651",
        email="",
        website="https://www.cafi-ga.org",
        eligibility="Low-income residents of Carroll, Coweta, Heard, Meriwether, or Troup counties; justice-involved adults eligible for reentry and housing prevention programs.",
        eligibility_es="Residentes de bajos ingresos de Carroll, Coweta, Heard, Meriwether o Troup; adultos con antecedentes penales elegibles para programas de reinserción.",
        notes="Schedule appointments at cafi-ga.org; reentry and homeless prevention services available—call 706-884-2651.",
        notes_es="Programe citas en cafi-ga.org; servicios de reinserción y prevención de personas sin hogar disponibles.",
        hours="Monday–Friday business hours; program hours vary",
        tags="lagrange|meriwether|troup|reentry|community-action|basic-needs",
        services="Reentry supports|Homeless prevention|LIHEAP utility assistance|Employment readiness|Veterans services|Service navigation",
        county="Troup",
        served_counties="Carroll|Coweta|Heard|Meriwether|Troup",
        coverage="multi",
        _source="https://www.cafi-ga.org/who-we-are/",
        _source_type="nonprofit",
        _confidence="high",
    )
    add(
        name="Christ Chapel Community Church — Food Pantry",
        category="food-nutrition",
        region="Zebulon / Pike County",
        description="Christ Chapel Community Church operates a food pantry in Zebulon serving low-income Pike County residents including returning citizens reestablishing food security after incarceration. The pantry provides groceries and referral connections to Griffin WorkSource and Pike County DFCS benefits offices. Call ahead for pantry hours and documentation requirements—not a hot meal shelter.",
        description_es="Christ Chapel Community Church opera una despensa de alimentos en Zebulon que sirve a residentes de bajos ingresos del condado Pike, incluidos ciudadanos que regresan que restablecen seguridad alimentaria después de la encarcelación. La despensa proporciona comestibles y conexiones de referencia a WorkSource Griffin y oficinas DFCS del condado.",
        address="115 Sullivan Road",
        city="Zebulon",
        phone="770-567-1141",
        email="",
        website="",
        eligibility="Low-income Pike County residents; contact pantry for intake requirements.",
        eligibility_es="Residentes de bajos ingresos del condado Pike; contacte la despensa para requisitos de admisión.",
        notes="Pantry hours Tue–Fri 9:00 a.m.–5:00 p.m.; call 770-567-1141 before visiting.",
        notes_es="Horario de despensa mar–vie 9:00 a.m.–5:00 p.m.; llame al 770-567-1141 antes de visitar.",
        hours="Tuesday–Friday 9:00 a.m.–5:00 p.m.",
        tags="pike|zebulon|food-pantry|food-nutrition|reentry",
        services="Food pantry|Grocery assistance|Community referrals|SNAP partner navigation",
        county="Pike",
        served_counties="Pike",
        coverage="single",
        _source="https://networks.whyhunger.org/organisation/33164",
        _source_type="nonprofit",
        _confidence="high",
    )
    add(
        name="GNTC — Whitfield County Adult Education",
        category="education",
        region="Dalton / Whitfield County",
        description="Georgia Northwestern Technical College operates the Whitfield County Adult Learning Center in Dalton providing free GED and HiSET preparation, adult literacy, and workforce transition classes for Whitfield County residents including returning citizens rebuilding credentials after release. Instructors connect graduates to WorkSource Dalton, The DEO Clinic health partners, and technical college certificate programs. Contact the center for enrollment—not walk-in testing without orientation.",
        description_es="Georgia Northwestern Technical College opera el Centro de Aprendizaje para Adultos del condado Whitfield en Dalton con preparación GED y HiSET gratuita, alfabetización para adultos y clases de transición laboral para residentes del condado Whitfield, incluidos ciudadanos que regresan. Los instructores conectan graduados a WorkSource Dalton y programas de certificado.",
        address="2310 Maddox Chapel Road",
        city="Dalton",
        phone="706-272-2909",
        email="",
        website="https://www.gntc.edu/adult-education/",
        eligibility="Adults age 16+ in Whitfield County; justice-involved adults welcome.",
        eligibility_es="Adultos de 16 años o más en el condado Whitfield; adultos con antecedentes penales bienvenidos.",
        notes="Call 706-272-2909 for enrollment; free TCSG-funded adult education classes.",
        notes_es="Llame al 706-272-2909 para inscripción; clases gratuitas financiadas por TCSG.",
        hours="Contact for class schedule",
        tags="whitfield|dalton|education|GED|GNTC|reentry",
        services="GED preparation|HiSET preparation|Adult literacy|Workforce transition|Technical college referrals",
        county="Whitfield",
        served_counties="Whitfield",
        coverage="single",
        _source="https://www.gntc.edu/adult-education/class/",
        _source_type="government",
        _confidence="high",
    )
    add(
        name="Southern Crescent Technical College — Griffin Adult Education",
        category="education",
        region="Griffin / Pike County",
        description="Southern Crescent Technical College provides free GED and HiSET preparation and adult education classes at its Griffin campus for Pike, Spalding, Lamar, and Upson county residents including returning citizens seeking high school equivalency credentials for Griffin WorkSource employment programs. Instructors help participants pass equivalency exams and transition to workforce certificates. Enrollment required before classes begin.",
        description_es="Southern Crescent Technical College ofrece preparación GED y HiSET gratuita y clases de educación para adultos en su campus de Griffin para residentes de los condados Pike, Spalding, Lamar y Upson, incluidos ciudadanos que regresan que buscan credenciales de equivalencia de secundaria para programas de empleo WorkSource Griffin.",
        address="501 Varsity Road",
        city="Griffin",
        phone="770-229-3176",
        email="",
        website="https://www.sctech.edu/adult-education",
        eligibility="Adults age 16+ in service area counties; open to justice-involved participants.",
        eligibility_es="Adultos de 16 años o más en condados del área de servicio; abierto a participantes con antecedentes penales.",
        notes="Call 770-229-3176 for Griffin adult education enrollment; connects to WorkSource Griffin career center.",
        notes_es="Llame al 770-229-3176 para inscripción en educación para adultos en Griffin; conecta con WorkSource Griffin.",
        hours="Contact for class schedule",
        tags="griffin|pike|spalding|education|GED|SCTC|reentry",
        services="GED preparation|HiSET preparation|Adult literacy|Workforce certificates|Career center referrals",
        county="Spalding",
        served_counties="Pike|Spalding|Lamar|Upson",
        coverage="multi",
        _source="https://www.sctech.edu/adult-education",
        _source_type="government",
        _confidence="high",
    )
