"""Illinois reentry resource expansion entries."""


def register_phase4(add):
    add(
        name='Safer Foundation — Chicago Reentry Employment',
        category='employment',
        region='Chicago / Cook County',
        description='Safer Foundation is Illinois\'s largest reentry employment organization providing job readiness training, transitional jobs, case management, and fair-chance employer partnerships for justice-involved adults returning to Cook County communities after incarceration. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='Safer Foundation — Chicago Reentry Employment sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. Safer Foundation is Illinois\'s largest reentry employment organization providing job readiness training, transitional jobs, case management, and fair-chance employer partnerships for justice-involved adults returning to Cook County communities after incarceration. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='571 W. Jackson Boulevard',
        city='Chicago',
        phone='312-922-2200',
        email='',
        website='https://www.saferfoundation.org',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 312-922-2200 or visit https://www.saferfoundation.org to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 312-922-2200 o visite https://www.saferfoundation.org para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|cook',
        services='',
        county='Cook',
        served_counties='Cook',
        coverage='single',
        _source='https://www.saferfoundation.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Heartland Alliance — Reentry Services',
        category='housing',
        region='Chicago / Cook County',
        description='Heartland Alliance provides housing, employment, health, and legal support for people experiencing poverty and homelessness including returning citizens in Chicago seeking stable housing and wraparound reentry services. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='Heartland Alliance — Reentry Services sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. Heartland Alliance provides housing, employment, health, and legal support for people experiencing poverty and homelessness including returning citizens in Chicago seeking stable housing and wraparound reentry services. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='208 S. LaSalle Street',
        city='Chicago',
        phone='312-660-1300',
        email='',
        website='https://www.heartlandalliance.org',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 312-660-1300 or visit https://www.heartlandalliance.org to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 312-660-1300 o visite https://www.heartlandalliance.org para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|cook',
        services='',
        county='Cook',
        served_counties='Cook',
        coverage='single',
        _source='https://www.heartlandalliance.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Thresholds — Justice Program',
        category='healthcare',
        region='Chicago / Cook County',
        description='Thresholds Justice Program provides intensive case management, mental health treatment, and housing navigation for adults with mental health conditions leaving incarceration in Cook County including connections to Medicaid and community providers. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='Thresholds — Justice Program sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. Thresholds Justice Program provides intensive case management, mental health treatment, and housing navigation for adults with mental health conditions leaving incarceration in Cook County including connections to Medicaid and community providers. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='4101 N. Ravenswood Avenue',
        city='Chicago',
        phone='773-572-5500',
        email='',
        website='https://www.thresholds.org',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 773-572-5500 or visit https://www.thresholds.org to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 773-572-5500 o visite https://www.thresholds.org para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|cook',
        services='',
        county='Cook',
        served_counties='Cook',
        coverage='single',
        _source='https://www.thresholds.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Legal Aid Chicago',
        category='legal-aid',
        region='Chicago / Cook County',
        description='Legal Aid Chicago provides free civil legal services to low-income Cook County residents including record sealing, housing defense, public benefits appeals, and family law for justice-involved clients—not criminal defense. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='Legal Aid Chicago sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. Legal Aid Chicago provides free civil legal services to low-income Cook County residents including record sealing, housing defense, public benefits appeals, and family law for justice-involved clients—not criminal defense. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='120 S. LaSalle Street',
        city='Chicago',
        phone='312-341-1070',
        email='',
        website='https://www.legalaidchicago.org',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 312-341-1070 or visit https://www.legalaidchicago.org to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 312-341-1070 o visite https://www.legalaidchicago.org para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|cook',
        services='',
        county='Cook',
        served_counties='Cook',
        coverage='single',
        _source='https://www.legalaidchicago.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='CARPLS — Coordinated Advice & Referral Program',
        category='legal-aid',
        region='Cook County',
        description='CARPLS is the largest legal aid hotline in Illinois providing free telephone advice and referrals for civil legal problems including eviction, benefits denials, and record relief for low-income Cook County residents including returning citizens. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='CARPLS — Coordinated Advice & Referral Program sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. CARPLS is the largest legal aid hotline in Illinois providing free telephone advice and referrals for civil legal problems including eviction, benefits denials, and record relief for low-income Cook County residents including returning citizens. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='120 S. LaSalle Street',
        city='Chicago',
        phone='312-738-9200',
        email='',
        website='https://www.carpls.org',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 312-738-9200 or visit https://www.carpls.org to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 312-738-9200 o visite https://www.carpls.org para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|cook',
        services='',
        county='Cook',
        served_counties='Cook',
        coverage='single',
        _source='https://www.carpls.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='InnerVoice — Supportive Housing',
        category='housing',
        region='Chicago / Cook County',
        description='InnerVoice provides supportive housing, case management, and employment services for homeless adults including justice-involved individuals in Chicago seeking permanent housing with on-site or scattered-site supportive services. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='InnerVoice — Supportive Housing sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. InnerVoice provides supportive housing, case management, and employment services for homeless adults including justice-involved individuals in Chicago seeking permanent housing with on-site or scattered-site supportive services. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='1640 W. 18th Street',
        city='Chicago',
        phone='773-638-7360',
        email='',
        website='https://www.innervoice.org',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 773-638-7360 or visit https://www.innervoice.org to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 773-638-7360 o visite https://www.innervoice.org para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|cook',
        services='',
        county='Cook',
        served_counties='Cook',
        coverage='single',
        _source='https://www.innervoice.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='TASC — Treatment Alternatives for Safe Communities',
        category='substance-use-treatment',
        region='Chicago / Cook County',
        description='TASC connects justice-involved individuals to community-based substance use treatment, recovery supports, and case management as an alternative to incarceration in Cook County courts and corrections partnerships statewide. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='TASC — Treatment Alternatives for Safe Communities sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. TASC connects justice-involved individuals to community-based substance use treatment, recovery supports, and case management as an alternative to incarceration in Cook County courts and corrections partnerships statewide. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='1500 N. Halsted Street',
        city='Chicago',
        phone='312-226-7980',
        email='',
        website='https://www.tasc.org',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 312-226-7980 or visit https://www.tasc.org to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 312-226-7980 o visite https://www.tasc.org para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|cook',
        services='',
        county='Cook',
        served_counties='Cook',
        coverage='single',
        _source='https://www.tasc.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Howard Brown Health — Reentry Health Services',
        category='healthcare',
        region='Chicago / Cook County',
        description='Howard Brown Health provides primary care, behavioral health, and HIV services on a sliding fee scale for LGBTQ+ and general populations including justice-involved adults reestablishing medical care after release in Chicago. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='Howard Brown Health — Reentry Health Services sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. Howard Brown Health provides primary care, behavioral health, and HIV services on a sliding fee scale for LGBTQ+ and general populations including justice-involved adults reestablishing medical care after release in Chicago. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='4025 N. Sheridan Road',
        city='Chicago',
        phone='773-388-1600',
        email='',
        website='https://howardbrown.org',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 773-388-1600 or visit https://howardbrown.org to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 773-388-1600 o visite https://howardbrown.org para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|cook',
        services='',
        county='Cook',
        served_counties='Cook',
        coverage='single',
        _source='https://howardbrown.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='PCC Community Wellness Center',
        category='healthcare',
        region='Chicago / Cook County',
        description='PCC Community Wellness Center is a federally qualified health center providing primary care, behavioral health, dental, and Medicaid enrollment on a sliding fee scale for uninsured and low-income patients including reentry populations in Chicago. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='PCC Community Wellness Center sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. PCC Community Wellness Center is a federally qualified health center providing primary care, behavioral health, dental, and Medicaid enrollment on a sliding fee scale for uninsured and low-income patients including reentry populations in Chicago. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='1157 S. Western Avenue',
        city='Chicago',
        phone='773-884-7722',
        email='',
        website='https://www.pccwellness.org',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 773-884-7722 or visit https://www.pccwellness.org to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 773-884-7722 o visite https://www.pccwellness.org para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|cook',
        services='',
        county='Cook',
        served_counties='Cook',
        coverage='single',
        _source='https://www.pccwellness.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Chicago Coalition for the Homeless',
        category='housing',
        region='Chicago / Cook County',
        description='Chicago Coalition for the Homeless advocates and connects unhoused Chicagoans including returning citizens to shelter, housing resources, and legal protections through outreach, hotline, and partner referrals—not direct shelter beds. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='Chicago Coalition for the Homeless sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. Chicago Coalition for the Homeless advocates and connects unhoused Chicagoans including returning citizens to shelter, housing resources, and legal protections through outreach, hotline, and partner referrals—not direct shelter beds. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='17 N. State Street',
        city='Chicago',
        phone='312-641-4140',
        email='',
        website='https://www.chicagohomeless.org',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 312-641-4140 or visit https://www.chicagohomeless.org to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 312-641-4140 o visite https://www.chicagohomeless.org para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|cook',
        services='',
        county='Cook',
        served_counties='Cook',
        coverage='single',
        _source='https://www.chicagohomeless.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Salvation Army Harbor Light — Chicago',
        category='housing',
        region='Chicago / Cook County',
        description='Salvation Army Harbor Light provides emergency shelter, addiction recovery, and transitional programming for men experiencing homelessness including justice-involved men seeking stable housing and treatment in Chicago. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='Salvation Army Harbor Light — Chicago sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. Salvation Army Harbor Light provides emergency shelter, addiction recovery, and transitional programming for men experiencing homelessness including justice-involved men seeking stable housing and treatment in Chicago. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='1515 W. Monroe Street',
        city='Chicago',
        phone='312-667-2200',
        email='',
        website='https://www.salarmychicago.org',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 312-667-2200 or visit https://www.salarmychicago.org to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 312-667-2200 o visite https://www.salarmychicago.org para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|cook',
        services='',
        county='Cook',
        served_counties='Cook',
        coverage='single',
        _source='https://www.salarmychicago.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='St. Leonard\'s Ministries — Reentry Housing',
        category='housing',
        region='Chicago / Cook County',
        description='St. Leonard\'s Ministries provides transitional housing, workforce development, and supportive services for men and women returning from incarceration in Chicago including case management and employment training at multiple West Side campuses. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='St. Leonard\'s Ministries — Reentry Housing sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. St. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='2100 W. Warren Boulevard',
        city='Chicago',
        phone='773-376-6460',
        email='',
        website='https://www.stleonardsministries.org',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 773-376-6460 or visit https://www.stleonardsministries.org to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 773-376-6460 o visite https://www.stleonardsministries.org para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|cook',
        services='',
        county='Cook',
        served_counties='Cook',
        coverage='single',
        _source='https://www.stleonardsministries.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='A Safe Haven Foundation — Reentry Housing',
        category='housing',
        region='Chicago / Cook County',
        description='A Safe Haven Foundation provides emergency shelter, transitional housing, workforce training, and case management for individuals experiencing homelessness including returning citizens in Chicago rebuilding stability after incarceration. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='A Safe Haven Foundation — Reentry Housing sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. A Safe Haven Foundation provides emergency shelter, transitional housing, workforce training, and case management for individuals experiencing homelessness including returning citizens in Chicago rebuilding stability after incarceration. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='2750 W. Roosevelt Road',
        city='Chicago',
        phone='773-435-8300',
        email='',
        website='https://www.asafehaven.org',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 773-435-8300 or visit https://www.asafehaven.org to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 773-435-8300 o visite https://www.asafehaven.org para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|cook',
        services='',
        county='Cook',
        served_counties='Cook',
        coverage='single',
        _source='https://www.asafehaven.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Prairie State Legal Services — Northern Illinois',
        category='legal-aid',
        region='Northern Illinois',
        description='Prairie State Legal Services provides free civil legal aid to low-income residents across northern and west-central Illinois including housing, benefits, family law, and record relief for justice-involved clients in 36 counties. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='Prairie State Legal Services — Northern Illinois sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. Prairie State Legal Services provides free civil legal aid to low-income residents across northern and west-central Illinois including housing, benefits, family law, and record relief for justice-involved clients in 36 counties. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='303 N. Main Street',
        city='Rockford',
        phone='800-531-7058',
        email='',
        website='https://www.pslegal.org',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 800-531-7058 or visit https://www.pslegal.org to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 800-531-7058 o visite https://www.pslegal.org para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|winnebago',
        services='',
        county='Winnebago',
        served_counties='Boone|Bureau|Carroll|DeKalb|DuPage|Fulton|Grundy|Henderson|Henry|Iroquois|Jo Daviess|Kane|Kankakee|Kendall|Knox|Lake|LaSalle|Lee|Livingston|Marshall|McDonough|McHenry|McLean|Mercer|Ogle|Peoria|Putnam|Rock Island|Stark|Stephenson|Tazewell|Warren|Whiteside|Will|Winnebago|Woodford',
        coverage='multi',
        _source='https://www.pslegal.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Land of Lincoln Legal Assistance',
        category='legal-aid',
        region='Central & Southern Illinois',
        description='Land of Lincoln Legal Assistance provides free civil legal services to low-income residents across 65 central and southern Illinois counties including expungement, housing, benefits, and family law for justice-involved clients. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='Land of Lincoln Legal Assistance sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. Land of Lincoln Legal Assistance provides free civil legal services to low-income residents across 65 central and southern Illinois counties including expungement, housing, benefits, and family law for justice-involved clients. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='300 N. 8th Street',
        city='Springfield',
        phone='800-642-5942',
        email='',
        website='https://www.lincolnlegal.org',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 800-642-5942 or visit https://www.lincolnlegal.org to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 800-642-5942 o visite https://www.lincolnlegal.org para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|sangamon',
        services='',
        county='Sangamon',
        served_counties='Adams|Alexander|Bond|Brown|Calhoun|Cass|Christian|Clay|Clinton|Coles|Crawford|Cumberland|DeWitt|Douglas|Edgar|Edwards|Effingham|Fayette|Franklin|Gallatin|Greene|Hamilton|Hancock|Hardin|Jackson|Jasper|Jefferson|Jersey|Johnson|Knox|Lawrence|Logan|Macon|Macoupin|Madison|Marion|Massac|Mason|Menard|Montgomery|Morgan|Moultrie|Perry|Pike|Piatt|Pope|Pulaski|Randolph|Richland|Saline|Sangamon|Scott|Shelby|St. Clair|Union|Vermilion|Washington|Wabash|Wayne|White|Williamson',
        coverage='multi',
        _source='https://www.lincolnlegal.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Prairie Center Health Systems — SUD Treatment',
        category='substance-use-treatment',
        region='Champaign / Champaign County',
        description='Prairie Center Health Systems provides outpatient and residential substance use disorder treatment, MAT, and recovery supports for justice-involved individuals referred by courts and corrections in east-central Illinois. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='Prairie Center Health Systems — SUD Treatment sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. Prairie Center Health Systems provides outpatient and residential substance use disorder treatment, MAT, and recovery supports for justice-involved individuals referred by courts and corrections in east-central Illinois. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='122 W. Hill Street',
        city='Champaign',
        phone='217-328-3300',
        email='',
        website='https://www.prairiecenter.org',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 217-328-3300 or visit https://www.prairiecenter.org to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 217-328-3300 o visite https://www.prairiecenter.org para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|champaign',
        services='',
        county='Champaign',
        served_counties='Champaign|Ford|Iroquois|Piatt|Vermilion',
        coverage='multi',
        _source='https://www.prairiecenter.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Rosecrance — SUD Treatment',
        category='substance-use-treatment',
        region='Rockford / Winnebago County',
        description='Rosecrance provides outpatient and residential substance use disorder treatment including MAT and recovery residences for adults including justice-involved clients in northern Illinois with intake assessment required. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='Rosecrance — SUD Treatment sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. Rosecrance provides outpatient and residential substance use disorder treatment including MAT and recovery residences for adults including justice-involved clients in northern Illinois with intake assessment required. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='4201 N. Mulford Road',
        city='Rockford',
        phone='888-928-5278',
        email='',
        website='https://www.rosecrance.org',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 888-928-5278 or visit https://www.rosecrance.org to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 888-928-5278 o visite https://www.rosecrance.org para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|winnebago',
        services='',
        county='Winnebago',
        served_counties='Boone|Ogle|Stephenson|Winnebago',
        coverage='multi',
        _source='https://www.rosecrance.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Center for Youth and Family Solutions — Reentry',
        category='family-children',
        region='Springfield / Sangamon County',
        description='Center for Youth and Family Solutions provides family reunification, counseling, and case management for families affected by incarceration in central Illinois including parenting support and referrals to housing and employment partners. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='Center for Youth and Family Solutions — Reentry sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. Center for Youth and Family Solutions provides family reunification, counseling, and case management for families affected by incarceration in central Illinois including parenting support and referrals to housing and employment partners. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='2610 N. Walnut Street',
        city='Springfield',
        phone='217-528-8400',
        email='',
        website='https://www.cyfsolutions.org',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 217-528-8400 or visit https://www.cyfsolutions.org to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 217-528-8400 o visite https://www.cyfsolutions.org para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|sangamon',
        services='',
        county='Sangamon',
        served_counties='Christian|Logan|Macon|Menard|Morgan|Sangamon',
        coverage='multi',
        _source='https://www.cyfsolutions.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Goodwill of Central Illinois — Reentry Employment',
        category='employment',
        region='Peoria / Peoria County',
        description='Goodwill of Central Illinois provides job training, career coaching, and fair-chance employment services for justice-involved job seekers in the Peoria region through American Job Center partnerships and employer connections. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='Goodwill of Central Illinois — Reentry Employment sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. Goodwill of Central Illinois provides job training, career coaching, and fair-chance employment services for justice-involved job seekers in the Peoria region through American Job Center partnerships and employer connections. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='2319 E. War Memorial Drive',
        city='Peoria',
        phone='309-682-1113',
        email='',
        website='https://www.goodwillpeo.org',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 309-682-1113 or visit https://www.goodwillpeo.org to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 309-682-1113 o visite https://www.goodwillpeo.org para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|peoria',
        services='',
        county='Peoria',
        served_counties='Fulton|Marshall|Peoria|Putnam|Stark|Tazewell|Woodford',
        coverage='multi',
        _source='https://www.goodwillpeo.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Peoria Friendship House — Reentry Support',
        category='basic-needs',
        region='Peoria / Peoria County',
        description='Peoria Friendship House provides clothing, hygiene items, food pantry access, and case management referrals for low-income Peoria residents including returning citizens rebuilding basic needs after incarceration. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='Peoria Friendship House — Reentry Support sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. Peoria Friendship House provides clothing, hygiene items, food pantry access, and case management referrals for low-income Peoria residents including returning citizens rebuilding basic needs after incarceration. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='800 NE Madison Avenue',
        city='Peoria',
        phone='309-671-5200',
        email='',
        website='https://www.peoriafriendshiphouse.org',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 309-671-5200 or visit https://www.peoriafriendshiphouse.org to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 309-671-5200 o visite https://www.peoriafriendshiphouse.org para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|peoria',
        services='',
        county='Peoria',
        served_counties='Peoria',
        coverage='single',
        _source='https://www.peoriafriendshiphouse.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Western Illinois Regional Council — Community Action',
        category='basic-needs',
        region='Macomb / McDonough County',
        description='Western Illinois Regional Council Community Action Agency provides emergency assistance, utility help, weatherization, and case management for low-income residents in western Illinois including returning citizens in rural counties. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='Western Illinois Regional Council — Community Action sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. Western Illinois Regional Council Community Action Agency provides emergency assistance, utility help, weatherization, and case management for low-income residents in western Illinois including returning citizens in rural counties. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='223 S. Randolph Street',
        city='Macomb',
        phone='309-837-2997',
        email='',
        website='https://www.wircc.net',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 309-837-2997 or visit https://www.wircc.net to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 309-837-2997 o visite https://www.wircc.net para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|mcdonough',
        services='',
        county='McDonough',
        served_counties='Fulton|Hancock|McDonough|Schuyler',
        coverage='multi',
        _source='https://www.wircc.net', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='East Central Illinois Community Action',
        category='basic-needs',
        region='Charleston / Coles County',
        description='East Central Illinois Community Action Agency provides emergency financial assistance, utility aid, and case management for low-income residents including justice-involved individuals in east-central Illinois rural communities. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='East Central Illinois Community Action sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. East Central Illinois Community Action Agency provides emergency financial assistance, utility aid, and case management for low-income residents including justice-involved individuals in east-central Illinois rural communities. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='1805 E. Main Street',
        city='Charleston',
        phone='217-345-6481',
        email='',
        website='https://www.ecicaaa.org',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 217-345-6481 or visit https://www.ecicaaa.org to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 217-345-6481 o visite https://www.ecicaaa.org para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|coles',
        services='',
        county='Coles',
        served_counties='Clark|Coles|Cumberland|Edgar|Moultrie|Shelby',
        coverage='multi',
        _source='https://www.ecicaaa.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Southern Illinois Community Action',
        category='basic-needs',
        region='Marion / Williamson County',
        description='Southern Illinois Community Action Agency provides emergency assistance, weatherization, and case management for low-income southern Illinois residents including returning citizens rebuilding after incarceration in rural counties. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='Southern Illinois Community Action sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. Southern Illinois Community Action Agency provides emergency assistance, weatherization, and case management for low-income southern Illinois residents including returning citizens rebuilding after incarceration in rural counties. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='1100 N. Carbon Street',
        city='Marion',
        phone='618-997-5567',
        email='',
        website='https://www.sicacaa.org',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 618-997-5567 or visit https://www.sicacaa.org to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 618-997-5567 o visite https://www.sicacaa.org para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|williamson',
        services='',
        county='Williamson',
        served_counties='Franklin|Jackson|Jefferson|Johnson|Perry|Randolph|Saline|Union|Williamson',
        coverage='multi',
        _source='https://www.sicacaa.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Illinois Valley Community College — Adult Education',
        category='education',
        region='Oglesby / LaSalle County',
        description='Illinois Valley Community College Adult Education provides GED, high school equivalency, and English language classes for adults including justice-involved learners in the Illinois Valley region with free or low-cost enrollment. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='Illinois Valley Community College — Adult Education sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. Illinois Valley Community College Adult Education provides GED, high school equivalency, and English language classes for adults including justice-involved learners in the Illinois Valley region with free or low-cost enrollment. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='815 N. Orlando Smith Road',
        city='Oglesby',
        phone='815-224-0427',
        email='',
        website='https://www.ivcc.edu/adulted',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 815-224-0427 or visit https://www.ivcc.edu/adulted to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 815-224-0427 o visite https://www.ivcc.edu/adulted para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|lasalle',
        services='',
        county='LaSalle',
        served_counties='Bureau|LaSalle|Lee|Livingston|Ogle|Putnam',
        coverage='multi',
        _source='https://www.ivcc.edu/adulted', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Parkland College — Adult Education & GED',
        category='education',
        region='Champaign / Champaign County',
        description='Parkland College Adult Education offers GED preparation, high school equivalency, and career training pathways for adult learners including returning citizens in the Champaign-Urbana region with orientation required before enrollment. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='Parkland College — Adult Education & GED sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. Parkland College Adult Education offers GED preparation, high school equivalency, and career training pathways for adult learners including returning citizens in the Champaign-Urbana region with orientation required before enrollment. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='2400 W. Bradley Avenue',
        city='Champaign',
        phone='217-353-2051',
        email='',
        website='https://www.parkland.edu/adulted',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 217-353-2051 or visit https://www.parkland.edu/adulted to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 217-353-2051 o visite https://www.parkland.edu/adulted para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|champaign',
        services='',
        county='Champaign',
        served_counties='Champaign|Ford|Iroquois|Piatt|Vermilion',
        coverage='multi',
        _source='https://www.parkland.edu/adulted', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Illinois Department of Transportation — Secretary of State ID Services',
        category='id-documentation',
        region='Statewide',
        description='Illinois Secretary of State provides state ID cards, driver\'s licenses, and credential reinstatement at branch offices statewide. Reentry partners help returning citizens gather proof of identity and residency documents required after incarceration. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='Illinois Department of Transportation — Secretary of State ID Services sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. Illinois Secretary of State provides state ID cards, driver\'s licenses, and credential reinstatement at branch offices statewide. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='',
        city='Springfield',
        phone='888-SOS-ILLINO',
        email='',
        website='https://www.ilsos.gov',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 888-SOS-ILLINO or visit https://www.ilsos.gov to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 888-SOS-ILLINO o visite https://www.ilsos.gov para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|sangamon',
        services='',
        county='Sangamon',
        served_counties='',
        coverage='statewide',
        _source='https://www.ilsos.gov', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Illinois Department of Veterans Affairs — County VSO Network',
        category='veterans',
        region='Statewide',
        description='Illinois Department of Veterans Affairs connects veterans and families to federal VA benefits, state veteran programs, and county Veterans Service Officers statewide including justice-involved veterans navigating discharge upgrades and healthcare enrollment. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='Illinois Department of Veterans Affairs — County VSO Network sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. Illinois Department of Veterans Affairs connects veterans and families to federal VA benefits, state veteran programs, and county Veterans Service Officers statewide including justice-involved veterans navigating discharge upgrades and healthcare enrollment. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='833 S. Spring Street',
        city='Springfield',
        phone='800-437-9824',
        email='',
        website='https://www.illinois.gov/veterans',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 800-437-9824 or visit https://www.illinois.gov/veterans to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 800-437-9824 o visite https://www.illinois.gov/veterans para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|sangamon',
        services='',
        county='Sangamon',
        served_counties='',
        coverage='statewide',
        _source='https://www.illinois.gov/veterans', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Chicago Transit Authority — Reduced Fare Program',
        category='transportation',
        region='Chicago / Cook County',
        description='Chicago Transit Authority Reduced Fare and Ride Free programs provide discounted bus and train passes for seniors, people with disabilities, and low-income residents including returning citizens who need affordable transportation to work and appointments. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='Chicago Transit Authority — Reduced Fare Program sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. Chicago Transit Authority Reduced Fare and Ride Free programs provide discounted bus and train passes for seniors, people with disabilities, and low-income residents including returning citizens who need affordable transportation to work and appointments. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='567 W. Lake Street',
        city='Chicago',
        phone='888-YOUR-CTA',
        email='',
        website='https://www.transitchicago.com',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 888-YOUR-CTA or visit https://www.transitchicago.com to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 888-YOUR-CTA o visite https://www.transitchicago.com para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|cook',
        services='',
        county='Cook',
        served_counties='Cook',
        coverage='single',
        _source='https://www.transitchicago.com', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Metra — Reduced Fare Program',
        category='transportation',
        region='Chicago Metro',
        description='Metra provides commuter rail service across the Chicago metropolitan area with reduced fare options for seniors, people with disabilities, and eligible low-income riders including returning citizens commuting to employment in collar counties. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='Metra — Reduced Fare Program sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. Metra provides commuter rail service across the Chicago metropolitan area with reduced fare options for seniors, people with disabilities, and eligible low-income riders including returning citizens commuting to employment in collar counties. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='547 W. Jackson Boulevard',
        city='Chicago',
        phone='312-322-6777',
        email='',
        website='https://www.metra.com',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 312-322-6777 or visit https://www.metra.com to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 312-322-6777 o visite https://www.metra.com para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|cook',
        services='',
        county='Cook',
        served_counties='Cook|DuPage|Kane|Lake|McHenry|Will',
        coverage='multi',
        _source='https://www.metra.com', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Illinois Certification Board — Peer Recovery Support',
        category='peer-support',
        region='Statewide',
        description='Illinois Certification Board certifies peer recovery support specialists and maintains a roster of certified peers who provide mentoring and recovery coaching for justice-involved individuals in treatment and reentry programs statewide. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='Illinois Certification Board — Peer Recovery Support sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. Illinois Certification Board certifies peer recovery support specialists and maintains a roster of certified peers who provide mentoring and recovery coaching for justice-involved individuals in treatment and reentry programs statewide. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='401 E. Sangamon Avenue',
        city='Springfield',
        phone='217-528-7335',
        email='',
        website='https://www.illinoiscertificationboard.org',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 217-528-7335 or visit https://www.illinoiscertificationboard.org to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 217-528-7335 o visite https://www.illinoiscertificationboard.org para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|sangamon',
        services='',
        county='Sangamon',
        served_counties='',
        coverage='statewide',
        _source='https://www.illinoiscertificationboard.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Community Mental Health Board of Chicago — Crisis Services',
        category='healthcare',
        region='Chicago / Cook County',
        description='Chicago Department of Public Health Mental Health Division coordinates publicly funded behavioral health services and crisis response for Cook County residents including justice-involved individuals; for immediate crisis call 988. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='Community Mental Health Board of Chicago — Crisis Services sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. Chicago Department of Public Health Mental Health Division coordinates publicly funded behavioral health services and crisis response for Cook County residents including justice-involved individuals; for immediate crisis call 988. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='10 S. LaSalle Street',
        city='Chicago',
        phone='312-747-1020',
        email='',
        website='https://www.chicago.gov/city/en/depts/mhcd.html',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 312-747-1020 or visit https://www.chicago.gov/city/en/depts/mhcd.html to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 312-747-1020 o visite https://www.chicago.gov/city/en/depts/mhcd.html para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|cook',
        services='',
        county='Cook',
        served_counties='Cook',
        coverage='single',
        _source='https://www.chicago.gov/city/en/depts/mhcd.html', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Aunt Martha\'s Health & Wellness',
        category='healthcare',
        region='Chicago Southland',
        description='Aunt Martha\'s is a federally qualified health center providing primary care, behavioral health, dental, and care coordination on a sliding fee scale for uninsured patients including justice-involved youth and adults in Chicago and south suburban Illinois. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='Aunt Martha\'s Health & Wellness sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. Aunt Martha\'s is a federally qualified health center providing primary care, behavioral health, dental, and care coordination on a sliding fee scale for uninsured patients including justice-involved youth and adults in Chicago and south suburban Illinois. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='1777 W. 2nd Street',
        city='Chicago',
        phone='877-692-8686',
        email='',
        website='https://www.auntmarthas.org',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 877-692-8686 or visit https://www.auntmarthas.org to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 877-692-8686 o visite https://www.auntmarthas.org para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|cook',
        services='',
        county='Cook',
        served_counties='Cook|Kankakee|Will',
        coverage='multi',
        _source='https://www.auntmarthas.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Esperanza Health Centers',
        category='healthcare',
        region='Chicago / Cook County',
        description='Esperanza Health Centers provides federally qualified health center services including primary care, behavioral health, and Medicaid enrollment on a sliding fee scale for low-income Chicago residents including returning citizens on the Southwest Side. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='Esperanza Health Centers sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. Esperanza Health Centers provides federally qualified health center services including primary care, behavioral health, and Medicaid enrollment on a sliding fee scale for low-income Chicago residents including returning citizens on the Southwest Side. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='2001 S. California Avenue',
        city='Chicago',
        phone='773-584-6200',
        email='',
        website='https://www.esperanzachicago.org',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 773-584-6200 or visit https://www.esperanzachicago.org to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 773-584-6200 o visite https://www.esperanzachicago.org para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|cook',
        services='',
        county='Cook',
        served_counties='Cook',
        coverage='single',
        _source='https://www.esperanzachicago.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Cook County Health — Reentry Health Linkage',
        category='healthcare',
        region='Chicago / Cook County',
        description='Cook County Health provides hospital, primary care, and specialty services for uninsured and Medicaid patients including justice-involved adults leaving Cook County Jail with discharge planning and community health center referrals. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='Cook County Health — Reentry Health Linkage sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. Cook County Health provides hospital, primary care, and specialty services for uninsured and Medicaid patients including justice-involved adults leaving Cook County Jail with discharge planning and community health center referrals. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='1900 W. Polk Street',
        city='Chicago',
        phone='312-864-6000',
        email='',
        website='https://www.cookcountyhealth.org',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 312-864-6000 or visit https://www.cookcountyhealth.org to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 312-864-6000 o visite https://www.cookcountyhealth.org para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|cook',
        services='',
        county='Cook',
        served_counties='Cook',
        coverage='single',
        _source='https://www.cookcountyhealth.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Illinois Department of Human Services — Division of Substance Use Prevention and Recovery',
        category='substance-use-treatment',
        region='Statewide',
        description='IDHS Division of Substance Use Prevention and Recovery coordinates publicly funded SUD treatment, recovery housing, and MAT access through regional provider networks for Illinois residents including justice-involved individuals after release. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='Illinois Department of Human Services — Division of Substance Use Prevention and Recovery sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. IDHS Division of Substance Use Prevention and Recovery coordinates publicly funded SUD treatment, recovery housing, and MAT access through regional provider networks for Illinois residents including justice-involved individuals after release. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='100 S. Grand Avenue East',
        city='Springfield',
        phone='217-782-3300',
        email='',
        website='https://www.dhs.state.il.us/page.aspx?item=29725',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 217-782-3300 or visit https://www.dhs.state.il.us/page.aspx?item=29725 to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 217-782-3300 o visite https://www.dhs.state.il.us/page.aspx?item=29725 para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|sangamon',
        services='',
        county='Sangamon',
        served_counties='',
        coverage='statewide',
        _source='https://www.dhs.state.il.us/page.aspx?item=29725', _source_type='nonprofit', _confidence='high',
    )
