"""Illinois reentry resource expansion entries."""


def register_pass2(add):
    add(
        name='IDOC — Parole Division Chicago Region',
        category='probation-parole',
        region='Chicago / Cook County',
        description='IDOC Parole Division Chicago Region supervises parolees in the Chicago metropolitan area connecting supervisees to community resources, reporting requirements, and reentry partners—not emergency navigation or crisis response. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='IDOC — Parole Division Chicago Region sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. IDOC Parole Division Chicago Region supervises parolees in the Chicago metropolitan area connecting supervisees to community resources, reporting requirements, and reentry partners—not emergency navigation or crisis response. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='100 W. Randolph Street',
        city='Chicago',
        phone='217-558-2200',
        email='',
        website='https://idoc.illinois.gov',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 217-558-2200 or visit https://idoc.illinois.gov to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 217-558-2200 o visite https://idoc.illinois.gov para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|cook',
        services='',
        county='Cook',
        served_counties='Cook|DuPage|Kane|Lake|McHenry|Will',
        coverage='multi',
        _source='https://idoc.illinois.gov', _source_type='government', _confidence='high',
    )
    add(
        name='IDOC — Parole Division Central Region',
        category='probation-parole',
        region='Springfield / Sangamon County',
        description='IDOC Parole Division Central Region office supervises parolees in central Illinois connecting supervisees to Land of Lincoln reentry partners, IDHS benefits, and Illinois workNet employment services. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='IDOC — Parole Division Central Region sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. IDOC Parole Division Central Region office supervises parolees in central Illinois connecting supervisees to Land of Lincoln reentry partners, IDHS benefits, and Illinois workNet employment services. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='1301 Concordia Court',
        city='Springfield',
        phone='217-558-2200',
        email='',
        website='https://idoc.illinois.gov',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 217-558-2200 or visit https://idoc.illinois.gov to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 217-558-2200 o visite https://idoc.illinois.gov para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|sangamon',
        services='',
        county='Sangamon',
        served_counties='Christian|Logan|Macon|McLean|Menard|Morgan|Sangamon|Vermilion',
        coverage='multi',
        _source='https://idoc.illinois.gov', _source_type='government', _confidence='high',
    )
    add(
        name='IDOC — Parole Division Southern Region',
        category='probation-parole',
        region='Marion / Williamson County',
        description='IDOC Parole Division Southern Region supervises parolees in southern Illinois connecting supervisees to community treatment, housing, and workforce partners in rural counties. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='IDOC — Parole Division Southern Region sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. IDOC Parole Division Southern Region supervises parolees in southern Illinois connecting supervisees to community treatment, housing, and workforce partners in rural counties. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='1700 W. 10th Street',
        city='Marion',
        phone='217-558-2200',
        email='',
        website='https://idoc.illinois.gov',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 217-558-2200 or visit https://idoc.illinois.gov to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 217-558-2200 o visite https://idoc.illinois.gov para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|williamson',
        services='',
        county='Williamson',
        served_counties='Franklin|Jackson|Jefferson|Johnson|Marion|Perry|Randolph|Saline|Union|Williamson',
        coverage='multi',
        _source='https://idoc.illinois.gov', _source_type='government', _confidence='high',
    )
    add(
        name='IDOC — Parole Division Northern Region',
        category='probation-parole',
        region='Rockford / Winnebago County',
        description='IDOC Parole Division Northern Region supervises parolees in northern Illinois outside Cook County connecting supervisees to Prairie State Legal Services and Rock Valley workforce partners. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='IDOC — Parole Division Northern Region sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. IDOC Parole Division Northern Region supervises parolees in northern Illinois outside Cook County connecting supervisees to Prairie State Legal Services and Rock Valley workforce partners. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='303 N. Main Street',
        city='Rockford',
        phone='217-558-2200',
        email='',
        website='https://idoc.illinois.gov',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 217-558-2200 or visit https://idoc.illinois.gov to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 217-558-2200 o visite https://idoc.illinois.gov para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|winnebago',
        services='',
        county='Winnebago',
        served_counties='Boone|DeKalb|Jo Daviess|Lee|Ogle|Stephenson|Whiteside|Winnebago',
        coverage='multi',
        _source='https://idoc.illinois.gov', _source_type='government', _confidence='high',
    )
    add(
        name='IDOC — Stateville Correctional Center Reentry',
        category='state-agency',
        region='Joliet / Will County',
        description='Stateville Correctional Center is a major IDOC facility near Joliet providing in-custody education, programming, and pre-release planning coordination with Will County parole and reentry partners for prisoners releasing to northern Illinois. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='IDOC — Stateville Correctional Center Reentry sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. Stateville Correctional Center is a major IDOC facility near Joliet providing in-custody education, programming, and pre-release planning coordination with Will County parole and reentry partners for prisoners releasing to northern Illinois. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='16830 W. Illinois Route 173',
        city='Crest Hill',
        phone='815-727-3607',
        email='',
        website='https://idoc.illinois.gov',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 815-727-3607 or visit https://idoc.illinois.gov to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 815-727-3607 o visite https://idoc.illinois.gov para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|will',
        services='',
        county='Will',
        served_counties='Will',
        coverage='single',
        _source='https://idoc.illinois.gov', _source_type='government', _confidence='high',
    )
    add(
        name='IDOC — Menard Correctional Center',
        category='state-agency',
        region='Chester / Randolph County',
        description='Menard Correctional Center is a maximum-security IDOC facility providing education and reentry preparation programming with institutional staff coordinating transition to southern Illinois parole offices and community partners. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='IDOC — Menard Correctional Center sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. Menard Correctional Center is a maximum-security IDOC facility providing education and reentry preparation programming with institutional staff coordinating transition to southern Illinois parole offices and community partners. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='711 Kaskaskia Street',
        city='Menard',
        phone='618-826-5071',
        email='',
        website='https://idoc.illinois.gov',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 618-826-5071 or visit https://idoc.illinois.gov to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 618-826-5071 o visite https://idoc.illinois.gov para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|randolph',
        services='',
        county='Randolph',
        served_counties='Randolph',
        coverage='single',
        _source='https://idoc.illinois.gov', _source_type='government', _confidence='high',
    )
    add(
        name='IDOC — Logan Correctional Center',
        category='state-agency',
        region='Lincoln / Logan County',
        description='Logan Correctional Center is a women\'s IDOC facility providing education, vocational programming, and pre-release planning for female prisoners releasing to central Illinois communities through Land of Lincoln workforce and housing partners. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='IDOC — Logan Correctional Center sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. Logan Correctional Center is a women\'s IDOC facility providing education, vocational programming, and pre-release planning for female prisoners releasing to central Illinois communities through Land of Lincoln workforce and housing partners. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='1093 1350th Avenue',
        city='Lincoln',
        phone='217-735-5581',
        email='',
        website='https://idoc.illinois.gov',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 217-735-5581 or visit https://idoc.illinois.gov to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 217-735-5581 o visite https://idoc.illinois.gov para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|logan',
        services='',
        county='Logan',
        served_counties='Logan',
        coverage='single',
        _source='https://idoc.illinois.gov', _source_type='government', _confidence='high',
    )
    add(
        name='IDOC — Illinois River Correctional Center',
        category='state-agency',
        region='Canton / Fulton County',
        description='Illinois River Correctional Center provides in-custody programming and pre-release coordination for adult male prisoners releasing to west-central Illinois counties through Greater Peoria reentry and workforce partners. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='IDOC — Illinois River Correctional Center sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. Illinois River Correctional Center provides in-custody programming and pre-release coordination for adult male prisoners releasing to west-central Illinois counties through Greater Peoria reentry and workforce partners. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='1300 E. Washington Street',
        city='Canton',
        phone='309-647-4962',
        email='',
        website='https://idoc.illinois.gov',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 309-647-4962 or visit https://idoc.illinois.gov to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 309-647-4962 o visite https://idoc.illinois.gov para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|fulton',
        services='',
        county='Fulton',
        served_counties='Fulton',
        coverage='single',
        _source='https://idoc.illinois.gov', _source_type='government', _confidence='high',
    )
    add(
        name='IDOC — Danville Correctional Center',
        category='state-agency',
        region='Danville / Vermilion County',
        description='Danville Correctional Center provides education and reentry preparation for prisoners releasing to east-central Illinois including Champaign-Urbana and Vermilion County parole coordination. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='IDOC — Danville Correctional Center sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. Danville Correctional Center provides education and reentry preparation for prisoners releasing to east-central Illinois including Champaign-Urbana and Vermilion County parole coordination. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='3820 E. Main Street',
        city='Danville',
        phone='217-446-0441',
        email='',
        website='https://idoc.illinois.gov',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 217-446-0441 or visit https://idoc.illinois.gov to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 217-446-0441 o visite https://idoc.illinois.gov para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|vermilion',
        services='',
        county='Vermilion',
        served_counties='Vermilion',
        coverage='single',
        _source='https://idoc.illinois.gov', _source_type='government', _confidence='high',
    )
    add(
        name='IDOC — Reentry Summits Program',
        category='reentry-organizations',
        region='Statewide',
        description='IDOC Reentry Summits bring together community providers, employers, and corrections staff to coordinate reentry resources for returning citizens statewide with regional summit events connecting parole agents to local service directories. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='IDOC — Reentry Summits Program sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. IDOC Reentry Summits bring together community providers, employers, and corrections staff to coordinate reentry resources for returning citizens statewide with regional summit events connecting parole agents to local service directories. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='1301 Concordia Court',
        city='Springfield',
        phone='217-558-2200',
        email='',
        website='https://idoc.illinois.gov/programs/reentry.html',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 217-558-2200 or visit https://idoc.illinois.gov/programs/reentry.html to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 217-558-2200 o visite https://idoc.illinois.gov/programs/reentry.html para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|sangamon',
        services='',
        county='Sangamon',
        served_counties='',
        coverage='statewide',
        _source='https://idoc.illinois.gov/programs/reentry.html', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Illinois Reentry Coalition',
        category='reentry-organizations',
        region='Statewide',
        description='Illinois Reentry Coalition is a statewide network of reentry service providers, advocates, and corrections partners sharing resources and warm referrals for people leaving incarceration—not a direct-service crisis or housing provider. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='Illinois Reentry Coalition sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. Illinois Reentry Coalition is a statewide network of reentry service providers, advocates, and corrections partners sharing resources and warm referrals for people leaving incarceration—not a direct-service crisis or housing provider. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='571 W. Jackson Boulevard',
        city='Chicago',
        phone='312-922-2200',
        email='',
        website='https://www.saferfoundation.org/reentry-coalition',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 312-922-2200 or visit https://www.saferfoundation.org/reentry-coalition to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 312-922-2200 o visite https://www.saferfoundation.org/reentry-coalition para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|cook',
        services='',
        county='Cook',
        served_counties='',
        coverage='statewide',
        _source='https://www.saferfoundation.org/reentry-coalition', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Eastern Illinois Foodbank — Partner Network',
        category='food-nutrition',
        region='Urbana / Champaign County',
        description='Eastern Illinois Foodbank distributes food to partner pantries across east-central Illinois helping returning citizens locate emergency food by ZIP code in rural counties outside the Chicago metro. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='Eastern Illinois Foodbank — Partner Network sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. Eastern Illinois Foodbank distributes food to partner pantries across east-central Illinois helping returning citizens locate emergency food by ZIP code in rural counties outside the Chicago metro. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='2405 N. Shore Drive',
        city='Urbana',
        phone='217-328-3663',
        email='',
        website='https://www.eifoodbank.org',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 217-328-3663 or visit https://www.eifoodbank.org to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 217-328-3663 o visite https://www.eifoodbank.org para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|champaign',
        services='',
        county='Champaign',
        served_counties='Champaign|Clark|Coles|Cumberland|DeWitt|Douglas|Edgar|Effingham|Fayette|Jasper|Macon|Moultrie|Piatt|Richland|Shelby|Vermilion',
        coverage='multi',
        _source='https://www.eifoodbank.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='River Bend Foodbank — Partner Network',
        category='food-nutrition',
        region='Davenport Area',
        description='River Bend Foodbank serves partner pantries in the Quad Cities region helping returning citizens in Henry, Mercer, and Rock Island counties locate emergency food assistance by ZIP code. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='River Bend Foodbank — Partner Network sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. River Bend Foodbank serves partner pantries in the Quad Cities region helping returning citizens in Henry, Mercer, and Rock Island counties locate emergency food assistance by ZIP code. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='4010 Kimm Drive',
        city='Davenport',
        phone='309-764-7431',
        email='',
        website='https://www.riverbendfoodbank.org',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 309-764-7431 or visit https://www.riverbendfoodbank.org to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 309-764-7431 o visite https://www.riverbendfoodbank.org para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|rock island',
        services='',
        county='Rock Island',
        served_counties='Henry|Mercer|Rock Island',
        coverage='multi',
        _source='https://www.riverbendfoodbank.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Midwest Food Bank — Illinois Division',
        category='food-nutrition',
        region='Peoria / Peoria County',
        description='Midwest Food Bank Illinois Division distributes food to partner agencies across central Illinois helping returning citizens access emergency food through church and community pantry partners in the Peoria region. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='Midwest Food Bank — Illinois Division sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. Midwest Food Bank Illinois Division distributes food to partner agencies across central Illinois helping returning citizens access emergency food through church and community pantry partners in the Peoria region. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='2121 W. Willow Knolls Drive',
        city='Peoria',
        phone='309-691-2320',
        email='',
        website='https://www.midwestfoodbank.org',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 309-691-2320 or visit https://www.midwestfoodbank.org to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 309-691-2320 o visite https://www.midwestfoodbank.org para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|peoria',
        services='',
        county='Peoria',
        served_counties='Bureau|Fulton|Marshall|Peoria|Putnam|Stark|Tazewell|Woodford',
        coverage='multi',
        _source='https://www.midwestfoodbank.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Health Care Service Corporation — Blue Cross Community Health Plans',
        category='healthcare',
        region='Statewide',
        description='Blue Cross Community Health Plans provide Medicaid managed care enrollment and care coordination for Illinois Medicaid beneficiaries including justice-involved adults establishing health coverage through ABE after release. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='Health Care Service Corporation — Blue Cross Community Health Plans sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. Blue Cross Community Health Plans provide Medicaid managed care enrollment and care coordination for Illinois Medicaid beneficiaries including justice-involved adults establishing health coverage through ABE after release. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='300 E. Randolph Street',
        city='Chicago',
        phone='800-225-5432',
        email='',
        website='https://www.bcbsil.com',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 800-225-5432 or visit https://www.bcbsil.com to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 800-225-5432 o visite https://www.bcbsil.com para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|cook',
        services='',
        county='Cook',
        served_counties='',
        coverage='statewide',
        _source='https://www.bcbsil.com', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Illinois Healthcare and Family Services — Medicaid Enrollment',
        category='healthcare',
        region='Statewide',
        description='Illinois Department of Healthcare and Family Services administers Medicaid and manages care programs statewide helping returning citizens verify enrollment and connect to managed care plans after ABE application. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='Illinois Healthcare and Family Services — Medicaid Enrollment sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. Illinois Department of Healthcare and Family Services administers Medicaid and manages care programs statewide helping returning citizens verify enrollment and connect to managed care plans after ABE application. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='201 S. LaSalle Street',
        city='Chicago',
        phone='800-226-0768',
        email='',
        website='https://www.hfs.illinois.gov',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 800-226-0768 or visit https://www.hfs.illinois.gov to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 800-226-0768 o visite https://www.hfs.illinois.gov para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|cook',
        services='',
        county='Cook',
        served_counties='',
        coverage='statewide',
        _source='https://www.hfs.illinois.gov', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Illinois Valley FQHC — Open Door Health',
        category='healthcare',
        region='Oglesby / LaSalle County',
        description='Open Door Health is a federally qualified health center providing primary care, behavioral health, and sliding-fee services for uninsured residents in the Illinois Valley including returning citizens in rural north-central counties. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='Illinois Valley FQHC — Open Door Health sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. Open Door Health is a federally qualified health center providing primary care, behavioral health, and sliding-fee services for uninsured residents in the Illinois Valley including returning citizens in rural north-central counties. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='815 N. Orlando Smith Road',
        city='Oglesby',
        phone='815-882-2200',
        email='',
        website='https://www.opendoorhealth.net',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 815-882-2200 or visit https://www.opendoorhealth.net to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 815-882-2200 o visite https://www.opendoorhealth.net para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|lasalle',
        services='',
        county='LaSalle',
        served_counties='Bureau|LaSalle|Lee|Livingston|Ogle|Putnam',
        coverage='multi',
        _source='https://www.opendoorhealth.net', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Blessing Health System — Community Care',
        category='healthcare',
        region='Quincy / Adams County',
        description='Blessing Health System provides hospital and community health services including primary care referrals and behavioral health navigation for residents of western Adams County and surrounding rural communities including returning citizens. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='Blessing Health System — Community Care sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. Blessing Health System provides hospital and community health services including primary care referrals and behavioral health navigation for residents of western Adams County and surrounding rural communities including returning citizens. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='110 NE 11th Street',
        city='Quincy',
        phone='217-223-8400',
        email='',
        website='https://www.blessinghealth.org',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 217-223-8400 or visit https://www.blessinghealth.org to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 217-223-8400 o visite https://www.blessinghealth.org para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|adams',
        services='',
        county='Adams',
        served_counties='Adams|Brown|Hancock|Pike|Schuyler',
        coverage='multi',
        _source='https://www.blessinghealth.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Southern Illinois University — Adult Education Centers',
        category='education',
        region='Carbondale / Jackson County',
        description='Southern Illinois University Adult Education Centers provide GED, high school equivalency, and career training for adult learners including justice-involved residents in southern Illinois with free orientation and enrollment assistance. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='Southern Illinois University — Adult Education Centers sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. Southern Illinois University Adult Education Centers provide GED, high school equivalency, and career training for adult learners including justice-involved residents in southern Illinois with free orientation and enrollment assistance. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='625 Wham Drive',
        city='Carbondale',
        phone='618-453-5748',
        email='',
        website='https://www.siu.edu/adulted',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 618-453-5748 or visit https://www.siu.edu/adulted to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 618-453-5748 o visite https://www.siu.edu/adulted para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|jackson',
        services='',
        county='Jackson',
        served_counties='Franklin|Jackson|Jefferson|Johnson|Perry|Randolph|Saline|Union|Williamson',
        coverage='multi',
        _source='https://www.siu.edu/adulted', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Illinois Community Action — State Association',
        category='basic-needs',
        region='Statewide',
        description='Illinois Community Action Association connects low-income residents to local Community Action Agencies in every county offering utility assistance, weatherization, emergency aid, and case management for returning citizens statewide. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='Illinois Community Action — State Association sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. Illinois Community Action Association connects low-income residents to local Community Action Agencies in every county offering utility assistance, weatherization, emergency aid, and case management for returning citizens statewide. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='2610 N. Walnut Street',
        city='Springfield',
        phone='217-528-8400',
        email='',
        website='https://www.icaaonline.org',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 217-528-8400 or visit https://www.icaaonline.org to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 217-528-8400 o visite https://www.icaaonline.org para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|sangamon',
        services='',
        county='Sangamon',
        served_counties='',
        coverage='statewide',
        _source='https://www.icaaonline.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Illinois Housing Development Authority — Rental Assistance',
        category='housing',
        region='Statewide',
        description='Illinois Housing Development Authority provides affordable housing resources, emergency rental assistance programs, and housing locator tools for low-income Illinois residents including returning citizens seeking income-restricted rental units. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='Illinois Housing Development Authority — Rental Assistance sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. Illinois Housing Development Authority provides affordable housing resources, emergency rental assistance programs, and housing locator tools for low-income Illinois residents including returning citizens seeking income-restricted rental units. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='111 E. Wacker Drive',
        city='Chicago',
        phone='312-386-8000',
        email='',
        website='https://www.ihda.org',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 312-386-8000 or visit https://www.ihda.org to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 312-386-8000 o visite https://www.ihda.org para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|cook',
        services='',
        county='Cook',
        served_counties='',
        coverage='statewide',
        _source='https://www.ihda.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Volunteers of America — Illinois Reentry',
        category='housing',
        region='Chicago / Cook County',
        description='Volunteers of America Illinois provides supportive housing, case management, and veterans reentry services for justice-involved adults and veterans in Chicago including transitional housing with sobriety and program participation requirements. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='Volunteers of America — Illinois Reentry sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. Volunteers of America Illinois provides supportive housing, case management, and veterans reentry services for justice-involved adults and veterans in Chicago including transitional housing with sobriety and program participation requirements. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='161 N. Clark Street',
        city='Chicago',
        phone='312-663-1700',
        email='',
        website='https://www.voaillinois.org',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 312-663-1700 or visit https://www.voaillinois.org to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 312-663-1700 o visite https://www.voaillinois.org para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|cook',
        services='',
        county='Cook',
        served_counties='Cook',
        coverage='single',
        _source='https://www.voaillinois.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Catholic Charities — Diocese of Joliet Reentry',
        category='basic-needs',
        region='Joliet / Will County',
        description='Catholic Charities Diocese of Joliet provides emergency assistance, food pantry access, counseling, and case management referrals for low-income residents including returning citizens in Will County and surrounding collar counties. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='Catholic Charities — Diocese of Joliet Reentry sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. Catholic Charities Diocese of Joliet provides emergency assistance, food pantry access, counseling, and case management referrals for low-income residents including returning citizens in Will County and surrounding collar counties. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='249 S. Schuyler Avenue',
        city='Joliet',
        phone='815-723-3405',
        email='',
        website='https://www.catholiccharitiesjoliet.org',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 815-723-3405 or visit https://www.catholiccharitiesjoliet.org to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 815-723-3405 o visite https://www.catholiccharitiesjoliet.org para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|will',
        services='',
        county='Will',
        served_counties='DuPage|Grundy|Kankakee|Kendall|Lake|McHenry|Will',
        coverage='multi',
        _source='https://www.catholiccharitiesjoliet.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='United Way of Metro Chicago — 211 Navigation',
        category='reentry-organizations',
        region='Chicago Metro',
        description='United Way of Metro Chicago supports community resource navigation and partners with 211 Illinois to connect returning citizens in the Chicago metropolitan area to housing, employment, and benefits resources through local nonprofit partners. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='United Way of Metro Chicago — 211 Navigation sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. United Way of Metro Chicago supports community resource navigation and partners with 211 Illinois to connect returning citizens in the Chicago metropolitan area to housing, employment, and benefits resources through local nonprofit partners. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='333 S. Wabash Avenue',
        city='Chicago',
        phone='312-906-2350',
        email='',
        website='https://www.unitedwaychicago.org',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 312-906-2350 or visit https://www.unitedwaychicago.org to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 312-906-2350 o visite https://www.unitedwaychicago.org para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|cook',
        services='',
        county='Cook',
        served_counties='Cook|DuPage|Kane|Lake|McHenry|Will',
        coverage='multi',
        _source='https://www.unitedwaychicago.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Illinois Criminal Justice Information Authority — Reentry',
        category='reentry-organizations',
        region='Statewide',
        description='Illinois Criminal Justice Information Authority coordinates research, grant-funded reentry programs, and policy resources connecting justice-involved Illinois residents to evidence-based services through community provider networks statewide. Contact this resource to confirm current intake steps, required documents, and whether walk-ins or referrals are accepted before visiting.',
        description_es='Illinois Criminal Justice Information Authority — Reentry sirve a adultos con antecedentes penales y familias que reconstruyen estabilidad en Illinois. Illinois Criminal Justice Information Authority coordinates research, grant-funded reentry programs, and policy resources connecting justice-involved Illinois residents to evidence-based services through community provider networks statewide. Contacte el programa para confirmar admisión, documentos requeridos y horarios actuales.',
        address='300 W. Adams Street',
        city='Chicago',
        phone='312-793-8550',
        email='',
        website='https://www.icjia.state.il.us',
        eligibility='Illinois residents in the program service area; justice-involved individuals generally welcome; income or referral rules vary by service.',
        eligibility_es='Residentes de Illinois en el área de servicio; personas con antecedentes penales generalmente son bienvenidas; las reglas varían según el servicio.',
        notes='Call 312-793-8550 or visit https://www.icjia.state.il.us to confirm current intake hours and whether walk-ins or referrals are accepted.',
        notes_es='Llame al 312-793-8550 o visite https://www.icjia.state.il.us para confirmar horarios de admisión y si se aceptan visitas sin cita o referencias.',
        hours='Contact for current hours',
        tags='reentry|illinois|cook',
        services='',
        county='Cook',
        served_counties='',
        coverage='statewide',
        _source='https://www.icjia.state.il.us', _source_type='nonprofit', _confidence='high',
    )
