"""Phase 4 program-level expansion entries for Michigan reentry resources."""


def register_phase4(add):
    """Register verified program-level resources with full EN+ES fields."""

    # --- Metro Detroit: housing ---
    add(
        name='Coalition on Temporary Shelter (COTS)',
        category='housing',
        region='Detroit / Wayne County',
        description='Detroit nonprofit providing emergency shelter, transitional housing, and permanent supportive housing for families experiencing homelessness including parents reuniting with children after incarceration. COTS operates year-round shelter services and case management in Wayne County. Contact the Coordinated Assessment Model (CAM) at 313-305-0311 before seeking emergency shelter intake.',
        description_es='Organización sin fines de lucro de Detroit con refugio de emergencia, vivienda transicional y vivienda de apoyo permanente para familias sin hogar, incluidos padres que se reúnen con hijos después de la encarcelación. COTS opera servicios de refugio y manejo de casos en el condado Wayne. Contacte el Modelo de Evaluación Coordinada (CAM) al 313-305-0311 antes de buscar admisión a refugio de emergencia.',
        address='26 Peterboro Street, Suite 100',
        city='Detroit',
        phone='313-831-3777',
        email='engage@cotsdetroit.org',
        website='https://cotsdetroit.org',
        eligibility='Families experiencing homelessness in Wayne County; intake coordinated through CAM; criminal record generally not a stated barrier.',
        eligibility_es='Familias sin hogar en el condado Wayne; admisión coordinada a través de CAM; los antecedentes penales generalmente no son barrera indicada.',
        notes='For emergency shelter access call CAM 313-305-0311 Mon–Fri 8 a.m.–6 p.m.; COTS admin office at 26 Peterboro for program questions.',
        notes_es='Para acceso a refugio de emergencia llame a CAM 313-305-0311 lun–vie 8 a.m.–6 p.m.; oficina administrativa de COTS en 26 Peterboro para preguntas del programa.',
        hours='Shelter 24/7; admin office Mon–Fri business hours',
        tags='detroit|wayne|housing|shelter|families|reentry',
        services='Emergency shelter|Transitional housing|Permanent supportive housing|Case management|Family reunification support',
        county='Wayne',
        served_counties='Wayne',
        coverage='single',
        _source='https://cotsdetroit.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Neighborhood Service Organization (NSO) — Tumaini Center',
        category='housing',
        region='Detroit / Wayne County',
        description='Detroit human services agency operating the Tumaini Center drop-in shelter and housing navigation for adults experiencing homelessness including returning citizens without stable housing in Wayne County. NSO connects clients to emergency shelter beds, housing assessments, and behavioral health referrals through CAM coordination.',
        description_es='Agencia de servicios humanos de Detroit que opera el refugio de acogida Tumaini Center y navegación de vivienda para adultos sin hogar, incluidos ciudadanos que regresan sin vivienda estable en el condado Wayne. NSO conecta a clientes con camas de refugio de emergencia, evaluaciones de vivienda y referencias de salud conductual a través de CAM.',
        address='882 Oakman Boulevard',
        city='Detroit',
        phone='313-961-4890',
        email='',
        website='https://www.nso-mi.org',
        eligibility='Adults experiencing homelessness in Wayne County; contact program for current intake and CAM referral requirements.',
        eligibility_es='Adultos sin hogar en el condado Wayne; contacte el programa para admisión actual y requisitos de referencia CAM.',
        notes='Call 313-961-4890 or CAM 313-305-0311 for shelter access; NSO also offers behavioral health and employment support programs.',
        notes_es='Llame al 313-961-4890 o CAM 313-305-0311 para acceso a refugio; NSO también ofrece programas de salud conductual y empleo.',
        hours='Contact for current shelter and drop-in hours',
        tags='detroit|wayne|housing|shelter|homeless|reentry',
        services='Drop-in shelter|Housing navigation|Behavioral health referrals|Employment support|CAM coordination',
        county='Wayne',
        served_counties='Wayne',
        coverage='single',
        _source='https://www.nso-mi.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Detroit Rescue Mission Ministries — Men\'s Campus',
        category='housing',
        region='Detroit / Wayne County',
        description='Faith-based Detroit rescue mission providing emergency shelter, meals, addiction recovery, and life-skills programming for men experiencing homelessness including justice-involved men seeking stable housing after release. Multiple campuses serve Wayne County with case management and referral to employment and treatment partners.',
        description_es='Misión de rescate de fe en Detroit con refugio de emergencia, comidas, recuperación de adicciones y programación de habilidades para la vida para hombres sin hogar, incluidos hombres con antecedentes penales que buscan vivienda estable después de la liberación. Varios campus sirven al condado Wayne con manejo de casos.',
        address='3535 Third Avenue',
        city='Detroit',
        phone='313-993-4700',
        email='',
        website='https://www.drmm.org',
        eligibility='Men experiencing homelessness or seeking recovery programming; contact campus for intake requirements; justice-involved individuals often accepted.',
        eligibility_es='Hombres sin hogar o que buscan programación de recuperación; contacte el campus para requisitos de admisión; personas con antecedentes penales a menudo aceptadas.',
        notes='Call 313-993-4700 for intake; separate women\'s and family programs at other DRMM locations; verify current bed availability.',
        notes_es='Llame al 313-993-4700 para admisión; programas separados para mujeres y familias en otras ubicaciones DRMM; verifique disponibilidad de camas.',
        hours='Contact for current intake hours',
        tags='detroit|wayne|housing|shelter|faith-based|recovery|reentry',
        services='Emergency shelter|Meals|Addiction recovery|Life skills|Case management|Employment referrals',
        county='Wayne',
        served_counties='Wayne',
        coverage='single',
        _source='https://www.drmm.org', _source_type='nonprofit', _confidence='high',
    )

    # --- Metro Detroit: legal, healthcare, food ---
    add(
        name='Lakeshore Legal Aid — Detroit Office',
        category='legal-aid',
        region='Metro Detroit / Wayne, Oakland & Macomb',
        description='Nonprofit civil legal aid serving low-income residents in Wayne, Oakland, and Macomb counties with housing, public benefits, family law, and consumer matters affecting reentry stability. Detroit office intake connects eligible clients to attorneys for eviction defense and benefits appeals. Does not provide criminal defense representation.',
        description_es='Asistencia legal civil sin fines de lucro para residentes de bajos ingresos en los condados Wayne, Oakland y Macomb con vivienda, beneficios públicos, derecho familiar y asuntos de consumo que afectan la estabilidad en reinserción. La admisión de la oficina de Detroit conecta con abogados para defensa de desalojo. No proporciona defensa penal.',
        address='3031 West Grand Boulevard, Suite 520',
        city='Detroit',
        phone='888-783-8190',
        email='',
        website='https://lakeshorelegalaid.org',
        eligibility='Low-income residents of Wayne, Oakland, or Macomb counties with qualifying civil legal problems; income limits apply.',
        eligibility_es='Residentes de bajos ingresos de Wayne, Oakland o Macomb con problemas legales civiles calificados; aplican límites de ingresos.',
        notes='Call 888-783-8190 for intake; apply online at lakeshorelegalaid.org; appointment required for attorney meetings.',
        notes_es='Llame al 888-783-8190 para admisión; solicite en línea en lakeshorelegalaid.org; se requiere cita para reuniones con abogados.',
        hours='Intake Monday–Friday business hours',
        tags='detroit|wayne|oakland|macomb|legal-aid|housing|reentry',
        services='Civil legal representation|Eviction defense|Benefits advocacy|Family law assistance|Consumer legal help',
        county='Wayne',
        served_counties='Wayne|Oakland|Macomb',
        coverage='multi',
        _source='https://lakeshorelegalaid.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Detroit Wayne Integrated Health Network (DWIHN)',
        category='healthcare',
        region='Detroit / Wayne County',
        description='Wayne County prepaid inpatient health plan and community mental health authority coordinating Medicaid behavioral health services, crisis response, and substance use treatment referrals for residents including justice-involved individuals reestablishing outpatient care after release. DWIHN connects members to provider networks and 988 crisis support.',
        description_es='Plan de salud prepagado del condado Wayne y autoridad de salud mental comunitaria que coordina servicios de salud conductual Medicaid, respuesta de crisis y referencias de tratamiento de sustancias para residentes, incluidas personas con antecedentes penales que restablecen atención ambulatoria después de la liberación.',
        address='707 West Milwaukee Street',
        city='Detroit',
        phone='800-241-4949',
        email='',
        website='https://www.dwihn.org',
        eligibility='Wayne County Medicaid beneficiaries and residents accessing publicly funded behavioral health services; eligibility varies by program.',
        eligibility_es='Beneficiarios de Medicaid del condado Wayne y residentes que acceden a servicios públicos de salud conductual; la elegibilidad varía según el programa.',
        notes='Member services 800-241-4949; for crisis call or text 988; provider directory at dwihn.org.',
        notes_es='Servicios para miembros 800-241-4949; para crisis llame o envíe texto al 988; directorio de proveedores en dwihn.org.',
        hours='Member services Mon–Fri business hours; 988 available 24/7',
        tags='detroit|wayne|healthcare|mental-health|Medicaid|reentry',
        services='Behavioral health care coordination|Substance use treatment referrals|Crisis services navigation|Medicaid provider network|Peer support linkage',
        county='Wayne',
        served_counties='Wayne',
        coverage='single',
        _source='https://www.dwihn.org', _source_type='government', _confidence='high',
    )
    add(
        name='Henry Ford Health — Community Health & Wellness Center (FQHC)',
        category='healthcare',
        region='Detroit / Wayne County',
        description='Federally qualified health center operated by Henry Ford Health providing primary care, behavioral health, dental, and pharmacy services on a sliding fee scale for underserved Detroit residents including returning citizens reestablishing medical care after incarceration. Accepts Medicaid and uninsured patients.',
        description_es='Centro de salud calificado federalmente operado por Henry Ford Health con atención primaria, salud conductual, dental y farmacia con tarifa escalonada para residentes desatendidos de Detroit, incluidos ciudadanos que regresan que restablecen atención médica después de la encarcelación. Acepta Medicaid y pacientes sin seguro.',
        address='7633 Second Avenue',
        city='Detroit',
        phone='313-874-7000',
        email='',
        website='https://www.henryford.com/locations/community-health',
        eligibility='Open to Detroit-area residents; sliding fee scale based on income; criminal record not a stated barrier.',
        eligibility_es='Abierto a residentes del área de Detroit; tarifa escalonada según ingresos; antecedentes penales no son barrera indicada.',
        notes='Call 313-874-7000 for appointments; multiple Henry Ford community health sites serve Wayne County; bring ID and proof of income if available.',
        notes_es='Llame al 313-874-7000 para citas; varios sitios de salud comunitaria Henry Ford sirven al condado Wayne; traiga identificación.',
        hours='Monday–Friday clinic hours; contact location for schedule',
        tags='detroit|wayne|healthcare|FQHC|primary-care|reentry',
        services='Primary care|Behavioral health|Dental services|Pharmacy|Sliding fee scale|Medicaid enrollment assistance',
        county='Wayne',
        served_counties='Wayne',
        coverage='single',
        _source='https://www.henryford.com/locations/community-health', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Gleaners Community Food Bank of Southeastern Michigan',
        category='food-nutrition',
        region='Southeast Michigan',
        description='Regional food bank distributing to partner pantries, mobile distributions, and school programs across Wayne, Oakland, Macomb, Monroe, and Livingston counties. Returning citizens and families can locate nearest partner pantry by ZIP code through the online food finder. Food assistance only—not cash or housing services.',
        description_es='Banco de alimentos regional que distribuye a despensas aliadas, distribuciones móviles y programas escolares en los condados Wayne, Oakland, Macomb, Monroe y Livingston. Ciudadanos que regresan pueden localizar la despensa aliada más cercana por código postal. Solo asistencia alimentaria, no efectivo ni vivienda.',
        address='2131 Beaufait Street',
        city='Detroit',
        phone='866-453-2637',
        email='',
        website='https://www.gcfb.org',
        eligibility='Open to Michigan residents needing food assistance through partner agencies; pantry rules vary by location.',
        eligibility_es='Abierto a residentes de Michigan que necesitan asistencia alimentaria a través de agencias aliadas; las reglas varían según la ubicación.',
        notes='Use gcfb.org/find-food for partner pantry locator; call 866-453-2637 for distribution schedules.',
        notes_es='Use gcfb.org/find-food para localizar despensas aliadas; llame al 866-453-2637 para horarios de distribución.',
        hours='Warehouse Mon–Fri; partner pantry hours vary',
        tags='detroit|wayne|oakland|macomb|food-bank|pantry|reentry',
        services='Partner pantry network|Mobile food distribution|SNAP outreach|School meal partnerships|Online food finder',
        county='Wayne',
        served_counties='Wayne|Oakland|Macomb|Monroe|Livingston',
        coverage='multi',
        _source='https://www.gcfb.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='HUDA Clinic — Free Community Health Center',
        category='healthcare',
        region='Detroit / Wayne County',
        description='Faith-based free clinic in Detroit providing primary care, mental health counseling, dental, vision, and prescription assistance for uninsured and underinsured Wayne County residents including returning citizens without established medical coverage. Services provided at no charge with appointment.',
        description_es='Clínica gratuita de fe en Detroit con atención primaria, consejería de salud mental, dental, visión y asistencia con recetas para residentes del condado Wayne sin seguro o con seguro insuficiente, incluidos ciudadanos que regresan sin cobertura médica establecida. Servicios sin cargo con cita.',
        address='13240 Woodrow Wilson Street',
        city='Detroit',
        phone='313-871-7811',
        email='',
        website='https://www.hudaclinic.org',
        eligibility='Uninsured or underinsured Wayne County residents; appointment required; criminal record not a stated barrier.',
        eligibility_es='Residentes del condado Wayne sin seguro o con seguro insuficiente; se requiere cita; antecedentes penales no son barrera indicada.',
        notes='Call 313-871-7811 for appointments; volunteer physicians and specialists; prescription assistance available for eligible patients.',
        notes_es='Llame al 313-871-7811 para citas; médicos y especialistas voluntarios; asistencia con recetas disponible.',
        hours='Clinic days vary; call for appointment schedule',
        tags='detroit|wayne|healthcare|free-clinic|dental|reentry',
        services='Primary care|Mental health counseling|Dental care|Vision services|Prescription assistance|Referrals',
        county='Wayne',
        served_counties='Wayne',
        coverage='single',
        _source='https://www.hudaclinic.org', _source_type='nonprofit', _confidence='high',
    )

    # --- Grand Rapids / Kent ---
    add(
        name='Mel Trotter Ministries',
        category='housing',
        region='Grand Rapids / Kent County',
        description='Grand Rapids rescue mission providing emergency shelter, meals, addiction recovery, and workforce development for men and women experiencing homelessness including returning citizens in Kent County. Mel Trotter connects guests to housing navigation, employment training, and community partner referrals.',
        description_es='Misión de rescate de Grand Rapids con refugio de emergencia, comidas, recuperación de adicciones y desarrollo de fuerza laboral para hombres y mujeres sin hogar, incluidos ciudadanos que regresan en el condado Kent. Mel Trotter conecta a huéspedes con navegación de vivienda y capacitación laboral.',
        address='225 Commerce Avenue SW',
        city='Grand Rapids',
        phone='616-454-4110',
        email='',
        website='https://www.meltrotter.org',
        eligibility='Adults experiencing homelessness or seeking recovery programming in Kent County; contact for intake requirements.',
        eligibility_es='Adultos sin hogar o que buscan programación de recuperación en el condado Kent; contacte para requisitos de admisión.',
        notes='Call 454-4110 for intake; separate men\'s and women\'s programs; workforce center assists with job readiness.',
        notes_es='Llame al 454-4110 para admisión; programas separados para hombres y mujeres; centro de fuerza laboral ayuda con preparación laboral.',
        hours='Contact for current shelter intake hours',
        tags='grand-rapids|kent|housing|shelter|recovery|reentry',
        services='Emergency shelter|Meals|Addiction recovery|Workforce development|Housing navigation|Case management',
        county='Kent',
        served_counties='Kent',
        coverage='single',
        _source='https://www.meltrotter.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Community Rebuilders',
        category='housing',
        region='Grand Rapids / Kent County',
        description='Kent County nonprofit providing permanent supportive housing, rapid rehousing, and landlord engagement for families and individuals experiencing homelessness including justice-involved tenants facing housing barriers due to criminal records. Community Rebuilders works with MDOC reentry partners in West Michigan.',
        description_es='Organización sin fines de lucro del condado Kent con vivienda de apoyo permanente, realojamiento rápido y participación de propietarios para familias e individuos sin hogar, incluidos inquilinos con antecedentes penales que enfrentan barreras de vivienda. Community Rebuilders trabaja con aliados de reinserción del MDOC en el oeste de Michigan.',
        address='101 Sheldon Boulevard SE, Suite 2',
        city='Grand Rapids',
        phone='616-458-2533',
        email='',
        website='https://www.communityrebuilders.org',
        eligibility='Households experiencing homelessness in Kent County meeting program criteria; referral often through Coordinated Entry.',
        eligibility_es='Hogares sin hogar en el condado Kent que cumplan criterios del programa; referencia a menudo a través de Entrada Coordinada.',
        notes='Call 616-458-2533; works with Kent County Coordinated Entry; landlord engagement program reduces housing barriers.',
        notes_es='Llame al 616-458-2533; trabaja con Entrada Coordinada del condado Kent; programa de propietarios reduce barreras de vivienda.',
        hours='Monday–Friday business hours',
        tags='grand-rapids|kent|housing|supportive-housing|reentry',
        services='Permanent supportive housing|Rapid rehousing|Landlord engagement|Housing case management|Coordinated Entry partnerships',
        county='Kent',
        served_counties='Kent',
        coverage='single',
        _source='https://www.communityrebuilders.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Legal Aid of West Michigan',
        category='legal-aid',
        region='West Michigan / 17 counties',
        description='Nonprofit civil legal aid serving low-income residents across 17 West Michigan counties including Kent, Ottawa, and Muskegon with housing, public benefits, family law, and consumer matters affecting reentry. Centralized intake at 616-774-0672 connects callers to Grand Rapids and regional offices. Does not handle criminal defense.',
        description_es='Asistencia legal civil sin fines de lucro para residentes de bajos ingresos en 17 condados del oeste de Michigan incluyendo Kent, Ottawa y Muskegon con vivienda, beneficios y derecho familiar que afectan la reinserción. Admisión centralizada al 616-774-0672. No maneja defensa penal.',
        address='89 Ionia Avenue NW, Suite 400',
        city='Grand Rapids',
        phone='616-774-0672',
        email='',
        website='https://www.lawestmichigan.org',
        eligibility='Low-income residents in 17-county West Michigan service area; income and household-size limits apply.',
        eligibility_es='Residentes de bajos ingresos en el área de 17 condados del oeste de Michigan; aplican límites de ingresos.',
        notes='Apply online at lawestmichigan.org or call 616-774-0672; eviction and benefits cases prioritized for eligible clients.',
        notes_es='Solicite en línea en lawestmichigan.org o llame al 616-774-0672; casos de desalojo y beneficios priorizados.',
        hours='Intake Monday–Friday business hours',
        tags='grand-rapids|kent|legal-aid|housing|reentry',
        services='Civil legal representation|Eviction defense|Benefits advocacy|Family law assistance|Consumer legal help',
        county='Kent',
        served_counties='Allegan|Barry|Ionia|Kent|Lake|Mecosta|Montcalm|Muskegon|Newaygo|Oceana|Osceola|Ottawa',
        coverage='multi',
        _source='https://www.lawestmichigan.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Cherry Health',
        category='healthcare',
        region='West Michigan / Kent County',
        description='Federally qualified health center network headquartered in Grand Rapids providing primary care, behavioral health, dental, and pharmacy services on a sliding fee scale across Kent and surrounding counties. Serves uninsured and Medicaid patients including returning citizens establishing medical and mental health care after release.',
        description_es='Red de centros de salud calificados federalmente con sede en Grand Rapids que ofrece atención primaria, salud conductual, dental y farmacia con tarifa escalonada en Kent y condados circundantes. Sirve a pacientes sin seguro y Medicaid, incluidos ciudadanos que regresan que establecen atención médica después de la liberación.',
        address='550 Cherry Street SE',
        city='Grand Rapids',
        phone='616-965-8200',
        email='',
        website='https://www.cherryhealth.com',
        eligibility='Open to West Michigan residents; sliding fee scale based on income; accepts Medicaid and Medicare.',
        eligibility_es='Abierto a residentes del oeste de Michigan; tarifa escalonada según ingresos; acepta Medicaid y Medicare.',
        notes='Call 616-965-8200 or use cherryhealth.com location finder; multiple sites across Kent County.',
        notes_es='Llame al 616-965-8200 o use el buscador de ubicaciones en cherryhealth.com; múltiples sitios en el condado Kent.',
        hours='Clinic hours vary by location',
        tags='grand-rapids|kent|healthcare|FQHC|primary-care|reentry',
        services='Primary care|Behavioral health|Dental care|Pharmacy|Sliding fee scale|Multiple clinic locations',
        county='Kent',
        served_counties='Kent|Montcalm|Ottawa',
        coverage='multi',
        _source='https://www.cherryhealth.com', _source_type='nonprofit', _confidence='high',
    )

    # --- Lansing / Ingham ---
    add(
        name='Haven House',
        category='housing',
        region='Lansing / Ingham County',
        description='Lansing emergency shelter and housing program serving families and individuals experiencing homelessness in Ingham County including parents reuniting with children after incarceration. Haven House provides shelter beds, case management, and rapid rehousing navigation through local Coordinated Entry.',
        description_es='Refugio de emergencia y programa de vivienda de Lansing para familias e individuos sin hogar en el condado Ingham, incluidos padres que se reúnen con hijos después de la encarcelación. Haven House ofrece camas de refugio, manejo de casos y navegación de realojamiento rápido.',
        address='1212 Turner Street',
        city='Lansing',
        phone='517-337-2731',
        email='',
        website='https://www.havenhouseelc.org',
        eligibility='Households experiencing homelessness in Ingham County; contact for intake and Coordinated Entry referral requirements.',
        eligibility_es='Hogares sin hogar en el condado Ingham; contacte para admisión y requisitos de referencia de Entrada Coordinada.',
        notes='Call 517-337-2731 for intake; coordinated through Ingham County housing access system.',
        notes_es='Llame al 517-337-2731 para admisión; coordinado a través del sistema de acceso a vivienda del condado Ingham.',
        hours='Contact for current shelter hours',
        tags='lansing|ingham|housing|shelter|families|reentry',
        services='Emergency shelter|Case management|Rapid rehousing|Coordinated Entry|Family shelter',
        county='Ingham',
        served_counties='Ingham',
        coverage='single',
        _source='https://www.havenhouseelc.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Mid-Michigan Legal Aid',
        category='legal-aid',
        region='Mid-Michigan / Clinton, Eaton & Ingham',
        description='Nonprofit civil legal aid serving low-income residents in Clinton, Eaton, and Ingham counties with housing, public benefits, family law, and consumer matters affecting reentry stability. Lansing office intake connects eligible clients to attorneys. Does not provide criminal defense representation.',
        description_es='Asistencia legal civil sin fines de lucro para residentes de bajos ingresos en los condados Clinton, Eaton e Ingham con vivienda, beneficios y derecho familiar que afectan la estabilidad en reinserción. La admisión de la oficina de Lansing conecta con abogados. No proporciona defensa penal.',
        address='300 North Washington Square, Suite 100',
        city='Lansing',
        phone='517-394-3121',
        email='',
        website='https://www.mmlas.org',
        eligibility='Low-income residents of Clinton, Eaton, or Ingham counties with qualifying civil legal problems; income limits apply.',
        eligibility_es='Residentes de bajos ingresos de Clinton, Eaton o Ingham con problemas legales civiles calificados; aplican límites de ingresos.',
        notes='Call 517-394-3121 or apply online at mmlas.org; appointment required for attorney consultation.',
        notes_es='Llame al 517-394-3121 o solicite en línea en mmlas.org; se requiere cita para consulta con abogado.',
        hours='Intake Monday–Friday business hours',
        tags='lansing|ingham|legal-aid|housing|reentry',
        services='Civil legal representation|Eviction defense|Benefits advocacy|Family law assistance|Consumer legal help',
        county='Ingham',
        served_counties='Clinton|Eaton|Ingham',
        coverage='multi',
        _source='https://www.mmlas.org', _source_type='nonprofit', _confidence='high',
    )

    # --- Flint / Genesee ---
    add(
        name='Carriage Town Ministries',
        category='housing',
        region='Flint / Genesee County',
        description='Flint rescue mission providing emergency shelter, meals, addiction recovery, and life transformation programming for men and women experiencing homelessness including returning citizens in Genesee County. Carriage Town connects guests to employment, treatment, and permanent housing partners.',
        description_es='Misión de rescate de Flint con refugio de emergencia, comidas, recuperación de adicciones y programación de transformación de vida para hombres y mujeres sin hogar, incluidos ciudadanos que regresan en el condado Genesee. Carriage Town conecta a huéspedes con empleo, tratamiento y vivienda permanente.',
        address='605 Garland Street',
        city='Flint',
        phone='810-234-5528',
        email='',
        website='https://www.carriage-town.org',
        eligibility='Adults experiencing homelessness or seeking recovery programming in Genesee County; contact for intake requirements.',
        eligibility_es='Adultos sin hogar o que buscan programación de recuperación en el condado Genesee; contacte para requisitos de admisión.',
        notes='Call 810-234-5528 for intake; separate men\'s and women\'s recovery programs; verify current bed availability.',
        notes_es='Llame al 810-234-5528 para admisión; programas de recuperación separados para hombres y mujeres; verifique disponibilidad.',
        hours='Contact for current intake hours',
        tags='flint|genesee|housing|shelter|recovery|reentry',
        services='Emergency shelter|Meals|Addiction recovery|Life skills|Employment referrals|Housing navigation',
        county='Genesee',
        served_counties='Genesee',
        coverage='single',
        _source='https://www.carriage-town.org', _source_type='nonprofit', _confidence='high',
    )

    # --- Ann Arbor / Washtenaw ---
    add(
        name='SOS Community Services',
        category='housing',
        region='Ann Arbor / Washtenaw County',
        description='Washtenaw County human services agency providing housing assistance, emergency financial aid, food pantry, and employment support for low-income residents including returning citizens rebuilding stability in Ann Arbor and Ypsilanti. SOS operates rapid rehousing and homelessness prevention programs.',
        description_es='Agencia de servicios humanos del condado Washtenaw con asistencia de vivienda, ayuda financiera de emergencia, despensa de alimentos y apoyo de empleo para residentes de bajos ingresos, incluidos ciudadanos que regresan que reconstruyen estabilidad en Ann Arbor e Ypsilanti.',
        address='114 South River Street',
        city='Ypsilanti',
        phone='734-484-9944',
        email='',
        website='https://www.soswashtenaw.org',
        eligibility='Washtenaw County residents meeting income guidelines for housing and basic needs programs; contact for current eligibility.',
        eligibility_es='Residentes del condado Washtenaw que cumplan pautas de ingresos para programas de vivienda y necesidades básicas; contacte para elegibilidad actual.',
        notes='Call 734-484-9944; housing intake through Coordinated Entry; food pantry and financial assistance by appointment.',
        notes_es='Llame al 734-484-9944; admisión de vivienda a través de Entrada Coordinada; despensa y asistencia financiera con cita.',
        hours='Monday–Friday business hours; pantry hours vary',
        tags='ann-arbor|washtenaw|housing|basic-needs|reentry',
        services='Housing assistance|Emergency financial aid|Food pantry|Employment support|Homelessness prevention|Rapid rehousing',
        county='Washtenaw',
        served_counties='Washtenaw',
        coverage='single',
        _source='https://www.soswashtenaw.org', _source_type='nonprofit', _confidence='high',
    )

    # --- Kalamazoo ---
    add(
        name='Ministry with Community',
        category='housing',
        region='Kalamazoo / Kalamazoo County',
        description='Kalamazoo day shelter and basic needs center providing meals, showers, laundry, mail service, and housing navigation for adults experiencing homelessness including returning citizens in Kalamazoo County. Ministry with Community connects guests to employment, treatment, and permanent housing partners.',
        description_es='Refugio diurno y centro de necesidades básicas de Kalamazoo con comidas, duchas, lavandería, servicio de correo y navegación de vivienda para adultos sin hogar, incluidos ciudadanos que regresan en el condado Kalamazoo. Conecta a huéspedes con empleo, tratamiento y vivienda permanente.',
        address='440 N Church Street',
        city='Kalamazoo',
        phone='269-343-6070',
        email='',
        website='https://www.ministrywithcommunity.org',
        eligibility='Adults experiencing homelessness in Kalamazoo County; walk-in day shelter services; housing programs have separate intake.',
        eligibility_es='Adultos sin hogar en el condado Kalamazoo; servicios de refugio diurno sin cita; programas de vivienda tienen admisión separada.',
        notes='Day shelter open weekdays; call 269-343-6070 for housing program intake and current hours.',
        notes_es='Refugio diurno abierto entre semana; llame al 269-343-6070 para admisión a programas de vivienda y horarios actuales.',
        hours='Day shelter weekday hours; contact for schedule',
        tags='kalamazoo|housing|basic-needs|day-shelter|reentry',
        services='Day shelter|Meals|Showers and laundry|Mail service|Housing navigation|Employment referrals',
        county='Kalamazoo',
        served_counties='Kalamazoo',
        coverage='single',
        _source='https://www.ministrywithcommunity.org', _source_type='nonprofit', _confidence='high',
    )

    # --- Regional legal aid ---
    add(
        name='Michigan Legal Help',
        category='legal-aid',
        region='Statewide',
        description='Statewide legal information portal operated by the Michigan Advocacy Program providing plain-language guides, court forms, and self-help tools for housing, benefits, family law, and expungement navigation. Helps Michigan residents understand civil legal options and connect to local legal aid providers. Online resource hub—not a law firm providing direct representation.',
        description_es='Portal estatal de información legal operado por Michigan Advocacy Program con guías en lenguaje sencillo, formularios judiciales y herramientas de autoayuda para vivienda, beneficios, derecho familiar y navegación de eliminación de antecedentes. Ayuda a conectar con proveedores locales de asistencia legal. Es un centro de recursos en línea, no un bufete.',
        address='',
        city='Ann Arbor',
        phone='',
        email='',
        website='https://michiganlegalhelp.org',
        eligibility='Open to all Michigan residents seeking civil legal information; direct representation eligibility varies by local legal aid provider.',
        eligibility_es='Abierto a todos los residentes de Michigan que buscan información legal civil; la representación directa varía según el proveedor local.',
        notes='Search michiganlegalhelp.org by topic and county; connects to Lakeshore, Legal Aid of Michigan, and regional providers.',
        notes_es='Busque en michiganlegalhelp.org por tema y condado; conecta con Lakeshore, Legal Aid of Michigan y proveedores regionales.',
        hours='Website 24/7',
        tags='statewide|legal-aid|online|housing|self-help',
        services='Legal information guides|Court form assistance|Local legal aid finder|Expungement resources|Benefits legal information',
        county='Washtenaw',
        served_counties='',
        coverage='statewide',
        _source='https://michiganlegalhelp.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Legal Services of South Central Michigan',
        category='legal-aid',
        region='South Central Michigan / 13 counties',
        description='Nonprofit civil legal aid serving low-income residents in 13 south-central Michigan counties including Jackson, Washtenaw, and Lenawee with housing, public benefits, family law, and consumer matters affecting reentry. Jackson office intake at 517-787-8414. Does not handle criminal defense cases.',
        description_es='Asistencia legal civil sin fines de lucro para residentes de bajos ingresos en 13 condados del centro-sur de Michigan incluyendo Jackson, Washtenaw y Lenawee con vivienda, beneficios y derecho familiar que afectan la reinserción. Admisión en Jackson al 517-787-8414. No maneja defensa penal.',
        address='1028 Tisdale Street',
        city='Jackson',
        phone='517-787-8414',
        email='',
        website='https://www.lsscm.org',
        eligibility='Low-income residents in 13-county south-central Michigan service area; income limits apply by federal LSC guidelines.',
        eligibility_es='Residentes de bajos ingresos en el área de 13 condados del centro-sur de Michigan; aplican límites de ingresos federales.',
        notes='Apply online at lsscm.org or call 517-787-8414; serves Jackson, Hillsdale, Lenawee, Livingston, Monroe, and Washtenaw among others.',
        notes_es='Solicite en línea en lsscm.org o llame al 517-787-8414; sirve Jackson, Hillsdale, Lenawee, Livingston, Monroe y Washtenaw entre otros.',
        hours='Intake Monday–Friday business hours',
        tags='jackson|washtenaw|legal-aid|housing|reentry',
        services='Civil legal representation|Eviction defense|Benefits advocacy|Family law assistance|Consumer legal help',
        county='Jackson',
        served_counties='Hillsdale|Jackson|Lenawee|Livingston|Monroe|Washtenaw',
        coverage='multi',
        _source='https://www.lsscm.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Upper Peninsula Legal Services',
        category='legal-aid',
        region='Upper Peninsula / 15 counties',
        description='Nonprofit civil legal aid serving low-income residents across all 15 Upper Peninsula counties with housing, public benefits, family law, and consumer matters affecting rural reentry populations. Marquette office provides centralized intake for UP residents. Does not provide criminal defense representation.',
        description_es='Asistencia legal civil sin fines de lucro para residentes de bajos ingresos en los 15 condados de la Península Superior con vivienda, beneficios y derecho familiar que afectan poblaciones rurales en reinserción. La oficina de Marquette proporciona admisión centralizada. No proporciona defensa penal.',
        address='101 Quincy Street',
        city='Hancock',
        phone='906-482-8768',
        email='',
        website='https://www.upls.org',
        eligibility='Low-income residents in any Upper Peninsula county with qualifying civil legal problems; income limits apply.',
        eligibility_es='Residentes de bajos ingresos en cualquier condado de la Península Superior con problemas legales civiles calificados; aplican límites de ingresos.',
        notes='Call 906-482-8768 or apply online at upls.org; serves all 15 UP counties from Hancock and Marquette offices.',
        notes_es='Llame al 906-482-8768 o solicite en línea en upls.org; sirve los 15 condados UP desde oficinas en Hancock y Marquette.',
        hours='Intake Monday–Friday business hours',
        tags='upper-peninsula|legal-aid|housing|rural|reentry',
        services='Civil legal representation|Eviction defense|Benefits advocacy|Family law assistance|Consumer legal help',
        county='Houghton',
        served_counties='Alger|Baraga|Chippewa|Delta|Dickinson|Gogebic|Houghton|Iron|Keweenaw|Luce|Mackinac|Marquette|Menominee|Ontonagon|Schoolcraft',
        coverage='multi',
        _source='https://www.upls.org', _source_type='nonprofit', _confidence='high',
    )

    # --- SUD treatment ---
    add(
        name='Dawn Farm',
        category='substance-use-treatment',
        region='Ann Arbor / Washtenaw County',
        description='Washtenaw County nonprofit providing residential treatment, outpatient counseling, detox referrals, and recovery housing for individuals with substance use disorders including justice-involved clients referred by courts, MDOC, and community partners. Dawn Farm operates long-term recovery programs with sliding fee scale.',
        description_es='Organización sin fines de lucro del condado Washtenaw con tratamiento residencial, consejería ambulatoria, referencias de desintoxicación y vivienda de recuperación para personas con trastornos por uso de sustancias, incluidos clientes con antecedentes penales referidos por tribunales, MDOC y aliados comunitarios.',
        address='6633 Stony Creek Road',
        city='Ypsilanti',
        phone='734-485-8727',
        email='',
        website='https://www.dawnfarm.org',
        eligibility='Adults with substance use disorders seeking treatment; some programs accept justice-involved referrals; contact for intake assessment.',
        eligibility_es='Adultos con trastornos por uso de sustancias que buscan tratamiento; algunos programas aceptan referencias de personas con antecedentes penales; contacte para evaluación.',
        notes='Call 734-485-8727 for intake; Chapin Street Project provides transitional recovery housing; sliding fee scale available.',
        notes_es='Llame al 734-485-8727 para admisión; Chapin Street Project ofrece vivienda de recuperación transicional; tarifa escalonada disponible.',
        hours='Intake during business hours; residential programs 24/7',
        tags='ann-arbor|washtenaw|substance-use|recovery|reentry',
        services='Residential treatment|Outpatient counseling|Recovery housing|Detox referrals|Sliding fee scale|Court and MDOC referrals',
        county='Washtenaw',
        served_counties='Washtenaw',
        coverage='single',
        _source='https://www.dawnfarm.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Sacred Heart Rehabilitation Center',
        category='substance-use-treatment',
        region='Southeast Michigan / Macomb County',
        description='Licensed substance use treatment provider operating residential and outpatient programs in Richmond and regional outpatient sites serving Macomb, St. Clair, and surrounding counties. Accepts Medicaid and offers services for justice-involved individuals referred by MDOC, courts, and community partners.',
        description_es='Proveedor licenciado de tratamiento de sustancias con programas residenciales y ambulatorios en Richmond y sitios ambulatorios regionales que sirven Macomb, St. Clair y condados circundantes. Acepta Medicaid y ofrece servicios para personas con antecedentes penales referidas por MDOC, tribunales y aliados comunitarios.',
        address='400 Stoddard Road',
        city='Richmond',
        phone='810-966-7800',
        email='',
        website='https://www.sacredheartcenter.com',
        eligibility='Adults with substance use disorders; Medicaid and private insurance accepted; justice-involved referrals accepted per program policy.',
        eligibility_es='Adultos con trastornos por uso de sustancias; acepta Medicaid y seguro privado; referencias de personas con antecedentes penales aceptadas según política del programa.',
        notes='Call 810-966-7800 for intake assessment; multiple outpatient locations in southeast Michigan.',
        notes_es='Llame al 810-966-7800 para evaluación de admisión; múltiples ubicaciones ambulatorias en el sureste de Michigan.',
        hours='Intake Mon–Fri business hours; residential 24/7',
        tags='macomb|substance-use|treatment|Medicaid|reentry',
        services='Residential treatment|Outpatient counseling|Medicaid services|Detox and recovery support|MDOC and court referrals',
        county='Macomb',
        served_counties='Macomb|St. Clair',
        coverage='multi',
        _source='https://www.sacredheartcenter.com', _source_type='nonprofit', _confidence='high',
    )

    # --- Veterans ---
    add(
        name='Michigan Veterans Affairs Agency — Statewide Hotline',
        category='veterans',
        region='Statewide',
        description='State agency connecting Michigan veterans and their families to federal VA benefits, state veteran benefits, employment resources, and county veteran service officers. MVAA navigators assist justice-involved veterans with discharge upgrades, VA healthcare enrollment, and housing referrals. A benefits navigation service—not emergency crisis response.',
        description_es='Agencia estatal que conecta a veteranos de Michigan y sus familias con beneficios federales de la VA, beneficios estatales para veteranos, recursos de empleo y oficiales de servicios para veteranos del condado. Los navegadores MVAA ayudan a veteranos con antecedentes penales con inscripción en atención de la VA y referencias de vivienda. Servicio de navegación de beneficios, no respuesta de crisis.',
        address='611 West Ottawa Street',
        city='Lansing',
        phone='800-MICH-VET',
        email='MichiganVeterans@michigan.gov',
        website='https://www.michigan.gov/veterans',
        eligibility='Michigan veterans, active-duty service members, and eligible family members; no criminal-record restrictions for benefits navigation.',
        eligibility_es='Veteranos de Michigan, miembros en servicio activo y familiares elegibles; sin restricciones de antecedentes penales para navegación de beneficios.',
        notes='Call 800-MICH-VET (800-642-4838) or visit michigan.gov/veterans; MVAA connects to county veteran service offices statewide.',
        notes_es='Llame al 800-MICH-VET (800-642-4838) o visite michigan.gov/veterans; MVAA conecta con oficinas de servicios para veteranos del condado.',
        hours='Hotline Mon–Fri business hours',
        tags='statewide|veterans|hotline|VA-benefits|reentry',
        services='VA benefits navigation|State veteran benefits|County VSO referrals|Employment resources|Healthcare enrollment assistance',
        county='Ingham',
        served_counties='',
        coverage='statewide',
        _source='https://www.michigan.gov/veterans', _source_type='government', _confidence='high',
    )
    add(
        name='Wayne County Veterans Services',
        category='veterans',
        region='Detroit / Wayne County',
        description='County veterans service office assisting Wayne County veterans and eligible family members with VA disability claims, healthcare enrollment, emergency financial assistance, and transportation to VA appointments. Serves as local MVAA partner for Detroit-area veterans including those recently released from incarceration.',
        description_es='Oficina de servicios para veteranos del condado que ayuda a veteranos del condado Wayne y familiares elegibles con reclamaciones de discapacidad de la VA, inscripción en atención médica, asistencia financiera de emergencia y transporte a citas de la VA. Aliado local de MVAA para veteranos del área de Detroit, incluidos recién liberados.',
        address='301 West Fort Street, Suite 601',
        city='Detroit',
        phone='313-224-5045',
        email='',
        website='https://www.waynecounty.com/elected/executive/veterans-services.aspx',
        eligibility='Wayne County veterans and eligible dependents; discharge status and income may affect specific benefit programs.',
        eligibility_es='Veteranos del condado Wayne y dependientes elegibles; el estado de baja e ingresos pueden afectar programas específicos de beneficios.',
        notes='Call 313-224-5045 for appointment; bring DD-214 and ID; connects to Detroit VA Medical Center and MVAA statewide resources.',
        notes_es='Llame al 313-224-5045 para cita; traiga DD-214 e identificación; conecta con el Centro Médico VA de Detroit y recursos estatales MVAA.',
        hours='Monday–Friday business hours',
        tags='detroit|wayne|veterans|VA-benefits|county|reentry',
        services='VA disability claims assistance|Healthcare enrollment|Emergency financial aid|VA transportation|Benefits counseling',
        county='Wayne',
        served_counties='Wayne',
        coverage='single',
        _source='https://www.waynecounty.com/elected/executive/veterans-services.aspx', _source_type='government', _confidence='high',
    )

    # --- Transportation ---
    add(
        name='Detroit Department of Transportation (DDOT)',
        category='transportation',
        region='Detroit / Wayne County',
        description='City of Detroit public bus system providing fixed-route and paratransit service across Detroit and connecting to regional transit. Reduced-fare programs assist seniors, persons with disabilities, and low-income Wayne County riders accessing employment, appointments, and reentry services.',
        description_es='Sistema de autobuses públicos de la ciudad de Detroit con servicio de ruta fija y paratransporte en Detroit y conexiones regionales. Programas de tarifa reducida ayudan a personas mayores, con discapacidades y de bajos ingresos del condado Wayne a acceder a empleo, citas y servicios de reinserción.',
        address='1301 E. Warren Avenue',
        city='Detroit',
        phone='313-933-1300',
        email='',
        website='https://www.detroitmi.gov/departments/detroit-department-of-transportation',
        eligibility='Open to all riders; reduced-fare eligibility for seniors, disabled riders, and qualifying low-income residents.',
        eligibility_es='Abierto a todos los pasajeros; elegibilidad de tarifa reducida para personas mayores, con discapacidades y residentes de bajos ingresos calificados.',
        notes='Call 313-933-1300 for routes and reduced-fare application; DDOT connects to SMART regional bus service in Wayne County suburbs.',
        notes_es='Llame al 313-933-1300 para rutas y solicitud de tarifa reducida; DDOT conecta con autobuses regionales SMART en suburbios del condado Wayne.',
        hours='Bus service daily; customer service Mon–Fri business hours',
        tags='detroit|wayne|transportation|transit|reduced-fare|reentry',
        services='Fixed-route bus service|Paratransit|Reduced-fare programs|Route planning|Regional transit connections',
        county='Wayne',
        served_counties='Wayne',
        coverage='single',
        _source='https://www.detroitmi.gov/departments/detroit-department-of-transportation', _source_type='government', _confidence='high',
    )
    add(
        name='The Rapid — Grand Rapids Public Transit',
        category='transportation',
        region='Grand Rapids / Kent County',
        description='Grand Rapids area public transit authority operating fixed-route buses, dial-a-ride, and reduced-fare programs for Kent County riders including returning citizens accessing employment, treatment, and probation reporting. The Rapid connects to Michigan Works! and reentry service locations.',
        description_es='Autoridad de tránsito público del área de Grand Rapids con autobuses de ruta fija, servicio dial-a-ride y programas de tarifa reducida para pasajeros del condado Kent, incluidos ciudadanos que regresan que acceden a empleo, tratamiento y reportes de libertad condicional.',
        address='300 Ellsworth Avenue SW',
        city='Grand Rapids',
        phone='616-776-1100',
        email='',
        website='https://www.ridetherapid.org',
        eligibility='Open to all riders; reduced-fare and ADA paratransit available for eligible Kent County residents.',
        eligibility_es='Abierto a todos los pasajeros; tarifa reducida y paratransporte ADA disponibles para residentes elegibles del condado Kent.',
        notes='Call 616-776-1100 or use ridetherapid.org trip planner; reduced-fare cards available at Rapid Central Station.',
        notes_es='Llame al 616-776-1100 o use el planificador de viajes en ridetherapid.org; tarjetas de tarifa reducida disponibles en Rapid Central Station.',
        hours='Bus service daily; customer service Mon–Fri business hours',
        tags='grand-rapids|kent|transportation|transit|reduced-fare|reentry',
        services='Fixed-route bus service|Dial-a-ride|Reduced-fare programs|Trip planning|ADA paratransit',
        county='Kent',
        served_counties='Kent',
        coverage='single',
        _source='https://www.ridetherapid.org', _source_type='government', _confidence='high',
    )
    add(
        name='Capital Area Transportation Authority (CATA)',
        category='transportation',
        region='Lansing / Ingham County',
        description='Lansing-area public transit providing fixed-route bus service and paratransit across Ingham County including routes to Michigan Works!, MDHHS offices, and treatment providers. Reduced-fare programs assist eligible low-income riders accessing employment and reentry appointments.',
        description_es='Tránsito público del área de Lansing con servicio de autobús de ruta fija y paratransporte en el condado Ingham incluyendo rutas a Michigan Works!, oficinas MDHHS y proveedores de tratamiento. Programas de tarifa reducida ayudan a pasajeros elegibles de bajos ingresos.',
        address='4615 Tranter Street',
        city='Lansing',
        phone='517-394-1000',
        email='',
        website='https://www.cata.org',
        eligibility='Open to all riders; reduced-fare eligibility for seniors, students, and qualifying low-income residents.',
        eligibility_es='Abierto a todos los pasajeros; elegibilidad de tarifa reducida para personas mayores, estudiantes y residentes de bajos ingresos calificados.',
        notes='Call 517-394-1000 for routes and reduced-fare application; CATA serves Lansing, East Lansing, and Meridian Township.',
        notes_es='Llame al 517-394-1000 para rutas y solicitud de tarifa reducida; CATA sirve Lansing, East Lansing y Meridian Township.',
        hours='Bus service daily; customer service Mon–Fri business hours',
        tags='lansing|ingham|transportation|transit|reduced-fare|reentry',
        services='Fixed-route bus service|Paratransit|Reduced-fare programs|Route planning|Regional connections',
        county='Ingham',
        served_counties='Ingham',
        coverage='single',
        _source='https://www.cata.org', _source_type='government', _confidence='high',
    )

    # --- Peer support ---
    add(
        name='Michigan Association of Recovery Community Organizations (MARCO)',
        category='peer-support',
        region='Statewide',
        description='Statewide nonprofit association connecting Michigan residents to certified Recovery Community Organizations providing peer-led, non-clinical recovery support services. MARCO\'s interactive map helps returning citizens and families locate local peer support, mutual aid groups, and recovery coaching by county.',
        description_es='Asociación sin fines de lucro estatal que conecta a residentes de Michigan con Organizaciones Comunitarias de Recuperación certificadas que ofrecen servicios de apoyo de recuperación liderados por pares. El mapa interactivo de MARCO ayuda a ciudadanos que regresan y familias a localizar apoyo entre pares y coaching de recuperación por condado.',
        address='',
        city='Lansing',
        phone='',
        email='',
        website='https://michiganarco.org',
        eligibility='Open to Michigan residents seeking peer recovery support; individual RCO programs may have specific eligibility.',
        eligibility_es='Abierto a residentes de Michigan que buscan apoyo de recuperación entre pares; los programas RCO individuales pueden tener elegibilidad específica.',
        notes='Use michiganarco.org recovery community map to find local RCOs; peer support complements clinical treatment and MDOC reentry services.',
        notes_es='Use el mapa de comunidades de recuperación en michiganarco.org para encontrar RCOs locales; el apoyo entre pares complementa tratamiento clínico y servicios de reinserción del MDOC.',
        hours='Online map 24/7; RCO hours vary by location',
        tags='statewide|peer-support|recovery|RCO|referral-only',
        services='Recovery community organization locator|Peer support referrals|Mutual aid group connections|Recovery coaching navigation',
        county='Ingham',
        served_counties='',
        coverage='statewide',
        _source='https://michiganarco.org', _source_type='nonprofit', _confidence='high',
    )

    # --- Education ---
    add(
        name='Michigan Adult Education — GED & High School Equivalency',
        category='education',
        region='Statewide',
        description='State resource through the Michigan Department of Labor and Economic Opportunity connecting adults including returning citizens to GED and high school equivalency preparation at local adult education programs statewide. MiTalent.org lists adult education providers by county for credential rebuilding after incarceration.',
        description_es='Recurso estatal a través del Departamento de Trabajo y Oportunidad Económica de Michigan que conecta a adultos, incluidos ciudadanos que regresan, con preparación para GED y equivalencia de escuela secundaria en programas locales de educación para adultos. MiTalent.org lista proveedores por condado.',
        address='',
        city='Lansing',
        phone='517-335-5858',
        email='',
        website='https://www.michigan.gov/leo/bureau-services/michigan-adult-education',
        eligibility='Michigan adults age 18 and older seeking GED or high school equivalency; criminal record not a stated barrier.',
        eligibility_es='Adultos de Michigan de 18 años o más que buscan GED o equivalencia de escuela secundaria; antecedentes penales no son barrera indicada.',
        notes='Search adult education providers at michigan.gov/leo or mitalent.org; MDOC offers GED preparation in facilities; community programs assist after release.',
        notes_es='Busque proveedores de educación para adultos en michigan.gov/leo o mitalent.org; el MDOC ofrece preparación GED en instalaciones; programas comunitarios ayudan después de la liberación.',
        hours='Provider hours vary by location',
        tags='statewide|education|GED|adult-education|reentry',
        services='GED preparation|High school equivalency|Adult education provider locator|Workforce credential pathways',
        county='Ingham',
        served_counties='',
        coverage='statewide',
        _source='https://www.michigan.gov/leo/bureau-services/michigan-adult-education', _source_type='government', _confidence='high',
    )

    # --- Basic needs ---
    add(
        name='The Salvation Army — Eastern Michigan Division',
        category='basic-needs',
        region='Southeast Michigan',
        description='Regional Salvation Army division providing emergency shelter, food assistance, utility aid, and disaster relief across southeast Michigan including Wayne, Oakland, and Macomb counties. Returning citizens can access corps community centers for meals, clothing, and case management referrals.',
        description_es='División regional de Salvation Army con refugio de emergencia, asistencia alimentaria, ayuda con servicios públicos y alivio en desastres en el sureste de Michigan incluyendo los condados Wayne, Oakland y Macomb. Ciudadanos que regresan pueden acceder a centros comunitarios para comidas, ropa y referencias de manejo de casos.',
        address='16130 Northland Drive',
        city='Southfield',
        phone='877-SAL-ARMY',
        email='',
        website='https://centralusa.salvationarmy.org/eastern-michigan',
        eligibility='Open to residents in need of emergency assistance; program eligibility varies by location and service type.',
        eligibility_es='Abierto a residentes que necesitan asistencia de emergencia; la elegibilidad del programa varía según ubicación y tipo de servicio.',
        notes='Call 877-SAL-ARMY (877-725-2769) or locate nearest corps at eastern-michigan Salvation Army website; services vary by location.',
        notes_es='Llame al 877-SAL-ARMY (877-725-2769) o localice el cuerpo más cercano en el sitio web de Salvation Army; los servicios varían.',
        hours='Corps hours vary; emergency services as available',
        tags='detroit|wayne|oakland|macomb|basic-needs|salvation-army|reentry',
        services='Emergency shelter|Food assistance|Utility aid|Clothing|Case management referrals|Disaster relief',
        county='Oakland',
        served_counties='Wayne|Oakland|Macomb|Livingston|Monroe',
        coverage='multi',
        _source='https://centralusa.salvationarmy.org/eastern-michigan', _source_type='nonprofit', _confidence='high',
    )

    # --- Probation / parole field offices ---
    add(
        name='MDOC Field Operations — Region 10 Detroit Metro Parole',
        category='probation-parole',
        region='Metro Detroit / Wayne County',
        description='Michigan Department of Corrections Region 10 West District parole office supervising parolees in Detroit and Wayne County. Parole agents connect supervisees to MDOC Offender Success services, DWIHN behavioral health providers, and local reentry partners. Contact for reporting requirements—not a general resource navigation hotline.',
        description_es='Oficina de libertad condicional del Distrito Oeste de la Región 10 del MDOC que supervisa personas en libertad condicional en Detroit y el condado Wayne. Los agentes conectan a supervisados con servicios Offender Success del MDOC, proveedores de salud conductual DWIHN y aliados locales de reinserción. Contacte para requisitos de reporte, no es una línea de navegación general.',
        address='3048 West Grand Boulevard, Suite 4-400',
        city='Detroit',
        phone='313-456-1000',
        email='',
        website='https://www.michigan.gov/corrections/parole-probation/office-directory/region-10',
        eligibility='Individuals under Michigan parole supervision in Wayne County; family members may contact for general office information.',
        eligibility_es='Personas bajo supervisión de libertad condicional de Michigan en el condado Wayne; familiares pueden contactar para información general de la oficina.',
        notes='See michigan.gov/corrections parole office directory for all Region 10 offices including Pontiac and Troy; report to assigned agent as directed.',
        notes_es='Consulte el directorio de oficinas de libertad condicional en michigan.gov/corrections para todas las oficinas de la Región 10 incluyendo Pontiac y Troy.',
        hours='Monday–Friday business hours',
        tags='detroit|wayne|parole|probation|MDOC|supervision',
        services='Parole supervision|Offender Success referrals|Reporting compliance|Behavioral health coordination|Employment partner connections',
        county='Wayne',
        served_counties='Wayne',
        coverage='single',
        _source='https://www.michigan.gov/corrections/parole-probation/office-directory/region-10', _source_type='government', _confidence='high',
    )
    add(
        name='MDOC Field Operations — Region 10 Pontiac Parole',
        category='probation-parole',
        region='Metro Detroit / Oakland County',
        description='MDOC Region 10 Northwest District parole office supervising parolees in Oakland and Macomb counties from Pontiac. Parole agents coordinate Offender Success administrative agency referrals through HMSA and connect supervisees to housing, employment, and treatment partners in the metro Detroit suburbs.',
        description_es='Oficina de libertad condicional del Distrito Noroeste de la Región 10 del MDOC que supervisa personas en libertad condicional en los condados Oakland y Macomb desde Pontiac. Los agentes coordinan referencias de agencias administrativas Offender Success a través de HMSA y conectan supervisados con aliados de vivienda, empleo y tratamiento.',
        address='235 North Saginaw Street, Suite 100',
        city='Pontiac',
        phone='248-253-2440',
        email='',
        website='https://www.michigan.gov/corrections/parole-probation/office-directory/region-10',
        eligibility='Individuals under Michigan parole supervision in Oakland or Macomb counties; contact assigned agent for reporting instructions.',
        eligibility_es='Personas bajo supervisión de libertad condicional de Michigan en los condados Oakland o Macomb; contacte al agente asignado para instrucciones de reporte.',
        notes='Northwest Operations Office at 1200 N. Telegraph Road Building 26 serves related probation functions; verify assigned office with agent.',
        notes_es='La Oficina de Operaciones del Noroeste en 1200 N. Telegraph Road Edificio 26 sirve funciones de libertad probatoria relacionadas; verifique la oficina asignada con el agente.',
        hours='Monday–Friday business hours',
        tags='pontiac|oakland|macomb|parole|probation|MDOC|supervision',
        services='Parole supervision|HMSA Offender Success referrals|Reporting compliance|Treatment coordination|Employment partner connections',
        county='Oakland',
        served_counties='Oakland|Macomb',
        coverage='multi',
        _source='https://www.michigan.gov/corrections/parole-probation/office-directory/region-10', _source_type='government', _confidence='high',
    )
    add(
        name='MDOC Field Operations — Region 4 Grand Rapids',
        category='probation-parole',
        region='West Michigan / Kent County',
        description='MDOC Region 4 parole and probation office supervising community corrections cases in Kent and surrounding West Michigan counties. Agents connect supervisees to Michigan Works! West Central Offender Success services, treatment providers, and local reentry partners. Contact for reporting requirements—not emergency services.',
        description_es='Oficina de libertad condicional y probatoria de la Región 4 del MDOC que supervisa casos de correcciones comunitarias en Kent y condados circundantes del oeste de Michigan. Los agentes conectan supervisados con servicios Offender Success de Michigan Works! West Central y aliados locales de reinserción. Contacte para requisitos de reporte, no servicios de emergencia.',
        address='678 Front Avenue NW',
        city='Grand Rapids',
        phone='616-356-0700',
        email='',
        website='https://www.michigan.gov/corrections/parole-probation/office-directory/region-4',
        eligibility='Individuals under Michigan parole or probation supervision in Region 4 counties; contact assigned agent for reporting.',
        eligibility_es='Personas bajo supervisión de libertad condicional o probatoria de Michigan en condados de la Región 4; contacte al agente asignado para reporte.',
        notes='Region 4 serves Allegan, Barry, Ionia, Kent, Lake, Mason, Mecosta, Montcalm, Muskegon, Newaygo, Oceana, Osceola, and Ottawa counties.',
        notes_es='La Región 4 sirve los condados Allegan, Barry, Ionia, Kent, Lake, Mason, Mecosta, Montcalm, Muskegon, Newaygo, Oceana, Osceola y Ottawa.',
        hours='Monday–Friday business hours',
        tags='grand-rapids|kent|parole|probation|MDOC|supervision',
        services='Parole and probation supervision|Offender Success referrals|Reporting compliance|Treatment coordination|Workforce partner connections',
        county='Kent',
        served_counties='Kent',
        coverage='single',
        _source='https://www.michigan.gov/corrections/parole-probation/office-directory/region-4', _source_type='government', _confidence='high',
    )

    # --- ID documentation (branch locator supplement to phase 1 statewide) ---
    add(
        name='Michigan Secretary of State — Branch Office Locator',
        category='id-documentation',
        region='Statewide',
        description='Official statewide branch locator for Michigan Secretary of State offices issuing state ID cards, driver\'s licenses, and vehicle registration. Returning citizens use branch offices to obtain identification needed for employment, MI Bridges benefits, and housing applications. Online appointment scheduling available at michigan.gov/sos.',
        description_es='Localizador oficial estatal de oficinas del Secretario de Estado de Michigan que emiten tarjetas de identificación estatal, licencias de conducir y registro de vehículos. Ciudadanos que regresan usan las oficinas para obtener identificación necesaria para empleo, beneficios MI Bridges y solicitudes de vivienda. Citas en línea disponibles en michigan.gov/sos.',
        address='',
        city='Lansing',
        phone='888-SOS-MICH',
        email='',
        website='https://www.michigan.gov/sos/all-services/branch-office-locator',
        eligibility='Michigan residents seeking state ID or driver\'s license; specific document requirements apply; MDOC reentry partners assist with vital records.',
        eligibility_es='Residentes de Michigan que buscan identificación estatal o licencia de conducir; aplican requisitos específicos de documentos; aliados de reinserción del MDOC ayudan con registros vitales.',
        notes='Call 888-SOS-MICH (888-767-6424) or schedule at michigan.gov/sos; bring proof of identity and residency; some transactions available online.',
        notes_es='Llame al 888-SOS-MICH (888-767-6424) o programe cita en michigan.gov/sos; traiga prueba de identidad y residencia; algunas transacciones disponibles en línea.',
        hours='Branch hours vary by location; online services 24/7',
        tags='statewide|id-documentation|drivers-license|SOS|online',
        services='State ID issuance|Driver\'s license services|Branch office locator|Online appointment scheduling|Document requirement information',
        county='Ingham',
        served_counties='',
        coverage='statewide',
        _source='https://www.michigan.gov/sos/all-services/branch-office-locator', _source_type='government', _confidence='high',
    )

    # --- Reentry direct-service CBOs (limited: 2 of ≤4 max) ---
    add(
        name='Goodwill Industries of Greater Detroit — Flip the Script',
        category='reentry-organizations',
        region='Detroit / Wayne County',
        description='Detroit workforce and reentry program connecting justice-involved Wayne County residents to employment training, job placement, and wraparound support through the Flip the Script reentry initiative. Goodwill partners with MDOC Offender Success and local employers for fair-chance hiring pathways.',
        description_es='Programa de fuerza laboral y reinserción de Detroit que conecta a residentes del condado Wayne con antecedentes penales a capacitación laboral, colocación de empleo y apoyo integral a través de la iniciativa de reinserción Flip the Script. Goodwill se asocia con Offender Success del MDOC y empleadores locales para contratación justa.',
        address='3111 Grand River Avenue',
        city='Detroit',
        phone='313-557-5000',
        email='',
        website='https://www.goodwilldetroit.org',
        eligibility='Wayne County residents with criminal records seeking employment and reentry support; contact for intake requirements.',
        eligibility_es='Residentes del condado Wayne con antecedentes penales que buscan empleo y apoyo de reinserción; contacte para requisitos de admisión.',
        notes='Call 313-557-5000 for Flip the Script and workforce program intake; multiple Goodwill service centers in metro Detroit.',
        notes_es='Llame al 313-557-5000 para admisión a Flip the Script y programas de fuerza laboral; múltiples centros Goodwill en el metro de Detroit.',
        hours='Monday–Friday business hours',
        tags='detroit|wayne|reentry|employment|fair-chance|Flip-the-Script',
        services='Reentry employment training|Job placement|Flip the Script program|Employer partnerships|Wraparound support',
        county='Wayne',
        served_counties='Wayne',
        coverage='single',
        _source='https://www.goodwilldetroit.org', _source_type='nonprofit', _confidence='high',
    )
    add(
        name='Hope Network — Recovery & Reentry Behavioral Health',
        category='reentry-organizations',
        region='Grand Rapids / Kent County',
        description='West Michigan behavioral health provider offering outpatient substance use treatment, recovery support, and community reintegration services for justice-involved individuals in Kent County. Hope Network partners with MDOC, courts, and Michigan Works! West Central for coordinated reentry care.',
        description_es='Proveedor de salud conductual del oeste de Michigan con tratamiento ambulatorio de sustancias, apoyo de recuperación y servicios de reintegración comunitaria para personas con antecedentes penales en el condado Kent. Hope Network se asocia con MDOC, tribunales y Michigan Works! West Central.',
        address='3355 East Beltline Avenue NE',
        city='Grand Rapids',
        phone='800-394-4673',
        email='',
        website='https://www.hopenetwork.org',
        eligibility='Adults with behavioral health or substance use needs; accepts Medicaid; justice-involved referrals accepted per program.',
        eligibility_es='Adultos con necesidades de salud conductual o uso de sustancias; acepta Medicaid; referencias de personas con antecedentes penales aceptadas según programa.',
        notes='Call 800-394-4673 for intake; multiple West Michigan locations; coordinates with parole agents and Offender Success providers.',
        notes_es='Llame al 800-394-4673 para admisión; múltiples ubicaciones en el oeste de Michigan; coordina con agentes de libertad condicional y proveedores Offender Success.',
        hours='Intake Mon–Fri business hours; crisis line 24/7',
        tags='grand-rapids|kent|reentry|behavioral-health|recovery',
        services='Outpatient substance use treatment|Recovery support|Community reintegration|Medicaid behavioral health|MDOC partner referrals',
        county='Kent',
        served_counties='Kent',
        coverage='single',
        _source='https://www.hopenetwork.org', _source_type='nonprofit', _confidence='high',
    )
