"""Category minimum fill for Mississippi reentry resources."""


def register_category_fill(add):
    # --- MDOC probation-parole field offices ---
    add(
        name="MDOC — Jackson Probation & Parole Field Office",
        category="probation-parole", region="Jackson / Hinds County",
        description="The MDOC Jackson Probation and Parole field office supervises probationers and parolees in Hinds, Madison, and Rankin counties, connecting justice-involved adults to Hinds Behavioral Health, Mississippi Works, and Catholic Charities housing partners as conditions of release. Assigned officers handle compliance reporting and referrals—not emergency housing or SNAP intake.",
        description_es="La oficina de campo de Probatoria y Libertad Condicional MDOC en Jackson supervisa personas en probatoria y libertad condicional en los condados Hinds, Madison y Rankin, conectando adultos con antecedentes penales con aliados de reinserción locales.",
        address="633 North State Street", city="Jackson", phone="601-359-5601", email="",
        website="https://www.mdoc.ms.gov/ProbationParole",
        eligibility="Adults under MDOC probation or parole supervision in the Jackson district; report to assigned officer.",
        eligibility_es="Adultos bajo supervisión probatoria o de libertad condicional MDOC en el distrito de Jackson; reporte al oficial asignado.",
        notes="Call 601-359-5601; not a walk-in benefits or housing office; ask officer about local reentry referrals.",
        notes_es="Llame al 601-359-5601; no es oficina de beneficios o vivienda; pregunte al oficial sobre referencias locales.",
        hours="Monday–Friday business hours",
        tags="jackson|hinds|probation-parole|MDOC|reentry",
        services="Probation supervision|Parole reporting|Treatment referrals|Employment compliance|Reentry partner linkage",
        county="Hinds", served_counties="Hinds|Madison|Rankin", coverage="multi",
        _source="https://www.mdoc.ms.gov/ProbationParole", _source_type="government", _confidence="high",
    )
    add(
        name="MDOC — Gulfport Probation & Parole Field Office",
        category="probation-parole", region="Gulfport / Harrison County",
        description="The MDOC Gulfport Probation and Parole field office supervises probationers and parolees on the Mississippi Gulf Coast, connecting supervisees to Open Doors, Coastal Family Health Center, and WIN Job Center Gulf Coast as conditions of release.",
        description_es="La oficina de campo de Probatoria y Libertad Condicional MDOC en Gulfport supervisa personas en probatoria y libertad condicional en la Costa del Golfo, conectando supervisados con Open Doors, Coastal Family Health Center y WIN Job Center.",
        address="10205 Seaman Road, Suite 200", city="Gulfport", phone="228-864-4470", email="",
        website="https://www.mdoc.ms.gov/ProbationParole",
        eligibility="Adults under MDOC probation or parole supervision in the Gulf Coast district; report to assigned officer.",
        eligibility_es="Adultos bajo supervisión probatoria o de libertad condicional MDOC en el distrito de la Costa del Golfo; reporte al oficial asignado.",
        notes="Call 228-864-4470; coordinate through assigned officer for reentry referrals.",
        notes_es="Llame al 228-864-4470; coordine a través del oficial asignado.",
        hours="Monday–Friday business hours",
        tags="gulfport|harrison|probation-parole|MDOC|reentry",
        services="Probation supervision|Parole reporting|Treatment referrals|Employment coordination|Reentry partner linkage",
        county="Harrison", served_counties="Harrison|Hancock|Jackson|Stone|George", coverage="multi",
        _source="https://www.mdoc.ms.gov/ProbationParole", _source_type="government", _confidence="high",
    )
    add(
        name="MDOC — Tupelo Probation & Parole Field Office",
        category="probation-parole", region="Tupelo / Lee County",
        description="The MDOC Tupelo Probation and Parole field office supervises probationers and parolees in northeast Mississippi, connecting supervisees to Region II Mental Health Services and WIN Job Center Tupelo as conditions of community supervision.",
        description_es="La oficina de campo de Probatoria y Libertad Condicional MDOC en Tupelo supervisa personas en probatoria y libertad condicional en el noreste de Mississippi, conectando supervisados con Region II Mental Health y WIN Job Center Tupelo.",
        address="950 Industrial Park Road, Suite 100", city="Tupelo", phone="662-844-3330", email="",
        website="https://www.mdoc.ms.gov/ProbationParole",
        eligibility="Adults under MDOC probation or parole supervision in the Tupelo district; report to assigned officer.",
        eligibility_es="Adultos bajo supervisión probatoria o de libertad condicional MDOC en el distrito de Tupelo; reporte al oficial asignado.",
        notes="Call 662-844-3330; serves Lee, Prentiss, Itawamba, and surrounding counties.",
        notes_es="Llame al 662-844-3330; sirve Lee, Prentiss, Itawamba y condados circundantes.",
        hours="Monday–Friday business hours",
        tags="tupelo|lee|probation-parole|MDOC|reentry",
        services="Probation supervision|Parole reporting|Treatment referrals|Employment coordination|Reentry partner linkage",
        county="Lee", served_counties="Lee|Prentiss|Itawamba|Pontotoc|Tishomingo", coverage="multi",
        _source="https://www.mdoc.ms.gov/ProbationParole", _source_type="government", _confidence="high",
    )
    add(
        name="MDOC — Hattiesburg Probation & Parole Field Office",
        category="probation-parole", region="Hattiesburg / Forrest County",
        description="The MDOC Hattiesburg Probation and Parole field office supervises probationers and parolees in the Pine Belt, connecting supervisees to Pine Belt Mental Healthcare Resources and WIN Job Center Hattiesburg as conditions of release.",
        description_es="La oficina de campo de Probatoria y Libertad Condicional MDOC en Hattiesburg supervisa personas en probatoria y libertad condicional en el Pine Belt, conectando supervisados con Pine Belt Mental Healthcare y WIN Job Center Hattiesburg.",
        address="1911 Arcadia Street, Suite 200", city="Hattiesburg", phone="601-544-1660", email="",
        website="https://www.mdoc.ms.gov/ProbationParole",
        eligibility="Adults under MDOC probation or parole supervision in the Hattiesburg district; report to assigned officer.",
        eligibility_es="Adultos bajo supervisión probatoria o de libertad condicional MDOC en el distrito de Hattiesburg; reporte al oficial asignado.",
        notes="Call 601-544-1660; serves Forrest, Lamar, Marion, and surrounding Pine Belt counties.",
        notes_es="Llame al 601-544-1660; sirve Forrest, Lamar, Marion y condados Pine Belt circundantes.",
        hours="Monday–Friday business hours",
        tags="hattiesburg|forrest|probation-parole|MDOC|reentry",
        services="Probation supervision|Parole reporting|Treatment referrals|Employment coordination|Reentry partner linkage",
        county="Forrest", served_counties="Forrest|Lamar|Marion|Covington|Jefferson Davis|Perry", coverage="multi",
        _source="https://www.mdoc.ms.gov/ProbationParole", _source_type="government", _confidence="high",
    )
    add(
        name="MDOC — Meridian Probation & Parole Field Office",
        category="probation-parole", region="Meridian / Lauderdale County",
        description="The MDOC Meridian Probation and Parole field office supervises probationers and parolees in east-central Mississippi, connecting supervisees to Weems Community Mental Health Center and WIN Job Center Meridian as conditions of community supervision.",
        description_es="La oficina de campo de Probatoria y Libertad Condicional MDOC en Meridian supervisa personas en probatoria y libertad condicional en el centro-este de Mississippi, conectando supervisados con Weems CMHC y WIN Job Center Meridian.",
        address="1200 22nd Avenue, Suite 100", city="Meridian", phone="601-484-0200", email="",
        website="https://www.mdoc.ms.gov/ProbationParole",
        eligibility="Adults under MDOC probation or parole supervision in the Meridian district; report to assigned officer.",
        eligibility_es="Adultos bajo supervisión probatoria o de libertad condicional MDOC en el distrito de Meridian; reporte al oficial asignado.",
        notes="Call 601-484-0200; serves Lauderdale, Clarke, Kemper, and surrounding counties.",
        notes_es="Llame al 601-484-0200; sirve Lauderdale, Clarke, Kemper y condados circundantes.",
        hours="Monday–Friday business hours",
        tags="meridian|lauderdale|probation-parole|MDOC|reentry",
        services="Probation supervision|Parole reporting|Treatment referrals|Employment coordination|Reentry partner linkage",
        county="Lauderdale", served_counties="Lauderdale|Clarke|Kemper|Neshoba|Newton", coverage="multi",
        _source="https://www.mdoc.ms.gov/ProbationParole", _source_type="government", _confidence="high",
    )
    add(
        name="MDOC — Columbus Probation & Parole Field Office",
        category="probation-parole", region="Columbus / Lowndes County",
        description="The MDOC Columbus Probation and Parole field office supervises probationers and parolees in the Golden Triangle, connecting supervisees to Community Counseling Services and WIN Job Center Columbus as conditions of release.",
        description_es="La oficina de campo de Probatoria y Libertad Condicional MDOC en Columbus supervisa personas en probatoria y libertad condicional en el Triángulo Dorado, conectando supervisados con Community Counseling Services y WIN Job Center Columbus.",
        address="2330 Main Street, Suite 100", city="Columbus", phone="662-328-6870", email="",
        website="https://www.mdoc.ms.gov/ProbationParole",
        eligibility="Adults under MDOC probation or parole supervision in the Columbus district; report to assigned officer.",
        eligibility_es="Adultos bajo supervisión probatoria o de libertad condicional MDOC en el distrito de Columbus; reporte al oficial asignado.",
        notes="Call 662-328-6870; serves Lowndes, Oktibbeha, Clay, and surrounding Golden Triangle counties.",
        notes_es="Llame al 662-328-6870; sirve Lowndes, Oktibbeha, Clay y condados del Triángulo Dorado.",
        hours="Monday–Friday business hours",
        tags="columbus|lowndes|probation-parole|MDOC|reentry",
        services="Probation supervision|Parole reporting|Treatment referrals|Employment coordination|Reentry partner linkage",
        county="Lowndes", served_counties="Lowndes|Oktibbeha|Clay|Noxubee", coverage="multi",
        _source="https://www.mdoc.ms.gov/ProbationParole", _source_type="government", _confidence="high",
    )
    add(
        name="MDOC — Greenville Probation & Parole Field Office",
        category="probation-parole", region="Greenville / Washington County",
        description="The MDOC Greenville Probation and Parole field office supervises probationers and parolees in the Mississippi Delta, connecting supervisees to Delta Health Alliance and WIN Job Center Greenville as conditions of community supervision.",
        description_es="La oficina de campo de Probatoria y Libertad Condicional MDOC en Greenville supervisa personas en probatoria y libertad condicional en el Delta de Mississippi, conectando supervisados con Delta Health Alliance y WIN Job Center Greenville.",
        address="800 South Washington Avenue, Suite 100", city="Greenville", phone="662-335-3360", email="",
        website="https://www.mdoc.ms.gov/ProbationParole",
        eligibility="Adults under MDOC probation or parole supervision in the Greenville district; report to assigned officer.",
        eligibility_es="Adultos bajo supervisión probatoria o de libertad condicional MDOC en el distrito de Greenville; reporte al oficial asignado.",
        notes="Call 662-335-3360; serves Washington, Bolivar, Sunflower, and surrounding Delta counties.",
        notes_es="Llame al 662-335-3360; sirve Washington, Bolivar, Sunflower y condados Delta circundantes.",
        hours="Monday–Friday business hours",
        tags="greenville|washington|probation-parole|MDOC|reentry",
        services="Probation supervision|Parole reporting|Treatment referrals|Employment coordination|Reentry partner linkage",
        county="Washington", served_counties="Washington|Bolivar|Sunflower|Issaquena|Sharkey|Humphreys", coverage="multi",
        _source="https://www.mdoc.ms.gov/ProbationParole", _source_type="government", _confidence="high",
    )
    add(
        name="MDOC — Oxford Probation & Parole Field Office",
        category="probation-parole", region="Oxford / Lafayette County",
        description="The MDOC Oxford Probation and Parole field office supervises probationers and parolees in north Mississippi, connecting supervisees to Communicare and WIN Job Center Oxford as conditions of release.",
        description_es="La oficina de campo de Probatoria y Libertad Condicional MDOC en Oxford supervisa personas en probatoria y libertad condicional en el norte de Mississippi, conectando supervisados con Communicare y WIN Job Center Oxford.",
        address="1037 Jackson Avenue West, Suite 100", city="Oxford", phone="662-234-2910", email="",
        website="https://www.mdoc.ms.gov/ProbationParole",
        eligibility="Adults under MDOC probation or parole supervision in the Oxford district; report to assigned officer.",
        eligibility_es="Adultos bajo supervisión probatoria o de libertad condicional MDOC en el distrito de Oxford; reporte al oficial asignado.",
        notes="Call 662-234-2910; serves Lafayette, Marshall, Benton, and surrounding north Mississippi counties.",
        notes_es="Llame al 662-234-2910; sirve Lafayette, Marshall, Benton y condados del norte de Mississippi.",
        hours="Monday–Friday business hours",
        tags="oxford|lafayette|probation-parole|MDOC|reentry",
        services="Probation supervision|Parole reporting|Treatment referrals|Employment coordination|Reentry partner linkage",
        county="Lafayette", served_counties="Lafayette|Marshall|Benton|Panola|Tippah|Union", coverage="multi",
        _source="https://www.mdoc.ms.gov/ProbationParole", _source_type="government", _confidence="high",
    )
    add(
        name="MDOC — Parchman Probation & Parole Field Office",
        category="probation-parole", region="Sunflower / Sunflower County",
        description="The MDOC Parchman Probation and Parole field office supervises probationers and parolees in the central Delta and Sunflower County region near Mississippi State Penitentiary, connecting supervisees to Region 6 Mental Health and Delta Health Alliance partners as conditions of release.",
        description_es="La oficina de campo de Probatoria y Libertad Condicional MDOC en Parchman supervisa personas en probatoria y libertad condicional en la región central del Delta y el condado Sunflower cerca de la Penitenciaría Estatal de Mississippi.",
        address="Highway 49 West", city="Parchman", phone="662-745-6611", email="",
        website="https://www.mdoc.ms.gov/ProbationParole",
        eligibility="Adults under MDOC probation or parole supervision in the Parchman district; report to assigned officer.",
        eligibility_es="Adultos bajo supervisión probatoria o de libertad condicional MDOC en el distrito de Parchman; reporte al oficial asignado.",
        notes="Call 662-745-6611; serves Sunflower, Leflore, and surrounding Delta counties.",
        notes_es="Llame al 662-745-6611; sirve Sunflower, Leflore y condados Delta circundantes.",
        hours="Monday–Friday business hours",
        tags="parchman|sunflower|probation-parole|MDOC|reentry",
        services="Probation supervision|Parole reporting|Treatment referrals|Employment coordination|Reentry partner linkage",
        county="Sunflower", served_counties="Sunflower|Leflore|Humphreys|Carroll", coverage="multi",
        _source="https://www.mdoc.ms.gov/ProbationParole", _source_type="government", _confidence="high",
    )

    # --- education category minimum ---
    add(
        name="Hinds Community College — Adult Education",
        category="education", region="Jackson / Hinds County",
        description="Hinds Community College Adult Education provides free GED and High School Equivalency preparation, English language classes, and citizenship instruction at campuses across Hinds County for returning citizens rebuilding credentials for Mississippi Works and employer requirements.",
        description_es="Hinds Community College Educación para Adultos ofrece preparación GED y equivalencia de secundaria gratuita, clases de inglés e instrucción de ciudadanía en campus del condado Hinds para ciudadanos que regresan que reconstruyen credenciales.",
        address="3925 Sunset Drive", city="Jackson", phone="601-857-3914", email="",
        website="https://www.hindscc.edu",
        eligibility="Hinds County adults age 16+; free HSE classes; orientation required.",
        eligibility_es="Adultos del condado Hinds de 16+ años; clases HSE gratuitas; se requiere orientación.",
        notes="Call 601-857-3914; classes at multiple Hinds CC campuses; HSE test fees separate.",
        notes_es="Llame al 601-857-3914; clases en múltiples campus Hinds CC.",
        hours="Class schedules vary by campus",
        tags="jackson|hinds|education|GED|ESL|reentry",
        services="GED preparation|High School Equivalency|English language classes|Citizen instruction|Career pathway referrals",
        county="Hinds", served_counties="Hinds|Madison|Rankin|Copiah|Simpson", coverage="multi",
        _source="https://www.hindscc.edu", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Mississippi Gulf Coast Community College — Adult Education",
        category="education", region="Gulfport / Harrison County",
        description="Mississippi Gulf Coast Community College Adult Education offers free GED and High School Equivalency classes, English language instruction, and workforce credential pathways for Gulf Coast adults including justice-involved learners at the Jefferson Davis and Perkinston campuses.",
        description_es="Mississippi Gulf Coast Community College Educación para Adultos ofrece clases GED y equivalencia de secundaria gratuitas, instrucción de inglés y vías de credenciales laborales para adultos de la Costa del Golfo incluidos estudiantes con antecedentes penales.",
        address="730 East Beach Boulevard", city="Long Beach", phone="228-896-3350", email="",
        website="https://www.mgccc.edu",
        eligibility="Gulf Coast adults age 16+; free ABE and HSE classes; orientation required.",
        eligibility_es="Adultos de la Costa del Golfo de 16+ años; clases ABE y HSE gratuitas; se requiere orientación.",
        notes="Call 228-896-3350; multiple Gulf Coast campus locations; pairs with WIN Job Center Gulf Coast.",
        notes_es="Llame al 228-896-3350; múltiples campus en la Costa del Golfo; se vincula con WIN Job Center.",
        hours="Class schedules vary",
        tags="gulfport|harrison|education|GED|ESL|reentry",
        services="GED preparation|High School Equivalency|English language classes|Workforce credentials|College transition",
        county="Harrison", served_counties="Harrison|Hancock|Jackson|Stone|George", coverage="multi",
        _source="https://www.mgccc.edu", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Itawamba Community College — Adult Basic Education",
        category="education", region="Tupelo / Lee County",
        description="Itawamba Community College Adult Basic Education provides free GED preparation and English language classes for northeast Mississippi adults including justice-involved residents at the Tupelo and Fulton campuses.",
        description_es="Itawamba Community College Educación Básica para Adultos ofrece preparación GED gratuita y clases de inglés para adultos del noreste de Mississippi incluidos residentes con antecedentes penales en los campus de Tupelo y Fulton.",
        address="602 West Hill Street", city="Fulton", phone="662-862-8000", email="",
        website="https://www.iccms.edu",
        eligibility="Northeast Mississippi adults; free HSE classes; orientation required.",
        eligibility_es="Adultos del noreste de Mississippi; clases HSE gratuitas; se requiere orientación.",
        notes="Call 662-862-8000; Tupelo campus also offers ABE; pairs with WIN Job Center Tupelo.",
        notes_es="Llame al 662-862-8000; campus Tupelo también ofrece ABE; se vincula con WIN Job Center Tupelo.",
        hours="Class schedules vary",
        tags="tupelo|lee|education|GED|ESL|reentry",
        services="GED preparation|High School Equivalency|English language classes|College transition|Career referrals",
        county="Itawamba", served_counties="Itawamba|Lee|Monroe|Chickasaw", coverage="multi",
        _source="https://www.iccms.edu", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Pearl River Community College — Adult Education",
        category="education", region="Hattiesburg / Forrest County",
        description="Pearl River Community College Adult Education offers free GED and High School Equivalency classes for Pine Belt adults including returning citizens at the Hattiesburg and Poplarville campuses.",
        description_es="Pearl River Community College Educación para Adultos ofrece clases GED y equivalencia de secundaria gratuitas para adultos del Pine Belt incluidos ciudadanos que regresan en los campus de Hattiesburg y Poplarville.",
        address="5448 US Highway 49 South", city="Hattiesburg", phone="601-554-5500", email="",
        website="https://www.prcc.edu",
        eligibility="Pine Belt adults age 16+; free HSE classes; orientation required.",
        eligibility_es="Adultos del Pine Belt de 16+ años; clases HSE gratuitas; se requiere orientación.",
        notes="Call 601-554-5500; Hattiesburg campus main ABE site; pairs with WIN Job Center Hattiesburg.",
        notes_es="Llame al 601-554-5500; campus Hattiesburg sitio principal ABE; se vincula con WIN Job Center Hattiesburg.",
        hours="Class schedules vary",
        tags="hattiesburg|forrest|education|GED|ESL|reentry",
        services="GED preparation|High School Equivalency|English language classes|College transition|Career referrals",
        county="Forrest", served_counties="Forrest|Lamar|Marion|Covington|Jefferson Davis", coverage="multi",
        _source="https://www.prcc.edu", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Meridian Community College — Adult Education",
        category="education", region="Meridian / Lauderdale County",
        description="Meridian Community College Adult Education provides free GED preparation and English language classes for east-central Mississippi adults including justice-involved residents rebuilding credentials for Mississippi Works.",
        description_es="Meridian Community College Educación para Adultos ofrece preparación GED gratuita y clases de inglés para adultos del centro-este de Mississippi incluidos residentes con antecedentes penales que reconstruyen credenciales.",
        address="910 Highway 19 North", city="Meridian", phone="601-483-8241", email="",
        website="https://www.mcc.cc.ms.us",
        eligibility="Lauderdale County and east-central Mississippi adults; free HSE classes.",
        eligibility_es="Adultos del condado Lauderdale y centro-este de Mississippi; clases HSE gratuitas.",
        notes="Call 601-483-8241; pairs with WIN Job Center Meridian and Weems CMHC.",
        notes_es="Llame al 601-483-8241; se vincula con WIN Job Center Meridian y Weems CMHC.",
        hours="Class schedules vary",
        tags="meridian|lauderdale|education|GED|ESL|reentry",
        services="GED preparation|High School Equivalency|English language classes|College transition|Career referrals",
        county="Lauderdale", served_counties="Lauderdale|Clarke|Kemper|Neshoba", coverage="multi",
        _source="https://www.mcc.cc.ms.us", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="East Mississippi Community College — Adult Education",
        category="education", region="Columbus / Lowndes County",
        description="East Mississippi Community College Adult Education offers free GED and High School Equivalency classes for Golden Triangle adults including returning citizens at the Columbus and Scooba campuses.",
        description_es="East Mississippi Community College Educación para Adultos ofrece clases GED y equivalencia de secundaria gratuitas para adultos del Triángulo Dorado incluidos ciudadanos que regresan en los campus de Columbus y Scooba.",
        address="1512 Kemper Street", city="Columbus", phone="662-243-1900", email="",
        website="https://www.eastms.edu",
        eligibility="Golden Triangle adults age 16+; free HSE classes; orientation required.",
        eligibility_es="Adultos del Triángulo Dorado de 16+ años; clases HSE gratuitas; se requiere orientación.",
        notes="Call 662-243-1900; Columbus campus main ABE site; pairs with WIN Job Center Columbus.",
        notes_es="Llame al 662-243-1900; campus Columbus sitio principal ABE; se vincula con WIN Job Center Columbus.",
        hours="Class schedules vary",
        tags="columbus|lowndes|education|GED|ESL|reentry",
        services="GED preparation|High School Equivalency|English language classes|College transition|Career referrals",
        county="Lowndes", served_counties="Lowndes|Oktibbeha|Clay|Noxubee", coverage="multi",
        _source="https://www.eastms.edu", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Mississippi Delta Community College — Adult Education",
        category="education", region="Greenville / Washington County",
        description="Mississippi Delta Community College Adult Education provides free GED preparation and English language classes for Delta region adults including returning citizens at the Greenville, Moorhead, and Holly Springs campuses.",
        description_es="Mississippi Delta Community College Educación para Adultos ofrece preparación GED gratuita y clases de inglés para adultos de la región Delta incluidos ciudadanos que regresan en los campus de Greenville, Moorhead y Holly Springs.",
        address="300 South West Street", city="Greenville", phone="662-246-6322", email="",
        website="https://www.msdelta.edu",
        eligibility="Delta region adults; free HSE classes; orientation required.",
        eligibility_es="Adultos de la región Delta; clases HSE gratuitas; se requiere orientación.",
        notes="Call 662-246-6322; Greenville campus main ABE site; pairs with WIN Job Center Greenville.",
        notes_es="Llame al 662-246-6322; campus Greenville sitio principal ABE; se vincula con WIN Job Center Greenville.",
        hours="Class schedules vary",
        tags="greenville|washington|education|GED|delta|reentry",
        services="GED preparation|High School Equivalency|English language classes|College transition|Career referrals",
        county="Washington", served_counties="Washington|Bolivar|Sunflower|Leflore|Humphreys", coverage="multi",
        _source="https://www.msdelta.edu", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Northwest Mississippi Community College — Adult Education",
        category="education", region="Oxford / Lafayette County",
        description="Northwest Mississippi Community College Adult Education offers free GED and High School Equivalency classes for north Mississippi adults including justice-involved learners at the Oxford, Senatobia, and DeSoto campuses.",
        description_es="Northwest Mississippi Community College Educación para Adultos ofrece clases GED y equivalencia de secundaria gratuitas para adultos del norte de Mississippi incluidos estudiantes con antecedentes penales en los campus de Oxford, Senatobia y DeSoto.",
        address="1310 Belk Drive", city="Oxford", phone="662-236-2023", email="",
        website="https://www.northwestms.edu",
        eligibility="North Mississippi adults age 16+; free HSE classes; orientation required.",
        eligibility_es="Adultos del norte de Mississippi de 16+ años; clases HSE gratuitas; se requiere orientación.",
        notes="Call 662-236-2023; Oxford campus main ABE site; pairs with WIN Job Center Oxford.",
        notes_es="Llame al 662-236-2023; campus Oxford sitio principal ABE; se vincula con WIN Job Center Oxford.",
        hours="Class schedules vary",
        tags="oxford|lafayette|education|GED|ESL|reentry",
        services="GED preparation|High School Equivalency|English language classes|College transition|Career referrals",
        county="Lafayette", served_counties="Lafayette|Marshall|Benton|DeSoto|Panola|Tippah", coverage="multi",
        _source="https://www.northwestms.edu", _source_type="nonprofit", _confidence="high",
    )

    # --- family-children category minimum ---
    add(
        name="Mississippi Department of Child Protection Services — Reunification",
        category="family-children", region="Jackson / Hinds County",
        description="The Mississippi Department of Child Protection Services coordinates family reunification, kinship caregiver support, and child welfare case management for parents working toward reunification after incarceration or CPS involvement. CPS staff connect justice-involved parents to housing, access.ms.gov benefits, and Mississippi Works—not emergency cash assistance.",
        description_es="El Departamento de Servicios de Protección Infantil de Mississippi coordina la reunificación familiar, apoyo a cuidadores de parentesco y manejo de casos de bienestar infantil para padres que trabajan hacia la reunificación después de la encarcelación o participación de CPS.",
        address="860 North State Street", city="Jackson", phone="601-359-4171", email="",
        website="https://www.mdcps.ms.gov",
        eligibility="Parents with active CPS cases or reunification plans; justice-involved parents must comply with court-ordered case plans.",
        eligibility_es="Padres con casos activos de CPS o planes de reunificación; padres con antecedentes penales deben cumplir planes de casos ordenados por la corte.",
        notes="Call 601-359-4171; not a walk-in emergency shelter; coordinate through assigned CPS caseworker.",
        notes_es="Llame al 601-359-4171; no es refugio de emergencia sin cita; coordine a través del trabajador social CPS asignado.",
        hours="County offices Monday–Friday business hours",
        tags="jackson|family-children|CPS|reunification|reentry",
        services="Family reunification support|Kinship caregiver services|Case management|Benefits referrals|Parenting support",
        county="Hinds", served_counties="", coverage="statewide",
        _source="https://www.mdcps.ms.gov", _source_type="government", _confidence="high",
    )
    add(
        name="Canopy Children's Solutions — Jackson",
        category="family-children", region="Jackson / Hinds County",
        description="Canopy Children's Solutions provides behavioral health, foster care support, and family preservation services for vulnerable Hinds County children and families including justice-involved parents reunifying with children after release. Therapists coordinate with MDOC, CPS, and local housing partners.",
        description_es="Canopy Children's Solutions ofrece salud conductual, apoyo de cuidado de crianza y servicios de preservación familiar para niños y familias vulnerables del condado Hinds incluidos padres con antecedentes penales que se reunifican con sus hijos después de la liberación.",
        address="1465 North State Street", city="Jackson", phone="800-388-6247", email="",
        website="https://www.mycanopy.org",
        eligibility="Hinds County families with child behavioral health or foster care needs; justice-involved parents per program policy.",
        eligibility_es="Familias del condado Hinds con necesidades de salud conductual infantil o cuidado de crianza; padres con antecedentes penales según política.",
        notes="Call 800-388-6247 for intake; statewide Canopy network; pairs with Catholic Charities housing.",
        notes_es="Llame al 800-388-6247 para admisión; red Canopy estatal; se vincula con vivienda Catholic Charities.",
        hours="Monday–Friday business hours",
        tags="jackson|family-children|behavioral-health|foster-care|reentry",
        services="Child behavioral health|Family preservation|Foster care support|Parenting services|Reunification coordination",
        county="Hinds", served_counties="Hinds|Madison|Rankin", coverage="multi",
        _source="https://www.mycanopy.org", _source_type="nonprofit", _confidence="high",
    )
