"""Close remaining Mississippi category minimum gaps."""


def register_minimum_closure(add):
    add(
        name="Mississippi Food Network — Statewide Food Bank",
        category="basic-needs", region="Statewide",
        description="Mississippi Food Network distributes emergency groceries through partner pantries across Mississippi for low-income households including returning citizens reestablishing food security after MDOC release. Statewide food bank network—not a SNAP application office.",
        description_es="Mississippi Food Network distribuye comestibles de emergencia a través de despensas aliadas en Mississippi para hogares de bajos ingresos incluidos ciudadanos que regresan después de la liberación de MDOC.",
        address="440 West Beatty Street", city="Jackson", phone="601-353-7286", email="",
        website="https://www.msfoodnet.org",
        eligibility="Low-income Mississippi residents; partner pantry locator online.",
        eligibility_es="Residentes de Mississippi de bajos ingresos; localizador de despensas aliadas en línea.",
        notes="Call 601-353-7286 or use msfoodnet.org pantry locator; not an MDHS benefits office.",
        notes_es="Llame al 601-353-7286 o use el localizador en msfoodnet.org.",
        hours="Warehouse hours vary; call partner pantries",
        tags="statewide|basic-needs|food-bank|reentry",
        services="Emergency food distribution|Partner pantry network|Mobile pantry|Nutrition support",
        county="Hinds", served_counties="", coverage="statewide",
        _source="https://www.msfoodnet.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Salvation Army — Jackson Area Command",
        category="basic-needs", region="Jackson / Hinds County",
        description="The Salvation Army Jackson Area Command provides emergency food, clothing, utility assistance, and disaster relief for low-income Hinds County households including justice-involved families stabilizing after incarceration.",
        description_es="El Area Command de Salvation Army en Jackson ofrece alimentos de emergencia, ropa, asistencia con servicios públicos y ayuda en desastres para hogares de bajos ingresos del condado Hinds.",
        address="110 Presto Lane", city="Jackson", phone="601-982-4881", email="",
        website="https://centralusa.salvationarmy.org/jackson",
        eligibility="Low-income Hinds County residents in crisis; justice-involved households may qualify for emergency assistance.",
        eligibility_es="Residentes de bajos ingresos del condado Hinds en crisis; hogares con antecedentes penales pueden calificar.",
        notes="Call 601-982-4881; not a walk-in MDHS office.",
        notes_es="Llame al 601-982-4881; no es oficina MDHS sin cita.",
        hours="Monday–Friday business hours",
        tags="jackson|hinds|basic-needs|utility|reentry",
        services="Emergency food|Clothing|Utility assistance|Disaster relief|Case referrals",
        county="Hinds", served_counties="Hinds|Rankin|Madison", coverage="multi",
        _source="https://centralusa.salvationarmy.org/jackson", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="St. Vincent de Paul — Gulf Coast",
        category="basic-needs", region="Gulfport / Harrison County",
        description="Society of St. Vincent de Paul Gulf Coast provides emergency food, clothing, and financial assistance for low-income Harrison and Jackson county households including returning citizens.",
        description_es="Sociedad de San Vicente de Paul Costa del Golfo ofrece alimentos de emergencia, ropa y asistencia financiera para hogares de bajos ingresos de los condados Harrison y Jackson.",
        address="228 East Pass Road", city="Gulfport", phone="228-896-0721", email="",
        website="https://www.svdpbiloxi.org",
        eligibility="Low-income Gulf Coast residents in need; conference-based assistance by parish.",
        eligibility_es="Residentes de la Costa del Golfo de bajos ingresos en necesidad; asistencia por conferencia parroquial.",
        notes="Call 228-896-0721 for nearest conference; pairs with Back Bay Mission.",
        notes_es="Llame al 228-896-0721 para la conferencia más cercana.",
        hours="Varies by conference; call ahead",
        tags="gulfport|harrison|basic-needs|clothing|reentry",
        services="Emergency food|Clothing|Financial assistance|Furniture|Referrals",
        county="Harrison", served_counties="Harrison|Jackson", coverage="multi",
        _source="https://www.svdpbiloxi.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Catholic Charities — North Mississippi",
        category="basic-needs", region="Tupelo / Lee County",
        description="Catholic Charities North Mississippi provides emergency assistance, food, and utility help for low-income families in Lee, Pontotoc, and Itawamba counties including justice-involved households.",
        description_es="Catholic Charities Norte de Mississippi ofrece asistencia de emergencia, alimentos y ayuda con servicios públicos para familias de bajos ingresos en los condados Lee, Pontotoc e Itawamba.",
        address="400 South Gloster Street", city="Tupelo", phone="662-842-3452", email="",
        website="https://www.catholiccharitiesjackson.org",
        eligibility="Low-income north Mississippi residents; justice-involved families may qualify for emergency aid.",
        eligibility_es="Residentes de bajos ingresos del norte de Mississippi; familias con antecedentes penales pueden calificar.",
        notes="Call 662-842-3452; regional office of Catholic Charities Jackson diocese.",
        notes_es="Llame al 662-842-3452; oficina regional de la diócesis de Jackson.",
        hours="Monday–Friday business hours",
        tags="tupelo|lee|basic-needs|utility|reentry",
        services="Emergency assistance|Food|Utility help|Referrals|Family support",
        county="Lee", served_counties="Lee|Pontotoc|Itawamba", coverage="multi",
        _source="https://www.catholiccharitiesjackson.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="United Way of Southeast Mississippi — Basic Needs",
        category="basic-needs", region="Hattiesburg / Forrest County",
        description="United Way of Southeast Mississippi coordinates emergency basic needs assistance and 211 referrals for low-income households in Forrest, Lamar, and Marion counties including returning citizens.",
        description_es="United Way del Sureste de Mississippi coordina asistencia de necesidades básicas de emergencia y referencias 211 para hogares de bajos ingresos en los condados Forrest, Lamar y Marion.",
        address="210 West Front Street", city="Hattiesburg", phone="601-545-7141", email="",
        website="https://www.unitedwaysems.org",
        eligibility="Low-income southeast Mississippi residents; dial 211 for resource navigation.",
        eligibility_es="Residentes de bajos ingresos del sureste de Mississippi; marque 211 para navegación de recursos.",
        notes="Call 601-545-7141 or 211; pairs with Pine Belt Mental Healthcare.",
        notes_es="Llame al 601-545-7141 o al 211.",
        hours="Monday–Friday business hours",
        tags="hattiesburg|forrest|basic-needs|211|reentry",
        services="Basic needs referrals|211 coordination|Emergency assistance navigation|Partner agency network",
        county="Forrest", served_counties="Forrest|Lamar|Marion", coverage="multi",
        _source="https://www.unitedwaysems.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Mississippi Community College Board — Adult Education",
        category="education", region="Statewide",
        description="The Mississippi Community College Board coordinates free High School Equivalency and adult basic education programs at community colleges statewide for justice-involved adults rebuilding credentials for Mississippi Works employment.",
        description_es="La Junta de Colegios Comunitarios de Mississippi coordina programas gratuitos de equivalencia de secundaria y educación básica para adultos en colegios comunitarios en todo el estado.",
        address="3825 Ridgewood Road", city="Jackson", phone="601-432-6514", email="",
        website="https://www.mccb.edu",
        eligibility="Mississippi adults age 16+ without high school diploma; free HSE classes at local community colleges.",
        eligibility_es="Adultos de Mississippi de 16+ años sin diploma de secundaria; clases HSE gratuitas en colegios comunitarios locales.",
        notes="Find nearest adult education site at mccb.edu; pairs with WIN Job Centers.",
        notes_es="Encuentre el sitio de educación para adultos más cercano en mccb.edu.",
        hours="Class schedules vary by campus",
        tags="statewide|education|GED|HSE|reentry",
        services="High School Equivalency|Adult Basic Education|Workforce pathway referrals|College transition",
        county="Hinds", served_counties="", coverage="statewide",
        _source="https://www.mccb.edu", _source_type="government", _confidence="high",
    )
    add(
        name="Hinds Community College — Adult Education",
        category="education", region="Jackson / Hinds County",
        description="Hinds Community College Adult Education offers free GED and HSE preparation for Hinds, Rankin, and Madison county adults including justice-involved learners at Jackson and Raymond campuses.",
        description_es="Hinds Community College Educación para Adultos ofrece preparación GED y HSE gratuita para adultos de los condados Hinds, Rankin y Madison.",
        address="3925 Sunset Drive", city="Jackson", phone="601-857-3686", email="",
        website="https://www.hindscc.edu",
        eligibility="Adults age 16+ in HCC service area; free HSE preparation.",
        eligibility_es="Adultos de 16+ años en el área de servicio de HCC; preparación HSE gratuita.",
        notes="Call 601-857-3686; multiple metro campuses.",
        notes_es="Llame al 601-857-3686; múltiples campus metropolitanos.",
        hours="Class schedules vary",
        tags="jackson|hinds|education|GED|reentry",
        services="GED preparation|HSE classes|English language learning|Workforce referrals",
        county="Hinds", served_counties="Hinds|Rankin|Madison", coverage="multi",
        _source="https://www.hindscc.edu", _source_type="government", _confidence="high",
    )
    add(
        name="East Mississippi Community College — Adult Education",
        category="education", region="Columbus / Lowndes County",
        description="East Mississippi Community College Adult Education provides free GED preparation for Lowndes, Oktibbeha, and Clay county adults including justice-involved residents near MDOC facilities.",
        description_es="East Mississippi Community College Educación para Adultos ofrece preparación GED gratuita para adultos de los condados Lowndes, Oktibbeha y Clay.",
        address="1512 Kemper Street", city="Columbus", phone="662-243-1900", email="",
        website="https://www.eastms.edu",
        eligibility="Adults age 16+ in EMCC service area; free HSE classes.",
        eligibility_es="Adultos de 16+ años en el área de servicio de EMCC; clases HSE gratuitas.",
        notes="Call 662-243-1900; Golden Triangle WIN Job Center partner.",
        notes_es="Llame al 662-243-1900; aliado del WIN Job Center Golden Triangle.",
        hours="Class schedules vary",
        tags="columbus|lowndes|education|GED|reentry",
        services="GED preparation|Adult education|Workforce referrals|College bridge",
        county="Lowndes", served_counties="Lowndes|Oktibbeha|Clay", coverage="multi",
        _source="https://www.eastms.edu", _source_type="government", _confidence="high",
    )
    add(
        name="Meridian Community College — Adult Education",
        category="education", region="Meridian / Lauderdale County",
        description="Meridian Community College Adult Education offers free GED and HSE classes for Lauderdale and Clarke county adults including justice-involved learners rebuilding education credentials.",
        description_es="Meridian Community College Educación para Adultos ofrece clases GED y HSE gratuitas para adultos de los condados Lauderdale y Clarke.",
        address="910 Highway 19 North", city="Meridian", phone="601-483-8241", email="",
        website="https://www.meridiancc.edu",
        eligibility="Adults age 16+ in MCC service area; free HSE preparation.",
        eligibility_es="Adultos de 16+ años en el área de servicio de MCC; preparación HSE gratuita.",
        notes="Call 601-483-8241; pairs with Weems Community Mental Health Meridian.",
        notes_es="Llame al 601-483-8241; se vincula con Weems Community Mental Health.",
        hours="Class schedules vary",
        tags="meridian|lauderdale|education|GED|reentry",
        services="GED preparation|Adult Basic Education|Workforce referrals",
        county="Lauderdale", served_counties="Lauderdale|Clarke", coverage="multi",
        _source="https://www.meridiancc.edu", _source_type="government", _confidence="high",
    )
    add(
        name="Mississippi Department of Child Protection Services — Family Support",
        category="family-children", region="Statewide",
        description="Mississippi Department of Child Protection Services provides kinship caregiver support, family preservation services, and reunification planning for vulnerable families including justice-involved parents working toward reunification after incarceration.",
        description_es="El Departamento de Servicios de Protección Infantil de Mississippi ofrece apoyo a cuidadores de parentesco, servicios de preservación familiar y planificación de reunificación para familias vulnerables incluidos padres con antecedentes penales.",
        address="750 North State Street", city="Jackson", phone="601-359-4171", email="",
        website="https://www.mdcps.ms.gov",
        eligibility="Mississippi families involved with child welfare or seeking kinship support; justice-involved parents may qualify for reunification services.",
        eligibility_es="Familias de Mississippi involucradas con bienestar infantil o que buscan apoyo de parentesco; padres con antecedentes penales pueden calificar.",
        notes="Call 601-359-4171; report child abuse to 1-800-222-8000; not an emergency shelter.",
        notes_es="Llame al 601-359-4171; reporte abuso infantil al 1-800-222-8000.",
        hours="Monday–Friday business hours",
        tags="statewide|family-children|kinship|reunification|reentry",
        services="Kinship caregiver support|Family preservation|Reunification planning|Parent education|Benefits referrals",
        county="Hinds", served_counties="", coverage="statewide",
        _source="https://www.mdcps.ms.gov", _source_type="government", _confidence="high",
    )
    add(
        name="Hinds County Circuit Clerk — Voter Registration",
        category="id-documentation", region="Jackson / Hinds County",
        description="The Hinds County Circuit Clerk assists residents with voter registration and guidance on restoring voting rights after felony convictions under Mississippi law. Staff provide forms and referrals to Mississippi DPS and Mississippi Center for Legal Services—not driver's license services.",
        description_es="El Secretario del Tribunal del Circuito del condado Hinds ayuda a residentes con registro de votantes y orientación sobre restauración de derechos de voto después de condenas por delitos graves según la ley de Mississippi.",
        address="407 East Pascagoula Street", city="Jackson", phone="601-968-6555", email="",
        website="https://www.co.hinds.ms.us",
        eligibility="Hinds County residents; individuals with felony convictions should verify rights restoration requirements.",
        eligibility_es="Residentes del condado Hinds; personas con condenas por delitos graves deben verificar requisitos de restauración de derechos.",
        notes="Call 601-968-6555; pairs with Mississippi DPS for ID documents.",
        notes_es="Llame al 601-968-6555; se vincula con Mississippi DPS para documentos de identificación.",
        hours="Monday–Friday business hours",
        tags="jackson|hinds|id-documentation|voting-rights|reentry",
        services="Voter registration|Rights restoration guidance|Document counseling|Election referrals",
        county="Hinds", served_counties="Hinds", coverage="single",
        _source="https://www.co.hinds.ms.us", _source_type="government", _confidence="high",
    )
    add(
        name="Harrison County Circuit Clerk — Voter Registration",
        category="id-documentation", region="Gulfport / Harrison County",
        description="The Harrison County Circuit Clerk assists Gulf Coast residents with voter registration and photo ID guidance for voting, with referrals to Mississippi DPS for driver's license and ID restoration after incarceration.",
        description_es="El Secretario del Tribunal del Circuito del condado Harrison ayuda a residentes de la Costa del Golfo con registro de votantes y orientación sobre identificación con foto para votar.",
        address="1801 23rd Avenue", city="Gulfport", phone="228-865-4000", email="",
        website="https://www.harrisoncountyms.gov",
        eligibility="Harrison County residents; felony conviction rights restoration rules apply.",
        eligibility_es="Residentes del condado Harrison; aplican reglas de restauración de derechos por condenas graves.",
        notes="Call 228-865-4000; not a DPS licensing office.",
        notes_es="Llame al 228-865-4000; no es oficina de licencias DPS.",
        hours="Monday–Friday business hours",
        tags="gulfport|harrison|id-documentation|voting-rights|reentry",
        services="Voter registration|Photo ID guidance|Rights restoration information|Document referrals",
        county="Harrison", served_counties="Harrison", coverage="single",
        _source="https://www.harrisoncountyms.gov", _source_type="government", _confidence="high",
    )
    add(
        name="North Mississippi Rural Legal Services — Oxford",
        category="legal-aid", region="Oxford / Lafayette County",
        description="North Mississippi Rural Legal Services provides free civil legal aid to low-income residents of north Mississippi including housing, benefits, and family law for justice-involved clients—not criminal defense.",
        description_es="North Mississippi Rural Legal Services brinda asistencia legal civil gratuita a residentes de bajos ingresos del norte de Mississippi incluyendo vivienda y beneficios.",
        address="220 South Lamar Boulevard", city="Oxford", phone="662-234-2916", email="",
        website="https://www.nmrls.com",
        eligibility="Low-income north Mississippi residents; LSC income limits; civil matters only.",
        eligibility_es="Residentes de bajos ingresos del norte de Mississippi; límites de ingresos LSC; solo asuntos civiles.",
        notes="Call 662-234-2916; complements Mississippi Center for Legal Services statewide intake.",
        notes_es="Llame al 662-234-2916; complementa la admisión estatal de Mississippi Center for Legal Services.",
        hours="Monday–Friday business hours",
        tags="oxford|lafayette|legal-aid|north-mississippi|reentry",
        services="Housing legal aid|Benefits advocacy|Family law assistance|Eviction defense",
        county="Lafayette", served_counties="Lafayette|Panola|Marshall", coverage="multi",
        _source="https://www.nmrls.com", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Mississippi Volunteer Lawyers Project",
        category="legal-aid", region="Jackson / Hinds County",
        description="Mississippi Volunteer Lawyers Project connects low-income Mississippians to pro bono civil attorneys for housing, benefits, and family law matters including limited record relief guidance—not criminal defense.",
        description_es="Mississippi Volunteer Lawyers Project conecta a personas de bajos ingresos de Mississippi con abogados civiles pro bono para vivienda, beneficios y derecho familiar.",
        address="643 North State Street", city="Jackson", phone="601-960-9577", email="",
        website="https://www.mvlp.org",
        eligibility="Low-income Mississippi residents with civil legal needs; income screening required.",
        eligibility_es="Residentes de Mississippi de bajos ingresos con necesidades legales civiles; se requiere evaluación de ingresos.",
        notes="Apply at mvlp.org or call 601-960-9577; complements MCLS statewide intake.",
        notes_es="Solicite en mvlp.org o llame al 601-960-9577.",
        hours="Monday–Friday business hours",
        tags="jackson|legal-aid|pro-bono|reentry",
        services="Pro bono civil referrals|Housing legal help|Benefits advocacy|Clinics",
        county="Hinds", served_counties="Hinds|Rankin|Madison", coverage="multi",
        _source="https://www.mvlp.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Gulf Coast Center for Law — Biloxi",
        category="legal-aid", region="Biloxi / Harrison County",
        description="Gulf Coast Center for Law provides free civil legal services to low-income Harrison, Jackson, and Hancock county residents including eviction defense and public benefits advocacy for justice-involved clients.",
        description_es="Gulf Coast Center for Law brinda servicios legales civiles gratuitos a residentes de bajos ingresos de los condados Harrison, Jackson y Hancock.",
        address="942 Porter Avenue", city="Biloxi", phone="228-435-9191", email="",
        website="https://www.gulfcoastlaw.org",
        eligibility="Low-income Gulf Coast residents; civil legal matters only.",
        eligibility_es="Residentes de la Costa del Golfo de bajos ingresos; solo asuntos legales civiles.",
        notes="Call 228-435-9191; pairs with Back Bay Mission housing programs.",
        notes_es="Llame al 228-435-9191; se vincula con programas de vivienda de Back Bay Mission.",
        hours="Monday–Friday business hours",
        tags="biloxi|harrison|legal-aid|gulf-coast|reentry",
        services="Eviction defense|Benefits advocacy|Housing legal aid|Family law referrals",
        county="Harrison", served_counties="Harrison|Jackson|Hancock", coverage="multi",
        _source="https://www.gulfcoastlaw.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Southern Poverty Law Center — Mississippi Reentry Advocacy",
        category="legal-aid", region="Jackson / Hinds County",
        description="The Southern Poverty Law Center Mississippi office advocates for fair chance employment, voting rights restoration, and civil rights protections for justice-involved Mississippians through litigation and policy support—not individual criminal defense.",
        description_es="La oficina de Mississippi del Southern Poverty Law Center aboga por empleo de segunda oportunidad, restauración de derechos de voto y protecciones de derechos civiles para personas con antecedentes penales.",
        address="400 North Congress Street", city="Jackson", phone="601-948-8881", email="",
        website="https://www.splcenter.org",
        eligibility="Mississippians facing civil rights violations related to criminal records or reentry barriers; advocacy organization.",
        eligibility_es="Personas de Mississippi que enfrentan violaciones de derechos civiles relacionadas con antecedentes penales; organización de defensa.",
        notes="Contact through splcenter.org; complements direct legal aid providers.",
        notes_es="Contacte a través de splcenter.org; complementa proveedores de asistencia legal directa.",
        hours="Monday–Friday business hours",
        tags="jackson|legal-aid|advocacy|civil-rights|reentry",
        services="Civil rights advocacy|Policy support|Voting rights|Fair chance employment advocacy",
        county="Hinds", served_counties="", coverage="statewide",
        _source="https://www.splcenter.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Mississippi Center for Re-Entry",
        category="reentry-organizations", region="Southaven / DeSoto County",
        description="Mississippi Center for Re-Entry provides transition support, work readiness, mentoring, and community resource navigation for formerly incarcerated individuals in DeSoto, Tunica, Marshall, and Tate counties and through statewide advocacy partnerships. Peer-led reentry navigation—not emergency cash or shelter intake.",
        description_es="Mississippi Center for Re-Entry ofrece apoyo de transición, preparación laboral, mentoría y navegación de recursos comunitarios para personas anteriormente encarceladas en los condados DeSoto, Tunica, Marshall y Tate y a través de alianzas de defensa estatal.",
        address="230-2 Goodman Road East, Suite 202", city="Southaven", phone="662-701-6031", email="",
        website="https://msreentry.org",
        eligibility="Formerly incarcerated Mississippians in northwest Mississippi and reentry allies; walk-in hours Monday, Wednesday, Friday.",
        eligibility_es="Personas anteriormente encarceladas del noroeste de Mississippi y aliados de reinserción; horario sin cita lunes, miércoles y viernes.",
        notes="Call 662-701-6031 or 833-536-1835; hours Mon/Wed/Fri 11:00 a.m.–5:00 p.m.; pairs with MDOC and WIN Job Centers.",
        notes_es="Llame al 662-701-6031 o 833-536-1835; horario lun/mié/vie 11:00 a.m.–5:00 p.m.",
        hours="Monday, Wednesday, Friday 11:00 a.m.–5:00 p.m.",
        tags="southaven|reentry-organizations|peer-support|employment|reentry",
        services="Transition support|Work readiness|Peer mentoring|Community resource navigation|Voting rights advocacy",
        county="DeSoto", served_counties="DeSoto|Tunica|Marshall|Tate", coverage="multi",
        _source="https://msreentry.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="RECH Foundation — M.O.R.E. Reentry Program",
        category="reentry-organizations", region="Jackson / Hinds County",
        description="The RECH Foundation's Mississippi Offender Reentry Establishment (M.O.R.E.) provides statewide mentoring, life skills coaching, workforce development, and employment navigation for justice-involved adults returning to Hinds County and communities across Mississippi. Program enrollment required—not emergency cash assistance.",
        description_es="El programa M.O.R.E. de RECH Foundation ofrece mentoría estatal, coaching de habilidades para la vida, desarrollo de fuerza laboral y navegación laboral para adultos con antecedentes penales que regresan al condado Hinds y comunidades en Mississippi.",
        address="1313 Maria Court", city="Jackson", phone="601-566-2276", email="",
        website="https://rechfoundationms.org/m-o-r-e/",
        eligibility="Justice-involved adults in Mississippi seeking mentoring and workforce reentry support; program enrollment required.",
        eligibility_es="Adultos con antecedentes penales en Mississippi que buscan mentoría y apoyo de reinserción laboral; se requiere inscripción en el programa.",
        notes="Contact through rechfoundationms.org; pairs with WIN Job Centers and Hinds Behavioral Health.",
        notes_es="Contacte a través de rechfoundationms.org; se vincula con WIN Job Centers y Hinds Behavioral Health.",
        hours="Program hours vary; contact for enrollment",
        tags="jackson|reentry-organizations|mentoring|MORE|reentry",
        services="Mentoring|Life skills coaching|Workforce development|Employment navigation|Reentry fairs",
        county="Hinds", served_counties="Hinds|Rankin|Madison", coverage="multi",
        _source="https://rechfoundationms.org/m-o-r-e/", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Mississippi Prison Industries — Reentry Employment",
        category="reentry-organizations", region="Statewide",
        description="Mississippi Prison Industries connects returning citizens to transitional employment, skills training, and employer partnerships through MDOC-linked programs preparing individuals for community-based work after release.",
        description_es="Mississippi Prison Industries conecta a ciudadanos que regresan con empleo transicional, capacitación en habilidades y alianzas con empleadores a través de programas vinculados con MDOC.",
        address="3794 Highway 468 West", city="Pearl", phone="601-932-2882", email="",
        website="https://www.msprisonindustries.com",
        eligibility="MDOC participants and returning citizens in MPI transitional employment programs.",
        eligibility_es="Participantes de MDOC y ciudadanos que regresan en programas de empleo transicional de MPI.",
        notes="Coordinate through MDOC reentry staff; not emergency cash assistance.",
        notes_es="Coordine con el personal de reinserción de MDOC; no es asistencia de efectivo de emergencia.",
        hours="Monday–Friday business hours",
        tags="statewide|reentry-organizations|employment|MPI|reentry",
        services="Transitional employment|Skills training|Employer partnerships|MDOC coordination",
        county="Rankin", served_counties="", coverage="statewide",
        _source="https://www.msprisonindustries.com", _source_type="government", _confidence="high",
    )
    add(
        name="Mississippi Association Returning Citizens (MARC)",
        category="reentry-organizations", region="Jackson / Hinds County",
        description="Mississippi Association Returning Citizens (MARC) mobilizes volunteers to mentor incarcerated and formerly incarcerated Mississippians, connect returning citizens to housing and employment resources, and advocate for successful community reintegration across the state.",
        description_es="Mississippi Association Returning Citizens (MARC) moviliza voluntarios para mentorar a personas encarceladas y anteriormente encarceladas de Mississippi, conectar a ciudadanos que regresan con recursos de vivienda y empleo y abogar por la reintegración comunitaria exitosa.",
        address="236 East Capitol Street", city="Jackson", phone="601-355-9400", email="",
        website="https://www.marcreentry.org",
        eligibility="Formerly incarcerated Mississippians and volunteer mentors; justice-involved individuals seeking community support.",
        eligibility_es="Personas anteriormente encarceladas de Mississippi y mentores voluntarios; personas con antecedentes penales que buscan apoyo comunitario.",
        notes="Contact through marcreentry.org; volunteer mentor and class facilitator opportunities statewide.",
        notes_es="Contacte a través de marcreentry.org; oportunidades de mentoría voluntaria en todo el estado.",
        hours="Program hours vary; contact for volunteer orientation",
        tags="jackson|reentry-organizations|mentoring|advocacy|reentry",
        services="Volunteer mentoring|Reentry advocacy|Resource navigation|Community education|Support groups",
        county="Hinds", served_counties="", coverage="statewide",
        _source="https://www.marcreentry.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Mississippi Department of Employment Security — UI & Labor",
        category="state-agency", region="Statewide",
        description="The Mississippi Department of Employment Security administers unemployment insurance, labor market information, and WIN Job Center oversight statewide, connecting justice-involved job seekers to Mississippi Works services after release.",
        description_es="El Departamento de Seguridad del Empleo de Mississippi administra seguro de desempleo, información del mercado laboral y supervisión de WIN Job Centers en todo el estado.",
        address="1230 North State Street", city="Jackson", phone="601-321-6000", email="",
        website="https://mdes.ms.gov",
        eligibility="Mississippi workers and job seekers including justice-involved individuals; unemployment claims require work history.",
        eligibility_es="Trabajadores y buscadores de empleo de Mississippi incluidas personas con antecedentes penales; reclamaciones de desempleo requieren historial laboral.",
        notes="File unemployment at mdes.ms.gov; find WIN Job Centers through Mississippi Works.",
        notes_es="Presente desempleo en mdes.ms.gov; encuentre WIN Job Centers a través de Mississippi Works.",
        hours="Online 24/7; offices Monday–Friday",
        tags="statewide|state-agency|unemployment|WIN|reentry",
        services="Unemployment insurance|Labor market data|WIN Job Center oversight|Employment program coordination",
        county="Hinds", served_counties="", coverage="statewide",
        _source="https://mdes.ms.gov", _source_type="government", _confidence="high",
    )
    add(
        name="Mississippi State Department of Health — Public Health",
        category="state-agency", region="Statewide",
        description="The Mississippi State Department of Health operates county health departments, vital records, and public health programs connecting returning citizens to immunizations, WIC, and community health referrals across all 82 counties.",
        description_es="El Departamento de Salud del Estado de Mississippi opera departamentos de salud del condado, registros vitales y programas de salud pública que conectan a ciudadanos que regresan con inmunizaciones, WIC y referencias de salud comunitaria.",
        address="570 East Woodrow Wilson Avenue", city="Jackson", phone="601-576-7400", email="",
        website="https://msdh.ms.gov",
        eligibility="Mississippi residents; county health department services vary by location.",
        eligibility_es="Residentes de Mississippi; los servicios del departamento de salud del condado varían por ubicación.",
        notes="Vital records at msdh.ms.gov; find county health department locator online.",
        notes_es="Registros vitales en msdh.ms.gov; encuentre el localizador del departamento de salud del condado en línea.",
        hours="County health departments vary",
        tags="statewide|state-agency|public-health|vital-records|reentry",
        services="County health departments|Vital records|WIC referrals|Immunizations|Public health navigation",
        county="Hinds", served_counties="", coverage="statewide",
        _source="https://msdh.ms.gov", _source_type="government", _confidence="high",
    )
    add(
        name="Jackson Transit Authority — JTRAN",
        category="transportation", region="Jackson / Hinds County",
        description="Jackson Transit Authority JTRAN provides fixed-route bus service across Jackson and parts of Hinds County with reduced-fare options for seniors, disabled riders, and low-income residents including justice-involved adults traveling to WIN Job Centers and MDHS offices.",
        description_es="Jackson Transit Authority JTRAN ofrece servicio de autobús de ruta fija en Jackson y partes del condado Hinds con opciones de tarifa reducida para residentes de bajos ingresos.",
        address="320 West Woodrow Wilson Avenue", city="Jackson", phone="601-952-1000", email="",
        website="https://www.jacksonms.gov/jtran",
        eligibility="Open to all riders; reduced fares for qualifying seniors, disabled, and low-income riders.",
        eligibility_es="Abierto a todos los pasajeros; tarifas reducidas para mayores, discapacitados y de bajos ingresos que califiquen.",
        notes="Call 601-952-1000 for routes and reduced-fare application.",
        notes_es="Llame al 601-952-1000 para rutas y solicitud de tarifa reducida.",
        hours="Route hours vary; see schedule online",
        tags="jackson|hinds|transportation|transit|reentry",
        services="Fixed-route bus service|Reduced fares|Paratransit referrals|Route planning",
        county="Hinds", served_counties="Hinds", coverage="single",
        _source="https://www.jacksonms.gov/jtran", _source_type="government", _confidence="high",
    )
    add(
        name="Coast Transit Authority — Gulfport Biloxi",
        category="transportation", region="Gulfport / Harrison County",
        description="Coast Transit Authority provides public bus service along the Mississippi Gulf Coast connecting Gulfport, Biloxi, and Pass Christian for low-income riders including returning citizens accessing WIN Job Centers and Gulf Coast health providers.",
        description_es="Coast Transit Authority ofrece servicio de autobús público a lo largo de la Costa del Golfo de Mississippi conectando Gulfport, Biloxi y Pass Christian.",
        address="333 DeBuys Road", city="Gulfport", phone="228-896-8080", email="",
        website="https://www.coasttransit.com",
        eligibility="Open to all Gulf Coast riders; reduced fares available for qualifying riders.",
        eligibility_es="Abierto a todos los pasajeros de la Costa del Golfo; tarifas reducidas disponibles para quienes califiquen.",
        notes="Call 228-896-8080 for schedules; pairs with Harrison County WIN Job Center.",
        notes_es="Llame al 228-896-8080 para horarios.",
        hours="Route hours vary",
        tags="gulfport|harrison|transportation|transit|reentry",
        services="Public bus service|Reduced fares|Route planning|Coastal transit connections",
        county="Harrison", served_counties="Harrison|Jackson", coverage="multi",
        _source="https://www.coasttransit.com", _source_type="government", _confidence="high",
    )
    add(
        name="Mississippi Department of Transportation — Rural Transit",
        category="transportation", region="Statewide",
        description="Mississippi Department of Transportation supports rural public transit providers and demand-response services in counties without fixed-route systems, helping justice-involved residents in rural Mississippi reach WIN Job Centers, MDHS offices, and treatment appointments.",
        description_es="El Departamento de Transporte de Mississippi apoya proveedores de tránsito público rural y servicios de respuesta a la demanda en condados sin sistemas de ruta fija.",
        address="401 North West Street", city="Jackson", phone="601-359-7000", email="",
        website="https://mdot.ms.gov",
        eligibility="Mississippi residents in rural transit service areas; schedules vary by county provider.",
        eligibility_es="Residentes de Mississippi en áreas de servicio de tránsito rural; horarios varían por proveedor del condado.",
        notes="Find local rural transit provider at mdot.ms.gov public transit directory.",
        notes_es="Encuentre el proveedor de tránsito rural local en el directorio de tránsito público de mdot.ms.gov.",
        hours="Varies by county provider",
        tags="statewide|transportation|rural-transit|reentry",
        services="Rural transit directory|Demand-response referrals|Public transit coordination|County provider locator",
        county="Hinds", served_counties="", coverage="statewide",
        _source="https://mdot.ms.gov", _source_type="government", _confidence="high",
    )
    add(
        name="Mississippi Veterans Affairs — Gulf Coast Office",
        category="veterans", region="Gulfport / Harrison County",
        description="The Mississippi Veterans Affairs Gulf Coast office provides free VA benefits claims assistance and healthcare enrollment help for veterans in Harrison, Jackson, and Hancock counties including justice-involved veterans.",
        description_es="La oficina de la Costa del Golfo de Asuntos de Veteranos de Mississippi ofrece asistencia gratuita con reclamaciones de beneficios VA e inscripción en atención médica para veteranos.",
        address="400 Favre Street", city="Biloxi", phone="228-388-6850", email="",
        website="https://www.msva.ms.gov",
        eligibility="Veterans and eligible dependents in coastal Mississippi; service documentation required for VA claims.",
        eligibility_es="Veteranos y dependientes elegibles en el Mississippi costero; se requiere documentación de servicio.",
        notes="Call 228-388-6850 for appointment; pairs with Keesler VA and Back Bay Mission.",
        notes_es="Llame al 228-388-6850 para cita.",
        hours="Monday–Friday business hours",
        tags="biloxi|harrison|veterans|VA-benefits|reentry",
        services="VA benefits claims assistance|Healthcare enrollment|Disability navigation|Employment referrals",
        county="Harrison", served_counties="Harrison|Jackson|Hancock", coverage="multi",
        _source="https://www.msva.ms.gov", _source_type="government", _confidence="high",
    )
    add(
        name="Feeding the Gulf Coast — Mobile Pantry",
        category="basic-needs", region="Biloxi / Harrison County",
        description="Feeding the Gulf Coast operates mobile food pantries and emergency grocery distribution for low-income households in coastal Mississippi including justice-involved families rebuilding food security after release.",
        description_es="Feeding the Gulf Coast opera despensas móviles y distribución de comestibles de emergencia para hogares de bajos ingresos en el Mississippi costero incluidas familias con antecedentes penales.",
        address="5248 Mobile South Street", city="Theodore", phone="251-653-1617", email="",
        website="https://www.feedingthegulfcoast.org",
        eligibility="Low-income Gulf Coast residents; mobile pantry schedule online.",
        eligibility_es="Residentes de la Costa del Golfo de bajos ingresos; horario de despensa móvil en línea.",
        notes="Call 251-653-1617 or check feedingthegulfcoast.org mobile pantry calendar.",
        notes_es="Llame al 251-653-1617 o consulte el calendario de despensa móvil en feedingthegulfcoast.org.",
        hours="Mobile pantry schedule varies",
        tags="biloxi|harrison|basic-needs|food-pantry|reentry",
        services="Mobile food pantry|Emergency groceries|Partner agency network|Nutrition support",
        county="Harrison", served_counties="Harrison|Jackson|Hancock", coverage="multi",
        _source="https://www.feedingthegulfcoast.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Pearl River Community College — Adult Education",
        category="education", region="Poplarville / Pearl River County",
        description="Pearl River Community College Adult Education offers free GED and HSE preparation for adults in Pearl River, Lamar, and Forrest counties including justice-involved learners rebuilding credentials.",
        description_es="Pearl River Community College Educación para Adultos ofrece preparación GED y HSE gratuita para adultos en los condados Pearl River, Lamar y Forrest.",
        address="101 Highway 11 North", city="Poplarville", phone="601-403-1000", email="",
        website="https://www.prcc.edu",
        eligibility="Adults age 16+ in PRCC service area; free HSE classes.",
        eligibility_es="Adultos de 16+ años en el área de servicio de PRCC; clases HSE gratuitas.",
        notes="Call 601-403-1000; pairs with WIN Job Center Hattiesburg.",
        notes_es="Llame al 601-403-1000; se vincula con WIN Job Center Hattiesburg.",
        hours="Class schedules vary",
        tags="poplarville|pearl-river|education|GED|reentry",
        services="GED preparation|Adult Basic Education|Workforce referrals|College bridge",
        county="Pearl River", served_counties="Pearl River|Lamar|Forrest", coverage="multi",
        _source="https://www.prcc.edu", _source_type="government", _confidence="high",
    )
    add(
        name="Southwest Mississippi Community College — Adult Education",
        category="education", region="Summit / Pike County",
        description="Southwest Mississippi Community College Adult Education provides free GED and HSE classes for adults in Pike, Walthall, and Amite counties including justice-involved residents near MDOC facilities.",
        description_es="Southwest Mississippi Community College Educación para Adultos ofrece clases GED y HSE gratuitas para adultos en los condados Pike, Walthall y Amite.",
        address="1156 College Drive", city="Summit", phone="601-276-2000", email="",
        website="https://www.smcc.edu",
        eligibility="Adults age 16+ in SMCC service area; free HSE preparation.",
        eligibility_es="Adultos de 16+ años en el área de servicio de SMCC; preparación HSE gratuita.",
        notes="Call 601-276-2000; pairs with Southwest Mississippi CMHC.",
        notes_es="Llame al 601-276-2000; se vincula con Southwest Mississippi CMHC.",
        hours="Class schedules vary",
        tags="summit|pike|education|GED|reentry",
        services="GED preparation|Adult education|Workforce referrals|College transition",
        county="Pike", served_counties="Pike|Walthall|Amite", coverage="multi",
        _source="https://www.smcc.edu", _source_type="government", _confidence="high",
    )
    add(
        name="Copiah-Lincoln Community College — Adult Education",
        category="education", region="Wesson / Copiah County",
        description="Copiah-Lincoln Community College Adult Education offers free GED and HSE preparation for adults in Copiah, Lincoln, and Simpson counties including returning citizens rebuilding education credentials.",
        description_es="Copiah-Lincoln Community College Educación para Adultos ofrece preparación GED y HSE gratuita para adultos en los condados Copiah, Lincoln y Simpson.",
        address="1001 Co-Lin Lane", city="Wesson", phone="601-643-5101", email="",
        website="https://www.colin.edu",
        eligibility="Adults age 16+ in Co-Lin service area; free HSE classes.",
        eligibility_es="Adultos de 16+ años en el área de servicio de Co-Lin; clases HSE gratuitas.",
        notes="Call 601-643-5101; pairs with Region 8 Mental Health Services.",
        notes_es="Llame al 601-643-5101; se vincula con Region 8 Mental Health Services.",
        hours="Class schedules vary",
        tags="wesson|copiah|education|GED|reentry",
        services="GED preparation|Adult Basic Education|Workforce referrals",
        county="Copiah", served_counties="Copiah|Lincoln|Simpson", coverage="multi",
        _source="https://www.colin.edu", _source_type="government", _confidence="high",
    )
    add(
        name="Mississippi Center for Justice — Reentry Legal Clinic",
        category="legal-aid", region="Jackson / Hinds County",
        description="Mississippi Center for Justice provides civil legal advocacy for low-income Mississippians including housing, benefits, and limited record-related civil matters for justice-involved clients—not criminal defense.",
        description_es="Mississippi Center for Justice brinda defensa legal civil para personas de bajos ingresos de Mississippi incluyendo vivienda, beneficios y asuntos civiles limitados relacionados con antecedentes.",
        address="420 South President Street", city="Jackson", phone="601-352-2269", email="",
        website="https://www.mscenterforjustice.org",
        eligibility="Low-income Mississippi residents with civil legal needs; income screening required.",
        eligibility_es="Residentes de Mississippi de bajos ingresos con necesidades legales civiles; se requiere evaluación de ingresos.",
        notes="Call 601-352-2269; complements MCLS and MVLP statewide intake.",
        notes_es="Llame al 601-352-2269; complementa la admisión estatal de MCLS y MVLP.",
        hours="Monday–Friday business hours",
        tags="jackson|legal-aid|civil-rights|reentry",
        services="Housing legal advocacy|Benefits advocacy|Civil rights litigation|Record-related civil guidance",
        county="Hinds", served_counties="Hinds|Rankin|Madison", coverage="multi",
        _source="https://www.mscenterforjustice.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Mississippi Veterans Affairs — North Mississippi Office",
        category="veterans", region="Tupelo / Lee County",
        description="The Mississippi Veterans Affairs north Mississippi office assists veterans in Lee, Pontotoc, and surrounding counties with VA disability claims, healthcare enrollment, and referrals to WIN Job Centers and CMHC treatment providers.",
        description_es="La oficina del norte de Mississippi de Asuntos de Veteranos ayuda a veteranos en Lee, Pontotoc y condados circundantes con reclamaciones de discapacidad VA e inscripción en atención médica.",
        address="431 West Main Street", city="Tupelo", phone="662-840-5770", email="",
        website="https://www.msva.ms.gov",
        eligibility="Veterans and eligible dependents in north Mississippi; service documentation required.",
        eligibility_es="Veteranos y dependientes elegibles en el norte de Mississippi; se requiere documentación de servicio.",
        notes="Call 662-840-5770; pairs with NMRC Tupelo and WIN Job Center.",
        notes_es="Llame al 662-840-5770.",
        hours="Monday–Friday business hours",
        tags="tupelo|lee|veterans|VA-benefits|reentry",
        services="VA benefits claims assistance|Healthcare enrollment help|Disability compensation navigation|Employment referrals",
        county="Lee", served_counties="Lee|Pontotoc|Itawamba", coverage="multi",
        _source="https://www.msva.ms.gov", _source_type="government", _confidence="high",
    )
