"""Direct-service pins for Mississippi counties that need local depth beyond MDHS rows."""


def register_thin_counties(add):
    """Two or more program-level rows per thin rural county."""

    # --- Issaquena ---
    add(
        name="Greenville WIN Job Center (serves Issaquena County)",
        category="employment", region="Greenville / Washington County",
        description="The Greenville WIN Job Center is the nearest Mississippi Department of Employment Security career center for Issaquena County job seekers—including justice-involved adults after MDOC release—offering resume coaching, WIOA training referrals, and fair-chance employment navigation. Issaquena residents travel to Greenville for in-person services; register online at mdes.ms.gov. Free core career services—not emergency cash or housing placement.",
        description_es="El Greenville WIN Job Center es el centro de carreras MDES más cercano para buscadores de empleo del condado Issaquena—incluidos adultos con antecedentes penales—con coaching de currículum y referencias WIOA. Los residentes de Issaquena viajan a Greenville para servicios en persona; regístrese en mdes.ms.gov.",
        address="1746 Highway 1, Suite C", city="Greenville", phone="662-379-7404", email="",
        website="https://mdes.ms.gov/win-job-centers/greenville-win-job-center/",
        eligibility="Open to Issaquena County job seekers including justice-involved individuals; core Mississippi Works services are free.",
        eligibility_es="Abierto a buscadores de empleo del condado Issaquena incluidas personas con antecedentes penales; servicios básicos gratuitos.",
        notes="Issaquena County is served by the Greenville WIN Job Center; call 662-379-7404 or register at mdes.ms.gov.",
        notes_es="El condado Issaquena es atendido por el Greenville WIN Job Center; llame al 662-379-7404 o regístrese en mdes.ms.gov.",
        hours="Monday–Friday 8:00 a.m.–5:00 p.m.; Wednesday closes at 4:00 p.m.",
        tags="issaquena|greenville|employment|WIN|WIOA|reentry|fair-chance",
        services="Job search assistance|Resume preparation|WIOA training referrals|Fair-chance employment|Career coaching",
        county="Issaquena", served_counties="Issaquena", coverage="single",
        _source="https://mdes.ms.gov/win-job-centers/greenville-win-job-center/", _source_type="government", _confidence="high",
    )
    add(
        name="Delta Health Alliance — Issaquena Outreach",
        category="healthcare", region="Greenville / Washington County",
        description="Delta Health Alliance operates community health outreach and clinic partnerships serving Issaquena County residents including uninsured and Medicaid patients such as returning citizens establishing medical care after release from MDOC custody. FQHC referral navigation—not a walk-in benefits or probation office.",
        description_es="Delta Health Alliance opera alcance de salud comunitaria y alianzas con clínicas que sirven a residentes del condado Issaquena incluidos pacientes sin seguro y Medicaid como ciudadanos que regresan que establecen atención médica después de la liberación.",
        address="141 South Main Street", city="Greenville", phone="662-335-0456", email="",
        website="https://www.deltahealthalliance.org",
        eligibility="Issaquena County residents; sliding-fee and Medicaid patients welcome including justice-involved adults.",
        eligibility_es="Residentes del condado Issaquena; pacientes con tarifa móvil y Medicaid bienvenidos incluidos adultos con antecedentes penales.",
        notes="Call 662-335-0456 for nearest clinic referral; Greenville hub serves Issaquena outreach.",
        notes_es="Llame al 662-335-0456 para referencia a la clínica más cercana; centro Greenville sirve alcance Issaquena.",
        hours="Monday–Friday business hours",
        tags="issaquena|healthcare|delta|FQHC|primary-care|reentry",
        services="Primary care referrals|Health navigation|Chronic disease management|Medicaid enrollment referrals|Community outreach",
        county="Issaquena", served_counties="Issaquena|Sharkey|Washington", coverage="multi",
        _source="https://www.deltahealthalliance.org", _source_type="nonprofit", _confidence="high",
    )

    # --- Sharkey ---
    add(
        name="Greenville WIN Job Center (serves Sharkey County)",
        category="employment", region="Greenville / Washington County",
        description="The Greenville WIN Job Center serves Sharkey County job seekers—including justice-involved adults from Rolling Fork and MDOC release—with resume coaching, WIOA training referrals, and fair-chance employment navigation through Mississippi Works. Sharkey residents use the Greenville office at 1746 Highway 1; register at mdes.ms.gov.",
        description_es="El Greenville WIN Job Center sirve a buscadores de empleo del condado Sharkey—incluidos adultos con antecedentes penales de Rolling Fork—con coaching de currículum y referencias WIOA a través de Mississippi Works.",
        address="1746 Highway 1, Suite C", city="Greenville", phone="662-379-7404", email="",
        website="https://mdes.ms.gov/win-job-centers/greenville-win-job-center/",
        eligibility="Open to Sharkey County job seekers including justice-involved individuals; core services free.",
        eligibility_es="Abierto a buscadores de empleo del condado Sharkey incluidas personas con antecedentes penales; servicios básicos gratuitos.",
        notes="Sharkey County is served by the Greenville WIN Job Center; call 662-379-7404.",
        notes_es="El condado Sharkey es atendido por el Greenville WIN Job Center; llame al 662-379-7404.",
        hours="Monday–Friday 8:00 a.m.–5:00 p.m.; Wednesday closes at 4:00 p.m.",
        tags="sharkey|greenville|employment|WIN|WIOA|reentry",
        services="Job search assistance|Resume coaching|WIOA referrals|Fair-chance employment|Career workshops",
        county="Sharkey", served_counties="Sharkey", coverage="single",
        _source="https://mdes.ms.gov/win-job-centers/greenville-win-job-center/", _source_type="government", _confidence="high",
    )
    add(
        name="WWISCAA — Sharkey-Issaquena Services",
        category="food-nutrition", region="Rolling Fork / Sharkey County",
        description="Warren-Washington-Issaquena-Sharkey Community Action Agency (WWISCAA) distributes emergency food boxes, LIHEAP energy assistance, and basic needs navigation for low-income Sharkey and Issaquena county residents including returning citizens reestablishing food security after release from MDOC custody or county jail.",
        description_es="WWISCAA distribuye cajas de alimentos de emergencia, asistencia energética LIHEAP y navegación de necesidades básicas para residentes de bajos ingresos de los condados Sharkey e Issaquena incluidos ciudadanos que regresan.",
        address="297 West Race Street", city="Rolling Fork", phone="662-873-4031", email="",
        website="https://www.wwiscaa.net",
        eligibility="Low-income Sharkey and Issaquena county residents; justice-involved clients welcome.",
        eligibility_es="Residentes de bajos ingresos de los condados Sharkey e Issaquena; clientes con antecedentes penales bienvenidos.",
        notes="Call 662-873-4031 for food and utility assistance; admin office at 1538 Old Leland Road, Greenville.",
        notes_es="Llame al 662-873-4031 para asistencia alimentaria y de servicios públicos; oficina administrativa en Greenville.",
        hours="Monday–Friday business hours",
        tags="sharkey|food-nutrition|community-action|basic-needs|reentry",
        services="Emergency food boxes|LIHEAP energy assistance|Basic needs navigation|SNAP enrollment referrals",
        county="Sharkey", served_counties="Sharkey|Issaquena", coverage="multi",
        _source="https://www.wwiscaa.net", _source_type="nonprofit", _confidence="high",
    )

    # --- Jefferson ---
    add(
        name="Natchez WIN Job Center (serves Jefferson County)",
        category="employment", region="Natchez / Adams County",
        description="The Natchez WIN Job Center serves Jefferson County job seekers—including justice-involved adults from Fayette and MDOC release—with resume coaching, WIOA training referrals, and fair-chance employment navigation. Jefferson County residents use the Natchez office; register at mdes.ms.gov.",
        description_es="El Natchez WIN Job Center sirve a buscadores de empleo del condado Jefferson—incluidos adultos con antecedentes penales de Fayette—con coaching de currículum y referencias WIOA.",
        address="107 Colonel John Pitchford Parkway", city="Natchez", phone="601-442-0243", email="",
        website="https://mdes.ms.gov/win-job-centers/natchez-win-job-center/",
        eligibility="Open to Jefferson County job seekers including justice-involved individuals; core services free.",
        eligibility_es="Abierto a buscadores de empleo del condado Jefferson incluidas personas con antecedentes penales; servicios básicos gratuitos.",
        notes="Jefferson County is served by the Natchez WIN Job Center; call 601-442-0243.",
        notes_es="El condado Jefferson es atendido por el Natchez WIN Job Center; llame al 601-442-0243.",
        hours="Monday–Friday 8:00 a.m.–5:00 p.m.; Wednesday closes at 4:00 p.m.",
        tags="jefferson|natchez|employment|WIN|WIOA|reentry",
        services="Job search assistance|Resume coaching|WIOA referrals|Fair-chance employment|Career coaching",
        county="Jefferson", served_counties="Jefferson", coverage="single",
        _source="https://mdes.ms.gov/win-job-centers/natchez-win-job-center/", _source_type="government", _confidence="high",
    )
    add(
        name="Southwest Mississippi Regional Medical Center",
        category="healthcare", region="McComb / Pike County",
        description="Southwest Mississippi Regional Medical Center provides primary care, emergency services, and community health outreach for Jefferson, Franklin, and southwest Mississippi residents including uninsured and Medicaid patients such as returning citizens establishing local medical care after release from MDOC custody or county jails.",
        description_es="Southwest Mississippi Regional Medical Center brinda atención primaria, servicios de emergencia y alcance de salud comunitaria para residentes de Jefferson, Franklin y suroeste de Mississippi incluidos pacientes sin seguro y Medicaid como ciudadanos que regresan.",
        address="1225 North Front Street", city="McComb", phone="601-249-5500", email="",
        website="https://www.smrmc.com",
        eligibility="Southwest Mississippi residents; sliding-fee and Medicaid patients welcome including justice-involved adults.",
        eligibility_es="Residentes del suroeste de Mississippi; pacientes con tarifa móvil y Medicaid bienvenidos incluidos adultos con antecedentes penales.",
        notes="Call 601-249-5500 for appointments; emergency 24/7; serves Jefferson County outreach from McComb hub.",
        notes_es="Llame al 601-249-5500 para citas; emergencias 24/7; sirve alcance del condado Jefferson desde McComb.",
        hours="Emergency 24/7; clinic hours vary",
        tags="jefferson|healthcare|rural|reentry",
        services="Primary care|Emergency services|Community health outreach|Sliding-fee care|Specialist referrals",
        county="Jefferson", served_counties="Jefferson|Franklin|Adams|Wilkinson", coverage="multi",
        _source="https://www.smrmc.com", _source_type="nonprofit", _confidence="high",
    )

    # --- Wilkinson ---
    add(
        name="Natchez WIN Job Center (serves Wilkinson County)",
        category="employment", region="Natchez / Adams County",
        description="The Natchez WIN Job Center serves Wilkinson County job seekers—including justice-involved adults from Woodville and MDOC release—with resume coaching, WIOA training referrals, and fair-chance employment navigation. Wilkinson residents use the Natchez office; register at mdes.ms.gov.",
        description_es="El Natchez WIN Job Center sirve a buscadores de empleo del condado Wilkinson—incluidos adultos con antecedentes penales de Woodville—con coaching de currículum y referencias WIOA.",
        address="107 Colonel John Pitchford Parkway", city="Natchez", phone="601-442-0243", email="",
        website="https://mdes.ms.gov/win-job-centers/natchez-win-job-center/",
        eligibility="Open to Wilkinson County job seekers including justice-involved individuals; core services free.",
        eligibility_es="Abierto a buscadores de empleo del condado Wilkinson incluidas personas con antecedentes penales; servicios básicos gratuitos.",
        notes="Wilkinson County is served by the Natchez WIN Job Center; call 601-442-0243.",
        notes_es="El condado Wilkinson es atendido por el Natchez WIN Job Center; llame al 601-442-0243.",
        hours="Monday–Friday 8:00 a.m.–5:00 p.m.; Wednesday closes at 4:00 p.m.",
        tags="wilkinson|natchez|employment|WIN|WIOA|reentry",
        services="Job search assistance|Resume coaching|WIOA referrals|Fair-chance employment|Career workshops",
        county="Wilkinson", served_counties="Wilkinson", coverage="single",
        _source="https://mdes.ms.gov/win-job-centers/natchez-win-job-center/", _source_type="government", _confidence="high",
    )
    add(
        name="Field Memorial Community Hospital",
        category="healthcare", region="Centreville / Wilkinson County",
        description="Field Memorial Community Hospital is a 25-bed critical access hospital owned by Wilkinson and Amite counties, providing emergency, inpatient, and outpatient care for Wilkinson County residents including uninsured and Medicaid patients such as returning citizens establishing local medical access after release from MDOC custody. Clinics also operate in Woodville.",
        description_es="Field Memorial Community Hospital es un hospital de acceso crítico de 25 camas propiedad de los condados Wilkinson y Amite que ofrece atención de emergencia, hospitalaria y ambulatoria para residentes del condado Wilkinson incluidos pacientes sin seguro y Medicaid como ciudadanos que regresan.",
        address="178 Highway 24 East", city="Centreville", phone="601-645-5221", email="",
        website="https://www.fieldhealth.org",
        eligibility="Wilkinson and Amite county patients; emergency care regardless of ability to pay; Medicaid accepted.",
        eligibility_es="Pacientes de los condados Wilkinson y Amite; atención de emergencia sin importar capacidad de pago; se acepta Medicaid.",
        notes="Call 601-645-5221; emergency 24/7; Catchings Clinic serves Woodville.",
        notes_es="Llame al 601-645-5221; emergencias 24/7; Catchings Clinic sirve Woodville.",
        hours="Emergency 24/7; outpatient Monday–Friday",
        tags="wilkinson|healthcare|rural|reentry",
        services="Emergency services|Primary care|Inpatient care|Outpatient clinics|Financial assistance",
        county="Wilkinson", served_counties="Wilkinson|Amite", coverage="multi",
        _source="https://www.fieldhealth.org", _source_type="nonprofit", _confidence="high",
    )

    # --- Quitman ---
    add(
        name="Greenwood WIN Job Center (serves Quitman County)",
        category="employment", region="Greenwood / Leflore County",
        description="The Greenwood WIN Job Center serves Quitman County job seekers—including justice-involved adults from Marks and MDOC release—with resume coaching, WIOA training referrals, and fair-chance employment navigation. Quitman residents travel to Greenwood for in-person services; register at mdes.ms.gov.",
        description_es="El Greenwood WIN Job Center sirve a buscadores de empleo del condado Quitman—incluidos adultos con antecedentes penales de Marks—con coaching de currículum y referencias WIOA.",
        address="812 West Park Avenue", city="Greenwood", phone="662-459-4600", email="",
        website="https://mdes.ms.gov/win-job-centers/greenwood-win-job-center/",
        eligibility="Open to Quitman County job seekers including justice-involved individuals; core services free.",
        eligibility_es="Abierto a buscadores de empleo del condado Quitman incluidas personas con antecedentes penales; servicios básicos gratuitos.",
        notes="Quitman County is served by the Greenwood WIN Job Center; call 662-459-4600.",
        notes_es="El condado Quitman es atendido por el Greenwood WIN Job Center; llame al 662-459-4600.",
        hours="Monday–Friday 8:00 a.m.–5:00 p.m.",
        tags="quitman|greenwood|employment|WIN|WIOA|reentry",
        services="Job search assistance|Resume coaching|WIOA referrals|Fair-chance employment|Career coaching",
        county="Quitman", served_counties="Quitman", coverage="single",
        _source="https://mdes.ms.gov/win-job-centers/greenwood-win-job-center/", _source_type="government", _confidence="high",
    )
    add(
        name="Region I Mental Health Center — Quitman County Office",
        category="healthcare", region="Marks / Quitman County",
        description="Region I Mental Health Center's Quitman County office in Marks provides outpatient mental health and substance use treatment for Quitman, Panola, and upper Delta residents including justice-involved adults referred by MDOC probation and drug courts. Medicaid and sliding-fee services support treatment continuity after release.",
        description_es="La oficina del condado Quitman de Region I Mental Health Center en Marks ofrece tratamiento ambulatorio de salud mental y uso de sustancias para residentes de Quitman, Panola y el Delta superior incluidos adultos con antecedentes penales referidos por probatoria MDOC.",
        address="400 Locust Street", city="Marks", phone="662-326-4445", email="",
        website="https://www.region1mhc.org",
        eligibility="Quitman County and Region 1 service area residents; Medicaid and sliding-fee accepted.",
        eligibility_es="Residentes del condado Quitman y área de servicio Region 1; se aceptan Medicaid y tarifa móvil.",
        notes="Call 662-326-4445 for intake; satellite of Region I Mental Health Center Clarksdale.",
        notes_es="Llame al 662-326-4445 para admisión; satélite de Region I Mental Health Center Clarksdale.",
        hours="Monday–Friday clinic hours",
        tags="quitman|substance-use-treatment|mental-health|reentry",
        services="Outpatient mental health|Substance use treatment|Crisis intervention|Case management|Probation referrals",
        county="Quitman", served_counties="Quitman|Panola|Tallahatchie", coverage="multi",
        _source="https://www.region1mhc.org", _source_type="nonprofit", _confidence="high",
    )

    # --- Kemper ---
    add(
        name="Meridian WIN Job Center (serves Kemper County)",
        category="employment", region="Meridian / Lauderdale County",
        description="The Meridian WIN Job Center serves Kemper County job seekers—including justice-involved adults from De Kalb and MDOC release—with resume coaching, WIOA training referrals, and fair-chance employment navigation. Kemper residents travel to Meridian for in-person services; register at mdes.ms.gov.",
        description_es="El Meridian WIN Job Center sirve a buscadores de empleo del condado Kemper—incluidos adultos con antecedentes penales de De Kalb—con coaching de currículum y referencias WIOA.",
        address="1228 22nd Avenue", city="Meridian", phone="601-483-5016", email="",
        website="https://mdes.ms.gov/win-job-centers/meridian-win-job-center/",
        eligibility="Open to Kemper County job seekers including justice-involved individuals; core services free.",
        eligibility_es="Abierto a buscadores de empleo del condado Kemper incluidas personas con antecedentes penales; servicios básicos gratuitos.",
        notes="Kemper County is served by the Meridian WIN Job Center; call 601-483-5016.",
        notes_es="El condado Kemper es atendido por el Meridian WIN Job Center; llame al 601-483-5016.",
        hours="Monday–Friday 8:00 a.m.–5:00 p.m.",
        tags="kemper|meridian|employment|WIN|WIOA|reentry",
        services="Job search assistance|Resume coaching|WIOA referrals|Fair-chance employment|Career workshops",
        county="Kemper", served_counties="Kemper", coverage="single",
        _source="https://mdes.ms.gov/win-job-centers/meridian-win-job-center/", _source_type="government", _confidence="high",
    )
    add(
        name="Ochsner Stennis Hospital",
        category="healthcare", region="De Kalb / Kemper County",
        description="Ochsner Stennis Hospital is a 25-bed critical access hospital in De Kalb providing emergency, inpatient, and outpatient care for Kemper County residents including uninsured and Medicaid patients such as returning citizens establishing local medical care after release from MDOC custody.",
        description_es="Ochsner Stennis Hospital es un hospital de acceso crítico de 25 camas en De Kalb que ofrece atención de emergencia, hospitalaria y ambulatoria para residentes del condado Kemper incluidos pacientes sin seguro y Medicaid como ciudadanos que regresan.",
        address="14365 Highway 16 West", city="De Kalb", phone="769-486-1000", email="",
        website="https://www.ochsner.org/locations/ochsner-stennis-hospital/",
        eligibility="Kemper County patients; emergency care regardless of ability to pay; Medicaid accepted.",
        eligibility_es="Pacientes del condado Kemper; atención de emergencia sin importar capacidad de pago; se acepta Medicaid.",
        notes="Call 769-486-1000; emergency 24/7; outpatient health center at 30 Ponderosa Avenue, De Kalb.",
        notes_es="Llame al 769-486-1000; emergencias 24/7.",
        hours="Emergency 24/7; outpatient hours vary",
        tags="kemper|healthcare|rural|reentry",
        services="Emergency services|Primary care|Inpatient care|Outpatient rehabilitation|Financial assistance",
        county="Kemper", served_counties="Kemper", coverage="single",
        _source="https://www.ochsner.org/locations/ochsner-stennis-hospital/", _source_type="nonprofit", _confidence="high",
    )

    # --- Clarke ---
    add(
        name="Meridian WIN Job Center (serves Clarke County)",
        category="employment", region="Meridian / Lauderdale County",
        description="The Meridian WIN Job Center serves Clarke County job seekers—including justice-involved adults from Quitman and MDOC release—with resume coaching, WIOA training referrals, and fair-chance employment navigation. Clarke residents travel to Meridian for in-person services; register at mdes.ms.gov.",
        description_es="El Meridian WIN Job Center sirve a buscadores de empleo del condado Clarke—incluidos adultos con antecedentes penales de Quitman—con coaching de currículum y referencias WIOA.",
        address="1228 22nd Avenue", city="Meridian", phone="601-483-5016", email="",
        website="https://mdes.ms.gov/win-job-centers/meridian-win-job-center/",
        eligibility="Open to Clarke County job seekers including justice-involved individuals; core services free.",
        eligibility_es="Abierto a buscadores de empleo del condado Clarke incluidas personas con antecedentes penales; servicios básicos gratuitos.",
        notes="Clarke County is served by the Meridian WIN Job Center; call 601-483-5016.",
        notes_es="El condado Clarke es atendido por el Meridian WIN Job Center; llame al 601-483-5016.",
        hours="Monday–Friday 8:00 a.m.–5:00 p.m.",
        tags="clarke|meridian|employment|WIN|WIOA|reentry",
        services="Job search assistance|Resume coaching|WIOA referrals|Fair-chance employment|Career coaching",
        county="Clarke", served_counties="Clarke", coverage="single",
        _source="https://mdes.ms.gov/win-job-centers/meridian-win-job-center/", _source_type="government", _confidence="high",
    )
    add(
        name="Ochsner Watkins Hospital",
        category="healthcare", region="Quitman / Clarke County",
        description="Ochsner Watkins Hospital is a 25-bed critical access hospital in Quitman providing emergency, inpatient, and outpatient care for Clarke County residents including uninsured and Medicaid patients such as returning citizens establishing local medical access after release from MDOC custody or county jail.",
        description_es="Ochsner Watkins Hospital es un hospital de acceso crítico de 25 camas en Quitman que ofrece atención de emergencia, hospitalaria y ambulatoria para residentes del condado Clarke incluidos pacientes sin seguro y Medicaid como ciudadanos que regresan.",
        address="605 South Archusa Avenue", city="Quitman", phone="601-776-6925", email="",
        website="https://www.ochsner.org/locations/ochsner-watkins-hospital/",
        eligibility="Clarke County patients; emergency care regardless of ability to pay; Medicaid accepted.",
        eligibility_es="Pacientes del condado Clarke; atención de emergencia sin importar capacidad de pago; se acepta Medicaid.",
        notes="Call 601-776-6925; emergency 24/7.",
        notes_es="Llame al 601-776-6925; emergencias 24/7.",
        hours="Emergency 24/7; outpatient Monday–Friday",
        tags="clarke|healthcare|rural|reentry",
        services="Emergency services|Primary care|Inpatient care|Outpatient rehabilitation|Financial assistance",
        county="Clarke", served_counties="Clarke", coverage="single",
        _source="https://www.ochsner.org/locations/ochsner-watkins-hospital/", _source_type="nonprofit", _confidence="high",
    )

    # --- Humphreys ---
    add(
        name="Greenwood WIN Job Center (serves Humphreys County)",
        category="employment", region="Greenwood / Leflore County",
        description="The Greenwood WIN Job Center serves Humphreys County job seekers—including justice-involved adults from Belzoni and MDOC release—with resume coaching, WIOA training referrals, and fair-chance employment navigation. Humphreys residents travel to Greenwood for in-person services; register at mdes.ms.gov.",
        description_es="El Greenwood WIN Job Center sirve a buscadores de empleo del condado Humphreys—incluidos adultos con antecedentes penales de Belzoni—con coaching de currículum y referencias WIOA.",
        address="812 West Park Avenue", city="Greenwood", phone="662-459-4600", email="",
        website="https://mdes.ms.gov/win-job-centers/greenwood-win-job-center/",
        eligibility="Open to Humphreys County job seekers including justice-involved individuals; core services free.",
        eligibility_es="Abierto a buscadores de empleo del condado Humphreys incluidas personas con antecedentes penales; servicios básicos gratuitos.",
        notes="Humphreys County is served by the Greenwood WIN Job Center; call 662-459-4600.",
        notes_es="El condado Humphreys es atendido por el Greenwood WIN Job Center; llame al 662-459-4600.",
        hours="Monday–Friday 8:00 a.m.–5:00 p.m.",
        tags="humphreys|greenwood|employment|WIN|WIOA|reentry|delta",
        services="Job search assistance|Resume coaching|WIOA referrals|Fair-chance employment|Career coaching",
        county="Humphreys", served_counties="Humphreys", coverage="single",
        _source="https://mdes.ms.gov/win-job-centers/greenwood-win-job-center/", _source_type="government", _confidence="high",
    )
    add(
        name="Greenwood Leflore Hospital",
        category="healthcare", region="Greenwood / Leflore County",
        description="Greenwood Leflore Hospital is the nearest full-service hospital for Humphreys County residents after the Belzoni hospital closed, providing emergency, inpatient, and outpatient care including uninsured and Medicaid patients such as returning citizens establishing medical access after release from MDOC custody.",
        description_es="Greenwood Leflore Hospital es el hospital de servicio completo más cercano para residentes del condado Humphreys después del cierre del hospital de Belzoni, ofreciendo atención de emergencia, hospitalaria y ambulatoria incluidos pacientes sin seguro y Medicaid como ciudadanos que regresan.",
        address="1530 Highway 82 East", city="Greenwood", phone="662-459-7000", email="",
        website="https://www.glh.org",
        eligibility="Delta region patients including Humphreys County; emergency care regardless of ability to pay; Medicaid accepted.",
        eligibility_es="Pacientes de la región Delta incluido el condado Humphreys; atención de emergencia sin importar capacidad de pago; se acepta Medicaid.",
        notes="Humphreys County has no operating hospital; nearest emergency care is Greenwood Leflore Hospital—call 662-459-7000.",
        notes_es="El condado Humphreys no tiene hospital operativo; la atención de emergencia más cercana es Greenwood Leflore Hospital—llame al 662-459-7000.",
        hours="Emergency 24/7",
        tags="humphreys|healthcare|delta|rural|reentry",
        services="Emergency services|Inpatient care|Outpatient clinics|Financial assistance|Specialist referrals",
        county="Humphreys", served_counties="Humphreys|Leflore|Sunflower", coverage="multi",
        _source="https://www.glh.org", _source_type="nonprofit", _confidence="high",
    )

    # --- Jefferson Davis ---
    add(
        name="Hattiesburg WIN Job Center (serves Jefferson Davis County)",
        category="employment", region="Hattiesburg / Forrest County",
        description="The Hattiesburg WIN Job Center serves Jefferson Davis County job seekers—including justice-involved adults from Prentiss and MDOC release—with resume coaching, WIOA training referrals, and fair-chance employment navigation. Jefferson Davis residents travel to Hattiesburg for in-person services; register at mdes.ms.gov.",
        description_es="El Hattiesburg WIN Job Center sirve a buscadores de empleo del condado Jefferson Davis—incluidos adultos con antecedentes penales de Prentiss—con coaching de currículum y referencias WIOA.",
        address="1911 Arcadia Street", city="Hattiesburg", phone="601-584-1202", email="",
        website="https://mdes.ms.gov/win-job-centers/hattiesburg-win-job-center/",
        eligibility="Open to Jefferson Davis County job seekers including justice-involved individuals; core services free.",
        eligibility_es="Abierto a buscadores de empleo del condado Jefferson Davis incluidas personas con antecedentes penales; servicios básicos gratuitos.",
        notes="Jefferson Davis County is served by the Hattiesburg WIN Job Center; call 601-584-1202.",
        notes_es="El condado Jefferson Davis es atendido por el Hattiesburg WIN Job Center; llame al 601-584-1202.",
        hours="Monday–Friday 8:00 a.m.–5:00 p.m.; Wednesday closes at 4:00 p.m.",
        tags="jefferson-davis|hattiesburg|employment|WIN|WIOA|reentry",
        services="Job search assistance|Resume coaching|WIOA referrals|Fair-chance employment|Career coaching",
        county="Jefferson Davis", served_counties="Jefferson Davis", coverage="single",
        _source="https://mdes.ms.gov/win-job-centers/hattiesburg-win-job-center/", _source_type="government", _confidence="high",
    )
    add(
        name="Jefferson Davis Community Hospital",
        category="healthcare", region="Prentiss / Jefferson Davis County",
        description="Jefferson Davis Community Hospital provides primary care, emergency services, and community health outreach for Jefferson Davis County residents including uninsured and Medicaid patients such as returning citizens establishing local medical access after release from MDOC custody or county jail.",
        description_es="Jefferson Davis Community Hospital brinda atención primaria, servicios de emergencia y alcance de salud comunitaria para residentes del condado Jefferson Davis incluidos pacientes sin seguro y Medicaid como ciudadanos que regresan.",
        address="1109 13th Street", city="Prentiss", phone="601-792-4276", email="",
        website="https://www.jdch.org",
        eligibility="Open to Jefferson Davis County residents; Medicaid and sliding-fee patients welcome including justice-involved adults.",
        eligibility_es="Abierto a residentes del condado Jefferson Davis; pacientes Medicaid y tarifa móvil bienvenidos incluidos adultos con antecedentes penales.",
        notes="Call 601-792-4276 for appointments; emergency 24/7.",
        notes_es="Llame al 601-792-4276 para citas; emergencias 24/7.",
        hours="Emergency 24/7; clinic hours vary",
        tags="jefferson-davis|healthcare|rural|reentry",
        services="Primary care|Emergency services|Community health outreach|Sliding-fee care|Specialist referrals",
        county="Jefferson Davis", served_counties="Jefferson Davis", coverage="single",
        _source="https://www.jdch.org", _source_type="nonprofit", _confidence="high",
    )

    # --- Perry ---
    add(
        name="Hattiesburg WIN Job Center (serves Perry County)",
        category="employment", region="Hattiesburg / Forrest County",
        description="The Hattiesburg WIN Job Center serves Perry County job seekers—including justice-involved adults from New Augusta and Richton and MDOC release—with resume coaching, WIOA training referrals, and fair-chance employment navigation. Perry residents travel to Hattiesburg for in-person services; register at mdes.ms.gov.",
        description_es="El Hattiesburg WIN Job Center sirve a buscadores de empleo del condado Perry—incluidos adultos con antecedentes penales de New Augusta y Richton—con coaching de currículum y referencias WIOA.",
        address="1911 Arcadia Street", city="Hattiesburg", phone="601-584-1202", email="",
        website="https://mdes.ms.gov/win-job-centers/hattiesburg-win-job-center/",
        eligibility="Open to Perry County job seekers including justice-involved individuals; core services free.",
        eligibility_es="Abierto a buscadores de empleo del condado Perry incluidas personas con antecedentes penales; servicios básicos gratuitos.",
        notes="Perry County is served by the Hattiesburg WIN Job Center; call 601-584-1202.",
        notes_es="El condado Perry es atendido por el Hattiesburg WIN Job Center; llame al 601-584-1202.",
        hours="Monday–Friday 8:00 a.m.–5:00 p.m.; Wednesday closes at 4:00 p.m.",
        tags="perry|hattiesburg|employment|WIN|WIOA|reentry",
        services="Job search assistance|Resume coaching|WIOA referrals|Fair-chance employment|Career coaching",
        county="Perry", served_counties="Perry", coverage="single",
        _source="https://mdes.ms.gov/win-job-centers/hattiesburg-win-job-center/", _source_type="government", _confidence="high",
    )
    add(
        name="Perry County General Hospital",
        category="healthcare", region="Richton / Perry County",
        description="Perry County General Hospital is a rural emergency hospital in Richton providing 24-hour emergency care, outpatient diagnostics, and rehabilitation for Perry County residents including uninsured and Medicaid patients such as returning citizens establishing local medical care after release from MDOC custody.",
        description_es="Perry County General Hospital es un hospital de emergencia rural en Richton que ofrece atención de emergencia 24 horas, diagnósticos ambulatorios y rehabilitación para residentes del condado Perry incluidos pacientes sin seguro y Medicaid como ciudadanos que regresan.",
        address="206 Bay Avenue", city="Richton", phone="601-788-6316", email="",
        website="https://www.forresthealth.org/our-locations/locations-profile/perry-county-general-hospital/",
        eligibility="Perry County patients; emergency care regardless of ability to pay; Medicaid accepted.",
        eligibility_es="Pacientes del condado Perry; atención de emergencia sin importar capacidad de pago; se acepta Medicaid.",
        notes="Call 601-788-6316; emergency 24/7; primary care through The Doctors Clinic on site.",
        notes_es="Llame al 601-788-6316; emergencias 24/7; atención primaria a través de The Doctors Clinic en el sitio.",
        hours="Emergency 24/7; clinic hours vary",
        tags="perry|healthcare|rural|reentry",
        services="Emergency services|Outpatient diagnostics|Rehabilitation|Primary care referrals|Financial assistance",
        county="Perry", served_counties="Perry", coverage="single",
        _source="https://www.forresthealth.org/our-locations/locations-profile/perry-county-general-hospital/", _source_type="nonprofit", _confidence="high",
    )
