"""Phase 4 program-level expansion entries for Mississippi reentry resources."""


def register_phase4(add):
    # --- housing ---
    add(
        name="Doors of Hope — Transitional Housing",
        category="housing", region="Jackson / Hinds County",
        description="Doors of Hope provides structured transitional housing and case management for justice-involved women and mothers reunifying with children after release from MDOC custody or Hinds County Jail in the Jackson metro. Housing specialists connect residents to access.ms.gov benefits, Mississippi Works, and Hinds Behavioral Health while stabilizing leases and family reunification plans.",
        description_es="Doors of Hope ofrece vivienda transicional estructurada y manejo de casos para mujeres con antecedentes penales y madres que se reunifican con sus hijos después de la liberación de custodia MDOC o la cárcel del condado Hinds en el metro de Jackson.",
        address="4500 Terry Road", city="Jackson", phone="601-362-4999", email="",
        website="https://www.doorsofhopems.org",
        eligibility="Justice-involved women and mothers in the Jackson metro; referral or application required; sobriety requirements may apply.",
        eligibility_es="Mujeres con antecedentes penales y madres en el metro de Jackson; se requiere referencia o solicitud; pueden aplicar requisitos de sobriedad.",
        notes="Call 601-362-4999 for intake; pairs with Catholic Charities Jackson and Gateway Rescue Mission.",
        notes_es="Llame al 601-362-4999 para admisión; se vincula con Catholic Charities Jackson y Gateway Rescue Mission.",
        hours="Contact for intake hours",
        tags="jackson|hinds|housing|transitional|women|reentry",
        services="Transitional housing|Case management|Family reunification support|Benefits navigation|Employment referrals",
        county="Hinds", served_counties="Hinds|Madison|Rankin", coverage="multi",
        _source="https://www.doorsofhopems.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Salvation Army — Center of Hope Jackson",
        category="housing", region="Jackson / Hinds County",
        description="The Salvation Army Center of Hope in Jackson provides emergency shelter, meals, and case management for men, women, and families experiencing homelessness in the Jackson metro including returning citizens with nowhere else to go after release. Case managers connect residents to Mississippi Works, access.ms.gov benefits, and permanent housing programs.",
        description_es="El Center of Hope del Ejército de Salvación en Jackson proporciona refugio de emergencia, comidas y manejo de casos para hombres, mujeres y familias sin hogar en el metro de Jackson incluidos ciudadanos que regresan sin otro lugar adonde ir.",
        address="110 Prentiss Street", city="Jackson", phone="601-969-5258", email="",
        website="https://salvationarmyalm.org/jackson",
        eligibility="Men, women, and families experiencing homelessness in the Jackson area; walk in or call for intake assessment.",
        eligibility_es="Hombres, mujeres y familias sin hogar en el área de Jackson; ingrese sin cita o llame para evaluación de admisión.",
        notes="Call 601-969-5258 for shelter intake; case management connects to WIN Job Center and MDHS benefits.",
        notes_es="Llame al 601-969-5258 para admisión al refugio; el manejo de casos conecta con WIN Job Center y beneficios MDHS.",
        hours="Shelter 24/7; intake during business hours",
        tags="jackson|hinds|housing|emergency-shelter|families|reentry",
        services="Emergency shelter|Meals|Case management|Employment referrals|Benefits navigation",
        county="Hinds", served_counties="Hinds", coverage="single",
        _source="https://salvationarmyalm.org/jackson", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Salvation Army — Gulf Coast Shelter",
        category="housing", region="Gulfport / Harrison County",
        description="The Salvation Army Gulf Coast provides emergency shelter, meals, and disaster and homelessness case management for Harrison and Hancock county residents including justice-involved adults returning from incarceration on the Mississippi Gulf Coast. Staff connect clients to Open Doors coordinated entry and Coastal Family Health Center.",
        description_es="El Ejército de Salvación de la Costa del Golfo ofrece refugio de emergencia, comidas y manejo de casos para residentes de los condados Harrison y Hancock incluidos adultos con antecedentes penales que regresan de la encarcelación.",
        address="2019 22nd Street", city="Gulfport", phone="228-863-6192", email="",
        website="https://salvationarmyalm.org/gulfport",
        eligibility="Homeless adults and families on the Gulf Coast; justice-involved clients welcome per intake.",
        eligibility_es="Adultos y familias sin hogar en la Costa del Golfo; clientes con antecedentes penales bienvenidos según admisión.",
        notes="Call 228-863-6192 for shelter intake; pairs with Back Bay Mission and Open Doors.",
        notes_es="Llame al 228-863-6192 para admisión; se vincula con Back Bay Mission y Open Doors.",
        hours="Shelter 24/7; office Monday–Friday",
        tags="gulfport|harrison|housing|emergency-shelter|reentry",
        services="Emergency shelter|Meals|Case management|Disaster relief|Benefits navigation",
        county="Harrison", served_counties="Harrison|Hancock", coverage="multi",
        _source="https://salvationarmyalm.org/gulfport", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Harbor House Family Violence Center",
        category="housing", region="Hattiesburg / Forrest County",
        description="Harbor House Family Violence Center provides emergency shelter, a 24-hour crisis line, counseling, and legal advocacy for survivors of domestic violence and their children in the Pine Belt including justice-involved survivors navigating both safety planning and court obligations. Advocates connect families to Pine Belt Mental Healthcare and Mississippi Center for Legal Services.",
        description_es="Harbor House Family Violence Center ofrece refugio de emergencia, línea de crisis 24 horas, consejería y defensa legal para sobrevivientes de violencia doméstica y sus hijos en el Pine Belt incluidas sobrevivientes con antecedentes penales.",
        address="PO Box 1568", city="Hattiesburg", phone="601-582-2111", email="",
        website="https://www.harborhousems.org",
        eligibility="Survivors of domestic violence and their children in the Pine Belt; justice-involved survivors eligible per safety assessment.",
        eligibility_es="Sobrevivientes de violencia doméstica y sus hijos en el Pine Belt; sobrevivientes con antecedentes penales elegibles según evaluación de seguridad.",
        notes="24/7 crisis line 601-582-2111; confidential intake; shelter location confidential for resident safety.",
        notes_es="Línea de crisis 24/7 601-582-2111; admisión confidencial; ubicación del refugio confidencial.",
        hours="Crisis line 24/7; shelter intake around the clock",
        tags="hattiesburg|forrest|housing|domestic-violence|shelter|reentry",
        services="Emergency DV shelter|24-hour crisis line|Legal advocacy|Counseling|Children's services",
        county="Forrest", served_counties="Forrest|Lamar|Marion|Covington|Perry|Jefferson Davis", coverage="multi",
        _source="https://www.harborhousems.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Salvation Army Red Shield Lodge — Tupelo",
        category="housing", region="Tupelo / Lee County",
        description="The Salvation Army Red Shield Lodge in Tupelo provides emergency overnight shelter, meals, and laundry for homeless adults in northeast Mississippi including returning citizens recently released from MDOC custody or Lee County Jail. Check-in begins at 5:00 p.m.; photo ID and background check required—not a long-term housing program.",
        description_es="El Salvation Army Red Shield Lodge en Tupelo ofrece refugio nocturno de emergencia, comidas y lavandería para adultos sin hogar en el noreste de Mississippi incluidos ciudadanos recién liberados de custodia MDOC o la cárcel del condado Lee.",
        address="527 Carnation Street", city="Tupelo", phone="662-842-9222", email="",
        website="https://centralusa.salvationarmy.org/tupelo",
        eligibility="Homeless adults in the Tupelo area; justice-involved guests accepted per intake screening; photo ID required.",
        eligibility_es="Adultos sin hogar en el área de Tupelo; huéspedes con antecedentes penales aceptados según evaluación de admisión; se requiere identificación con foto.",
        notes="Call 662-842-9222; check-in from 5:00 p.m.; pairs with Region II Mental Health and WIN Job Center Tupelo.",
        notes_es="Llame al 662-842-9222; registro desde las 5:00 p.m.; se vincula con Region II Mental Health y WIN Job Center Tupelo.",
        hours="Check-in from 5:00 p.m.; call for current availability",
        tags="tupelo|lee|housing|emergency-shelter|reentry",
        services="Emergency overnight shelter|Meals|Laundry|Case referrals|Employment navigation",
        county="Lee", served_counties="Lee|Prentiss|Itawamba|Pontotoc", coverage="multi",
        _source="https://centralusa.salvationarmy.org/tupelo", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Elizabeth Gwin Village — Supportive Housing",
        category="housing", region="Jackson / Hinds County",
        description="Elizabeth Gwin Village provides affordable and supportive rental housing for low-income Jackson metro households including returning citizens rebuilding stable tenancy after incarceration. Property management connects residents to Mississippi Works, Hinds Behavioral Health, and Mississippi Center for Legal Services for employment and tenant-rights support.",
        description_es="Elizabeth Gwin Village ofrece vivienda de alquiler asequible y de apoyo para hogares de bajos ingresos del metro de Jackson incluidos ciudadanos que regresan que reconstruyen arrendamiento estable después de la encarcelación.",
        address="1400 University Boulevard", city="Jackson", phone="601-362-0909", email="",
        website="https://www.housingcorp.org",
        eligibility="Low-income Hinds County households; justice-involved applicants may qualify for supportive housing units per screening.",
        eligibility_es="Hogares de bajos ingresos del condado Hinds; solicitantes con antecedentes penales pueden calificar para unidades de vivienda de apoyo según evaluación.",
        notes="Call 601-362-0909 for availability; managed by Mississippi Home Corporation partners; not an emergency shelter.",
        notes_es="Llame al 601-362-0909 para disponibilidad; no es refugio de emergencia.",
        hours="Monday–Friday business hours",
        tags="jackson|hinds|housing|affordable|supportive|reentry",
        services="Affordable rental housing|Supportive housing|Tenant support|Employment referrals|Housing stabilization",
        county="Hinds", served_counties="Hinds", coverage="single",
        _source="https://www.housingcorp.org", _source_type="nonprofit", _confidence="high",
    )

    # --- healthcare ---
    add(
        name="Jackson Free Clinic",
        category="healthcare", region="Jackson / Hinds County",
        description="Jackson Free Clinic is a student-run free clinic providing primary care, chronic disease management, and prescription assistance for uninsured low-income Hinds County residents including returning citizens establishing a medical home after release. Volunteer physicians and nurses coordinate referrals to Hinds Behavioral Health and Division of Medicaid enrollment.",
        description_es="Jackson Free Clinic es una clínica gratuita operada por estudiantes que ofrece atención primaria, manejo de enfermedades crónicas y asistencia con recetas para residentes del condado Hinds sin seguro y de bajos ingresos incluidos ciudadanos que regresan.",
        address="925 Martin Luther King Jr. Drive", city="Jackson", phone="601-355-5160", email="",
        website="https://www.jacksonfreeclinic.org",
        eligibility="Uninsured low-income Hinds County residents; income screening required; justice-involved patients welcome.",
        eligibility_es="Residentes del condado Hinds sin seguro y de bajos ingresos; se requiere evaluación de ingresos; pacientes con antecedentes penales bienvenidos.",
        notes="Call 601-355-5160 for appointments; evening clinic hours; not an emergency room.",
        notes_es="Llame al 601-355-5160 para citas; horario de clínica nocturna; no es sala de emergencias.",
        hours="Evening clinic hours; call for schedule",
        tags="jackson|hinds|healthcare|free-clinic|primary-care|reentry",
        services="Free primary care|Chronic disease management|Prescription assistance|Medicaid enrollment referrals|Specialist referrals",
        county="Hinds", served_counties="Hinds", coverage="single",
        _source="https://www.jacksonfreeclinic.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="G.A. Carmichael Family Health Center",
        category="healthcare", region="Canton / Madison County",
        description="G.A. Carmichael Family Health Center operates Federally Qualified Health Center clinics across central Mississippi providing primary care, behavioral health, dental services, and sliding-fee care for uninsured and Medicaid patients including justice-involved adults in the Jackson metro and Madison County.",
        description_es="G.A. Carmichael Family Health Center opera clínicas FQHC en el centro de Mississippi que ofrecen atención primaria, salud conductual, servicios dentales y atención con tarifa móvil para pacientes sin seguro y Medicaid incluidos adultos con antecedentes penales.",
        address="909 East North Street", city="Canton", phone="601-859-5213", email="",
        website="https://www.carmichaelhealth.org",
        eligibility="Central Mississippi residents of all ages; sliding scale with proof of income; Medicaid accepted.",
        eligibility_es="Residentes del centro de Mississippi de todas las edades; escala móvil con prueba de ingresos; se acepta Medicaid.",
        notes="Call 601-859-5213 for nearest clinic; multiple central Mississippi locations including Canton and Jackson area.",
        notes_es="Llame al 601-859-5213 para la clínica más cercana; múltiples ubicaciones en el centro de Mississippi.",
        hours="Monday–Friday clinic hours; varies by location",
        tags="canton|madison|healthcare|FQHC|primary-care|reentry",
        services="Primary care|Behavioral health|Dental care|Sliding-fee services|Pharmacy assistance",
        county="Madison", served_counties="Madison|Leake|Attala|Holmes|Yazoo", coverage="multi",
        _source="https://www.carmichaelhealth.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="North Mississippi Medical Center — Tupelo",
        category="healthcare", region="Tupelo / Lee County",
        description="North Mississippi Medical Center is the region's largest hospital providing emergency, inpatient, and outpatient care with financial assistance and Medicaid coordination for uninsured and justice-involved patients including those leaving MDOC custody or Lee County Jail. Social workers connect discharged patients to Region II Mental Health and access.ms.gov enrollment.",
        description_es="North Mississippi Medical Center es el hospital más grande de la región que ofrece atención de emergencia, hospitalaria y ambulatoria con asistencia financiera y coordinación Medicaid para pacientes sin seguro y con antecedentes penales.",
        address="830 South Gloster Street", city="Tupelo", phone="662-377-3000", email="",
        website="https://www.nmhs.net",
        eligibility="Lee County and northeast Mississippi patients; financial assistance available; Medicaid accepted.",
        eligibility_es="Pacientes del condado Lee y noreste de Mississippi; asistencia financiera disponible; se acepta Medicaid.",
        notes="Call 662-377-3000; emergency 24/7; financial counseling for uninsured patients.",
        notes_es="Llame al 662-377-3000; emergencias 24/7; consejería financiera para pacientes sin seguro.",
        hours="Emergency 24/7; offices Monday–Friday",
        tags="tupelo|lee|healthcare|hospital|reentry",
        services="Emergency care|Inpatient services|Outpatient clinics|Financial assistance|Discharge planning",
        county="Lee", served_counties="Lee|Prentiss|Itawamba|Pontotoc|Tishomingo", coverage="multi",
        _source="https://www.nmhs.net", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Delta Regional Medical Center — Greenville",
        category="healthcare", region="Greenville / Washington County",
        description="Delta Regional Medical Center provides emergency, inpatient, and outpatient care for Washington County and Delta region residents including uninsured and Medicaid patients such as returning citizens establishing local medical access after release. Charity care and financial assistance programs help justice-involved patients without coverage.",
        description_es="Delta Regional Medical Center brinda atención de emergencia, hospitalaria y ambulatoria para residentes del condado Washington y la región Delta incluidos pacientes sin seguro y Medicaid como ciudadanos que regresan.",
        address="1400 East Union Street", city="Greenville", phone="662-334-4100", email="",
        website="https://www.deltregional.com",
        eligibility="Delta region patients; emergency care regardless of ability to pay; charity care application for eligible uninsured.",
        eligibility_es="Pacientes de la región Delta; atención de emergencia independientemente de capacidad de pago; solicitud de atención caritativa para sin seguro elegibles.",
        notes="Emergency 662-334-4100; pairs with Delta Health Alliance and WIN Job Center Greenville.",
        notes_es="Emergencias 662-334-4100; se vincula con Delta Health Alliance y WIN Job Center Greenville.",
        hours="Emergency 24/7; clinic hours vary",
        tags="greenville|washington|healthcare|hospital|delta|reentry",
        services="Emergency care|Inpatient services|Outpatient clinics|Charity care|Discharge planning",
        county="Washington", served_counties="Washington|Bolivar|Sunflower|Issaquena|Sharkey", coverage="multi",
        _source="https://www.deltregional.com", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Merit Health River Region — Meridian",
        category="healthcare", region="Meridian / Lauderdale County",
        description="Merit Health River Region operates hospital and outpatient services in Meridian providing emergency care, primary care referrals, and financial assistance for Lauderdale County residents including uninsured justice-involved adults reestablishing healthcare after release from MDOC custody or county jail.",
        description_es="Merit Health River Region opera servicios hospitalarios y ambulatorios en Meridian que ofrecen atención de emergencia, referencias de atención primaria y asistencia financiera para residentes del condado Lauderdale incluidos adultos con antecedentes penales sin seguro.",
        address="2100 13th Street", city="Meridian", phone="601-483-0011", email="",
        website="https://merithealthriverregion.com",
        eligibility="Lauderdale County patients; emergency care available; financial assistance for eligible uninsured.",
        eligibility_es="Pacientes del condado Lauderdale; atención de emergencia disponible; asistencia financiera para sin seguro elegibles.",
        notes="Call 601-483-0011; emergency 24/7; pairs with Weems CMHC and WIN Job Center Meridian.",
        notes_es="Llame al 601-483-0011; emergencias 24/7; se vincula con Weems CMHC y WIN Job Center Meridian.",
        hours="Emergency 24/7; offices Monday–Friday",
        tags="meridian|lauderdale|healthcare|hospital|reentry",
        services="Emergency care|Inpatient services|Outpatient referrals|Financial assistance|Discharge planning",
        county="Lauderdale", served_counties="Lauderdale|Clarke|Kemper", coverage="multi",
        _source="https://merithealthriverregion.com", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Baptist Memorial Hospital — Oxford",
        category="healthcare", region="Oxford / Lafayette County",
        description="Baptist Memorial Hospital-North Mississippi in Oxford provides emergency, inpatient, and outpatient care with financial assistance for uninsured and Medicaid patients in Lafayette and north Mississippi counties including returning citizens from MDOC custody establishing local medical care.",
        description_es="Baptist Memorial Hospital-North Mississippi en Oxford ofrece atención de emergencia, hospitalaria y ambulatoria con asistencia financiera para pacientes sin seguro y Medicaid en Lafayette y condados del norte de Mississippi incluidos ciudadanos que regresan de custodia MDOC.",
        address="1100 Belk Boulevard", city="Oxford", phone="662-636-1000", email="",
        website="https://www.baptistonline.org",
        eligibility="North Mississippi patients; financial assistance available; Medicaid accepted.",
        eligibility_es="Pacientes del norte de Mississippi; asistencia financiera disponible; se acepta Medicaid.",
        notes="Call 662-636-1000; emergency 24/7; pairs with Communicare and WIN Job Center Oxford.",
        notes_es="Llame al 662-636-1000; emergencias 24/7; se vincula con Communicare y WIN Job Center Oxford.",
        hours="Emergency 24/7; offices Monday–Friday",
        tags="oxford|lafayette|healthcare|hospital|reentry",
        services="Emergency care|Inpatient services|Outpatient clinics|Financial assistance|Specialist referrals",
        county="Lafayette", served_counties="Lafayette|Marshall|Benton|Panola", coverage="multi",
        _source="https://www.baptistonline.org", _source_type="nonprofit", _confidence="high",
    )

    # --- employment ---
    add(
        name="Goodwill Industries of Mississippi — Jackson",
        category="employment", region="Jackson / Hinds County",
        description="Goodwill Industries of Mississippi operates career centers in Jackson offering job readiness training, resume assistance, and fair-chance employer connections for adults facing employment barriers including returning citizens. Program staff coordinate with Mississippi Works and MDOC probation officers to place participants in retail, warehouse, and service-sector jobs.",
        description_es="Goodwill Industries of Mississippi opera centros de carrera en Jackson que ofrecen capacitación de preparación laboral, asistencia con currículum y conexiones con empleadores de segunda oportunidad para adultos que enfrentan barreras de empleo incluidos ciudadanos que regresan.",
        address="1500 West Capitol Street", city="Jackson", phone="601-948-3949", email="",
        website="https://www.goodwillms.org",
        eligibility="Adults in the Jackson area facing employment barriers including justice-involved individuals; program enrollment through career center intake.",
        eligibility_es="Adultos en el área de Jackson que enfrentan barreras de empleo incluidas personas con antecedentes penales; inscripción a través de admisión del centro de carrera.",
        notes="Call 601-948-3949 to schedule intake; job coaching continues after placement.",
        notes_es="Llame al 601-948-3949 para programar admisión; el coaching laboral continúa después de la colocación.",
        hours="Monday–Friday business hours",
        tags="jackson|hinds|employment|goodwill|job-readiness|fair-chance|reentry",
        services="Job readiness training|Resume assistance|Fair-chance employer connections|Job coaching|Retail and warehouse placement",
        county="Hinds", served_counties="Hinds|Madison|Rankin", coverage="multi",
        _source="https://www.goodwillms.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Mississippi Job Corps — Jackson Center",
        category="employment", region="Jackson / Hinds County",
        description="Mississippi Job Corps at the Jackson center provides free residential and non-residential career technical training, GED preparation, and job placement for eligible young adults ages 16–24 including justice-involved youth seeking credentials for sustainable employment. Training connects graduates to Mississippi Works and employer partners statewide.",
        description_es="Mississippi Job Corps en el centro de Jackson ofrece capacitación técnica profesional residencial y no residencial gratuita, preparación GED y colocación laboral para adultos jóvenes elegibles de 16 a 24 años incluidos jóvenes con antecedentes penales que buscan credenciales para empleo sostenible.",
        address="7644 Old Canton Road", city="Ridgeland", phone="601-956-5681", email="",
        website="https://www.jobcorps.gov",
        eligibility="Mississippi residents ages 16–24 meeting Job Corps income and eligibility requirements; justice-involved youth may qualify.",
        eligibility_es="Residentes de Mississippi de 16 a 24 años que cumplan requisitos de ingresos y elegibilidad de Job Corps; jóvenes con antecedentes penales pueden calificar.",
        notes="Call 601-956-5681 for enrollment; residential program available; GED and trade credentials offered.",
        notes_es="Llame al 601-956-5681 para inscripción; programa residencial disponible; se ofrecen credenciales GED y oficios.",
        hours="Residential program; contact admissions",
        tags="ridgeland|madison|employment|job-corps|GED|youth|reentry",
        services="Career technical training|GED preparation|Job placement|Residential program|Employer partnerships",
        county="Madison", served_counties="Madison|Hinds|Rankin", coverage="multi",
        _source="https://www.jobcorps.gov", _source_type="government", _confidence="high",
    )
    add(
        name="Mississippi Construction Education Foundation",
        category="employment", region="Jackson / Hinds County",
        description="The Mississippi Construction Education Foundation provides NCCER-certified construction skills training, apprenticeship pathways, and employer connections for justice-involved Mississippians seeking trades careers in carpentry, electrical, plumbing, and HVAC across the state. Training partners with Mississippi Works and MDOC reentry programs for credential building after release.",
        description_es="Mississippi Construction Education Foundation ofrece capacitación certificada NCCER en habilidades de construcción, vías de aprendizaje y conexiones con empleadores para mississippianos con antecedentes penales que buscan carreras en carpintería, electricidad, plomería y HVAC.",
        address="6725 South Siwell Road", city="Byram", phone="601-932-9100", email="",
        website="https://www.mcef.net",
        eligibility="Mississippi residents seeking construction trades training; some programs require employer sponsorship or WIN Job Center referral.",
        eligibility_es="Residentes de Mississippi que buscan capacitación en oficios de construcción; algunos programas requieren patrocinio del empleador o referencia de WIN Job Center.",
        notes="Call 601-932-9100; NCCER credentials recognized statewide; pairs with Mississippi Works.",
        notes_es="Llame al 601-932-9100; credenciales NCCER reconocidas en todo el estado; se vincula con Mississippi Works.",
        hours="Training schedules vary by program",
        tags="byram|hinds|employment|construction|NCCER|apprenticeship|reentry",
        services="Construction skills training|NCCER certification|Apprenticeship pathways|Employer connections|Career coaching",
        county="Hinds", served_counties="", coverage="statewide",
        _source="https://www.mcef.net", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Southern Mississippi Planning and Development District — Workforce",
        category="employment", region="Hattiesburg / Forrest County",
        description="Southern Mississippi Planning and Development District operates workforce development programs connecting Pine Belt job seekers including justice-involved adults to WIOA training, employer partnerships, and career navigation in Forrest, Lamar, and surrounding south Mississippi counties. Staff coordinate with Pine Belt Mental Healthcare and MDOC field offices.",
        description_es="Southern Mississippi Planning and Development District opera programas de desarrollo de la fuerza laboral que conectan buscadores de empleo del Pine Belt incluidos adultos con antecedentes penales con capacitación WIOA, alianzas con empleadores y navegación de carrera.",
        address="709 James Street", city="Hattiesburg", phone="601-545-2137", email="",
        website="https://www.smpdd.com",
        eligibility="South Mississippi residents seeking workforce services; justice-involved adults eligible for WIOA programs.",
        eligibility_es="Residentes del sur de Mississippi que buscan servicios de fuerza laboral; adultos con antecedentes penales elegibles para programas WIOA.",
        notes="Call 601-545-2137; regional workforce board partner; pairs with WIN Job Center Hattiesburg.",
        notes_es="Llame al 601-545-2137; aliado de la junta regional de fuerza laboral; se vincula con WIN Job Center Hattiesburg.",
        hours="Monday–Friday business hours",
        tags="hattiesburg|forrest|employment|WIOA|workforce|reentry",
        services="WIOA training referrals|Employer partnerships|Career navigation|Job placement|Regional workforce coordination",
        county="Forrest", served_counties="Forrest|Lamar|Marion|Covington|Jefferson Davis|Perry|Wayne", coverage="multi",
        _source="https://www.smpdd.com", _source_type="government", _confidence="high",
    )
    add(
        name="Three Rivers Planning and Development District — Workforce",
        category="employment", region="Columbus / Lowndes County",
        description="Three Rivers Planning and Development District connects Golden Triangle job seekers including justice-involved adults to WIOA-funded training, resume assistance, and fair-chance employment navigation in Lowndes, Oktibbeha, and Clay counties. Staff link returning citizens to Community Counseling Services and MDOC Columbus field office.",
        description_es="Three Rivers Planning and Development District conecta buscadores de empleo del Triángulo Dorado incluidos adultos con antecedentes penales con capacitación WIOA, ayuda con currículum y navegación de empleo de segunda oportunidad en Lowndes, Oktibbeha y Clay.",
        address="248 South Lafayette Street", city="Starkville", phone="662-324-7860", email="",
        website="https://www.trpdd.com",
        eligibility="Golden Triangle residents seeking workforce services; justice-involved adults eligible for WIOA programs.",
        eligibility_es="Residentes del Triángulo Dorado que buscan servicios de fuerza laboral; adultos con antecedentes penales elegibles para programas WIOA.",
        notes="Call 662-324-7860; serves Columbus, Starkville, and West Point; pairs with WIN Job Center Columbus.",
        notes_es="Llame al 662-324-7860; sirve Columbus, Starkville y West Point; se vincula con WIN Job Center Columbus.",
        hours="Monday–Friday business hours",
        tags="starkville|oktibbeha|employment|WIOA|golden-triangle|reentry",
        services="WIOA training referrals|Resume assistance|Fair-chance employment|Job placement|Regional workforce coordination",
        county="Oktibbeha", served_counties="Lowndes|Oktibbeha|Clay|Noxubee", coverage="multi",
        _source="https://www.trpdd.com", _source_type="government", _confidence="high",
    )

    # --- legal-aid ---
    add(
        name="Mississippi Center for Legal Services — Hattiesburg Office",
        category="legal-aid", region="Hattiesburg / Forrest County",
        description="The Mississippi Center for Legal Services Hattiesburg regional office provides free civil legal aid to low-income residents of south Mississippi counties including housing eviction defense, public benefits appeals, family law, and expungement assistance under Mississippi law. Justice-involved clients can apply for record relief—not criminal defense.",
        description_es="La oficina regional de Mississippi Center for Legal Services en Hattiesburg brinda asistencia legal civil gratuita a residentes de bajos ingresos de condados del sur de Mississippi incluyendo defensa contra desalojo, apelaciones de beneficios y asistencia con expungación.",
        address="601 North Main Street", city="Hattiesburg", phone="601-582-2080", email="",
        website="https://www.mslegalservices.org",
        eligibility="Low-income residents of MCLS Hattiesburg service counties with civil legal problems; LSC income limits apply.",
        eligibility_es="Residentes de bajos ingresos de los condados de servicio MCLS Hattiesburg con problemas legales civiles; aplican límites de ingresos LSC.",
        notes="Call 601-582-2080 or statewide helpline 1-800-498-1804; apply online at mslegalservices.org.",
        notes_es="Llame al 601-582-2080 o línea estatal 1-800-498-1804; solicite en mslegalservices.org.",
        hours="Intake Monday–Friday business hours",
        tags="hattiesburg|legal-aid|low-income|expungement|reentry",
        services="Civil legal representation|Expungement assistance|Housing legal aid|Benefits appeals|Family law assistance",
        county="Forrest", served_counties="Forrest|Lamar|Marion|Covington|Jefferson Davis|Perry|Wayne|Jones|Greene", coverage="multi",
        _source="https://www.mslegalservices.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Mississippi Center for Legal Services — Gulfport Office",
        category="legal-aid", region="Gulfport / Harrison County",
        description="The Mississippi Center for Legal Services Gulfport regional office provides free civil legal aid to low-income Gulf Coast residents including housing, public benefits, family law, and expungement assistance. Justice-involved clients in Harrison, Hancock, and Jackson counties can apply for record relief and benefits denials—not criminal defense.",
        description_es="La oficina regional de Mississippi Center for Legal Services en Gulfport brinda asistencia legal civil gratuita a residentes de bajos ingresos de la Costa del Golfo incluyendo vivienda, beneficios públicos y asistencia con expungación.",
        address="14209 Seaway Road, Suite B1", city="Gulfport", phone="228-896-9144", email="",
        website="https://www.mslegalservices.org",
        eligibility="Low-income residents of MCLS Gulfport service counties with civil legal problems; LSC income limits apply.",
        eligibility_es="Residentes de bajos ingresos de los condados de servicio MCLS Gulfport con problemas legales civiles; aplican límites de ingresos LSC.",
        notes="Call 228-896-9144 or statewide helpline 1-800-498-1804; apply online at mslegalservices.org.",
        notes_es="Llame al 228-896-9144 o línea estatal 1-800-498-1804; solicite en mslegalservices.org.",
        hours="Intake Monday–Friday business hours",
        tags="gulfport|legal-aid|low-income|expungement|reentry",
        services="Civil legal representation|Expungement assistance|Housing legal aid|Benefits appeals|Family law assistance",
        county="Harrison", served_counties="Harrison|Hancock|Jackson|Stone|George|Pearl River", coverage="multi",
        _source="https://www.mslegalservices.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Mississippi Center for Legal Services — Tupelo Office",
        category="legal-aid", region="Tupelo / Lee County",
        description="The Mississippi Center for Legal Services Tupelo regional office provides free civil legal aid to low-income northeast Mississippi residents including housing eviction defense, public benefits appeals, and expungement assistance. Justice-involved clients in Lee, Prentiss, and surrounding counties can apply for help with record relief.",
        description_es="La oficina regional de Mississippi Center for Legal Services en Tupelo brinda asistencia legal civil gratuita a residentes de bajos ingresos del noreste de Mississippi incluyendo defensa contra desalojo, apelaciones de beneficios y asistencia con expungación.",
        address="507 West Main Street, Suite 200", city="Tupelo", phone="662-842-6751", email="",
        website="https://www.mslegalservices.org",
        eligibility="Low-income residents of MCLS Tupelo service counties with civil legal problems; LSC income limits apply.",
        eligibility_es="Residentes de bajos ingresos de los condados de servicio MCLS Tupelo con problemas legales civiles; aplican límites de ingresos LSC.",
        notes="Call 662-842-6751 or statewide helpline 1-800-498-1804; apply online at mslegalservices.org.",
        notes_es="Llame al 662-842-6751 o línea estatal 1-800-498-1804; solicite en mslegalservices.org.",
        hours="Intake Monday–Friday business hours",
        tags="tupelo|legal-aid|low-income|expungement|reentry",
        services="Civil legal representation|Expungement assistance|Housing legal aid|Benefits appeals|Family law assistance",
        county="Lee", served_counties="Lee|Prentiss|Itawamba|Pontotoc|Tishomingo|Alcorn|Union", coverage="multi",
        _source="https://www.mslegalservices.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Mississippi Center for Legal Services — Greenwood Office",
        category="legal-aid", region="Greenwood / Leflore County",
        description="The Mississippi Center for Legal Services Greenwood regional office provides free civil legal aid to low-income Delta and north-central Mississippi residents including housing, public benefits, and expungement assistance. Justice-involved clients in Washington, Leflore, and surrounding Delta counties can apply for record relief and benefits appeals.",
        description_es="La oficina regional de Mississippi Center for Legal Services en Greenwood brinda asistencia legal civil gratuita a residentes de bajos ingresos del Delta y centro-norte de Mississippi incluyendo vivienda, beneficios públicos y asistencia con expungación.",
        address="101 W. Washington Street, Suite 109", city="Greenwood", phone="662-453-5631", email="",
        website="https://www.mslegalservices.org",
        eligibility="Low-income residents of MCLS Greenwood service counties with civil legal problems; LSC income limits apply.",
        eligibility_es="Residentes de bajos ingresos de los condados de servicio MCLS Greenwood con problemas legales civiles; aplican límites de ingresos LSC.",
        notes="Call 662-453-5631 or statewide helpline 1-800-498-1804; serves Delta region counties.",
        notes_es="Llame al 662-453-5631 o línea estatal 1-800-498-1804; sirve condados de la región Delta.",
        hours="Intake Monday–Friday business hours",
        tags="greenwood|legal-aid|low-income|expungement|delta|reentry",
        services="Civil legal representation|Expungement assistance|Housing legal aid|Benefits appeals|Family law assistance",
        county="Leflore", served_counties="Leflore|Washington|Bolivar|Sunflower|Humphreys|Carroll|Montgomery|Grenada", coverage="multi",
        _source="https://www.mslegalservices.org", _source_type="nonprofit", _confidence="high",
    )

    # --- substance-use ---
    add(
        name="Region 8 Mental Health Services — Jackson Substance Use",
        category="substance-use-treatment", region="Jackson / Hinds County",
        description="Region 8 Mental Health Services provides outpatient mental health and substance use treatment, crisis intervention, and case management for Hinds, Rankin, and Madison county residents including justice-involved adults referred by MDOC probation and drug courts. Medicaid and sliding-fee care accepted—not a residential detox facility.",
        description_es="Region 8 Mental Health Services ofrece tratamiento ambulatorio de salud mental y uso de sustancias, intervención en crisis y manejo de casos para residentes de los condados Hinds, Rankin y Madison incluidos adultos con antecedentes penales referidos por probatoria MDOC.",
        address="613 Marquette Road", city="Brandon", phone="601-825-6515", email="",
        website="https://www.region8mhs.org",
        eligibility="Hinds metro residents seeking mental health or substance use services; Medicaid and sliding-fee accepted; justice-involved clients welcome.",
        eligibility_es="Residentes del metro de Hinds que buscan servicios de salud mental o uso de sustancias; se aceptan Medicaid y tarifa móvil; clientes con antecedentes penales bienvenidos.",
        notes="Call 601-825-6515 for intake; pairs with Hinds Behavioral Health and MDOC Jackson field offices.",
        notes_es="Llame al 601-825-6515 para admisión; se vincula con Hinds Behavioral Health y oficinas MDOC Jackson.",
        hours="Monday–Friday clinic hours; crisis services vary",
        tags="jackson|substance-use-treatment|mental-health|reentry",
        services="Outpatient substance use treatment|Mental health counseling|Crisis intervention|Case management|Probation referrals",
        county="Hinds", served_counties="Hinds|Rankin|Madison", coverage="multi",
        _source="https://www.region8mhs.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Region 8 Mental Health Services — Brandon",
        category="substance-use-treatment", region="Brandon / Rankin County",
        description="Region 8 Mental Health Services provides outpatient mental health and substance use treatment, crisis intervention, and case management for Rankin, Madison, and Simpson county residents including justice-involved adults referred by MDOC probation and drug courts. Medicaid and sliding-fee care accepted.",
        description_es="Region 8 Mental Health Services ofrece tratamiento ambulatorio de salud mental y uso de sustancias, intervención en crisis y manejo de casos para residentes de Rankin, Madison y Simpson incluidos adultos con antecedentes penales referidos por probatoria MDOC.",
        address="613 Marquette Road", city="Brandon", phone="601-825-6515", email="",
        website="https://www.region8mhs.org",
        eligibility="Rankin County and Region 8 service area residents; Medicaid and sliding-fee accepted; justice-involved clients welcome.",
        eligibility_es="Residentes del condado Rankin y área de servicio Region 8; se aceptan Medicaid y tarifa móvil; clientes con antecedentes penales bienvenidos.",
        notes="Call 601-825-6515 for intake; crisis line available; pairs with MDOC Jackson field offices.",
        notes_es="Llame al 601-825-6515 para admisión; línea de crisis disponible; se vincula con oficinas MDOC Jackson.",
        hours="Monday–Friday clinic hours; crisis services vary",
        tags="brandon|rankin|substance-use-treatment|mental-health|reentry",
        services="Outpatient mental health|Substance use treatment|Crisis intervention|Case management|Probation referrals",
        county="Rankin", served_counties="Rankin|Madison|Simpson|Scott", coverage="multi",
        _source="https://www.region8mhs.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Region 10 Mental Health Services — Corinth",
        category="substance-use-treatment", region="Corinth / Alcorn County",
        description="Region 10 Mental Health Services provides outpatient mental health and substance use treatment for northeast Mississippi counties including Alcorn, Tishomingo, and Prentiss, serving justice-involved adults referred by MDOC probation and local drug courts. Sliding-fee and Medicaid services support treatment continuity after release.",
        description_es="Region 10 Mental Health Services ofrece tratamiento ambulatorio de salud mental y uso de sustancias para condados del noreste de Mississippi incluidos Alcorn, Tishomingo y Prentiss, sirviendo a adultos con antecedentes penales referidos por probatoria MDOC.",
        address="611 West Corinth Street", city="Corinth", phone="662-287-6171", email="",
        website="https://www.region10mhs.com",
        eligibility="Region 10 service area residents seeking mental health or substance use services; Medicaid and sliding-fee accepted.",
        eligibility_es="Residentes del área de servicio Region 10 que buscan servicios de salud mental o uso de sustancias; se aceptan Medicaid y tarifa móvil.",
        notes="Call 662-287-6171 for intake; pairs with WIN Job Center Tupelo and Region II Mental Health.",
        notes_es="Llame al 662-287-6171 para admisión; se vincula con WIN Job Center Tupelo y Region II Mental Health.",
        hours="Monday–Friday clinic hours",
        tags="corinth|alcorn|substance-use-treatment|mental-health|reentry",
        services="Outpatient mental health|Substance use treatment|Crisis intervention|Case management|Drug court referrals",
        county="Alcorn", served_counties="Alcorn|Tishomingo|Prentiss|Tippah", coverage="multi",
        _source="https://www.region10mhs.com", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Region 12 Mental Health Services — Ellisville",
        category="substance-use-treatment", region="Ellisville / Jones County",
        description="Region 12 Mental Health Services provides outpatient psychiatric care, substance use treatment, and crisis services for Jones, Wayne, and south-central Mississippi counties including justice-involved adults under MDOC supervision. The Ellisville campus coordinates with Pine Belt Mental Healthcare and local reentry partners.",
        description_es="Region 12 Mental Health Services ofrece atención psiquiátrica ambulatoria, tratamiento de uso de sustancias y servicios de crisis para los condados Jones, Wayne y centro-sur de Mississippi incluidos adultos con antecedentes penales bajo supervisión MDOC.",
        address="1577 Highway 15 North", city="Ellisville", phone="601-477-3644", email="",
        website="https://www.region12mhs.com",
        eligibility="Region 12 service area residents; Medicaid and sliding-fee accepted; justice-involved clients welcome.",
        eligibility_es="Residentes del área de servicio Region 12; se aceptan Medicaid y tarifa móvil; clientes con antecedentes penales bienvenidos.",
        notes="Call 601-477-3644 for intake; multiple south Mississippi locations.",
        notes_es="Llame al 601-477-3644 para admisión; múltiples ubicaciones del sur de Mississippi.",
        hours="Monday–Friday clinic hours",
        tags="ellisville|jones|substance-use-treatment|mental-health|reentry",
        services="Outpatient psychiatric care|Substance use treatment|Crisis services|Case management|Probation referrals",
        county="Jones", served_counties="Jones|Wayne|Greene|Perry|Forrest", coverage="multi",
        _source="https://www.region12mhs.com", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Region 6 Mental Health Services — Clarksdale",
        category="substance-use-treatment", region="Clarksdale / Coahoma County",
        description="Region 6 Mental Health Services provides outpatient mental health and substance use treatment for Delta counties including Coahoma, Quitman, and Tallahatchie, serving justice-involved adults referred by MDOC probation and drug courts. Medicaid and sliding-fee services help returning citizens stabilize treatment in rural Delta communities.",
        description_es="Region 6 Mental Health Services ofrece tratamiento ambulatorio de salud mental y uso de sustancias para condados Delta incluidos Coahoma, Quitman y Tallahatchie, sirviendo a adultos con antecedentes penales referidos por probatoria MDOC.",
        address="611 East Sunflower Road", city="Clarksdale", phone="662-624-0131", email="",
        website="https://www.region6mhs.com",
        eligibility="Delta region residents seeking mental health or substance use services; Medicaid and sliding-fee accepted.",
        eligibility_es="Residentes de la región Delta que buscan servicios de salud mental o uso de sustancias; se aceptan Medicaid y tarifa móvil.",
        notes="Call 662-624-0131 for intake; pairs with Delta Health Alliance and WIN Job Center Greenville.",
        notes_es="Llame al 662-624-0131 para admisión; se vincula con Delta Health Alliance y WIN Job Center Greenville.",
        hours="Monday–Friday clinic hours",
        tags="clarksdale|coahoma|substance-use-treatment|delta|reentry",
        services="Outpatient mental health|Substance use treatment|Crisis intervention|Case management|Drug court referrals",
        county="Coahoma", served_counties="Coahoma|Quitman|Tallahatchie|Panola", coverage="multi",
        _source="https://www.region6mhs.com", _source_type="nonprofit", _confidence="high",
    )

    # --- veterans ---
    add(
        name="G.V. (Sonny) Montgomery VA Medical Center",
        category="veterans", region="Jackson / Hinds County",
        description="The G.V. Sonny Montgomery VA Medical Center in Jackson provides primary care, mental health, substance use treatment, and housing assistance for eligible veterans including justice-involved veterans released from incarceration. VA social workers coordinate with Mississippi Veterans Affairs county service officers and MDOC reentry staff for benefits and treatment continuity.",
        description_es="El Centro Médico VA G.V. Sonny Montgomery en Jackson ofrece atención primaria, salud mental, tratamiento de uso de sustancias y asistencia de vivienda para veteranos elegibles incluidos veteranos con antecedentes penales liberados de la encarcelación.",
        address="1500 East Woodrow Wilson Avenue", city="Jackson", phone="601-364-1200", email="",
        website="https://www.va.gov/jackson-health-care",
        eligibility="Eligible veterans with DD-214 or qualifying service; justice-involved veterans may qualify for VA health care and housing programs.",
        eligibility_es="Veteranos elegibles con DD-214 o servicio calificado; veteranos con antecedentes penales pueden calificar para atención médica VA y programas de vivienda.",
        notes="Call 601-364-1200 for enrollment; HUD-VASH housing vouchers available for eligible homeless veterans.",
        notes_es="Llame al 601-364-1200 para inscripción; vales de vivienda HUD-VASH disponibles para veteranos sin hogar elegibles.",
        hours="Medical center Monday–Friday; emergency 24/7",
        tags="jackson|veterans|VA|healthcare|housing|reentry",
        services="VA primary care|Mental health treatment|Substance use treatment|HUD-VASH housing|Benefits enrollment",
        county="Hinds", served_counties="", coverage="statewide",
        _source="https://www.va.gov/jackson-health-care", _source_type="government", _confidence="high",
    )
    add(
        name="VA Gulf Coast Veterans Health Care System — Biloxi",
        category="veterans", region="Biloxi / Harrison County",
        description="The VA Gulf Coast Veterans Health Care System Biloxi campus provides primary care, mental health, substance use treatment, and homeless veteran services for eligible veterans on the Mississippi Gulf Coast including justice-involved veterans. VA staff coordinate with Mississippi Veterans Affairs and Open Doors for housing and employment support.",
        description_es="El sistema de atención médica VA Gulf Coast en el campus de Biloxi ofrece atención primaria, salud mental, tratamiento de uso de sustancias y servicios para veteranos sin hogar en la Costa del Golfo de Mississippi incluidos veteranos con antecedentes penales.",
        address="400 Veterans Avenue", city="Biloxi", phone="228-523-5000", email="",
        website="https://www.va.gov/gulf-coast-health-care",
        eligibility="Eligible Gulf Coast veterans; justice-involved veterans may qualify for VA health care and homeless veteran programs.",
        eligibility_es="Veteranos elegibles de la Costa del Golfo; veteranos con antecedentes penales pueden calificar para atención médica VA y programas para veteranos sin hogar.",
        notes="Call 228-523-5000 for enrollment; homeless veteran coordinator available; pairs with Back Bay Mission.",
        notes_es="Llame al 228-523-5000 para inscripción; coordinador de veteranos sin hogar disponible; se vincula con Back Bay Mission.",
        hours="Medical center Monday–Friday; emergency 24/7",
        tags="biloxi|veterans|VA|healthcare|homeless|reentry",
        services="VA primary care|Mental health treatment|Substance use treatment|Homeless veteran services|Benefits enrollment",
        county="Harrison", served_counties="Harrison|Hancock|Jackson|Stone|George|Pearl River", coverage="multi",
        _source="https://www.va.gov/gulf-coast-health-care", _source_type="government", _confidence="high",
    )
    add(
        name="Veterans of Foreign Wars — Mississippi State Veterans Home",
        category="veterans", region="Collins / Covington County",
        description="The Mississippi State Veterans Home in Collins provides long-term care, rehabilitation, and supportive services for eligible Mississippi veterans including justice-involved veterans who qualify for state veterans home placement. The facility coordinates with VA medical centers and Mississippi Veterans Affairs for benefits and discharge planning.",
        description_es="El Hogar Estatal para Veteranos de Mississippi en Collins ofrece cuidado a largo plazo, rehabilitación y servicios de apoyo para veteranos elegibles de Mississippi incluidos veteranos con antecedentes penales que califiquen para colocación en hogar estatal para veteranos.",
        address="670 Veterans Avenue", city="Collins", phone="601-765-2351", email="",
        website="https://www.msva.ms.gov/veterans-homes",
        eligibility="Eligible Mississippi veterans requiring long-term care; admission through Mississippi Veterans Affairs and VA coordination.",
        eligibility_es="Veteranos elegibles de Mississippi que requieren cuidado a largo plazo; admisión a través de Mississippi Veterans Affairs y coordinación VA.",
        notes="Call 601-765-2351 for admission information; also state veterans homes in Kosciusko and Oxford.",
        notes_es="Llame al 601-765-2351 para información de admisión; también hogares estatales para veteranos en Kosciusko y Oxford.",
        hours="Facility 24/7; admissions Monday–Friday",
        tags="collins|veterans|long-term-care|state-veterans-home|reentry",
        services="Long-term veteran care|Rehabilitation|Supportive services|VA benefits coordination|Discharge planning",
        county="Covington", served_counties="", coverage="statewide",
        _source="https://www.msva.ms.gov/veterans-homes", _source_type="government", _confidence="high",
    )
    add(
        name="Delta Regional Medical Center — Veterans Outreach",
        category="veterans", region="Greenville / Washington County",
        description="Delta Regional Medical Center in Greenville provides healthcare services with veterans outreach coordination connecting Delta region veterans including justice-involved veterans to VA Gulf Coast and Jackson VA medical centers, Mississippi Veterans Affairs service officers, and local employment partners.",
        description_es="Delta Regional Medical Center en Greenville ofrece servicios de salud con coordinación de alcance para veteranos que conecta a veteranos de la región Delta incluidos veteranos con antecedentes penales con centros médicos VA y oficiales de servicios para veteranos de Mississippi.",
        address="1400 East Union Street", city="Greenville", phone="662-334-4100", email="",
        website="https://www.deltregional.com",
        eligibility="Delta region patients including veterans; VA referral coordination for eligible veterans.",
        eligibility_es="Pacientes de la región Delta incluidos veteranos; coordinación de referencias VA para veteranos elegibles.",
        notes="Call 662-334-4100; pairs with Delta Health Alliance and Greenville WIN Job Center.",
        notes_es="Llame al 662-334-4100; se vincula con Delta Health Alliance y Greenville WIN Job Center.",
        hours="Emergency 24/7; offices Monday–Friday",
        tags="greenville|veterans|healthcare|delta|reentry",
        services="Healthcare services|Veterans outreach|VA referral coordination|Community health programs|Employment referrals",
        county="Washington", served_counties="Washington|Bolivar|Sunflower|Issaquena|Sharkey", coverage="multi",
        _source="https://www.deltregional.com", _source_type="nonprofit", _confidence="high",
    )

    # --- food ---
    add(
        name="Mississippi Food Network",
        category="food-nutrition", region="Jackson / Hinds County",
        description="Mississippi Food Network is the state's largest food bank, distributing emergency food boxes and partnering with pantries across all 82 counties to serve food-insecure residents including returning citizens reestablishing food security after release from MDOC custody or county jails. Pantry locator at msfoodnet.org—not a walk-in benefits office.",
        description_es="Mississippi Food Network es el banco de alimentos más grande del estado, distribuyendo cajas de alimentos de emergencia y asociándose con despensas en los 82 condados para servir a residentes con inseguridad alimentaria incluidos ciudadanos que regresan.",
        address="440 West Beatty Street", city="Jackson", phone="601-973-3990", email="",
        website="https://www.msfoodnet.org",
        eligibility="Food-insecure Mississippi residents; partner pantries may require income screening; justice-involved clients welcome.",
        eligibility_es="Residentes de Mississippi con inseguridad alimentaria; las despensas asociadas pueden requerir evaluación de ingresos; clientes con antecedentes penales bienvenidos.",
        notes="Find nearest pantry at msfoodnet.org; call 601-973-3990; pairs with access.ms.gov SNAP enrollment.",
        notes_es="Encuentre la despensa más cercana en msfoodnet.org; llame al 601-973-3990; se vincula con inscripción SNAP access.ms.gov.",
        hours="Warehouse Monday–Friday; pantry hours vary",
        tags="jackson|food-nutrition|food-bank|statewide|reentry",
        services="Emergency food distribution|Partner pantry network|SNAP outreach|Food insecurity navigation",
        county="Hinds", served_counties="", coverage="statewide",
        _source="https://www.msfoodnet.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Gulf Coast Public Safety Feed the Needy",
        category="food-nutrition", region="Gulfport / Harrison County",
        description="The Gulf Coast Public Safety Feed the Needy program delivers holiday hot meals on Thanksgiving and Christmas to low-income Harrison County households through a partnership of local law enforcement agencies and community volunteers. Returning citizens and families in need can request meal delivery by calling participating police departments—not year-round pantry services.",
        description_es="El programa Gulf Coast Public Safety Feed the Needy entrega comidas calientes en Acción de Gracias y Navidad a hogares de bajos ingresos del condado Harrison a través de una alianza de agencias locales de seguridad pública y voluntarios comunitarios.",
        address="2220 15th Street", city="Gulfport", phone="228-868-5703", email="",
        website="https://www.gulfportpolice.com",
        eligibility="Low-income Harrison County residents needing holiday meal delivery; contact sponsoring law enforcement agency before published deadline.",
        eligibility_es="Residentes de bajos ingresos del condado Harrison que necesitan entrega de comida en días festivos; contacte la agencia de seguridad pública patrocinadora antes de la fecha límite publicada.",
        notes="Request meals through Gulfport Police 228-868-5703, Biloxi Police 228-385-3033, or Harrison County Sheriff 228-896-0606; holiday program only.",
        notes_es="Solicite comidas a través de Gulfport Police 228-868-5703, Biloxi Police 228-385-3033 o Harrison County Sheriff 228-896-0606; solo programa de días festivos.",
        hours="Holiday meal delivery only; call sponsoring agency for deadlines",
        tags="gulfport|harrison|food-nutrition|holiday-meals|reentry",
        services="Holiday hot meal delivery|Law enforcement community partnership|Volunteer meal program",
        county="Harrison", served_counties="Harrison", coverage="single",
        _source="https://www.gulfportpolice.com", _source_type="government", _confidence="high",
    )
    add(
        name="St. Vincent de Paul — Jackson Food Pantry",
        category="food-nutrition", region="Jackson / Hinds County",
        description="Society of St. Vincent de Paul Jackson provides emergency food pantry services, utility assistance referrals, and basic needs support for low-income Hinds County households including returning citizens rebuilding stability after incarceration. Volunteers connect clients to access.ms.gov SNAP enrollment and Mississippi Works.",
        description_es="Sociedad de San Vicente de Paul Jackson ofrece servicios de despensa de alimentos de emergencia, referencias de asistencia con servicios públicos y apoyo de necesidades básicas para hogares de bajos ingresos del condado Hinds incluidos ciudadanos que regresan.",
        address="823 West Capitol Street", city="Jackson", phone="601-969-3121", email="",
        website="https://www.svdpjackson.org",
        eligibility="Low-income Hinds County residents facing food or utility insecurity; justice-involved clients welcome.",
        eligibility_es="Residentes de bajos ingresos del condado Hinds que enfrentan inseguridad alimentaria o de servicios públicos; clientes con antecedentes penales bienvenidos.",
        notes="Call 601-969-3121 for pantry hours; bring ID if available; pairs with Stewpot Community Services.",
        notes_es="Llame al 601-969-3121 para horario de despensa; traiga identificación si está disponible; se vincula con Stewpot Community Services.",
        hours="Pantry hours vary; call ahead",
        tags="jackson|food-nutrition|food-pantry|basic-needs|reentry",
        services="Emergency food pantry|Utility assistance referrals|Basic needs support|SNAP enrollment referrals",
        county="Hinds", served_counties="Hinds", coverage="single",
        _source="https://www.svdpjackson.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Extra Table — Hattiesburg",
        category="food-nutrition", region="Hattiesburg / Forrest County",
        description="Extra Table operates a food bank and pantry network serving Pine Belt counties including Forrest and Lamar, distributing emergency food to partner agencies serving food-insecure residents such as returning citizens from MDOC custody. Food distribution hub—not a walk-in SNAP office.",
        description_es="Extra Table opera un banco de alimentos y red de despensas que sirve a condados del Pine Belt incluidos Forrest y Lamar, distribuyendo alimentos de emergencia a agencias asociadas que sirven a residentes con inseguridad alimentaria como ciudadanos que regresan de custodia MDOC.",
        address="312 South 38th Avenue", city="Hattiesburg", phone="601-264-0672", email="",
        website="https://www.extratable.org",
        eligibility="Partner agencies serve food-insecure Pine Belt residents; justice-involved clients access food through partner pantries.",
        eligibility_es="Las agencias asociadas sirven a residentes del Pine Belt con inseguridad alimentaria; clientes con antecedentes penales acceden a alimentos a través de despensas asociadas.",
        notes="Call 601-264-0672 for partner pantry locations; pairs with Pine Belt Mental Healthcare and WIN Job Center Hattiesburg.",
        notes_es="Llame al 601-264-0672 para ubicaciones de despensas asociadas; se vincula con Pine Belt Mental Healthcare y WIN Job Center Hattiesburg.",
        hours="Monday–Friday business hours",
        tags="hattiesburg|food-nutrition|food-bank|pine-belt|reentry",
        services="Food bank distribution|Partner pantry network|Emergency food boxes|Agency food supply",
        county="Forrest", served_counties="Forrest|Lamar|Marion|Covington|Jones", coverage="multi",
        _source="https://www.extratable.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Mid-South Food Bank — North Mississippi",
        category="food-nutrition", region="Oxford / Lafayette County",
        description="Mid-South Food Bank serves north Mississippi and the Memphis metro region through partner pantries in Lafayette, Marshall, and surrounding counties, providing emergency food to food-insecure residents including returning citizens establishing food security after release. Pantry locator online—not direct SNAP intake.",
        description_es="Mid-South Food Bank sirve al norte de Mississippi y la región metropolitana de Memphis a través de despensas asociadas en Lafayette, Marshall y condados circundantes, proporcionando alimentos de emergencia a residentes con inseguridad alimentaria incluidos ciudadanos que regresan.",
        address="239 S. Dudley Street", city="Memphis", phone="901-527-0841", email="",
        website="https://www.midsouthfoodbank.org",
        eligibility="Food-insecure north Mississippi residents through partner pantries; justice-involved clients welcome.",
        eligibility_es="Residentes del norte de Mississippi con inseguridad alimentaria a través de despensas asociadas; clientes con antecedentes penales bienvenidos.",
        notes="Find north Mississippi pantries at midsouthfoodbank.org; serves Lafayette, Marshall, Benton, and DeSoto counties.",
        notes_es="Encuentre despensas del norte de Mississippi en midsouthfoodbank.org; sirve Lafayette, Marshall, Benton y DeSoto.",
        hours="Partner pantry hours vary",
        tags="oxford|food-nutrition|food-bank|north-mississippi|reentry",
        services="Emergency food distribution|Partner pantry network|Agency food supply|Food insecurity navigation",
        county="Lafayette", served_counties="Lafayette|Marshall|Benton|DeSoto|Tippah|Union", coverage="multi",
        _source="https://www.midsouthfoodbank.org", _source_type="nonprofit", _confidence="high",
    )

    # --- peer-support ---
    add(
        name="NAMI Mississippi",
        category="peer-support", region="Jackson / Hinds County",
        description="NAMI Mississippi provides peer support groups, family education, and mental health advocacy for Mississippians with mental illness and their families including justice-involved individuals and families navigating reentry and treatment compliance. Support groups coordinate with DMH community mental health centers—not clinical treatment.",
        description_es="NAMI Mississippi ofrece grupos de apoyo entre pares, educación familiar y defensa de salud mental para mississippianos con enfermedades mentales y sus familias incluidas personas con antecedentes penales y familias que navegan la reinserción.",
        address="411 Briarwood Drive, Suite 405", city="Jackson", phone="601-899-2818", email="",
        website="https://www.namims.org",
        eligibility="Open to individuals and families affected by mental illness in Mississippi; no criminal-record restrictions for support groups.",
        eligibility_es="Abierto a personas y familias afectadas por enfermedades mentales en Mississippi; sin restricciones de antecedentes para grupos de apoyo.",
        notes="Call 601-899-2818 for support group schedule; pairs with Hinds Behavioral Health and DMH centers.",
        notes_es="Llame al 601-899-2818 para horario de grupos de apoyo; se vincula con Hinds Behavioral Health y centros DMH.",
        hours="Support groups vary; call for schedule",
        tags="jackson|peer-support|NAMI|mental-health|families|reentry",
        services="Peer support groups|Family education|Mental health advocacy|Crisis resource referrals|Community outreach",
        county="Hinds", served_counties="", coverage="statewide",
        _source="https://www.namims.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Alcoholics Anonymous — Central Mississippi Intergroup",
        category="peer-support", region="Jackson / Hinds County",
        description="Alcoholics Anonymous Central Mississippi Intergroup connects individuals seeking recovery from alcohol use disorder to free peer-led meetings across the Jackson metro and central Mississippi including justice-involved adults referred by MDOC probation, drug courts, and treatment providers. AA is peer support—not a treatment or probation office.",
        description_es="Alcoholics Anonymous Intergrupo del Centro de Mississippi conecta a personas que buscan recuperación del trastorno por uso de alcohol con reuniones gratuitas lideradas por pares en el metro de Jackson y centro de Mississippi incluidos adultos con antecedentes penales referidos por probatoria MDOC.",
        address="PO Box 4274", city="Jackson", phone="601-948-7373", email="",
        website="https://aacms.org",
        eligibility="Open to anyone seeking recovery from alcohol use disorder; no fees; justice-involved participants welcome.",
        eligibility_es="Abierto a cualquier persona que busque recuperación del trastorno por uso de alcohol; sin tarifas; participantes con antecedentes penales bienvenidos.",
        notes="Call 601-948-7373 for meeting locator; meetings statewide; pairs with Born Free New Life and Hinds Behavioral Health.",
        notes_es="Llame al 601-948-7373 para localizador de reuniones; reuniones en todo el estado; se vincula con Born Free New Life y Hinds Behavioral Health.",
        hours="Meetings daily; schedule at aacms.org",
        tags="jackson|peer-support|AA|recovery|substance-use|reentry",
        services="Peer-led recovery meetings|Sponsorship|Meeting locator|Recovery support|Community connections",
        county="Hinds", served_counties="Hinds|Madison|Rankin", coverage="multi",
        _source="https://aacms.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Oxford House — Mississippi Chapters",
        category="peer-support", region="Jackson / Hinds County",
        description="Oxford House chapters across Mississippi provide democratic self-run sober living homes for individuals in recovery from substance use disorders including justice-involved adults transitioning from residential treatment or MDOC release. Residents share housing costs and support each other's recovery while connecting to Mississippi Works and local CMHC treatment.",
        description_es="Los capítulos de Oxford House en Mississippi ofrecen hogares sobrios autogestionados democráticos para personas en recuperación de trastornos por uso de sustancias incluidos adultos con antecedentes penales en transición desde tratamiento residencial o liberación MDOC.",
        address="1010 Lakeland Drive, Suite 500", city="Jackson", phone="601-366-8989", email="",
        website="https://www.oxfordhouse.org",
        eligibility="Adults in recovery from substance use disorders; self-pay rent; justice-involved residents welcome per house policy.",
        eligibility_es="Adultos en recuperación de trastornos por uso de sustancias; alquiler autopagado; residentes con antecedentes penales bienvenidos según política de la casa.",
        notes="Find Mississippi houses at oxfordhouse.org; call 601-366-8989; multiple locations in Jackson, Gulf Coast, and north Mississippi.",
        notes_es="Encuentre casas de Mississippi en oxfordhouse.org; llame al 601-366-8989; múltiples ubicaciones en Jackson, Costa del Golfo y norte de Mississippi.",
        hours="Residential 24/7; contact for vacancy",
        tags="jackson|peer-support|oxford-house|sober-living|recovery|reentry",
        services="Sober living housing|Peer recovery support|Democratic self-governance|Employment coordination|Treatment referrals",
        county="Hinds", served_counties="", coverage="statewide",
        _source="https://www.oxfordhouse.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Mississippi Reentry Project — Peer Navigation",
        category="peer-support", region="Jackson / Hinds County",
        description="The Mississippi Reentry Project provides peer navigation, mentoring, and community resource connections for justice-involved Mississippians returning from MDOC custody and county jails in the Jackson metro and statewide through partner organizations. Peer navigators connect clients to access.ms.gov, Mississippi Works, and Mississippi Center for Legal Services—not emergency cash or shelter.",
        description_es="Mississippi Reentry Project ofrece navegación entre pares, mentoría y conexiones con recursos comunitarios para mississippianos con antecedentes penales que regresan de custodia MDOC y cárceles del condado en el metro de Jackson y en todo el estado.",
        address="633 North State Street", city="Jackson", phone="601-359-5600", email="",
        website="https://www.mdoc.ms.gov",
        eligibility="Justice-involved Mississippi residents seeking reentry navigation; referrals from MDOC, probation, and community partners.",
        eligibility_es="Residentes de Mississippi con antecedentes penales que buscan navegación de reinserción; referencias de MDOC, probatoria y aliados comunitarios.",
        notes="Coordinate through MDOC Community Corrections and assigned probation officer; pairs with WIN Job Center and county MDHS.",
        notes_es="Coordine a través de Correcciones Comunitarias MDOC y oficial de probatoria asignado; se vincula con WIN Job Center y MDHS del condado.",
        hours="Contact for referral hours",
        tags="jackson|peer-support|reentry|navigation|mentoring",
        services="Peer navigation|Mentoring|Community resource connections|Benefits navigation|Employment referrals",
        county="Hinds", served_counties="", coverage="statewide",
        _source="https://www.mdoc.ms.gov", _source_type="government", _confidence="high",
    )
    add(
        name="Gulf Coast Center for Nonviolence — Peer Support",
        category="peer-support", region="Gulfport / Harrison County",
        description="Gulf Coast Center for Nonviolence provides crisis intervention, peer support, and advocacy for survivors of domestic violence and human trafficking on the Mississippi Gulf Coast including justice-involved survivors navigating safety planning and court obligations. Advocates connect clients to Harbor House partners, legal aid, and housing resources.",
        description_es="Gulf Coast Center for Nonviolence ofrece intervención en crisis, apoyo entre pares y defensa para sobrevivientes de violencia doméstica y trata de personas en la Costa del Golfo de Mississippi incluidas sobrevivientes con antecedentes penales.",
        address="PO Box 333", city="Biloxi", phone="228-436-3809", email="",
        website="https://www.gccfn.org",
        eligibility="Survivors of domestic violence and human trafficking on the Gulf Coast; justice-involved survivors eligible per safety assessment.",
        eligibility_es="Sobrevivientes de violencia doméstica y trata de personas en la Costa del Golfo; sobrevivientes con antecedentes penales elegibles según evaluación de seguridad.",
        notes="24/7 crisis line 228-436-3809; confidential intake; pairs with Mississippi Center for Legal Services Gulfport.",
        notes_es="Línea de crisis 24/7 228-436-3809; admisión confidencial; se vincula con Mississippi Center for Legal Services Gulfport.",
        hours="Crisis line 24/7; office Monday–Friday",
        tags="gulfport|peer-support|domestic-violence|crisis|reentry",
        services="Crisis intervention|Peer support|Safety planning|Legal advocacy referrals|Housing resource connections",
        county="Harrison", served_counties="Harrison|Hancock|Jackson|Stone|George", coverage="multi",
        _source="https://www.gccfn.org", _source_type="nonprofit", _confidence="high",
    )
