"""Category minimum fill for North Carolina reentry resources."""


def register_category_fill(add):
    """Add verified rows to meet category minimums not met by phase4/rural depth."""

    # --- housing (+9 needed) ---
    add(
        name="Raleigh Rescue Mission — New Life Plan Transitional Housing",
        category="housing", region="Raleigh / Wake County",
        description="Raleigh Rescue Mission provides transitional housing and wraparound services through its New Life Plan for homeless men, women, and families in Wake County including returning citizens rebuilding stability after incarceration. The phased program offers shelter, meals, counseling, vocational training, and employment support leading to independent housing. Commitment to the multi-month New Life Plan required—not walk-in emergency shelter without intake.",
        description_es="Raleigh Rescue Mission ofrece vivienda transicional y servicios integrales a través de su Plan Nueva Vida para hombres, mujeres y familias sin hogar en el condado Wake, incluidos ciudadanos que regresan que reconstruyen estabilidad después de la encarcelación. El programa por fases ofrece refugio, comidas, consejería, capacitación vocacional y apoyo laboral hacia vivienda independiente. Se requiere compromiso con el plan de varios meses.",
        address="314 East Hargett Street", city="Raleigh", phone="919-828-9014", email="",
        website="https://www.raleighrescue.org",
        eligibility="Homeless adults in Wake County willing to commit to the New Life Plan; justice-involved participants welcome per program policy.",
        eligibility_es="Adultos sin hogar en el condado Wake dispuestos a comprometerse con el Plan Nueva Vida; participantes con antecedentes penales bienvenidos según política.",
        notes="Email MensProgram@raleighrescue.org or WomensProgram@raleighrescue.org; pairs with Wake LRC and NCWorks Capital Area.",
        notes_es="Envíe correo a MensProgram@raleighrescue.org o WomensProgram@raleighrescue.org; se vincula con LRC de Wake y NCWorks.",
        hours="Residential program; contact for intake hours",
        tags="raleigh|wake|housing|transitional|reentry|homeless",
        services="Transitional housing|Meals|Counseling|Vocational training|Employment support|Parenting classes",
        county="Wake", served_counties="Wake", coverage="single",
        _source="https://www.raleighrescue.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Men's Shelter of Charlotte — Emergency & Transitional Housing",
        category="housing", region="Charlotte / Mecklenburg County",
        description="Men's Shelter of Charlotte provides emergency shelter and housing navigation for unhoused men in Mecklenburg County including returning citizens recently released from Mecklenburg County Jail or state custody. Staff at the Housing and Employment Resource Center help guests create resumes, search for jobs, and locate permanent housing through coordinated entry partners. Direct men's shelter services—not a statewide hotline.",
        description_es="Men's Shelter of Charlotte proporciona refugio de emergencia y navegación de vivienda para hombres sin hogar en el condado Mecklenburg, incluidos ciudadanos que regresan recién liberados de la cárcel del condado o custodia estatal. El personal ayuda a crear currículums, buscar empleo y localizar vivienda permanente. Servicios directos de refugio para hombres.",
        address="1210 North Tryon Street", city="Charlotte", phone="704-334-3187", email="",
        website="https://www.mensshelterofcharlotte.org",
        eligibility="Unhoused men in Mecklenburg County; justice-involved men welcome for shelter and employment navigation.",
        eligibility_es="Hombres sin hogar en el condado Mecklenburg; hombres con antecedentes penales bienvenidos para refugio y navegación laboral.",
        notes="Call 704-334-3187 for intake; Housing and Employment Resource Center open for job and housing search assistance.",
        notes_es="Llame al 704-334-3187 para admisión; Centro de Recursos de Vivienda y Empleo abierto para búsqueda de trabajo y vivienda.",
        hours="Contact for shelter intake hours",
        tags="charlotte|mecklenburg|housing|shelter|employment|reentry",
        services="Emergency shelter|Housing navigation|Resume assistance|Job search support|Coordinated entry referrals",
        county="Mecklenburg", served_counties="Mecklenburg", coverage="single",
        _source="https://www.mensshelterofcharlotte.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Salvation Army Center of Hope — Women's Transitional Housing",
        category="housing", region="Charlotte / Mecklenburg County",
        description="The Salvation Army Center of Hope in Charlotte operates one of the largest women's and children's shelters in the Southeast, providing emergency shelter, transitional housing, and case management for unhoused women including justice-involved mothers reuniting with children after release. On-campus programs connect residents to employment, benefits, and permanent housing resources in Mecklenburg County. Direct shelter intake—not a benefits application office.",
        description_es="El Salvation Army Center of Hope en Charlotte opera uno de los refugios para mujeres y niños más grandes del sureste, ofreciendo refugio de emergencia, vivienda transicional y manejo de casos para mujeres sin hogar, incluidas madres con antecedentes penales que se reúnen con sus hijos. Los programas conectan a residentes con empleo, beneficios y vivienda permanente.",
        address="534 Spratt Street", city="Charlotte", phone="704-716-1702", email="",
        website="https://salvationarmycarolinas.org/charlotte/center-of-hope/",
        eligibility="Unhoused women and families in Mecklenburg County; justice-involved women with children welcome per intake policy.",
        eligibility_es="Mujeres y familias sin hogar en el condado Mecklenburg; mujeres con antecedentes penales con hijos bienvenidas según política de admisión.",
        notes="Call 704-716-1702 for shelter intake; coordinates with Mecklenburg Reentry Partners and CCT programs.",
        notes_es="Llame al 704-716-1702 para admisión al refugio; coordina con aliados de reinserción de Mecklenburg y programas CCT.",
        hours="24-hour residential facility; intake hours vary",
        tags="charlotte|mecklenburg|housing|women|families|transitional|reentry",
        services="Emergency shelter|Transitional housing|Case management|Family reunification support|Employment referrals",
        county="Mecklenburg", served_counties="Mecklenburg", coverage="single",
        _source="https://salvationarmycarolinas.org/charlotte/center-of-hope/", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Homeward Bound of WNC — Permanent Supportive Housing",
        category="housing", region="Asheville / Buncombe County",
        description="Homeward Bound of Western North Carolina provides permanent supportive housing, rapid rehousing, and homelessness prevention for unhoused adults in Buncombe County including returning citizens exiting jail or treatment programs. The AHOPE Day Center offers showers, mail receipt, and housing assessments connecting participants to veteran-specific and general housing programs. Housing-focused nonprofit—not emergency cash assistance.",
        description_es="Homeward Bound del oeste de Carolina del Norte ofrece vivienda de apoyo permanente, realojamiento rápido y prevención de la falta de vivienda para adultos sin hogar en el condado Buncombe, incluidos ciudadanos que regresan de la cárcel o programas de tratamiento. El Centro Diurno AHOPE ofrece duchas, recepción de correo y evaluaciones de vivienda.",
        address="19 North Ann Street", city="Asheville", phone="828-252-8883", email="",
        website="https://homewardboundwnc.org",
        eligibility="Unhoused adults in Buncombe County seeking housing assistance; justice-involved individuals welcome through AHOPE intake.",
        eligibility_es="Adultos sin hogar en el condado Buncombe que buscan asistencia de vivienda; personas con antecedentes penales bienvenidas mediante admisión AHOPE.",
        notes="Start at AHOPE Day Center at 19 N Ann St; call 828-252-8883; SSVF program for eligible veterans.",
        notes_es="Comience en el Centro Diurno AHOPE en 19 N Ann St; llame al 828-252-8883; programa SSVF para veteranos elegibles.",
        hours="AHOPE Day Center Monday–Friday business hours",
        tags="asheville|buncombe|housing|supportive-housing|rapid-rehousing|reentry",
        services="Permanent supportive housing|Rapid rehousing|Homelessness prevention|Veteran housing supports|Day center services",
        county="Buncombe", served_counties="Buncombe", coverage="single",
        _source="https://homewardboundwnc.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Good Shepherd Center — Wilmington Transitional Housing",
        category="housing", region="Wilmington / New Hanover County",
        description="Good Shepherd Center in Wilmington operates transitional and emergency housing programs for unhoused adults in New Hanover County including returning citizens recently released from local jail or state custody. Case managers connect residents to coastal North Carolina employment, healthcare, and benefits partners while providing meals and shelter on the Martin Street campus. Direct housing services—not a statewide referral hotline.",
        description_es="Good Shepherd Center en Wilmington opera programas de vivienda transicional y de emergencia para adultos sin hogar en el condado New Hanover, incluidos ciudadanos que regresan recién liberados. Los administradores de casos conectan a residentes con aliados de empleo, salud y beneficios mientras proporcionan comidas y refugio en el campus de Martin Street.",
        address="811 Martin Street", city="Wilmington", phone="910-763-4424", email="",
        website="https://goodshepherdcenter.org",
        eligibility="Unhoused adults in New Hanover County; justice-involved individuals welcome for transitional housing tracks.",
        eligibility_es="Adultos sin hogar en el condado New Hanover; personas con antecedentes penales bienvenidas para programas de vivienda transicional.",
        notes="Call 910-763-4424 for housing intake; connects to NCWorks Wilmington and New Hanover LRC.",
        notes_es="Llame al 910-763-4424 para admisión de vivienda; conecta con NCWorks Wilmington y LRC de New Hanover.",
        hours="Contact for program hours",
        tags="wilmington|new-hanover|housing|transitional|reentry|shelter",
        services="Transitional housing|Emergency shelter|Case management|Meals|Employment and benefits referrals",
        county="New Hanover", served_counties="New Hanover", coverage="single",
        _source="https://goodshepherdcenter.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="CASA — Transitional Living Program",
        category="housing", region="Durham / Orange County",
        description="CASA (Community Alternatives for Supportive Abodes) provides affordable and supportive housing including transitional living for low-income adults in Durham and Orange counties, serving justice-involved tenants through permanent supportive housing and rapid rehousing partnerships. Property management and supportive services help returning citizens maintain stable leases and connect to local reentry resources. Housing provider—not emergency walk-in shelter.",
        description_es="CASA (Alternativas Comunitarias para Viviendas de Apoyo) ofrece vivienda asequible y de apoyo incluyendo vida transicional para adultos de bajos ingresos en los condados Durham y Orange, sirviendo a inquilinos con antecedentes penales mediante vivienda de apoyo permanente. La administración de propiedades ayuda a quienes regresan a mantener arrendamientos estables.",
        address="632 N Mangum Street", city="Durham", phone="919-941-8700", email="",
        website="https://www.casata.org",
        eligibility="Low-income adults in Durham and Orange counties; some units designated for formerly homeless or justice-involved tenants.",
        eligibility_es="Adultos de bajos ingresos en los condados Durham y Orange; algunas unidades designadas para inquilinos anteriormente sin hogar o con antecedentes penales.",
        notes="Call 919-941-8700 for housing availability; partners with Durham LRC and NC FIT programs.",
        notes_es="Llame al 919-941-8700 para disponibilidad de vivienda; aliados con LRC de Durham y programas NC FIT.",
        hours="Office Monday–Friday business hours",
        tags="durham|orange|housing|supportive|transitional|reentry",
        services="Supportive housing|Transitional living|Affordable rental units|Tenant support services|Reentry housing partnerships",
        county="Durham", served_counties="Durham|Orange", coverage="multi",
        _source="https://www.casata.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Family Promise of the Triangle — Shelter & Rehousing",
        category="housing", region="Durham / Wake County",
        description="Family Promise of the Triangle provides emergency shelter, case management, and rehousing assistance for homeless families in Wake, Durham, and Orange counties including parents returning from incarceration seeking reunification with children. Congregation-based shelter network and stabilization services connect families to employment, childcare, and permanent housing. Family-focused program—not single-adult men's shelter.",
        description_es="Family Promise of the Triangle ofrece refugio de emergencia, manejo de casos y asistencia de realojamiento para familias sin hogar en los condados Wake, Durham y Orange, incluidos padres que regresan de la encarcelación que buscan reunificación con sus hijos. La red de refugios comunitarios conecta familias con empleo, cuidado infantil y vivienda permanente.",
        address="908 North Mangum Street", city="Durham", phone="919-682-7963", email="",
        website="https://www.familypromisetriangle.org",
        eligibility="Homeless families with children in Wake, Durham, or Orange counties; justice-involved parents welcome.",
        eligibility_es="Familias sin hogar con niños en los condados Wake, Durham u Orange; padres con antecedentes penales bienvenidos.",
        notes="Call 919-682-7963 for intake; serves Triangle families through host congregation network.",
        notes_es="Llame al 919-682-7963 para admisión; sirve familias del Triángulo a través de red de congregaciones.",
        hours="Contact for intake hours",
        tags="durham|wake|orange|housing|families|reunification|reentry",
        services="Emergency family shelter|Case management|Rehousing assistance|Employment navigation|Childcare referrals",
        county="Durham", served_counties="Wake|Durham|Orange", coverage="multi",
        _source="https://www.familypromisetriangle.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Moore Place — Permanent Supportive Housing",
        category="housing", region="Charlotte / Mecklenburg County",
        description="Moore Place is Charlotte's permanent supportive housing community for chronically homeless adults including returning citizens with disabilities or long-term homelessness histories in Mecklenburg County. On-site case management, healthcare coordination, and life skills programming help residents maintain housing stability and connect to NCWorks and behavioral health partners. Permanent housing—not short-term emergency shelter.",
        description_es="Moore Place es la comunidad de vivienda de apoyo permanente de Charlotte para adultos crónicamente sin hogar, incluidos ciudadanos que regresan con discapacidades o historiales prolongados de falta de vivienda en el condado Mecklenburg. El manejo de casos en el sitio ayuda a residentes a mantener estabilidad habitacional y conectarse con NCWorks.",
        address="3106 Wilkinson Boulevard", city="Charlotte", phone="704-334-8300", email="",
        website="https://www.mooreplace.org",
        eligibility="Chronically homeless adults in Mecklenburg County meeting HUD chronic homelessness criteria; justice-involved adults may qualify.",
        eligibility_es="Adultos crónicamente sin hogar en el condado Mecklenburg que cumplan criterios HUD; adultos con antecedentes penales pueden calificar.",
        notes="Referral through Mecklenburg Coordinated Entry; call 704-334-8300 for program information.",
        notes_es="Referencia a través de Admisión Coordinada de Mecklenburg; llame al 704-334-8300 para información del programa.",
        hours="Residential community; office Monday–Friday",
        tags="charlotte|mecklenburg|housing|permanent-supportive|chronic-homeless|reentry",
        services="Permanent supportive housing|On-site case management|Healthcare coordination|Life skills programming|Employment referrals",
        county="Mecklenburg", served_counties="Mecklenburg", coverage="single",
        _source="https://www.mooreplace.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="NC Housing Finance Agency — Supportive Housing Resources",
        category="housing", region="Statewide",
        description="The North Carolina Housing Finance Agency administers affordable and supportive housing programs including rental assistance and development funding that justice-involved North Carolinians access through local housing authorities and nonprofit providers statewide. NCHFA resources help returning citizens locate subsidized units and navigate tenant-based rental assistance after release. State housing finance agency—not walk-in emergency shelter intake.",
        description_es="La Agencia de Financiamiento de Vivienda de Carolina del Norte administra programas de vivienda asequible y de apoyo incluyendo asistencia de alquiler y financiamiento que carolinenses con antecedentes penales acceden a través de autoridades locales y proveedores sin fines de lucro. Los recursos NCHFA ayudan a quienes regresan a localizar unidades subsidiadas.",
        address="3508 Bush Street", city="Raleigh", phone="919-877-5700", email="",
        website="https://www.nchfa.com",
        eligibility="North Carolina residents seeking affordable or supportive housing through NCHFA-funded programs; eligibility varies by property.",
        eligibility_es="Residentes de Carolina del Norte que buscan vivienda asequible o de apoyo mediante programas financiados por NCHFA; la elegibilidad varía por propiedad.",
        notes="Search affordable rentals at nchfa.com; connect through local housing authorities and coordinated entry systems.",
        notes_es="Busque alquileres asequibles en nchfa.com; conéctese a través de autoridades locales de vivienda y sistemas de admisión coordinada.",
        hours="State office Monday–Friday business hours",
        tags="statewide|housing|affordable|rental-assistance|supportive-housing|reentry",
        services="Affordable housing locator|Supportive housing program information|Rental assistance navigation|Housing authority referrals",
        county="Wake", served_counties="", coverage="statewide",
        _source="https://www.nchfa.com", _source_type="government", _confidence="high",
    )

    # --- healthcare (+8 needed) ---
    add(
        name="Blue Ridge Health — Western NC FQHC",
        category="healthcare", region="Asheville / Western NC",
        description="Blue Ridge Health is a Federally Qualified Health Center providing primary care, dental, behavioral health, and sliding-fee services to uninsured and low-income residents across western North Carolina including justice-involved adults rebuilding health coverage after release. Clinics in Buncombe, Henderson, Haywood, and surrounding counties accept Medicaid and offer substance use treatment referrals. Direct clinical services—not a crisis hotline.",
        description_es="Blue Ridge Health es un Centro de Salud Calificado Federalmente que ofrece atención primaria, dental, salud conductual y servicios con tarifa móvil a residentes sin seguro y de bajos ingresos en el oeste de Carolina del Norte, incluidos adultos con antecedentes penales. Las clínicas aceptan Medicaid y ofrecen referencias de tratamiento de uso de sustancias.",
        address="303 Airport Road", city="Arden", phone="828-698-2979", email="",
        website="https://www.brchs.com",
        eligibility="Uninsured and low-income residents in western NC service area; justice-involved patients welcome; sliding fee available.",
        eligibility_es="Residentes sin seguro y de bajos ingresos en el área de servicio del oeste de NC; pacientes con antecedentes penales bienvenidos; tarifa móvil disponible.",
        notes="Serves Buncombe, Henderson, Haywood, Jackson, Macon, Polk, Rutherford, Transylvania and more; call 828-698-2979.",
        notes_es="Sirve Buncombe, Henderson, Haywood, Jackson, Macon, Polk, Rutherford, Transylvania y más; llame al 828-698-2979.",
        hours="Clinic hours vary by location; typically Monday–Friday",
        tags="asheville|buncombe|healthcare|FQHC|sliding-fee|reentry",
        services="Primary care|Dental services|Behavioral health|Sliding-fee care|Medicaid enrollment|Substance use referrals",
        county="Buncombe", served_counties="Buncombe|Henderson|Haywood|Jackson|Macon|Polk|Rutherford|Transylvania|McDowell|Swain", coverage="multi",
        _source="https://www.brchs.com", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="MAHEC Family Health Center — Asheville",
        category="healthcare", region="Asheville / Buncombe County",
        description="The Mountain Area Health Education Center Family Health Center in Asheville provides primary care, behavioral health, and care coordination for low-income Buncombe County residents including returning citizens establishing medical homes after incarceration. MAHEC accepts Medicaid and offers integrated substance use and mental health services through its FQHC network. Appointment-based clinic—not emergency room.",
        description_es="El Centro de Salud Familiar MAHEC en Asheville ofrece atención primaria, salud conductual y coordinación de cuidados para residentes de bajos ingresos del condado Buncombe, incluidos ciudadanos que regresan que establecen hogares médicos después de la encarcelación. MAHEC acepta Medicaid y ofrece servicios integrados de salud mental.",
        address="121 Hendersonville Road", city="Asheville", phone="828-257-4400", email="",
        website="https://mahec.net",
        eligibility="Low-income Buncombe County residents; Medicaid and uninsured patients welcome including justice-involved adults.",
        eligibility_es="Residentes de bajos ingresos del condado Buncombe; pacientes Medicaid y sin seguro bienvenidos incluidos adultos con antecedentes penales.",
        notes="Call 828-257-4400 for appointments; partners with Blue Ridge Health and Buncombe reentry programs.",
        notes_es="Llame al 828-257-4400 para citas; aliados con Blue Ridge Health y programas de reinserción de Buncombe.",
        hours="Monday–Friday clinic hours",
        tags="asheville|buncombe|healthcare|FQHC|primary-care|reentry",
        services="Primary care|Behavioral health|Care coordination|Medicaid services|Substance use treatment",
        county="Buncombe", served_counties="Buncombe", coverage="single",
        _source="https://mahec.net", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Kinston Community Health Center",
        category="healthcare", region="Kinston / Lenoir County",
        description="Kinston Community Health Center is a Federally Qualified Health Center serving low-income and uninsured residents of Lenoir, Greene, and surrounding eastern North Carolina counties including justice-involved adults returning from local jail or state custody. Sliding-fee primary care, behavioral health, and pharmacy services help returning citizens establish Medicaid-eligible medical homes. Direct clinic services—not a hospital emergency department.",
        description_es="Kinston Community Health Center es un Centro de Salud Calificado Federalmente que sirve a residentes de bajos ingresos y sin seguro de Lenoir, Greene y condados del este de Carolina del Norte, incluidos adultos con antecedentes penales. Atención primaria con tarifa móvil, salud conductual y servicios de farmacia ayudan a establecer hogares médicos.",
        address="522 North Queen Street", city="Kinston", phone="252-527-4000", email="",
        website="https://www.kinstonchc.org",
        eligibility="Uninsured and low-income residents in Kinston CHC service area; sliding fee scale available.",
        eligibility_es="Residentes sin seguro y de bajos ingresos en el área de servicio de Kinston CHC; escala de tarifa móvil disponible.",
        notes="Call 252-527-4000 for appointments; serves Lenoir, Greene, and surrounding eastern NC counties.",
        notes_es="Llame al 252-527-4000 para citas; sirve Lenoir, Greene y condados circundantes del este de NC.",
        hours="Monday–Friday clinic hours",
        tags="kinston|lenoir|healthcare|FQHC|eastern-nc|reentry",
        services="Primary care|Behavioral health|Pharmacy services|Sliding-fee care|Medicaid enrollment assistance",
        county="Lenoir", served_counties="Lenoir|Greene|Jones|Duplin", coverage="multi",
        _source="https://www.kinstonchc.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Cabarrus Health Alliance — Community Health",
        category="healthcare", region="Concord / Cabarrus County",
        description="Cabarrus Health Alliance operates as North Carolina's only combined public health authority and FQHC, providing primary care, dental, and behavioral health for uninsured and Medicaid patients in Cabarrus County including returning citizens from local jail seeking medical homes. Sliding-fee services and care coordination connect patients to DSS benefits and NCWorks Concord. Public health and clinical services—not emergency psychiatric crisis center.",
        description_es="Cabarrus Health Alliance opera como la única autoridad combinada de salud pública y FQHC de Carolina del Norte, ofreciendo atención primaria, dental y conductual para pacientes sin seguro y Medicaid en el condado Cabarrus, incluidos ciudadanos que regresan de la cárcel local. Servicios con tarifa móvil conectan pacientes con beneficios DSS.",
        address="300 Mooresville Road", city="Kannapolis", phone="704-920-1000", email="",
        website="https://www.cabarrushealth.org",
        eligibility="Cabarrus County residents; uninsured and Medicaid patients including justice-involved adults welcome.",
        eligibility_es="Residentes del condado Cabarrus; pacientes sin seguro y Medicaid incluidos adultos con antecedentes penales bienvenidos.",
        notes="Call 704-920-1000 for appointments; Kannapolis and Concord clinic locations listed at cabarrushealth.org.",
        notes_es="Llame al 704-920-1000 para citas; ubicaciones de clínicas en Kannapolis y Concord en cabarrushealth.org.",
        hours="Monday–Friday clinic hours",
        tags="concord|cabarrus|healthcare|FQHC|public-health|reentry",
        services="Primary care|Dental care|Behavioral health|Sliding-fee services|Public health programs",
        county="Cabarrus", served_counties="Cabarrus", coverage="single",
        _source="https://www.cabarrushealth.org", _source_type="government", _confidence="high",
    )
    add(
        name="CommWell Health — Rural Eastern NC FQHC",
        category="healthcare", region="Clinton / Sampson County",
        description="CommWell Health is a Federally Qualified Health Center network serving rural eastern North Carolina counties including Sampson, Duplin, Bladen, and Johnston with primary care, dental, behavioral health, and pharmacy services for uninsured and Medicaid patients. Justice-involved adults returning to rural communities access sliding-fee care and substance use referrals through CommWell clinics. Multi-county FQHC—not a statewide hotline.",
        description_es="CommWell Health es una red de Centros de Salud Calificados Federalmente que sirve condados rurales del este de Carolina del Norte incluyendo Sampson, Duplin, Bladen y Johnston con atención primaria, dental, salud conductual y farmacia. Adultos con antecedentes penales acceden a atención con tarifa móvil y referencias de uso de sustancias.",
        address="566 Beaman Street", city="Clinton", phone="910-567-7114", email="",
        website="https://www.commwellhealth.org",
        eligibility="Uninsured and low-income residents in CommWell service counties; Medicaid accepted; sliding fee available.",
        eligibility_es="Residentes sin seguro y de bajos ingresos en condados de servicio CommWell; Medicaid aceptado; tarifa móvil disponible.",
        notes="Multiple clinic locations across Sampson, Duplin, Bladen counties; call 910-567-7114 for nearest site.",
        notes_es="Múltiples ubicaciones en condados Sampson, Duplin, Bladen; llame al 910-567-7114 para el sitio más cercano.",
        hours="Clinic hours vary by location",
        tags="clinton|sampson|healthcare|FQHC|rural|reentry",
        services="Primary care|Dental services|Behavioral health|Pharmacy|Sliding-fee care|Substance use referrals",
        county="Sampson", served_counties="Sampson|Duplin|Bladen|Johnston|Harnett", coverage="multi",
        _source="https://www.commwellhealth.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="ECU Health Community Care — Greenville",
        category="healthcare", region="Greenville / Pitt County",
        description="ECU Health Community Care operates Federally Qualified Health Center clinics across eastern North Carolina including Pitt, Beaufort, and Martin counties, providing primary care, behavioral health, and care management for uninsured and Medicaid patients including justice-involved adults. Sliding-fee services and NC Medicaid enrollment assistance help returning citizens establish medical homes after release from Pitt County Detention Center or state custody.",
        description_es="ECU Health Community Care opera clínicas FQHC en el este de Carolina del Norte incluyendo Pitt, Beaufort y Martin, ofreciendo atención primaria, salud conductual y manejo de cuidados para pacientes sin seguro y Medicaid incluidos adultos con antecedentes penales. Servicios con tarifa móvil ayudan a establecer hogares médicos.",
        address="2210 Stantonsburg Road", city="Greenville", phone="252-847-9800", email="",
        website="https://www.ecuhealth.org/services/community-care/",
        eligibility="Uninsured and Medicaid patients in ECU Health Community Care service area; sliding fee scale available.",
        eligibility_es="Pacientes sin seguro y Medicaid en el área de servicio ECU Health Community Care; escala de tarifa móvil disponible.",
        notes="Call 252-847-9800 for appointments; multiple eastern NC clinic locations at ecuhealth.org.",
        notes_es="Llame al 252-847-9800 para citas; múltiples ubicaciones de clínicas del este de NC en ecuhealth.org.",
        hours="Monday–Friday clinic hours",
        tags="greenville|pitt|healthcare|FQHC|eastern-nc|reentry",
        services="Primary care|Behavioral health|Care management|Sliding-fee care|Medicaid enrollment",
        county="Pitt", served_counties="Pitt|Beaufort|Martin|Edgecombe|Wilson", coverage="multi",
        _source="https://www.ecuhealth.org/services/community-care/", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Goshen Medical Center — Eastern NC FQHC",
        category="healthcare", region="Faison / Duplin County",
        description="Goshen Medical Center is a Federally Qualified Health Center providing primary care, dental, and behavioral health across rural eastern North Carolina counties including Duplin, Sampson, Wayne, and Lenoir. Justice-involved adults in agricultural and rural communities access sliding-fee care, pharmacy services, and Medicaid enrollment assistance at Goshen clinic locations. Multi-site FQHC—not an emergency room.",
        description_es="Goshen Medical Center es un Centro de Salud Calificado Federalmente que ofrece atención primaria, dental y conductual en condados rurales del este de Carolina del Norte incluyendo Duplin, Sampson, Wayne y Lenoir. Adultos con antecedentes penales en comunidades rurales acceden a atención con tarifa móvil y asistencia de inscripción Medicaid.",
        address="107 Goshen Drive", city="Faison", phone="910-267-0479", email="",
        website="https://www.goshenmedical.org",
        eligibility="Uninsured and low-income residents in Goshen service counties; Medicaid and sliding fee accepted.",
        eligibility_es="Residentes sin seguro y de bajos ingresos en condados de servicio Goshen; Medicaid y tarifa móvil aceptados.",
        notes="Multiple eastern NC locations; call 910-267-0479 or visit goshenmedical.org for clinic finder.",
        notes_es="Múltiples ubicaciones del este de NC; llame al 910-267-0479 o visite goshenmedical.org.",
        hours="Clinic hours vary by location",
        tags="faison|duplin|healthcare|FQHC|rural|eastern-nc|reentry",
        services="Primary care|Dental care|Behavioral health|Pharmacy|Sliding-fee care|Medicaid assistance",
        county="Duplin", served_counties="Duplin|Sampson|Wayne|Lenoir|Greene|Jones", coverage="multi",
        _source="https://www.goshenmedical.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="NC Medicaid Ombudsman — Enrollment Help",
        category="healthcare", region="Statewide",
        description="The NC Medicaid Ombudsman program helps North Carolina residents including justice-involved adults navigate Medicaid enrollment, redetermination, and coverage disputes after release from custody. Trained ombudsmen provide free assistance understanding Medicaid managed care plans, finding providers, and resolving billing issues across all 100 counties. Advocacy and navigation—not clinical care.",
        description_es="El programa Ombudsman de Medicaid de NC ayuda a residentes de Carolina del Norte incluidos adultos con antecedentes penales a navegar inscripción Medicaid, redeterminación y disputas de cobertura después de la liberación. Ombudsmen capacitados ofrecen asistencia gratuita para entender planes de cuidado administrado Medicaid.",
        address="1201 Front Street", city="Raleigh", phone="877-201-3750", email="",
        website="https://www.ncmedicaidombudsman.org",
        eligibility="North Carolina Medicaid beneficiaries and applicants needing enrollment or coverage assistance.",
        eligibility_es="Beneficiarios y solicitantes de Medicaid de Carolina del Norte que necesitan asistencia de inscripción o cobertura.",
        notes="Call 877-201-3750 toll-free; helps with managed care plan selection and provider access statewide.",
        notes_es="Llame gratis al 877-201-3750; ayuda con selección de plan de cuidado administrado y acceso a proveedores.",
        hours="Monday–Friday business hours",
        tags="statewide|healthcare|Medicaid|ombudsman|enrollment|reentry",
        services="Medicaid enrollment assistance|Coverage dispute help|Managed care navigation|Provider access support",
        county="Wake", served_counties="", coverage="statewide",
        _source="https://www.ncmedicaidombudsman.org", _source_type="nonprofit", _confidence="high",
    )

    # --- education (+7 needed) ---
    add(
        name="NC Community College System — Adult High School Equivalency",
        category="education", region="Statewide",
        description="The North Carolina Community College System offers free adult education and High School Equivalency preparation through GED and HiSET at all 58 community colleges statewide, helping justice-involved North Carolinians earn diplomas required for NCWorks training and employment after release. Local community college adult education offices provide orientation, classes, and testing referrals in every county region. Statewide navigation resource—not a walk-in classroom at the Raleigh office.",
        description_es="El Sistema de Colegios Comunitarios de Carolina del Norte ofrece educación para adultos gratuita y preparación de Equivalencia de Secundaria mediante GED e HiSET en los 58 colegios comunitarios, ayudando a carolinenses con antecedentes penales a obtener diplomas requeridos para capacitación NCWorks. Las oficinas locales de educación para adultos ofrecen orientación, clases y referencias de exámenes.",
        address="200 West Jones Street", city="Raleigh", phone="919-807-7100", email="",
        website="https://www.nccommunitycolleges.edu/students/what-we-offer/finish-high-school/",
        eligibility="North Carolina adults age 16+ not enrolled in high school seeking GED or HiSET; criminal record not a barrier.",
        eligibility_es="Adultos de Carolina del Norte de 16 años o más no inscritos en secundaria que buscan GED o HiSET; los antecedentes penales no son barrera.",
        notes="Contact your local community college adult education office; transcripts via DiplomaSender at 855-313-5799.",
        notes_es="Contacte la oficina de educación para adultos de su colegio comunitario local; transcripciones vía DiplomaSender al 855-313-5799.",
        hours="Local sites vary; state office Monday–Friday",
        tags="statewide|education|GED|HiSET|adult-education|reentry",
        services="GED preparation|HiSET preparation|Adult high school diploma|Local site locator|Testing referrals",
        county="Wake", served_counties="", coverage="statewide",
        _source="https://www.nccommunitycolleges.edu/students/what-we-offer/finish-high-school/", _source_type="government", _confidence="high",
    )
    add(
        name="Cape Fear Community College — Adult Education",
        category="education", region="Wilmington / New Hanover County",
        description="Cape Fear Community College Adult Education provides GED and HiSET preparation, adult literacy, and workforce transition classes for low-income adults in New Hanover, Brunswick, and Pender counties including returning citizens from New Hanover County Jail seeking credentials for coastal North Carolina jobs. Free instruction connects graduates to NCWorks Wilmington and local employers. Enrollment required before classes begin.",
        description_es="Cape Fear Community College Educación para Adultos ofrece preparación GED e HiSET, alfabetización para adultos y clases de transición laboral para adultos de bajos ingresos en los condados New Hanover, Brunswick y Pender, incluidos ciudadanos que regresan de la cárcel del condado. Instrucción gratuita conecta graduados con NCWorks Wilmington.",
        address="411 North Front Street", city="Wilmington", phone="910-362-7323", email="",
        website="https://cfcc.edu/adult-education/",
        eligibility="Adults age 16+ in Cape Fear CC service area seeking GED or HiSET; justice-involved adults accepted.",
        eligibility_es="Adultos de 16 años o más en el área de servicio de Cape Fear CC que buscan GED o HiSET; adultos con antecedentes penales aceptados.",
        notes="Call 910-362-7323 for enrollment; Wilmington and Burgaw campus locations available.",
        notes_es="Llame al 910-362-7323 para inscripción; ubicaciones de campus Wilmington y Burgaw disponibles.",
        hours="Contact for class schedule",
        tags="wilmington|new-hanover|education|GED|HiSET|reentry",
        services="GED preparation|HiSET preparation|Adult literacy|Workforce transition|NCWorks referrals",
        county="New Hanover", served_counties="New Hanover|Brunswick|Pender", coverage="multi",
        _source="https://cfcc.edu/adult-education/", _source_type="government", _confidence="high",
    )
    add(
        name="Pitt Community College — Adult Education",
        category="education", region="Greenville / Pitt County",
        description="Pitt Community College Adult Education offers GED and HiSET preparation for justice-involved adults in Pitt, Greene, and surrounding eastern North Carolina counties rebuilding education credentials after release from Pitt County Detention Center or state custody. Free classes prepare participants for high school equivalency exams and connect to ECU Health employment partners and NCWorks Greenville career centers.",
        description_es="Pitt Community College Educación para Adultos ofrece preparación GED e HiSET para adultos con antecedentes penales en Pitt, Greene y condados del este de Carolina del Norte que reconstruyen credenciales educativas. Clases gratuitas preparan para exámenes de equivalencia y conectan con NCWorks Greenville.",
        address="1986 Pitt Tech Road", city="Winterville", phone="252-493-7494", email="",
        website="https://www.pittcc.edu/academics/adult-education/",
        eligibility="Adults age 16+ in Pitt CC service area; open to returning citizens per local enrollment policy.",
        eligibility_es="Adultos de 16 años o más en el área de servicio de Pitt CC; abierto a ciudadanos que regresan según política local.",
        notes="Call 252-493-7494 for orientation; Winterville campus serves Pitt and Greene counties.",
        notes_es="Llame al 252-493-7494 para orientación; campus Winterville sirve condados Pitt y Greene.",
        hours="Contact for class schedule",
        tags="greenville|pitt|education|GED|HiSET|reentry",
        services="GED preparation|HiSET preparation|Adult literacy|Workforce referrals|Career center connections",
        county="Pitt", served_counties="Pitt|Greene|Martin", coverage="multi",
        _source="https://www.pittcc.edu/academics/adult-education/", _source_type="government", _confidence="high",
    )
    add(
        name="Nash Community College — Adult Education",
        category="education", region="Rocky Mount / Nash County",
        description="Nash Community College Adult Education provides GED and HiSET preparation for low-income adults in Nash, Edgecombe, and Halifax counties including returning citizens from Rocky Mount area jails seeking credentials for eastern North Carolina employment. Free instruction at the Rocky Mount campus connects graduates to NCWorks Twin Counties and local manufacturing employers. Orientation required for enrollment.",
        description_es="Nash Community College Educación para Adultos ofrece preparación GED e HiSET para adultos de bajos ingresos en los condados Nash, Edgecombe y Halifax, incluidos ciudadanos que regresan de cárceles del área de Rocky Mount. Instrucción gratuita conecta graduados con NCWorks Twin Counties.",
        address="522 North Old Carriage Road", city="Rocky Mount", phone="252-451-8240", email="",
        website="https://www.nashcc.edu/adult-education",
        eligibility="Adults age 16+ in Nash CC service area seeking GED or HiSET; justice-involved adults welcome.",
        eligibility_es="Adultos de 16 años o más en el área de servicio de Nash CC que buscan GED o HiSET; adultos con antecedentes penales bienvenidos.",
        notes="Call 252-451-8240 for enrollment; serves Nash, Edgecombe, and Halifax county residents.",
        notes_es="Llame al 252-451-8240 para inscripción; sirve residentes de Nash, Edgecombe y Halifax.",
        hours="Contact for class schedule",
        tags="rocky-mount|nash|education|GED|HiSET|reentry",
        services="GED preparation|HiSET preparation|Adult literacy|NCWorks referrals|Workforce transition",
        county="Nash", served_counties="Nash|Edgecombe|Halifax", coverage="multi",
        _source="https://www.nashcc.edu/adult-education", _source_type="government", _confidence="high",
    )
    add(
        name="Mitchell Community College — Adult Education",
        category="education", region="Statesville / Iredell County",
        description="Mitchell Community College Adult Education offers GED and HiSET preparation for adults in Iredell, Alexander, and Catawba counties including justice-involved individuals returning from Iredell County Detention Center seeking credentials for NCWorks and local industrial employment in the Piedmont region. Free classes and testing preparation available at Statesville and Mooresville sites.",
        description_es="Mitchell Community College Educación para Adultos ofrece preparación GED e HiSET para adultos en los condados Iredell, Alexander y Catawba, incluidas personas con antecedentes penales que buscan credenciales para NCWorks y empleo industrial local. Clases gratuitas disponibles en sitios de Statesville y Mooresville.",
        address="500 West Broad Street", city="Statesville", phone="704-878-3235", email="",
        website="https://www.mitchellcc.edu/programs/adult-education/",
        eligibility="Adults age 16+ in Mitchell CC service area; open to justice-involved participants.",
        eligibility_es="Adultos de 16 años o más en el área de servicio de Mitchell CC; abierto a participantes con antecedentes penales.",
        notes="Call 704-878-3235 for enrollment; Statesville and Mooresville campus locations.",
        notes_es="Llame al 704-878-3235 para inscripción; ubicaciones de campus Statesville y Mooresville.",
        hours="Contact for class schedule",
        tags="statesville|iredell|education|GED|HiSET|reentry",
        services="GED preparation|HiSET preparation|Adult literacy|Workforce referrals|Testing preparation",
        county="Iredell", served_counties="Iredell|Alexander|Catawba", coverage="multi",
        _source="https://www.mitchellcc.edu/programs/adult-education/", _source_type="government", _confidence="high",
    )
    add(
        name="Coastal Carolina Community College — Adult Education",
        category="education", region="Jacksonville / Onslow County",
        description="Coastal Carolina Community College Adult Education provides GED and HiSET preparation for adults in Onslow, Carteret, and Duplin counties including returning citizens from Camp Lejeune area and Onslow County Jail seeking credentials for coastal military-adjacent employment markets. Free instruction connects graduates to NCWorks Jacksonville and local workforce partners.",
        description_es="Coastal Carolina Community College Educación para Adultos ofrece preparación GED e HiSET para adultos en los condados Onslow, Carteret y Duplin, incluidos ciudadanos que regresan de la cárcel del condado Onslow que buscan credenciales para mercados laborales costeros. Instrucción gratuita conecta graduados con NCWorks Jacksonville.",
        address="444 Western Boulevard", city="Jacksonville", phone="910-938-6320", email="",
        website="https://www.coastalcarolina.edu/adult-education/",
        eligibility="Adults age 16+ in Coastal Carolina CC service area; justice-involved adults accepted.",
        eligibility_es="Adultos de 16 años o más en el área de servicio de Coastal Carolina CC; adultos con antecedentes penales aceptados.",
        notes="Call 910-938-6320 for enrollment; serves Onslow County and surrounding coastal counties.",
        notes_es="Llame al 910-938-6320 para inscripción; sirve el condado Onslow y condados costeros circundantes.",
        hours="Contact for class schedule",
        tags="jacksonville|onslow|education|GED|HiSET|reentry",
        services="GED preparation|HiSET preparation|Adult literacy|NCWorks referrals|Workforce transition",
        county="Onslow", served_counties="Onslow|Carteret|Duplin", coverage="multi",
        _source="https://www.coastalcarolina.edu/adult-education/", _source_type="government", _confidence="high",
    )
    add(
        name="Rowan-Cabarrus Community College — Adult Education",
        category="education", region="Salisbury / Rowan County",
        description="Rowan-Cabarrus Community College Adult Education offers GED and HiSET preparation for adults in Rowan, Cabarrus, and Stanly counties including justice-involved individuals returning from Rowan County Detention Center seeking credentials for NCWorks and regional manufacturing jobs. Free classes at Salisbury and Kannapolis campuses connect graduates to Goodwill and local employer partners.",
        description_es="Rowan-Cabarrus Community College Educación para Adultos ofrece preparación GED e HiSET para adultos en los condados Rowan, Cabarrus y Stanly, incluidas personas con antecedentes penales que buscan credenciales para NCWorks y empleos manufactureros regionales. Clases gratuitas conectan graduados con Goodwill y empleadores locales.",
        address="1333 Jake Alexander Boulevard South", city="Salisbury", phone="704-216-7209", email="",
        website="https://www.rccc.edu/adult-education/",
        eligibility="Adults age 16+ in Rowan-Cabarrus CC service area; open to returning citizens.",
        eligibility_es="Adultos de 16 años o más en el área de servicio de Rowan-Cabarrus CC; abierto a ciudadanos que regresan.",
        notes="Call 704-216-7209 for enrollment; Salisbury and Kannapolis campus locations.",
        notes_es="Llame al 704-216-7209 para inscripción; ubicaciones de campus Salisbury y Kannapolis.",
        hours="Contact for class schedule",
        tags="salisbury|rowan|education|GED|HiSET|reentry",
        services="GED preparation|HiSET preparation|Adult literacy|Workforce referrals|Employer connections",
        county="Rowan", served_counties="Rowan|Cabarrus|Stanly", coverage="multi",
        _source="https://www.rccc.edu/adult-education/", _source_type="government", _confidence="high",
    )

    # --- basic-needs (+5 needed) ---
    add(
        name="Urban Ministry Center — Charlotte",
        category="basic-needs", region="Charlotte / Mecklenburg County",
        description="Urban Ministry Center in Charlotte provides day services, meals, clothing, hygiene supplies, and resource navigation for unhoused adults in Mecklenburg County including returning citizens recently released from jail or prison. The Room in the Inn winter shelter program and ongoing support connect guests to housing, NCWorks, and healthcare partners. Direct basic-needs services—not a statewide hotline.",
        description_es="Urban Ministry Center en Charlotte ofrece servicios diurnos, comidas, ropa, artículos de higiene y navegación de recursos para adultos sin hogar en el condado Mecklenburg, incluidos ciudadanos recién liberados. El programa Room in the Inn y apoyo continuo conectan a huéspedes con vivienda, NCWorks y aliados de salud.",
        address="945 North College Street", city="Charlotte", phone="704-347-0278", email="",
        website="https://www.urbanministrycenter.org",
        eligibility="Unhoused adults in Mecklenburg County; justice-involved individuals welcome for day services and navigation.",
        eligibility_es="Adultos sin hogar en el condado Mecklenburg; personas con antecedentes penales bienvenidas para servicios diurnos.",
        notes="Call 704-347-0278; day center open weekdays; Room in the Inn shelter November–March.",
        notes_es="Llame al 704-347-0278; centro diurno abierto entre semana; refugio Room in the Inn noviembre–marzo.",
        hours="Day center weekday hours; call for schedule",
        tags="charlotte|mecklenburg|basic-needs|meals|clothing|reentry",
        services="Day services|Meals|Clothing|Hygiene supplies|Resource navigation|Shelter referrals",
        county="Mecklenburg", served_counties="Mecklenburg", coverage="single",
        _source="https://www.urbanministrycenter.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Loaves & Fishes — Charlotte Food Pantry",
        category="basic-needs", region="Charlotte / Mecklenburg County",
        description="Loaves & Fishes provides emergency food assistance through a network of food pantries across Mecklenburg County, serving low-income families and returning citizens establishing food security after release from incarceration. Pantry locations offer groceries, hygiene items, and referrals to DSS SNAP enrollment and NCWorks employment services. Food pantry network—not cash assistance.",
        description_es="Loaves & Fishes proporciona asistencia alimentaria de emergencia a través de una red de despensas en el condado Mecklenburg, sirviendo a familias de bajos ingresos y ciudadanos que regresan que establecen seguridad alimentaria después de la liberación. Las despensas ofrecen comestibles, artículos de higiene y referencias a inscripción SNAP.",
        address="648 Griffith Street", city="Charlotte", phone="704-523-4333", email="",
        website="https://www.loavesandfishes.org",
        eligibility="Low-income Mecklenburg County residents needing food assistance; no criminal-record restrictions stated.",
        eligibility_es="Residentes de bajos ingresos del condado Mecklenburg que necesitan asistencia alimentaria; sin restricciones de antecedentes indicadas.",
        notes="Find nearest pantry at loavesandfishes.org; call 704-523-4333 for pantry locations and hours.",
        notes_es="Encuentre la despensa más cercana en loavesandfishes.org; llame al 704-523-4333 para ubicaciones y horarios.",
        hours="Pantry hours vary by location",
        tags="charlotte|mecklenburg|basic-needs|food-pantry|reentry",
        services="Emergency food assistance|Pantry groceries|Hygiene items|SNAP referrals|Resource navigation",
        county="Mecklenburg", served_counties="Mecklenburg", coverage="single",
        _source="https://www.loavesandfishes.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Inter-Faith Food Shuttle — Wake County",
        category="basic-needs", region="Raleigh / Wake County",
        description="Inter-Faith Food Shuttle fights hunger in Wake and surrounding counties through mobile food markets, community gardens, culinary job training, and direct food distribution for low-income residents including returning citizens rebuilding food security after release. BackPack Buddies and mobile markets serve food deserts across the Triangle. Food and training nonprofit—not emergency cash provider.",
        description_es="Inter-Faith Food Shuttle combate el hambre en Wake y condados circundantes mediante mercados móviles de alimentos, huertos comunitarios, capacitación culinaria laboral y distribución directa para residentes de bajos ingresos incluidos ciudadanos que regresan. Mercados móviles sirven desiertos alimentarios en el Triángulo.",
        address="1001 Blair Drive", city="Raleigh", phone="919-250-0043", email="",
        website="https://foodshuttle.org",
        eligibility="Low-income Wake County residents needing food assistance; culinary training programs have separate eligibility.",
        eligibility_es="Residentes de bajos ingresos del condado Wake que necesitan asistencia alimentaria; programas de capacitación culinaria tienen elegibilidad separada.",
        notes="Call 919-250-0043 or visit foodshuttle.org for mobile market schedule and culinary training enrollment.",
        notes_es="Llame al 919-250-0043 o visite foodshuttle.org para horario de mercados móviles e inscripción culinaria.",
        hours="Office Monday–Friday; mobile market schedules vary",
        tags="raleigh|wake|basic-needs|food|culinary-training|reentry",
        services="Mobile food markets|Food distribution|Culinary job training|Community gardens|SNAP education",
        county="Wake", served_counties="Wake|Durham|Orange|Johnston", coverage="multi",
        _source="https://foodshuttle.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Community Action Partnership of Orange County",
        category="basic-needs", region="Chapel Hill / Orange County",
        description="Community Action Partnership of Orange County provides emergency assistance, utility help, clothing, and resource navigation for low-income Orange County residents including justice-involved adults returning from jail seeking stabilization support. CAPOC connects clients to DSS benefits, NCWorks, and local housing partners through case management. Direct assistance programs—not a statewide referral line.",
        description_es="Community Action Partnership del condado Orange ofrece asistencia de emergencia, ayuda con servicios públicos, ropa y navegación de recursos para residentes de bajos ingresos incluidos adultos con antecedentes penales que buscan apoyo de estabilización. CAPOC conecta clientes con beneficios DSS, NCWorks y aliados de vivienda.",
        address="919 North Bickett Boulevard", city="Hillsborough", phone="919-732-5077", email="",
        website="https://www.capoc.org",
        eligibility="Low-income Orange County residents meeting CAPOC program income guidelines; justice-involved adults welcome.",
        eligibility_es="Residentes de bajos ingresos del condado Orange que cumplan directrices de ingresos de CAPOC; adultos con antecedentes penales bienvenidos.",
        notes="Call 919-732-5077 for emergency assistance intake; Hillsborough office serves all Orange County.",
        notes_es="Llame al 919-732-5077 para admisión de asistencia de emergencia; oficina Hillsborough sirve todo el condado Orange.",
        hours="Monday–Friday business hours",
        tags="hillsborough|orange|basic-needs|emergency-assistance|utilities|reentry",
        services="Emergency assistance|Utility help|Clothing|Resource navigation|Benefits referrals",
        county="Orange", served_counties="Orange", coverage="single",
        _source="https://www.capoc.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Salvation Army of Greensboro — Emergency Assistance",
        category="basic-needs", region="Greensboro / Guilford County",
        description="The Salvation Army of Greensboro provides emergency food, clothing, utility assistance, and disaster relief for low-income Guilford County residents including returning citizens establishing basic stability after release. Seasonal programs and Pathway of Hope case management connect families to employment and housing resources. Direct emergency assistance—not a legal aid or healthcare clinic.",
        description_es="El Salvation Army de Greensboro ofrece alimentos de emergencia, ropa, asistencia con servicios públicos y alivio en desastres para residentes de bajos ingresos del condado Guilford incluidos ciudadanos que regresan que establecen estabilidad básica. Pathway of Hope conecta familias con recursos de empleo y vivienda.",
        address="106 Gate City Boulevard", city="Greensboro", phone="336-274-7175", email="",
        website="https://salvationarmypiedmont.org/greensboro/",
        eligibility="Low-income Guilford County residents in emergency need; program-specific requirements apply.",
        eligibility_es="Residentes de bajos ingresos del condado Guilford en necesidad de emergencia; aplican requisitos específicos del programa.",
        notes="Call 336-274-7175 for emergency assistance; Guilford LRC and StepUp Greensboro partners.",
        notes_es="Llame al 336-274-7175 para asistencia de emergencia; aliados LRC de Guilford y StepUp Greensboro.",
        hours="Monday–Friday; seasonal program hours vary",
        tags="greensboro|guilford|basic-needs|emergency|food|utilities|reentry",
        services="Emergency food|Clothing|Utility assistance|Pathway of Hope case management|Disaster relief",
        county="Guilford", served_counties="Guilford", coverage="single",
        _source="https://salvationarmypiedmont.org/greensboro/", _source_type="nonprofit", _confidence="high",
    )

    # --- legal-aid (+4 needed) ---
    add(
        name="Legal Aid of North Carolina — Wilmington Office",
        category="legal-aid", region="Wilmington / New Hanover County",
        description="Legal Aid of North Carolina Wilmington office provides free civil legal aid to low-income residents of Bladen, Brunswick, Columbus, Duplin, New Hanover, Onslow, and Pender counties including housing, benefits, family law, and expungement assistance for returning citizens. Attorneys handle reentry-related civil legal barriers—not criminal defense representation.",
        description_es="La oficina de Wilmington de Legal Aid of North Carolina ofrece asistencia legal civil gratuita a residentes de bajos ingresos de siete condados costeros incluyendo vivienda, beneficios, derecho familiar y expungación para ciudadanos que regresan. Abogados manejan barreras legales civiles de reinserción, no defensa penal.",
        address="272 North Front Street, Suite 220", city="Wilmington", phone="910-763-6207", email="",
        website="https://www.legalaidnc.org",
        eligibility="Low-income residents of coastal NC counties served by Wilmington office; LSC income limits apply.",
        eligibility_es="Residentes de bajos ingresos de condados costeros servidos por la oficina de Wilmington; aplican límites LSC.",
        notes="Call 910-763-6207 or apply at legalaidnc.org; also use statewide helpline 1-866-219-5262.",
        notes_es="Llame al 910-763-6207 o solicite en legalaidnc.org; también use la línea estatal 1-866-219-5262.",
        hours="Monday–Friday business hours",
        tags="wilmington|new-hanover|legal-aid|expungement|coastal-nc|reentry",
        services="Civil legal representation|Expungement assistance|Housing legal aid|Benefits advocacy|Family law",
        county="New Hanover", served_counties="Bladen|Brunswick|Columbus|Duplin|New Hanover|Onslow|Pender", coverage="multi",
        _source="https://www.legalaidnc.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Legal Aid of North Carolina — Rocky Mount Office",
        category="legal-aid", region="Rocky Mount / Nash County",
        description="Legal Aid of North Carolina Rocky Mount office provides free civil legal assistance to low-income residents of Edgecombe, Greene, Lenoir, Nash, Wayne, and Wilson counties including eviction defense, public benefits appeals, and criminal record relief for justice-involved adults in eastern North Carolina. Extension of the Wilson LANC office serving growing rural demand.",
        description_es="La oficina de Rocky Mount de Legal Aid of North Carolina ofrece asistencia legal civil gratuita a residentes de bajos ingresos de Edgecombe, Greene, Lenoir, Nash, Wayne y Wilson incluyendo defensa de desalojo, apelaciones de beneficios y alivio de antecedentes penales.",
        address="101 Tarboro Street, Suite 100", city="Rocky Mount", phone="252-281-2536", email="",
        website="https://www.legalaidnc.org",
        eligibility="Low-income residents of eastern NC counties served by Rocky Mount office; LSC income limits apply.",
        eligibility_es="Residentes de bajos ingresos de condados del este de NC servidos por la oficina de Rocky Mount; aplican límites LSC.",
        notes="Call 252-281-2536 for appointment; serves Nash, Edgecombe, Wilson, Wayne, Lenoir, and Greene counties.",
        notes_es="Llame al 252-281-2536 para cita; sirve Nash, Edgecombe, Wilson, Wayne, Lenoir y Greene.",
        hours="Monday–Friday business hours",
        tags="rocky-mount|nash|legal-aid|eastern-nc|expungement|reentry",
        services="Civil legal representation|Eviction defense|Benefits appeals|Record relief|Housing legal aid",
        county="Nash", served_counties="Edgecombe|Greene|Lenoir|Nash|Wayne|Wilson", coverage="multi",
        _source="https://www.legalaidnc.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Legal Aid of North Carolina — Asheville Senior Law Project",
        category="legal-aid", region="Asheville / Western NC",
        description="Legal Aid of North Carolina Asheville office houses the statewide Senior Law Project and serves low-income residents of western North Carolina counties with civil legal aid including housing, benefits, and consumer issues affecting returning citizens age 60 and older. The Senior Legal Helpline at 877-579-7562 assists older North Carolinians statewide with reentry-related civil matters.",
        description_es="La oficina de Asheville de Legal Aid of North Carolina alberga el Proyecto de Ley para Personas Mayores estatal y sirve a residentes de bajos ingresos del oeste de Carolina del Norte con asistencia legal civil incluyendo vivienda y beneficios. La Línea Legal para Personas Mayores al 877-579-7562 asiste a carolinenses mayores de 60 años.",
        address="20 Artful Way, Suite 210", city="Asheville", phone="877-579-7562", email="",
        website="https://www.legalaidnc.org/office/asheville/",
        eligibility="Low-income western NC residents; Senior Law Project serves North Carolinians age 60+ statewide.",
        eligibility_es="Residentes de bajos ingresos del oeste de NC; el Proyecto de Ley para Personas Mayores sirve carolinenses de 60+ años en todo el estado.",
        notes="Senior Legal Helpline 877-579-7562; general intake via 1-866-219-5262 or legalaidnc.org.",
        notes_es="Línea Legal para Personas Mayores 877-579-7562; admisión general vía 1-866-219-5262 o legalaidnc.org.",
        hours="Monday–Friday business hours",
        tags="asheville|buncombe|legal-aid|senior-law|western-nc|reentry",
        services="Senior legal helpline|Civil legal aid|Housing legal assistance|Benefits advocacy|Consumer law",
        county="Buncombe", served_counties="Buncombe|Henderson|Madison|McDowell|Mitchell|Transylvania|Yancey", coverage="multi",
        _source="https://www.legalaidnc.org/office/asheville/", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Southern Coalition for Social Justice — Clean Slate Project",
        category="legal-aid", region="Durham / Statewide",
        description="Southern Coalition for Social Justice Clean Slate Project provides legal education, policy advocacy, and direct assistance helping North Carolina residents including justice-involved individuals understand expungement eligibility under state law and navigate record-clearing processes. While not a general legal aid intake line, SCSJ resources and clinics support fair-chance employment and housing after release.",
        description_es="El Proyecto Clean Slate de Southern Coalition for Social Justice ofrece educación legal, defensa de políticas y asistencia directa ayudando a residentes de Carolina del Norte incluidas personas con antecedentes penales a entender elegibilidad de expungación y procesos de limpieza de registros.",
        address="1415 West Highway 54", city="Durham", phone="919-323-3380", email="",
        website="https://www.southerncoalition.org",
        eligibility="North Carolina residents seeking expungement information and record-clearing assistance; case acceptance varies.",
        eligibility_es="Residentes de Carolina del Norte que buscan información de expungación y asistencia de limpieza de registros; aceptación de casos varía.",
        notes="Visit southerncoalition.org for Clean Slate resources; for general civil aid call Legal Aid 1-866-219-5262.",
        notes_es="Visite southerncoalition.org para recursos Clean Slate; para asistencia civil general llame Legal Aid 1-866-219-5262.",
        hours="Office Monday–Friday business hours",
        tags="durham|statewide|legal-aid|expungement|clean-slate|reentry",
        services="Expungement education|Record-clearing assistance|Policy advocacy|Legal rights resources|Fair-chance support",
        county="Durham", served_counties="", coverage="statewide",
        _source="https://www.southerncoalition.org", _source_type="nonprofit", _confidence="high",
    )

    # --- employment (+3 needed) ---
    add(
        name="Goodwill Industries of Central NC — Triad Career Center",
        category="employment", region="Greensboro / Guilford County",
        description="Goodwill Industries of Central North Carolina Triad Career Center in Greensboro provides free career coaching, job search assistance, resume writing, skills training including HVAC and construction pathways, and fair-chance employment navigation for justice-involved adults in Guilford and surrounding Piedmont counties. Walk-in and virtual services connect participants to NCWorks and regional employers.",
        description_es="El Centro de Carrera Triad de Goodwill Industries del centro de Carolina del Norte en Greensboro ofrece coaching de carrera gratuito, asistencia de búsqueda de empleo, redacción de currículums, capacitación en HVAC y construcción, y navegación de empleo de segunda oportunidad para adultos con antecedentes penales en Guilford y condados circundantes.",
        address="1235 South Eugene Street", city="Greensboro", phone="336-544-5305", email="",
        website="https://www.triadgoodwill.org/train/career-center/",
        eligibility="Open to job seekers in Triad Goodwill service area including justice-involved adults; core services free.",
        eligibility_es="Abierto a buscadores de empleo en el área de servicio de Triad Goodwill incluidos adultos con antecedentes penales; servicios básicos gratuitos.",
        notes="Walk-in Monday–Friday 9 a.m.–3 p.m.; call 336-544-5305 or email careerservices@triadgoodwill.org.",
        notes_es="Sin cita lunes–viernes 9 a.m.–3 p.m.; llame al 336-544-5305 o envíe correo a careerservices@triadgoodwill.org.",
        hours="Monday–Friday 9:00 a.m.–3:00 p.m.",
        tags="greensboro|guilford|employment|goodwill|fair-chance|reentry",
        services="Career coaching|Job search assistance|Resume writing|Skills training|Fair-chance employment|NCWorks referrals",
        county="Guilford", served_counties="Guilford|Randolph|Rockingham|Alamance|Davidson", coverage="multi",
        _source="https://www.triadgoodwill.org/train/career-center/", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Goodwill Industries of the Southern Piedmont — Workforce Development",
        category="employment", region="Charlotte / Mecklenburg County",
        description="Goodwill Industries of the Southern Piedmont operates workforce development centers in Charlotte connecting justice-involved job seekers to career coaching, skills training, NCWorks referrals, and fair-chance employer partnerships across Mecklenburg and surrounding counties. Programs include digital skills, hospitality training, and reentry-focused employment navigation at the Freedom Drive campus.",
        description_es="Goodwill Industries del Piedmont Sur opera centros de desarrollo laboral en Charlotte conectando buscadores de empleo con antecedentes penales con coaching de carrera, capacitación, referencias NCWorks y alianzas de empleo de segunda oportunidad en Mecklenburg y condados circundantes.",
        address="5301 Wilkinson Boulevard", city="Charlotte", phone="704-372-3434", email="",
        website="https://www.goodwillsp.org/workforce-development/",
        eligibility="Job seekers in Goodwill Southern Piedmont service area including justice-involved adults; free core services.",
        eligibility_es="Buscadores de empleo en el área de servicio de Goodwill Southern Piedmont incluidos adultos con antecedentes penales; servicios básicos gratuitos.",
        notes="Call 704-372-3434 for career center hours; multiple Charlotte-area locations at goodwillsp.org.",
        notes_es="Llame al 704-372-3434 para horarios del centro de carrera; múltiples ubicaciones en goodwillsp.org.",
        hours="Career center hours vary; call for schedule",
        tags="charlotte|mecklenburg|employment|goodwill|fair-chance|reentry",
        services="Career coaching|Skills training|NCWorks referrals|Fair-chance employers|Digital skills|Hospitality training",
        county="Mecklenburg", served_counties="Mecklenburg|Union|Cabarrus|Gaston|Lincoln", coverage="multi",
        _source="https://www.goodwillsp.org/workforce-development/", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="NCWorks Career Center — Forsyth County",
        category="employment", region="Winston-Salem / Forsyth County",
        description="NCWorks Career Center Forsyth County at the Goodwill Workforce Development Center connects job seekers including justice-involved adults to WIOA-funded training, career coaching, unemployment services, and fair-chance employment navigation in Winston-Salem and surrounding Piedmont counties. Staff coordinate with Forsyth Reentry Council, TROSA, and regional employers for returning citizens.",
        description_es="NCWorks Career Center del condado Forsyth en el Centro de Desarrollo Laboral Goodwill conecta buscadores de empleo incluidos adultos con antecedentes penales con capacitación WIOA, coaching de carrera, servicios de desempleo y navegación de empleo de segunda oportunidad en Winston-Salem.",
        address="2701 University Parkway", city="Winston-Salem", phone="336-464-0520", email="",
        website="https://www.ncworks.gov",
        eligibility="Open to Forsyth County job seekers including justice-involved individuals; core career center services free.",
        eligibility_es="Abierto a buscadores de empleo del condado Forsyth incluidas personas con antecedentes penales; servicios básicos gratuitos.",
        notes="Register at ncworks.gov; call 336-464-0520; partners with Forsyth LRC and TROSA Winston-Salem.",
        notes_es="Regístrese en ncworks.gov; llame al 336-464-0520; aliados con LRC de Forsyth y TROSA Winston-Salem.",
        hours="Monday–Friday business hours",
        tags="winston-salem|forsyth|employment|NCWorks|WIOA|reentry",
        services="WIOA training|Career coaching|Job search|Unemployment services|Fair-chance employment",
        county="Forsyth", served_counties="Forsyth|Stokes|Surry|Yadkin", coverage="multi",
        _source="https://www.ncworks.gov", _source_type="government", _confidence="high",
    )

    # --- veterans (+2 needed) ---
    add(
        name="Durham VA Medical Center — Veterans Justice Outreach",
        category="veterans", region="Durham / Triangle",
        description="Durham VA Medical Center Veterans Justice Outreach specialists connect justice-involved veterans in the Triangle and Sandhills to VA health care, benefits, housing, and treatment court supports after release from incarceration. VJO staff coordinate with NC Department of Military and Veterans Affairs county offices and local courts on veteran reentry plans. VA enrollment required for medical services.",
        description_es="Los especialistas de Veterans Justice Outreach del Centro Médico VA de Durham conectan a veteranos con antecedentes penales en el Triángulo y Sandhills con atención médica del VA, beneficios, vivienda y apoyos de tribunales de tratamiento después de la liberación. El personal VJO coordina con oficinas del condado NCDMVA.",
        address="508 Fulton Street", city="Durham", phone="919-452-6612", email="",
        website="https://www.va.gov/durham-health-care/",
        eligibility="Justice-involved veterans with qualifying military service; VA eligibility determination required.",
        eligibility_es="Veteranos con antecedentes penales con servicio militar calificado; se requiere determinación de elegibilidad del VA.",
        notes="Contact VJO at 919-452-6612; main VA line 919-286-0411; also call county veterans service office.",
        notes_es="Contacte VJO al 919-452-6612; línea principal VA 919-286-0411; también llame a la oficina de veteranos del condado.",
        hours="VA business hours; call for VJO appointment",
        tags="durham|veterans|VJO|reentry|justice-involved-veterans|triangle",
        services="Veterans Justice Outreach|VA health care enrollment|Benefits navigation|Treatment court coordination|Housing referrals",
        county="Durham", served_counties="Durham|Wake|Orange|Chatham|Lee|Harnett|Johnston", coverage="multi",
        _source="https://www.va.gov/durham-health-care/", _source_type="government", _confidence="high",
    )
    add(
        name="Salisbury VA Health Care System — Veterans Justice Outreach",
        category="veterans", region="Charlotte / Piedmont",
        description="Salisbury VA Health Care System Veterans Justice Outreach serves justice-involved veterans in the Charlotte metro and Piedmont region including those released from Mecklenburg County Jail and state custody. VJO specialists at the Charlotte Health Care Center link veterans to VA mental health, substance use treatment, and housing resources through the W.G. Hefner VA Medical Center network.",
        description_es="Veterans Justice Outreach del Sistema de Salud VA de Salisbury sirve a veteranos con antecedentes penales en el metro de Charlotte y región Piedmont incluidos los liberados de la cárcel del condado Mecklenburg. Especialistas VJO vinculan a veteranos con salud mental del VA, tratamiento de uso de sustancias y recursos de vivienda.",
        address="8601 University East Drive", city="Charlotte", phone="704-638-9000", email="",
        website="https://www.va.gov/salisbury-health-care/",
        eligibility="Justice-involved veterans in Charlotte/Piedmont region with qualifying military service.",
        eligibility_es="Veteranos con antecedentes penales en la región Charlotte/Piedmont con servicio militar calificado.",
        notes="Charlotte HCC at 704-638-9000; VJO contact via Salisbury VA; coordinates with Mecklenburg County VSO.",
        notes_es="Charlotte HCC al 704-638-9000; contacto VJO vía VA Salisbury; coordina con VSO del condado Mecklenburg.",
        hours="VA business hours",
        tags="charlotte|mecklenburg|veterans|VJO|reentry|piedmont",
        services="Veterans Justice Outreach|VA mental health referrals|Substance use treatment|Housing navigation|Benefits enrollment",
        county="Mecklenburg", served_counties="Mecklenburg|Cabarrus|Union|Gaston|Iredell|Rowan|Stanly", coverage="multi",
        _source="https://www.va.gov/salisbury-health-care/", _source_type="government", _confidence="high",
    )

    # --- probation-parole (+2 needed) ---
    add(
        name="NCDAC Community Supervision — Buncombe Judicial District 28",
        category="probation-parole", region="Asheville / Buncombe County",
        description="NCDAC Judicial District 28 supervises probationers and parolees in Buncombe County from the Asheville Courthouse field office, coordinating compliance reporting and referrals to Homeward Bound, Blue Ridge Health, MAHEC, and western North Carolina reentry partners. Returning citizens report to assigned probation or parole officers—not a walk-in resource center for housing or emergency cash.",
        description_es="El Distrito Judicial 28 de NCDAC supervisa personas en libertad probatoria y condicional en el condado Buncombe desde la oficina de Asheville, coordinando reportes de cumplimiento y referencias a Homeward Bound, Blue Ridge Health y aliados de reinserción del oeste de NC.",
        address="60 Court Plaza, 13th Floor", city="Asheville", phone="828-641-7101", email="",
        website="https://www.dac.nc.gov/divisions-and-sections/community-supervision",
        eligibility="Individuals under NCDAC community supervision in Buncombe County; report to assigned officer.",
        eligibility_es="Personas bajo supervisión comunitaria de NCDAC en el condado Buncombe; reporte al oficial asignado.",
        notes="Buncombe district office at Courthouse; pairs with Homeward Bound and western NC reentry resources.",
        notes_es="Oficina del distrito Buncombe en el Palacio de Justicia; se vincula con Homeward Bound y recursos de reinserción del oeste.",
        hours="Monday–Friday business hours",
        tags="asheville|buncombe|probation-parole|NCDAC|reentry",
        services="Buncombe probation supervision|Parole reporting|Western NC reentry referrals|Treatment coordination|Compliance monitoring",
        county="Buncombe", served_counties="Buncombe", coverage="single",
        _source="https://www.dac.nc.gov/community-supervision-field-operations-division-and-district-contacts-0/open", _source_type="government", _confidence="high",
    )
    add(
        name="NCDAC Community Supervision — Henderson Judicial District 29",
        category="probation-parole", region="Hendersonville / Western NC",
        description="NCDAC Judicial District 29 supervises justice-involved adults in Henderson, Transylvania, Polk, Rutherford, and McDowell counties from the Hendersonville Spartanburg Highway office. Officers connect returning citizens to Blue Ridge Health, rural workforce partners, and western North Carolina treatment providers. Probation and parole officers assigned by case—not walk-in benefits intake.",
        description_es="El Distrito Judicial 29 de NCDAC supervisa adultos con antecedentes penales en los condados Henderson, Transylvania, Polk, Rutherford y McDowell desde la oficina de Hendersonville. Los oficiales conectan a quienes regresan con Blue Ridge Health y proveedores de tratamiento del oeste de NC.",
        address="1347 Spartanburg Highway, Suite 4", city="Hendersonville", phone="828-393-4402", email="",
        website="https://www.dac.nc.gov/divisions-and-sections/community-supervision",
        eligibility="Individuals under NCDAC community supervision in District 29 counties; report to assigned officer.",
        eligibility_es="Personas bajo supervisión comunitaria de NCDAC en condados del Distrito 29; reporte al oficial asignado.",
        notes="Covers Henderson, Transylvania, Polk, Rutherford, McDowell; western NC rural reentry partner referrals.",
        notes_es="Cubre Henderson, Transylvania, Polk, Rutherford, McDowell; referencias a aliados de reinserción rural del oeste.",
        hours="Monday–Friday business hours",
        tags="hendersonville|henderson|probation-parole|NCDAC|western-nc",
        services="Multi-county probation supervision|Parole reporting|Rural reentry referrals|Treatment coordination|Compliance monitoring",
        county="Henderson", served_counties="Henderson|Transylvania|Polk|Rutherford|McDowell", coverage="multi",
        _source="https://www.dac.nc.gov/community-supervision-field-operations-division-and-district-contacts-0/open", _source_type="government", _confidence="high",
    )

    # --- remaining single-deficit categories ---
    add(
        name="Freedom House Recovery Center — Chapel Hill",
        category="substance-use-treatment", region="Chapel Hill / Orange County",
        description="Freedom House Recovery Center provides outpatient and facility-based crisis substance use and mental health treatment for adults in Orange, Durham, and Chatham counties including justice-involved individuals referred from courts, probation, and local jails. The 16-bed facility-based crisis unit in Chapel Hill offers an alternative to hospital emergency rooms or incarceration for acute behavioral health needs.",
        description_es="Freedom House Recovery Center ofrece tratamiento ambulatorio y de crisis residencial para uso de sustancias y salud mental para adultos en Orange, Durham y Chatham incluidas personas referidas por tribunales, probatoria y cárceles locales. La unidad de crisis de 16 camas en Chapel Hill ofrece alternativa a salas de emergencia o encarcelación.",
        address="104 New Stateside Drive", city="Chapel Hill", phone="919-967-8844", email="",
        website="https://freedomhouserecovery.org",
        eligibility="Adults with substance use or mental health treatment needs; justice referrals accepted per program policy.",
        eligibility_es="Adultos con necesidades de tratamiento de uso de sustancias o salud mental; referencias de justicia aceptadas según política.",
        notes="Crisis unit 919-967-8844; mobile crisis 866-275-9552; outpatient 833-800-1505.",
        notes_es="Unidad de crisis 919-967-8844; crisis móvil 866-275-9552; ambulatorio 833-800-1505.",
        hours="Crisis services 24/7; outpatient business hours",
        tags="chapel-hill|orange|substance-use|mental-health|crisis|reentry",
        services="Outpatient SUD treatment|Facility-based crisis|Mobile crisis|Peer support|Court and probation referrals",
        county="Orange", served_counties="Orange|Durham|Chatham", coverage="multi",
        _source="https://freedomhouserecovery.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="MANNA FoodBank — Western North Carolina",
        category="food-nutrition", region="Asheville / Western NC",
        description="MANNA FoodBank distributes food through more than 200 partner agencies across 16 western North Carolina counties and the Qualla Boundary, operating a Food Helpline for pantry locator assistance and SNAP application help for low-income residents including returning citizens. Community markets and MANNA Packs for Kids supplement direct food access in rural mountain counties.",
        description_es="MANNA FoodBank distribuye alimentos a través de más de 200 agencias aliadas en 16 condados del oeste de Carolina del Norte y la Frontera Qualla, operando una Línea de Alimentos para localizar despensas y ayuda con solicitudes SNAP para residentes de bajos ingresos incluidos ciudadanos que regresan.",
        address="99 Broadpointe Drive", city="Mills River", phone="828-299-3663", email="",
        website="https://mannafoodbank.org",
        eligibility="Open to western NC residents needing food assistance; SNAP help available through Food Helpline.",
        eligibility_es="Abierto a residentes del oeste de NC que necesitan asistencia alimentaria; ayuda SNAP disponible a través de la Línea de Alimentos.",
        notes="Food Helpline 828-290-9749 or 800-820-1109; food finder at mannafoodbank.org/find-food.",
        notes_es="Línea de Alimentos 828-290-9749 o 800-820-1109; buscador en mannafoodbank.org/find-food.",
        hours="Office Monday–Friday 8:00 a.m.–4:00 p.m.; helpline Monday–Friday 9:00 a.m.–4:00 p.m.",
        tags="asheville|western-nc|food-nutrition|food-bank|SNAP|reentry",
        services="Food bank distribution|Pantry network|SNAP application help|Food Helpline|Community markets",
        county="Buncombe", served_counties="Buncombe|Henderson|Haywood|Jackson|Macon|Madison|Mitchell|Polk|Rutherford|Transylvania|Yancey|McDowell|Cherokee|Clay|Graham|Swain", coverage="multi",
        _source="https://mannafoodbank.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="NC Peer Warmline — Promise Resource Network",
        category="peer-support", region="Statewide",
        description="The NC Peer Warmline at 1-855-PEERS-NC is a free 24/7 service staffed by Certified Peer Support Specialists with lived experience in mental health and substance use recovery, including justice-involved North Carolinians navigating reentry challenges. Operated by Promise Resource Network, the warmline offers non-crisis support by phone, text, and chat—not a substitute for 988 emergency services.",
        description_es="La Línea de Apoyo entre Pares de NC al 1-855-PEERS-NC es un servicio gratuito 24/7 operado por Especialistas Certificados en Apoyo entre Pares con experiencia vivida en salud mental y recuperación de uso de sustancias, incluidos carolinenses con antecedentes penales. Ofrece apoyo no crisis por teléfono, texto y chat.",
        address="", city="Charlotte", phone="1-855-733-7762", email="",
        website="https://www.ncdhhs.gov/divisions/mental-health-developmental-disabilities-and-substance-use-services/crisis-services/peer-warmline",
        eligibility="Open to any North Carolina resident seeking non-crisis peer support; no eligibility restrictions.",
        eligibility_es="Abierto a cualquier residente de Carolina del Norte que busque apoyo entre pares no crisis; sin restricciones de elegibilidad.",
        notes="Call or text 1-855-733-7762; for crisis call or text 988; operated by Promise Resource Network.",
        notes_es="Llame o envíe texto al 1-855-733-7762; para crisis llame o envíe texto al 988; operado por Promise Resource Network.",
        hours="Available 24/7",
        tags="statewide|peer-support|warmline|recovery|mental-health|reentry",
        services="Peer recovery support|Non-crisis counseling|Resource navigation|Text and chat support|Recovery connections",
        county="Mecklenburg", served_counties="", coverage="statewide",
        _source="https://www.ncdhhs.gov/divisions/mental-health-developmental-disabilities-and-substance-use-services/crisis-services/peer-warmline", _source_type="government", _confidence="high",
    )
    add(
        name="GoTriangle ACCESS — Paratransit Service",
        category="transportation", region="Raleigh / Durham / Chapel Hill",
        description="GoTriangle ACCESS provides ADA paratransit and reduced-fare transportation for eligible riders with disabilities in the Triangle including justice-involved adults who qualify under Americans with Disabilities Act criteria, connecting residents to NCWorks appointments, healthcare, probation reporting, and reentry services across Wake, Durham, and Orange counties.",
        description_es="GoTriangle ACCESS ofrece paratransporte ADA y transporte con tarifa reducida para pasajeros elegibles con discapacidades en el Triángulo incluidos adultos con antecedentes penales que califiquen bajo criterios ADA, conectando residentes con citas NCWorks, salud, reportes de probatoria y servicios de reinserción.",
        address="1907 East Millbrook Road", city="Raleigh", phone="919-485-7433", email="",
        website="https://gotriangle.org/access",
        eligibility="Triangle residents with disabilities meeting ADA paratransit eligibility; application and certification required.",
        eligibility_es="Residentes del Triángulo con discapacidades que cumplan elegibilidad de paratransporte ADA; se requiere solicitud y certificación.",
        notes="Call 919-485-7433 to apply; serves Wake, Durham, Orange, and parts of Chatham and Johnston counties.",
        notes_es="Llame al 919-485-7433 para solicitar; sirve Wake, Durham, Orange y partes de Chatham y Johnston.",
        hours="Service hours vary; call for schedule",
        tags="raleigh|durham|triangle|transportation|paratransit|ADA|reentry",
        services="ADA paratransit|Reduced-fare transit|Medical appointment rides|Workforce transportation|Eligibility certification",
        county="Wake", served_counties="Wake|Durham|Orange|Chatham|Johnston", coverage="multi",
        _source="https://gotriangle.org/access", _source_type="government", _confidence="high",
    )
    add(
        name="Our Children's Place — Coastal Horizons Center",
        category="family-children", region="Statewide",
        description="Our Children's Place of Coastal Horizons Center is North Carolina's statewide advocacy and education program for children of incarcerated and returning parents, providing workshops, resource navigation, and community presentations across all 100 counties. Staff help caregivers and justice-involved parents understand the impact of parental incarceration and support family reunification planning.",
        description_es="Our Children's Place de Coastal Horizons Center es el programa estatal de defensa y educación de Carolina del Norte para niños de padres encarcelados y que regresan, ofreciendo talleres, navegación de recursos y presentaciones comunitarias en los 100 condados. El personal ayuda a cuidadores y padres con antecedentes penales con planificación de reunificación familiar.",
        address="PO Box 13073", city="Durham", phone="919-904-4286", email="",
        website="https://ourchildrensplace.com",
        eligibility="Caregivers, educators, and justice-involved parents seeking resources for children affected by parental incarceration.",
        eligibility_es="Cuidadores, educadores y padres con antecedentes penales que buscan recursos para niños afectados por encarcelamiento parental.",
        notes="Call 919-904-4286 or visit ourchildrensplace.com; statewide workshops available by request.",
        notes_es="Llame al 919-904-4286 o visite ourchildrensplace.com; talleres estatales disponibles bajo solicitud.",
        hours="Contact for program schedule",
        tags="statewide|family-children|incarcerated-parents|reunification|advocacy|reentry",
        services="Advocacy for children of incarcerated parents|Educational workshops|Resource navigation|Reunification support|Caregiver guidance",
        county="Durham", served_counties="", coverage="statewide",
        _source="https://ourchildrensplace.com", _source_type="nonprofit", _confidence="high",
    )
