"""Direct-service pins for NC counties that previously had only a DSS row."""


def register_thin_counties(add):
    """Two or more program-level rows per thin county (NCWorks + local provider)."""

    add(
        name="NCWorks Career Center — Anson County",
        category="employment",
        region="Wadesboro / Anson County",
        description="NCWorks Career Center Anson County at the Lockhart-Taylor Center in Wadesboro connects job seekers including justice-involved adults from Anson County Jail and NCDAC custody to WIOA-funded training, resume assistance, fair-chance employment navigation, and NCWorks online job matching. Staff link returning citizens to Atrium Health Anson, Anson Crisis Ministry, and regional reentry partners in the Charlotte metro Sandhills fringe. Free core career services—not emergency cash or housing placement.",
        description_es="NCWorks Career Center del condado Anson en el Lockhart-Taylor Center de Wadesboro conecta buscadores de empleo incluidos adultos con antecedentes penales de la cárcel del condado Anson y custodia NCDAC con capacitación WIOA, ayuda con currículum y navegación de empleo de segunda oportunidad. El personal vincula a quienes regresan con Atrium Health Anson y Anson Crisis Ministry. Servicios básicos de carrera gratuitos.",
        address="514 North Washington Street", city="Wadesboro", phone="704-272-5479", email="",
        website="https://www.ncworks.gov",
        eligibility="Open to Anson County job seekers including justice-involved individuals; core NCWorks services are free.",
        eligibility_es="Abierto a buscadores de empleo del condado Anson incluidas personas con antecedentes penales; servicios básicos de NCWorks son gratuitos.",
        notes="Register at ncworks.gov; email AnsonCounty@NCWorks.gov; hours Monday–Friday 8:00 a.m.–4:30 p.m. (closes noon second Friday monthly).",
        notes_es="Regístrese en ncworks.gov; correo AnsonCounty@NCWorks.gov; horario lunes a viernes 8:00 a.m.–4:30 p.m.",
        hours="Monday–Friday, 8:00 a.m.–4:30 p.m. ET",
        tags="wadesboro|anson|employment|NCWorks|WIOA|reentry|fair-chance",
        services="Job search assistance|Resume preparation|WIOA training referrals|Fair-chance employment|Career coaching",
        county="Anson", served_counties="Anson", coverage="single",
        _source="https://www.milvets.nc.gov/documents/files/nc-works-and-career-centers/open",
        _source_type="government", _confidence="high",
    )
    add(
        name="Atrium Health Anson",
        category="healthcare",
        region="Wadesboro / Anson County",
        description="Atrium Health Anson is a 15-bed hospital and medical home in Wadesboro providing 24/7 emergency care, primary care, behavioral health, pharmacy, and specialty referrals for Anson County residents including uninsured and Medicaid patients such as returning citizens. Carolinas Primary Care on-site coordinates chronic disease management and community health outreach including mobile primary care visits in rural Anson communities. A hospital—not a walk-in benefits office.",
        description_es="Atrium Health Anson es un hospital de 15 camas y hogar médico en Wadesboro que ofrece atención de emergencia 24/7, atención primaria, salud conductual y referencias de especialidad para residentes del condado Anson incluidos pacientes sin seguro y Medicaid como ciudadanos que regresan. Carolinas Primary Care en el sitio coordina manejo de enfermedades crónicas y alcance comunitario.",
        address="2301 U.S. Highway 74", city="Wadesboro", phone="704-994-4000", email="",
        website="https://atriumhealth.org/locations/detail/atrium-health-anson",
        eligibility="Open to Anson County residents; sliding-fee and Medicaid patients welcome including justice-involved adults establishing local medical care.",
        eligibility_es="Abierto a residentes del condado Anson; pacientes con tarifa móvil y Medicaid bienvenidos incluidos adultos con antecedentes penales.",
        notes="Call 704-994-4000 for appointments and emergency; mobile primary care unit serves rural Anson on scheduled days.",
        notes_es="Llame al 704-994-4000 para citas y emergencias; unidad móvil de atención primaria sirve Anson rural en días programados.",
        hours="Emergency 24/7; clinic hours vary by service",
        tags="wadesboro|anson|healthcare|hospital|primary-care|reentry",
        services="Emergency care|Primary care|Behavioral health|Pharmacy|Specialty referrals|Mobile primary care",
        county="Anson", served_counties="Anson", coverage="single",
        _source="https://atriumhealth.org/locations/detail/atrium-health-anson",
        _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Anson Crisis Ministry — Food Bank",
        category="food-nutrition",
        region="Wadesboro / Anson County",
        description="Anson Crisis Ministry operates a food bank in Wadesboro distributing groceries, produce, and nutrition support to low-income Anson County households including returning citizens reestablishing food security after incarceration. Registered clients may receive food up to twice monthly; mobile pantry events rotate among partner churches in Anson and eastern Union counties. Direct food assistance—not a statewide hotline.",
        description_es="Anson Crisis Ministry opera un banco de alimentos en Wadesboro distribuyendo comestibles y apoyo nutricional a hogares de bajos ingresos del condado Anson incluidos ciudadanos que regresan que reestablecen seguridad alimentaria. Clientes registrados pueden recibir alimentos hasta dos veces al mes; despensas móviles rotan entre iglesias aliadas.",
        address="117 North Rutherford Street", city="Wadesboro", phone="704-694-2445", email="",
        website="https://www.ansoncrisisministry.org",
        eligibility="Anson County residents meeting income guidelines or receiving EBT; registration with proof of income and household size required.",
        eligibility_es="Residentes del condado Anson que cumplan lineamientos de ingresos o reciban EBT; registro con prueba de ingresos y tamaño del hogar requerido.",
        notes="Food distribution Tuesday–Friday 8:00 a.m.–1:00 p.m.; call 704-694-2445 before first visit to register.",
        notes_es="Distribución de alimentos martes a viernes 8:00 a.m.–1:00 p.m.; llame al 704-694-2445 antes de la primera visita para registrarse.",
        hours="Tuesday–Friday, 8:00 a.m.–1:00 p.m.",
        tags="wadesboro|anson|food-nutrition|food-bank|pantry|reentry",
        services="Emergency food boxes|Mobile food pantry|Nutrition support|Client registration|SNAP complement",
        county="Anson", served_counties="Anson", coverage="single",
        _source="https://www.ansoncrisisministry.org",
        _source_type="nonprofit", _confidence="high",
    )

    add(
        name="NCWorks Career Center — Craven County",
        category="employment",
        region="New Bern / Craven County",
        description="NCWorks Career Center Craven in New Bern provides free employment services for justice-involved adults in Craven, Jones, and Pamlico counties including resume coaching, veteran hiring support, career fairs, and WIOA training referrals through the Eastern Carolina Workforce Development Board. Staff coordinate with Craven Community College, Craven County Community Health Center, and Coastal Carolina reentry partners. A workforce center—not emergency housing intake.",
        description_es="NCWorks Career Center Craven en New Bern brinda servicios de empleo gratuitos para adultos con antecedentes penales en los condados Craven, Jones y Pamlico incluyendo coaching de currículum, apoyo a veteranos y referencias de capacitación WIOA. El personal coordina con Craven Community College y el Centro de Salud Comunitario del condado Craven.",
        address="2836 Neuse Boulevard", city="New Bern", phone="252-514-4828", email="",
        website="https://www.ncworks.gov",
        eligibility="Open to eastern NC job seekers including justice-involved individuals; veterans receive priority job listing access.",
        eligibility_es="Abierto a buscadores de empleo del este de NC incluidas personas con antecedentes penales; veteranos reciben acceso prioritario a listados.",
        notes="Register at ncworks.gov; email CravenCounty@ncworks.gov; co-located near Vocational Rehabilitation on Neuse Boulevard.",
        notes_es="Regístrese en ncworks.gov; correo CravenCounty@ncworks.gov; ubicado cerca de Rehabilitación Vocacional en Neuse Boulevard.",
        hours="Monday–Friday, 8:00 a.m.–4:30 p.m. ET",
        tags="new-bern|craven|employment|NCWorks|veterans|reentry|fair-chance",
        services="Resume assistance|Career planning|Veteran employment services|WIOA referrals|Job fairs",
        county="Craven", served_counties="Craven", coverage="single",
        _source="https://business.newbernchamber.com/members/member/ncworks-career-center-craven-6081",
        _source_type="government", _confidence="high",
    )
    add(
        name="Craven County Community Health Center",
        category="healthcare",
        region="New Bern / Craven County",
        description="Craven County Community Health Center operates Federally Qualified Health Center clinics in New Bern and Havelock providing primary care, chronic disease management, immunizations, and sliding-fee services for uninsured and Medicaid patients in Craven County including justice-involved adults establishing local medical homes after release. Same-day sick visits and care coordination with specialists support reentry health stability. FQHC—not a hospital emergency room for major trauma.",
        description_es="Craven County Community Health Center opera clínicas FQHC en New Bern y Havelock que ofrecen atención primaria, manejo de enfermedades crónicas e inmunizaciones con tarifa móvil para pacientes sin seguro y Medicaid en el condado Craven incluidos adultos con antecedentes penales. Visitas por enfermedad el mismo día y coordinación con especialistas apoyan estabilidad de salud en reinserción.",
        address="2818 Neuse Boulevard", city="New Bern", phone="252-636-4920", email="",
        website="https://www.cravencountync.gov/1816/Craven-County-Community-Health-Center",
        eligibility="Craven County residents of all ages; sliding scale with proof of income; Medicaid and Medicare accepted.",
        eligibility_es="Residentes del condado Craven de todas las edades; tarifa móvil con prueba de ingresos; acepta Medicaid y Medicare.",
        notes="New Bern 252-636-4920 option 2; Havelock 252-444-1533 option 2; payment expected at visit.",
        notes_es="New Bern 252-636-4920 opción 2; Havelock 252-444-1533 opción 2; pago esperado en la visita.",
        hours="Monday–Friday clinic hours; call for appointment",
        tags="new-bern|craven|healthcare|FQHC|primary-care|sliding-fee|reentry",
        services="Primary care|Chronic disease management|Immunizations|Sliding-fee care|Specialist coordination",
        county="Craven", served_counties="Craven", coverage="single",
        _source="https://www.cravencountync.gov/1816/Craven-County-Community-Health-Center",
        _source_type="government", _confidence="high",
    )

    add(
        name="NCWorks Career Center — Davie County",
        category="employment",
        region="Mocksville / Davie County",
        description="NCWorks Career Center Davie County on the Davidson-Davie Community College Mocksville campus connects job seekers including justice-involved adults to career coaching, on-the-job training referrals, resume workshops, and fair-chance employer partnerships across Davie and Davidson counties. Staff coordinate with adult education GED programs on-site and Piedmont Triad workforce partners. Free employment services—not a classroom for HiSET testing.",
        description_es="NCWorks Career Center del condado Davie en el campus de Davidson-Davie Community College en Mocksville conecta buscadores de empleo incluidos adultos con antecedentes penales con coaching de carrera, referencias de capacitación en el trabajo y talleres de currículum en los condados Davie y Davidson. Servicios de empleo gratuitos.",
        address="1205 Salisbury Road", city="Mocksville", phone="336-751-2885", email="",
        website="https://www.ncworks.gov",
        eligibility="Open to Davie County job seekers including justice-involved individuals; call for appointment if office unstaffed.",
        eligibility_es="Abierto a buscadores de empleo del condado Davie incluidas personas con antecedentes penales; llame para cita si la oficina no tiene personal.",
        notes="Room 115 Davie campus; extension 4859; email DavieCounty@NCWorks.gov; unemployment help 1-888-737-0259.",
        notes_es="Sala 115 campus Davie; extensión 4859; correo DavieCounty@NCWorks.gov.",
        hours="Monday, Tuesday, Thursday 8:00 a.m.–4:00 p.m. (verify before visit)",
        tags="mocksville|davie|employment|NCWorks|WIOA|reentry|fair-chance",
        services="Career coaching|On-the-job training referrals|Resume workshops|Job club|Fair-chance employment",
        county="Davie", served_counties="Davie", coverage="single",
        _source="https://www.daviecountync.gov/1140/NC-Works",
        _source_type="government", _confidence="high",
    )
    add(
        name="Davidson-Davie Community College — Adult Education (Davie)",
        category="education",
        region="Mocksville / Davie County",
        description="Davidson-Davie Community College Adult Education at the Mocksville campus provides free GED and HiSET preparation and Adult High School diploma pathways for Davie County adults including returning citizens rebuilding credentials for NCWorks employment and technical college enrollment. Day and evening classes meet on campus; orientation is required before enrollment. Instruction is free; official HSE test fees apply separately.",
        description_es="Davidson-Davie Community College Educación para Adultos en el campus de Mocksville ofrece preparación GED y HiSET gratuita y vías de diploma de secundaria para adultos del condado Davie incluidos ciudadanos que regresan que reconstruyen credenciales para empleo NCWorks. Se requiere orientación antes de inscripción; las clases son gratuitas.",
        address="1205 Salisbury Road", city="Mocksville", phone="336-751-2885", email="",
        website="https://www.davidsondavie.edu/academics/college-and-career-readiness/high-school-equivalency-program/",
        eligibility="Adults age 18+ in Davie County; ages 16–17 with minor admission form; justice-involved adults welcome.",
        eligibility_es="Adultos de 18 años o más en el condado Davie; 16–17 con formulario de admisión de menor; adultos con antecedentes penales bienvenidos.",
        notes="Attend orientation via davidsondavie.edu college and career readiness; classes in CLAS 201 Mocksville.",
        notes_es="Asista a orientación en davidsondavie.edu college and career readiness; clases en CLAS 201 Mocksville.",
        hours="Day and evening class schedules; call for orientation dates",
        tags="mocksville|davie|education|GED|HiSET|adult-education|reentry",
        services="GED preparation|HiSET preparation|Adult High School pathway|Orientation|Workforce referrals",
        county="Davie", served_counties="Davie", coverage="single",
        _source="https://www.davidsondavie.edu/continuing_education/high-school-equivalency-davie-county/",
        _source_type="government", _confidence="high",
    )

    add(
        name="NCWorks Career Center — Granville County",
        category="employment",
        region="Oxford / Granville County",
        description="NCWorks Career Center Granville County in Oxford connects job seekers including justice-involved adults in Granville, Vance, and Warren counties to WIOA training, business services, resume preparation, and fair-chance employment navigation through the Kerr-Tar Workforce Development Board. Staff link returning citizens to Vance-Granville Community College, local health centers, and Triangle-north reentry resources. Workforce services—not probation reporting.",
        description_es="NCWorks Career Center del condado Granville en Oxford conecta buscadores de empleo incluidos adultos con antecedentes penales en los condados Granville, Vance y Warren con capacitación WIOA, preparación de currículum y navegación de empleo de segunda oportunidad. Servicios de fuerza laboral, no reportes de libertad condicional.",
        address="111 Hilltop Village", city="Oxford", phone="919-693-2686", email="",
        website="https://www.ncworks.gov",
        eligibility="Open to Kerr-Tar region job seekers including individuals with criminal records; appointments recommended.",
        eligibility_es="Abierto a buscadores de empleo de la región Kerr-Tar incluidas personas con antecedentes penales; se recomiendan citas.",
        notes="Register at ncworks.gov; Thursday office closes at noon; email ncworks.6900@nccommerce.com.",
        notes_es="Regístrese en ncworks.gov; oficina cierra al mediodía los jueves.",
        hours="Monday–Wednesday and Friday 8:30 a.m.–5:00 p.m.; Thursday 8:30 a.m.–12:00 p.m.",
        tags="oxford|granville|employment|NCWorks|Kerr-Tar|reentry|fair-chance",
        services="WIOA training|Resume preparation|Employer recruitment support|Career pathways|Fair-chance navigation",
        county="Granville", served_counties="Granville", coverage="single",
        _source="https://members.granville-chamber.com/list/member/nc-works-career-center-granville-co-190",
        _source_type="government", _confidence="high",
    )
    add(
        name="Vance-Granville Community College — South Campus Adult Education",
        category="education",
        region="Creedmoor / Granville County",
        description="Vance-Granville Community College College and Career Readiness program at the South Campus in Creedmoor offers free GED, HiSET, and Adult High School preparation for Granville County adults including justice-involved residents seeking credentials for NCWorks Oxford and regional manufacturing jobs. Morning and evening classes support self-paced progress; orientation and placement testing are required before enrollment.",
        description_es="El programa College and Career Readiness de Vance-Granville Community College en el South Campus de Creedmoor ofrece preparación GED, HiSET y secundaria para adultos gratuita para residentes del condado Granville incluidos personas con antecedentes penales que buscan credenciales para NCWorks y empleos manufactureros regionales.",
        address="800 Vance-Granville Community College Road", city="Creedmoor", phone="252-738-3275", email="",
        website="https://www.vgcc.edu/ccr/",
        eligibility="Adults age 18+ in Granville County service area; minors 16–17 require information session; justice-involved adults accepted.",
        eligibility_es="Adultos de 18 años o más en el área de servicio del condado Granville; menores 16–17 requieren sesión informativa; adultos con antecedentes penales aceptados.",
        notes="Complete virtual orientation and registration at vgcc.edu/ccr; placement testing by appointment Wednesdays.",
        notes_es="Complete orientación virtual y registro en vgcc.edu/ccr; prueba de ubicación con cita los miércoles.",
        hours="Monday–Thursday day classes; Monday–Wednesday evening classes",
        tags="creedmoor|granville|education|GED|HiSET|VGCC|reentry",
        services="GED preparation|HiSET preparation|Adult High School|Placement testing|NCWorks referrals",
        county="Granville", served_counties="Granville", coverage="single",
        _source="https://www.vgcc.edu/vance-granville-community-college-offers-free-ged-and-ahs-face-to-face-classes/",
        _source_type="government", _confidence="high",
    )

    add(
        name="NCWorks Access Point — Pamlico County",
        category="employment",
        region="Grantsboro / Pamlico County",
        description="NCWorks Access Point Pamlico County at Pamlico Community College in Grantsboro connects eastern coastal job seekers including justice-involved adults to career coaching, job search tools, and referrals to NCWorks Craven and Eastern Carolina Workforce Development Board partners serving Pamlico, Craven, and Jones counties. Coordinated with PCC career services and Vocational Rehabilitation—not a DSS benefits desk.",
        description_es="NCWorks Access Point del condado Pamlico en Pamlico Community College en Grantsboro conecta buscadores de empleo costeros incluidos adultos con antecedentes penales con coaching de carrera y referencias a aliados NCWorks Craven y la Junta de Desarrollo Laboral del este de Carolina del Norte.",
        address="5049 Highway 306 South", city="Grantsboro", phone="252-249-1851", email="",
        website="https://www.ncworks.gov",
        eligibility="Open to Pamlico County job seekers; coordinate with PCC career services for appointment.",
        eligibility_es="Abierto a buscadores de empleo del condado Pamlico; coordine con servicios de carrera de PCC para cita.",
        notes="Room 409 Brinson Building; email ncworks.0400@nccommerce.com; partners with Pamlico CC career services ext. 3014.",
        notes_es="Sala 409 Edificio Brinson; aliados con servicios de carrera Pamlico CC ext. 3014.",
        hours="Monday–Friday business hours; call for current schedule",
        tags="grantsboro|pamlico|employment|NCWorks|coastal|reentry",
        services="Career coaching|Job search tools|Workforce board referrals|PCC career linkage|Vocational Rehabilitation coordination",
        county="Pamlico", served_counties="Pamlico", coverage="single",
        _source="https://ecwdb.org/location.php?Pamlico-County-NCWorks-Career-Resource-Center-8=",
        _source_type="government", _confidence="high",
    )
    add(
        name="CCHC Pamlico Medical Center",
        category="healthcare",
        region="Bayboro / Pamlico County",
        description="CCHC Pamlico Medical Center in Bayboro provides primary care and family medicine for Pamlico County residents including low-income and uninsured patients such as returning citizens from Pamlico County custody seeking a local medical home. The practice is part of Coastal Carolina Health Care multi-county physician network with referrals to New Bern specialists and sliding-fee options through affiliated programs. Outpatient clinic—not hospital emergency care.",
        description_es="CCHC Pamlico Medical Center en Bayboro ofrece atención primaria y medicina familiar para residentes del condado Pamlico incluidos pacientes de bajos ingresos y sin seguro como ciudadanos que regresan de custodia del condado Pamlico. Clínica ambulatoria, no emergencias hospitalarias.",
        address="606 Main Street", city="Bayboro", phone="252-745-3191", email="",
        website="https://www.cchchealthcare.com/portfolio-item/cchc-pamlico-medical-center/",
        eligibility="Pamlico County residents; new patients welcome including justice-involved adults; most insurance and Medicaid accepted.",
        eligibility_es="Residentes del condado Pamlico; nuevos pacientes bienvenidos incluidos adultos con antecedentes penales; acepta la mayoría de seguros y Medicaid.",
        notes="Call 252-745-3191 for appointments; CCHC new patient line 252-633-4111; Monday–Friday 8:30 a.m.–5:00 p.m.",
        notes_es="Llame al 252-745-3191 para citas; línea de nuevos pacientes CCHC 252-633-4111.",
        hours="Monday–Friday, 8:30 a.m.–5:00 p.m. ET",
        tags="bayboro|pamlico|healthcare|primary-care|CCHC|reentry",
        services="Primary care|Family medicine|Chronic care management|Specialist referrals|New patient intake",
        county="Pamlico", served_counties="Pamlico", coverage="single",
        _source="https://www.cchchealthcare.com/portfolio-item/cchc-pamlico-medical-center/",
        _source_type="nonprofit", _confidence="high",
    )

    add(
        name="NCWorks Career Center — Scotland County",
        category="employment",
        region="Laurinburg / Scotland County",
        description="NCWorks Career Center Scotland County on the Laurinburg bypass connects job seekers including justice-involved adults from Scotland County Jail and nearby correctional facilities to WIOA-funded training, career assessment, virtual workshops, and fair-chance employer partnerships in the Sandhills border region. Staff coordinate with Scotland Health Center, Richmond Community College, and regional reentry navigators. Free workforce services.",
        description_es="NCWorks Career Center del condado Scotland en Laurinburg conecta buscadores de empleo incluidos adultos con antecedentes penales de la cárcel del condado Scotland con capacitación WIOA, evaluación de carrera y alianzas de empleo de segunda oportunidad. Servicios de fuerza laboral gratuitos.",
        address="16800-A U.S. Highway 401 Bypass", city="Laurinburg", phone="910-405-5200", email="",
        website="https://www.ncworks.gov",
        eligibility="Open to Scotland County job seekers including justice-involved individuals; core services free.",
        eligibility_es="Abierto a buscadores de empleo del condado Scotland incluidas personas con antecedentes penales; servicios básicos gratuitos.",
        notes="Register at ncworks.gov; email ScotlandCounty@NCWorks.gov; computers and fax available on site.",
        notes_es="Regístrese en ncworks.gov; correo ScotlandCounty@NCWorks.gov; computadoras y fax disponibles.",
        hours="Monday–Friday business hours",
        tags="laurinburg|scotland|employment|NCWorks|WIOA|reentry|fair-chance",
        services="Career assessment|WIOA training|Virtual workshops|Job matching|Fair-chance employer partnerships",
        county="Scotland", served_counties="Scotland", coverage="single",
        _source="https://nccareers.org/ncworks-career-centers",
        _source_type="government", _confidence="high",
    )
    add(
        name="Scotland Health Center — Robeson Health Care Corporation",
        category="healthcare",
        region="Laurinburg / Scotland County",
        description="Scotland Health Center is a Federally Qualified Health Center in Laurinburg operated by Robeson Health Care Corporation, providing primary care, behavioral health, and sliding-fee services for uninsured and Medicaid patients in Scotland County including justice-involved adults establishing medical homes after release. Patient-centered medical home model with same-week appointment access for enrolled patients. FQHC clinic—not Scotland Memorial Hospital emergency department.",
        description_es="Scotland Health Center es un FQHC en Laurinburg operado por Robeson Health Care Corporation que ofrece atención primaria, salud conductual y tarifa móvil para pacientes sin seguro y Medicaid en el condado Scotland incluidos adultos con antecedentes penales. Modelo de hogar médico centrado en el paciente.",
        address="507 Lauchwood Drive", city="Laurinburg", phone="910-506-4682", email="",
        website="https://www.rhcchealth.org/scotlandmedical",
        eligibility="Scotland County residents; sliding fee based on income; Medicaid and Medicare accepted.",
        eligibility_es="Residentes del condado Scotland; tarifa móvil según ingresos; acepta Medicaid y Medicare.",
        notes="Call 910-506-4682 for appointments; after-hours nurse line same number; closed lunch Monday–Thursday noon–1 p.m.",
        notes_es="Llame al 910-506-4682 para citas; línea de enfermería fuera de horario mismo número.",
        hours="Monday 8:00 a.m.–7:00 p.m.; Tuesday–Thursday 8:00 a.m.–5:00 p.m.; Friday 8:00 a.m.–2:00 p.m.",
        tags="laurinburg|scotland|healthcare|FQHC|sliding-fee|reentry",
        services="Primary care|Behavioral health|Sliding-fee care|Medicaid services|Patient-centered medical home",
        county="Scotland", served_counties="Scotland", coverage="single",
        _source="https://www.rhcchealth.org/scotlandmedical",
        _source_type="nonprofit", _confidence="high",
    )

    add(
        name="NCWorks Career Center — Vance County",
        category="employment",
        region="Henderson / Vance County",
        description="NCWorks Career Center Vance County in Henderson provides comprehensive workforce services for justice-involved adults in Vance, Granville, and Warren counties including UI filing assistance, career fairs, on-site workshops, and WIOA referrals through the Kerr-Tar Workforce Development Board. Staff connect returning citizens to Vance-Granville Community College, Maria Parham Health, and Henderson reentry partners. American Job Center—not emergency shelter.",
        description_es="NCWorks Career Center del condado Vance en Henderson brinda servicios integrales de fuerza laboral para adultos con antecedentes penales en los condados Vance, Granville y Warren incluyendo asistencia de desempleo, ferias de empleo y referencias WIOA. Centro de Empleo Americano, no refugio de emergencia.",
        address="826 South Garnett Street", city="Henderson", phone="252-598-5200", email="",
        website="https://www.ncworks.gov",
        eligibility="Open to Kerr-Tar job seekers including individuals with criminal records; re-entry services available.",
        eligibility_es="Abierto a buscadores de empleo Kerr-Tar incluidas personas con antecedentes penales; servicios de reinserción disponibles.",
        notes="Email VanceCounty@NCWorks.gov; UI online and staff assistance; Thursday closes at noon.",
        notes_es="Correo VanceCounty@NCWorks.gov; desempleo en línea y asistencia del personal; jueves cierra al mediodía.",
        hours="Monday–Wednesday and Friday 8:30 a.m.–5:00 p.m.; Thursday 8:30 a.m.–12:00 p.m.",
        tags="henderson|vance|employment|NCWorks|re-entry|fair-chance|reentry",
        services="WIOA training|UI filing assistance|Career fairs|Workshops|Re-entry employment navigation",
        county="Vance", served_counties="Vance", coverage="single",
        _source="https://www.kerrtarcog.org/workforce-development/kerr-tar-ncworks-career-centers-access-points",
        _source_type="government", _confidence="high",
    )
    add(
        name="Vance-Granville Community College — Main Campus Adult Education",
        category="education",
        region="Henderson / Vance County",
        description="Vance-Granville Community College College and Career Readiness at the Main Campus in Henderson provides free GED, HiSET, and Adult High School instruction for Vance County adults including returning citizens preparing for NCWorks employment and skilled trades programs. Self-paced HSE classes and placement testing support learners with limited prior schooling; orientation video and registration required before classes begin.",
        description_es="College and Career Readiness de Vance-Granville Community College en el campus principal de Henderson ofrece instrucción GED, HiSET y secundaria para adultos gratuita para residentes del condado Vance incluidos ciudadanos que regresan que se preparan para empleo NCWorks y programas de oficios calificados.",
        address="1585 U.S. Highway 158 Bypass", city="Henderson", phone="252-738-3275", email="",
        website="https://www.vgcc.edu/ccr/high-school-equivalency-hse/",
        eligibility="Adults 18+ in Vance County; ages 16–17 with minor admission process; criminal record not a barrier.",
        eligibility_es="Adultos de 18 años o más en el condado Vance; 16–17 con proceso de admisión de menor; antecedentes penales no son barrera.",
        notes="Start at vgcc.edu/ccr virtual orientation; placement testing Wednesdays 8:30 a.m. by appointment; room 7212.",
        notes_es="Comience en orientación virtual vgcc.edu/ccr; prueba de ubicación miércoles 8:30 a.m. con cita.",
        hours="Monday–Thursday 8:30 a.m.–1:30 p.m. classes; evening ESL schedules vary",
        tags="henderson|vance|education|GED|HiSET|VGCC|reentry",
        services="GED preparation|HiSET preparation|Adult High School|Placement testing|ESL classes",
        county="Vance", served_counties="Vance", coverage="single",
        _source="https://www.vgcc.edu/ccr/high-school-equivalency-hse/",
        _source_type="government", _confidence="high",
    )

    add(
        name="NCWorks Career Center — Warren County",
        category="employment",
        region="Warrenton / Warren County",
        description="NCWorks Career Center Warren County at the Vance-Granville Community College Warrenton campus connects rural northern Piedmont job seekers including justice-involved adults to Kerr-Tar Workforce Development Board services, resume help, and WIOA training referrals serving Warren, Vance, and Granville counties. Warren County government accepts job applications at this access point on Wednesdays. Employment services—not county DSS intake.",
        description_es="NCWorks Career Center del condado Warren en el campus VGCC de Warrenton conecta buscadores de empleo del Piedmont norte incluidos adultos con antecedentes penales con servicios de la Junta Kerr-Tar, ayuda con currículum y referencias WIOA sirviendo los condados Warren, Vance y Granville.",
        address="210 West Ridgeway Street", city="Warrenton", phone="252-257-3230", email="",
        website="https://www.ncworks.gov",
        eligibility="Open to Warren County job seekers including justice-involved individuals; Wednesday hours for county job application drop-off.",
        eligibility_es="Abierto a buscadores de empleo del condado Warren incluidas personas con antecedentes penales; horario de miércoles para entrega de solicitudes de empleo del condado.",
        notes="VGCC Building 1 Room 1106; email WarrenCounty@NCWorks.gov; Wednesday 8:30 a.m.–4:30 p.m. primary access day.",
        notes_es="VGCC Edificio 1 Sala 1106; correo WarrenCounty@NCWorks.gov; miércoles 8:30 a.m.–4:30 p.m.",
        hours="Monday–Tuesday 8:30 a.m.–5:00 p.m.; Wednesday 8:30 a.m.–4:30 p.m.",
        tags="warrenton|warren|employment|NCWorks|VGCC|reentry|fair-chance",
        services="Career coaching|WIOA referrals|Resume assistance|Kerr-Tar workforce services|Employer job postings",
        county="Warren", served_counties="Warren", coverage="single",
        _source="https://www.milvets.nc.gov/documents/files/nc-works-and-career-centers/open",
        _source_type="government", _confidence="high",
    )
    add(
        name="Vance-Granville Community College — Warren Campus Adult Education",
        category="education",
        region="Warrenton / Warren County",
        description="Vance-Granville Community College College and Career Readiness at the Warren Campus in Warrenton offers free GED and HiSET preparation for Warren County adults including justice-involved residents seeking high school credentials for NCWorks employment and regional skilled jobs. Day and evening ESL and HSE classes support rural learners; orientation and placement testing required through the CCR department in Henderson.",
        description_es="College and Career Readiness de VGCC en el campus Warren de Warrenton ofrece preparación GED e HiSET gratuita para adultos del condado Warren incluidos residentes con antecedentes penales que buscan credenciales de secundaria para empleo NCWorks y trabajos calificados regionales.",
        address="210 West Ridgeway Street", city="Warrenton", phone="252-738-3212", email="",
        website="https://www.vgcc.edu/ccr/",
        eligibility="Adults 18+ in Warren County; minors 16–17 require minor information session; open to justice-involved adults.",
        eligibility_es="Adultos de 18 años o más en el condado Warren; menores 16–17 requieren sesión informativa; abierto a adultos con antecedentes penales.",
        notes="Register at vgcc.edu/ccr; CCR department 252-738-3212; Monday–Thursday day classes and Monday/Wednesday evening ESL.",
        notes_es="Regístrese en vgcc.edu/ccr; departamento CCR 252-738-3212; clases diurnas lunes a jueves.",
        hours="Monday–Thursday 8:30 a.m.–1:30 p.m.; Monday and Wednesday evening ESL",
        tags="warrenton|warren|education|GED|HiSET|VGCC|reentry",
        services="GED preparation|HiSET preparation|ESL classes|Placement testing|NCWorks coordination",
        county="Warren", served_counties="Warren", coverage="single",
        _source="https://www.vgcc.edu/vance-granville-community-college-offers-free-ged-and-ahs-face-to-face-classes/",
        _source_type="government", _confidence="high",
    )

    add(
        name="NCWorks Career Center — Wilkes County",
        category="employment",
        region="North Wilkesboro / Wilkes County",
        description="NCWorks Career Center Wilkes County in North Wilkesboro connects foothills job seekers including justice-involved adults from Wilkes County Jail and state custody to WIOA training, career planning, job placement assistance, and fair-chance employer partnerships through the High Country Workforce Development Board. On-site computers and resume support serve rural mountain communities. Workforce center—not Goodwill retail store.",
        description_es="NCWorks Career Center del condado Wilkes en North Wilkesboro conecta buscadores de empleo de las montañas incluidos adultos con antecedentes penales de la cárcel del condado Wilkes con capacitación WIOA, planificación de carrera y asistencia de colocación laboral. Centro de fuerza laboral.",
        address="1320 West D Street, Suite 2", city="North Wilkesboro", phone="336-838-5164", email="",
        website="https://www.ncworks.gov",
        eligibility="Open to Wilkes County job seekers including justice-involved individuals; core services free.",
        eligibility_es="Abierto a buscadores de empleo del condado Wilkes incluidas personas con antecedentes penales; servicios básicos gratuitos.",
        notes="Register at ncworks.gov; email WilkesCounty@NCWorks.gov; lunch closure 12:00–1:00 p.m. Monday–Thursday.",
        notes_es="Regístrese en ncworks.gov; correo WilkesCounty@NCWorks.gov; cierre de almuerzo 12:00–1:00 p.m. lunes a jueves.",
        hours="Monday–Thursday 8:00 a.m.–5:00 p.m.; Friday 8:00 a.m.–12:00 p.m.",
        tags="north-wilkesboro|wilkes|employment|NCWorks|WIOA|reentry|fair-chance",
        services="Career planning|WIOA training|Job placement|Resume preparation|Employer recruitment support",
        county="Wilkes", served_counties="Wilkes", coverage="single",
        _source="https://highcountrywdb.com/job-seekers/locate-a-career-center/",
        _source_type="government", _confidence="high",
    )
    add(
        name="Wilkes Community College — Adult Education",
        category="education",
        region="Wilkesboro / Wilkes County",
        description="Wilkes Community College College and Career Readiness division provides free Adult High School and GED/HiSET preparation for Wilkes County adults including returning citizens rebuilding education credentials for NCWorks foothills jobs and technical programs. Classroom and online HSE options serve Wilkes, Ashe, and Alleghany learners with minimal face-to-face requirements for online track. Orientation required before enrollment.",
        description_es="La división College and Career Readiness de Wilkes Community College ofrece preparación gratuita de secundaria para adultos y GED/HiSET para adultos del condado Wilkes incluidos ciudadanos que regresan que reconstruyen credenciales educativas para empleos NCWorks y programas técnicos. Se requiere orientación antes de inscripción.",
        address="1328 South Collegiate Drive", city="Wilkesboro", phone="336-903-3230", email="",
        website="https://www.wilkescc.edu/programs/wdce/adult-education/high-school-credential/",
        eligibility="Adults 18+ in Wilkes County; ages 16–17 contact program director; justice-involved adults welcome.",
        eligibility_es="Adultos de 18 años o más en el condado Wilkes; 16–17 contacten al director del programa; adultos con antecedentes penales bienvenidos.",
        notes="Call 336-903-3230 for HSE and Adult High School registration; online HSE available with minimal campus visits.",
        notes_es="Llame al 336-903-3230 para registro HSE y secundaria para adultos; HSE en línea disponible con visitas mínimas al campus.",
        hours="Contact for class schedules",
        tags="wilkesboro|wilkes|education|GED|HiSET|adult-education|reentry",
        services="GED preparation|HiSET preparation|Adult High School diploma|Online HSE option|NCWorks referrals",
        county="Wilkes", served_counties="Wilkes", coverage="single",
        _source="https://www.wilkescc.edu/programs/wdce/adult-education/high-school-credential/",
        _source_type="government", _confidence="high",
    )
