"""North Carolina Pass 2 rural depth — verified direct-service rows for thin rural counties."""


def register_rural_depth(add):
    """Register verified resources with full EN+ES fields for counties with only DSS pins."""

    add(
        name="Second Harvest Food Bank of Southeast NC",
        category="food-nutrition",
        region="Fayetteville / Multi-County",
        description="Second Harvest Food Bank of Southeast North Carolina distributes food through partner agencies across Bladen, Cumberland, Duplin, Harnett, Hoke, Robeson, and Sampson counties, serving low-income residents including returning citizens in rural Sandhills and southeastern communities. The Fayetteville warehouse connects neighbors to pantries, mobile distributions, and SNAP enrollment partners. Regional food bank—not direct walk-in pantry.",
        description_es="Second Harvest Food Bank del sureste de Carolina del Norte distribuye alimentos a través de agencias aliadas en los condados Bladen, Cumberland, Duplin, Harnett, Hoke, Robeson y Sampson, sirviendo a residentes de bajos ingresos incluidos ciudadanos que regresan en comunidades rurales. El almacén de Fayetteville conecta a vecinos con despensas y distribuciones móviles.",
        address="406 Deep Creek Road", city="Fayetteville", phone="910-485-6923", email="",
        website="https://www.secondharvestnc.org",
        eligibility="Open to residents in seven-county service area needing food assistance through partner pantries.",
        eligibility_es="Abierto a residentes en el área de servicio de siete condados que necesitan asistencia alimentaria mediante despensas aliadas.",
        notes="Find partner pantries at secondharvestnc.org; serves Sandhills and southeastern NC counties.",
        notes_es="Encuentre despensas aliadas en secondharvestnc.org; sirve condados Sandhills y sureste de NC.",
        hours="Office Monday–Friday business hours",
        tags="fayetteville|cumberland|food-nutrition|food-bank|rural-depth|reentry",
        services="Food bank distribution|Partner pantry network|Mobile distributions|SNAP referral partners",
        county="Cumberland", served_counties="Bladen|Cumberland|Duplin|Harnett|Hoke|Robeson|Sampson", coverage="multi",
        _source="https://www.secondharvestnc.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Food Bank of the Albemarle — Northeastern NC",
        category="food-nutrition",
        region="Elizabeth City / Multi-County",
        description="Food Bank of the Albemarle serves northeastern North Carolina including Bertie, Camden, Chowan, Currituck, Dare, Gates, Hertford, Hyde, Martin, Northampton, Pasquotank, Perquimans, Tyrrell, and Washington counties through a network of partner food pantries and mobile distributions. Justice-involved adults in rural northeastern counties access emergency food through partner agencies listed on the food bank website.",
        description_es="Food Bank of the Albemarle sirve el noreste de Carolina del Norte incluyendo quince condados rurales a través de una red de despensas aliadas y distribuciones móviles. Adultos con antecedentes penales en condados del noreste acceden a alimentos de emergencia mediante agencias aliadas.",
        address="109 Tidewater Way", city="Elizabeth City", phone="252-335-4035", email="",
        website="https://www.afoodbank.org",
        eligibility="Residents in northeastern NC food bank service area; access through partner pantries.",
        eligibility_es="Residentes en el área de servicio del banco de alimentos del noreste de NC; acceso mediante despensas aliadas.",
        notes="Find pantries at afoodbank.org; covers 15 northeastern NC counties including Outer Banks region.",
        notes_es="Encuentre despensas en afoodbank.org; cubre 15 condados del noreste de NC incluyendo la región Outer Banks.",
        hours="Office Monday–Friday business hours",
        tags="elizabeth-city|pasquotank|food-nutrition|food-bank|rural-depth|reentry",
        services="Food bank distribution|Partner pantry network|Mobile food distributions|Rural county coverage",
        county="Pasquotank", served_counties="Bertie|Camden|Chowan|Currituck|Dare|Gates|Hertford|Hyde|Martin|Northampton|Pasquotank|Perquimans|Tyrrell|Washington", coverage="multi",
        _source="https://www.afoodbank.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="NCWorks Career Center — Asheville/Buncombe",
        category="employment",
        region="Asheville / Buncombe County",
        description="NCWorks Career Center Asheville connects job seekers in Buncombe and surrounding western North Carolina counties to WIOA-funded training, career coaching, and fair-chance employment navigation including justice-involved adults returning from Buncombe County Detention Center or state custody. Staff coordinate with Homeward Bound, Blue Ridge Health, and regional employers.",
        description_es="NCWorks Career Center Asheville conecta buscadores de empleo en Buncombe y condados del oeste de Carolina del Norte con capacitación WIOA, coaching de carrera y navegación de empleo de segunda oportunidad incluidos adultos con antecedentes penales que regresan de la cárcel del condado.",
        address="48 Grove Street", city="Asheville", phone="828-251-6200", email="",
        website="https://www.ncworks.gov",
        eligibility="Open to western NC job seekers including justice-involved individuals; core services free.",
        eligibility_es="Abierto a buscadores de empleo del oeste de NC incluidas personas con antecedentes penales; servicios básicos gratuitos.",
        notes="Register at ncworks.gov; call 828-251-6200; serves Buncombe and western NC workforce region.",
        notes_es="Regístrese en ncworks.gov; llame al 828-251-6200; sirve la región laboral de Buncombe y oeste de NC.",
        hours="Monday–Friday business hours",
        tags="asheville|buncombe|employment|NCWorks|WIOA|rural-depth|reentry",
        services="WIOA training|Career coaching|Job search|Fair-chance employment|Employer partnerships",
        county="Buncombe", served_counties="Buncombe|Madison|Yancey|Mitchell|Avery", coverage="multi",
        _source="https://www.ncworks.gov", _source_type="government", _confidence="high",
    )
    add(
        name="NCWorks Career Center — Greenville/Pitt",
        category="employment",
        region="Greenville / Pitt County",
        description="NCWorks Career Center Greenville serves Pitt, Greene, and Martin counties connecting job seekers including justice-involved adults to WIOA-funded career training, unemployment services, and fair-chance employer partnerships in eastern North Carolina. Staff link returning citizens to ECU Health Community Care, Pitt Community College adult education, and regional manufacturing employers.",
        description_es="NCWorks Career Center Greenville sirve los condados Pitt, Greene y Martin conectando buscadores de empleo incluidos adultos con antecedentes penales con capacitación WIOA, servicios de desempleo y alianzas de empleo de segunda oportunidad en el este de Carolina del Norte.",
        address="210 South Greene Street", city="Greenville", phone="252-493-7523", email="",
        website="https://www.ncworks.gov",
        eligibility="Open to eastern NC job seekers including justice-involved individuals; core services free.",
        eligibility_es="Abierto a buscadores de empleo del este de NC incluidas personas con antecedentes penales; servicios básicos gratuitos.",
        notes="Register at ncworks.gov; call 252-493-7523; partners with Pitt CC adult ed and ECU Health.",
        notes_es="Regístrese en ncworks.gov; llame al 252-493-7523; aliados con educación para adultos Pitt CC y ECU Health.",
        hours="Monday–Friday business hours",
        tags="greenville|pitt|employment|NCWorks|WIOA|rural-depth|reentry",
        services="WIOA training|Career coaching|Unemployment services|Fair-chance employment|Training referrals",
        county="Pitt", served_counties="Pitt|Greene|Martin|Edgecombe|Beaufort", coverage="multi",
        _source="https://www.ncworks.gov", _source_type="government", _confidence="high",
    )
    add(
        name="NCWorks Career Center — Fayetteville/Cumberland",
        category="employment",
        region="Fayetteville / Cumberland County",
        description="NCWorks Career Center Fayetteville connects job seekers in Cumberland, Hoke, and Robeson counties including justice-involved veterans and returning citizens from Fort Liberty area facilities to WIOA training, career coaching, and fair-chance employment navigation. Staff coordinate with Fayetteville-Cumberland Reentry Council and regional employers.",
        description_es="NCWorks Career Center Fayetteville conecta buscadores de empleo en los condados Cumberland, Hoke y Robeson incluidos veteranos y ciudadanos que regresan del área de Fort Liberty con capacitación WIOA, coaching de carrera y navegación de empleo de segunda oportunidad.",
        address="1000 Ramsey Street", city="Fayetteville", phone="910-486-1100", email="",
        website="https://www.ncworks.gov",
        eligibility="Open to Sandhills region job seekers including justice-involved adults; core services free.",
        eligibility_es="Abierto a buscadores de empleo de la región Sandhills incluidos adultos con antecedentes penales; servicios básicos gratuitos.",
        notes="Register at ncworks.gov; call 910-486-1100; Fayetteville-Cumberland Reentry Council partner.",
        notes_es="Regístrese en ncworks.gov; llame al 910-486-1100; aliado del Consejo de Reinserción Fayetteville-Cumberland.",
        hours="Monday–Friday business hours",
        tags="fayetteville|cumberland|employment|NCWorks|WIOA|rural-depth|reentry",
        services="WIOA training|Career coaching|Veteran employment|Fair-chance employment|Reentry partner linkages",
        county="Cumberland", served_counties="Cumberland|Hoke|Robeson|Harnett|Bladen", coverage="multi",
        _source="https://www.ncworks.gov", _source_type="government", _confidence="high",
    )
    add(
        name="NCWorks Career Center — Hickory/Catawba",
        category="employment",
        region="Hickory / Catawba County",
        description="NCWorks Career Center Hickory serves Catawba, Alexander, Burke, and Caldwell counties in the foothills region, connecting job seekers including justice-involved adults to WIOA-funded training, career coaching, and manufacturing employer partnerships. Returning citizens access fair-chance employment navigation and referrals to local FQHC and reentry resources.",
        description_es="NCWorks Career Center Hickory sirve los condados Catawba, Alexander, Burke y Caldwell en la región de foothills, conectando buscadores de empleo incluidos adultos con antecedentes penales con capacitación WIOA, coaching de carrera y alianzas con empleadores manufactureros.",
        address="828 Conover Boulevard West", city="Conover", phone="828-465-5479", email="",
        website="https://www.ncworks.gov",
        eligibility="Open to foothills region job seekers including justice-involved individuals; core services free.",
        eligibility_es="Abierto a buscadores de empleo de la región foothills incluidas personas con antecedentes penales; servicios básicos gratuitos.",
        notes="Register at ncworks.gov; call 828-465-5479; Conover location serves Catawba Valley counties.",
        notes_es="Regístrese en ncworks.gov; llame al 828-465-5479; ubicación Conover sirve condados del Valle Catawba.",
        hours="Monday–Friday business hours",
        tags="hickory|catawba|employment|NCWorks|WIOA|rural-depth|reentry",
        services="WIOA training|Career coaching|Manufacturing job placement|Fair-chance employment|Skills training",
        county="Catawba", served_counties="Catawba|Alexander|Burke|Caldwell|Lincoln", coverage="multi",
        _source="https://www.ncworks.gov", _source_type="government", _confidence="high",
    )
    add(
        name="Appalachian Regional Healthcare System — Community Care",
        category="healthcare",
        region="Boone / Watauga County",
        description="Appalachian Regional Healthcare System provides primary care and behavioral health services to residents of Watauga, Avery, and Ashe counties in the North Carolina high country including low-income and uninsured patients such as returning citizens. Sliding-fee and Medicaid services at Boone and Linville clinics connect patients to regional reentry and workforce partners.",
        description_es="Appalachian Regional Healthcare System ofrece atención primaria y salud conductual a residentes de Watauga, Avery y Ashe en las montañas del norte de Carolina del Norte incluidos pacientes de bajos ingresos y sin seguro como ciudadanos que regresan. Servicios con tarifa móvil y Medicaid conectan pacientes con aliados regionales.",
        address="336 Deerfield Road", city="Boone", phone="828-262-4100", email="",
        website="https://apprhs.org",
        eligibility="Residents in ARHS service area; uninsured and Medicaid patients welcome including justice-involved adults.",
        eligibility_es="Residentes en el área de servicio ARHS; pacientes sin seguro y Medicaid bienvenidos incluidos adultos con antecedentes penales.",
        notes="Call 828-262-4100 for appointments; Boone hospital and Linville clinic locations.",
        notes_es="Llame al 828-262-4100 para citas; hospital Boone y clínica Linville.",
        hours="Clinic Monday–Friday hours",
        tags="boone|watauga|healthcare|rural-depth|mountain|reentry",
        services="Primary care|Behavioral health|Sliding-fee care|Medicaid services|Regional referrals",
        county="Watauga", served_counties="Watauga|Avery|Ashe|Alleghany", coverage="multi",
        _source="https://apprhs.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Rutherford Health — FQHC Network",
        category="healthcare",
        region="Forest City / Rutherford County",
        description="Rutherford Health operates Federally Qualified Health Center clinics serving Rutherford, McDowell, and Polk counties in western North Carolina foothills, providing primary care, dental, and behavioral health on a sliding-fee scale for uninsured and Medicaid patients including justice-involved adults in rural communities.",
        description_es="Rutherford Health opera clínicas FQHC sirviendo los condados Rutherford, McDowell y Polk en las foothills del oeste de Carolina del Norte, ofreciendo atención primaria, dental y conductual con tarifa móvil para pacientes sin seguro y Medicaid incluidos adultos con antecedentes penales.",
        address="187 South Church Street", city="Forest City", phone="828-245-0620", email="",
        website="https://www.rutherfordhealth.org",
        eligibility="Uninsured and low-income residents in Rutherford Health service counties; sliding fee available.",
        eligibility_es="Residentes sin seguro y de bajos ingresos en condados de servicio Rutherford Health; tarifa móvil disponible.",
        notes="Call 828-245-0620 for appointments; Forest City and Spindale clinic locations.",
        notes_es="Llame al 828-245-0620 para citas; ubicaciones de clínicas Forest City y Spindale.",
        hours="Monday–Friday clinic hours",
        tags="forest-city|rutherford|healthcare|FQHC|rural-depth|reentry",
        services="Primary care|Dental care|Behavioral health|Sliding-fee care|Medicaid enrollment",
        county="Rutherford", served_counties="Rutherford|McDowell|Polk|Cleveland", coverage="multi",
        _source="https://www.rutherfordhealth.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="NCDAC Community Supervision — Pitt Judicial District 3B",
        category="probation-parole",
        region="Greenville / Pitt County",
        description="NCDAC Judicial District 3B supervises probationers and parolees in Pitt, Beaufort, and Martin counties from the Greenville field office, connecting returning citizens to eastern North Carolina reentry partners, ECU Health, NCWorks Greenville, and Legal Aid Rocky Mount extension office. Assigned officers handle reporting—not emergency housing intake.",
        description_es="El Distrito Judicial 3B de NCDAC supervisa personas en libertad probatoria y condicional en los condados Pitt, Beaufort y Martin desde la oficina de Greenville, conectando a quienes regresan con aliados de reinserción del este de NC, ECU Health y NCWorks Greenville.",
        address="215 South Evans Street", city="Greenville", phone="252-830-3300", email="",
        website="https://www.dac.nc.gov/divisions-and-sections/community-supervision",
        eligibility="Individuals under NCDAC community supervision in Pitt, Beaufort, or Martin counties.",
        eligibility_es="Personas bajo supervisión comunitaria de NCDAC en los condados Pitt, Beaufort o Martin.",
        notes="Eastern NC district office; pairs with Pitt CC adult ed and ECU Health Community Care.",
        notes_es="Oficina del distrito del este de NC; se vincula con educación para adultos Pitt CC y ECU Health.",
        hours="Monday–Friday business hours",
        tags="greenville|pitt|probation-parole|NCDAC|rural-depth|reentry",
        services="Pitt-area probation supervision|Parole reporting|Eastern NC reentry referrals|Treatment coordination",
        county="Pitt", served_counties="Pitt|Beaufort|Martin", coverage="multi",
        _source="https://www.dac.nc.gov/community-supervision-field-operations-division-and-district-contacts-0/open", _source_type="government", _confidence="high",
    )
    add(
        name="Sandhills Community College — Adult Education",
        category="education",
        region="Pinehurst / Moore County",
        description="Sandhills Community College Adult Education provides GED and HiSET preparation for adults in Moore, Hoke, Richmond, and Montgomery counties including returning citizens from the Sandhills region seeking credentials for NCWorks and Fort Liberty area employment. Free classes at the Pinehurst campus connect graduates to regional workforce partners.",
        description_es="Sandhills Community College Educación para Adultos ofrece preparación GED e HiSET para adultos en los condados Moore, Hoke, Richmond y Montgomery incluidos ciudadanos que regresan de la región Sandhills que buscan credenciales para NCWorks y empleo en el área de Fort Liberty.",
        address="3395 Airport Road", city="Pinehurst", phone="910-695-3777", email="",
        website="https://www.sandhills.edu/adult-education/",
        eligibility="Adults age 16+ in Sandhills CC service area; justice-involved adults accepted.",
        eligibility_es="Adultos de 16 años o más en el área de servicio de Sandhills CC; adultos con antecedentes penales aceptados.",
        notes="Call 910-695-3777 for enrollment; serves Sandhills and south-central NC counties.",
        notes_es="Llame al 910-695-3777 para inscripción; sirve condados Sandhills y centro-sur de NC.",
        hours="Contact for class schedule",
        tags="pinehurst|moore|education|GED|HiSET|rural-depth|reentry",
        services="GED preparation|HiSET preparation|Adult literacy|NCWorks referrals|Workforce transition",
        county="Moore", served_counties="Moore|Hoke|Richmond|Montgomery|Lee", coverage="multi",
        _source="https://www.sandhills.edu/adult-education/", _source_type="government", _confidence="high",
    )
