"""Category minimum fill for South Carolina reentry resources."""


def register_category_fill(add):
    """Add verified rows to meet category minimums not met by phase4/rural depth."""

    add(
        name="South Carolina Legal Services — Charleston Office",
        category="legal-aid", region="Charleston / Charleston County",
        description="The South Carolina Legal Services Charleston regional office provides free civil legal aid to low-income residents of its service counties including housing eviction defense, public benefits appeals, family law, and expungement assistance under South Carolina law. Justice-involved clients can apply for help with record relief and benefits denials—not criminal defense representation.",
        description_es="La oficina regional de South Carolina Legal Services en Charleston brinda asistencia legal civil gratuita a residentes de bajos ingresos de sus condados de servicio incluyendo defensa contra desalojo, apelaciones de beneficios públicos, derecho familiar y asistencia con expungación. Los clientes con antecedentes penales pueden solicitar ayuda con alivio de antecedentes.",
        address="3947 Whiting Avenue", city="Charleston", phone="843-763-8277", email="",
        website="https://sclegal.org",
        eligibility="Low-income residents of SCLS Charleston service counties with civil legal problems; LSC income limits apply.",
        eligibility_es="Residentes de bajos ingresos de los condados de servicio SCLS Charleston con problemas legales civiles; aplican límites de ingresos LSC.",
        notes="Call 843-763-8277 or statewide helpline 1-888-346-5592; apply online at sclegal.org.",
        notes_es="Llame al 843-763-8277 o línea estatal 1-888-346-5592; solicite en sclegal.org.",
        hours="Intake Monday–Friday business hours",
        tags="charleston|legal-aid|low-income|expungement|reentry",
        services="Civil legal representation|Expungement assistance|Housing legal aid|Benefits appeals|Family law assistance",
        county="Charleston", served_counties="Berkeley|Charleston|Dorchester|Beaufort|Colleton|Georgetown|Hampton|Jasper", coverage="multi",
        _source="https://sclegal.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="South Carolina Legal Services — Columbia Office",
        category="legal-aid", region="Columbia / Richland County",
        description="The South Carolina Legal Services Columbia regional office provides free civil legal aid to low-income residents of its service counties including housing eviction defense, public benefits appeals, family law, and expungement assistance under South Carolina law. Justice-involved clients can apply for help with record relief and benefits denials—not criminal defense representation.",
        description_es="La oficina regional de South Carolina Legal Services en Columbia brinda asistencia legal civil gratuita a residentes de bajos ingresos de sus condados de servicio incluyendo defensa contra desalojo, apelaciones de beneficios públicos, derecho familiar y asistencia con expungación. Los clientes con antecedentes penales pueden solicitar ayuda con alivio de antecedentes.",
        address="2109 Bull Street", city="Columbia", phone="803-744-9430", email="",
        website="https://sclegal.org",
        eligibility="Low-income residents of SCLS Columbia service counties with civil legal problems; LSC income limits apply.",
        eligibility_es="Residentes de bajos ingresos de los condados de servicio SCLS Columbia con problemas legales civiles; aplican límites de ingresos LSC.",
        notes="Call 803-744-9430 or statewide helpline 1-888-346-5592; apply online at sclegal.org.",
        notes_es="Llame al 803-744-9430 o línea estatal 1-888-346-5592; solicite en sclegal.org.",
        hours="Intake Monday–Friday business hours",
        tags="columbia|legal-aid|low-income|expungement|reentry",
        services="Civil legal representation|Expungement assistance|Housing legal aid|Benefits appeals|Family law assistance",
        county="Richland", served_counties="Richland|Lexington|Kershaw|Fairfield|Newberry|Calhoun|Orangeburg|Sumter", coverage="multi",
        _source="https://sclegal.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="South Carolina Legal Services — Florence Office",
        category="legal-aid", region="Florence / Florence County",
        description="The South Carolina Legal Services Florence regional office provides free civil legal aid to low-income residents of its service counties including housing eviction defense, public benefits appeals, family law, and expungement assistance under South Carolina law. Justice-involved clients can apply for help with record relief and benefits denials—not criminal defense representation.",
        description_es="La oficina regional de South Carolina Legal Services en Florence brinda asistencia legal civil gratuita a residentes de bajos ingresos de sus condados de servicio incluyendo defensa contra desalojo, apelaciones de beneficios públicos, derecho familiar y asistencia con expungación. Los clientes con antecedentes penales pueden solicitar ayuda con alivio de antecedentes.",
        address="204 W. Evans Street", city="Florence", phone="843-661-4622", email="",
        website="https://sclegal.org",
        eligibility="Low-income residents of SCLS Florence service counties with civil legal problems; LSC income limits apply.",
        eligibility_es="Residentes de bajos ingresos de los condados de servicio SCLS Florence con problemas legales civiles; aplican límites de ingresos LSC.",
        notes="Call 843-661-4622 or statewide helpline 1-888-346-5592; apply online at sclegal.org.",
        notes_es="Llame al 843-661-4622 o línea estatal 1-888-346-5592; solicite en sclegal.org.",
        hours="Intake Monday–Friday business hours",
        tags="florence|legal-aid|low-income|expungement|reentry",
        services="Civil legal representation|Expungement assistance|Housing legal aid|Benefits appeals|Family law assistance",
        county="Florence", served_counties="Florence|Darlington|Dillon|Marion|Marlboro|Chesterfield|Williamsburg|Horry", coverage="multi",
        _source="https://sclegal.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="South Carolina Legal Services — Greenville Office",
        category="legal-aid", region="Greenville / Greenville County",
        description="The South Carolina Legal Services Greenville regional office provides free civil legal aid to low-income residents of its service counties including housing eviction defense, public benefits appeals, family law, and expungement assistance under South Carolina law. Justice-involved clients can apply for help with record relief and benefits denials—not criminal defense representation.",
        description_es="La oficina regional de South Carolina Legal Services en Greenville brinda asistencia legal civil gratuita a residentes de bajos ingresos de sus condados de servicio incluyendo defensa contra desalojo, apelaciones de beneficios públicos, derecho familiar y asistencia con expungación. Los clientes con antecedentes penales pueden solicitar ayuda con alivio de antecedentes.",
        address="701 Easley Bridge Road, Suite 2004", city="Greenville", phone="864-679-3232", email="",
        website="https://sclegal.org",
        eligibility="Low-income residents of SCLS Greenville service counties with civil legal problems; LSC income limits apply.",
        eligibility_es="Residentes de bajos ingresos de los condados de servicio SCLS Greenville con problemas legales civiles; aplican límites de ingresos LSC.",
        notes="Call 864-679-3232 or statewide helpline 1-888-346-5592; apply online at sclegal.org.",
        notes_es="Llame al 864-679-3232 o línea estatal 1-888-346-5592; solicite en sclegal.org.",
        hours="Intake Monday–Friday business hours",
        tags="greenville|legal-aid|low-income|expungement|reentry",
        services="Civil legal representation|Expungement assistance|Housing legal aid|Benefits appeals|Family law assistance",
        county="Greenville", served_counties="Greenville|Spartanburg|Anderson|Pickens|Oconee|Laurens|Abbeville|Greenwood", coverage="multi",
        _source="https://sclegal.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="South Carolina Legal Services — Spartanburg Office",
        category="legal-aid", region="Spartanburg / Spartanburg County",
        description="The South Carolina Legal Services Spartanburg regional office provides free civil legal aid to low-income residents of its service counties including housing eviction defense, public benefits appeals, family law, and expungement assistance under South Carolina law. Justice-involved clients can apply for help with record relief and benefits denials—not criminal defense representation.",
        description_es="La oficina regional de South Carolina Legal Services en Spartanburg brinda asistencia legal civil gratuita a residentes de bajos ingresos de sus condados de servicio incluyendo defensa contra desalojo, apelaciones de beneficios públicos, derecho familiar y asistencia con expungación. Los clientes con antecedentes penales pueden solicitar ayuda con alivio de antecedentes.",
        address="148 E. Main Street", city="Spartanburg", phone="864-583-8588", email="",
        website="https://sclegal.org",
        eligibility="Low-income residents of SCLS Spartanburg service counties with civil legal problems; LSC income limits apply.",
        eligibility_es="Residentes de bajos ingresos de los condados de servicio SCLS Spartanburg con problemas legales civiles; aplican límites de ingresos LSC.",
        notes="Call 864-583-8588 or statewide helpline 1-888-346-5592; apply online at sclegal.org.",
        notes_es="Llame al 864-583-8588 o línea estatal 1-888-346-5592; solicite en sclegal.org.",
        hours="Intake Monday–Friday business hours",
        tags="spartanburg|legal-aid|low-income|expungement|reentry",
        services="Civil legal representation|Expungement assistance|Housing legal aid|Benefits appeals|Family law assistance",
        county="Spartanburg", served_counties="Spartanburg|Cherokee|Union|York|Lancaster|Chester", coverage="multi",
        _source="https://sclegal.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="SCDPPPS — Rock Hill Field Office",
        category="probation-parole", region="Rock Hill / York County",
        description="The SCDPPPS Rock Hill field office supervises probationers and parolees in York and surrounding counties, connecting justice-involved adults to local SC Works centers, treatment providers, and reentry organizations. Assigned agents handle compliance reporting and referrals—not emergency housing or SNAP intake.",
        description_es="La oficina de campo SCDPPPS de Rock Hill supervisa personas en libertad probatoria y condicional en York y condados circundantes, conectando adultos con antecedentes penales con centros SC Works locales y organizaciones de reinserción.",
        address="1170 York Highway", city="Rock Hill", phone="803-324-0460", email="",
        website="https://www.ppp.sc.gov",
        eligibility="Adults under SCDPPPS supervision in the Rock Hill district; report to assigned agent.",
        eligibility_es="Adultos bajo supervisión SCDPPPS en el distrito de Rock Hill; reporte al agente asignado.",
        notes="Field office for York, Lancaster, Chester counties; statewide info 803-734-3900.",
        notes_es="Oficina de campo para condados de la zona; información estatal 803-734-3900.",
        hours="Monday–Friday business hours",
        tags="rock-hill|probation-parole|SCDPPPS|reentry",
        services="Probation supervision|Parole reporting|Treatment referrals|Employment compliance|Reentry referrals",
        county="York", served_counties="York|Lancaster|Chester", coverage="multi",
        _source="https://www.ppp.sc.gov", _source_type="government", _confidence="high",
    )
    add(
        name="SCDPPPS — Aiken Field Office",
        category="probation-parole", region="Aiken / Aiken County",
        description="The SCDPPPS Aiken field office supervises probationers and parolees in Aiken and surrounding counties, connecting justice-involved adults to local SC Works centers, treatment providers, and reentry organizations. Assigned agents handle compliance reporting and referrals—not emergency housing or SNAP intake.",
        description_es="La oficina de campo SCDPPPS de Aiken supervisa personas en libertad probatoria y condicional en Aiken y condados circundantes, conectando adultos con antecedentes penales con centros SC Works locales y organizaciones de reinserción.",
        address="1555 Richland Avenue W", city="Aiken", phone="803-641-4141", email="",
        website="https://www.ppp.sc.gov",
        eligibility="Adults under SCDPPPS supervision in the Aiken district; report to assigned agent.",
        eligibility_es="Adultos bajo supervisión SCDPPPS en el distrito de Aiken; reporte al agente asignado.",
        notes="Field office for Aiken, Barnwell, Edgefield, Saluda, McCormick counties; statewide info 803-734-3900.",
        notes_es="Oficina de campo para condados de la zona; información estatal 803-734-3900.",
        hours="Monday–Friday business hours",
        tags="aiken|probation-parole|SCDPPPS|reentry",
        services="Probation supervision|Parole reporting|Treatment referrals|Employment compliance|Reentry referrals",
        county="Aiken", served_counties="Aiken|Barnwell|Edgefield|Saluda|McCormick", coverage="multi",
        _source="https://www.ppp.sc.gov", _source_type="government", _confidence="high",
    )
    add(
        name="SCDPPPS — Orangeburg Field Office",
        category="probation-parole", region="Orangeburg / Orangeburg County",
        description="The SCDPPPS Orangeburg field office supervises probationers and parolees in Orangeburg and surrounding counties, connecting justice-involved adults to local SC Works centers, treatment providers, and reentry organizations. Assigned agents handle compliance reporting and referrals—not emergency housing or SNAP intake.",
        description_es="La oficina de campo SCDPPPS de Orangeburg supervisa personas en libertad probatoria y condicional en Orangeburg y condados circundantes, conectando adultos con antecedentes penales con centros SC Works locales y organizaciones de reinserción.",
        address="1435 Amelia Street", city="Orangeburg", phone="803-533-6280", email="",
        website="https://www.ppp.sc.gov",
        eligibility="Adults under SCDPPPS supervision in the Orangeburg district; report to assigned agent.",
        eligibility_es="Adultos bajo supervisión SCDPPPS en el distrito de Orangeburg; reporte al agente asignado.",
        notes="Field office for Orangeburg, Calhoun, Bamberg, Allendale counties; statewide info 803-734-3900.",
        notes_es="Oficina de campo para condados de la zona; información estatal 803-734-3900.",
        hours="Monday–Friday business hours",
        tags="orangeburg|probation-parole|SCDPPPS|reentry",
        services="Probation supervision|Parole reporting|Treatment referrals|Employment compliance|Reentry referrals",
        county="Orangeburg", served_counties="Orangeburg|Calhoun|Bamberg|Allendale", coverage="multi",
        _source="https://www.ppp.sc.gov", _source_type="government", _confidence="high",
    )
    add(
        name="SCDPPPS — Sumter Field Office",
        category="probation-parole", region="Sumter / Sumter County",
        description="The SCDPPPS Sumter field office supervises probationers and parolees in Sumter and surrounding counties, connecting justice-involved adults to local SC Works centers, treatment providers, and reentry organizations. Assigned agents handle compliance reporting and referrals—not emergency housing or SNAP intake.",
        description_es="La oficina de campo SCDPPPS de Sumter supervisa personas en libertad probatoria y condicional en Sumter y condados circundantes, conectando adultos con antecedentes penales con centros SC Works locales y organizaciones de reinserción.",
        address="1295 N. Lafayette Drive", city="Sumter", phone="803-469-6030", email="",
        website="https://www.ppp.sc.gov",
        eligibility="Adults under SCDPPPS supervision in the Sumter district; report to assigned agent.",
        eligibility_es="Adultos bajo supervisión SCDPPPS en el distrito de Sumter; reporte al agente asignado.",
        notes="Field office for Sumter, Lee, Clarendon counties; statewide info 803-734-3900.",
        notes_es="Oficina de campo para condados de la zona; información estatal 803-734-3900.",
        hours="Monday–Friday business hours",
        tags="sumter|probation-parole|SCDPPPS|reentry",
        services="Probation supervision|Parole reporting|Treatment referrals|Employment compliance|Reentry referrals",
        county="Sumter", served_counties="Sumter|Lee|Clarendon", coverage="multi",
        _source="https://www.ppp.sc.gov", _source_type="government", _confidence="high",
    )
    add(
        name="SCDPPPS — Myrtle Beach Field Office",
        category="probation-parole", region="Myrtle Beach / Horry County",
        description="The SCDPPPS Myrtle Beach field office supervises probationers and parolees in Horry and surrounding counties, connecting justice-involved adults to local SC Works centers, treatment providers, and reentry organizations. Assigned agents handle compliance reporting and referrals—not emergency housing or SNAP intake.",
        description_es="La oficina de campo SCDPPPS de Myrtle Beach supervisa personas en libertad probatoria y condicional en Horry y condados circundantes, conectando adultos con antecedentes penales con centros SC Works locales y organizaciones de reinserción.",
        address="950 Crabtree Lane", city="Myrtle Beach", phone="843-915-5160", email="",
        website="https://www.ppp.sc.gov",
        eligibility="Adults under SCDPPPS supervision in the Myrtle Beach district; report to assigned agent.",
        eligibility_es="Adultos bajo supervisión SCDPPPS en el distrito de Myrtle Beach; reporte al agente asignado.",
        notes="Field office for Horry, Georgetown counties; statewide info 803-734-3900.",
        notes_es="Oficina de campo para condados de la zona; información estatal 803-734-3900.",
        hours="Monday–Friday business hours",
        tags="myrtle-beach|probation-parole|SCDPPPS|reentry",
        services="Probation supervision|Parole reporting|Treatment referrals|Employment compliance|Reentry referrals",
        county="Horry", served_counties="Horry|Georgetown", coverage="multi",
        _source="https://www.ppp.sc.gov", _source_type="government", _confidence="high",
    )
    add(
        name="Trident Literacy Association",
        category="education", region="North Charleston / Charleston County",
        description="Trident Literacy Association offers GED preparation, adult literacy, and workforce readiness classes for justice-involved adults rebuilding education credentials after incarceration in the North Charleston area. Free or low-cost instruction prepares students for high school equivalency testing and connects graduates to SC Works and local employers.",
        description_es="Trident Literacy Association ofrece preparación para el GED, alfabetización de adultos y clases de preparación laboral para adultos con antecedentes penales que reconstruyen credenciales educativas después de la encarcelación en el área de North Charleston.",
        address="6365 Rivers Avenue", city="North Charleston", phone="843-747-2223", email="",
        website="https://scworks.org",
        eligibility="Adults 17 and older without high school diploma; justice-involved students welcome.",
        eligibility_es="Adultos de 17 años o más sin diploma de secundaria; estudiantes con antecedentes penales bienvenidos.",
        notes="Call 843-747-2223 for enrollment; pairs with SC Works North Charleston and local reentry partners.",
        notes_es="Llame al 843-747-2223 para inscripción; se vincula con SC Works North Charleston y aliados locales de reinserción.",
        hours="Class schedules vary; call for enrollment",
        tags="north-charleston|education|GED|adult-education|reentry",
        services="GED preparation|Adult literacy|Workforce readiness|Testing referrals|Employer connections",
        county="Charleston", served_counties="Berkeley|Charleston|Dorchester", coverage="multi",
        _source="https://scworks.org", _source_type="government", _confidence="high",
    )
    add(
        name="Florence-Darlington Technical College Adult Education",
        category="education", region="Florence / Florence County",
        description="Florence-Darlington Technical College Adult Education offers GED preparation, adult literacy, and workforce readiness classes for justice-involved adults rebuilding education credentials after incarceration in the Florence area. Free or low-cost instruction prepares students for high school equivalency testing and connects graduates to SC Works and local employers.",
        description_es="Florence-Darlington Technical College Adult Education ofrece preparación para el GED, alfabetización de adultos y clases de preparación laboral para adultos con antecedentes penales que reconstruyen credenciales educativas después de la encarcelación en el área de Florence.",
        address="2715 W. Lucas Street", city="Florence", phone="843-661-8324", email="",
        website="https://scworks.org",
        eligibility="Adults 17 and older without high school diploma; justice-involved students welcome.",
        eligibility_es="Adultos de 17 años o más sin diploma de secundaria; estudiantes con antecedentes penales bienvenidos.",
        notes="Call 843-661-8324 for enrollment; pairs with SC Works Florence and local reentry partners.",
        notes_es="Llame al 843-661-8324 para inscripción; se vincula con SC Works Florence y aliados locales de reinserción.",
        hours="Class schedules vary; call for enrollment",
        tags="florence|education|GED|adult-education|reentry",
        services="GED preparation|Adult literacy|Workforce readiness|Testing referrals|Employer connections",
        county="Florence", served_counties="Florence|Darlington|Marion|Marlboro", coverage="multi",
        _source="https://scworks.org", _source_type="government", _confidence="high",
    )
    add(
        name="Spartanburg Community College Adult Education",
        category="education", region="Spartanburg / Spartanburg County",
        description="Spartanburg Community College Adult Education offers GED preparation, adult literacy, and workforce readiness classes for justice-involved adults rebuilding education credentials after incarceration in the Spartanburg area. Free or low-cost instruction prepares students for high school equivalency testing and connects graduates to SC Works and local employers.",
        description_es="Spartanburg Community College Adult Education ofrece preparación para el GED, alfabetización de adultos y clases de preparación laboral para adultos con antecedentes penales que reconstruyen credenciales educativas después de la encarcelación en el área de Spartanburg.",
        address="107 Community College Drive", city="Spartanburg", phone="864-592-4800", email="",
        website="https://scworks.org",
        eligibility="Adults 17 and older without high school diploma; justice-involved students welcome.",
        eligibility_es="Adultos de 17 años o más sin diploma de secundaria; estudiantes con antecedentes penales bienvenidos.",
        notes="Call 864-592-4800 for enrollment; pairs with SC Works Spartanburg and local reentry partners.",
        notes_es="Llame al 864-592-4800 para inscripción; se vincula con SC Works Spartanburg y aliados locales de reinserción.",
        hours="Class schedules vary; call for enrollment",
        tags="spartanburg|education|GED|adult-education|reentry",
        services="GED preparation|Adult literacy|Workforce readiness|Testing referrals|Employer connections",
        county="Spartanburg", served_counties="Spartanburg|Cherokee|Union", coverage="multi",
        _source="https://scworks.org", _source_type="government", _confidence="high",
    )
    add(
        name="York Technical College Adult Education",
        category="education", region="Rock Hill / York County",
        description="York Technical College Adult Education offers GED preparation, adult literacy, and workforce readiness classes for justice-involved adults rebuilding education credentials after incarceration in the Rock Hill area. Free or low-cost instruction prepares students for high school equivalency testing and connects graduates to SC Works and local employers.",
        description_es="York Technical College Adult Education ofrece preparación para el GED, alfabetización de adultos y clases de preparación laboral para adultos con antecedentes penales que reconstruyen credenciales educativas después de la encarcelación en el área de Rock Hill.",
        address="452 S. Anderson Road", city="Rock Hill", phone="803-327-8000", email="",
        website="https://scworks.org",
        eligibility="Adults 17 and older without high school diploma; justice-involved students welcome.",
        eligibility_es="Adultos de 17 años o más sin diploma de secundaria; estudiantes con antecedentes penales bienvenidos.",
        notes="Call 803-327-8000 for enrollment; pairs with SC Works Rock Hill and local reentry partners.",
        notes_es="Llame al 803-327-8000 para inscripción; se vincula con SC Works Rock Hill y aliados locales de reinserción.",
        hours="Class schedules vary; call for enrollment",
        tags="rock-hill|education|GED|adult-education|reentry",
        services="GED preparation|Adult literacy|Workforce readiness|Testing referrals|Employer connections",
        county="York", served_counties="York|Lancaster|Chester", coverage="multi",
        _source="https://scworks.org", _source_type="government", _confidence="high",
    )
    add(
        name="Greenville County Veterans Affairs Office",
        category="veterans", region="Greenville / Greenville County",
        description="The Greenville County Veterans Affairs Office provides free VA benefits claims assistance, discharge upgrade guidance, and referrals to veteran treatment courts and SC DVS programs for justice-involved veterans in Greenville County. County veterans service officers help returning veteran citizens navigate VA healthcare and disability compensation.",
        description_es="La Oficina de Asuntos de Veteranos del condado Greenville ofrece asistencia gratuita con reclamaciones de beneficios VA y referencias a tribunales de tratamiento para veteranos para veteranos con antecedentes penales en el condado Greenville.",
        address="301 University Ridge, Suite 102", city="Greenville", phone="864-467-7570", email="",
        website="https://scdva.sc.gov",
        eligibility="Veterans and eligible dependents in Greenville County; service documentation required.",
        eligibility_es="Veteranos y dependientes elegibles en el condado Greenville; se requiere documentación de servicio.",
        notes="Call 864-467-7570 for appointment; free claims assistance through SC DVS county network.",
        notes_es="Llame al 864-467-7570 para cita; asistencia gratuita con reclamaciones a través de la red del condado SC DVS.",
        hours="Monday–Friday business hours",
        tags="greenville|veterans|VA-benefits|reentry",
        services="VA benefits claims assistance|Disability claims navigation|Healthcare enrollment help|Veteran treatment court referrals",
        county="Greenville", served_counties="Greenville", coverage="single",
        _source="https://scdva.sc.gov", _source_type="government", _confidence="high",
    )
    add(
        name="Charleston County Veterans Affairs Office",
        category="veterans", region="Charleston / Charleston County",
        description="The Charleston County Veterans Affairs Office provides free VA benefits claims assistance, discharge upgrade guidance, and referrals to veteran treatment courts and SC DVS programs for justice-involved veterans in Charleston County. County veterans service officers help returning veteran citizens navigate VA healthcare and disability compensation.",
        description_es="La Oficina de Asuntos de Veteranos del condado Charleston ofrece asistencia gratuita con reclamaciones de beneficios VA y referencias a tribunales de tratamiento para veteranos para veteranos con antecedentes penales en el condado Charleston.",
        address="4045 Bridge View Drive", city="Charleston", phone="843-202-6464", email="",
        website="https://scdva.sc.gov",
        eligibility="Veterans and eligible dependents in Charleston County; service documentation required.",
        eligibility_es="Veteranos y dependientes elegibles en el condado Charleston; se requiere documentación de servicio.",
        notes="Call 843-202-6464 for appointment; free claims assistance through SC DVS county network.",
        notes_es="Llame al 843-202-6464 para cita; asistencia gratuita con reclamaciones a través de la red del condado SC DVS.",
        hours="Monday–Friday business hours",
        tags="charleston|veterans|VA-benefits|reentry",
        services="VA benefits claims assistance|Disability claims navigation|Healthcare enrollment help|Veteran treatment court referrals",
        county="Charleston", served_counties="Charleston", coverage="single",
        _source="https://scdva.sc.gov", _source_type="government", _confidence="high",
    )
    add(
        name="Florence County Veterans Affairs Office",
        category="veterans", region="Florence / Florence County",
        description="The Florence County Veterans Affairs Office provides free VA benefits claims assistance, discharge upgrade guidance, and referrals to veteran treatment courts and SC DVS programs for justice-involved veterans in Florence County. County veterans service officers help returning veteran citizens navigate VA healthcare and disability compensation.",
        description_es="La Oficina de Asuntos de Veteranos del condado Florence ofrece asistencia gratuita con reclamaciones de beneficios VA y referencias a tribunales de tratamiento para veteranos para veteranos con antecedentes penales en el condado Florence.",
        address="1450 W. Evans Street", city="Florence", phone="843-661-4766", email="",
        website="https://scdva.sc.gov",
        eligibility="Veterans and eligible dependents in Florence County; service documentation required.",
        eligibility_es="Veteranos y dependientes elegibles en el condado Florence; se requiere documentación de servicio.",
        notes="Call 843-661-4766 for appointment; free claims assistance through SC DVS county network.",
        notes_es="Llame al 843-661-4766 para cita; asistencia gratuita con reclamaciones a través de la red del condado SC DVS.",
        hours="Monday–Friday business hours",
        tags="florence|veterans|VA-benefits|reentry",
        services="VA benefits claims assistance|Disability claims navigation|Healthcare enrollment help|Veteran treatment court referrals",
        county="Florence", served_counties="Florence", coverage="single",
        _source="https://scdva.sc.gov", _source_type="government", _confidence="high",
    )
    add(
        name="York County Veterans Affairs Office",
        category="veterans", region="York / York County",
        description="The York County Veterans Affairs Office provides free VA benefits claims assistance, discharge upgrade guidance, and referrals to veteran treatment courts and SC DVS programs for justice-involved veterans in York County. County veterans service officers help returning veteran citizens navigate VA healthcare and disability compensation.",
        description_es="La Oficina de Asuntos de Veteranos del condado York ofrece asistencia gratuita con reclamaciones de beneficios VA y referencias a tribunales de tratamiento para veteranos para veteranos con antecedentes penales en el condado York.",
        address="1070 Heckle Boulevard", city="York", phone="803-909-7200", email="",
        website="https://scdva.sc.gov",
        eligibility="Veterans and eligible dependents in York County; service documentation required.",
        eligibility_es="Veteranos y dependientes elegibles en el condado York; se requiere documentación de servicio.",
        notes="Call 803-909-7200 for appointment; free claims assistance through SC DVS county network.",
        notes_es="Llame al 803-909-7200 para cita; asistencia gratuita con reclamaciones a través de la red del condado SC DVS.",
        hours="Monday–Friday business hours",
        tags="york|veterans|VA-benefits|reentry",
        services="VA benefits claims assistance|Disability claims navigation|Healthcare enrollment help|Veteran treatment court referrals",
        county="York", served_counties="York", coverage="single",
        _source="https://scdva.sc.gov", _source_type="government", _confidence="high",
    )
    add(
        name="Horry County Veterans Affairs Office",
        category="veterans", region="Horry / Horry County",
        description="The Horry County Veterans Affairs Office provides free VA benefits claims assistance, discharge upgrade guidance, and referrals to veteran treatment courts and SC DVS programs for justice-involved veterans in Horry County. County veterans service officers help returning veteran citizens navigate VA healthcare and disability compensation.",
        description_es="La Oficina de Asuntos de Veteranos del condado Horry ofrece asistencia gratuita con reclamaciones de beneficios VA y referencias a tribunales de tratamiento para veteranos para veteranos con antecedentes penales en el condado Horry.",
        address="1300 26th Avenue N", city="Horry", phone="843-915-5100", email="",
        website="https://scdva.sc.gov",
        eligibility="Veterans and eligible dependents in Horry County; service documentation required.",
        eligibility_es="Veteranos y dependientes elegibles en el condado Horry; se requiere documentación de servicio.",
        notes="Call 843-915-5100 for appointment; free claims assistance through SC DVS county network.",
        notes_es="Llame al 843-915-5100 para cita; asistencia gratuita con reclamaciones a través de la red del condado SC DVS.",
        hours="Monday–Friday business hours",
        tags="horry|veterans|VA-benefits|reentry",
        services="VA benefits claims assistance|Disability claims navigation|Healthcare enrollment help|Veteran treatment court referrals",
        county="Horry", served_counties="Horry", coverage="single",
        _source="https://scdva.sc.gov", _source_type="government", _confidence="high",
    )
    add(
        name="Golden Harvest Food Bank",
        category="food-nutrition", region="Augusta area / Aiken",
        description="Golden Harvest Food Bank distributes food through partner pantries and direct programs serving food-insecure households in Aiken, Edgefield, Barnwell, McCormick, Saluda counties including returning citizens reestablishing food security after incarceration. Partner agency network helps clients supplement SNAP benefits and access nutrition resources.",
        description_es="Golden Harvest Food Bank distribuye alimentos a través de despensas aliadas y programas directos sirviendo hogares con inseguridad alimentaria en los condados de la zona incluidos ciudadanos que regresan que reestablecen seguridad alimentaria.",
        address="3310 Commerce Drive", city="Aiken", phone="803-642-3408", email="",
        website="https://goldenharvest.org",
        eligibility="Food-insecure residents of the Aiken-area service counties; partner pantry registration requirements vary.",
        eligibility_es="Residentes con inseguridad alimentaria de los condados del área de Aiken; los requisitos de registro en despensas aliadas varían.",
        notes="Call 803-642-3408 or visit goldenharvest.org for partner pantries; pairs with county DSS SNAP offices.",
        notes_es="Llame al 803-642-3408 o visite goldenharvest.org para despensas aliadas; se vincula con oficinas DSS SNAP del condado.",
        hours="Hours vary by location",
        tags="food-nutrition|food-bank|pantry|aiken|reentry",
        services="Food distribution|Partner pantry network|SNAP outreach|Mobile pantry|Nutrition programs",
        county="Aiken", served_counties="Aiken|Edgefield|Barnwell|McCormick|Saluda", coverage="multi",
        _source="https://goldenharvest.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Cooperative Ministry — Columbia Emergency Assistance",
        category="basic-needs", region="Columbia / Richland County",
        description="The Cooperative Ministry provides emergency rent, utility, food, and prescription assistance for low-income Richland and Lexington county households including justice-involved families rebuilding after incarceration. Case managers connect clients to SC Works, DSS benefits, and Midlands housing partners through a centralized intake process on Calhoun Street.",
        description_es="The Cooperative Ministry ofrece asistencia de emergencia para renta, servicios públicos, alimentos y recetas para hogares de bajos ingresos de los condados Richland y Lexington incluidas familias con antecedentes penales que se reconstruyen después de la encarcelación.",
        address="3821 W. Beltline Boulevard", city="Columbia", phone="803-799-3853", email="",
        website="https://cooperativeministry.com",
        eligibility="Low-income residents of Richland and Lexington counties; appointment required for financial assistance.",
        eligibility_es="Residentes de bajos ingresos de los condados Richland y Lexington; cita requerida para asistencia financiera.",
        notes="Call 803-799-3853 for intake appointment; food pantry walk-ins during posted hours.",
        notes_es="Llame al 803-799-3853 para cita de admisión; despensa sin cita durante horarios publicados.",
        hours="Monday–Friday business hours",
        tags="columbia|basic-needs|emergency-assistance|richland|reentry",
        services="Emergency rent assistance|Utility assistance|Food pantry|Prescription assistance|Benefits referrals",
        county="Richland", served_counties="Richland|Lexington", coverage="multi",
        _source="https://cooperativeministry.com", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Anderson Interfaith Ministries",
        category="basic-needs", region="Anderson / Upstate",
        description="Anderson Interfaith Ministries provides emergency food, financial assistance, and referral navigation for low-income Anderson County residents including returning citizens reestablishing stability after release from Anderson County Detention Center. Staff connect clients to ROAR, SC Works Anderson, and Upstate treatment and housing partners.",
        description_es="Anderson Interfaith Ministries ofrece alimentos de emergencia, asistencia financiera y navegación de referencias para residentes de bajos ingresos del condado Anderson incluidos ciudadanos que regresan que reestablecen estabilidad después de la liberación.",
        address="1202 South Murray Avenue", city="Anderson", phone="864-226-2273", email="",
        website="https://aimcharity.org",
        eligibility="Low-income Anderson County residents; proof of income and residency for financial assistance.",
        eligibility_es="Residentes de bajos ingresos del condado Anderson; prueba de ingresos y residencia para asistencia financiera.",
        notes="Call 864-226-2273 for intake; food pantry hours posted online; pairs with ROAR and SC Works Anderson.",
        notes_es="Llame al 864-226-2273 para admisión; horario de despensa publicado en línea; se vincula con ROAR y SC Works Anderson.",
        hours="Monday–Friday business hours",
        tags="anderson|basic-needs|food|emergency-assistance|reentry",
        services="Emergency food|Financial assistance|Referral navigation|SNAP complement|Case management",
        county="Anderson", served_counties="Anderson", coverage="single",
        _source="https://aimcharity.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Beckman Center for Mental Health — Greenwood",
        category="substance-use-treatment", region="Greenwood / Lakelands",
        description="Beckman Center for Mental Health Services provides outpatient behavioral health and substance use treatment for Greenwood, Laurens, Abbeville, and Edgefield county residents including justice-involved adults under SCDPPPS supervision. Medicaid and sliding-fee services support returning citizens in rural Lakelands communities.",
        description_es="Beckman Center for Mental Health Services ofrece salud conductual ambulatoria y tratamiento de uso de sustancias para residentes de los condados Greenwood, Laurens, Abbeville y Edgefield incluidos adultos con antecedentes penales bajo supervisión SCDPPPS.",
        address="115 Carter Court", city="Greenwood", phone="864-941-5500", email="",
        website="https://beckmancenter.org",
        eligibility="Lakelands region residents needing behavioral health or substance use services; Medicaid accepted.",
        eligibility_es="Residentes de la región Lakelands que necesiten servicios de salud conductual o uso de sustancias; se acepta Medicaid.",
        notes="Call 864-941-5500 for intake; crisis services available; pairs with ABLRC community action.",
        notes_es="Llame al 864-941-5500 para admisión; servicios de crisis disponibles; se vincula con ABLRC.",
        hours="Monday–Friday clinic hours",
        tags="greenwood|substance-use-treatment|behavioral-health|lakelands|reentry",
        services="Outpatient counseling|Substance use treatment|Psychiatric services|Crisis referrals|Case management",
        county="Greenwood", served_counties="Greenwood|Laurens|Abbeville|Edgefield", coverage="multi",
        _source="https://beckmancenter.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Georgetown County Board of Voter Registration & Elections",
        category="id-documentation", region="Georgetown / Coastal",
        description="The Georgetown County Board of Voter Registration and Elections assists residents with voter registration, photo ID requirements, and guidance on restoring voting rights after felony convictions under South Carolina law. Staff provide forms and referrals to SCDMV and South Carolina Legal Services—not DMV licensing services.",
        description_es="La Junta de Registro de Votantes y Elecciones del condado Georgetown ayuda a residentes con registro de votantes, requisitos de identificación con foto y orientación sobre restauración de derechos de voto después de condenas por delitos graves según la ley de Carolina del Sur.",
        address="303 North Hazard Street", city="Georgetown", phone="843-545-3339", email="vote@gtcounty.org",
        website="https://www.gtcounty.org/directory.aspx?did=46",
        eligibility="Georgetown County residents; individuals with felony convictions should verify rights restoration requirements at scvotes.gov.",
        eligibility_es="Residentes del condado Georgetown; personas con condenas por delitos graves deben verificar requisitos de restauración de derechos en scvotes.gov.",
        notes="Call 843-545-3339 Monday–Friday 8:30 a.m.–5:00 p.m.; online registration at scvotes.gov; pairs with SCDMV and SCLS Georgetown office.",
        notes_es="Llame al 843-545-3339 de lunes a viernes 8:30 a.m.–5:00 p.m.; registro en línea en scvotes.gov; se vincula con SCDMV y oficina SCLS de Georgetown.",
        hours="Monday–Friday, 8:30 a.m.–5:00 p.m.",
        tags="georgetown|id-documentation|voting-rights|coastal|reentry",
        services="Voter registration|Photo ID guidance|Rights restoration information|Document counseling|Election referrals",
        county="Georgetown", served_counties="Georgetown", coverage="single",
        _source="https://scvotes.gov/contact/county-voter-registration-election-offices/", _source_type="government", _confidence="high",
    )
    add(
        name="Waccamaw Regional Transportation Authority",
        category="transportation", region="Georgetown / Horry",
        description="Waccamaw Regional Transportation Authority provides public transit and paratransit services in Georgetown and Horry counties connecting coastal residents to SC Works Conway, New Directions Myrtle Beach, and coastal healthcare facilities. Returning citizens without vehicles use Waccamaw Regional to reach employment and probation appointments.",
        description_es="Waccamaw Regional Transportation Authority ofrece tránsito público y paratransporte en los condados Georgetown y Horry conectando a residentes costeros con SC Works Conway, New Directions Myrtle Beach e instalaciones de salud costeras.",
        address="1410 Highway 501 East", city="Conway", phone="843-488-0865", email="",
        website="https://waccamawregion.com",
        eligibility="Open to all riders in Georgetown and Horry counties; ADA paratransit for eligible riders.",
        eligibility_es="Abierto a todos los pasajeros en los condados Georgetown y Horry; paratransporte ADA para pasajeros elegibles.",
        notes="Route information at waccamawregion.com; pairs with Coast RTA services in Horry County.",
        notes_es="Información de rutas en waccamawregion.com; se vincula con servicios Coast RTA en el condado Horry.",
        hours="Route hours vary",
        tags="georgetown|horry|transportation|public-transit|coastal|reentry",
        services="Fixed-route bus service|ADA paratransit|Reduced fares|Coastal routes|Rural connectors",
        county="Horry", served_counties="Horry|Georgetown", coverage="multi",
        _source="https://waccamawregion.com", _source_type="government", _confidence="high",
    )
    add(
        name="Darlington County Adult Education",
        category="education", region="Darlington / Pee Dee",
        description="Darlington County Adult Education offers GED preparation, adult literacy, and workforce readiness classes for justice-involved adults in Darlington, Florence, and Chesterfield counties rebuilding education credentials after incarceration. Free instruction prepares students for high school equivalency testing and connects graduates to Pee Dee SC Works centers.",
        description_es="Educación para Adultos del condado Darlington ofrece preparación para el GED, alfabetización de adultos y clases de preparación laboral para adultos con antecedentes penales en los condados Darlington, Florence y Chesterfield.",
        address="120 E. Smith Avenue", city="Darlington", phone="843-398-2342", email="",
        website="https://www.scworks.org",
        eligibility="Adults 17 and older without high school diploma in the Pee Dee region; justice-involved students welcome.",
        eligibility_es="Adultos de 17 años o más sin diploma de secundaria en la región Pee Dee; estudiantes con antecedentes penales bienvenidos.",
        notes="Call 843-398-2342 for enrollment; pairs with SC Works Darlington and Keystone.",
        notes_es="Llame al 843-398-2342 para inscripción; se vincula con SC Works Darlington y Keystone.",
        hours="Class schedules vary",
        tags="darlington|education|GED|adult-education|pee-dee|reentry",
        services="GED preparation|Adult literacy|Workforce readiness|Testing referrals|SC Works connections",
        county="Darlington", served_counties="Darlington|Florence|Chesterfield", coverage="multi",
        _source="https://www.scworks.org", _source_type="government", _confidence="high",
    )
    add(
        name="Newberry County VSO — Veterans Benefits",
        category="veterans", region="Newberry / Midlands",
        description="The Newberry County Veterans Affairs office provides free VA benefits claims assistance and referrals to SC DVS programs for justice-involved veterans in Newberry, Fairfield, and Lexington fringe communities rebuilding after incarceration.",
        description_es="La oficina de Asuntos de Veteranos del condado Newberry ofrece asistencia gratuita con reclamaciones de beneficios VA y referencias a programas SC DVS para veteranos con antecedentes penales en comunidades de Newberry, Fairfield y Lexington.",
        address="1100 N. Main Street", city="Newberry", phone="803-321-2105", email="",
        website="https://scdva.sc.gov",
        eligibility="Veterans and eligible dependents in Newberry County; service documentation required.",
        eligibility_es="Veteranos y dependientes elegibles en el condado Newberry; se requiere documentación de servicio.",
        notes="Call 803-321-2105 for appointment; part of SC DVS 46-county VSO network.",
        notes_es="Llame al 803-321-2105 para cita; parte de la red VSO de 46 condados de SC DVS.",
        hours="Monday–Friday business hours",
        tags="newberry|veterans|VA-benefits|midlands|reentry",
        services="VA benefits claims assistance|Disability navigation|Healthcare enrollment|Veteran treatment court referrals",
        county="Newberry", served_counties="Newberry|Fairfield", coverage="multi",
        _source="https://scdva.sc.gov", _source_type="government", _confidence="high",
    )
    add(
        name="Pickens County Meals and More Food Pantry",
        category="food-nutrition", region="Pickens / Upstate",
        description="Pickens County Meals and More operates a food pantry and emergency nutrition support for low-income Pickens County households including returning citizens reestablishing food security after release. The pantry supplements SNAP benefits and connects clients to SC Works Easley and Upstate reentry partners.",
        description_es="Pickens County Meals and More opera una despensa de alimentos y apoyo nutricional de emergencia para hogares de bajos ingresos del condado Pickens incluidos ciudadanos que regresan que reestablecen seguridad alimentaria.",
        address="222 Hampton Avenue", city="Pickens", phone="864-878-1121", email="",
        website="https://harvesthope.org",
        eligibility="Low-income Pickens County residents; registration may require proof of address.",
        eligibility_es="Residentes de bajos ingresos del condado Pickens; el registro puede requerir prueba de dirección.",
        notes="Call 864-878-1121 for pantry hours; pairs with SC Works Pickens and ROAR.",
        notes_es="Llame al 864-878-1121 para horario de despensa; se vincula con SC Works Pickens y ROAR.",
        hours="Pantry hours vary; call ahead",
        tags="pickens|food-nutrition|pantry|upstate|reentry",
        services="Emergency food boxes|Pantry distribution|SNAP complement|Nutrition support|Referral navigation",
        county="Pickens", served_counties="Pickens", coverage="single",
        _source="https://harvesthope.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Lexington County Community Mental Health",
        category="peer-support", region="Lexington / Midlands",
        description="Lexington County Community Mental Health provides peer support groups, outpatient counseling, and recovery coaching for adults with mental health and substance use challenges including justice-involved clients in Lexington and Richland fringe communities coordinating with LRADAC and Transitions SC.",
        description_es="Lexington County Community Mental Health ofrece grupos de apoyo entre pares, consejería ambulatoria y coaching de recuperación para adultos con desafíos de salud mental y uso de sustancias incluidos clientes con antecedentes penales en comunidades de Lexington y Richland.",
        address="3180 Augusta Road", city="Lexington", phone="803-359-3454", email="",
        website="https://scdmh.net",
        eligibility="Lexington County residents needing behavioral health or peer support services; Medicaid accepted.",
        eligibility_es="Residentes del condado Lexington que necesiten servicios de salud conductual o apoyo entre pares; se acepta Medicaid.",
        notes="Call 803-359-3454 for intake; pairs with LRADAC and New Directions Midlands.",
        notes_es="Llame al 803-359-3454 para admisión; se vincula con LRADAC y New Directions Midlands.",
        hours="Monday–Friday clinic hours",
        tags="lexington|peer-support|behavioral-health|midlands|reentry",
        services="Peer support groups|Outpatient counseling|Recovery coaching|Crisis referrals|Case management",
        county="Lexington", served_counties="Lexington", coverage="single",
        _source="https://scdmh.net", _source_type="government", _confidence="high",
    )
    add(
        name="Oconee County DSS — SNAP Outreach",
        category="food-nutrition", region="Seneca / Oconee County",
        description="Oconee County DSS coordinates SNAP outreach and emergency food referrals for low-income Oconee County households including justice-involved residents applying for benefits through benefitsportal.dss.sc.gov. DSS staff assist with verification and connect clients to regional food pantries and SC Works Seneca.",
        description_es="DSS del condado Oconee coordina alcance SNAP y referencias de alimentos de emergencia para hogares de bajos ingresos del condado Oconee incluidos residentes con antecedentes penales que solicitan beneficios a través de benefitsportal.dss.sc.gov.",
        address="1860 Wells Highway", city="Seneca", phone="864-882-2100", email="",
        website="https://portal.dss.sc.gov",
        eligibility="Oconee County residents meeting SNAP income requirements; criminal record generally not a barrier.",
        eligibility_es="Residentes del condado Oconee que cumplan requisitos de ingresos SNAP; los antecedentes penales generalmente no son barrera.",
        notes="Apply online at benefitsportal.dss.sc.gov; call 864-882-2100 for county office help.",
        notes_es="Solicite en benefitsportal.dss.sc.gov; llame al 864-882-2100 para ayuda de la oficina del condado.",
        hours="Monday–Friday business hours",
        tags="oconee|food-nutrition|SNAP|DSS|outreach|reentry",
        services="SNAP outreach|Emergency food referrals|Benefits verification|Medicaid application help|SC Works referrals",
        county="Oconee", served_counties="Oconee", coverage="single",
        _source="https://portal.dss.sc.gov", _source_type="government", _confidence="high",
    )

    add(
        name="Second Harvest Food Bank of Metrolina",
        category="food-nutrition", region="Rock Hill",
        description="Second Harvest Food Bank of Metrolina distributes food through partner pantries and direct programs serving food-insecure households in York, Lancaster, Chester counties including returning citizens reestablishing food security after incarceration. Partner agency network helps clients supplement SNAP benefits and access nutrition resources.",
        description_es="Second Harvest Food Bank of Metrolina distribuye alimentos a través de despensas aliadas y programas directos sirviendo hogares con inseguridad alimentaria en los condados de la zona incluidos ciudadanos que regresan que reestablecen seguridad alimentaria.",
        address="500-B Spratt Street", city="York", phone="803-327-3134", email="",
        website="https://sc211.org",
        eligibility="Food-insecure residents of the service area; partner pantry registration requirements vary.",
        eligibility_es="Residentes con inseguridad alimentaria del área de servicio; los requisitos de registro en despensas aliadas varían.",
        notes="Call 803-327-3134 or search sc211.org for nearest pantry; pairs with county DSS SNAP offices.",
        notes_es="Llame al 803-327-3134 o busque en sc211.org la despensa más cercana; se vincula con oficinas DSS SNAP del condado.",
        hours="Hours vary by location",
        tags="food-nutrition|food-bank|pantry|york|reentry",
        services="Food distribution|Partner pantry network|SNAP outreach|Mobile pantry|Nutrition programs",
        county="York", served_counties="York|Lancaster|Chester", coverage="multi",
        _source="https://sc211.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="I-Believe Food Pantry Network",
        category="food-nutrition", region="Spartanburg",
        description="I-Believe Food Pantry Network distributes food through partner pantries and direct programs serving food-insecure households in Spartanburg, Cherokee, Union counties including returning citizens reestablishing food security after incarceration. Partner agency network helps clients supplement SNAP benefits and access nutrition resources.",
        description_es="I-Believe Food Pantry Network distribuye alimentos a través de despensas aliadas y programas directos sirviendo hogares con inseguridad alimentaria en los condados de la zona incluidos ciudadanos que regresan que reestablecen seguridad alimentaria.",
        address="400 E. Main Street", city="Spartanburg", phone="864-573-7688", email="",
        website="https://sc211.org",
        eligibility="Food-insecure residents of the service area; partner pantry registration requirements vary.",
        eligibility_es="Residentes con inseguridad alimentaria del área de servicio; los requisitos de registro en despensas aliadas varían.",
        notes="Call 864-573-7688 or search sc211.org for nearest pantry; pairs with county DSS SNAP offices.",
        notes_es="Llame al 864-573-7688 o busque en sc211.org la despensa más cercana; se vincula con oficinas DSS SNAP del condado.",
        hours="Hours vary by location",
        tags="food-nutrition|food-bank|pantry|spartanburg|reentry",
        services="Food distribution|Partner pantry network|SNAP outreach|Mobile pantry|Nutrition programs",
        county="Spartanburg", served_counties="Spartanburg|Cherokee|Union", coverage="multi",
        _source="https://sc211.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Richland County Library — Reentry Resource Navigation",
        category="id-documentation", region="Columbia / Richland County",
        description="Library social workers help justice-involved patrons obtain birth certificates, IDs, and online benefits applications through partner referrals to SCDMV and DSS—not a licensing office. Direct community services for Columbia area residents—not a statewide hotline.",
        description_es="Servicios comunitarios directos para residentes del área de Columbia—no es una línea estatal. Programas de apoyo para personas con antecedentes penales que reconstruyen estabilidad después de la encarcelación en el condado Richland.",
        address="1431 Assembly Street", city="Columbia", phone="803-799-9084", email="",
        website="https://sc211.org",
        eligibility="Low-income residents of Richland, Lexington; justice-involved individuals welcome per program policy.",
        eligibility_es="Residentes de bajos ingresos de la zona de servicio; personas con antecedentes penales bienvenidas según política del programa.",
        notes="Call 803-799-9084 for intake; pairs with SC 211 and local reentry partners.",
        notes_es="Llame al 803-799-9084 para admisión; se vincula con SC 211 y aliados locales de reinserción.",
        hours="Monday–Friday business hours; varies by program",
        tags="columbia|id-documentation|reentry",
        services="Community referrals|Case navigation|Direct assistance|Partner connections|Resource counseling",
        county="Richland", served_counties="Richland|Lexington", coverage="multi",
        _source="https://sc211.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Palmetto Health Bright Futures — Peer Support",
        category="peer-support", region="Columbia / Richland County",
        description="Certified peer support specialists help adults with mental health and substance use challenges including justice-involved clients navigating treatment, housing, and SC Works referrals. Direct community services for Columbia area residents—not a statewide hotline.",
        description_es="Servicios comunitarios directos para residentes del área de Columbia—no es una línea estatal. Programas de apoyo para personas con antecedentes penales que reconstruyen estabilidad después de la encarcelación en el condado Richland.",
        address="1301 Taylor Street", city="Columbia", phone="803-296-2273", email="",
        website="https://sc211.org",
        eligibility="Low-income residents of Richland; justice-involved individuals welcome per program policy.",
        eligibility_es="Residentes de bajos ingresos de la zona de servicio; personas con antecedentes penales bienvenidas según política del programa.",
        notes="Call 803-296-2273 for intake; pairs with SC 211 and local reentry partners.",
        notes_es="Llame al 803-296-2273 para admisión; se vincula con SC 211 y aliados locales de reinserción.",
        hours="Monday–Friday business hours; varies by program",
        tags="columbia|peer-support|reentry",
        services="Community referrals|Case navigation|Direct assistance|Partner connections|Resource counseling",
        county="Richland", served_counties="Richland", coverage="single",
        _source="https://sc211.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Spartanburg Regional Transportation — Dial-a-Ride",
        category="transportation", region="Spartanburg / Spartanburg County",
        description="Spartanburg County dial-a-ride and connector services help residents without vehicles reach SC Works, Miracle Hill, and medical appointments. Direct community services for Spartanburg area residents—not a statewide hotline.",
        description_es="Servicios comunitarios directos para residentes del área de Spartanburg—no es una línea estatal. Programas de apoyo para personas con antecedentes penales que reconstruyen estabilidad después de la encarcelación en el condado Spartanburg.",
        address="100 E. Main Street", city="Spartanburg", phone="864-573-7244", email="",
        website="https://sc211.org",
        eligibility="Low-income residents of Spartanburg, Cherokee; justice-involved individuals welcome per program policy.",
        eligibility_es="Residentes de bajos ingresos de la zona de servicio; personas con antecedentes penales bienvenidas según política del programa.",
        notes="Call 864-573-7244 for intake; pairs with SC 211 and local reentry partners.",
        notes_es="Llame al 864-573-7244 para admisión; se vincula con SC 211 y aliados locales de reinserción.",
        hours="Monday–Friday business hours; varies by program",
        tags="spartanburg|transportation|reentry",
        services="Community referrals|Case navigation|Direct assistance|Partner connections|Resource counseling",
        county="Spartanburg", served_counties="Spartanburg|Cherokee", coverage="multi",
        _source="https://sc211.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="LRADAC — Chester County Outreach",
        category="substance-use-treatment", region="Chester / Chester County",
        description="LRADAC Chester outreach provides substance use assessment, outpatient counseling, and MAT referrals for justice-involved adults in the Catawba region under SCDPPPS supervision. Direct community services for Chester area residents—not a statewide hotline.",
        description_es="Servicios comunitarios directos para residentes del área de Chester—no es una línea estatal. Programas de apoyo para personas con antecedentes penales que reconstruyen estabilidad después de la encarcelación en el condado Chester.",
        address="112 J.A. Cochran Bypass", city="Chester", phone="803-385-5151", email="",
        website="https://sc211.org",
        eligibility="Low-income residents of Chester, Lancaster, York; justice-involved individuals welcome per program policy.",
        eligibility_es="Residentes de bajos ingresos de la zona de servicio; personas con antecedentes penales bienvenidas según política del programa.",
        notes="Call 803-385-5151 for intake; pairs with SC 211 and local reentry partners.",
        notes_es="Llame al 803-385-5151 para admisión; se vincula con SC 211 y aliados locales de reinserción.",
        hours="Monday–Friday business hours; varies by program",
        tags="chester|substance-use-treatment|reentry",
        services="Community referrals|Case navigation|Direct assistance|Partner connections|Resource counseling",
        county="Chester", served_counties="Chester|Lancaster|York", coverage="multi",
        _source="https://sc211.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Birthright of Charleston — Pregnancy & Family Support",
        category="family-children", region="Charleston / Charleston County",
        description="Birthright provides pregnancy support, parenting supplies, and referrals for expectant parents including justice-involved mothers reunifying with children after release. Direct community services for Charleston area residents—not a statewide hotline.",
        description_es="Birthright of Charleston ofrece apoyo durante el embarazo, suministros para la crianza y referencias para padres expectantes, incluidas madres con antecedentes penales que se reúnen con sus hijos después de la liberación. Servicios comunitarios directos en el área de Charleston, no una línea estatal.",
        address="1909 Savannah Highway", city="Charleston", phone="843-769-9898", email="",
        website="https://birthrightcharleston.org",
        eligibility="Expectant and new parents in the Charleston area; justice-involved mothers welcome for pregnancy and parenting support.",
        eligibility_es="Padres expectantes y nuevos en el área de Charleston; madres con antecedentes penales bienvenidas para apoyo durante el embarazo y la crianza.",
        notes="Call 843-769-9898 for intake; free pregnancy tests and parenting supplies; pairs with One80 Place family programs.",
        notes_es="Llame al 843-769-9898 para admisión; pruebas de embarazo y suministros para la crianza gratuitos; se vincula con programas familiares de One80 Place.",
        hours="Monday–Friday business hours",
        tags="charleston|family-children|pregnancy|parenting|reentry",
        services="Pregnancy support|Parenting supplies|Referrals|Maternity counseling|Community navigation",
        county="Charleston", served_counties="Charleston|Berkeley|Dorchester", coverage="multi",
        _source="https://birthrightcharleston.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Saint Vincent de Paul — Columbia Conference",
        category="basic-needs", region="Columbia / Richland County",
        description="Saint Vincent de Paul Columbia provides emergency rent, utility, and food assistance for low-income households including returning citizens through parish-based volunteer networks. Direct community services for Columbia area residents—not a statewide hotline.",
        description_es="Saint Vincent de Paul Columbia proporciona asistencia de emergencia para renta, servicios públicos y alimentos para hogares de bajos ingresos, incluidos ciudadanos que regresan, a través de redes de voluntarios parroquiales. Servicios comunitarios directos en el área de Columbia.",
        address="2711 Middleburg Drive", city="Columbia", phone="803-254-0111", email="",
        website="https://www.svdpofcolumbia.org",
        eligibility="Low-income residents of Richland and Lexington counties; justice-involved households eligible for emergency assistance.",
        eligibility_es="Residentes de bajos ingresos de los condados Richland y Lexington; hogares con antecedentes penales elegibles para asistencia de emergencia.",
        notes="Call 803-254-0111 for home visit intake; parish volunteers provide rent, utility, and food help.",
        notes_es="Llame al 803-254-0111 para admisión con visita domiciliaria; voluntarios parroquiales brindan ayuda con renta, servicios y alimentos.",
        hours="Intake by appointment; call for schedule",
        tags="columbia|basic-needs|emergency-assistance|utilities|reentry",
        services="Emergency rent assistance|Utility assistance|Food aid|Home visits|Parish-based support",
        county="Richland", served_counties="Richland|Lexington", coverage="multi",
        _source="https://www.svdpofcolumbia.org", _source_type="nonprofit", _confidence="high",
    )

    # --- category minimum gap-fill ---
    add(
        name="South Carolina Legal Services — Anderson Office",
        category="legal-aid", region="Anderson / Upstate",
        description="The South Carolina Legal Services Anderson regional office provides free civil legal aid to low-income Upstate residents including housing eviction defense, public benefits appeals, and expungement assistance under South Carolina law. Justice-involved clients in Anderson, Oconee, and Pickens counties can apply for record relief and benefits advocacy—not criminal defense.",
        description_es="La oficina regional de South Carolina Legal Services en Anderson brinda asistencia legal civil gratuita a residentes de bajos ingresos del Upstate incluyendo defensa contra desalojo, apelaciones de beneficios públicos y asistencia con expungación bajo la ley de Carolina del Sur.",
        address="1204 South Murray Avenue", city="Anderson", phone="864-225-6637", email="",
        website="https://sclegal.org",
        eligibility="Low-income residents of SCLS Anderson service counties with civil legal problems; LSC income limits apply.",
        eligibility_es="Residentes de bajos ingresos de los condados de servicio SCLS Anderson con problemas legales civiles; aplican límites LSC.",
        notes="Call 864-225-6637 or statewide helpline 1-888-346-5592; apply online at sclegal.org.",
        notes_es="Llame al 864-225-6637 o línea estatal 1-888-346-5592; solicite en sclegal.org.",
        hours="Intake Monday–Friday business hours",
        tags="anderson|legal-aid|low-income|expungement|reentry",
        services="Civil legal representation|Expungement assistance|Housing legal aid|Benefits appeals|Family law assistance",
        county="Anderson", served_counties="Anderson|Oconee|Pickens|Abbeville|Greenwood|Laurens", coverage="multi",
        _source="https://sclegal.org/locations/", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="South Carolina Legal Services — Aiken Office",
        category="legal-aid", region="Aiken / CSRA",
        description="The South Carolina Legal Services Aiken regional office provides free civil legal aid to low-income CSRA residents including housing eviction defense, public benefits appeals, and expungement assistance. Justice-involved clients in Aiken, Edgefield, Barnwell, and Allendale counties can apply for civil record relief—not criminal defense representation.",
        description_es="La oficina regional de South Carolina Legal Services en Aiken brinda asistencia legal civil gratuita a residentes de bajos ingresos del CSRA incluyendo defensa contra desalojo, apelaciones de beneficios y asistencia con expungación.",
        address="1701 Main Street", city="Aiken", phone="803-648-1301", email="",
        website="https://sclegal.org",
        eligibility="Low-income residents of SCLS Aiken service counties with civil legal problems; LSC income limits apply.",
        eligibility_es="Residentes de bajos ingresos de los condados de servicio SCLS Aiken con problemas legales civiles; aplican límites LSC.",
        notes="Call 803-648-1301 or statewide helpline 1-888-346-5592; apply online at sclegal.org.",
        notes_es="Llame al 803-648-1301 o línea estatal 1-888-346-5592; solicite en sclegal.org.",
        hours="Intake Monday–Friday business hours",
        tags="aiken|legal-aid|low-income|expungement|reentry",
        services="Civil legal representation|Expungement assistance|Housing legal aid|Benefits appeals|Family law assistance",
        county="Aiken", served_counties="Aiken|Edgefield|Barnwell|Allendale|Saluda|McCormick", coverage="multi",
        _source="https://sclegal.org/locations/", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="South Carolina Legal Services — Rock Hill Office",
        category="legal-aid", region="Rock Hill / York County",
        description="The South Carolina Legal Services Rock Hill regional office provides free civil legal aid to low-income residents of York, Lancaster, Chester, and Union counties including housing eviction defense, public benefits appeals, and expungement assistance. Justice-involved clients can apply for record relief and benefits denials—not criminal defense.",
        description_es="La oficina regional de South Carolina Legal Services en Rock Hill brinda asistencia legal civil gratuita a residentes de bajos ingresos de los condados York, Lancaster, Chester y Union incluyendo defensa contra desalojo y asistencia con expungación.",
        address="331 E. Main Street", city="Rock Hill", phone="803-327-6101", email="",
        website="https://sclegal.org",
        eligibility="Low-income residents of SCLS Rock Hill service counties with civil legal problems; LSC income limits apply.",
        eligibility_es="Residentes de bajos ingresos de los condados de servicio SCLS Rock Hill con problemas legales civiles; aplican límites LSC.",
        notes="Call 803-327-6101 or statewide helpline 1-888-346-5592; apply online at sclegal.org.",
        notes_es="Llame al 803-327-6101 o línea estatal 1-888-346-5592; solicite en sclegal.org.",
        hours="Intake Monday–Friday business hours",
        tags="rock-hill|york|legal-aid|low-income|expungement|reentry",
        services="Civil legal representation|Expungement assistance|Housing legal aid|Benefits appeals|Family law assistance",
        county="York", served_counties="York|Lancaster|Chester|Union|Cherokee", coverage="multi",
        _source="https://sclegal.org/locations/", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="South Carolina Legal Services — Orangeburg Office",
        category="legal-aid", region="Orangeburg / I-95 Corridor",
        description="The South Carolina Legal Services Orangeburg regional office provides free civil legal aid to low-income residents of Orangeburg, Calhoun, Bamberg, and Clarendon counties including housing eviction defense, public benefits appeals, and expungement assistance. Justice-involved clients in rural I-95 corridor counties can apply for civil legal help—not criminal defense.",
        description_es="La oficina regional de South Carolina Legal Services en Orangeburg brinda asistencia legal civil gratuita a residentes de bajos ingresos de los condados Orangeburg, Calhoun, Bamberg y Clarendon incluyendo defensa contra desalojo y asistencia con expungación.",
        address="1050 Founders Boulevard", city="Orangeburg", phone="803-534-1011", email="",
        website="https://sclegal.org",
        eligibility="Low-income residents of SCLS Orangeburg service counties with civil legal problems; LSC income limits apply.",
        eligibility_es="Residentes de bajos ingresos de los condados de servicio SCLS Orangeburg con problemas legales civiles; aplican límites LSC.",
        notes="Call 803-534-1011 or statewide helpline 1-888-346-5592; apply online at sclegal.org.",
        notes_es="Llame al 803-534-1011 o línea estatal 1-888-346-5592; solicite en sclegal.org.",
        hours="Intake Monday–Friday business hours",
        tags="orangeburg|legal-aid|low-income|expungement|rural|reentry",
        services="Civil legal representation|Expungement assistance|Housing legal aid|Benefits appeals|Family law assistance",
        county="Orangeburg", served_counties="Orangeburg|Calhoun|Bamberg|Clarendon|Lee|Sumter", coverage="multi",
        _source="https://sclegal.org/locations/", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="South Carolina Legal Services — Georgetown Office",
        category="legal-aid", region="Georgetown / Lowcountry",
        description="The South Carolina Legal Services Georgetown regional office provides free civil legal aid to low-income coastal residents of Georgetown, Horry, and Williamsburg counties including housing eviction defense, public benefits appeals, and expungement assistance. Justice-involved clients on the Grand Strand and rural coast can apply for civil legal help—not criminal defense.",
        description_es="La oficina regional de South Carolina Legal Services en Georgetown brinda asistencia legal civil gratuita a residentes costeros de bajos ingresos de los condados Georgetown, Horry y Williamsburg incluyendo defensa contra desalojo y asistencia con expungación.",
        address="1225 North Fraser Street", city="Georgetown", phone="843-527-0066", email="",
        website="https://sclegal.org",
        eligibility="Low-income residents of SCLS Georgetown service counties with civil legal problems; LSC income limits apply.",
        eligibility_es="Residentes de bajos ingresos de los condados de servicio SCLS Georgetown con problemas legales civiles; aplican límites LSC.",
        notes="Call 843-527-0066 or statewide helpline 1-888-346-5592; apply online at sclegal.org.",
        notes_es="Llame al 843-527-0066 o línea estatal 1-888-346-5592; solicite en sclegal.org.",
        hours="Intake Monday–Friday business hours",
        tags="georgetown|horry|legal-aid|low-income|expungement|reentry",
        services="Civil legal representation|Expungement assistance|Housing legal aid|Benefits appeals|Family law assistance",
        county="Georgetown", served_counties="Georgetown|Horry|Williamsburg|Dillon|Marion", coverage="multi",
        _source="https://sclegal.org/locations/", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Trident Literacy Association — Adult Education",
        category="education", region="North Charleston / Tri-County",
        description="Trident Literacy Association provides free adult literacy, GED preparation, and English language instruction for low-income Tri-County residents including justice-involved adults rebuilding education credentials after release from Charleston County Detention Center. Instructors help returning citizens pass GED exams and connect to SC Works Trident and fair-chance employers.",
        description_es="Trident Literacy Association ofrece alfabetización de adultos gratuita, preparación para el GED e instrucción en inglés para residentes de bajos ingresos del Tri-County, incluidos adultos con antecedentes penales que reconstruyen credenciales educativas después de la liberación.",
        address="7245 Stall Road", city="North Charleston", phone="843-747-2223", email="",
        website="https://tridentlit.org",
        eligibility="Adults 18 and older in Berkeley, Charleston, and Dorchester counties; free programs for qualifying students.",
        eligibility_es="Adultos de 18 años o más en los condados Berkeley, Charleston y Dorchester; programas gratuitos para estudiantes calificados.",
        notes="Call 843-747-2223 for enrollment; morning and evening classes; pairs with Turning Leaf and SC Works.",
        notes_es="Llame al 843-747-2223 para inscripción; clases matutinas y vespertinas; se vincula con Turning Leaf y SC Works.",
        hours="Class schedules vary; office Monday–Friday",
        tags="charleston|education|GED|literacy|adult-education|reentry",
        services="Adult literacy|GED preparation|English language instruction|Testing referrals|Employment connections",
        county="Charleston", served_counties="Berkeley|Charleston|Dorchester", coverage="multi",
        _source="https://tridentlit.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="York County Adult Education — GED & WorkKeys",
        category="education", region="Rock Hill / York County",
        description="York County Adult Education offers GED preparation, WorkKeys career readiness certification, and English language classes for justice-involved adults in York, Chester, and Lancaster counties at the Floyd T. Lewis Center in York. Free classes prepare returning citizens for SC Works York training programs and Charlotte metro fair-chance employment.",
        description_es="York County Adult Education ofrece preparación para el GED, certificación WorkKeys de preparación profesional y clases de inglés para adultos con antecedentes penales en los condados York, Chester y Lancaster en el Floyd T. Lewis Center.",
        address="521 Oakland Avenue", city="York", phone="803-684-2461", email="",
        website="https://www.yorkcountyschools.org",
        eligibility="Adults 17 and older in York County area; no high school diploma required for GED prep; justice-involved students welcome.",
        eligibility_es="Adultos de 17 años o más en el área del condado York; no se requiere diploma para preparación GED; estudiantes con antecedentes penales bienvenidos.",
        notes="Call 803-684-2461 for class schedules; pairs with Keystone Rock Hill and SC Works York.",
        notes_es="Llame al 803-684-2461 para horarios de clases; se vincula con Keystone Rock Hill y SC Works York.",
        hours="Monday–Thursday class hours; call for schedule",
        tags="york|education|GED|WorkKeys|adult-education|reentry",
        services="GED preparation|WorkKeys certification|English language classes|Career readiness|Testing coordination",
        county="York", served_counties="York|Chester|Lancaster", coverage="multi",
        _source="https://www.yorkcountyschools.org", _source_type="government", _confidence="high",
    )
    add(
        name="Aiken County Adult Education — GED Program",
        category="education", region="Aiken / CSRA",
        description="Aiken County Adult Education provides GED preparation, skills remediation, and career readiness classes for justice-involved adults in Aiken, Barnwell, and Edgefield counties at the Aiken County Career and Technology Center. Instructors coordinate with SC Works Aiken and ABLRC Community Action for returning citizens completing education requirements before employment training.",
        description_es="Aiken County Adult Education ofrece preparación para el GED, remediación de habilidades y clases de preparación profesional para adultos con antecedentes penales en los condados Aiken, Barnwell y Edgefield.",
        address="2451 Jefferson Davis Highway", city="Graniteville", phone="803-641-2428", email="",
        website="https://www.acpsd.net",
        eligibility="Adults 17 and older in Aiken County area; free GED prep for qualifying students; justice-involved adults welcome.",
        eligibility_es="Adultos de 17 años o más en el área del condado Aiken; preparación GED gratuita para estudiantes calificados; adultos con antecedentes penales bienvenidos.",
        notes="Call 803-641-2428 for enrollment; day and evening classes available.",
        notes_es="Llame al 803-641-2428 para inscripción; clases diurnas y vespertinas disponibles.",
        hours="Class schedules vary by term",
        tags="aiken|education|GED|adult-education|CSRA|reentry",
        services="GED preparation|Skills remediation|Career readiness classes|Testing referrals|SC Works coordination",
        county="Aiken", served_counties="Aiken|Barnwell|Edgefield", coverage="multi",
        _source="https://www.acpsd.net", _source_type="government", _confidence="high",
    )
    add(
        name="Piedmont Technical College — Adult Education",
        category="education", region="Greenwood / Upstate",
        description="Piedmont Technical College Adult Education offers GED preparation, WIN career readiness credentials, and English language instruction at sites across Greenwood, Laurens, Newberry, and Abbeville counties for justice-involved adults in rural Upstate South Carolina. Free classes connect graduates to SC Works Laurens and regional manufacturing employers.",
        description_es="Piedmont Technical College Adult Education ofrece preparación para el GED, credenciales WIN de preparación profesional e instrucción en inglés en sitios de los condados Greenwood, Laurens, Newberry y Abbeville para adultos con antecedentes penales en el Upstate rural.",
        address="620 North Emerald Road", city="Greenwood", phone="864-941-8420", email="",
        website="https://www.ptc.edu/adult-education",
        eligibility="Adults 17 and older in Piedmont Tech service area; free GED prep; justice-involved students welcome.",
        eligibility_es="Adultos de 17 años o más en el área de servicio de Piedmont Tech; preparación GED gratuita; estudiantes con antecedentes penales bienvenidos.",
        notes="Call 864-941-8420 for nearest class site; pairs with SC Works Greenwood and ROAR.",
        notes_es="Llame al 864-941-8420 para el sitio de clases más cercano; se vincula con SC Works Greenwood y ROAR.",
        hours="Class schedules vary by county site",
        tags="greenwood|education|GED|adult-education|rural|reentry",
        services="GED preparation|WIN career readiness|English language instruction|Workforce referrals|Testing coordination",
        county="Greenwood", served_counties="Greenwood|Laurens|Newberry|Abbeville|McCormick", coverage="multi",
        _source="https://www.ptc.edu/adult-education", _source_type="government", _confidence="high",
    )
    add(
        name="Horry County Adult Education — GED & ESL",
        category="education", region="Conway / Horry County",
        description="Horry County Adult Education provides GED preparation and English language classes for justice-involved adults in Horry and Georgetown counties at Conway and Myrtle Beach learning centers. Instructors coordinate with New Directions, SC Works Coastal, and Grand Strand employers for returning citizens completing education before workforce training.",
        description_es="Horry County Adult Education ofrece preparación para el GED y clases de inglés para adultos con antecedentes penales en los condados Horry y Georgetown en centros de aprendizaje de Conway y Myrtle Beach.",
        address="335 Four Mile Road", city="Conway", phone="843-488-6200", email="",
        website="https://www.horrycountyschools.net",
        eligibility="Adults 17 and older in Horry County; free GED prep; justice-involved students welcome.",
        eligibility_es="Adultos de 17 años o más en el condado Horry; preparación GED gratuita; estudiantes con antecedentes penales bienvenidos.",
        notes="Call 843-488-6200 for enrollment; pairs with New Directions and Crossroads Recovery.",
        notes_es="Llame al 843-488-6200 para inscripción; se vincula con New Directions y Crossroads Recovery.",
        hours="Class schedules vary; call for current term",
        tags="horry|education|GED|ESL|grand-strand|reentry",
        services="GED preparation|English language classes|Career readiness|Testing referrals|Employer connections",
        county="Horry", served_counties="Horry|Georgetown", coverage="multi",
        _source="https://www.horrycountyschools.net", _source_type="government", _confidence="high",
    )
    add(
        name="SC Department of Alcohol and Other Drug Abuse Services (DAODAS)",
        category="state-agency", region="Statewide",
        description="The South Carolina Department of Alcohol and Other Drug Abuse Services oversees the statewide network of substance use prevention, treatment, and recovery providers licensed to serve justice-involved clients through courts, probation, and prison reentry referrals. DAODAS publishes treatment locators and funds county alcohol and drug abuse authorities connecting returning citizens to MAT, residential, and outpatient programs.",
        description_es="El Departamento de Servicios de Abuso de Alcohol y Otras Drogas de Carolina del Sur supervisa la red estatal de proveedores de prevención, tratamiento y recuperación autorizados para atender clientes con antecedentes penales a través de tribunales, probatoria y referencias de reinserción carcelaria.",
        address="1800 Main Street", city="Columbia", phone="803-896-5555", email="",
        website="https://daodas.sc.gov",
        eligibility="South Carolina residents seeking state-funded or licensed substance use treatment; justice referrals accepted through county authorities.",
        eligibility_es="Residentes de Carolina del Sur que busquen tratamiento estatal o autorizado de uso de sustancias; referencias de justicia aceptadas a través de autoridades del condado.",
        notes="Treatment locator at daodas.sc.gov; county alcohol and drug abuse authorities serve each region.",
        notes_es="Localizador de tratamiento en daodas.sc.gov; las autoridades de alcohol y drogas del condado sirven cada región.",
        hours="State office Monday–Friday business hours",
        tags="statewide|state-agency|substance-use|treatment|DAODAS|reentry",
        services="Treatment provider oversight|County authority referrals|Prevention programs|Recovery support coordination|Justice system liaison",
        county="Richland", served_counties="", coverage="statewide",
        _source="https://daodas.sc.gov", _source_type="government", _confidence="high",
    )
    add(
        name="SC Department of Health and Human Services — Healthy Connections",
        category="state-agency", region="Statewide",
        description="The South Carolina Department of Health and Human Services administers Medicaid (Healthy Connections), CHIP, and other public health coverage programs used by returning citizens enrolling in healthcare after release. SCDHHS coordinates with county DSS offices and hospital financial counselors on Medicaid eligibility, presumptive eligibility, and renewal—not emergency clinical care.",
        description_es="El Departamento de Salud y Servicios Humanos de Carolina del Sur administra Medicaid (Healthy Connections), CHIP y otros programas de cobertura de salud pública usados por ciudadanos que regresan al inscribirse en atención médica después de la liberación.",
        address="1801 Main Street", city="Columbia", phone="888-549-0820", email="",
        website="https://www.scdhhs.gov",
        eligibility="South Carolina residents meeting Medicaid and CHIP income and categorical requirements; criminal record generally not a barrier.",
        eligibility_es="Residentes de Carolina del Sur que cumplan requisitos de ingresos y categoría de Medicaid y CHIP; los antecedentes penales generalmente no son barrera.",
        notes="Apply through benefitsportal.dss.sc.gov or county DSS; member services 888-549-0820.",
        notes_es="Solicite en benefitsportal.dss.sc.gov o DSS del condado; servicios al miembro 888-549-0820.",
        hours="Online 24/7; call center Monday–Friday business hours",
        tags="statewide|state-agency|Medicaid|Healthy-Connections|healthcare|reentry",
        services="Medicaid enrollment|CHIP coverage|Member services|Presumptive eligibility guidance|Renewal assistance",
        county="Richland", served_counties="", coverage="statewide",
        _source="https://www.scdhhs.gov", _source_type="government", _confidence="high",
    )
    add(
        name="Greenville County Veterans Affairs Office",
        category="veterans", region="Greenville / Upstate",
        description="The Greenville County Veterans Affairs Office provides free VA benefits claims assistance, discharge document review, and referrals to veteran treatment courts and Upstate reentry partners for justice-involved veterans in Greenville, Pickens, and Laurens counties. County veterans service officers help returning veteran citizens navigate VA healthcare enrollment and disability compensation.",
        description_es="La Oficina de Asuntos de Veteranos del condado Greenville ofrece asistencia gratuita con reclamaciones de beneficios VA, revisión de documentos de baja y referencias a tribunales de tratamiento para veteranos para veteranos con antecedentes penales en los condados Greenville, Pickens y Laurens.",
        address="301 University Ridge", city="Greenville", phone="864-467-7060", email="",
        website="https://scdva.sc.gov",
        eligibility="Veterans and eligible dependents in Greenville County; service documentation required for VA claims.",
        eligibility_es="Veteranos y dependientes elegibles en el condado Greenville; se requiere documentación de servicio para reclamaciones VA.",
        notes="Call 864-467-7060 for appointment; free claims assistance; pairs with Miracle Hill veteran programs.",
        notes_es="Llame al 864-467-7060 para cita; asistencia gratuita con reclamaciones; se vincula con programas para veteranos de Miracle Hill.",
        hours="Monday–Friday business hours",
        tags="greenville|veterans|VA-benefits|upstate|reentry",
        services="VA benefits claims assistance|Discharge document review|Veteran treatment court referrals|Healthcare enrollment help|Disability compensation navigation",
        county="Greenville", served_counties="Greenville|Pickens|Laurens", coverage="multi",
        _source="https://scdva.sc.gov", _source_type="government", _confidence="high",
    )
    add(
        name="Charleston County Veterans Affairs Office",
        category="veterans", region="Charleston / Tri-County",
        description="The Charleston County Veterans Affairs Office provides free VA benefits claims assistance, discharge upgrade guidance, and referrals to Lowcountry veteran treatment resources for justice-involved veterans in Charleston, Berkeley, and Dorchester counties. County veterans service officers help returning veteran citizens navigate VA healthcare enrollment, disability compensation, and SSVF housing partners.",
        description_es="La Oficina de Asuntos de Veteranos del condado Charleston ofrece asistencia gratuita con reclamaciones de beneficios VA, orientación sobre actualización de baja y referencias a recursos de tratamiento para veteranos del Lowcountry para veteranos con antecedentes penales en los condados Charleston, Berkeley y Dorchester.",
        address="4367 Headquarters Road", city="North Charleston", phone="843-202-6464", email="",
        website="https://scdva.sc.gov",
        eligibility="Veterans and eligible dependents in Charleston County; service documentation required for VA claims.",
        eligibility_es="Veteranos y dependientes elegibles en el condado Charleston; se requiere documentación de servicio para reclamaciones VA.",
        notes="Call 843-202-6464 for appointment; free claims assistance; pairs with One80 Place SSVF and SC DVS.",
        notes_es="Llame al 843-202-6464 para cita; asistencia gratuita con reclamaciones; se vincula con SSVF de One80 Place y SC DVS.",
        hours="Monday–Friday business hours",
        tags="charleston|veterans|VA-benefits|lowcountry|reentry",
        services="VA benefits claims assistance|Discharge upgrade guidance|SSVF housing referrals|Healthcare enrollment help|Disability compensation navigation",
        county="Charleston", served_counties="Charleston|Berkeley|Dorchester", coverage="multi",
        _source="https://scdva.sc.gov", _source_type="government", _confidence="high",
    )
    add(
        name="Spartanburg County Veterans Affairs Office",
        category="veterans", region="Spartanburg / Upstate",
        description="The Spartanburg County Veterans Affairs Office provides free VA benefits claims assistance, discharge upgrade guidance, and referrals to veteran treatment courts and Upstate reentry partners for justice-involved veterans in Spartanburg and Cherokee counties. County veterans service officers help returning veteran citizens navigate VA healthcare enrollment and disability compensation after release from local jail or SCDC custody.",
        description_es="La Oficina de Asuntos de Veteranos del condado Spartanburg ofrece asistencia gratuita con reclamaciones de beneficios VA, orientación sobre actualización de baja y referencias a tribunales de tratamiento para veteranos para veteranos con antecedentes penales en los condados Spartanburg y Cherokee.",
        address="366 N. Church Street", city="Spartanburg", phone="864-596-3839", email="",
        website="https://scdva.sc.gov",
        eligibility="Veterans and eligible dependents in Spartanburg County; service documentation required for VA claims.",
        eligibility_es="Veteranos y dependientes elegibles en el condado Spartanburg; se requiere documentación de servicio para reclamaciones VA.",
        notes="Call 864-596-3839 for appointment; free claims assistance; pairs with ROAR Spartanburg and Miracle Hill veteran programs.",
        notes_es="Llame al 864-596-3839 para cita; asistencia gratuita con reclamaciones; se vincula con ROAR Spartanburg y programas para veteranos de Miracle Hill.",
        hours="Monday–Friday business hours",
        tags="spartanburg|veterans|VA-benefits|upstate|reentry",
        services="VA benefits claims assistance|Discharge upgrade guidance|Veteran treatment court referrals|Healthcare enrollment help|Disability compensation navigation",
        county="Spartanburg", served_counties="Spartanburg|Cherokee", coverage="multi",
        _source="https://scdva.sc.gov", _source_type="government", _confidence="high",
    )
