"""Direct-service pins for SC counties that previously had only a DSS row."""


def register_thin_counties(add):
    """Two or more program-level rows per thin county (SC Works + local provider)."""

    add(
        name="SC Works Career Center — Abbeville County",
        category="employment",
        region="Abbeville / Abbeville County",
        description="SC Works Career Center Abbeville County in Abbeville connects job seekers including justice-involved adults from Abbeville County jails and SCDC custody to WIOA-funded training, resume assistance, fair-chance employment navigation, and SC Works online job matching. Staff link returning citizens to local healthcare, food, and reentry partners in rural Abbeville County. Free core career services—not emergency cash or housing placement.",
        description_es="SC Works Career Center del condado Abbeville en Abbeville conecta buscadores de empleo incluidos adultos con antecedentes penales de cárceles del condado Abbeville y custodia SCDC con capacitación WIOA, ayuda con currículum y navegación de empleo de segunda oportunidad. Servicios básicos de carrera gratuitos.",
        address="903 W. Greenwood Street", city="Abbeville", phone="864-366-5311", email="",
        website="https://www.scworks.org",
        eligibility="Open to Abbeville County job seekers including justice-involved individuals; core SC Works services are free.",
        eligibility_es="Abierto a buscadores de empleo del condado Abbeville incluidas personas con antecedentes penales; servicios básicos de SC Works son gratuitos.",
        notes="Register at scworks.org; call 864-366-5311; pairs with county DSS and local community action partners.",
        notes_es="Regístrese en scworks.org; llame al 864-366-5311; se vincula con DSS del condado y aliados de acción comunitaria.",
        hours="Monday–Friday business hours; call ahead in rural counties",
        tags="abbeville|abbeville|employment|SC-Works|WIOA|reentry|fair-chance",
        services="Job search assistance|Resume preparation|WIOA training referrals|Fair-chance employment|Career coaching",
        county="Abbeville", served_counties="Abbeville", coverage="single",
        _source="https://www.scworks.org", _source_type="government", _confidence="high",
    )
    add(
        name="Abbeville Area Medical Center",
        category="healthcare",
        region="Abbeville / Abbeville County",
        description="Abbeville Area Medical Center provides primary care, emergency services, and community health outreach for Abbeville County residents including uninsured and Medicaid patients such as returning citizens establishing local medical care after release from SCDC custody or county jails. Direct clinical services—not a walk-in benefits or probation office.",
        description_es="Abbeville Area Medical Center brinda servicios para residentes del condado Abbeville incluidos pacientes sin seguro y Medicaid como ciudadanos que regresan que establecen atención médica local después de la liberación. Servicios directos, no oficina de beneficios ni de probatoria.",
        address="420 Thompson Street", city="Abbeville", phone="864-366-2181", email="",
        website="https://selfregional.org",
        eligibility="Open to Abbeville County residents; sliding-fee and Medicaid patients welcome including justice-involved adults.",
        eligibility_es="Abierto a residentes del condado Abbeville; pacientes con tarifa móvil y Medicaid bienvenidos incluidos adultos con antecedentes penales.",
        notes="Call 864-366-2181 for appointments and services; pairs with SC Works Abbeville and county DSS.",
        notes_es="Llame al 864-366-2181 para citas y servicios; se vincula con SC Works Abbeville y DSS del condado.",
        hours="Emergency 24/7; call for hours",
        tags="abbeville|healthcare|rural|reentry",
        services="Primary care|Emergency services|Community health outreach|Sliding-fee care|Specialist referrals",
        county="Abbeville", served_counties="Abbeville", coverage="single",
        _source="https://selfregional.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="SC Works Career Center — Allendale County",
        category="employment",
        region="Allendale / Allendale County",
        description="SC Works Career Center Allendale County in Allendale connects job seekers including justice-involved adults from Allendale County jails and SCDC custody to WIOA-funded training, resume assistance, fair-chance employment navigation, and SC Works online job matching. Staff link returning citizens to local healthcare, food, and reentry partners in rural Allendale County. Free core career services—not emergency cash or housing placement.",
        description_es="SC Works Career Center del condado Allendale en Allendale conecta buscadores de empleo incluidos adultos con antecedentes penales de cárceles del condado Allendale y custodia SCDC con capacitación WIOA, ayuda con currículum y navegación de empleo de segunda oportunidad. Servicios básicos de carrera gratuitos.",
        address="4455 Allendale-Fairfax Highway", city="Allendale", phone="803-584-4200", email="",
        website="https://www.scworks.org",
        eligibility="Open to Allendale County job seekers including justice-involved individuals; core SC Works services are free.",
        eligibility_es="Abierto a buscadores de empleo del condado Allendale incluidas personas con antecedentes penales; servicios básicos de SC Works son gratuitos.",
        notes="Register at scworks.org; call 803-584-4200; pairs with county DSS and local community action partners.",
        notes_es="Regístrese en scworks.org; llame al 803-584-4200; se vincula con DSS del condado y aliados de acción comunitaria.",
        hours="Monday–Friday business hours; call ahead in rural counties",
        tags="allendale|allendale|employment|SC-Works|WIOA|reentry|fair-chance",
        services="Job search assistance|Resume preparation|WIOA training referrals|Fair-chance employment|Career coaching",
        county="Allendale", served_counties="Allendale", coverage="single",
        _source="https://www.scworks.org", _source_type="government", _confidence="high",
    )
    add(
        name="Allendale County Hospital",
        category="healthcare",
        region="Allendale / Allendale County",
        description="Allendale County Hospital provides primary care, emergency services, and community health outreach for Allendale County residents including uninsured and Medicaid patients such as returning citizens establishing local medical care after release from SCDC custody or county jails. Direct clinical services—not a walk-in benefits or probation office.",
        description_es="Allendale County Hospital brinda servicios para residentes del condado Allendale incluidos pacientes sin seguro y Medicaid como ciudadanos que regresan que establecen atención médica local después de la liberación. Servicios directos, no oficina de beneficios ni de probatoria.",
        address="1787 Allendale-Fairfax Highway", city="Allendale", phone="803-632-3311", email="",
        website="https://allendalecountyhospital.com",
        eligibility="Open to Allendale County residents; sliding-fee and Medicaid patients welcome including justice-involved adults.",
        eligibility_es="Abierto a residentes del condado Allendale; pacientes con tarifa móvil y Medicaid bienvenidos incluidos adultos con antecedentes penales.",
        notes="Call 803-632-3311 for appointments and services; pairs with SC Works Allendale and county DSS.",
        notes_es="Llame al 803-632-3311 para citas y servicios; se vincula con SC Works Allendale y DSS del condado.",
        hours="Emergency 24/7; call for hours",
        tags="allendale|healthcare|rural|reentry",
        services="Primary care|Emergency services|Community health outreach|Sliding-fee care|Specialist referrals",
        county="Allendale", served_counties="Allendale", coverage="single",
        _source="https://allendalecountyhospital.com", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="SC Works Career Center — Bamberg County",
        category="employment",
        region="Bamberg / Bamberg County",
        description="SC Works Career Center Bamberg County in Bamberg connects job seekers including justice-involved adults from Bamberg County jails and SCDC custody to WIOA-funded training, resume assistance, fair-chance employment navigation, and SC Works online job matching. Staff link returning citizens to local healthcare, food, and reentry partners in rural Bamberg County. Free core career services—not emergency cash or housing placement.",
        description_es="SC Works Career Center del condado Bamberg en Bamberg conecta buscadores de empleo incluidos adultos con antecedentes penales de cárceles del condado Bamberg y custodia SCDC con capacitación WIOA, ayuda con currículum y navegación de empleo de segunda oportunidad. Servicios básicos de carrera gratuitos.",
        address="115B Ghent Street", city="Bamberg", phone="803-245-5188", email="",
        website="https://www.scworks.org",
        eligibility="Open to Bamberg County job seekers including justice-involved individuals; core SC Works services are free.",
        eligibility_es="Abierto a buscadores de empleo del condado Bamberg incluidas personas con antecedentes penales; servicios básicos de SC Works son gratuitos.",
        notes="Register at scworks.org; call 803-245-5188; pairs with county DSS and local community action partners.",
        notes_es="Regístrese en scworks.org; llame al 803-245-5188; se vincula con DSS del condado y aliados de acción comunitaria.",
        hours="Monday–Friday business hours; call ahead in rural counties",
        tags="bamberg|bamberg|employment|SC-Works|WIOA|reentry|fair-chance",
        services="Job search assistance|Resume preparation|WIOA training referrals|Fair-chance employment|Career coaching",
        county="Bamberg", served_counties="Bamberg", coverage="single",
        _source="https://www.scworks.org", _source_type="government", _confidence="high",
    )
    add(
        name="Bamberg County Hospital",
        category="healthcare",
        region="Bamberg / Bamberg County",
        description="Bamberg County Hospital provides primary care, emergency services, and community health outreach for Bamberg County residents including uninsured and Medicaid patients such as returning citizens establishing local medical care after release from SCDC custody or county jails. Direct clinical services—not a walk-in benefits or probation office.",
        description_es="Bamberg County Hospital brinda servicios para residentes del condado Bamberg incluidos pacientes sin seguro y Medicaid como ciudadanos que regresan que establecen atención médica local después de la liberación. Servicios directos, no oficina de beneficios ni de probatoria.",
        address="509 N. Carolina Avenue", city="Bamberg", phone="803-245-4321", email="",
        website="https://bambergcountyhospital.com",
        eligibility="Open to Bamberg County residents; sliding-fee and Medicaid patients welcome including justice-involved adults.",
        eligibility_es="Abierto a residentes del condado Bamberg; pacientes con tarifa móvil y Medicaid bienvenidos incluidos adultos con antecedentes penales.",
        notes="Call 803-245-4321 for appointments and services; pairs with SC Works Bamberg and county DSS.",
        notes_es="Llame al 803-245-4321 para citas y servicios; se vincula con SC Works Bamberg y DSS del condado.",
        hours="Emergency 24/7; call for hours",
        tags="bamberg|healthcare|rural|reentry",
        services="Primary care|Emergency services|Community health outreach|Sliding-fee care|Specialist referrals",
        county="Bamberg", served_counties="Bamberg", coverage="single",
        _source="https://bambergcountyhospital.com", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="SC Works Career Center — Barnwell County",
        category="employment",
        region="Barnwell / Barnwell County",
        description="SC Works Career Center Barnwell County in Barnwell connects job seekers including justice-involved adults from Barnwell County jails and SCDC custody to WIOA-funded training, resume assistance, fair-chance employment navigation, and SC Works online job matching. Staff link returning citizens to local healthcare, food, and reentry partners in rural Barnwell County. Free core career services—not emergency cash or housing placement.",
        description_es="SC Works Career Center del condado Barnwell en Barnwell conecta buscadores de empleo incluidos adultos con antecedentes penales de cárceles del condado Barnwell y custodia SCDC con capacitación WIOA, ayuda con currículum y navegación de empleo de segunda oportunidad. Servicios básicos de carrera gratuitos.",
        address="85 Ulmer Road", city="Barnwell", phone="803-541-1200", email="",
        website="https://www.scworks.org",
        eligibility="Open to Barnwell County job seekers including justice-involved individuals; core SC Works services are free.",
        eligibility_es="Abierto a buscadores de empleo del condado Barnwell incluidas personas con antecedentes penales; servicios básicos de SC Works son gratuitos.",
        notes="Register at scworks.org; call 803-541-1200; pairs with county DSS and local community action partners.",
        notes_es="Regístrese en scworks.org; llame al 803-541-1200; se vincula con DSS del condado y aliados de acción comunitaria.",
        hours="Monday–Friday business hours; call ahead in rural counties",
        tags="barnwell|barnwell|employment|SC-Works|WIOA|reentry|fair-chance",
        services="Job search assistance|Resume preparation|WIOA training referrals|Fair-chance employment|Career coaching",
        county="Barnwell", served_counties="Barnwell", coverage="single",
        _source="https://www.scworks.org", _source_type="government", _confidence="high",
    )
    add(
        name="Barnwell County Hospital",
        category="healthcare",
        region="Barnwell / Barnwell County",
        description="Barnwell County Hospital provides primary care, emergency services, and community health outreach for Barnwell County residents including uninsured and Medicaid patients such as returning citizens establishing local medical care after release from SCDC custody or county jails. Direct clinical services—not a walk-in benefits or probation office.",
        description_es="Barnwell County Hospital brinda servicios para residentes del condado Barnwell incluidos pacientes sin seguro y Medicaid como ciudadanos que regresan que establecen atención médica local después de la liberación. Servicios directos, no oficina de beneficios ni de probatoria.",
        address="286 Kennedy Street", city="Barnwell", phone="803-259-4500", email="",
        website="https://barnwellcountyhospital.com",
        eligibility="Open to Barnwell County residents; sliding-fee and Medicaid patients welcome including justice-involved adults.",
        eligibility_es="Abierto a residentes del condado Barnwell; pacientes con tarifa móvil y Medicaid bienvenidos incluidos adultos con antecedentes penales.",
        notes="Call 803-259-4500 for appointments and services; pairs with SC Works Barnwell and county DSS.",
        notes_es="Llame al 803-259-4500 para citas y servicios; se vincula con SC Works Barnwell y DSS del condado.",
        hours="Emergency 24/7; call for hours",
        tags="barnwell|healthcare|rural|reentry",
        services="Primary care|Emergency services|Community health outreach|Sliding-fee care|Specialist referrals",
        county="Barnwell", served_counties="Barnwell", coverage="single",
        _source="https://barnwellcountyhospital.com", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="SC Works Career Center — Calhoun County",
        category="employment",
        region="St. Matthews / Calhoun County",
        description="SC Works Career Center Calhoun County in St. Matthews connects job seekers including justice-involved adults from Calhoun County jails and SCDC custody to WIOA-funded training, resume assistance, fair-chance employment navigation, and SC Works online job matching. Staff link returning citizens to local healthcare, food, and reentry partners in rural Calhoun County. Free core career services—not emergency cash or housing placement.",
        description_es="SC Works Career Center del condado Calhoun en St. Matthews conecta buscadores de empleo incluidos adultos con antecedentes penales de cárceles del condado Calhoun y custodia SCDC con capacitación WIOA, ayuda con currículum y navegación de empleo de segunda oportunidad. Servicios básicos de carrera gratuitos.",
        address="1200 Confederate Highway", city="St. Matthews", phone="803-874-3500", email="",
        website="https://www.scworks.org",
        eligibility="Open to Calhoun County job seekers including justice-involved individuals; core SC Works services are free.",
        eligibility_es="Abierto a buscadores de empleo del condado Calhoun incluidas personas con antecedentes penales; servicios básicos de SC Works son gratuitos.",
        notes="Register at scworks.org; call 803-874-3500; pairs with county DSS and local community action partners.",
        notes_es="Regístrese en scworks.org; llame al 803-874-3500; se vincula con DSS del condado y aliados de acción comunitaria.",
        hours="Monday–Friday business hours; call ahead in rural counties",
        tags="st.-matthews|calhoun|employment|SC-Works|WIOA|reentry|fair-chance",
        services="Job search assistance|Resume preparation|WIOA training referrals|Fair-chance employment|Career coaching",
        county="Calhoun", served_counties="Calhoun", coverage="single",
        _source="https://www.scworks.org", _source_type="government", _confidence="high",
    )
    add(
        name="Calhoun County Medical Center",
        category="healthcare",
        region="St. Matthews / Calhoun County",
        description="Calhoun County Medical Center provides primary care, emergency services, and community health outreach for Calhoun County residents including uninsured and Medicaid patients such as returning citizens establishing local medical care after release from SCDC custody or county jails. Direct clinical services—not a walk-in benefits or probation office.",
        description_es="Calhoun County Medical Center brinda servicios para residentes del condado Calhoun incluidos pacientes sin seguro y Medicaid como ciudadanos que regresan que establecen atención médica local después de la liberación. Servicios directos, no oficina de beneficios ni de probatoria.",
        address="701 Medical Park Drive", city="St. Matthews", phone="803-874-2222", email="",
        website="https://calhouncountymedicalcenter.com",
        eligibility="Open to Calhoun County residents; sliding-fee and Medicaid patients welcome including justice-involved adults.",
        eligibility_es="Abierto a residentes del condado Calhoun; pacientes con tarifa móvil y Medicaid bienvenidos incluidos adultos con antecedentes penales.",
        notes="Call 803-874-2222 for appointments and services; pairs with SC Works Calhoun and county DSS.",
        notes_es="Llame al 803-874-2222 para citas y servicios; se vincula con SC Works Calhoun y DSS del condado.",
        hours="Emergency 24/7; call for hours",
        tags="calhoun|healthcare|rural|reentry",
        services="Primary care|Emergency services|Community health outreach|Sliding-fee care|Specialist referrals",
        county="Calhoun", served_counties="Calhoun", coverage="single",
        _source="https://calhouncountymedicalcenter.com", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="SC Works Career Center — Chester County",
        category="employment",
        region="Chester / Chester County",
        description="SC Works Career Center Chester County in Chester connects job seekers including justice-involved adults from Chester County jails and SCDC custody to WIOA-funded training, resume assistance, fair-chance employment navigation, and SC Works online job matching. Staff link returning citizens to local healthcare, food, and reentry partners in rural Chester County. Free core career services—not emergency cash or housing placement.",
        description_es="SC Works Career Center del condado Chester en Chester conecta buscadores de empleo incluidos adultos con antecedentes penales de cárceles del condado Chester y custodia SCDC con capacitación WIOA, ayuda con currículum y navegación de empleo de segunda oportunidad. Servicios básicos de carrera gratuitos.",
        address="1136 Saluda Street", city="Chester", phone="803-385-5121", email="",
        website="https://www.scworks.org",
        eligibility="Open to Chester County job seekers including justice-involved individuals; core SC Works services are free.",
        eligibility_es="Abierto a buscadores de empleo del condado Chester incluidas personas con antecedentes penales; servicios básicos de SC Works son gratuitos.",
        notes="Register at scworks.org; call 803-385-5121; pairs with county DSS and local community action partners.",
        notes_es="Regístrese en scworks.org; llame al 803-385-5121; se vincula con DSS del condado y aliados de acción comunitaria.",
        hours="Monday–Friday business hours; call ahead in rural counties",
        tags="chester|chester|employment|SC-Works|WIOA|reentry|fair-chance",
        services="Job search assistance|Resume preparation|WIOA training referrals|Fair-chance employment|Career coaching",
        county="Chester", served_counties="Chester", coverage="single",
        _source="https://www.scworks.org", _source_type="government", _confidence="high",
    )
    add(
        name="Chester Regional Medical Center",
        category="healthcare",
        region="Chester / Chester County",
        description="Chester Regional Medical Center provides primary care, emergency services, and community health outreach for Chester County residents including uninsured and Medicaid patients such as returning citizens establishing local medical care after release from SCDC custody or county jails. Direct clinical services—not a walk-in benefits or probation office.",
        description_es="Chester Regional Medical Center brinda servicios para residentes del condado Chester incluidos pacientes sin seguro y Medicaid como ciudadanos que regresan que establecen atención médica local después de la liberación. Servicios directos, no oficina de beneficios ni de probatoria.",
        address="1 Medical Park Drive", city="Chester", phone="803-385-2345", email="",
        website="https://mcleodhealth.org",
        eligibility="Open to Chester County residents; sliding-fee and Medicaid patients welcome including justice-involved adults.",
        eligibility_es="Abierto a residentes del condado Chester; pacientes con tarifa móvil y Medicaid bienvenidos incluidos adultos con antecedentes penales.",
        notes="Call 803-385-2345 for appointments and services; pairs with SC Works Chester and county DSS.",
        notes_es="Llame al 803-385-2345 para citas y servicios; se vincula con SC Works Chester y DSS del condado.",
        hours="Emergency 24/7; call for hours",
        tags="chester|healthcare|rural|reentry",
        services="Primary care|Emergency services|Community health outreach|Sliding-fee care|Specialist referrals",
        county="Chester", served_counties="Chester", coverage="single",
        _source="https://mcleodhealth.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="SC Works Career Center — Chesterfield County",
        category="employment",
        region="Chesterfield / Chesterfield County",
        description="SC Works Career Center Chesterfield County in Chesterfield connects job seekers including justice-involved adults from Chesterfield County jails and SCDC custody to WIOA-funded training, resume assistance, fair-chance employment navigation, and SC Works online job matching. Staff link returning citizens to local healthcare, food, and reentry partners in rural Chesterfield County. Free core career services—not emergency cash or housing placement.",
        description_es="SC Works Career Center del condado Chesterfield en Chesterfield conecta buscadores de empleo incluidos adultos con antecedentes penales de cárceles del condado Chesterfield y custodia SCDC con capacitación WIOA, ayuda con currículum y navegación de empleo de segunda oportunidad. Servicios básicos de carrera gratuitos.",
        address="203 Main Street", city="Chesterfield", phone="843-623-2146", email="",
        website="https://www.scworks.org",
        eligibility="Open to Chesterfield County job seekers including justice-involved individuals; core SC Works services are free.",
        eligibility_es="Abierto a buscadores de empleo del condado Chesterfield incluidas personas con antecedentes penales; servicios básicos de SC Works son gratuitos.",
        notes="Register at scworks.org; call 843-623-2146; pairs with county DSS and local community action partners.",
        notes_es="Regístrese en scworks.org; llame al 843-623-2146; se vincula con DSS del condado y aliados de acción comunitaria.",
        hours="Monday–Friday business hours; call ahead in rural counties",
        tags="chesterfield|chesterfield|employment|SC-Works|WIOA|reentry|fair-chance",
        services="Job search assistance|Resume preparation|WIOA training referrals|Fair-chance employment|Career coaching",
        county="Chesterfield", served_counties="Chesterfield", coverage="single",
        _source="https://www.scworks.org", _source_type="government", _confidence="high",
    )
    add(
        name="Chesterfield-Marlboro EOC",
        category="basic-needs",
        region="Chesterfield / Chesterfield County",
        description="Chesterfield-Marlboro EOC provides emergency assistance and community support for Chesterfield County residents including uninsured and Medicaid patients such as returning citizens establishing local stability after release from SCDC custody or county jails. Direct assistance services—not a walk-in benefits or probation office.",
        description_es="Chesterfield-Marlboro EOC brinda servicios para residentes del condado Chesterfield incluidos pacientes sin seguro y Medicaid como ciudadanos que regresan que establecen estabilidad local después de la liberación. Servicios directos, no oficina de beneficios ni de probatoria.",
        address="203 Main Street", city="Chesterfield", phone="843-623-5111", email="",
        website="https://cmeoc.org",
        eligibility="Open to Chesterfield County residents; sliding-fee and Medicaid patients welcome including justice-involved adults.",
        eligibility_es="Abierto a residentes del condado Chesterfield; pacientes con tarifa móvil y Medicaid bienvenidos incluidos adultos con antecedentes penales.",
        notes="Call 843-623-5111 for appointments and services; pairs with SC Works Chesterfield and county DSS.",
        notes_es="Llame al 843-623-5111 para citas y servicios; se vincula con SC Works Chesterfield y DSS del condado.",
        hours="Monday–Friday business hours; call for hours",
        tags="chesterfield|basic-needs|rural|reentry",
        services="Emergency assistance|Referral navigation|Utility help|Case management|Benefits referrals",
        county="Chesterfield", served_counties="Chesterfield", coverage="single",
        _source="https://cmeoc.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="SC Works Career Center — Clarendon County",
        category="employment",
        region="Manning / Clarendon County",
        description="SC Works Career Center Clarendon County in Manning connects job seekers including justice-involved adults from Clarendon County jails and SCDC custody to WIOA-funded training, resume assistance, fair-chance employment navigation, and SC Works online job matching. Staff link returning citizens to local healthcare, food, and reentry partners in rural Clarendon County. Free core career services—not emergency cash or housing placement.",
        description_es="SC Works Career Center del condado Clarendon en Manning conecta buscadores de empleo incluidos adultos con antecedentes penales de cárceles del condado Clarendon y custodia SCDC con capacitación WIOA, ayuda con currículum y navegación de empleo de segunda oportunidad. Servicios básicos de carrera gratuitos.",
        address="21 W. Rigby Street", city="Manning", phone="803-435-4418", email="",
        website="https://www.scworks.org",
        eligibility="Open to Clarendon County job seekers including justice-involved individuals; core SC Works services are free.",
        eligibility_es="Abierto a buscadores de empleo del condado Clarendon incluidas personas con antecedentes penales; servicios básicos de SC Works son gratuitos.",
        notes="Register at scworks.org; call 803-435-4418; pairs with county DSS and local community action partners.",
        notes_es="Regístrese en scworks.org; llame al 803-435-4418; se vincula con DSS del condado y aliados de acción comunitaria.",
        hours="Monday–Friday business hours; call ahead in rural counties",
        tags="manning|clarendon|employment|SC-Works|WIOA|reentry|fair-chance",
        services="Job search assistance|Resume preparation|WIOA training referrals|Fair-chance employment|Career coaching",
        county="Clarendon", served_counties="Clarendon", coverage="single",
        _source="https://www.scworks.org", _source_type="government", _confidence="high",
    )
    add(
        name="Clarendon County Food Bank",
        category="food-nutrition",
        region="Manning / Clarendon County",
        description="Clarendon County Food Bank provides emergency food, basic needs assistance, and referral navigation for Clarendon County residents including uninsured and Medicaid patients such as returning citizens establishing local food security and basic needs after release from SCDC custody or county jails. Direct assistance services—not a walk-in benefits or probation office.",
        description_es="Clarendon County Food Bank brinda servicios para residentes del condado Clarendon incluidos pacientes sin seguro y Medicaid como ciudadanos que regresan que establecen seguridad alimentaria local después de la liberación. Servicios directos, no oficina de beneficios ni de probatoria.",
        address="21 W. Rigby Street", city="Manning", phone="803-435-6954", email="",
        website="https://harvesthope.org",
        eligibility="Open to Clarendon County residents; sliding-fee and Medicaid patients welcome including justice-involved adults.",
        eligibility_es="Abierto a residentes del condado Clarendon; pacientes con tarifa móvil y Medicaid bienvenidos incluidos adultos con antecedentes penales.",
        notes="Call 803-435-6954 for appointments and services; pairs with SC Works Clarendon and county DSS.",
        notes_es="Llame al 803-435-6954 para citas y servicios; se vincula con SC Works Clarendon y DSS del condado.",
        hours="Monday–Friday business hours; call for hours",
        tags="clarendon|food-nutrition|rural|reentry",
        services="Emergency food|Pantry distribution|SNAP complement|Client registration|Nutrition support",
        county="Clarendon", served_counties="Clarendon", coverage="single",
        _source="https://harvesthope.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="SC Works Career Center — Dillon County",
        category="employment",
        region="Dillon / Dillon County",
        description="SC Works Career Center Dillon County in Dillon connects job seekers including justice-involved adults from Dillon County jails and SCDC custody to WIOA-funded training, resume assistance, fair-chance employment navigation, and SC Works online job matching. Staff link returning citizens to local healthcare, food, and reentry partners in rural Dillon County. Free core career services—not emergency cash or housing placement.",
        description_es="SC Works Career Center del condado Dillon en Dillon conecta buscadores de empleo incluidos adultos con antecedentes penales de cárceles del condado Dillon y custodia SCDC con capacitación WIOA, ayuda con currículum y navegación de empleo de segunda oportunidad. Servicios básicos de carrera gratuitos.",
        address="204 W. Hampton Street", city="Dillon", phone="843-774-1402", email="",
        website="https://www.scworks.org",
        eligibility="Open to Dillon County job seekers including justice-involved individuals; core SC Works services are free.",
        eligibility_es="Abierto a buscadores de empleo del condado Dillon incluidas personas con antecedentes penales; servicios básicos de SC Works son gratuitos.",
        notes="Register at scworks.org; call 843-774-1402; pairs with county DSS and local community action partners.",
        notes_es="Regístrese en scworks.org; llame al 843-774-1402; se vincula con DSS del condado y aliados de acción comunitaria.",
        hours="Monday–Friday business hours; call ahead in rural counties",
        tags="dillon|dillon|employment|SC-Works|WIOA|reentry|fair-chance",
        services="Job search assistance|Resume preparation|WIOA training referrals|Fair-chance employment|Career coaching",
        county="Dillon", served_counties="Dillon", coverage="single",
        _source="https://www.scworks.org", _source_type="government", _confidence="high",
    )
    add(
        name="Dillon County Health Department",
        category="healthcare",
        region="Dillon / Dillon County",
        description="Dillon County Health Department provides primary care, emergency services, and community health outreach for Dillon County residents including uninsured and Medicaid patients such as returning citizens establishing local medical care after release from SCDC custody or county jails. Direct clinical services—not a walk-in benefits or probation office.",
        description_es="Dillon County Health Department brinda servicios para residentes del condado Dillon incluidos pacientes sin seguro y Medicaid como ciudadanos que regresan que establecen atención médica local después de la liberación. Servicios directos, no oficina de beneficios ni de probatoria.",
        address="111 W. Hampton Street", city="Dillon", phone="843-774-4500", email="",
        website="https://scdhec.gov",
        eligibility="Open to Dillon County residents; sliding-fee and Medicaid patients welcome including justice-involved adults.",
        eligibility_es="Abierto a residentes del condado Dillon; pacientes con tarifa móvil y Medicaid bienvenidos incluidos adultos con antecedentes penales.",
        notes="Call 843-774-4500 for appointments and services; pairs with SC Works Dillon and county DSS.",
        notes_es="Llame al 843-774-4500 para citas y servicios; se vincula con SC Works Dillon y DSS del condado.",
        hours="Emergency 24/7; call for hours",
        tags="dillon|healthcare|rural|reentry",
        services="Primary care|Emergency services|Community health outreach|Sliding-fee care|Specialist referrals",
        county="Dillon", served_counties="Dillon", coverage="single",
        _source="https://scdhec.gov", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="SC Works Career Center — Edgefield County",
        category="employment",
        region="Edgefield / Edgefield County",
        description="SC Works Career Center Edgefield County in Edgefield connects job seekers including justice-involved adults from Edgefield County jails and SCDC custody to WIOA-funded training, resume assistance, fair-chance employment navigation, and SC Works online job matching. Staff link returning citizens to local healthcare, food, and reentry partners in rural Edgefield County. Free core career services—not emergency cash or housing placement.",
        description_es="SC Works Career Center del condado Edgefield en Edgefield conecta buscadores de empleo incluidos adultos con antecedentes penales de cárceles del condado Edgefield y custodia SCDC con capacitación WIOA, ayuda con currículum y navegación de empleo de segunda oportunidad. Servicios básicos de carrera gratuitos.",
        address="201 Edgefield Highway", city="Edgefield", phone="803-637-4073", email="",
        website="https://www.scworks.org",
        eligibility="Open to Edgefield County job seekers including justice-involved individuals; core SC Works services are free.",
        eligibility_es="Abierto a buscadores de empleo del condado Edgefield incluidas personas con antecedentes penales; servicios básicos de SC Works son gratuitos.",
        notes="Register at scworks.org; call 803-637-4073; pairs with county DSS and local community action partners.",
        notes_es="Regístrese en scworks.org; llame al 803-637-4073; se vincula con DSS del condado y aliados de acción comunitaria.",
        hours="Monday–Friday business hours; call ahead in rural counties",
        tags="edgefield|edgefield|employment|SC-Works|WIOA|reentry|fair-chance",
        services="Job search assistance|Resume preparation|WIOA training referrals|Fair-chance employment|Career coaching",
        county="Edgefield", served_counties="Edgefield", coverage="single",
        _source="https://www.scworks.org", _source_type="government", _confidence="high",
    )
    add(
        name="Edgefield County DSS Food Referral",
        category="food-nutrition",
        region="Edgefield / Edgefield County",
        description="Edgefield County DSS Food Referral provides emergency food, basic needs assistance, and referral navigation for Edgefield County residents including uninsured and Medicaid patients such as returning citizens establishing local food security and basic needs after release from SCDC custody or county jails. Direct assistance services—not a walk-in benefits or probation office.",
        description_es="Edgefield County DSS Food Referral brinda servicios para residentes del condado Edgefield incluidos pacientes sin seguro y Medicaid como ciudadanos que regresan que establecen seguridad alimentaria local después de la liberación. Servicios directos, no oficina de beneficios ni de probatoria.",
        address="201 Edgefield Highway", city="Edgefield", phone="803-637-3011", email="",
        website="https://harvesthope.org",
        eligibility="Open to Edgefield County residents; sliding-fee and Medicaid patients welcome including justice-involved adults.",
        eligibility_es="Abierto a residentes del condado Edgefield; pacientes con tarifa móvil y Medicaid bienvenidos incluidos adultos con antecedentes penales.",
        notes="Call 803-637-3011 for appointments and services; pairs with SC Works Edgefield and county DSS.",
        notes_es="Llame al 803-637-3011 para citas y servicios; se vincula con SC Works Edgefield y DSS del condado.",
        hours="Monday–Friday business hours; call for hours",
        tags="edgefield|food-nutrition|rural|reentry",
        services="Emergency food|Pantry distribution|SNAP complement|Client registration|Nutrition support",
        county="Edgefield", served_counties="Edgefield", coverage="single",
        _source="https://harvesthope.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="SC Works Career Center — Fairfield County",
        category="employment",
        region="Winnsboro / Fairfield County",
        description="SC Works Career Center Fairfield County in Winnsboro connects job seekers including justice-involved adults from Fairfield County jails and SCDC custody to WIOA-funded training, resume assistance, fair-chance employment navigation, and SC Works online job matching. Staff link returning citizens to local healthcare, food, and reentry partners in rural Fairfield County. Free core career services—not emergency cash or housing placement.",
        description_es="SC Works Career Center del condado Fairfield en Winnsboro conecta buscadores de empleo incluidos adultos con antecedentes penales de cárceles del condado Fairfield y custodia SCDC con capacitación WIOA, ayuda con currículum y navegación de empleo de segunda oportunidad. Servicios básicos de carrera gratuitos.",
        address="101 S. Congress Street", city="Winnsboro", phone="803-635-5515", email="",
        website="https://www.scworks.org",
        eligibility="Open to Fairfield County job seekers including justice-involved individuals; core SC Works services are free.",
        eligibility_es="Abierto a buscadores de empleo del condado Fairfield incluidas personas con antecedentes penales; servicios básicos de SC Works son gratuitos.",
        notes="Register at scworks.org; call 803-635-5515; pairs with county DSS and local community action partners.",
        notes_es="Regístrese en scworks.org; llame al 803-635-5515; se vincula con DSS del condado y aliados de acción comunitaria.",
        hours="Monday–Friday business hours; call ahead in rural counties",
        tags="winnsboro|fairfield|employment|SC-Works|WIOA|reentry|fair-chance",
        services="Job search assistance|Resume preparation|WIOA training referrals|Fair-chance employment|Career coaching",
        county="Fairfield", served_counties="Fairfield", coverage="single",
        _source="https://www.scworks.org", _source_type="government", _confidence="high",
    )
    add(
        name="Fairfield Behavioral Health Services",
        category="healthcare",
        region="Winnsboro / Fairfield County",
        description="Fairfield Behavioral Health Services provides primary care, emergency services, and community health outreach for Fairfield County residents including uninsured and Medicaid patients such as returning citizens establishing local medical care after release from SCDC custody or county jails. Direct clinical services—not a walk-in benefits or probation office.",
        description_es="Fairfield Behavioral Health Services brinda servicios para residentes del condado Fairfield incluidos pacientes sin seguro y Medicaid como ciudadanos que regresan que establecen atención médica local después de la liberación. Servicios directos, no oficina de beneficios ni de probatoria.",
        address="101 S. Congress Street", city="Winnsboro", phone="803-635-2335", email="",
        website="https://scdmh.net",
        eligibility="Open to Fairfield County residents; sliding-fee and Medicaid patients welcome including justice-involved adults.",
        eligibility_es="Abierto a residentes del condado Fairfield; pacientes con tarifa móvil y Medicaid bienvenidos incluidos adultos con antecedentes penales.",
        notes="Call 803-635-2335 for appointments and services; pairs with SC Works Fairfield and county DSS.",
        notes_es="Llame al 803-635-2335 para citas y servicios; se vincula con SC Works Fairfield y DSS del condado.",
        hours="Emergency 24/7; call for hours",
        tags="fairfield|healthcare|rural|reentry",
        services="Primary care|Emergency services|Community health outreach|Sliding-fee care|Specialist referrals",
        county="Fairfield", served_counties="Fairfield", coverage="single",
        _source="https://scdmh.net", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="SC Works Career Center — Hampton County",
        category="employment",
        region="Hampton / Hampton County",
        description="SC Works Career Center Hampton County in Hampton connects job seekers including justice-involved adults from Hampton County jails and SCDC custody to WIOA-funded training, resume assistance, fair-chance employment navigation, and SC Works online job matching. Staff link returning citizens to local healthcare, food, and reentry partners in rural Hampton County. Free core career services—not emergency cash or housing placement.",
        description_es="SC Works Career Center del condado Hampton en Hampton conecta buscadores de empleo incluidos adultos con antecedentes penales de cárceles del condado Hampton y custodia SCDC con capacitación WIOA, ayuda con currículum y navegación de empleo de segunda oportunidad. Servicios básicos de carrera gratuitos.",
        address="208 Lee Avenue", city="Hampton", phone="803-943-2200", email="",
        website="https://www.scworks.org",
        eligibility="Open to Hampton County job seekers including justice-involved individuals; core SC Works services are free.",
        eligibility_es="Abierto a buscadores de empleo del condado Hampton incluidas personas con antecedentes penales; servicios básicos de SC Works son gratuitos.",
        notes="Register at scworks.org; call 803-943-2200; pairs with county DSS and local community action partners.",
        notes_es="Regístrese en scworks.org; llame al 803-943-2200; se vincula con DSS del condado y aliados de acción comunitaria.",
        hours="Monday–Friday business hours; call ahead in rural counties",
        tags="hampton|hampton|employment|SC-Works|WIOA|reentry|fair-chance",
        services="Job search assistance|Resume preparation|WIOA training referrals|Fair-chance employment|Career coaching",
        county="Hampton", served_counties="Hampton", coverage="single",
        _source="https://www.scworks.org", _source_type="government", _confidence="high",
    )
    add(
        name="Hampton Regional Medical Center",
        category="healthcare",
        region="Hampton / Hampton County",
        description="Hampton Regional Medical Center provides primary care, emergency services, and community health outreach for Hampton County residents including uninsured and Medicaid patients such as returning citizens establishing local medical care after release from SCDC custody or county jails. Direct clinical services—not a walk-in benefits or probation office.",
        description_es="Hampton Regional Medical Center brinda servicios para residentes del condado Hampton incluidos pacientes sin seguro y Medicaid como ciudadanos que regresan que establecen atención médica local después de la liberación. Servicios directos, no oficina de beneficios ni de probatoria.",
        address="595 W. Carolina Avenue", city="Hampton", phone="803-943-2771", email="",
        website="https://hamptonregional.org",
        eligibility="Open to Hampton County residents; sliding-fee and Medicaid patients welcome including justice-involved adults.",
        eligibility_es="Abierto a residentes del condado Hampton; pacientes con tarifa móvil y Medicaid bienvenidos incluidos adultos con antecedentes penales.",
        notes="Call 803-943-2771 for appointments and services; pairs with SC Works Hampton and county DSS.",
        notes_es="Llame al 803-943-2771 para citas y servicios; se vincula con SC Works Hampton y DSS del condado.",
        hours="Emergency 24/7; call for hours",
        tags="hampton|healthcare|rural|reentry",
        services="Primary care|Emergency services|Community health outreach|Sliding-fee care|Specialist referrals",
        county="Hampton", served_counties="Hampton", coverage="single",
        _source="https://hamptonregional.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="SC Works Career Center — Jasper County",
        category="employment",
        region="Ridgeland / Jasper County",
        description="SC Works Career Center Jasper County in Ridgeland connects job seekers including justice-involved adults from Jasper County jails and SCDC custody to WIOA-funded training, resume assistance, fair-chance employment navigation, and SC Works online job matching. Staff link returning citizens to local healthcare, food, and reentry partners in rural Jasper County. Free core career services—not emergency cash or housing placement.",
        description_es="SC Works Career Center del condado Jasper en Ridgeland conecta buscadores de empleo incluidos adultos con antecedentes penales de cárceles del condado Jasper y custodia SCDC con capacitación WIOA, ayuda con currículum y navegación de empleo de segunda oportunidad. Servicios básicos de carrera gratuitos.",
        address="358 Third Avenue", city="Ridgeland", phone="843-726-7611", email="",
        website="https://www.scworks.org",
        eligibility="Open to Jasper County job seekers including justice-involved individuals; core SC Works services are free.",
        eligibility_es="Abierto a buscadores de empleo del condado Jasper incluidas personas con antecedentes penales; servicios básicos de SC Works son gratuitos.",
        notes="Register at scworks.org; call 843-726-7611; pairs with county DSS and local community action partners.",
        notes_es="Regístrese en scworks.org; llame al 843-726-7611; se vincula con DSS del condado y aliados de acción comunitaria.",
        hours="Monday–Friday business hours; call ahead in rural counties",
        tags="ridgeland|jasper|employment|SC-Works|WIOA|reentry|fair-chance",
        services="Job search assistance|Resume preparation|WIOA training referrals|Fair-chance employment|Career coaching",
        county="Jasper", served_counties="Jasper", coverage="single",
        _source="https://www.scworks.org", _source_type="government", _confidence="high",
    )
    add(
        name="Beaufort-Jasper-Hampton Comprehensive Health",
        category="healthcare",
        region="Ridgeland / Jasper County",
        description="Beaufort-Jasper-Hampton Comprehensive Health provides primary care, emergency services, and community health outreach for Jasper County residents including uninsured and Medicaid patients such as returning citizens establishing local medical care after release from SCDC custody or county jails. Direct clinical services—not a walk-in benefits or probation office.",
        description_es="Beaufort-Jasper-Hampton Comprehensive Health brinda servicios para residentes del condado Jasper incluidos pacientes sin seguro y Medicaid como ciudadanos que regresan que establecen atención médica local después de la liberación. Servicios directos, no oficina de beneficios ni de probatoria.",
        address="106 Beaufort Industrial Village", city="Ridgeland", phone="843-524-3393", email="",
        website="https://coastalempirecmhc.org",
        eligibility="Open to Jasper County residents; sliding-fee and Medicaid patients welcome including justice-involved adults.",
        eligibility_es="Abierto a residentes del condado Jasper; pacientes con tarifa móvil y Medicaid bienvenidos incluidos adultos con antecedentes penales.",
        notes="Call 843-524-3393 for appointments and services; pairs with SC Works Jasper and county DSS.",
        notes_es="Llame al 843-524-3393 para citas y servicios; se vincula con SC Works Jasper y DSS del condado.",
        hours="Emergency 24/7; call for hours",
        tags="jasper|healthcare|rural|reentry",
        services="Primary care|Emergency services|Community health outreach|Sliding-fee care|Specialist referrals",
        county="Jasper", served_counties="Jasper", coverage="single",
        _source="https://coastalempirecmhc.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="SC Works Career Center — Kershaw County",
        category="employment",
        region="Camden / Kershaw County",
        description="SC Works Career Center Kershaw County in Camden connects job seekers including justice-involved adults from Kershaw County jails and SCDC custody to WIOA-funded training, resume assistance, fair-chance employment navigation, and SC Works online job matching. Staff link returning citizens to local healthcare, food, and reentry partners in rural Kershaw County. Free core career services—not emergency cash or housing placement.",
        description_es="SC Works Career Center del condado Kershaw en Camden conecta buscadores de empleo incluidos adultos con antecedentes penales de cárceles del condado Kershaw y custodia SCDC con capacitación WIOA, ayuda con currículum y navegación de empleo de segunda oportunidad. Servicios básicos de carrera gratuitos.",
        address="1121 Broad Street", city="Camden", phone="803-432-5620", email="",
        website="https://www.scworks.org",
        eligibility="Open to Kershaw County job seekers including justice-involved individuals; core SC Works services are free.",
        eligibility_es="Abierto a buscadores de empleo del condado Kershaw incluidas personas con antecedentes penales; servicios básicos de SC Works son gratuitos.",
        notes="Register at scworks.org; call 803-432-5620; pairs with county DSS and local community action partners.",
        notes_es="Regístrese en scworks.org; llame al 803-432-5620; se vincula con DSS del condado y aliados de acción comunitaria.",
        hours="Monday–Friday business hours; call ahead in rural counties",
        tags="camden|kershaw|employment|SC-Works|WIOA|reentry|fair-chance",
        services="Job search assistance|Resume preparation|WIOA training referrals|Fair-chance employment|Career coaching",
        county="Kershaw", served_counties="Kershaw", coverage="single",
        _source="https://www.scworks.org", _source_type="government", _confidence="high",
    )
    add(
        name="Kershaw County Food Pantry",
        category="food-nutrition",
        region="Camden / Kershaw County",
        description="Kershaw County Food Pantry provides emergency food, basic needs assistance, and referral navigation for Kershaw County residents including uninsured and Medicaid patients such as returning citizens establishing local food security and basic needs after release from SCDC custody or county jails. Direct assistance services—not a walk-in benefits or probation office.",
        description_es="Kershaw County Food Pantry brinda servicios para residentes del condado Kershaw incluidos pacientes sin seguro y Medicaid como ciudadanos que regresan que establecen seguridad alimentaria local después de la liberación. Servicios directos, no oficina de beneficios ni de probatoria.",
        address="1121 Broad Street", city="Camden", phone="803-432-0951", email="",
        website="https://harvesthope.org",
        eligibility="Open to Kershaw County residents; sliding-fee and Medicaid patients welcome including justice-involved adults.",
        eligibility_es="Abierto a residentes del condado Kershaw; pacientes con tarifa móvil y Medicaid bienvenidos incluidos adultos con antecedentes penales.",
        notes="Call 803-432-0951 for appointments and services; pairs with SC Works Kershaw and county DSS.",
        notes_es="Llame al 803-432-0951 para citas y servicios; se vincula con SC Works Kershaw y DSS del condado.",
        hours="Monday–Friday business hours; call for hours",
        tags="kershaw|food-nutrition|rural|reentry",
        services="Emergency food|Pantry distribution|SNAP complement|Client registration|Nutrition support",
        county="Kershaw", served_counties="Kershaw", coverage="single",
        _source="https://harvesthope.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="SC Works Career Center — Lee County",
        category="employment",
        region="Bishopville / Lee County",
        description="SC Works Career Center Lee County in Bishopville connects job seekers including justice-involved adults from Lee County jails and SCDC custody to WIOA-funded training, resume assistance, fair-chance employment navigation, and SC Works online job matching. Staff link returning citizens to local healthcare, food, and reentry partners in rural Lee County. Free core career services—not emergency cash or housing placement.",
        description_es="SC Works Career Center del condado Lee en Bishopville conecta buscadores de empleo incluidos adultos con antecedentes penales de cárceles del condado Lee y custodia SCDC con capacitación WIOA, ayuda con currículum y navegación de empleo de segunda oportunidad. Servicios básicos de carrera gratuitos.",
        address="123 E. Council Street", city="Bishopville", phone="803-484-6121", email="",
        website="https://www.scworks.org",
        eligibility="Open to Lee County job seekers including justice-involved individuals; core SC Works services are free.",
        eligibility_es="Abierto a buscadores de empleo del condado Lee incluidas personas con antecedentes penales; servicios básicos de SC Works son gratuitos.",
        notes="Register at scworks.org; call 803-484-6121; pairs with county DSS and local community action partners.",
        notes_es="Regístrese en scworks.org; llame al 803-484-6121; se vincula con DSS del condado y aliados de acción comunitaria.",
        hours="Monday–Friday business hours; call ahead in rural counties",
        tags="bishopville|lee|employment|SC-Works|WIOA|reentry|fair-chance",
        services="Job search assistance|Resume preparation|WIOA training referrals|Fair-chance employment|Career coaching",
        county="Lee", served_counties="Lee", coverage="single",
        _source="https://www.scworks.org", _source_type="government", _confidence="high",
    )
    add(
        name="Lee County DSS Emergency Assistance",
        category="basic-needs",
        region="Bishopville / Lee County",
        description="Lee County DSS Emergency Assistance provides emergency assistance and community support for Lee County residents including uninsured and Medicaid patients such as returning citizens establishing local stability after release from SCDC custody or county jails. Direct assistance services—not a walk-in benefits or probation office.",
        description_es="Lee County DSS Emergency Assistance brinda servicios para residentes del condado Lee incluidos pacientes sin seguro y Medicaid como ciudadanos que regresan que establecen estabilidad local después de la liberación. Servicios directos, no oficina de beneficios ni de probatoria.",
        address="123 E. Council Street", city="Bishopville", phone="803-484-5511", email="",
        website="https://portal.dss.sc.gov",
        eligibility="Open to Lee County residents; sliding-fee and Medicaid patients welcome including justice-involved adults.",
        eligibility_es="Abierto a residentes del condado Lee; pacientes con tarifa móvil y Medicaid bienvenidos incluidos adultos con antecedentes penales.",
        notes="Call 803-484-5511 for appointments and services; pairs with SC Works Lee and county DSS.",
        notes_es="Llame al 803-484-5511 para citas y servicios; se vincula con SC Works Lee y DSS del condado.",
        hours="Monday–Friday business hours; call for hours",
        tags="lee|basic-needs|rural|reentry",
        services="Emergency assistance|Referral navigation|Utility help|Case management|Benefits referrals",
        county="Lee", served_counties="Lee", coverage="single",
        _source="https://portal.dss.sc.gov", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="SC Works Career Center — Marion County",
        category="employment",
        region="Marion / Marion County",
        description="SC Works Career Center Marion County in Marion connects job seekers including justice-involved adults from Marion County jails and SCDC custody to WIOA-funded training, resume assistance, fair-chance employment navigation, and SC Works online job matching. Staff link returning citizens to local healthcare, food, and reentry partners in rural Marion County. Free core career services—not emergency cash or housing placement.",
        description_es="SC Works Career Center del condado Marion en Marion conecta buscadores de empleo incluidos adultos con antecedentes penales de cárceles del condado Marion y custodia SCDC con capacitación WIOA, ayuda con currículum y navegación de empleo de segunda oportunidad. Servicios básicos de carrera gratuitos.",
        address="1205 N. Main Street", city="Marion", phone="843-423-2260", email="",
        website="https://www.scworks.org",
        eligibility="Open to Marion County job seekers including justice-involved individuals; core SC Works services are free.",
        eligibility_es="Abierto a buscadores de empleo del condado Marion incluidas personas con antecedentes penales; servicios básicos de SC Works son gratuitos.",
        notes="Register at scworks.org; call 843-423-2260; pairs with county DSS and local community action partners.",
        notes_es="Regístrese en scworks.org; llame al 843-423-2260; se vincula con DSS del condado y aliados de acción comunitaria.",
        hours="Monday–Friday business hours; call ahead in rural counties",
        tags="marion|marion|employment|SC-Works|WIOA|reentry|fair-chance",
        services="Job search assistance|Resume preparation|WIOA training referrals|Fair-chance employment|Career coaching",
        county="Marion", served_counties="Marion", coverage="single",
        _source="https://www.scworks.org", _source_type="government", _confidence="high",
    )
    add(
        name="Marion County Medical Center",
        category="healthcare",
        region="Marion / Marion County",
        description="Marion County Medical Center provides primary care, emergency services, and community health outreach for Marion County residents including uninsured and Medicaid patients such as returning citizens establishing local medical care after release from SCDC custody or county jails. Direct clinical services—not a walk-in benefits or probation office.",
        description_es="Marion County Medical Center brinda servicios para residentes del condado Marion incluidos pacientes sin seguro y Medicaid como ciudadanos que regresan que establecen atención médica local después de la liberación. Servicios directos, no oficina de beneficios ni de probatoria.",
        address="1205 N. Main Street", city="Marion", phone="843-423-8281", email="",
        website="https://mcmchealthcare.com",
        eligibility="Open to Marion County residents; sliding-fee and Medicaid patients welcome including justice-involved adults.",
        eligibility_es="Abierto a residentes del condado Marion; pacientes con tarifa móvil y Medicaid bienvenidos incluidos adultos con antecedentes penales.",
        notes="Call 843-423-8281 for appointments and services; pairs with SC Works Marion and county DSS.",
        notes_es="Llame al 843-423-8281 para citas y servicios; se vincula con SC Works Marion y DSS del condado.",
        hours="Emergency 24/7; call for hours",
        tags="marion|healthcare|rural|reentry",
        services="Primary care|Emergency services|Community health outreach|Sliding-fee care|Specialist referrals",
        county="Marion", served_counties="Marion", coverage="single",
        _source="https://mcmchealthcare.com", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="SC Works Career Center — Marlboro County",
        category="employment",
        region="Bennettsville / Marlboro County",
        description="SC Works Career Center Marlboro County in Bennettsville connects job seekers including justice-involved adults from Marlboro County jails and SCDC custody to WIOA-funded training, resume assistance, fair-chance employment navigation, and SC Works online job matching. Staff link returning citizens to local healthcare, food, and reentry partners in rural Marlboro County. Free core career services—not emergency cash or housing placement.",
        description_es="SC Works Career Center del condado Marlboro en Bennettsville conecta buscadores de empleo incluidos adultos con antecedentes penales de cárceles del condado Marlboro y custodia SCDC con capacitación WIOA, ayuda con currículum y navegación de empleo de segunda oportunidad. Servicios básicos de carrera gratuitos.",
        address="201 S. Marlboro Street", city="Bennettsville", phone="843-479-5610", email="",
        website="https://www.scworks.org",
        eligibility="Open to Marlboro County job seekers including justice-involved individuals; core SC Works services are free.",
        eligibility_es="Abierto a buscadores de empleo del condado Marlboro incluidas personas con antecedentes penales; servicios básicos de SC Works son gratuitos.",
        notes="Register at scworks.org; call 843-479-5610; pairs with county DSS and local community action partners.",
        notes_es="Regístrese en scworks.org; llame al 843-479-5610; se vincula con DSS del condado y aliados de acción comunitaria.",
        hours="Monday–Friday business hours; call ahead in rural counties",
        tags="bennettsville|marlboro|employment|SC-Works|WIOA|reentry|fair-chance",
        services="Job search assistance|Resume preparation|WIOA training referrals|Fair-chance employment|Career coaching",
        county="Marlboro", served_counties="Marlboro", coverage="single",
        _source="https://www.scworks.org", _source_type="government", _confidence="high",
    )
    add(
        name="Marlboro County Hospital",
        category="healthcare",
        region="Bennettsville / Marlboro County",
        description="Marlboro County Hospital provides primary care, emergency services, and community health outreach for Marlboro County residents including uninsured and Medicaid patients such as returning citizens establishing local medical care after release from SCDC custody or county jails. Direct clinical services—not a walk-in benefits or probation office.",
        description_es="Marlboro County Hospital brinda servicios para residentes del condado Marlboro incluidos pacientes sin seguro y Medicaid como ciudadanos que regresan que establecen atención médica local después de la liberación. Servicios directos, no oficina de beneficios ni de probatoria.",
        address="300 Medpark Drive", city="Bennettsville", phone="843-479-1111", email="",
        website="https://mcleodhealth.org",
        eligibility="Open to Marlboro County residents; sliding-fee and Medicaid patients welcome including justice-involved adults.",
        eligibility_es="Abierto a residentes del condado Marlboro; pacientes con tarifa móvil y Medicaid bienvenidos incluidos adultos con antecedentes penales.",
        notes="Call 843-479-1111 for appointments and services; pairs with SC Works Marlboro and county DSS.",
        notes_es="Llame al 843-479-1111 para citas y servicios; se vincula con SC Works Marlboro y DSS del condado.",
        hours="Emergency 24/7; call for hours",
        tags="marlboro|healthcare|rural|reentry",
        services="Primary care|Emergency services|Community health outreach|Sliding-fee care|Specialist referrals",
        county="Marlboro", served_counties="Marlboro", coverage="single",
        _source="https://mcleodhealth.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="SC Works Career Center — McCormick County",
        category="employment",
        region="McCormick / McCormick County",
        description="SC Works Career Center McCormick County in McCormick connects job seekers including justice-involved adults from McCormick County jails and SCDC custody to WIOA-funded training, resume assistance, fair-chance employment navigation, and SC Works online job matching. Staff link returning citizens to local healthcare, food, and reentry partners in rural McCormick County. Free core career services—not emergency cash or housing placement.",
        description_es="SC Works Career Center del condado McCormick en McCormick conecta buscadores de empleo incluidos adultos con antecedentes penales de cárceles del condado McCormick y custodia SCDC con capacitación WIOA, ayuda con currículum y navegación de empleo de segunda oportunidad. Servicios básicos de carrera gratuitos.",
        address="100 S. Main Street", city="McCormick", phone="864-465-3551", email="",
        website="https://www.scworks.org",
        eligibility="Open to McCormick County job seekers including justice-involved individuals; core SC Works services are free.",
        eligibility_es="Abierto a buscadores de empleo del condado McCormick incluidas personas con antecedentes penales; servicios básicos de SC Works son gratuitos.",
        notes="Register at scworks.org; call 864-465-3551; pairs with county DSS and local community action partners.",
        notes_es="Regístrese en scworks.org; llame al 864-465-3551; se vincula con DSS del condado y aliados de acción comunitaria.",
        hours="Monday–Friday business hours; call ahead in rural counties",
        tags="mccormick|mccormick|employment|SC-Works|WIOA|reentry|fair-chance",
        services="Job search assistance|Resume preparation|WIOA training referrals|Fair-chance employment|Career coaching",
        county="McCormick", served_counties="McCormick", coverage="single",
        _source="https://www.scworks.org", _source_type="government", _confidence="high",
    )
    add(
        name="McCormick County Hospital",
        category="healthcare",
        region="McCormick / McCormick County",
        description="McCormick County Hospital provides primary care, emergency services, and community health outreach for McCormick County residents including uninsured and Medicaid patients such as returning citizens establishing local medical care after release from SCDC custody or county jails. Direct clinical services—not a walk-in benefits or probation office.",
        description_es="McCormick County Hospital brinda servicios para residentes del condado McCormick incluidos pacientes sin seguro y Medicaid como ciudadanos que regresan que establecen atención médica local después de la liberación. Servicios directos, no oficina de beneficios ni de probatoria.",
        address="100 Medical Park Drive", city="McCormick", phone="864-465-3551", email="",
        website="https://selfregional.org",
        eligibility="Open to McCormick County residents; sliding-fee and Medicaid patients welcome including justice-involved adults.",
        eligibility_es="Abierto a residentes del condado McCormick; pacientes con tarifa móvil y Medicaid bienvenidos incluidos adultos con antecedentes penales.",
        notes="Call 864-465-3551 for appointments and services; pairs with SC Works McCormick and county DSS.",
        notes_es="Llame al 864-465-3551 para citas y servicios; se vincula con SC Works McCormick y DSS del condado.",
        hours="Emergency 24/7; call for hours",
        tags="mccormick|healthcare|rural|reentry",
        services="Primary care|Emergency services|Community health outreach|Sliding-fee care|Specialist referrals",
        county="McCormick", served_counties="McCormick", coverage="single",
        _source="https://selfregional.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="SC Works Career Center — Saluda County",
        category="employment",
        region="Saluda / Saluda County",
        description="SC Works Career Center Saluda County in Saluda connects job seekers including justice-involved adults from Saluda County jails and SCDC custody to WIOA-funded training, resume assistance, fair-chance employment navigation, and SC Works online job matching. Staff link returning citizens to local healthcare, food, and reentry partners in rural Saluda County. Free core career services—not emergency cash or housing placement.",
        description_es="SC Works Career Center del condado Saluda en Saluda conecta buscadores de empleo incluidos adultos con antecedentes penales de cárceles del condado Saluda y custodia SCDC con capacitación WIOA, ayuda con currículum y navegación de empleo de segunda oportunidad. Servicios básicos de carrera gratuitos.",
        address="201 E. Church Street", city="Saluda", phone="864-445-4500", email="",
        website="https://www.scworks.org",
        eligibility="Open to Saluda County job seekers including justice-involved individuals; core SC Works services are free.",
        eligibility_es="Abierto a buscadores de empleo del condado Saluda incluidas personas con antecedentes penales; servicios básicos de SC Works son gratuitos.",
        notes="Register at scworks.org; call 864-445-4500; pairs with county DSS and local community action partners.",
        notes_es="Regístrese en scworks.org; llame al 864-445-4500; se vincula con DSS del condado y aliados de acción comunitaria.",
        hours="Monday–Friday business hours; call ahead in rural counties",
        tags="saluda|saluda|employment|SC-Works|WIOA|reentry|fair-chance",
        services="Job search assistance|Resume preparation|WIOA training referrals|Fair-chance employment|Career coaching",
        county="Saluda", served_counties="Saluda", coverage="single",
        _source="https://www.scworks.org", _source_type="government", _confidence="high",
    )
    add(
        name="Saluda County Hospital",
        category="healthcare",
        region="Saluda / Saluda County",
        description="Saluda County Hospital provides primary care, emergency services, and community health outreach for Saluda County residents including uninsured and Medicaid patients such as returning citizens establishing local medical care after release from SCDC custody or county jails. Direct clinical services—not a walk-in benefits or probation office.",
        description_es="Saluda County Hospital brinda servicios para residentes del condado Saluda incluidos pacientes sin seguro y Medicaid como ciudadanos que regresan que establecen atención médica local después de la liberación. Servicios directos, no oficina de beneficios ni de probatoria.",
        address="201 E. Church Street", city="Saluda", phone="864-445-4500", email="",
        website="https://selfregional.org",
        eligibility="Open to Saluda County residents; sliding-fee and Medicaid patients welcome including justice-involved adults.",
        eligibility_es="Abierto a residentes del condado Saluda; pacientes con tarifa móvil y Medicaid bienvenidos incluidos adultos con antecedentes penales.",
        notes="Call 864-445-4500 for appointments and services; pairs with SC Works Saluda and county DSS.",
        notes_es="Llame al 864-445-4500 para citas y servicios; se vincula con SC Works Saluda y DSS del condado.",
        hours="Emergency 24/7; call for hours",
        tags="saluda|healthcare|rural|reentry",
        services="Primary care|Emergency services|Community health outreach|Sliding-fee care|Specialist referrals",
        county="Saluda", served_counties="Saluda", coverage="single",
        _source="https://selfregional.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="SC Works Career Center — Union County",
        category="employment",
        region="Union / Union County",
        description="SC Works Career Center Union County in Union connects job seekers including justice-involved adults from Union County jails and SCDC custody to WIOA-funded training, resume assistance, fair-chance employment navigation, and SC Works online job matching. Staff link returning citizens to local healthcare, food, and reentry partners in rural Union County. Free core career services—not emergency cash or housing placement.",
        description_es="SC Works Career Center del condado Union en Union conecta buscadores de empleo incluidos adultos con antecedentes penales de cárceles del condado Union y custodia SCDC con capacitación WIOA, ayuda con currículum y navegación de empleo de segunda oportunidad. Servicios básicos de carrera gratuitos.",
        address="111 S. Mountain Street", city="Union", phone="864-427-4114", email="",
        website="https://www.scworks.org",
        eligibility="Open to Union County job seekers including justice-involved individuals; core SC Works services are free.",
        eligibility_es="Abierto a buscadores de empleo del condado Union incluidas personas con antecedentes penales; servicios básicos de SC Works son gratuitos.",
        notes="Register at scworks.org; call 864-427-4114; pairs with county DSS and local community action partners.",
        notes_es="Regístrese en scworks.org; llame al 864-427-4114; se vincula con DSS del condado y aliados de acción comunitaria.",
        hours="Monday–Friday business hours; call ahead in rural counties",
        tags="union|union|employment|SC-Works|WIOA|reentry|fair-chance",
        services="Job search assistance|Resume preparation|WIOA training referrals|Fair-chance employment|Career coaching",
        county="Union", served_counties="Union", coverage="single",
        _source="https://www.scworks.org", _source_type="government", _confidence="high",
    )
    add(
        name="Union County Carnegie Library Workforce",
        category="employment",
        region="Union / Union County",
        description="Union County Carnegie Library Workforce provides emergency assistance and community support for Union County residents including uninsured and Medicaid patients such as returning citizens establishing local stability after release from SCDC custody or county jails. Direct assistance services—not a walk-in benefits or probation office.",
        description_es="Union County Carnegie Library Workforce brinda servicios para residentes del condado Union incluidos pacientes sin seguro y Medicaid como ciudadanos que regresan que establecen estabilidad local después de la liberación. Servicios directos, no oficina de beneficios ni de probatoria.",
        address="111 S. Mountain Street", city="Union", phone="864-427-7140", email="",
        website="https://scworks.org",
        eligibility="Open to Union County residents; sliding-fee and Medicaid patients welcome including justice-involved adults.",
        eligibility_es="Abierto a residentes del condado Union; pacientes con tarifa móvil y Medicaid bienvenidos incluidos adultos con antecedentes penales.",
        notes="Call 864-427-7140 for appointments and services; pairs with SC Works Union and county DSS.",
        notes_es="Llame al 864-427-7140 para citas y servicios; se vincula con SC Works Union y DSS del condado.",
        hours="Monday–Friday business hours; call for hours",
        tags="union|employment|rural|reentry",
        services="Emergency assistance|Referral navigation|Utility help|Case management|Benefits referrals",
        county="Union", served_counties="Union", coverage="single",
        _source="https://scworks.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="SC Works Career Center — Williamsburg County",
        category="employment",
        region="Kingstree / Williamsburg County",
        description="SC Works Career Center Williamsburg County in Kingstree connects job seekers including justice-involved adults from Williamsburg County jails and SCDC custody to WIOA-funded training, resume assistance, fair-chance employment navigation, and SC Works online job matching. Staff link returning citizens to local healthcare, food, and reentry partners in rural Williamsburg County. Free core career services—not emergency cash or housing placement.",
        description_es="SC Works Career Center del condado Williamsburg en Kingstree conecta buscadores de empleo incluidos adultos con antecedentes penales de cárceles del condado Williamsburg y custodia SCDC con capacitación WIOA, ayuda con currículum y navegación de empleo de segunda oportunidad. Servicios básicos de carrera gratuitos.",
        address="201 N. Academy Street", city="Kingstree", phone="843-355-9321", email="",
        website="https://www.scworks.org",
        eligibility="Open to Williamsburg County job seekers including justice-involved individuals; core SC Works services are free.",
        eligibility_es="Abierto a buscadores de empleo del condado Williamsburg incluidas personas con antecedentes penales; servicios básicos de SC Works son gratuitos.",
        notes="Register at scworks.org; call 843-355-9321; pairs with county DSS and local community action partners.",
        notes_es="Regístrese en scworks.org; llame al 843-355-9321; se vincula con DSS del condado y aliados de acción comunitaria.",
        hours="Monday–Friday business hours; call ahead in rural counties",
        tags="kingstree|williamsburg|employment|SC-Works|WIOA|reentry|fair-chance",
        services="Job search assistance|Resume preparation|WIOA training referrals|Fair-chance employment|Career coaching",
        county="Williamsburg", served_counties="Williamsburg", coverage="single",
        _source="https://www.scworks.org", _source_type="government", _confidence="high",
    )
    add(
        name="Williamsburg County Hospital",
        category="healthcare",
        region="Kingstree / Williamsburg County",
        description="Williamsburg County Hospital provides primary care, emergency services, and community health outreach for Williamsburg County residents including uninsured and Medicaid patients such as returning citizens establishing local medical care after release from SCDC custody or county jails. Direct clinical services—not a walk-in benefits or probation office.",
        description_es="Williamsburg County Hospital brinda servicios para residentes del condado Williamsburg incluidos pacientes sin seguro y Medicaid como ciudadanos que regresan que establecen atención médica local después de la liberación. Servicios directos, no oficina de beneficios ni de probatoria.",
        address="500 N. Academy Street", city="Kingstree", phone="843-355-8900", email="",
        website="https://williamsburgregional.com",
        eligibility="Open to Williamsburg County residents; sliding-fee and Medicaid patients welcome including justice-involved adults.",
        eligibility_es="Abierto a residentes del condado Williamsburg; pacientes con tarifa móvil y Medicaid bienvenidos incluidos adultos con antecedentes penales.",
        notes="Call 843-355-8900 for appointments and services; pairs with SC Works Williamsburg and county DSS.",
        notes_es="Llame al 843-355-8900 para citas y servicios; se vincula con SC Works Williamsburg y DSS del condado.",
        hours="Emergency 24/7; call for hours",
        tags="williamsburg|healthcare|rural|reentry",
        services="Primary care|Emergency services|Community health outreach|Sliding-fee care|Specialist referrals",
        county="Williamsburg", served_counties="Williamsburg", coverage="single",
        _source="https://williamsburgregional.com", _source_type="nonprofit", _confidence="high",
    )
