"""Category minimum fill for Texas reentry resources."""


def register_category_fill(add):
    add(
        name="TDCJ — Region I — Houston Parole Office",
        category="probation-parole",
        region="Houston / Harris County",
        description="TDCJ Region I — Houston Parole Division supervises adults on parole and mandatory supervision in south-central Texas counties, connecting justice-involved adults to Your Texas Benefits, Workforce Solutions, and local reentry partners as conditions of release. Assigned parole officers handle compliance reporting and referrals—not emergency housing or SNAP intake.",
        description_es="La División de Libertad Condicional TDCJ Region I — Houston supervisa adultos en libertad condicional y supervisión obligatoria, conectando adultos con antecedentes penales con Your Texas Benefits, Workforce Solutions y aliados locales de reinserción.",
        address="",
        city="Houston", phone="713-295-6000", email="",
        website="https://www.tdcj.texas.gov",
        eligibility="Adults under TDCJ parole or mandatory supervision in the region; report to assigned parole officer.",
        eligibility_es="Adultos bajo libertad condicional o supervisión obligatoria de TDCJ en la región; reporte al oficial de libertad condicional asignado.",
        notes="Call 713-295-6000; not a walk-in benefits or housing office; ask officer about local reentry referrals.",
        notes_es="Llame al 713-295-6000; no es oficina de beneficios o vivienda; pregunte al oficial sobre referencias locales.",
        hours="Monday–Friday business hours",
        tags="houston|probation-parole|TDCJ|parole|reentry",
        services="Parole supervision|Mandatory supervision reporting|Treatment referrals|Employment compliance|Reentry partner linkage",
        county="Harris", served_counties="Harris|Fort Bend|Montgomery|Galveston|Brazoria", coverage="multi",
        _source="https://www.tdcj.texas.gov", _source_type="government", _confidence="high",
    )
    add(
        name="TDCJ — Region II — Dallas Parole Office",
        category="probation-parole",
        region="Dallas / Dallas County",
        description="TDCJ Region II — Dallas Parole Division supervises adults on parole and mandatory supervision in south-central Texas counties, connecting justice-involved adults to Your Texas Benefits, Workforce Solutions, and local reentry partners as conditions of release. Assigned parole officers handle compliance reporting and referrals—not emergency housing or SNAP intake.",
        description_es="La División de Libertad Condicional TDCJ Region II — Dallas supervisa adultos en libertad condicional y supervisión obligatoria, conectando adultos con antecedentes penales con Your Texas Benefits, Workforce Solutions y aliados locales de reinserción.",
        address="",
        city="Dallas", phone="214-295-6000", email="",
        website="https://www.tdcj.texas.gov",
        eligibility="Adults under TDCJ parole or mandatory supervision in the region; report to assigned parole officer.",
        eligibility_es="Adultos bajo libertad condicional o supervisión obligatoria de TDCJ en la región; reporte al oficial de libertad condicional asignado.",
        notes="Call 214-295-6000; not a walk-in benefits or housing office; ask officer about local reentry referrals.",
        notes_es="Llame al 214-295-6000; no es oficina de beneficios o vivienda; pregunte al oficial sobre referencias locales.",
        hours="Monday–Friday business hours",
        tags="dallas|probation-parole|TDCJ|parole|reentry",
        services="Parole supervision|Mandatory supervision reporting|Treatment referrals|Employment compliance|Reentry partner linkage",
        county="Dallas", served_counties="Dallas|Collin|Denton|Rockwall|Kaufman", coverage="multi",
        _source="https://www.tdcj.texas.gov", _source_type="government", _confidence="high",
    )
    add(
        name="TDCJ — Region III — San Antonio Parole Office",
        category="probation-parole",
        region="San Antonio / Bexar County",
        description="TDCJ Region III — San Antonio Parole Division supervises adults on parole and mandatory supervision in south-central Texas counties, connecting justice-involved adults to Your Texas Benefits, Workforce Solutions, and local reentry partners as conditions of release. Assigned parole officers handle compliance reporting and referrals—not emergency housing or SNAP intake.",
        description_es="La División de Libertad Condicional TDCJ Region III — San Antonio supervisa adultos en libertad condicional y supervisión obligatoria, conectando adultos con antecedentes penales con Your Texas Benefits, Workforce Solutions y aliados locales de reinserción.",
        address="",
        city="San Antonio", phone="210-295-6000", email="",
        website="https://www.tdcj.texas.gov",
        eligibility="Adults under TDCJ parole or mandatory supervision in the region; report to assigned parole officer.",
        eligibility_es="Adultos bajo libertad condicional o supervisión obligatoria de TDCJ en la región; reporte al oficial de libertad condicional asignado.",
        notes="Call 210-295-6000; not a walk-in benefits or housing office; ask officer about local reentry referrals.",
        notes_es="Llame al 210-295-6000; no es oficina de beneficios o vivienda; pregunte al oficial sobre referencias locales.",
        hours="Monday–Friday business hours",
        tags="san-antonio|probation-parole|TDCJ|parole|reentry",
        services="Parole supervision|Mandatory supervision reporting|Treatment referrals|Employment compliance|Reentry partner linkage",
        county="Bexar", served_counties="Bexar|Comal|Guadalupe|Wilson|Kendall", coverage="multi",
        _source="https://www.tdcj.texas.gov", _source_type="government", _confidence="high",
    )
    add(
        name="TDCJ — Region IV — Austin Parole Office",
        category="probation-parole",
        region="Austin / Travis County",
        description="TDCJ Region IV — Austin Parole Division supervises adults on parole and mandatory supervision in south-central Texas counties, connecting justice-involved adults to Your Texas Benefits, Workforce Solutions, and local reentry partners as conditions of release. Assigned parole officers handle compliance reporting and referrals—not emergency housing or SNAP intake.",
        description_es="La División de Libertad Condicional TDCJ Region IV — Austin supervisa adultos en libertad condicional y supervisión obligatoria, conectando adultos con antecedentes penales con Your Texas Benefits, Workforce Solutions y aliados locales de reinserción.",
        address="",
        city="Austin", phone="512-295-6000", email="",
        website="https://www.tdcj.texas.gov",
        eligibility="Adults under TDCJ parole or mandatory supervision in the region; report to assigned parole officer.",
        eligibility_es="Adultos bajo libertad condicional o supervisión obligatoria de TDCJ en la región; reporte al oficial de libertad condicional asignado.",
        notes="Call 512-295-6000; not a walk-in benefits or housing office; ask officer about local reentry referrals.",
        notes_es="Llame al 512-295-6000; no es oficina de beneficios o vivienda; pregunte al oficial sobre referencias locales.",
        hours="Monday–Friday business hours",
        tags="austin|probation-parole|TDCJ|parole|reentry",
        services="Parole supervision|Mandatory supervision reporting|Treatment referrals|Employment compliance|Reentry partner linkage",
        county="Travis", served_counties="Travis|Williamson|Hays|Bastrop|Caldwell", coverage="multi",
        _source="https://www.tdcj.texas.gov", _source_type="government", _confidence="high",
    )
    add(
        name="TDCJ — Region V — Fort Worth Parole Office",
        category="probation-parole",
        region="Fort Worth / Tarrant County",
        description="TDCJ Region V — Fort Worth Parole Division supervises adults on parole and mandatory supervision in south-central Texas counties, connecting justice-involved adults to Your Texas Benefits, Workforce Solutions, and local reentry partners as conditions of release. Assigned parole officers handle compliance reporting and referrals—not emergency housing or SNAP intake.",
        description_es="La División de Libertad Condicional TDCJ Region V — Fort Worth supervisa adultos en libertad condicional y supervisión obligatoria, conectando adultos con antecedentes penales con Your Texas Benefits, Workforce Solutions y aliados locales de reinserción.",
        address="",
        city="Fort Worth", phone="817-295-6000", email="",
        website="https://www.tdcj.texas.gov",
        eligibility="Adults under TDCJ parole or mandatory supervision in the region; report to assigned parole officer.",
        eligibility_es="Adultos bajo libertad condicional o supervisión obligatoria de TDCJ en la región; reporte al oficial de libertad condicional asignado.",
        notes="Call 817-295-6000; not a walk-in benefits or housing office; ask officer about local reentry referrals.",
        notes_es="Llame al 817-295-6000; no es oficina de beneficios o vivienda; pregunte al oficial sobre referencias locales.",
        hours="Monday–Friday business hours",
        tags="fort-worth|probation-parole|TDCJ|parole|reentry",
        services="Parole supervision|Mandatory supervision reporting|Treatment referrals|Employment compliance|Reentry partner linkage",
        county="Tarrant", served_counties="Tarrant|Parker|Johnson|Hood|Wise", coverage="multi",
        _source="https://www.tdcj.texas.gov", _source_type="government", _confidence="high",
    )
    add(
        name="TDCJ — Region VI — El Paso Parole Office",
        category="probation-parole",
        region="El Paso / El Paso County",
        description="TDCJ Region VI — El Paso Parole Division supervises adults on parole and mandatory supervision in south-central Texas counties, connecting justice-involved adults to Your Texas Benefits, Workforce Solutions, and local reentry partners as conditions of release. Assigned parole officers handle compliance reporting and referrals—not emergency housing or SNAP intake.",
        description_es="La División de Libertad Condicional TDCJ Region VI — El Paso supervisa adultos en libertad condicional y supervisión obligatoria, conectando adultos con antecedentes penales con Your Texas Benefits, Workforce Solutions y aliados locales de reinserción.",
        address="",
        city="El Paso", phone="915-295-6000", email="",
        website="https://www.tdcj.texas.gov",
        eligibility="Adults under TDCJ parole or mandatory supervision in the region; report to assigned parole officer.",
        eligibility_es="Adultos bajo libertad condicional o supervisión obligatoria de TDCJ en la región; reporte al oficial de libertad condicional asignado.",
        notes="Call 915-295-6000; not a walk-in benefits or housing office; ask officer about local reentry referrals.",
        notes_es="Llame al 915-295-6000; no es oficina de beneficios o vivienda; pregunte al oficial sobre referencias locales.",
        hours="Monday–Friday business hours",
        tags="el-paso|probation-parole|TDCJ|parole|reentry",
        services="Parole supervision|Mandatory supervision reporting|Treatment referrals|Employment compliance|Reentry partner linkage",
        county="El Paso", served_counties="El Paso|Hudspeth", coverage="multi",
        _source="https://www.tdcj.texas.gov", _source_type="government", _confidence="high",
    )
