"""Phase 4 program-level expansion entries for Texas reentry resources."""


def register_phase4(add):
    add(
        name="The Way Home — Houston/Harris Reentry Housing",
        category="housing",
        region="Houston / Harris County",
        description="The Way Home — Houston/Harris Reentry Housing serves justice-involved adults returning from TDCJ custody and Harris County jails with reentry supports connecting participants to Your Texas Benefits, Workforce Solutions, and local treatment and housing partners across Houston / Harris County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
        description_es="The Way Home — Houston/Harris Reentry Housing sirve a adultos con antecedentes penales que regresan de custodia TDCJ y cárceles del condado Harris con apoyos de reinserción conectando participantes con Your Texas Benefits, Workforce Solutions y aliados locales de tratamiento y vivienda en Houston / condado Harris.",
        address="500 Fannin Street, Suite 100", city="Houston", phone="713-533-9900", email="",
        website="https://www.thewayhomehouston.org",
        eligibility="Harris County residents and returning citizens; program eligibility varies; contact for intake.",
        eligibility_es="Residentes del condado Harris y ciudadanos que regresan; la elegibilidad del programa varía; contacte para admisión.",
        notes="Call 713-533-9900 for current intake hours and eligibility.",
        notes_es="Llame al 713-533-9900 para horarios de admisión y elegibilidad actuales.",
        hours="Monday–Friday business hours; call ahead",
        tags="houston|harris|housing|reentry|HMIS",
        services="Reentry navigation|Benefits referrals|Employment linkage|Treatment referrals|Housing support",
        county="Harris", served_counties="Harris", coverage="single",
        _source="https://www.thewayhomehouston.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="SEARCH Homeless Services — Houston",
        category="housing",
        region="Houston / Harris County",
        description="SEARCH Homeless Services — Houston serves justice-involved adults returning from TDCJ custody and Harris County jails with reentry supports connecting participants to Your Texas Benefits, Workforce Solutions, and local treatment and housing partners across Houston / Harris County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
        description_es="SEARCH Homeless Services — Houston sirve a adultos con antecedentes penales que regresan de custodia TDCJ y cárceles del condado Harris con apoyos de reinserción conectando participantes con Your Texas Benefits, Workforce Solutions y aliados locales de tratamiento y vivienda en Houston / condado Harris.",
        address="2015 Congress Avenue", city="Houston", phone="713-739-7752", email="",
        website="https://www.searchhomeless.org",
        eligibility="Harris County residents and returning citizens; program eligibility varies; contact for intake.",
        eligibility_es="Residentes del condado Harris y ciudadanos que regresan; la elegibilidad del programa varía; contacte para admisión.",
        notes="Call 713-739-7752 for current intake hours and eligibility.",
        notes_es="Llame al 713-739-7752 para horarios de admisión y elegibilidad actuales.",
        hours="Monday–Friday business hours; call ahead",
        tags="houston|harris|housing|homeless|reentry",
        services="Reentry navigation|Benefits referrals|Employment linkage|Treatment referrals|Housing support",
        county="Harris", served_counties="Harris", coverage="single",
        _source="https://www.searchhomeless.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Career and Recovery Resources — Houston",
        category="reentry-organizations",
        region="Houston / Harris County",
        description="Career and Recovery Resources — Houston serves justice-involved adults returning from TDCJ custody and Harris County jails with reentry supports connecting participants to Your Texas Benefits, Workforce Solutions, and local treatment and housing partners across Houston / Harris County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
        description_es="Career and Recovery Resources — Houston sirve a adultos con antecedentes penales que regresan de custodia TDCJ y cárceles del condado Harris con apoyos de reinserción conectando participantes con Your Texas Benefits, Workforce Solutions y aliados locales de tratamiento y vivienda en Houston / condado Harris.",
        address="2525 San Jacinto Street", city="Houston", phone="713-754-7000", email="",
        website="https://www.crrhouston.org",
        eligibility="Harris County residents and returning citizens; program eligibility varies; contact for intake.",
        eligibility_es="Residentes del condado Harris y ciudadanos que regresan; la elegibilidad del programa varía; contacte para admisión.",
        notes="Call 713-754-7000 for current intake hours and eligibility.",
        notes_es="Llame al 713-754-7000 para horarios de admisión y elegibilidad actuales.",
        hours="Monday–Friday business hours; call ahead",
        tags="houston|harris|reentry|employment|case-management",
        services="Reentry navigation|Benefits referrals|Employment linkage|Treatment referrals|Housing support",
        county="Harris", served_counties="Harris", coverage="single",
        _source="https://www.crrhouston.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Unlocking DOORS — Dallas Reentry",
        category="reentry-organizations",
        region="Dallas / Dallas County",
        description="Unlocking DOORS — Dallas Reentry serves justice-involved adults returning from TDCJ custody and Dallas County jails with reentry supports connecting participants to Your Texas Benefits, Workforce Solutions, and local treatment and housing partners across Dallas / Dallas County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
        description_es="Unlocking DOORS — Dallas Reentry sirve a adultos con antecedentes penales que regresan de custodia TDCJ y cárceles del condado Dallas con apoyos de reinserción conectando participantes con Your Texas Benefits, Workforce Solutions y aliados locales de tratamiento y vivienda en Dallas / condado Dallas.",
        address="1600 Viceroy Drive, Suite 400", city="Dallas", phone="214-671-8244", email="",
        website="https://www.unlockingdoors.org",
        eligibility="Dallas County residents and returning citizens; program eligibility varies; contact for intake.",
        eligibility_es="Residentes del condado Dallas y ciudadanos que regresan; la elegibilidad del programa varía; contacte para admisión.",
        notes="Call 214-671-8244 for current intake hours and eligibility.",
        notes_es="Llame al 214-671-8244 para horarios de admisión y elegibilidad actuales.",
        hours="Monday–Friday business hours; call ahead",
        tags="dallas|reentry|employment|case-management",
        services="Reentry navigation|Benefits referrals|Employment linkage|Treatment referrals|Housing support",
        county="Dallas", served_counties="Dallas", coverage="single",
        _source="https://www.unlockingdoors.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Exodus Ministries — Dallas Reentry",
        category="reentry-organizations",
        region="Dallas / Dallas County",
        description="Exodus Ministries — Dallas Reentry serves justice-involved adults returning from TDCJ custody and Dallas County jails with reentry supports connecting participants to Your Texas Benefits, Workforce Solutions, and local treatment and housing partners across Dallas / Dallas County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
        description_es="Exodus Ministries — Dallas Reentry sirve a adultos con antecedentes penales que regresan de custodia TDCJ y cárceles del condado Dallas con apoyos de reinserción conectando participantes con Your Texas Benefits, Workforce Solutions y aliados locales de tratamiento y vivienda en Dallas / condado Dallas.",
        address="3100 Swiss Avenue", city="Dallas", phone="214-821-6380", email="",
        website="https://www.exodusministries.org",
        eligibility="Dallas County residents and returning citizens; program eligibility varies; contact for intake.",
        eligibility_es="Residentes del condado Dallas y ciudadanos que regresan; la elegibilidad del programa varía; contacte para admisión.",
        notes="Call 214-821-6380 for current intake hours and eligibility.",
        notes_es="Llame al 214-821-6380 para horarios de admisión y elegibilidad actuales.",
        hours="Monday–Friday business hours; call ahead",
        tags="dallas|reentry|housing|faith-based",
        services="Reentry navigation|Benefits referrals|Employment linkage|Treatment referrals|Housing support",
        county="Dallas", served_counties="Dallas", coverage="single",
        _source="https://www.exodusministries.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Workforce Solutions Greater Dallas",
        category="employment",
        region="Dallas / Dallas County",
        description="Workforce Solutions Greater Dallas serves justice-involved adults returning from TDCJ custody and Dallas County jails with reentry supports connecting participants to Your Texas Benefits, Workforce Solutions, and local treatment and housing partners across Dallas / Dallas County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
        description_es="Workforce Solutions Greater Dallas sirve a adultos con antecedentes penales que regresan de custodia TDCJ y cárceles del condado Dallas con apoyos de reinserción conectando participantes con Your Texas Benefits, Workforce Solutions y aliados locales de tratamiento y vivienda en Dallas / condado Dallas.",
        address="500 North Akard Street", city="Dallas", phone="214-860-0000", email="",
        website="https://www.dallasworkforce.org",
        eligibility="Dallas County residents and returning citizens; program eligibility varies; contact for intake.",
        eligibility_es="Residentes del condado Dallas y ciudadanos que regresan; la elegibilidad del programa varía; contacte para admisión.",
        notes="Call 214-860-0000 for current intake hours and eligibility.",
        notes_es="Llame al 214-860-0000 para horarios de admisión y elegibilidad actuales.",
        hours="Monday–Friday business hours; call ahead",
        tags="dallas|employment|WIOA|workforce-solutions",
        services="Reentry navigation|Benefits referrals|Employment linkage|Treatment referrals|Housing support",
        county="Dallas", served_counties="Dallas", coverage="single",
        _source="https://www.dallasworkforce.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Workforce Solutions Alamo — San Antonio",
        category="employment",
        region="San Antonio / Bexar County",
        description="Workforce Solutions Alamo — San Antonio serves justice-involved adults returning from TDCJ custody and Bexar County jails with reentry supports connecting participants to Your Texas Benefits, Workforce Solutions, and local treatment and housing partners across San Antonio / Bexar County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
        description_es="Workforce Solutions Alamo — San Antonio sirve a adultos con antecedentes penales que regresan de custodia TDCJ y cárceles del condado Bexar con apoyos de reinserción conectando participantes con Your Texas Benefits, Workforce Solutions y aliados locales de tratamiento y vivienda en San Antonio / condado Bexar.",
        address="6723 South Flores Street", city="San Antonio", phone="210-272-3260", email="",
        website="https://www.workforcesolutionsalamo.org",
        eligibility="Bexar County residents and returning citizens; program eligibility varies; contact for intake.",
        eligibility_es="Residentes del condado Bexar y ciudadanos que regresan; la elegibilidad del programa varía; contacte para admisión.",
        notes="Call 210-272-3260 for current intake hours and eligibility.",
        notes_es="Llame al 210-272-3260 para horarios de admisión y elegibilidad actuales.",
        hours="Monday–Friday business hours; call ahead",
        tags="san-antonio|bexar|employment|WIOA|workforce-solutions",
        services="Reentry navigation|Benefits referrals|Employment linkage|Treatment referrals|Housing support",
        county="Bexar", served_counties="Bexar", coverage="single",
        _source="https://www.workforcesolutionsalamo.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Bexar County Reentry Services",
        category="reentry-organizations",
        region="San Antonio / Bexar County",
        description="Bexar County Reentry Services serves justice-involved adults returning from TDCJ custody and Bexar County jails with reentry supports connecting participants to Your Texas Benefits, Workforce Solutions, and local treatment and housing partners across San Antonio / Bexar County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
        description_es="Bexar County Reentry Services sirve a adultos con antecedentes penales que regresan de custodia TDCJ y cárceles del condado Bexar con apoyos de reinserción conectando participantes con Your Texas Benefits, Workforce Solutions y aliados locales de tratamiento y vivienda en San Antonio / condado Bexar.",
        address="100 Dolorosa, Suite 201", city="San Antonio", phone="210-335-6777", email="",
        website="https://www.bexar.org/3267/Reentry-Services",
        eligibility="Bexar County residents and returning citizens; program eligibility varies; contact for intake.",
        eligibility_es="Residentes del condado Bexar y ciudadanos que regresan; la elegibilidad del programa varía; contacte para admisión.",
        notes="Call 210-335-6777 for current intake hours and eligibility.",
        notes_es="Llame al 210-335-6777 para horarios de admisión y elegibilidad actuales.",
        hours="Monday–Friday business hours; call ahead",
        tags="san-antonio|bexar|reentry|county",
        services="Reentry navigation|Benefits referrals|Employment linkage|Treatment referrals|Housing support",
        county="Bexar", served_counties="Bexar", coverage="single",
        _source="https://www.bexar.org/3267/Reentry-Services", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Foundation Communities — Austin Reentry Housing",
        category="housing",
        region="Austin / Travis County",
        description="Foundation Communities — Austin Reentry Housing serves justice-involved adults returning from TDCJ custody and Travis County jails with reentry supports connecting participants to Your Texas Benefits, Workforce Solutions, and local treatment and housing partners across Austin / Travis County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
        description_es="Foundation Communities — Austin Reentry Housing sirve a adultos con antecedentes penales que regresan de custodia TDCJ y cárceles del condado Travis con apoyos de reinserción conectando participantes con Your Texas Benefits, Workforce Solutions y aliados locales de tratamiento y vivienda en Austin / condado Travis.",
        address="3036 South First Street", city="Austin", phone="512-447-2026", email="",
        website="https://www.foundationcommunities.org",
        eligibility="Travis County residents and returning citizens; program eligibility varies; contact for intake.",
        eligibility_es="Residentes del condado Travis y ciudadanos que regresan; la elegibilidad del programa varía; contacte para admisión.",
        notes="Call 512-447-2026 for current intake hours and eligibility.",
        notes_es="Llame al 512-447-2026 para horarios de admisión y elegibilidad actuales.",
        hours="Monday–Friday business hours; call ahead",
        tags="austin|travis|housing|affordable|reentry",
        services="Reentry navigation|Benefits referrals|Employment linkage|Treatment referrals|Housing support",
        county="Travis", served_counties="Travis", coverage="single",
        _source="https://www.foundationcommunities.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Texas Criminal Justice Coalition — Austin",
        category="reentry-organizations",
        region="Austin / Travis County",
        description="Texas Criminal Justice Coalition — Austin serves justice-involved adults returning from TDCJ custody and Travis County jails with reentry supports connecting participants to Your Texas Benefits, Workforce Solutions, and local treatment and housing partners across Austin / Travis County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
        description_es="Texas Criminal Justice Coalition — Austin sirve a adultos con antecedentes penales que regresan de custodia TDCJ y cárceles del condado Travis con apoyos de reinserción conectando participantes con Your Texas Benefits, Workforce Solutions y aliados locales de tratamiento y vivienda en Austin / condado Travis.",
        address="510 South Congress Avenue", city="Austin", phone="512-441-8123", email="",
        website="https://www.texascjc.org",
        eligibility="Travis County residents and returning citizens; program eligibility varies; contact for intake.",
        eligibility_es="Residentes del condado Travis y ciudadanos que regresan; la elegibilidad del programa varía; contacte para admisión.",
        notes="Call 512-441-8123 for current intake hours and eligibility.",
        notes_es="Llame al 512-441-8123 para horarios de admisión y elegibilidad actuales.",
        hours="Monday–Friday business hours; call ahead",
        tags="austin|travis|reentry|advocacy|policy",
        services="Reentry navigation|Benefits referrals|Employment linkage|Treatment referrals|Housing support",
        county="Travis", served_counties="Travis", coverage="single",
        _source="https://www.texascjc.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Workforce Solutions Capital Area — Austin",
        category="employment",
        region="Austin / Travis County",
        description="Workforce Solutions Capital Area — Austin serves justice-involved adults returning from TDCJ custody and Travis County jails with reentry supports connecting participants to Your Texas Benefits, Workforce Solutions, and local treatment and housing partners across Austin / Travis County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
        description_es="Workforce Solutions Capital Area — Austin sirve a adultos con antecedentes penales que regresan de custodia TDCJ y cárceles del condado Travis con apoyos de reinserción conectando participantes con Your Texas Benefits, Workforce Solutions y aliados locales de tratamiento y vivienda en Austin / condado Travis.",
        address="9001 North IH-35, Suite 110", city="Austin", phone="512-458-8755", email="",
        website="https://www.wfscapitalarea.com",
        eligibility="Travis County residents and returning citizens; program eligibility varies; contact for intake.",
        eligibility_es="Residentes del condado Travis y ciudadanos que regresan; la elegibilidad del programa varía; contacte para admisión.",
        notes="Call 512-458-8755 for current intake hours and eligibility.",
        notes_es="Llame al 512-458-8755 para horarios de admisión y elegibilidad actuales.",
        hours="Monday–Friday business hours; call ahead",
        tags="austin|travis|employment|WIOA|workforce-solutions",
        services="Reentry navigation|Benefits referrals|Employment linkage|Treatment referrals|Housing support",
        county="Travis", served_counties="Travis", coverage="single",
        _source="https://www.wfscapitalarea.com", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Project Vida — El Paso Reentry",
        category="reentry-organizations",
        region="El Paso / El Paso County",
        description="Project Vida — El Paso Reentry serves justice-involved adults returning from TDCJ custody and El Paso County jails with reentry supports connecting participants to Your Texas Benefits, Workforce Solutions, and local treatment and housing partners across El Paso / El Paso County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
        description_es="Project Vida — El Paso Reentry sirve a adultos con antecedentes penales que regresan de custodia TDCJ y cárceles del condado El Paso con apoyos de reinserción conectando participantes con Your Texas Benefits, Workforce Solutions y aliados locales de tratamiento y vivienda en El Paso / condado El Paso.",
        address="3607 Rivera Avenue", city="El Paso", phone="915-532-3414", email="",
        website="https://www.projectvida.net",
        eligibility="El Paso County residents and returning citizens; program eligibility varies; contact for intake.",
        eligibility_es="Residentes del condado El Paso y ciudadanos que regresan; la elegibilidad del programa varía; contacte para admisión.",
        notes="Call 915-532-3414 for current intake hours and eligibility.",
        notes_es="Llame al 915-532-3414 para horarios de admisión y elegibilidad actuales.",
        hours="Monday–Friday business hours; call ahead",
        tags="el-paso|reentry|healthcare|community",
        services="Reentry navigation|Benefits referrals|Employment linkage|Treatment referrals|Housing support",
        county="El Paso", served_counties="El Paso", coverage="single",
        _source="https://www.projectvida.net", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Tarrant County Reentry Coalition",
        category="reentry-organizations",
        region="Fort Worth / Tarrant County",
        description="Tarrant County Reentry Coalition serves justice-involved adults returning from TDCJ custody and Tarrant County jails with reentry supports connecting participants to Your Texas Benefits, Workforce Solutions, and local treatment and housing partners across Fort Worth / Tarrant County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
        description_es="Tarrant County Reentry Coalition sirve a adultos con antecedentes penales que regresan de custodia TDCJ y cárceles del condado Tarrant con apoyos de reinserción conectando participantes con Your Texas Benefits, Workforce Solutions y aliados locales de tratamiento y vivienda en Fort Worth / condado Tarrant.",
        address="401 West Belknap Street", city="Fort Worth", phone="817-884-2684", email="",
        website="https://www.tarrantcounty.com/en/criminal-district-attorney/reentry.html",
        eligibility="Tarrant County residents and returning citizens; program eligibility varies; contact for intake.",
        eligibility_es="Residentes del condado Tarrant y ciudadanos que regresan; la elegibilidad del programa varía; contacte para admisión.",
        notes="Call 817-884-2684 for current intake hours and eligibility.",
        notes_es="Llame al 817-884-2684 para horarios de admisión y elegibilidad actuales.",
        hours="Monday–Friday business hours; call ahead",
        tags="fort-worth|tarrant|reentry|coalition",
        services="Reentry navigation|Benefits referrals|Employment linkage|Treatment referrals|Housing support",
        county="Tarrant", served_counties="Tarrant", coverage="single",
        _source="https://www.tarrantcounty.com/en/criminal-district-attorney/reentry.html", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Gulf Coast Center — Behavioral Health",
        category="healthcare",
        region="Galveston / Galveston County",
        description="Gulf Coast Center — Behavioral Health serves justice-involved adults returning from TDCJ custody and Galveston County jails with reentry supports connecting participants to Your Texas Benefits, Workforce Solutions, and local treatment and housing partners across Texas City / Galveston County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
        description_es="Gulf Coast Center — Behavioral Health sirve a adultos con antecedentes penales que regresan de custodia TDCJ y cárceles del condado Galveston con apoyos de reinserción conectando participantes con Your Texas Benefits, Workforce Solutions y aliados locales de tratamiento y vivienda en Texas City / condado Galveston.",
        address="2102 Avenue H", city="Texas City", phone="866-729-3848", email="",
        website="https://www.gulfcoastcenter.org",
        eligibility="Galveston County residents and returning citizens; program eligibility varies; contact for intake.",
        eligibility_es="Residentes del condado Galveston y ciudadanos que regresan; la elegibilidad del programa varía; contacte para admisión.",
        notes="Call 866-729-3848 for current intake hours and eligibility.",
        notes_es="Llame al 866-729-3848 para horarios de admisión y elegibilidad actuales.",
        hours="Monday–Friday business hours; call ahead",
        tags="galveston|behavioral-health|Medicaid|reentry",
        services="Reentry navigation|Benefits referrals|Employment linkage|Treatment referrals|Housing support",
        county="Galveston", served_counties="Galveston", coverage="single",
        _source="https://www.gulfcoastcenter.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Harris Center for Mental Health — Houston",
        category="healthcare",
        region="Houston / Harris County",
        description="Harris Center for Mental Health — Houston serves justice-involved adults returning from TDCJ custody and Harris County jails with reentry supports connecting participants to Your Texas Benefits, Workforce Solutions, and local treatment and housing partners across Houston / Harris County. Direct program services—not emergency cash assistance or a general probation reporting office unless noted.",
        description_es="Harris Center for Mental Health — Houston sirve a adultos con antecedentes penales que regresan de custodia TDCJ y cárceles del condado Harris con apoyos de reinserción conectando participantes con Your Texas Benefits, Workforce Solutions y aliados locales de tratamiento y vivienda en Houston / condado Harris.",
        address="9401 Southwest Freeway", city="Houston", phone="713-970-7000", email="",
        website="https://www.theharriscenter.org",
        eligibility="Harris County residents and returning citizens; program eligibility varies; contact for intake.",
        eligibility_es="Residentes del condado Harris y ciudadanos que regresan; la elegibilidad del programa varía; contacte para admisión.",
        notes="Call 713-970-7000 for current intake hours and eligibility.",
        notes_es="Llame al 713-970-7000 para horarios de admisión y elegibilidad actuales.",
        hours="Monday–Friday business hours; call ahead",
        tags="houston|harris|behavioral-health|Medicaid|reentry",
        services="Reentry navigation|Benefits referrals|Employment linkage|Treatment referrals|Housing support",
        county="Harris", served_counties="Harris", coverage="single",
        _source="https://www.theharriscenter.org", _source_type="nonprofit", _confidence="high",
    )
