"""Direct-service pins for Virginia localities that had only a DSS row (Tier A depth)."""


def register_thin_counties(add):
    """Program-level rows for thin rural localities — housing, healthcare, employment."""

    add(
        name="Valley Mission — Emergency Shelter & Reentry Support",
        category="housing",
        region="Staunton / Augusta County",
        description="Valley Mission in Staunton operates one of the few shelters within 100 miles that serves single men, single women, and families with 24/7 emergency beds, meals, case management, GED classes, housing-fund assistance, and pastoral counseling. Justice-involved adults returning to Augusta County, Staunton, or Waynesboro can call for bed availability and complete intake with photo ID. Direct shelter and reentry support—not a statewide benefits hotline or legal clinic.",
        description_es="Valley Mission en Staunton opera uno de los pocos refugios en un radio de 100 millas que atiende a hombres solteros, mujeres solteras y familias con camas de emergencia 24/7, comidas, manejo de caso, clases de GED, asistencia para fondos de vivienda y consejería pastoral. Adultos con antecedentes penales que regresan al condado Augusta, Staunton o Waynesboro pueden llamar para disponibilidad de camas y completar la admisión con identificación con foto.",
        address="1513 West Beverley Street",
        city="Staunton",
        phone="540-886-4673",
        email="",
        website="https://valleymission.net/shelter/",
        eligibility="Homeless adults and families in Augusta County, Staunton, and Waynesboro; must function independently; children must be with a parent; call ahead for bed availability.",
        eligibility_es="Adultos y familias sin hogar en el condado Augusta, Staunton y Waynesboro; deben funcionar de forma independiente; los niños deben estar con un padre; llame con anticipación para disponibilidad de camas.",
        notes="Call 540-886-4673 before arriving; bring photo ID; dayroom open Monday–Friday 8 a.m.–5 p.m.; thrift store vouchers available for clothing.",
        notes_es="Llame al 540-886-4673 antes de llegar; traiga identificación con foto; sala diurna abierta lunes a viernes de 8 a.m. a 5 p.m.; vales de tienda de segunda mano disponibles para ropa.",
        hours="Shelter 24/7; administrative hours Monday–Friday, 8:00 a.m.–4:30 p.m.",
        tags="housing|emergency-shelter|case-management|GED|Staunton|Augusta|reentry",
        services="Emergency shelter|Meals|Case management|GED classes|Housing fund assistance|Thrift store vouchers",
        county="Staunton",
        served_counties="Augusta|Staunton|Waynesboro",
        coverage="multi",
        _source="https://valleymission.net/shelter/",
        _source_type="nonprofit",
        _confidence="high",
    )

    add(
        name="Southern Dominion Health System — Lunenburg Medical Center",
        category="healthcare",
        region="Lunenburg County / Southside",
        description="Southern Dominion Health System operates Lunenburg Medical Center, a Federally Qualified Health Center in Victoria providing primary medical, dental, behavioral health, and sliding-fee care for uninsured and Medicaid patients in Lunenburg County and surrounding Southside communities. Justice-involved adults reestablishing healthcare after release can access same-week appointments, medication assistance, and counseling at the K-V Road clinic. Direct clinical care—not emergency room or SNAP intake.",
        description_es="Southern Dominion Health System opera el Lunenburg Medical Center, un Centro de Salud Calificado Federalmente en Victoria que ofrece atención médica primaria, dental, de salud conductual y tarifas móviles para pacientes sin seguro y Medicaid en el condado Lunenburg y comunidades del Southside. Adultos con antecedentes penales que restablecen atención médica pueden acceder a citas, asistencia con medicamentos y consejería en la clínica de K-V Road.",
        address="1508 K-V Road",
        city="Victoria",
        phone="434-696-2165",
        email="",
        website="https://sdhsinc.com/locations/lunenburg/",
        eligibility="Residents of Lunenburg and surrounding Southside localities; sliding-fee scale based on income; Medicaid and Medicare accepted; criminal record not a stated barrier.",
        eligibility_es="Residentes de Lunenburg y localidades del Southside circundante; escala de tarifas según ingresos; se aceptan Medicaid y Medicare; los antecedentes penales no son una barrera indicada.",
        notes="Call 434-696-2165 for appointments; behavioral health at Lunenburg and Dinwiddie sites; Saturday hours 8 a.m.–12 p.m.",
        notes_es="Llame al 434-696-2165 para citas; salud conductual en sitios de Lunenburg y Dinwiddie; horario de sábado de 8 a.m. a 12 p.m.",
        hours="Monday–Friday, 8:00 a.m.–5:00 p.m.; Saturday, 8:00 a.m.–12:00 p.m.",
        tags="healthcare|FQHC|primary-care|behavioral-health|Lunenburg|Southside|reentry",
        services="Primary medical care|Dental care|Behavioral health counseling|Sliding-fee program|Medication assistance",
        county="Lunenburg",
        served_counties="Lunenburg",
        coverage="single",
        _source="https://sdhsinc.com/locations/lunenburg/",
        _source_type="nonprofit",
        _confidence="high",
    )

    add(
        name="Virginia Career Works — South Hill Center",
        category="employment",
        region="Mecklenburg County / South Central Virginia",
        description="The Virginia Career Works South Hill center connects job seekers in Mecklenburg, Lunenburg, Brunswick, and surrounding South Central Virginia localities to resume help, skills assessments, employer referrals, and WIOA training through the South Central Workforce Development Board. Justice-involved adults on probation or recently released can register on Virginia Workforce Connection for fair-chance job search support and case management when eligible. Workforce center—not emergency housing or legal aid.",
        description_es="El centro Virginia Career Works de South Hill conecta a buscadores de empleo en Mecklenburg, Lunenburg, Brunswick y localidades del sur central de Virginia con ayuda de currículum, evaluaciones de habilidades, referencias a empleadores y capacitación WIOA a través de la Junta de Desarrollo de la Fuerza Laboral del Sur Central. Adultos con antecedentes penales en libertad condicional o recién liberados pueden registrarse en Virginia Workforce Connection.",
        address="118 East Danville Street",
        city="South Hill",
        phone="434-955-2252",
        email="",
        website="https://www.virginiaworks.gov/local-office/south-hill/",
        eligibility="Open to South Central Virginia job seekers including justice-involved individuals; veterans receive priority services; register at vawc.virginia.gov.",
        eligibility_es="Abierto a buscadores de empleo del sur central de Virginia incluidas personas con antecedentes penales; veteranos reciben servicios prioritarios; regístrese en vawc.virginia.gov.",
        notes="Hours Monday, Wednesday–Friday 8:30 a.m.–4:30 p.m., Tuesday 9:30 a.m.–4:30 p.m.; closed lunch 12–1 p.m.; board office in Charlotte Court House 434-542-5871.",
        notes_es="Horario lunes y miércoles–viernes 8:30 a.m.–4:30 p.m., martes 9:30 a.m.–4:30 p.m.; cerrado almuerzo 12–1 p.m.; oficina de la junta en Charlotte Court House 434-542-5871.",
        hours="Monday, Wednesday–Friday 8:30 a.m.–4:30 p.m.; Tuesday 9:30 a.m.–4:30 p.m.",
        tags="employment|workforce|WIOA|fair-chance|Mecklenburg|Southside|reentry",
        services="Job search assistance|Resume writing|Skills assessment|Employer referrals|WIOA training navigation",
        county="Mecklenburg",
        served_counties="Mecklenburg|Lunenburg|Brunswick|Charlotte|Halifax|Nottoway",
        coverage="multi",
        _source="https://www.virginiaworks.gov/local-office/south-hill/",
        _source_type="government",
        _confidence="high",
    )

    add(
        name="Centra Southside Community Hospital",
        category="healthcare",
        region="Farmville / Buckingham County",
        description="Centra Southside Community Hospital in Farmville is a 100-bed acute care hospital serving Buckingham, Cumberland, Prince Edward, and surrounding South Central Virginia counties with emergency care, inpatient services, primary care referrals, and community health outreach. Returning citizens without a medical home can establish emergency and follow-up care through Centra's Farmville campus and affiliated primary care practices. Hospital services—not a walk-in SNAP or probation office.",
        description_es="Centra Southside Community Hospital en Farmville es un hospital de cuidados agudos de 100 camas que sirve a Buckingham, Cumberland, Prince Edward y condados del sur central de Virginia con atención de emergencia, servicios hospitalarios, referencias de atención primaria y alcance comunitario. Ciudadanos que regresan sin hogar médico pueden establecer atención de emergencia y seguimiento a través del campus de Farmville de Centra.",
        address="800 Oak Street",
        city="Farmville",
        phone="434-392-8811",
        email="",
        website="https://www.centrahealth.com/locations/centra-southside-community-hospital",
        eligibility="Open to residents of South Central Virginia; emergency care regardless of ability to pay; Medicaid and uninsured patients accepted for eligible services.",
        eligibility_es="Abierto a residentes del sur central de Virginia; atención de emergencia independientemente de capacidad de pago; pacientes Medicaid y sin seguro aceptados para servicios elegibles.",
        notes="Emergency department 24/7; main switchboard 434-392-8811; Centra primary care practices throughout Farmville and Buckingham County.",
        notes_es="Departamento de emergencias 24/7; conmutador principal 434-392-8811; prácticas de atención primaria de Centra en Farmville y el condado Buckingham.",
        hours="Emergency 24/7; hospital and clinic hours vary",
        tags="healthcare|hospital|emergency-care|Buckingham|Farmville|Southside|reentry",
        services="Emergency care|Inpatient hospital services|Primary care referrals|Community health outreach|Specialty referrals",
        county="Prince Edward",
        served_counties="Buckingham|Cumberland|Prince Edward|Charlotte|Lunenburg",
        coverage="multi",
        _source="https://www.centrahealth.com/locations/centra-southside-community-hospital",
        _source_type="nonprofit",
        _confidence="high",
    )

    add(
        name="People Inc. — Clarke County Community Action",
        category="basic-needs",
        region="Berryville / Clarke County",
        description="People Inc. is the community action agency serving Clarke, Frederick, Page, Shenandoah, and Warren counties with emergency assistance for rent, utilities, food, and clothing plus long-term self-sufficiency programs for low-income families. Justice-involved adults returning to Clarke County can apply for crisis assistance and connect to regional housing, employment, and benefits partners through the Berryville office. Direct assistance programs—not a statewide legal aid intake line.",
        description_es="People Inc. es la agencia de acción comunitaria que sirve a los condados Clarke, Frederick, Page, Shenandoah y Warren con asistencia de emergencia para renta, servicios públicos, alimentos y ropa, además de programas de autosuficiencia para familias de bajos ingresos. Adultos con antecedentes penales que regresan al condado Clarke pueden solicitar asistencia en crisis y conectarse con aliados regionales de vivienda, empleo y beneficios.",
        address="117 Commerce Street",
        city="Berryville",
        phone="540-955-2460",
        email="",
        website="https://www.peopleinc.net/",
        eligibility="Low-income residents of Clarke, Frederick, Page, Shenandoah, and Warren counties; income documentation required; justice-involved households eligible for crisis assistance.",
        eligibility_es="Residentes de bajos ingresos de los condados Clarke, Frederick, Page, Shenandoah y Warren; se requiere documentación de ingresos; hogares con antecedentes penales elegibles para asistencia en crisis.",
        notes="Call 540-955-2460 for intake; emergency assistance by appointment; Head Start and weatherization programs also available.",
        notes_es="Llame al 540-955-2460 para admisión; asistencia de emergencia con cita; también programas Head Start y de climatización.",
        hours="Monday–Friday business hours; call for appointment",
        tags="basic-needs|emergency-assistance|utilities|clothing|Clarke|reentry",
        services="Emergency rent and utility assistance|Food and clothing aid|Self-sufficiency coaching|Head Start referrals|Weatherization program",
        county="Clarke",
        served_counties="Clarke|Frederick|Page|Shenandoah|Warren",
        coverage="multi",
        _source="https://www.peopleinc.net/",
        _source_type="nonprofit",
        _confidence="high",
    )
