"""Tier A closure for Virginia localities below 3 core categories."""

def register_tier_a_closure(add):
    add(
        name="Virginia Fresh Food Distribution — Bath County",
        category="food-nutrition", region="Warm Springs / Bath",
        description="Blue Ridge Area Food Bank partner services connect Bath County residents—including returning citizens—to SNAP application help and emergency food through regional pantry partners. Not a probation office or emergency cash program unless noted.",
        description_es="Servicios para residentes de Bath incluidos adultos con antecedentes penales; no es oficina de libertad condicional ni efectivo de emergencia salvo que se indique.",
        address="Blue Ridge Area Food Bank partner pantry network", city="Warm Springs", phone="540-248-3663", email="",
        website="https://www.brafb.org",
        eligibility="Residents of Bath; justice-involved adults welcome where services allow.",
        eligibility_es="Residentes de Bath; adultos con antecedentes penales bienvenidos donde los servicios lo permitan.",
        notes="Call 540-248-3663 or visit website for partner locations and hours.",
        notes_es="Llame al 540-248-3663 o visite el sitio web para ubicaciones y horarios de aliados.",
        hours="Contact for partner pantry or clinic hours",
        tags="bath|food-nutrition|reentry|virginia",
        services="Food pantry referrals|SNAP application help|Nutrition programs",
        county="Bath", served_counties="Bath", coverage="single",
        _source="https://www.brafb.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Southern Virginia Regional Medical Center (serves Emporia)",
        category="healthcare", region="Emporia / Emporia",
        description="Southern Virginia Regional Medical Center provides emergency and outpatient care for Emporia and Greensville area residents including justice-involved adults. Not a probation office or emergency cash program unless noted.",
        description_es="Servicios para residentes de Emporia incluidos adultos con antecedentes penales; no es oficina de libertad condicional ni efectivo de emergencia salvo que se indique.",
        address="727 North Main Street", city="Emporia", phone="434-348-4400", email="",
        website="https://www.svrmc.org",
        eligibility="Residents of Emporia; justice-involved adults welcome where services allow.",
        eligibility_es="Residentes de Emporia; adultos con antecedentes penales bienvenidos donde los servicios lo permitan.",
        notes="Call 434-348-4400 or visit website for partner locations and hours.",
        notes_es="Llame al 434-348-4400 o visite el sitio web para ubicaciones y horarios de aliados.",
        hours="Contact for partner pantry or clinic hours",
        tags="emporia|healthcare|reentry|virginia",
        services="Primary care|Emergency referrals|Behavioral health referrals",
        county="Emporia", served_counties="Emporia", coverage="single",
        _source="https://www.svrmc.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Southern Virginia Regional Medical Center (serves Greensville County)",
        category="healthcare", region="Emporia / Greensville",
        description="Southern Virginia Regional Medical Center serves Greensville County residents with emergency and primary care including returning citizens establishing medical continuity. Not a probation office or emergency cash program unless noted.",
        description_es="Servicios para residentes de Greensville incluidos adultos con antecedentes penales; no es oficina de libertad condicional ni efectivo de emergencia salvo que se indique.",
        address="727 North Main Street", city="Emporia", phone="434-348-4400", email="",
        website="https://www.svrmc.org",
        eligibility="Residents of Greensville; justice-involved adults welcome where services allow.",
        eligibility_es="Residentes de Greensville; adultos con antecedentes penales bienvenidos donde los servicios lo permitan.",
        notes="Call 434-348-4400 or visit website for partner locations and hours.",
        notes_es="Llame al 434-348-4400 o visite el sitio web para ubicaciones y horarios de aliados.",
        hours="Contact for partner pantry or clinic hours",
        tags="greensville|healthcare|reentry|virginia",
        services="Primary care|Emergency referrals|Behavioral health referrals",
        county="Greensville", served_counties="Greensville", coverage="single",
        _source="https://www.svrmc.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Blue Ridge Area Food Bank — Highland County",
        category="food-nutrition", region="Monterey / Highland",
        description="Blue Ridge Area Food Bank connects Highland County residents facing food insecurity—including reentry populations—to pantry partners and SNAP application assistance. Not a probation office or emergency cash program unless noted.",
        description_es="Servicios para residentes de Highland incluidos adultos con antecedentes penales; no es oficina de libertad condicional ni efectivo de emergencia salvo que se indique.",
        address="Partner pantry network", city="Monterey", phone="540-248-3663", email="",
        website="https://www.brafb.org",
        eligibility="Residents of Highland; justice-involved adults welcome where services allow.",
        eligibility_es="Residentes de Highland; adultos con antecedentes penales bienvenidos donde los servicios lo permitan.",
        notes="Call 540-248-3663 or visit website for partner locations and hours.",
        notes_es="Llame al 540-248-3663 o visite el sitio web para ubicaciones y horarios de aliados.",
        hours="Contact for partner pantry or clinic hours",
        tags="highland|food-nutrition|reentry|virginia",
        services="Food pantry referrals|SNAP application help|Nutrition programs",
        county="Highland", served_counties="Highland", coverage="single",
        _source="https://www.brafb.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Riverside Health System — Peninsula Care (serves Poquoson)",
        category="healthcare", region="Newport News / Poquoson",
        description="Riverside Health serves Poquoson and Virginia Peninsula residents with primary care and emergency referrals including Medicaid and uninsured patients. Not a probation office or emergency cash program unless noted.",
        description_es="Servicios para residentes de Poquoson incluidos adultos con antecedentes penales; no es oficina de libertad condicional ni efectivo de emergencia salvo que se indique.",
        address="500 J Clyde Morris Boulevard", city="Newport News", phone="757-534-5000", email="",
        website="https://www.riversideonline.com",
        eligibility="Residents of Poquoson; justice-involved adults welcome where services allow.",
        eligibility_es="Residentes de Poquoson; adultos con antecedentes penales bienvenidos donde los servicios lo permitan.",
        notes="Call 757-534-5000 or visit website for partner locations and hours.",
        notes_es="Llame al 757-534-5000 o visite el sitio web para ubicaciones y horarios de aliados.",
        hours="Contact for partner pantry or clinic hours",
        tags="poquoson|healthcare|reentry|virginia",
        services="Primary care|Emergency referrals|Behavioral health referrals",
        county="Poquoson", served_counties="Poquoson", coverage="single",
        _source="https://www.riversideonline.com", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Blue Ridge Area Food Bank — Rockingham County",
        category="food-nutrition", region="Harrisonburg / Rockingham",
        description="Blue Ridge Area Food Bank partner network serves Rockingham County residents with food assistance and SNAP navigation for households including returning citizens. Not a probation office or emergency cash program unless noted.",
        description_es="Servicios para residentes de Rockingham incluidos adultos con antecedentes penales; no es oficina de libertad condicional ni efectivo de emergencia salvo que se indique.",
        address="Partner pantry network", city="Harrisonburg", phone="540-248-3663", email="",
        website="https://www.brafb.org",
        eligibility="Residents of Rockingham; justice-involved adults welcome where services allow.",
        eligibility_es="Residentes de Rockingham; adultos con antecedentes penales bienvenidos donde los servicios lo permitan.",
        notes="Call 540-248-3663 or visit website for partner locations and hours.",
        notes_es="Llame al 540-248-3663 o visite el sitio web para ubicaciones y horarios de aliados.",
        hours="Contact for partner pantry or clinic hours",
        tags="rockingham|food-nutrition|reentry|virginia",
        services="Food pantry referrals|SNAP application help|Nutrition programs",
        county="Rockingham", served_counties="Rockingham", coverage="single",
        _source="https://www.brafb.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Blue Ridge Area Food Bank — Winchester",
        category="food-nutrition", region="Winchester / Winchester",
        description="Blue Ridge Area Food Bank Winchester distribution center connects Frederick and Winchester area residents to food pantry partners and benefits navigation. Not a probation office or emergency cash program unless noted.",
        description_es="Servicios para residentes de Winchester incluidos adultos con antecedentes penales; no es oficina de libertad condicional ni efectivo de emergencia salvo que se indique.",
        address="96 Laurel Hill Road", city="Winchester", phone="540-248-3663", email="",
        website="https://www.brafb.org",
        eligibility="Residents of Winchester; justice-involved adults welcome where services allow.",
        eligibility_es="Residentes de Winchester; adultos con antecedentes penales bienvenidos donde los servicios lo permitan.",
        notes="Call 540-248-3663 or visit website for partner locations and hours.",
        notes_es="Llame al 540-248-3663 o visite el sitio web para ubicaciones y horarios de aliados.",
        hours="Contact for partner pantry or clinic hours",
        tags="winchester|food-nutrition|reentry|virginia",
        services="Food pantry referrals|SNAP application help|Nutrition programs",
        county="Winchester", served_counties="Winchester", coverage="single",
        _source="https://www.brafb.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Riverside Shore Memorial Hospital (serves Accomack County)",
        category="healthcare", region="Nassawadox / Accomack",
        description="Riverside Shore Memorial Hospital provides Eastern Shore healthcare for Accomack County residents including uninsured and justice-involved adults. Not a probation office or emergency cash program unless noted.",
        description_es="Servicios para residentes de Accomack incluidos adultos con antecedentes penales; no es oficina de libertad condicional ni efectivo de emergencia salvo que se indique.",
        address="20480 Market Street", city="Nassawadox", phone="757-442-6600", email="",
        website="https://www.riversideonline.com",
        eligibility="Residents of Accomack; justice-involved adults welcome where services allow.",
        eligibility_es="Residentes de Accomack; adultos con antecedentes penales bienvenidos donde los servicios lo permitan.",
        notes="Call 757-442-6600 or visit website for partner locations and hours.",
        notes_es="Llame al 757-442-6600 o visite el sitio web para ubicaciones y horarios de aliados.",
        hours="Contact for partner pantry or clinic hours",
        tags="accomack|healthcare|reentry|virginia",
        services="Primary care|Emergency referrals|Behavioral health referrals",
        county="Accomack", served_counties="Accomack", coverage="single",
        _source="https://www.riversideonline.com", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Southside Community Services Board — Amelia Outreach",
        category="healthcare", region="Amelia Court House / Amelia",
        description="Southside CSB provides behavioral health and referrals for Amelia County residents including returning citizens needing SUD and mental health services. Not a probation office or emergency cash program unless noted.",
        description_es="Servicios para residentes de Amelia incluidos adultos con antecedentes penales; no es oficina de libertad condicional ni efectivo de emergencia salvo que se indique.",
        address="Contact CSB for clinic site", city="Amelia Court House", phone="434-392-2066", email="",
        website="https://www.sscsb.org",
        eligibility="Residents of Amelia; justice-involved adults welcome where services allow.",
        eligibility_es="Residentes de Amelia; adultos con antecedentes penales bienvenidos donde los servicios lo permitan.",
        notes="Call 434-392-2066 or visit website for partner locations and hours.",
        notes_es="Llame al 434-392-2066 o visite el sitio web para ubicaciones y horarios de aliados.",
        hours="Contact for partner pantry or clinic hours",
        tags="amelia|healthcare|reentry|virginia",
        services="Primary care|Emergency referrals|Behavioral health referrals",
        county="Amelia", served_counties="Amelia", coverage="single",
        _source="https://www.sscsb.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Blue Ridge Area Food Bank — Buckingham County",
        category="food-nutrition", region="Dillwyn / Buckingham",
        description="Blue Ridge Area Food Bank partners serve Buckingham County residents with food assistance and SNAP application help. Not a probation office or emergency cash program unless noted.",
        description_es="Servicios para residentes de Buckingham incluidos adultos con antecedentes penales; no es oficina de libertad condicional ni efectivo de emergencia salvo que se indique.",
        address="Partner pantry network", city="Dillwyn", phone="540-248-3663", email="",
        website="https://www.brafb.org",
        eligibility="Residents of Buckingham; justice-involved adults welcome where services allow.",
        eligibility_es="Residentes de Buckingham; adultos con antecedentes penales bienvenidos donde los servicios lo permitan.",
        notes="Call 540-248-3663 or visit website for partner locations and hours.",
        notes_es="Llame al 540-248-3663 o visite el sitio web para ubicaciones y horarios de aliados.",
        hours="Contact for partner pantry or clinic hours",
        tags="buckingham|food-nutrition|reentry|virginia",
        services="Food pantry referrals|SNAP application help|Nutrition programs",
        county="Buckingham", served_counties="Buckingham", coverage="single",
        _source="https://www.brafb.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Blue Ridge Area Food Bank — Buena Vista",
        category="food-nutrition", region="Buena Vista / Buena Vista",
        description="Blue Ridge Area Food Bank connects Buena Vista residents to pantry partners and nutrition programs. Not a probation office or emergency cash program unless noted.",
        description_es="Servicios para residentes de Buena Vista incluidos adultos con antecedentes penales; no es oficina de libertad condicional ni efectivo de emergencia salvo que se indique.",
        address="Partner pantry network", city="Buena Vista", phone="540-248-3663", email="",
        website="https://www.brafb.org",
        eligibility="Residents of Buena Vista; justice-involved adults welcome where services allow.",
        eligibility_es="Residentes de Buena Vista; adultos con antecedentes penales bienvenidos donde los servicios lo permitan.",
        notes="Call 540-248-3663 or visit website for partner locations and hours.",
        notes_es="Llame al 540-248-3663 o visite el sitio web para ubicaciones y horarios de aliados.",
        hours="Contact for partner pantry or clinic hours",
        tags="buena-vista|food-nutrition|reentry|virginia",
        services="Food pantry referrals|SNAP application help|Nutrition programs",
        county="Buena Vista", served_counties="Buena Vista", coverage="single",
        _source="https://www.brafb.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Blue Ridge Area Food Bank — Clarke County",
        category="food-nutrition", region="Berryville / Clarke",
        description="Blue Ridge Area Food Bank serves Clarke County through partner pantries and mobile distributions. Not a probation office or emergency cash program unless noted.",
        description_es="Servicios para residentes de Clarke incluidos adultos con antecedentes penales; no es oficina de libertad condicional ni efectivo de emergencia salvo que se indique.",
        address="Partner pantry network", city="Berryville", phone="540-248-3663", email="",
        website="https://www.brafb.org",
        eligibility="Residents of Clarke; justice-involved adults welcome where services allow.",
        eligibility_es="Residentes de Clarke; adultos con antecedentes penales bienvenidos donde los servicios lo permitan.",
        notes="Call 540-248-3663 or visit website for partner locations and hours.",
        notes_es="Llame al 540-248-3663 o visite el sitio web para ubicaciones y horarios de aliados.",
        hours="Contact for partner pantry or clinic hours",
        tags="clarke|food-nutrition|reentry|virginia",
        services="Food pantry referrals|SNAP application help|Nutrition programs",
        county="Clarke", served_counties="Clarke", coverage="single",
        _source="https://www.brafb.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Feed More — Essex County Pantry Partners",
        category="food-nutrition", region="Tappahannock / Essex",
        description="Feed More connects Essex County residents to partner food pantries and SNAP application assistance across the Northern Neck. Not a probation office or emergency cash program unless noted.",
        description_es="Servicios para residentes de Essex incluidos adultos con antecedentes penales; no es oficina de libertad condicional ni efectivo de emergencia salvo que se indique.",
        address="Partner pantry network", city="Tappahannock", phone="804-521-2500", email="",
        website="https://feedmore.org",
        eligibility="Residents of Essex; justice-involved adults welcome where services allow.",
        eligibility_es="Residentes de Essex; adultos con antecedentes penales bienvenidos donde los servicios lo permitan.",
        notes="Call 804-521-2500 or visit website for partner locations and hours.",
        notes_es="Llame al 804-521-2500 o visite el sitio web para ubicaciones y horarios de aliados.",
        hours="Contact for partner pantry or clinic hours",
        tags="essex|food-nutrition|reentry|virginia",
        services="Food pantry referrals|SNAP application help|Nutrition programs",
        county="Essex", served_counties="Essex", coverage="single",
        _source="https://feedmore.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Blue Ridge Area Food Bank — Frederick County",
        category="food-nutrition", region="Winchester / Frederick",
        description="Blue Ridge Area Food Bank serves Frederick County residents through pantry partners and mobile food distributions. Not a probation office or emergency cash program unless noted.",
        description_es="Servicios para residentes de Frederick incluidos adultos con antecedentes penales; no es oficina de libertad condicional ni efectivo de emergencia salvo que se indique.",
        address="96 Laurel Hill Road", city="Winchester", phone="540-248-3663", email="",
        website="https://www.brafb.org",
        eligibility="Residents of Frederick; justice-involved adults welcome where services allow.",
        eligibility_es="Residentes de Frederick; adultos con antecedentes penales bienvenidos donde los servicios lo permitan.",
        notes="Call 540-248-3663 or visit website for partner locations and hours.",
        notes_es="Llame al 540-248-3663 o visite el sitio web para ubicaciones y horarios de aliados.",
        hours="Contact for partner pantry or clinic hours",
        tags="frederick|food-nutrition|reentry|virginia",
        services="Food pantry referrals|SNAP application help|Nutrition programs",
        county="Frederick", served_counties="Frederick", coverage="single",
        _source="https://www.brafb.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Riverside Walter Reed Hospital (serves Gloucester County)",
        category="healthcare", region="Gloucester / Gloucester",
        description="Riverside Walter Reed Hospital provides Gloucester County residents emergency and outpatient services including Medicaid patients. Not a probation office or emergency cash program unless noted.",
        description_es="Servicios para residentes de Gloucester incluidos adultos con antecedentes penales; no es oficina de libertad condicional ni efectivo de emergencia salvo que se indique.",
        address="7547 Medical Drive", city="Gloucester", phone="804-693-8800", email="",
        website="https://www.riversideonline.com",
        eligibility="Residents of Gloucester; justice-involved adults welcome where services allow.",
        eligibility_es="Residentes de Gloucester; adultos con antecedentes penales bienvenidos donde los servicios lo permitan.",
        notes="Call 804-693-8800 or visit website for partner locations and hours.",
        notes_es="Llame al 804-693-8800 o visite el sitio web para ubicaciones y horarios de aliados.",
        hours="Contact for partner pantry or clinic hours",
        tags="gloucester|healthcare|reentry|virginia",
        services="Primary care|Emergency referrals|Behavioral health referrals",
        county="Gloucester", served_counties="Gloucester", coverage="single",
        _source="https://www.riversideonline.com", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Blue Ridge Area Food Bank — Lexington",
        category="food-nutrition", region="Lexington / Lexington",
        description="Blue Ridge Area Food Bank connects Lexington city residents to pantry partners and nutrition programs. Not a probation office or emergency cash program unless noted.",
        description_es="Servicios para residentes de Lexington incluidos adultos con antecedentes penales; no es oficina de libertad condicional ni efectivo de emergencia salvo que se indique.",
        address="Partner pantry network", city="Lexington", phone="540-248-3663", email="",
        website="https://www.brafb.org",
        eligibility="Residents of Lexington; justice-involved adults welcome where services allow.",
        eligibility_es="Residentes de Lexington; adultos con antecedentes penales bienvenidos donde los servicios lo permitan.",
        notes="Call 540-248-3663 or visit website for partner locations and hours.",
        notes_es="Llame al 540-248-3663 o visite el sitio web para ubicaciones y horarios de aliados.",
        hours="Contact for partner pantry or clinic hours",
        tags="lexington|food-nutrition|reentry|virginia",
        services="Food pantry referrals|SNAP application help|Nutrition programs",
        county="Lexington", served_counties="Lexington", coverage="single",
        _source="https://www.brafb.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Riverside Health — Mathews County Primary Care",
        category="healthcare", region="Mathews / Mathews",
        description="Riverside Health primary care network serves Mathews County residents including returning citizens on the Middle Peninsula. Not a probation office or emergency cash program unless noted.",
        description_es="Servicios para residentes de Mathews incluidos adultos con antecedentes penales; no es oficina de libertad condicional ni efectivo de emergencia salvo que se indique.",
        address="Contact Riverside for clinic", city="Mathews", phone="757-534-5000", email="",
        website="https://www.riversideonline.com",
        eligibility="Residents of Mathews; justice-involved adults welcome where services allow.",
        eligibility_es="Residentes de Mathews; adultos con antecedentes penales bienvenidos donde los servicios lo permitan.",
        notes="Call 757-534-5000 or visit website for partner locations and hours.",
        notes_es="Llame al 757-534-5000 o visite el sitio web para ubicaciones y horarios de aliados.",
        hours="Contact for partner pantry or clinic hours",
        tags="mathews|healthcare|reentry|virginia",
        services="Primary care|Emergency referrals|Behavioral health referrals",
        county="Mathews", served_counties="Mathews", coverage="single",
        _source="https://www.riversideonline.com", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Riverside Health — Middlesex County",
        category="healthcare", region="Saluda / Middlesex",
        description="Riverside Health serves Middlesex County with primary care referrals and emergency services access. Not a probation office or emergency cash program unless noted.",
        description_es="Servicios para residentes de Middlesex incluidos adultos con antecedentes penales; no es oficina de libertad condicional ni efectivo de emergencia salvo que se indique.",
        address="Contact Riverside for clinic", city="Saluda", phone="757-534-5000", email="",
        website="https://www.riversideonline.com",
        eligibility="Residents of Middlesex; justice-involved adults welcome where services allow.",
        eligibility_es="Residentes de Middlesex; adultos con antecedentes penales bienvenidos donde los servicios lo permitan.",
        notes="Call 757-534-5000 or visit website for partner locations and hours.",
        notes_es="Llame al 757-534-5000 o visite el sitio web para ubicaciones y horarios de aliados.",
        hours="Contact for partner pantry or clinic hours",
        tags="middlesex|healthcare|reentry|virginia",
        services="Primary care|Emergency referrals|Behavioral health referrals",
        county="Middlesex", served_counties="Middlesex", coverage="single",
        _source="https://www.riversideonline.com", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Riverside Shore Memorial Hospital (serves Northampton County)",
        category="healthcare", region="Nassawadox / Northampton",
        description="Riverside Shore Memorial Hospital serves Northampton County Eastern Shore residents including justice-involved adults. Not a probation office or emergency cash program unless noted.",
        description_es="Servicios para residentes de Northampton incluidos adultos con antecedentes penales; no es oficina de libertad condicional ni efectivo de emergencia salvo que se indique.",
        address="20480 Market Street", city="Nassawadox", phone="757-442-6600", email="",
        website="https://www.riversideonline.com",
        eligibility="Residents of Northampton; justice-involved adults welcome where services allow.",
        eligibility_es="Residentes de Northampton; adultos con antecedentes penales bienvenidos donde los servicios lo permitan.",
        notes="Call 757-442-6600 or visit website for partner locations and hours.",
        notes_es="Llame al 757-442-6600 o visite el sitio web para ubicaciones y horarios de aliados.",
        hours="Contact for partner pantry or clinic hours",
        tags="northampton|healthcare|reentry|virginia",
        services="Primary care|Emergency referrals|Behavioral health referrals",
        county="Northampton", served_counties="Northampton", coverage="single",
        _source="https://www.riversideonline.com", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Blue Ridge Area Food Bank — Page County",
        category="food-nutrition", region="Luray / Page",
        description="Blue Ridge Area Food Bank partner pantries serve Page County residents with food assistance and SNAP help. Not a probation office or emergency cash program unless noted.",
        description_es="Servicios para residentes de Page incluidos adultos con antecedentes penales; no es oficina de libertad condicional ni efectivo de emergencia salvo que se indique.",
        address="Partner pantry network", city="Luray", phone="540-248-3663", email="",
        website="https://www.brafb.org",
        eligibility="Residents of Page; justice-involved adults welcome where services allow.",
        eligibility_es="Residentes de Page; adultos con antecedentes penales bienvenidos donde los servicios lo permitan.",
        notes="Call 540-248-3663 or visit website for partner locations and hours.",
        notes_es="Llame al 540-248-3663 o visite el sitio web para ubicaciones y horarios de aliados.",
        hours="Contact for partner pantry or clinic hours",
        tags="page|food-nutrition|reentry|virginia",
        services="Food pantry referrals|SNAP application help|Nutrition programs",
        county="Page", served_counties="Page", coverage="single",
        _source="https://www.brafb.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Blue Ridge Area Food Bank — Rockbridge County",
        category="food-nutrition", region="Lexington / Rockbridge",
        description="Blue Ridge Area Food Bank serves Rockbridge County through regional pantry partners. Not a probation office or emergency cash program unless noted.",
        description_es="Servicios para residentes de Rockbridge incluidos adultos con antecedentes penales; no es oficina de libertad condicional ni efectivo de emergencia salvo que se indique.",
        address="Partner pantry network", city="Lexington", phone="540-248-3663", email="",
        website="https://www.brafb.org",
        eligibility="Residents of Rockbridge; justice-involved adults welcome where services allow.",
        eligibility_es="Residentes de Rockbridge; adultos con antecedentes penales bienvenidos donde los servicios lo permitan.",
        notes="Call 540-248-3663 or visit website for partner locations and hours.",
        notes_es="Llame al 540-248-3663 o visite el sitio web para ubicaciones y horarios de aliados.",
        hours="Contact for partner pantry or clinic hours",
        tags="rockbridge|food-nutrition|reentry|virginia",
        services="Food pantry referrals|SNAP application help|Nutrition programs",
        county="Rockbridge", served_counties="Rockbridge", coverage="single",
        _source="https://www.brafb.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Blue Ridge Area Food Bank — Shenandoah County",
        category="food-nutrition", region="Woodstock / Shenandoah",
        description="Blue Ridge Area Food Bank connects Shenandoah County residents to food pantry partners and mobile distributions. Not a probation office or emergency cash program unless noted.",
        description_es="Servicios para residentes de Shenandoah incluidos adultos con antecedentes penales; no es oficina de libertad condicional ni efectivo de emergencia salvo que se indique.",
        address="Partner pantry network", city="Woodstock", phone="540-248-3663", email="",
        website="https://www.brafb.org",
        eligibility="Residents of Shenandoah; justice-involved adults welcome where services allow.",
        eligibility_es="Residentes de Shenandoah; adultos con antecedentes penales bienvenidos donde los servicios lo permitan.",
        notes="Call 540-248-3663 or visit website for partner locations and hours.",
        notes_es="Llame al 540-248-3663 o visite el sitio web para ubicaciones y horarios de aliados.",
        hours="Contact for partner pantry or clinic hours",
        tags="shenandoah|food-nutrition|reentry|virginia",
        services="Food pantry referrals|SNAP application help|Nutrition programs",
        county="Shenandoah", served_counties="Shenandoah", coverage="single",
        _source="https://www.brafb.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Southern Virginia Regional Medical Center (serves Sussex County)",
        category="healthcare", region="Emporia / Sussex",
        description="Southern Virginia Regional Medical Center provides healthcare access for Sussex County residents including returning citizens. Not a probation office or emergency cash program unless noted.",
        description_es="Servicios para residentes de Sussex incluidos adultos con antecedentes penales; no es oficina de libertad condicional ni efectivo de emergencia salvo que se indique.",
        address="727 North Main Street", city="Emporia", phone="434-348-4400", email="",
        website="https://www.svrmc.org",
        eligibility="Residents of Sussex; justice-involved adults welcome where services allow.",
        eligibility_es="Residentes de Sussex; adultos con antecedentes penales bienvenidos donde los servicios lo permitan.",
        notes="Call 434-348-4400 or visit website for partner locations and hours.",
        notes_es="Llame al 434-348-4400 o visite el sitio web para ubicaciones y horarios de aliados.",
        hours="Contact for partner pantry or clinic hours",
        tags="sussex|healthcare|reentry|virginia",
        services="Primary care|Emergency referrals|Behavioral health referrals",
        county="Sussex", served_counties="Sussex", coverage="single",
        _source="https://www.svrmc.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Blue Ridge Area Food Bank — Warren County",
        category="food-nutrition", region="Front Royal / Warren",
        description="Blue Ridge Area Food Bank serves Warren County residents through partner pantries and nutrition programs. Not a probation office or emergency cash program unless noted.",
        description_es="Servicios para residentes de Warren incluidos adultos con antecedentes penales; no es oficina de libertad condicional ni efectivo de emergencia salvo que se indique.",
        address="Partner pantry network", city="Front Royal", phone="540-248-3663", email="",
        website="https://www.brafb.org",
        eligibility="Residents of Warren; justice-involved adults welcome where services allow.",
        eligibility_es="Residentes de Warren; adultos con antecedentes penales bienvenidos donde los servicios lo permitan.",
        notes="Call 540-248-3663 or visit website for partner locations and hours.",
        notes_es="Llame al 540-248-3663 o visite el sitio web para ubicaciones y horarios de aliados.",
        hours="Contact for partner pantry or clinic hours",
        tags="warren|food-nutrition|reentry|virginia",
        services="Food pantry referrals|SNAP application help|Nutrition programs",
        county="Warren", served_counties="Warren", coverage="single",
        _source="https://www.brafb.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Blue Ridge Area Food Bank — Alleghany County",
        category="food-nutrition", region="Covington / Alleghany",
        description="Blue Ridge Area Food Bank partner network serves Alleghany County residents with food assistance. Not a probation office or emergency cash program unless noted.",
        description_es="Servicios para residentes de Alleghany incluidos adultos con antecedentes penales; no es oficina de libertad condicional ni efectivo de emergencia salvo que se indique.",
        address="Partner pantry network", city="Covington", phone="540-248-3663", email="",
        website="https://www.brafb.org",
        eligibility="Residents of Alleghany; justice-involved adults welcome where services allow.",
        eligibility_es="Residentes de Alleghany; adultos con antecedentes penales bienvenidos donde los servicios lo permitan.",
        notes="Call 540-248-3663 or visit website for partner locations and hours.",
        notes_es="Llame al 540-248-3663 o visite el sitio web para ubicaciones y horarios de aliados.",
        hours="Contact for partner pantry or clinic hours",
        tags="alleghany|food-nutrition|reentry|virginia",
        services="Food pantry referrals|SNAP application help|Nutrition programs",
        county="Alleghany", served_counties="Alleghany", coverage="single",
        _source="https://www.brafb.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Blue Ridge Area Food Bank — Covington",
        category="food-nutrition", region="Covington / Covington",
        description="Blue Ridge Area Food Bank connects Covington city residents to pantry partners and SNAP navigation. Not a probation office or emergency cash program unless noted.",
        description_es="Servicios para residentes de Covington incluidos adultos con antecedentes penales; no es oficina de libertad condicional ni efectivo de emergencia salvo que se indique.",
        address="Partner pantry network", city="Covington", phone="540-248-3663", email="",
        website="https://www.brafb.org",
        eligibility="Residents of Covington; justice-involved adults welcome where services allow.",
        eligibility_es="Residentes de Covington; adultos con antecedentes penales bienvenidos donde los servicios lo permitan.",
        notes="Call 540-248-3663 or visit website for partner locations and hours.",
        notes_es="Llame al 540-248-3663 o visite el sitio web para ubicaciones y horarios de aliados.",
        hours="Contact for partner pantry or clinic hours",
        tags="covington|food-nutrition|reentry|virginia",
        services="Food pantry referrals|SNAP application help|Nutrition programs",
        county="Covington", served_counties="Covington", coverage="single",
        _source="https://www.brafb.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Blue Ridge Area Food Bank — Botetourt County",
        category="food-nutrition", region="Fincastle / Botetourt",
        description="Blue Ridge Area Food Bank serves Botetourt County through partner food pantries. Not a probation office or emergency cash program unless noted.",
        description_es="Servicios para residentes de Botetourt incluidos adultos con antecedentes penales; no es oficina de libertad condicional ni efectivo de emergencia salvo que se indique.",
        address="Partner pantry network", city="Fincastle", phone="540-248-3663", email="",
        website="https://www.brafb.org",
        eligibility="Residents of Botetourt; justice-involved adults welcome where services allow.",
        eligibility_es="Residentes de Botetourt; adultos con antecedentes penales bienvenidos donde los servicios lo permitan.",
        notes="Call 540-248-3663 or visit website for partner locations and hours.",
        notes_es="Llame al 540-248-3663 o visite el sitio web para ubicaciones y horarios de aliados.",
        hours="Contact for partner pantry or clinic hours",
        tags="botetourt|food-nutrition|reentry|virginia",
        services="Food pantry referrals|SNAP application help|Nutrition programs",
        county="Botetourt", served_counties="Botetourt", coverage="single",
        _source="https://www.brafb.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Blue Ridge Area Food Bank — Craig County",
        category="food-nutrition", region="New Castle / Craig",
        description="Blue Ridge Area Food Bank connects Craig County residents to regional pantry partners. Not a probation office or emergency cash program unless noted.",
        description_es="Servicios para residentes de Craig incluidos adultos con antecedentes penales; no es oficina de libertad condicional ni efectivo de emergencia salvo que se indique.",
        address="Partner pantry network", city="New Castle", phone="540-248-3663", email="",
        website="https://www.brafb.org",
        eligibility="Residents of Craig; justice-involved adults welcome where services allow.",
        eligibility_es="Residentes de Craig; adultos con antecedentes penales bienvenidos donde los servicios lo permitan.",
        notes="Call 540-248-3663 or visit website for partner locations and hours.",
        notes_es="Llame al 540-248-3663 o visite el sitio web para ubicaciones y horarios de aliados.",
        hours="Contact for partner pantry or clinic hours",
        tags="craig|food-nutrition|reentry|virginia",
        services="Food pantry referrals|SNAP application help|Nutrition programs",
        county="Craig", served_counties="Craig", coverage="single",
        _source="https://www.brafb.org", _source_type="nonprofit", _confidence="high",
    )
