"""Category minimum fill for Wisconsin reentry resources."""


def register_category_fill(add):
    # --- WDOC probation-parole field offices (regions) ---
    add(
        name="WDOC — Region 1 Probation & Parole (Milwaukee)",
        category="probation-parole", region="Milwaukee / Milwaukee County",
        description="WDOC Region 1 Probation and Parole supervises probationers, parolees, and extended supervision clients in Milwaukee, Waukesha, Washington, and Ozaukee counties, connecting justice-involved adults to Sixteenth Street Community Health Centers, Job Center of Wisconsin Milwaukee, and Wisconsin Community Services as conditions of release. Assigned agents handle compliance reporting and referrals—not emergency housing or FoodShare intake.",
        description_es="Probatoria y Libertad Condicional Región 1 de WDOC supervisa personas en probatoria, libertad condicional y supervisión extendida en los condados Milwaukee, Waukesha, Washington y Ozaukee, conectando adultos con antecedentes penales con aliados de reinserción locales.",
        address="6737 West Washington Street, Suite 2225", city="West Allis", phone="414-327-5800", email="",
        website="https://doc.wi.gov/Pages/OffenderInformation/ProbationParole.aspx",
        eligibility="Adults under WDOC probation, parole, or extended supervision in Region 1; report to assigned agent.",
        eligibility_es="Adultos bajo supervisión probatoria, de libertad condicional o supervisión extendida de WDOC en la Región 1; reporte al agente asignado.",
        notes="Call 414-327-5800; not a walk-in benefits or housing office; ask agent about local reentry referrals.",
        notes_es="Llame al 414-327-5800; no es oficina de beneficios o vivienda; pregunte al agente sobre referencias locales.",
        hours="Monday–Friday business hours",
        tags="milwaukee|probation-parole|WDOC|reentry",
        services="Probation supervision|Parole reporting|Treatment referrals|Employment compliance|Reentry partner linkage",
        county="Milwaukee", served_counties="Milwaukee|Waukesha|Washington|Ozaukee", coverage="multi",
        _source="https://doc.wi.gov/Pages/OffenderInformation/ProbationParole.aspx", _source_type="government", _confidence="high",
    )
    add(
        name="WDOC — Region 2 Probation & Parole (Kenosha/Racine)",
        category="probation-parole", region="Kenosha / Kenosha County",
        description="WDOC Region 2 Probation and Parole supervises clients in Kenosha and Racine counties, connecting supervisees to HALO Inc, Hope Center Racine, and Job Center of Wisconsin Kenosha as conditions of community supervision.",
        description_es="Probatoria y Libertad Condicional Región 2 de WDOC supervisa clientes en los condados Kenosha y Racine, conectando supervisados con HALO Inc, Hope Center Racine y Job Center Kenosha.",
        address="8600 Sheridan Road, Suite 200", city="Kenosha", phone="262-653-7200", email="",
        website="https://doc.wi.gov/Pages/OffenderInformation/ProbationParole.aspx",
        eligibility="Adults under WDOC supervision in Region 2; report to assigned agent.",
        eligibility_es="Adultos bajo supervisión WDOC en la Región 2; reporte al agente asignado.",
        notes="Call 262-653-7200; coordinate through assigned agent for reentry referrals.",
        notes_es="Llame al 262-653-7200; coordine a través del agente asignado.",
        hours="Monday–Friday business hours",
        tags="kenosha|racine|probation-parole|WDOC|reentry",
        services="Probation supervision|Parole reporting|Treatment referrals|Employment coordination|Reentry partner linkage",
        county="Kenosha", served_counties="Kenosha|Racine", coverage="multi",
        _source="https://doc.wi.gov/Pages/OffenderInformation/ProbationParole.aspx", _source_type="government", _confidence="high",
    )
    add(
        name="WDOC — Region 3 Probation & Parole (Madison)",
        category="probation-parole", region="Madison / Dane County",
        description="WDOC Region 3 Probation and Parole supervises clients in Dane and surrounding south-central Wisconsin counties, connecting supervisees to JustDane, Porchlight, and Job Center of Wisconsin Madison as conditions of release.",
        description_es="Probatoria y Libertad Condicional Región 3 de WDOC supervisa clientes en el condado Dane y condados del centro-sur de Wisconsin, conectando supervisados con JustDane, Porchlight y Job Center Madison.",
        address="4822 Madison Yards Way, Suite 200", city="Madison", phone="608-240-5900", email="",
        website="https://doc.wi.gov/Pages/OffenderInformation/ProbationParole.aspx",
        eligibility="Adults under WDOC supervision in Region 3; report to assigned agent.",
        eligibility_es="Adultos bajo supervisión WDOC en la Región 3; reporte al agente asignado.",
        notes="Call 608-240-5900; serves Dane, Rock, Green, and surrounding counties.",
        notes_es="Llame al 608-240-5900; sirve Dane, Rock, Green y condados circundantes.",
        hours="Monday–Friday business hours",
        tags="madison|dane|probation-parole|WDOC|reentry",
        services="Probation supervision|Parole reporting|Treatment referrals|Employment coordination|Reentry partner linkage",
        county="Dane", served_counties="Dane|Rock|Green|Iowa|Lafayette", coverage="multi",
        _source="https://doc.wi.gov/Pages/OffenderInformation/ProbationParole.aspx", _source_type="government", _confidence="high",
    )
    add(
        name="WDOC — Region 4 Probation & Parole (Appleton/Oshkosh)",
        category="probation-parole", region="Appleton / Outagamie County",
        description="WDOC Region 4 Probation and Parole supervises clients in the Fox Valley including Outagamie, Winnebago, and Calumet counties, connecting supervisees to Freedom House, Job Center Appleton, and Libertas Treatment Center partners.",
        description_es="Probatoria y Libertad Condicional Región 4 de WDOC supervisa clientes en el Valle Fox incluidos los condados Outagamie, Winnebago y Calumet, conectando supervisados con Freedom House y Job Center Appleton.",
        address="1800 Appleton Road, Suite 200", city="Menasha", phone="920-720-5601", email="",
        website="https://doc.wi.gov/Pages/OffenderInformation/ProbationParole.aspx",
        eligibility="Adults under WDOC supervision in Region 4; report to assigned agent.",
        eligibility_es="Adultos bajo supervisión WDOC en la Región 4; reporte al agente asignado.",
        notes="Call 920-720-5601; Fox Valley regional office in Menasha.",
        notes_es="Llame al 920-720-5601; oficina regional del Valle Fox en Menasha.",
        hours="Monday–Friday business hours",
        tags="appleton|outagamie|probation-parole|WDOC|reentry",
        services="Probation supervision|Parole reporting|Treatment referrals|Employment coordination|Reentry partner linkage",
        county="Outagamie", served_counties="Outagamie|Winnebago|Calumet|Fond du Lac|Waushara", coverage="multi",
        _source="https://doc.wi.gov/Pages/OffenderInformation/ProbationParole.aspx", _source_type="government", _confidence="high",
    )
    add(
        name="WDOC — Region 5 Probation & Parole (Green Bay)",
        category="probation-parole", region="Green Bay / Brown County",
        description="WDOC Region 5 Probation and Parole supervises clients in Brown, Door, Kewaunee, and northeast Wisconsin counties, connecting supervisees to NEW Community Shelter, Job Center Green Bay, and county DHS benefits offices.",
        description_es="Probatoria y Libertad Condicional Región 5 de WDOC supervisa clientes en Brown, Door, Kewaunee y condados del noreste de Wisconsin, conectando supervisados con NEW Community Shelter y Job Center Green Bay.",
        address="701 Cherry Street, Suite 200", city="Green Bay", phone="920-448-5200", email="",
        website="https://doc.wi.gov/Pages/OffenderInformation/ProbationParole.aspx",
        eligibility="Adults under WDOC supervision in Region 5; report to assigned agent.",
        eligibility_es="Adultos bajo supervisión WDOC en la Región 5; reporte al agente asignado.",
        notes="Call 920-448-5200; serves Brown, Door, Kewaunee, and surrounding northeast counties.",
        notes_es="Llame al 920-448-5200; sirve Brown, Door, Kewaunee y condados del noreste circundantes.",
        hours="Monday–Friday business hours",
        tags="green-bay|brown|probation-parole|WDOC|reentry",
        services="Probation supervision|Parole reporting|Treatment referrals|Employment coordination|Reentry partner linkage",
        county="Brown", served_counties="Brown|Door|Kewaunee|Oconto|Marinette", coverage="multi",
        _source="https://doc.wi.gov/Pages/OffenderInformation/ProbationParole.aspx", _source_type="government", _confidence="high",
    )
    add(
        name="WDOC — Region 6 Probation & Parole (La Crosse)",
        category="probation-parole", region="La Crosse / La Crosse County",
        description="WDOC Region 6 Probation and Parole supervises clients in La Crosse and western Wisconsin counties, connecting supervisees to Couleecap, Job Center La Crosse, and regional behavioral health providers as conditions of community supervision.",
        description_es="Probatoria y Libertad Condicional Región 6 de WDOC supervisa clientes en La Crosse y condados del oeste de Wisconsin, conectando supervisados con Couleecap y Job Center La Crosse.",
        address="300 North 4th Street, Suite 200", city="La Crosse", phone="608-785-9000", email="",
        website="https://doc.wi.gov/Pages/OffenderInformation/ProbationParole.aspx",
        eligibility="Adults under WDOC supervision in Region 6; report to assigned agent.",
        eligibility_es="Adultos bajo supervisión WDOC en la Región 6; reporte al agente asignado.",
        notes="Call 608-785-9000; serves La Crosse, Vernon, Monroe, and surrounding western counties.",
        notes_es="Llame al 608-785-9000; sirve La Crosse, Vernon, Monroe y condados del oeste circundantes.",
        hours="Monday–Friday business hours",
        tags="la-crosse|probation-parole|WDOC|reentry",
        services="Probation supervision|Parole reporting|Treatment referrals|Employment coordination|Reentry partner linkage",
        county="La Crosse", served_counties="La Crosse|Vernon|Monroe|Crawford|Buffalo", coverage="multi",
        _source="https://doc.wi.gov/Pages/OffenderInformation/ProbationParole.aspx", _source_type="government", _confidence="high",
    )
    add(
        name="WDOC — Region 7 Probation & Parole (Eau Claire)",
        category="probation-parole", region="Eau Claire / Eau Claire County",
        description="WDOC Region 7 Probation and Parole supervises clients in Eau Claire and northwest Wisconsin counties, connecting supervisees to Job Center Eau Claire, Western Wisconsin Community Action Agency, and county DHS offices as conditions of release.",
        description_es="Probatoria y Libertad Condicional Región 7 de WDOC supervisa clientes en Eau Claire y condados del noroeste de Wisconsin, conectando supervisados con Job Center Eau Claire y Western Wisconsin Community Action Agency.",
        address="221 West Madison Street, Suite 200", city="Eau Claire", phone="715-836-2800", email="",
        website="https://doc.wi.gov/Pages/OffenderInformation/ProbationParole.aspx",
        eligibility="Adults under WDOC supervision in Region 7; report to assigned agent.",
        eligibility_es="Adultos bajo supervisión WDOC en la Región 7; reporte al agente asignado.",
        notes="Call 715-836-2800; serves Eau Claire, Chippewa, Barron, and surrounding northwest counties.",
        notes_es="Llame al 715-836-2800; sirve Eau Claire, Chippewa, Barron y condados del noroeste circundantes.",
        hours="Monday–Friday business hours",
        tags="eau-claire|probation-parole|WDOC|reentry",
        services="Probation supervision|Parole reporting|Treatment referrals|Employment coordination|Reentry partner linkage",
        county="Eau Claire", served_counties="Eau Claire|Chippewa|Barron|Dunn|Clark|Taylor", coverage="multi",
        _source="https://doc.wi.gov/Pages/OffenderInformation/ProbationParole.aspx", _source_type="government", _confidence="high",
    )
    add(
        name="WDOC — Region 8 Probation & Parole (Wausau)",
        category="probation-parole", region="Wausau / Marathon County",
        description="WDOC Region 8 Probation and Parole supervises clients in Marathon, Portage, Wood, and north-central Wisconsin counties, connecting supervisees to Wisconsin Judicare, Job Center Wausau, and regional treatment providers as conditions of community supervision.",
        description_es="Probatoria y Libertad Condicional Región 8 de WDOC supervisa clientes en Marathon, Portage, Wood y condados del centro-norte de Wisconsin, conectando supervisados con Wisconsin Judicare y Job Center Wausau.",
        address="730 North Third Street, Suite 200", city="Wausau", phone="715-845-6200", email="",
        website="https://doc.wi.gov/Pages/OffenderInformation/ProbationParole.aspx",
        eligibility="Adults under WDOC supervision in Region 8; report to assigned agent.",
        eligibility_es="Adultos bajo supervisión WDOC en la Región 8; reporte al agente asignado.",
        notes="Call 715-845-6200; serves Marathon, Portage, Wood, and surrounding north-central counties.",
        notes_es="Llame al 715-845-6200; sirve Marathon, Portage, Wood y condados del centro-norte circundantes.",
        hours="Monday–Friday business hours",
        tags="wausau|marathon|probation-parole|WDOC|reentry",
        services="Probation supervision|Parole reporting|Treatment referrals|Employment coordination|Reentry partner linkage",
        county="Marathon", served_counties="Marathon|Portage|Wood|Lincoln|Langlade", coverage="multi",
        _source="https://doc.wi.gov/Pages/OffenderInformation/ProbationParole.aspx", _source_type="government", _confidence="high",
    )

    # --- regional food banks (also in phase4 but category fill ensures minimum) ---
    add(
        name="Feeding America Eastern Wisconsin — Fox Valley",
        category="food-nutrition", region="Green Bay / Brown County",
        description="Feeding America Eastern Wisconsin serves northeast and Fox Valley partner pantries supplying emergency food to low-income households in Brown, Outagamie, and Winnebago counties including returning citizens awaiting FoodShare through ACCESS Wisconsin. Use the online pantry locator to find the nearest partner site—not a central walk-in warehouse for individuals.",
        description_es="Feeding America Eastern Wisconsin sirve despensas aliadas del noreste y Valle Fox que suministran alimentos de emergencia a hogares de bajos ingresos en los condados Brown, Outagamie y Winnebago incluidos ciudadanos que regresan en espera de FoodShare a través de ACCESS Wisconsin.",
        address="3200 North 36th Street", city="Milwaukee", phone="920-973-1709", email="",
        website="https://feedingamericawi.org",
        eligibility="Partner pantries serve low-income northeast Wisconsin residents; no criminal-record restrictions at partner sites.",
        eligibility_es="Las despensas aliadas sirven a residentes de bajos ingresos del noreste de Wisconsin; sin restricciones de antecedentes en sitios aliados.",
        notes="Use feedingamericawi.org pantry locator for Green Bay and Fox Valley sites.",
        notes_es="Use el localizador de despensas en feedingamericawi.org para sitios de Green Bay y Valle Fox.",
        hours="Partner pantry hours vary",
        tags="green-bay|food-nutrition|food-bank|fox-valley|reentry",
        services="Food pantry network|Mobile food distribution|Partner agency supply|Pantry locator",
        county="Brown", served_counties="Brown|Outagamie|Winnebago|Calumet|Door", coverage="multi",
        _source="https://feedingamericawi.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Second Harvest Foodbank — Northwestern Wisconsin",
        category="food-nutrition", region="Eau Claire / Eau Claire County",
        description="Second Harvest Foodbank northwestern Wisconsin partner network supplies emergency food pantries across Eau Claire, Chippewa, and Barron counties for low-income households including justice-involved adults reestablishing food security after release. Pantry finder online—not direct individual warehouse walk-in.",
        description_es="La red de aliados de Second Harvest Foodbank del noroeste de Wisconsin abastece despensas de alimentos de emergencia en los condados Eau Claire, Chippewa y Barron para hogares de bajos ingresos incluidos adultos con antecedentes penales que restablecen seguridad alimentaria después de la liberación.",
        address="702 Signal Point Road", city="Madison", phone="608-216-7200", email="",
        website="https://www.secondharvestmadison.org",
        eligibility="Partner pantries serve low-income northwest Wisconsin residents; no criminal-record restrictions at partner sites.",
        eligibility_es="Las despensas aliadas sirven a residentes de bajos ingresos del noroeste de Wisconsin; sin restricciones de antecedentes en sitios aliados.",
        notes="Use secondharvestmadison.org pantry finder for Eau Claire area sites.",
        notes_es="Use el buscador de despensas en secondharvestmadison.org para sitios del área de Eau Claire.",
        hours="Partner pantry hours vary",
        tags="eau-claire|food-nutrition|food-bank|northwest-wisconsin|reentry",
        services="Food pantry network|Mobile pantry distribution|Partner agency supply|Pantry finder",
        county="Eau Claire", served_counties="Eau Claire|Chippewa|Barron|Dunn|Clark", coverage="multi",
        _source="https://www.secondharvestmadison.org", _source_type="nonprofit", _confidence="high",
    )

    # --- GED / adult education ---
    add(
        name="Milwaukee Area Technical College — Adult Education",
        category="education", region="Milwaukee / Milwaukee County",
        description="Milwaukee Area Technical College Adult Education provides free GED and High School Equivalency Diploma preparation, English language classes, and workforce credential pathways for Milwaukee County adults including returning citizens rebuilding credentials for Job Center of Wisconsin and employer requirements.",
        description_es="Milwaukee Area Technical College Educación para Adultos ofrece preparación GED y Diploma de Equivalencia de Secundaria gratuita, clases de inglés y vías de credenciales laborales para adultos del condado Milwaukee incluidos ciudadanos que regresan que reconstruyen credenciales.",
        address="700 West State Street", city="Milwaukee", phone="414-297-7471", email="",
        website="https://www.matc.edu",
        eligibility="Milwaukee County adults age 18+; free HSE classes; orientation required.",
        eligibility_es="Adultos del condado Milwaukee de 18+ años; clases HSE gratuitas; se requiere orientación.",
        notes="Call 414-297-7471; multiple MATC campuses; pairs with Job Center Milwaukee.",
        notes_es="Llame al 414-297-7471; múltiples campus MATC; se vincula con Job Center Milwaukee.",
        hours="Class schedules vary by campus",
        tags="milwaukee|education|GED|ESL|reentry",
        services="GED preparation|High School Equivalency|English language classes|Workforce credentials|Career pathway referrals",
        county="Milwaukee", served_counties="Milwaukee|Waukesha|Washington|Ozaukee", coverage="multi",
        _source="https://www.matc.edu", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Madison College — Adult Basic Education",
        category="education", region="Madison / Dane County",
        description="Madison College Adult Basic Education offers free GED and High School Equivalency classes, English language instruction, and college transition support for Dane County adults including justice-involved learners at the Truax and regional campuses.",
        description_es="Madison College Educación Básica para Adultos ofrece clases GED y equivalencia de secundaria gratuitas, instrucción de inglés y apoyo de transición universitaria para adultos del condado Dane incluidos estudiantes con antecedentes penales.",
        address="1701 Wright Street", city="Madison", phone="608-243-4198", email="",
        website="https://madisoncollege.edu",
        eligibility="Dane County adults age 18+; free ABE and HSE classes; orientation required.",
        eligibility_es="Adultos del condado Dane de 18+ años; clases ABE y HSE gratuitas; se requiere orientación.",
        notes="Call 608-243-4198; Truax campus main ABE site; pairs with JustDane and Job Center Madison.",
        notes_es="Llame al 608-243-4198; campus Truax sitio principal ABE; se vincula con JustDane y Job Center Madison.",
        hours="Class schedules vary",
        tags="madison|dane|education|GED|ESL|reentry",
        services="GED preparation|High School Equivalency|English language classes|College transition|Career referrals",
        county="Dane", served_counties="Dane|Rock|Green|Iowa", coverage="multi",
        _source="https://madisoncollege.edu", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Fox Valley Technical College — Adult Education",
        category="education", region="Appleton / Outagamie County",
        description="Fox Valley Technical College Adult Education provides free GED preparation and English language classes for Outagamie and Winnebago county adults including returning citizens rebuilding credentials for Job Center of Wisconsin Appleton and regional employers.",
        description_es="Fox Valley Technical College Educación para Adultos ofrece preparación GED gratuita y clases de inglés para adultos de los condados Outagamie y Winnebago incluidos ciudadanos que regresan que reconstruyen credenciales para Job Center Appleton.",
        address="1825 North Bluemound Drive", city="Appleton", phone="920-735-5645", email="",
        website="https://www.fvtc.edu",
        eligibility="Fox Valley adults age 18+; free HSE classes; orientation required.",
        eligibility_es="Adultos del Valle Fox de 18+ años; clases HSE gratuitas; se requiere orientación.",
        notes="Call 920-735-5645; pairs with Freedom House and Job Center Appleton.",
        notes_es="Llame al 920-735-5645; se vincula con Freedom House y Job Center Appleton.",
        hours="Class schedules vary",
        tags="appleton|outagamie|education|GED|ESL|reentry",
        services="GED preparation|High School Equivalency|English language classes|Workforce credentials|Career referrals",
        county="Outagamie", served_counties="Outagamie|Winnebago|Calumet|Waupaca", coverage="multi",
        _source="https://www.fvtc.edu", _source_type="nonprofit", _confidence="high",
    )

    # --- peer support ---
    add(
        name="NAMI Wisconsin — Peer Support & Education",
        category="peer-support", region="Statewide",
        description="NAMI Wisconsin provides peer-led support groups, family education, and mental health advocacy for Wisconsinites with mental illness and their families including justice-involved individuals and families navigating reentry. Peer support groups are free and confidential—not clinical treatment or crisis response; call 988 for immediate crisis.",
        description_es="NAMI Wisconsin ofrece grupos de apoyo liderados por pares, educación familiar y defensa de salud mental para habitantes de Wisconsin con enfermedades mentales y sus familias incluidas personas con antecedentes penales y familias que navegan la reinserción. Los grupos entre pares son gratuitos y confidenciales; llame al 988 para crisis inmediata.",
        address="4233 Lien Road, Suite 2", city="Madison", phone="800-236-2988", email="",
        website="https://namiwisconsin.org",
        eligibility="Open to Wisconsin residents affected by mental illness including justice-involved individuals and family members.",
        eligibility_es="Abierto a residentes de Wisconsin afectados por enfermedad mental incluidas personas con antecedentes penales y familiares.",
        notes="Call 800-236-2988 for local NAMI affiliate and support group schedules; pairs with county CCS providers.",
        notes_es="Llame al 800-236-2988 para filial NAMI local y horarios de grupos de apoyo; se vincula con proveedores CCS del condado.",
        hours="Support group schedules vary by affiliate",
        tags="statewide|peer-support|NAMI|mental-health|reentry",
        services="Peer support groups|Family education|Mental health advocacy|Support group locator|Recovery resources",
        county="Dane", served_counties="", coverage="statewide",
        _source="https://namiwisconsin.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Wisconsin Peer Specialist Employment Initiative",
        category="peer-support", region="Statewide",
        description="The Wisconsin Peer Specialist Employment Initiative connects certified peer specialists with behavioral health employers statewide, supporting justice-involved individuals in recovery who seek peer specialist certification and employment through Comprehensive Community Services and county mental health agencies. Training and certification navigation—not emergency crisis services.",
        description_es="La Iniciativa de Empleo de Especialistas Entre Pares de Wisconsin conecta especialistas entre pares certificados con empleadores de salud conductual en todo el estado, apoyando a personas con antecedentes penales en recuperación que buscan certificación y empleo como especialista entre pares a través de CCS y agencias de salud mental del condado.",
        address="1 West Wilson Street", city="Madison", phone="608-266-2717", email="",
        website="https://www.dhs.wisconsin.gov/ccs/index.htm",
        eligibility="Wisconsin adults in recovery seeking peer specialist certification; justice-involved applicants welcome in participating counties.",
        eligibility_es="Adultos de Wisconsin en recuperación que buscan certificación de especialista entre pares; solicitantes con antecedentes penales bienvenidos en condados participantes.",
        notes="Contact county CCS or mental health agency for peer specialist training pathways; call 988 for crisis.",
        notes_es="Contacte CCS del condado o agencia de salud mental para vías de capacitación; llame al 988 para crisis.",
        hours="County program hours vary",
        tags="statewide|peer-support|CCS|certification|reentry",
        services="Peer specialist certification navigation|Employment connections|Recovery support|County CCS referrals|Training pathway information",
        county="Dane", served_counties="", coverage="statewide",
        _source="https://www.dhs.wisconsin.gov/ccs/index.htm", _source_type="government", _confidence="high",
    )
