"""Phase 4 program-level expansion entries for Wisconsin reentry resources."""


def register_phase4(add):
    # --- housing ---
    add(
        name="Salvation Army — Milwaukee Emergency Lodge",
        category="housing", region="Milwaukee / Milwaukee County",
        description="The Salvation Army Emergency Lodge in Milwaukee provides emergency shelter, meals, and case management for men, women, and families experiencing homelessness in Milwaukee County including returning citizens with nowhere else to go after release from WDOC custody or Milwaukee County Jail. Case managers connect residents to Job Center of Wisconsin, ACCESS Wisconsin benefits, and permanent housing programs.",
        description_es="El Emergency Lodge del Ejército de Salvación en Milwaukee proporciona refugio de emergencia, comidas y manejo de casos para hombres, mujeres y familias sin hogar en el condado Milwaukee incluidos ciudadanos que regresan sin otro lugar adonde ir después de la liberación.",
        address="915 North 16th Street", city="Milwaukee", phone="414-271-7933", email="",
        website="https://centralusa.salvationarmy.org/milwaukee",
        eligibility="Men, women, and families experiencing homelessness in Milwaukee; walk in or call for intake assessment.",
        eligibility_es="Hombres, mujeres y familias sin hogar en Milwaukee; ingrese sin cita o llame para evaluación de admisión.",
        notes="Call 414-271-7933 for shelter intake; case management connects to Job Center and ACCESS Wisconsin.",
        notes_es="Llame al 414-271-7933 para admisión al refugio; el manejo de casos conecta con Job Center y ACCESS Wisconsin.",
        hours="Shelter 24/7; intake during business hours",
        tags="milwaukee|housing|emergency-shelter|families|reentry",
        services="Emergency shelter|Meals|Case management|Employment referrals|Benefits navigation",
        county="Milwaukee", served_counties="Milwaukee", coverage="single",
        _source="https://centralusa.salvationarmy.org/milwaukee", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="The Road Home Dane County — Supportive Housing",
        category="housing", region="Madison / Dane County",
        description="The Road Home Dane County provides family shelter, rapid rehousing, and permanent supportive housing for low-income Dane County households including returning citizens establishing stable tenancy after incarceration. Housing specialists coordinate with JustDane, ACCESS Wisconsin, and Job Center of Wisconsin Madison for whole-person reentry support.",
        description_es="The Road Home Dane County ofrece refugio familiar, realojamiento rápido y vivienda de apoyo permanente para hogares de bajos ingresos del condado Dane incluidos ciudadanos que regresan que establecen arrendamiento estable después de la encarcelación.",
        address="1202 Williamson Street, Suite 102", city="Madison", phone="608-294-7999", email="",
        website="https://www.theroadhomedc.org",
        eligibility="Low-income Dane County families facing housing instability; justice-involved adults may qualify for rapid rehousing.",
        eligibility_es="Familias de bajos ingresos del condado Dane que enfrentan inestabilidad de vivienda; adultos con antecedentes penales pueden calificar para realojamiento rápido.",
        notes="Call 608-294-7999 for housing intake; not a walk-in men's emergency shelter.",
        notes_es="Llame al 608-294-7999 para admisión de vivienda; no es refugio de emergencia para hombres sin cita.",
        hours="Monday–Friday business hours",
        tags="madison|dane|housing|rapid-rehousing|families|reentry",
        services="Family shelter|Rapid rehousing|Permanent supportive housing|Case management|Benefits navigation",
        county="Dane", served_counties="Dane", coverage="single",
        _source="https://www.theroadhomedc.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Freedom House — Appleton Transitional Housing",
        category="housing", region="Appleton / Outagamie County",
        description="Freedom House provides transitional housing and case management for homeless families in the Fox Valley including justice-involved parents reunifying with children after release from WDOC custody or Outagamie County Jail. Case managers connect residents to Job Center of Wisconsin Appleton, ACCESS Wisconsin, and Second Harvest Foodbank.",
        description_es="Freedom House ofrece vivienda transicional y manejo de casos para familias sin hogar en el Valle Fox incluidos padres con antecedentes penales que se reunifican con sus hijos después de la liberación de custodia WDOC o la cárcel del condado Outagamie.",
        address="102 East Hancock Street", city="Appleton", phone="920-734-9192", email="",
        website="https://www.freedomhousewi.org",
        eligibility="Homeless families in the Fox Valley; justice-involved parents may qualify per program screening.",
        eligibility_es="Familias sin hogar en el Valle Fox; padres con antecedentes penales pueden calificar según evaluación del programa.",
        notes="Call 920-734-9192 for intake; pairs with Job Center Appleton and Second Harvest Foodbank.",
        notes_es="Llame al 920-734-9192 para admisión; se vincula con Job Center Appleton y Second Harvest Foodbank.",
        hours="Contact for intake hours",
        tags="appleton|outagamie|housing|transitional|families|reentry",
        services="Transitional housing|Case management|Family reunification support|Benefits navigation|Employment referrals",
        county="Outagamie", served_counties="Outagamie|Winnebago|Calumet", coverage="multi",
        _source="https://www.freedomhousewi.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Couleecap — La Crosse Housing Programs",
        category="housing", region="La Crosse / La Crosse County",
        description="Couleecap administers emergency shelter referrals, rapid rehousing, and homeless prevention programs for low-income La Crosse County households including returning citizens from WDOC release. Housing navigators connect clients to Job Center of Wisconsin La Crosse, ACCESS Wisconsin, and regional behavioral health providers.",
        description_es="Couleecap administra referencias de refugio de emergencia, realojamiento rápido y programas de prevención de falta de vivienda para hogares de bajos ingresos del condado La Crosse incluidos ciudadanos que regresan de liberación WDOC.",
        address="201 Melby Street", city="Westby", phone="608-634-3104", email="",
        website="https://www.couleecap.org",
        eligibility="Low-income La Crosse County residents facing housing instability; justice-involved adults may qualify for prevention and rehousing.",
        eligibility_es="Residentes de bajos ingresos del condado La Crosse que enfrentan inestabilidad de vivienda; adultos con antecedentes penales pueden calificar.",
        notes="Call 608-634-3104 for housing program information; La Crosse office also serves county residents.",
        notes_es="Llame al 608-634-3104 para información del programa de vivienda; la oficina de La Crosse también sirve residentes del condado.",
        hours="Monday–Friday business hours",
        tags="la-crosse|housing|rapid-rehousing|homeless-prevention|reentry",
        services="Emergency shelter referrals|Rapid rehousing|Homeless prevention|Case management|Benefits navigation",
        county="La Crosse", served_counties="La Crosse|Vernon|Monroe|Crawford", coverage="multi",
        _source="https://www.couleecap.org", _source_type="nonprofit", _confidence="high",
    )

    # --- employment ---
    add(
        name="WRTP/BIG STEP — Milwaukee Construction Training",
        category="employment", region="Milwaukee / Milwaukee County",
        description="WRTP/BIG STEP provides pre-apprenticeship construction training, industry certifications, and employer connections for Milwaukee adults including justice-involved individuals seeking skilled trades careers in carpentry, electrical, plumbing, and HVAC. Graduates connect to union apprenticeship programs and fair-chance employers through Job Center of Wisconsin Milwaukee.",
        description_es="WRTP/BIG STEP ofrece capacitación pre-aprendiz en construcción, certificaciones industriales y conexiones con empleadores para adultos de Milwaukee incluidas personas con antecedentes penales que buscan carreras en oficios calificados en carpintería, electricidad, plomería y HVAC.",
        address="3841 West Wisconsin Avenue", city="Milwaukee", phone="414-385-6920", email="",
        website="https://www.wrtp.org",
        eligibility="Milwaukee-area adults seeking construction careers; justice-involved participants welcome per program policy.",
        eligibility_es="Adultos del área de Milwaukee que buscan carreras en construcción; participantes con antecedentes penales bienvenidos según política del programa.",
        notes="Call 414-385-6920; located at Milwaukee Job Center campus; pairs with Wisconsin Community Services.",
        notes_es="Llame al 414-385-6920; ubicado en el campus Job Center de Milwaukee; se vincula con Wisconsin Community Services.",
        hours="Training program hours vary; call for enrollment",
        tags="milwaukee|employment|construction|pre-apprenticeship|reentry",
        services="Pre-apprenticeship training|Industry certifications|Employer connections|Career coaching|Fair-chance employment",
        county="Milwaukee", served_counties="Milwaukee|Waukesha|Washington|Ozaukee", coverage="multi",
        _source="https://www.wrtp.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Job Center of Wisconsin — Kenosha",
        category="employment", region="Kenosha / Kenosha County",
        description="The Kenosha Job Center connects Kenosha and Racine county job seekers including justice-involved adults to WIOA-funded training, resume assistance, and fair-chance employment navigation. Staff coordinate with HALO Inc, Hope Center Racine, and WDOC Region 2 field offices for reentry stabilization.",
        description_es="El Job Center de Kenosha conecta buscadores de empleo de los condados Kenosha y Racine incluidos adultos con antecedentes penales con capacitación WIOA y navegación de empleo de segunda oportunidad.",
        address="8600 Sheridan Road, Suite 100", city="Kenosha", phone="262-697-4500", email="",
        website="https://www.wisconsinjobcenter.org",
        eligibility="Open to Kenosha and Racine county job seekers including justice-involved individuals.",
        eligibility_es="Abierto a buscadores de empleo de los condados Kenosha y Racine incluidas personas con antecedentes penales.",
        notes="Register at wisconsinjobcenter.org; call 262-697-4500; pairs with HALO Inc and Hope Center Racine.",
        notes_es="Regístrese en wisconsinjobcenter.org; llame al 262-697-4500; se vincula con HALO Inc y Hope Center Racine.",
        hours="Monday–Friday business hours",
        tags="kenosha|racine|employment|job-center|WIOA|reentry",
        services="Job search assistance|Resume coaching|WIOA referrals|Fair-chance employment|Career coaching",
        county="Kenosha", served_counties="Kenosha|Racine", coverage="multi",
        _source="https://www.wisconsinjobcenter.org", _source_type="government", _confidence="high",
    )
    add(
        name="Job Center of Wisconsin — La Crosse",
        category="employment", region="La Crosse / La Crosse County",
        description="The La Crosse Job Center connects western Wisconsin job seekers including justice-involved adults to WIOA training, resume assistance, and fair-chance employer navigation. Staff link returning citizens to Couleecap housing programs and county DHS benefits offices.",
        description_es="El Job Center de La Crosse conecta buscadores de empleo del oeste de Wisconsin incluidos adultos con antecedentes penales con capacitación WIOA y navegación de empleo de segunda oportunidad.",
        address="300 North 4th Street", city="La Crosse", phone="608-789-5620", email="",
        website="https://www.wisconsinjobcenter.org",
        eligibility="Open to La Crosse County and western Wisconsin job seekers including justice-involved individuals.",
        eligibility_es="Abierto a buscadores de empleo del condado La Crosse y oeste de Wisconsin incluidas personas con antecedentes penales.",
        notes="Register at wisconsinjobcenter.org; call 608-789-5620; pairs with Couleecap and WDOC Region 6.",
        notes_es="Regístrese en wisconsinjobcenter.org; llame al 608-789-5620; se vincula con Couleecap y WDOC Región 6.",
        hours="Monday–Friday business hours",
        tags="la-crosse|employment|job-center|WIOA|reentry",
        services="Job search assistance|Resume coaching|WIOA referrals|Fair-chance employment|Career workshops",
        county="La Crosse", served_counties="La Crosse|Vernon|Monroe|Buffalo", coverage="multi",
        _source="https://www.wisconsinjobcenter.org", _source_type="government", _confidence="high",
    )
    add(
        name="Job Center of Wisconsin — Eau Claire",
        category="employment", region="Eau Claire / Eau Claire County",
        description="The Eau Claire Job Center connects northwest Wisconsin job seekers including justice-involved adults to WIOA-funded training, resume assistance, and fair-chance employment navigation. Staff coordinate with county DHS offices and regional treatment providers for reentry stabilization.",
        description_es="El Job Center de Eau Claire conecta buscadores de empleo del noroeste de Wisconsin incluidos adultos con antecedentes penales con capacitación WIOA y navegación de empleo de segunda oportunidad.",
        address="221 West Madison Street", city="Eau Claire", phone="715-831-9600", email="",
        website="https://www.wisconsinjobcenter.org",
        eligibility="Open to Eau Claire County and northwest Wisconsin job seekers including justice-involved individuals.",
        eligibility_es="Abierto a buscadores de empleo del condado Eau Claire y noroeste de Wisconsin incluidas personas con antecedentes penales.",
        notes="Register at wisconsinjobcenter.org; call 715-831-9600; serves multiple northwest Wisconsin counties.",
        notes_es="Regístrese en wisconsinjobcenter.org; llame al 715-831-9600; sirve múltiples condados del noroeste de Wisconsin.",
        hours="Monday–Friday business hours",
        tags="eau-claire|employment|job-center|WIOA|reentry",
        services="Job search assistance|Resume coaching|WIOA referrals|Fair-chance employment|Career coaching",
        county="Eau Claire", served_counties="Eau Claire|Chippewa|Barron|Dunn|Clark", coverage="multi",
        _source="https://www.wisconsinjobcenter.org", _source_type="government", _confidence="high",
    )

    # --- substance use / healthcare ---
    add(
        name="Rogers Behavioral Health — Milwaukee",
        category="substance-use-treatment", region="Milwaukee / Milwaukee County",
        description="Rogers Behavioral Health provides outpatient and residential substance use disorder and mental health treatment including MAT and dual-diagnosis programming for Milwaukee County adults including justice-involved individuals referred by WDOC, courts, or self-referral. Accepts BadgerCare Plus and offers financial assistance for uninsured patients.",
        description_es="Rogers Behavioral Health ofrece tratamiento ambulatorio y residencial de trastornos por uso de sustancias y salud mental incluida programación TMO y doble diagnóstico para adultos del condado Milwaukee incluidas personas con antecedentes penales referidas por WDOC o tribunales.",
        address="11101 West Lincoln Avenue", city="West Allis", phone="800-767-4411", email="",
        website="https://rogersbh.org",
        eligibility="Milwaukee-area adults seeking SUD or mental health treatment; justice-involved clients welcome; insurance and sliding-fee options.",
        eligibility_es="Adultos del área de Milwaukee que buscan tratamiento de TUS o salud mental; clientes con antecedentes penales bienvenidos; opciones de seguro y tarifa móvil.",
        notes="Call 800-767-4411 for intake; multiple Wisconsin locations; ask about court and DOC referral pathways.",
        notes_es="Llame al 800-767-4411 para admisión; múltiples ubicaciones en Wisconsin; pregunte sobre vías de referencia judicial y DOC.",
        hours="Intake Monday–Friday; crisis line available",
        tags="milwaukee|substance-use|mental-health|MAT|reentry",
        services="Outpatient SUD treatment|Residential treatment|MAT|Dual-diagnosis care|Financial assistance",
        county="Milwaukee", served_counties="Milwaukee|Waukesha|Washington|Ozaukee", coverage="multi",
        _source="https://rogersbh.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Tellurian — Madison Behavioral Health",
        category="substance-use-treatment", region="Madison / Dane County",
        description="Tellurian provides outpatient substance use disorder treatment, mental health services, and crisis stabilization for Dane County adults including justice-involved individuals under WDOC supervision or drug court referral. Sliding-fee and BadgerCare Plus billing support continuity of care after release.",
        description_es="Tellurian ofrece tratamiento ambulatorio de trastornos por uso de sustancias, servicios de salud mental y estabilización en crisis para adultos del condado Dane incluidas personas con antecedentes penales bajo supervisión WDOC o referencia de tribunal de drogas.",
        address="2914 Industrial Drive", city="Madison", phone="608-222-7311", email="",
        website="https://www.tellurian.org",
        eligibility="Dane County residents seeking mental health or SUD services; Medicaid and sliding-fee accepted; justice-involved clients welcome.",
        eligibility_es="Residentes del condado Dane que buscan servicios de salud mental o TUS; se aceptan Medicaid y tarifa móvil; clientes con antecedentes penales bienvenidos.",
        notes="Call 608-222-7311 for intake; pairs with JustDane and Dane County CCS providers.",
        notes_es="Llame al 608-222-7311 para admisión; se vincula con JustDane y proveedores CCS del condado Dane.",
        hours="Monday–Friday clinic hours",
        tags="madison|dane|substance-use|mental-health|reentry",
        services="Outpatient SUD treatment|Mental health counseling|Crisis stabilization|Drug court referrals|Sliding-fee enrollment",
        county="Dane", served_counties="Dane", coverage="single",
        _source="https://www.tellurian.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Libertas Treatment Center — Green Bay",
        category="substance-use-treatment", region="Green Bay / Brown County",
        description="Libertas Treatment Center provides outpatient substance use disorder treatment including MAT and group counseling for Brown County and northeast Wisconsin adults including justice-involved individuals referred by WDOC or self-referral. Accepts BadgerCare Plus and offers sliding-fee services for uninsured patients.",
        description_es="Libertas Treatment Center ofrece tratamiento ambulatorio de trastornos por uso de sustancias incluida TMO y consejería grupal para adultos del condado Brown y noreste de Wisconsin incluidas personas con antecedentes penales referidas por WDOC o autorreferencia.",
        address="515 S Monroe Avenue", city="Green Bay", phone="920-498-8600", email="",
        website="https://www.libertastreatment.org",
        eligibility="Brown County and northeast Wisconsin adults seeking SUD treatment; justice-involved clients welcome per intake.",
        eligibility_es="Adultos del condado Brown y noreste de Wisconsin que buscan tratamiento de TUS; clientes con antecedentes penales bienvenidos según admisión.",
        notes="Call 920-498-8600 for intake; pairs with NEW Community Shelter and Job Center Green Bay.",
        notes_es="Llame al 920-498-8600 para admisión; se vincula con NEW Community Shelter y Job Center Green Bay.",
        hours="Monday–Friday clinic hours",
        tags="green-bay|brown|substance-use|MAT|reentry",
        services="Outpatient SUD treatment|MAT|Group counseling|Individual counseling|Sliding-fee services",
        county="Brown", served_counties="Brown|Outagamie|Winnebago|Kewaunee", coverage="multi",
        _source="https://www.libertastreatment.org", _source_type="nonprofit", _confidence="high",
    )

    # --- legal ---
    add(
        name="Legal Action of Wisconsin — Milwaukee Office",
        category="legal-aid", region="Milwaukee / Milwaukee County",
        description="The Legal Action of Wisconsin Milwaukee office provides civil legal representation for low-income Milwaukee County residents including housing, public benefits, family law, and expungement matters for justice-involved adults. Does not handle criminal defense—contact centralized intake at 888-278-0633 for eligibility screening.",
        description_es="La oficina de Legal Action of Wisconsin en Milwaukee ofrece representación legal civil para residentes de bajos ingresos del condado Milwaukee incluyendo vivienda, beneficios, derecho familiar y asuntos de expungación para adultos con antecedentes penales. No maneja defensa penal.",
        address="230 West Wells Street, Suite 800", city="Milwaukee", phone="888-278-0633", email="",
        website="https://www.legalaction.org",
        eligibility="Low-income Milwaukee County residents with non-criminal legal problems; LSC income limits apply.",
        eligibility_es="Residentes de bajos ingresos del condado Milwaukee con problemas legales no penales; aplican límites de ingresos LSC.",
        notes="Call 888-278-0633 for intake; expungement and housing legal aid available for eligible clients.",
        notes_es="Llame al 888-278-0633 para admisión; asistencia legal de vivienda y expungación disponible para clientes elegibles.",
        hours="Intake Monday–Friday business hours",
        tags="milwaukee|legal-aid|expungement|housing|reentry",
        services="Civil legal representation|Expungement assistance|Housing legal aid|Benefits advocacy|Eviction defense",
        county="Milwaukee", served_counties="Milwaukee", coverage="single",
        _source="https://www.legalaction.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Legal Action of Wisconsin — Madison Office",
        category="legal-aid", region="Madison / Dane County",
        description="The Legal Action of Wisconsin Madison office serves low-income Dane County residents with civil legal aid including housing, benefits, family law, and record relief for justice-involved adults rebuilding legal stability after release. Not criminal defense—call 888-278-0633 for statewide intake routing.",
        description_es="La oficina de Legal Action of Wisconsin en Madison sirve a residentes de bajos ingresos del condado Dane con asistencia legal civil incluyendo vivienda, beneficios, derecho familiar y alivio de antecedentes para adultos con antecedentes penales. No es defensa penal.",
        address="744 Williamson Street", city="Madison", phone="888-278-0633", email="",
        website="https://www.legalaction.org",
        eligibility="Low-income Dane County residents with non-criminal legal problems; LSC income limits apply.",
        eligibility_es="Residentes de bajos ingresos del condado Dane con problemas legales no penales; aplican límites de ingresos LSC.",
        notes="Call 888-278-0633; pairs with JustDane and Dane County DHS for benefits appeals.",
        notes_es="Llame al 888-278-0633; se vincula con JustDane y DHS del condado Dane para apelaciones de beneficios.",
        hours="Intake Monday–Friday business hours",
        tags="madison|dane|legal-aid|expungement|reentry",
        services="Civil legal representation|Expungement assistance|Housing legal aid|Benefits advocacy|Family law assistance",
        county="Dane", served_counties="Dane", coverage="single",
        _source="https://www.legalaction.org", _source_type="nonprofit", _confidence="high",
    )

    # --- veterans ---
    add(
        name="Dryhootch of America — Milwaukee Veterans Peer Support",
        category="veterans", region="Milwaukee / Milwaukee County",
        description="Dryhootch of America provides peer support, coffeehouse community space, and reentry navigation for justice-involved veterans in the Milwaukee area connecting participants to WDVA county veterans service officers, VA health care enrollment, and veterans treatment court supports. Veteran-led peer services—not emergency shelter or cash assistance.",
        description_es="Dryhootch of America ofrece apoyo entre pares, espacio comunitario tipo cafetería y navegación de reinserción para veteranos con antecedentes penales en el área de Milwaukee conectando participantes con oficiales de servicios para veteranos del condado WDVA e inscripción en atención médica del VA.",
        address="1030 East Brady Street", city="Milwaukee", phone="414-763-2949", email="",
        website="https://www.dryhootch.org",
        eligibility="Military veterans including justice-involved veterans in the Milwaukee area; no discharge status restrictions stated for peer support.",
        eligibility_es="Veteranos militares incluidos veteranos con antecedentes penales en el área de Milwaukee; sin restricciones de estatus de baja indicadas para apoyo entre pares.",
        notes="Call 414-763-2949; veteran peer support; pairs with WDVA and Wisconsin Community Services.",
        notes_es="Llame al 414-763-2949; apoyo entre pares de veteranos; se vincula con WDVA y Wisconsin Community Services.",
        hours="Coffeehouse hours vary; call ahead",
        tags="milwaukee|veterans|peer-support|reentry|justice-involved-veterans",
        services="Veteran peer support|Reentry navigation|VA benefits referrals|Community coffeehouse|Treatment court support",
        county="Milwaukee", served_counties="Milwaukee|Waukesha|Washington|Ozaukee", coverage="multi",
        _source="https://www.dryhootch.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Veterans Outreach of Wisconsin — Racine/Kenosha",
        category="veterans", region="Racine / Racine County",
        description="Veterans Outreach of Wisconsin provides transitional housing, case management, and peer support for homeless and at-risk veterans in Racine and Kenosha counties including justice-involved veterans released from incarceration. Staff connect residents to WDVA benefits claims assistance, VA health care, and Job Center of Wisconsin Kenosha.",
        description_es="Veterans Outreach of Wisconsin ofrece vivienda transicional, manejo de casos y apoyo entre pares para veteranos sin hogar y en riesgo en los condados Racine y Kenosha incluidos veteranos con antecedentes penales liberados de la encarcelación.",
        address="1301 17th Street", city="Racine", phone="262-633-3278", email="",
        website="https://www.veteransoutreachofwi.org",
        eligibility="Homeless or at-risk veterans in Racine and Kenosha counties; justice-involved veterans welcome per intake.",
        eligibility_es="Veteranos sin hogar o en riesgo en los condados Racine y Kenosha; veteranos con antecedentes penales bienvenidos según admisión.",
        notes="Call 262-633-3278 for intake; pairs with HALO Kenosha and WDVA county VSO.",
        notes_es="Llame al 262-633-3278 para admisión; se vincula con HALO Kenosha y VSO del condado WDVA.",
        hours="Monday–Friday business hours",
        tags="racine|kenosha|veterans|transitional-housing|reentry",
        services="Transitional veteran housing|Case management|Peer support|VA benefits navigation|Employment referrals",
        county="Racine", served_counties="Racine|Kenosha", coverage="multi",
        _source="https://www.veteransoutreachofwi.org", _source_type="nonprofit", _confidence="high",
    )

    # --- basic needs ---
    add(
        name="Feeding America Eastern Wisconsin — Milwaukee",
        category="food-nutrition", region="Milwaukee / Milwaukee County",
        description="Feeding America Eastern Wisconsin distributes food through partner pantries and meal programs across eastern Wisconsin including Milwaukee County, serving returning citizens and low-income households reestablishing food security after release from WDOC custody or county jails. Pantry locator online—not a walk-in central warehouse for individuals.",
        description_es="Feeding America Eastern Wisconsin distribuye alimentos a través de despensas aliadas y programas de comidas en el este de Wisconsin incluido el condado Milwaukee, sirviendo a ciudadanos que regresan y hogares de bajos ingresos que restablecen seguridad alimentaria después de la liberación.",
        address="3200 North 36th Street", city="Milwaukee", phone="920-973-1709", email="",
        website="https://feedingamericawi.org",
        eligibility="Open to partner pantries serving low-income Milwaukee and eastern Wisconsin residents; no criminal-record restrictions at partner sites.",
        eligibility_es="Abierto a despensas aliadas que sirven a residentes de bajos ingresos de Milwaukee y el este de Wisconsin; sin restricciones de antecedentes en sitios aliados.",
        notes="Use feedingamericawi.org pantry locator; pairs with ACCESS Wisconsin FoodShare and Community Advocates.",
        notes_es="Use el localizador de despensas en feedingamericawi.org; se vincula con FoodShare ACCESS Wisconsin y Community Advocates.",
        hours="Partner pantry hours vary; check locator",
        tags="milwaukee|food-nutrition|food-bank|eastern-wisconsin|reentry",
        services="Food pantry network|Mobile food distribution|Partner agency food supply|Pantry locator|Nutrition program support",
        county="Milwaukee", served_counties="Milwaukee|Waukesha|Washington|Ozaukee|Racine|Kenosha", coverage="multi",
        _source="https://feedingamericawi.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Second Harvest Foodbank — Madison Region",
        category="food-nutrition", region="Madison / Dane County",
        description="Second Harvest Foodbank of Southern Wisconsin supplies partner food pantries and meal sites across Dane County and south-central Wisconsin, helping returning citizens and low-income households access emergency food while FoodShare applications process through ACCESS Wisconsin. Use the online pantry finder—not a direct walk-in distribution center for individuals.",
        description_es="Second Harvest Foodbank of Southern Wisconsin abastece despensas aliadas y sitios de comidas en el condado Dane y el centro-sur de Wisconsin, ayudando a ciudadanos que regresan y hogares de bajos ingresos a acceder a alimentos de emergencia mientras se procesan solicitudes FoodShare a través de ACCESS Wisconsin.",
        address="702 Signal Point Road", city="Madison", phone="608-216-7200", email="",
        website="https://www.secondharvestmadison.org",
        eligibility="Partner pantries serve low-income south-central Wisconsin residents; no criminal-record restrictions at partner sites.",
        eligibility_es="Las despensas aliadas sirven a residentes de bajos ingresos del centro-sur de Wisconsin; sin restricciones de antecedentes en sitios aliados.",
        notes="Use secondharvestmadison.org pantry finder; pairs with JustDane and Dane County DHS FoodShare.",
        notes_es="Use el buscador de despensas en secondharvestmadison.org; se vincula con JustDane y FoodShare DHS del condado Dane.",
        hours="Partner pantry hours vary; check finder",
        tags="madison|dane|food-nutrition|food-bank|reentry",
        services="Food pantry network|Mobile pantry distribution|Partner agency supply|Pantry finder|Nutrition education",
        county="Dane", served_counties="Dane|Rock|Green|Iowa|Lafayette|Grant", coverage="multi",
        _source="https://www.secondharvestmadison.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Paul's Pantry — Green Bay",
        category="food-nutrition", region="Green Bay / Brown County",
        description="Paul's Pantry provides free grocery assistance to low-income Green Bay and Brown County households including returning citizens establishing food security after release. Clients may shop monthly for fresh and shelf-stable foods while coordinating FoodShare enrollment through ACCESS Wisconsin and county DHS offices.",
        description_es="Paul's Pantry ofrece asistencia gratuita de comestibles a hogares de bajos ingresos de Green Bay y el condado Brown incluidos ciudadanos que regresan que establecen seguridad alimentaria después de la liberación. Los clientes pueden comprar mensualmente alimentos frescos y no perecederos.",
        address="1520 Leo Frigo Way", city="Green Bay", phone="920-435-6900", email="",
        website="https://www.paulspantry.org",
        eligibility="Low-income Brown County households meeting pantry income guidelines; justice-involved clients welcome.",
        eligibility_es="Hogares de bajos ingresos del condado Brown que cumplan pautas de ingresos de la despensa; clientes con antecedentes penales bienvenidos.",
        notes="Call 920-435-6900 for hours and registration; pairs with NEW Community Shelter and Job Center Green Bay.",
        notes_es="Llame al 920-435-6900 para horario e inscripción; se vincula con NEW Community Shelter y Job Center Green Bay.",
        hours="Pantry distribution hours posted weekly; call ahead",
        tags="green-bay|brown|food-nutrition|pantry|reentry",
        services="Free grocery assistance|Fresh food distribution|FoodShare enrollment referrals|Monthly shopping program",
        county="Brown", served_counties="Brown", coverage="single",
        _source="https://www.paulspantry.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Western Wisconsin Community Action Agency — Eau Claire",
        category="basic-needs", region="Eau Claire / Eau Claire County",
        description="Western Wisconsin Community Action Agency provides emergency assistance, energy assistance, and basic-needs navigation for low-income Eau Claire County households including returning citizens from WDOC release. Case managers connect clients to Job Center of Wisconsin Eau Claire, ACCESS Wisconsin benefits, and regional housing partners.",
        description_es="Western Wisconsin Community Action Agency ofrece asistencia de emergencia, asistencia energética y navegación de necesidades básicas para hogares de bajos ingresos del condado Eau Claire incluidos ciudadanos que regresan de liberación WDOC.",
        address="525 Second Avenue", city="Eau Claire", phone="715-836-7511", email="",
        website="https://www.wwca.org",
        eligibility="Low-income western Wisconsin residents; justice-involved adults may qualify for emergency and energy assistance.",
        eligibility_es="Residentes de bajos ingresos del oeste de Wisconsin; adultos con antecedentes penales pueden calificar para asistencia de emergencia y energética.",
        notes="Call 715-836-7511 for program intake; serves multiple western Wisconsin counties from Eau Claire office.",
        notes_es="Llame al 715-836-7511 para admisión al programa; sirve múltiples condados del oeste de Wisconsin desde la oficina de Eau Claire.",
        hours="Monday–Friday business hours",
        tags="eau-claire|basic-needs|energy-assistance|emergency-aid|reentry",
        services="Emergency assistance|Energy assistance|Basic-needs navigation|Benefits referrals|Employment referrals",
        county="Eau Claire", served_counties="Eau Claire|Chippewa|Barron|Dunn|Clark|Jackson", coverage="multi",
        _source="https://www.wwca.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Catholic Charities — La Crosse Basic Needs",
        category="basic-needs", region="La Crosse / La Crosse County",
        description="Catholic Charities of the Diocese of La Crosse provides emergency financial assistance, food pantry referrals, and case management for low-income La Crosse County households including returning citizens stabilizing after release from WDOC custody or county jail. Staff coordinate with Couleecap housing programs and Job Center La Crosse.",
        description_es="Catholic Charities de la Diócesis de La Crosse ofrece asistencia financiera de emergencia, referencias de despensa de alimentos y manejo de casos para hogares de bajos ingresos del condado La Crosse incluidos ciudadanos que estabilizan después de la liberación de custodia WDOC o cárcel del condado.",
        address="3710 East Avenue South", city="La Crosse", phone="608-782-0710", email="",
        website="https://www.cclse.org",
        eligibility="Low-income La Crosse County residents facing basic-needs crises; justice-involved adults may qualify for emergency assistance.",
        eligibility_es="Residentes de bajos ingresos del condado La Crosse que enfrentan crisis de necesidades básicas; adultos con antecedentes penales pueden calificar.",
        notes="Call 608-782-0710 for intake; not a walk-in emergency shelter.",
        notes_es="Llame al 608-782-0710 para admisión; no es refugio de emergencia sin cita.",
        hours="Monday–Friday business hours",
        tags="la-crosse|basic-needs|emergency-assistance|reentry",
        services="Emergency financial assistance|Food pantry referrals|Case management|Benefits navigation|Housing referrals",
        county="La Crosse", served_counties="La Crosse|Vernon|Monroe", coverage="multi",
        _source="https://www.cclse.org", _source_type="nonprofit", _confidence="high",
    )
    add(
        name="Appleton Health Department — Outreach Clinic",
        category="healthcare", region="Appleton / Outagamie County",
        description="Appleton Health Department outreach programs connect uninsured and BadgerCare Plus patients in Outagamie County to primary care, immunizations, and health navigation including justice-involved adults reestablishing medical care after release. Coordinates with regional FQHCs and ForwardHealth enrollment—not a full-service hospital emergency department.",
        description_es="Los programas de alcance del Departamento de Salud de Appleton conectan a pacientes sin seguro y BadgerCare Plus en el condado Outagamie con atención primaria, inmunizaciones y navegación de salud incluidos adultos con antecedentes penales que restablecen atención médica después de la liberación.",
        address="100 North Appleton Street", city="Appleton", phone="920-832-6423", email="",
        website="https://www.appletonwi.gov/government/departments/health",
        eligibility="Outagamie County residents; sliding-fee and BadgerCare Plus patients welcome including justice-involved adults.",
        eligibility_es="Residentes del condado Outagamie; pacientes con tarifa móvil y BadgerCare Plus bienvenidos incluidos adultos con antecedentes penales.",
        notes="Call 920-832-6423 for clinic schedule; pairs with Freedom House and Job Center Appleton.",
        notes_es="Llame al 920-832-6423 para horario de clínica; se vincula con Freedom House y Job Center Appleton.",
        hours="Clinic hours vary; call for schedule",
        tags="appleton|outagamie|healthcare|primary-care|reentry",
        services="Primary care outreach|Immunizations|Health navigation|BadgerCare Plus referrals|Community health education",
        county="Outagamie", served_counties="Outagamie|Calumet|Winnebago", coverage="multi",
        _source="https://www.appletonwi.gov/government/departments/health", _source_type="government", _confidence="high",
    )
    add(
        name="Job Center of Wisconsin — Appleton",
        category="employment", region="Appleton / Outagamie County",
        description="The Appleton Job Center connects Fox Valley job seekers including justice-involved adults to WIOA training, resume assistance, and fair-chance employment navigation at the Menasha workforce hub. Staff coordinate with Freedom House, Libertas Treatment Center Green Bay, and Outagamie County DHS.",
        description_es="El Job Center de Appleton conecta buscadores de empleo del Valle Fox incluidos adultos con antecedentes penales con capacitación WIOA y navegación de empleo de segunda oportunidad en el centro de fuerza laboral de Menasha.",
        address="1800 Appleton Road", city="Menasha", phone="920-720-5600", email="",
        website="https://www.wisconsinjobcenter.org",
        eligibility="Open to Outagamie, Winnebago, and Calumet county job seekers including justice-involved individuals.",
        eligibility_es="Abierto a buscadores de empleo de los condados Outagamie, Winnebago y Calumet incluidas personas con antecedentes penales.",
        notes="Register at wisconsinjobcenter.org; call 920-720-5600; Menasha location serves Fox Valley.",
        notes_es="Regístrese en wisconsinjobcenter.org; llame al 920-720-5600; la ubicación Menasha sirve al Valle Fox.",
        hours="Monday–Friday business hours",
        tags="appleton|outagamie|employment|job-center|WIOA|reentry",
        services="Job search assistance|Resume coaching|WIOA referrals|Fair-chance employment|Career workshops",
        county="Outagamie", served_counties="Outagamie|Winnebago|Calumet", coverage="multi",
        _source="https://www.wisconsinjobcenter.org", _source_type="government", _confidence="high",
    )
    add(
        name="Racine Vocational Ministry — Reentry Employment",
        category="employment", region="Racine / Racine County",
        description="Racine Vocational Ministry provides faith-based employment coaching, job placement, and mentoring for justice-involved adults returning to Racine County from WDOC custody and county jail. Participants connect to Job Center of Wisconsin Racine, Hope Center Racine, and ACCESS Wisconsin benefits for stabilization—not emergency cash or housing.",
        description_es="Racine Vocational Ministry ofrece coaching laboral basado en la fe, colocación laboral y mentoría para adultos con antecedentes penales que regresan al condado Racine de custodia WDOC y cárcel del condado. Los participantes se conectan con Job Center Racine y beneficios ACCESS Wisconsin.",
        address="510 Seventh Street", city="Racine", phone="262-633-1688", email="",
        website="https://www.racinevocationalministry.org",
        eligibility="Justice-involved adults in Racine County seeking employment support; faith-based program open to all participants.",
        eligibility_es="Adultos con antecedentes penales en el condado Racine que buscan apoyo laboral; programa basado en la fe abierto a todos los participantes.",
        notes="Call 262-633-1688 for enrollment; pairs with Hope Center Racine and WDOC Region 2.",
        notes_es="Llame al 262-633-1688 para inscripción; se vincula con Hope Center Racine y WDOC Región 2.",
        hours="Program hours vary; call for schedule",
        tags="racine|employment|reentry|mentoring|faith-based",
        services="Employment coaching|Job placement|Mentoring|Resume assistance|Benefits navigation",
        county="Racine", served_counties="Racine", coverage="single",
        _source="https://www.racinevocationalministry.org", _source_type="nonprofit", _confidence="high",
    )
